- docs/examples/reserved-capacity-utilization.yaml
N/A
Removes an errant line referring to the `queue_length` metric from the [queue-length-average-value example](https://github.com/awslabs/karpenter/blob/main/docs/examples/queue-length-average-value.yaml) seemingly copied into the overprovisioning example.
> Remove Queue reference from NodeGroup overprovisioning example

- README.md
N/A
Corrects capitalisation of the [TERMS.md link](https://github.com/awslabs/karpenter/blob/main/docs/TERMS.md), the [current link](https://github.com/awslabs/karpenter/blob/main/docs/terms.md) works locally but 404s in Github.
> Capitalise TERMS.md link

- pkg/controllers/metricsproducer/v1alpha1/suite_test.go
- pkg/metrics/producers/reservedcapacity/gauges.go
- pkg/metrics/producers/reservedcapacity/producer.go
- pkg/metrics/producers/reservedcapacity/reservations.go
- pkg/test/objects.go
> Switches to Allocatable from Capacity and makes status quantities more readable.

- pkg/cloudprovider/fake/errors.go
- pkg/cloudprovider/fake/factory.go
- pkg/cloudprovider/fake/nodegroup.go
- pkg/controllers/horizontalautoscaler/v1alpha1/suite_test.go
- pkg/controllers/scalablenodegroup/v1alpha1/suite_test.go
Add unit test for scalable node group controller
> Add unit test for scalable node group controller

- hack/quick-install.sh
Issues here require resolving as independent to #184.
File https://raw.githubusercontent.com/awslabs/karpenter/v0.1.1/hack/quick-install.sh contains two issues to be addressed:
**Install:**
Command `helm upgrade --install karpenter charts/karpenter` fails.
PR updates command to read `helm upgrade --install karpenter karpenter/karpenter`.
**Uninstall:**
Current order of operation leaves deployment: `karpenter` and statefulset: `prometheus-karpenter-monitor` remaining:
```
delete() {
helm delete cert-manager --namespace cert-manager || true
helm delete kube-prometheus-stack --namespace monitoring || true
helm delete karpenter || true
```
PR changes order to move karpenter deletion to occur prior to removal of dependencies:
```
delete() { …
```
> Multiple updates in hack/quick-install.sh

- docs/DEVELOPER_GUIDE.md
Seemed a bit too trivial to warrant an issue
The developer guide hadn't been updated after some of the `make` commands changed name. Also corrected an environment variable name.
> Fixed a few typos in developer guide

- docs/working-group/README.md
Add notes from working group meeting for 01/12/21
> Add notes from working group meeting

- pkg/apis/autoscaling/v1alpha1/metricsproducer.go
- pkg/apis/autoscaling/v1alpha1/metricsproducer_status.go
- pkg/apis/autoscaling/v1alpha1/metricsproducer_validation.go
- pkg/metrics/producers/factory.go
> ScheduledCapacity Metrics Producer API

- pkg/cloudprovider/aws/capacity.go
- pkg/cloudprovider/aws/factory.go
- pkg/cloudprovider/fake/capacity.go
- pkg/cloudprovider/fake/factory.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioner/v1alpha1/allocation/greedyallocator.go
- pkg/controllers/provisioner/v1alpha1/allocation/types.go
- pkg/controllers/provisioner/v1alpha1/controller.go
- pkg/controllers/provisioner/v1alpha1/reallocation/types.go
- pkg/controllers/provisioner/v1alpha1/scheduling/types.go
> Provisioner skeleton code

- cmd/controller/main.go
- config/rbac/role.yaml
- docs/aws/README.md
- go.mod
- pkg/cloudprovider/aws/capacity.go
- pkg/cloudprovider/aws/factory.go
- pkg/cloudprovider/aws/initialization.go
- pkg/cloudprovider/fake/capacity.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioner/v1alpha1/allocation/greedyallocator.go
- pkg/controllers/provisioner/v1alpha1/controller.go
> Implemented cloud provider initialization

- docs/examples/queue-length-average-value.yaml
- docs/examples/reserved-capacity-utilization.yaml
- docs/examples/scheduled-capacity.yaml
- pkg/apis/autoscaling/v1alpha1/metricsproducer_defaults.go
- pkg/apis/autoscaling/v1alpha1/metricsproducer_validation.go
- pkg/apis/autoscaling/v1alpha1/scalablenodegroup_validation.go
- pkg/controllers/controller.go
- pkg/controllers/horizontalautoscaler/v1alpha1/suite_test.go
- pkg/metrics/producers/factory.go
- Uses ValidationWebhooks generated by KubeBuilder to validate CRD yamls
- modifies current Queue-Length Metrics Producer validation efforts for cloud provider specific resources
- adds in a field into example docs for current issue (https://github.com/awslabs/karpenter/issues/64)
> Validations for MetricsProducers

- cmd/controller/main.go
- config/rbac/role.yaml
- pkg/cloudprovider/aws/fleet/capacity.go
- pkg/cloudprovider/aws/fleet/nodefactory.go
- pkg/controllers/provisioner/v1alpha1/allocation/greedyallocator.go
- pkg/controllers/provisioner/v1alpha1/controller.go
Create node objects in kubernetes and bind pod to node.
> Create node objects and bind pods to nodes

- pkg/cloudprovider/aws/fleet/capacity.go
- pkg/cloudprovider/fake/capacity.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioner/v1alpha1/allocation/greedyallocator.go
```
karpenter-6fc6f46667-stjzm manager {"level":"info","ts":1612317115.3636768,"msg":"Allocating 4 pending pods from 4 constraint groups"}
karpenter-6fc6f46667-stjzm manager {"level":"info","ts":1612317116.7961228,"msg":"Successfully discovered subnets in 3 zones for cluster etarn-dev"}
karpenter-6fc6f46667-stjzm manager {"level":"info","ts":1612317116.8354862,"msg":"Successfully discovered launch template Karpenter-etarn-dev for cluster etarn-dev"}
karpenter-6fc6f46667-stjzm manager {"level":"info","ts":1612317118.7805374,"msg":"Successfully requested 1 nodes"}
karpenter-6fc6f46667-stjzm manager {"level":"info","ts":1612317118.7995632,"msg":"Successfully bound pod default/pause-5d968bbb58-lc88c to node ip-192-168-136-52.us-west-2.compute.internal"}
karpenter-6fc6f46667-stjzm manager …
```
> Reoriented Capacity CloudProvider around BinPacking

- docs/DEVELOPER_GUIDE.md
- pkg/cloudprovider/aws/fleet/instanceprofile.go
- pkg/cloudprovider/aws/fleet/launchtemplate.go
*Issue #, if available:* https://github.com/awslabs/karpenter/issues/230
This change switches from the EKS Optimized AMI to the Bottlerocket EKS AMI. It doesn't add any new functionality beyond that, (e.g., it does not include the ability to have custom UserData or switch between the two forms of AMI, which should be a separate issue.) Tested by hand on a cluster by cordoning existing nodes and ensuring a BR instance spins up.
> Bottlerocket support

- pkg/controllers/provisioning/v1alpha1/reallocator/controller.go
- pkg/controllers/provisioning/v1alpha1/reallocator/terminate.go
Fixed an error in reallocator where cloudprovider was not defined, resulting in inability to delete nodes.
> Fixed Error in reallocator for cloudprovider

- pkg/apis/provisioning/v1alpha1/doc.go
- pkg/controllers/provisioning/v1alpha1/reallocation/annotate.go
- pkg/controllers/provisioning/v1alpha1/reallocation/controller.go
- pkg/controllers/provisioning/v1alpha1/reallocation/filter.go
- pkg/controllers/provisioning/v1alpha1/reallocation/terminate.go
- pkg/utils/node/predicates.go
- pkg/utils/ptr/ptr.go
- Nodes that have a TTL set due to underutilization are now reevaluated in case pods or other resources begin using that pass the threshold (0 non-daemon pods) right now
Logical Flow: (asterisked fields are added in this PR)
- Node is deemed underutilized
- Node labeled underutilized*
- Add TTL to underutilized nodes
- Get Nodes labeled underutilized and remove TTL if they have sufficient utilization*
- Get expired nodes (past TTL)
- Cordon expired Nodes
- Delete cordoned Nodes
> Added TTL reevaluation logic for reallocation

- pkg/controllers/provisioning/v1alpha1/allocation/constraints.go
- pkg/utils/scheduling/scheduling.go
Since a ResourceList is a `map[ResourceName]resource.Quantity`, the Add function does not work for values of this map, since we pass in a direct reference, not a pointer. 
GetResources used to return 0 values of quantities, but now returns accurate values.
> ResourceList Pointer error fix

- pkg/apis/provisioning/v1alpha1/provisioner.go
N/A
- The json tag on the provisioner spec struct was missing a comma before inline resulting in the actual field `inline` to carry over to the provisioner crd. This PR simply adds the comma. 
Error before:
```
$ cat <<EOF | kubectl apply -f -
apiVersion: provisioning.karpenter.sh/v1alpha1
metadata:
name: default
spec:
cluster:
name: ${CLUSTER_NAME}
caBundle: $(aws eks describe-cluster --name ${CLUSTER_NAME} | jq ".cluster.certificateAuthority.data")
endpoint: $(aws eks describe-cluster --name ${CLUSTER_NAME} | jq ".cluster.endpoint")
EOF
kubectl get provisioner default -oyaml
error: error validating "STDIN": error validating data: ValidationError(Provisioner.spec): missing required field "inline" in …
```
> fix provisioner inline spec on json struct tag

- pkg/cloudprovider/aws/fleet/packing/packing.go
Problem: we check all the node capacities, if smallest node is checked in the end `remainingPods` gets updated but the `bestPackedPods` already contains higher number of packed pods. So when this function returns it `bestPackedPods` which contains the highest number of packed pods but `remainingPods` contains pods left over for the node with a smaller capacity.
This fix will update the `remainingPods` to the right set of pods everytime we update `bestPackedPods`.
> Fix wrong remaining pods value 

- pkg/apis/provisioning/v1alpha1/provisioner_defaults.go
- pkg/apis/provisioning/v1alpha1/provisioner_validation.go
- pkg/apis/provisioning/v1alpha1/suite_test.go
- pkg/cloudprovider/aws/fleet/capacity.go
- pkg/cloudprovider/aws/test/allocator_test.go
- pkg/cloudprovider/aws/test/suite_test.go
- pkg/cloudprovider/aws/test/validation_test.go
- pkg/controllers/controller.go
- pkg/controllers/manager.go
- pkg/controllers/provisioning/v1alpha1/allocation/filter.go
- pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
- pkg/utils/functional/functional.go
1. Support for provider specific validation (i.e. supported OS/Arch)
2. Support for common validation (i.e. restricted labels, cluster spec)
```
Error from server (spec.labels contains restricted label kubernetes.io/arch): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"provisioning.karpenter.sh/v1alpha1\",\"kind\":\"Provisioner\",\"metadata\":{\"annotations\":{},\"name\":\"default\",\"namespace\":\"default\"},\"spec\":{\"cluster\":{\"caBundle\":\"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ESXhNVEl3TURVeE0xb1hEVE14TURJd09USXdNRFV4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGd …
```
> Added validation for provisioners

- .github/PULL_REQUEST_TEMPLATE.md
N/A
- The default pull request template doesn't specify the license. This change adds apache-2.0 license
> add apache-2.0 license to pull request template

- pkg/cloudprovider/aws/packing/packing.go
N/A
Turn off burstable instances for now until we determine how to handle the details of cpu credits.
> turn off burstable t instance for now

- config/controller.yaml
N/A
- Add OS and Architecture affinity so that karpenter doesn't schedule to windows or arm64 nodes 
- Remove cpu and memory limits to avoid OOM
> remove limits and add os and arch affinity

- pkg/cloudprovider/aws/instance.go
N/A
- Fleet returns back launch errors that may mean that the request was successful eventually. This can happen if one of the instance types results in an ICE, but fleet retries and is able to launch the capacity with another instance type specified in the request.  We see some errors now because some instance types are not available in all AZs. With this change, we only error out if the capacity is also not met. Otherwise, we print these errors as warnings.
> do not fail on create fleet launch errors

- docs/aws/README.md
Description of changes: I don't think refer to the name of the nodegroup anywhere, so it's easier if we just let `eksctl` create a random name for us.
> make easier to run commands if creating two stacks

- docs/aws/karpenter.cloudformation.yaml
If a karpenter specific cfn stack exists and these policy and profile are created, a second stack for the new cluster fails because these policy/profiles already exist in the account
> Keep policy and profile also cluster specific

- docs/aws/README.md
1.19 currently breaks our subnet discovery system. https://github.com/weaveworks/eksctl/issues/3341
Change back to 1.19 when https://github.com/kubernetes/cloud-provider-aws/issues/184 gets resolved.
> Reverted eksctl create cluster version back to 1.18

- pkg/controllers/provisioning/v1alpha1/allocation/filter.go
N/A
- A lot of cloud provider resources are being fetch unnecessarily if there are no pods to schedule and therefore check supported labels for. This change short circuits the fetching of cloud provider resources if there are no pods. 
> short circuit if there are no schedulable pods in the allocation controller

- pkg/cloudprovider/aws/capacity.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instanceprofile.go
- pkg/cloudprovider/aws/securitygroups.go
- pkg/cloudprovider/aws/vpc.go
- pkg/controllers/controller.go
- pkg/controllers/provisioning/v1alpha1/allocation/bind.go
- pkg/controllers/provisioning/v1alpha1/allocation/constraints.go
- pkg/controllers/provisioning/v1alpha1/allocation/controller.go
- pkg/controllers/provisioning/v1alpha1/allocation/filter.go
- pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
- pkg/controllers/provisioning/v1alpha1/reallocation/controller.go
- pkg/controllers/provisioning/v1alpha1/reallocation/suite_test.go
- pkg/controllers/provisioning/v1alpha1/reallocation/utilization.go
- pkg/controllers/types.go
Looking for advice on what the default timeout for contexts should be. Ideally, any command we do shouldn't take anywhere close to 300 seconds. 
Replaced each context.TODO with proper contexts.
- Contexts will be created at the top level of each controller as a `context.Background()`
- Each time a context is used as a parameter, it only creates a new context if the command is a request (with timeout of 300 seconds)
- Request to the API Server
- Request to the AWS CLI 
> Replaced context.TODO with actual contexts

- pkg/cloudprovider/aws/capacity.go
- pkg/cloudprovider/aws/factory.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/instancetypes_test.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/aws/utils/utils.go
- pkg/cloudprovider/aws/vpc.go
N/A
- Restructured instance type provider to reduce ec2 InstanceTypeOffering API calls
- `2021-03-31T00:17:09.790Z	DEBUG	Successfully discovered 392 EC2 instance types` is only logged one time per cache miss. 
- Fixed bad log on normalizeZones, no need to log in that func at all.  
- Retrieving all zones and caching as instance type with supported zones allowed a simplification of the provider (removing vpc provider dependency).
> minimize logging and simplify instance types provider

- pkg/cloudprovider/aws/capacity.go
- pkg/cloudprovider/aws/vpc.go
https://github.com/awslabs/karpenter/issues/261
Support for zone-ids was actually implemented as part of the instance type provider PR (https://github.com/awslabs/karpenter/pull/307), but this PR adds zone-ids to the cloud provider GetZones list so the provisioner validation webhook will succeed if a user puts a zone-id in the provisioner.
---
provisioner.yml
```
apiVersion: provisioning.karpenter.sh/v1alpha1
metadata:
spec:
cluster:
....
name: karpenter-test
ttlSeconds: 10
zones:
- use1-az2
```
My account maps use1-az2 -> us-east-1a.  Tested launching several instance which all went to the proper AZ. 
> add zone-ids to zone validation

- pkg/controllers/provisioning/v1alpha1/reallocation/terminate.go
https://github.com/awslabs/karpenter/issues/275
Discussed [here](https://github.com/awslabs/karpenter/pull/335). The TODO was placed to ensure that if the Terminate API command succeeded but only terminated partial instances, that the node wouldn't be deleted in the APIServer. After realizing that the command would not error only if all instances are deleted, this TODO becomes unneeded.
> removed TODO per discussion

- pkg/controllers/provisioning/v1alpha1/reallocation/terminate.go
- pkg/controllers/provisioning/v1alpha1/reallocation/utilization.go
N/A
Currently, only nodes that have the same labels as the provisioner spec Labels list is marked as underutilized and eventually terminated. We don't want to churn whole clusters because of a simple label change in the provisioner and if we don't churn, then nodes will be orphaned from the provisioners management.  So this PR removes the Labels requirement when looking for nodes to mark as underutilized.
> don't require labels to match when terminating nodes

- pkg/cloudprovider/aws/suite_test.go
- pkg/webhooks/provisioning/v1alpha1/suite_test.go
N/A
- Add instance types to InstanceType tests in cloudprovider aws and webhook validation tests.
> add instance types to instance type tests

- Makefile
- pkg/cloudprovider/aws/factory.go
- pkg/utils/project/project.go
N/A
- Add a karpenter specific user-agent string w/ version to the AWS session 
> add user-agent string

- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instancetypes_test.go
- pkg/cloudprovider/aws/suite_test.go
Issue #, if available: 273
- wasn't resetting the list of fake ec2 instances when Reset was called
> Fix bug in ec2 api mock

- go.mod
- go.sum
- pkg/cloudprovider/aws/factory.go
- pkg/cloudprovider/aws/nodefactory.go
- pkg/cloudprovider/aws/utils/retryer.go
N/A
- remove retry library in favor of aws sdk retryer configured on the aws session
> remove retry library in favor of aws sdk retryer configured on the aws session

- cmd/controller/main.go
- pkg/cloudprovider/aws/capacity.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/nodefactory.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/capacity.go
- pkg/controllers/provisioning/v1alpha1/allocation/constraints.go
- pkg/controllers/provisioning/v1alpha1/allocation/filter.go
- pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
- pkg/packing/nodecapacity.go
- pkg/packing/packing.go
- pkg/test/pods.go
- pkg/utils/binpacking/binpacking.go
- pkg/utils/resources/resources.go
```
karpenter-7fc58bdcf9-sjvtp manager 2021-04-14T23:03:30.919Z	DEBUG	Successfully discovered 392 EC2 instance types
karpenter-7fc58bdcf9-sjvtp manager 2021-04-14T23:03:30.919Z	INFO	Found 1 provisionable pods
karpenter-7fc58bdcf9-sjvtp manager 2021-04-14T23:03:31.208Z	DEBUG	Successfully discovered subnets in 3 zones for cluster etarn
karpenter-7fc58bdcf9-sjvtp manager 2021-04-14T23:03:31.210Z	DEBUG	Selected 20 instance type options for 1 pod(s) [g3.16xlarge g3.4xlarge p3.2xlarge g3.8xlarge g2.2xlarge g4dn.12xlarge p4d.24xlarge p2.8xlarge g4dn.xlarge g3s.xlarge p2.16xlarge p3.8xlarge g4dn.2xlarge p3.16xlarge g4dn.4xlarge g4dn.16xlarge g2.8xlarge p2.xlarge g4dn.8xlarge p3dn.24xlarge]
karpenter-7fc58bdcf9-sjvtp manager 2021-04-14T23:03:31.210Z	DEBUG	Computed packings for 1 pod(s) onto 1 …
```
> Implemented support for Nvidia GPU and AWS Neuron

- cmd/controller/main.go
- go.mod
- pkg/controllers/controller.go
- pkg/controllers/manager.go
https://github.com/awslabs/karpenter/issues/358
If it fails, it exponentially backs off from `100ms` to `10s` detailed below.
```100ms -> 200ms -> 400ms -> 800 ms -> 1.6s -> 3.2s -> 6.4s -> 10s -> 10s -> 10s ....```
> Properly implemented exponential backoff for reconciliation failures

- hack/quick-install.sh
We removed Prometheus, so no pods remain in the `monitoring` namespace. We don't want to delete namespaces that we do not own. 
> remove monitoring ns deletion

- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/fake/capacity.go
- pkg/cloudprovider/fake/instancetype.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
- pkg/packing/packable.go
- pkg/utils/resources/resources.go
Issue #, if available: https://github.com/awslabs/karpenter/issues/384
```
karpenter-bc6977c4b-jk6gf manager 2021-05-18T22:52:50.263Z	DEBUG	Successfully computed packing for pod(s) [default/inflate-5bcf57c57f-tcbl6] with instance type option(s) [g4ad.4xlarge g4ad.8xlarge g4ad.16xlarge]
```
> Implemented support for AMD GPUs

- Makefile
N/A
`make` treats double quotes as literals, so `HELM_OPTS ?= ""` is verbatim executed when running `make apply` which causes an arg mismatch:
```
$ make apply
helm template karpenter charts/karpenter \
"" \
--set controller.image=ko://github.com/awslabs/karpenter/cmd/controller | \
GOFLAGS="-tags=aws "-ldflags=-X=github.com/awslabs/karpenter/pkg/utils/project.Version=v0.2.3-15-g20ee200"" ko apply -B -f -
Error: expected at most two arguments, unexpected arguments:
``` 
Removing the double quotes fixes this:
```
$ make apply
helm template karpenter charts/karpenter \
\
--set controller.image=ko://github.com/awslabs/karpenter/cmd/controller | \
GOFLAGS="-tags=aws "-ldflags=-X=github.com/awslabs/karpenter/pkg/utils/project.Version=v0.2.3-15-g20e …
```
> fix helm-opts

- docs/aws/README.md
When working through the getting started docs I noticed an issue with `aws` commands that were piped to `jq`, and cause an error like:
```
parse error: Invalid numeric literal at line 1, column 8
```
This was because my default output was not set to `json` for the AWS CLI, so added the `--output json` option to the relevant commands.
> Explicitly set output of aws cli to json

- Makefile
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/packing/packable.go
Issue #, if available: #393
Implementation driven by https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources
Modeling a few ec2 instances here: https://docs.google.com/spreadsheets/d/1-mCo9-P2ThQxV0VdLbvyM59glykheP3pCBAZRdquZng/edit#gid=0
Note: I can't account for the difference between Kubernete's discovered Capacity and EC2's advertised memory values. To address this, we need to include an additional buffer. I chose 7.25%, since overhead is a monotonically decreasing function, with c5a.micro as largest percentage overhead of 7.04%. Nanos are excluded, since pods will never fit on them given default overhead values.
```
karpenter-5799c57d45-ts889 manager 2021-05-21T20:12:29.675Z	DEBUG	Excluding instance type t3.nano because there are not …
```
> Factored in overhead properly to avoid OutOfCPU or OutOfMemory errors

- charts/karpenter/templates/controller.yaml
- charts/karpenter/values.yaml
- pkg/cloudprovider/aws/factory.go
Karpenter currently relies on EC2 instance metadata service (IMDS) to figure out which AWS region it is running in. IMDS is not available for pods running on EKS Fargate ([ref](https://docs.aws.amazon.com/eks/latest/userguide/fargate.html)). This change preserves region discovery via EC2 IMDS if the Go SDK has not picked up region configuration via the environment.
> Allow Karpenter controller to run on Fargate

- hack/quick-install.sh
- added `--namespace karpenter` to delete command to delete the release in the proper namespace
- Cert-manager takes a little bit to become usable. This is well known and documented [here](https://cert-manager.io/docs/concepts/webhook/#webhook-connection-problems-shortly-after-cert-manager-installation). Immediately attempting to install Karpenter after Cert-manager results in a failure below. 
```
Error: release karpenter failed, and has been uninstalled due to atomic being set: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: x509: certificate signed by unknown authority
```
By submitting this pull request, I confirm that my contribution is …
> Properly delete Karpenter release on uninstall and wait for Cert-Manager on install

- docs/ROADMAP.md
1. Added T-Shirt Sizes
2. Reworded v0.2, v0.3, v0.4 blurbs
3. Removed native support for ec2 instance interruption to a future release, users can rely on https://github.com/aws/aws-node-termination-handler in the interim
4. Added tasks for Subnet and SecurityGroup overrides
5. Separated concepts of cluster upgrade for new vs existing nodes
6. Separated scheduling concepts.
> Updates to ROADMAP.md

- README.md
N/A
- Remove go-report-card because it seems to be unstable and giving us an F :(  
> remove go-report-card

- pkg/cloudprovider/aws/instance.go
- pkg/packing/packer.go
https://github.com/awslabs/karpenter/issues/438
- Move the truncation of instance type options from the cloud provider specific implementation to the generic packing pkg. 
> move lowest-n instance type options to generic packing pkg

- Makefile
> Added delete namespace to uninstall process

- docs/deprecated/designs/metrics-driven-autoscaling.md
- docs/deprecated/designs/scheduled_capacity.md
- docs/designs/aws-launch-templates-options.md
- docs/designs/bin-packing.md
- docs/designs/termination.md
Added authors to existing design docs
> Added authors to existing design docs

- charts/karpenter/templates/webhook/deployment.yaml
- charts/karpenter/templates/webhook/webhooks.yaml
- cmd/webhook/main.go
Issue #, if available: #463
The main change is that we now statically populate webhooks.yaml instead of allowing the webhook controller to inject the resources into the webhook. This ensures that the webhook configuration prevents creation of provisioners even if the webhook controller fails to come online (e.g. auth issues)
```rules:  - apiGroups:    - provisioning.karpenter.sh    apiVersions:    - v1alpha1    resources:    - provisioners      provisioners/status    operations:    - CREATE    - UPDATE    - DELETE```
> Resolved a race condition where provisioners could skip having defaults if applied before karpenter-webhook came online

- cmd/webhook/main.go
- pkg/apis/provisioning/v1alpha1/provisioner.go
- pkg/apis/provisioning/v1alpha1/provisioner_validation.go
- pkg/apis/provisioning/v1alpha1/provisioner_validation_test.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/constraints.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/node.go
- pkg/cloudprovider/aws/subnets.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/registry/register.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/v1alpha1/allocation/constraints.go
- pkg/controllers/provisioning/v1alpha1/allocation/filter.go
- pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
- pkg/controllers/provisioning/v1alpha1/reallocation/suite_test.go
- pkg/controllers/terminating/v1alpha1/suite_test.go
- pkg/test/expectations/expectations.go
- pkg/test/pods.go
- Users may specify subnets using `node.k8s.aws/subnet-name: dns-compliant-name`
- Users may specify subnets using `node.k8s.aws/subnet-tag-key: kubernetes-label-compliant-tag-key-name`
- Added a bunch of validation and tests
> Support for Subnets specification/override

- cmd/webhook/main.go
- pkg/cloudprovider/aws/constraints.go
- pkg/cloudprovider/aws/node.go
- pkg/controllers/controller.go
- pkg/controllers/provisioning/v1alpha1/reallocation/controller.go
- pkg/controllers/provisioning/v1alpha1/reallocation/suite_test.go
- pkg/test/expectations/expectations.go
- pkg/utils/conditions/conditions.go
> Added SetDefault() for each Reconcile function

- pkg/apis/provisioning/v1alpha1/provisioner.go
- pkg/apis/provisioning/v1alpha1/provisioner_validation.go
- pkg/apis/provisioning/v1alpha1/provisioner_validation_test.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/v1alpha1/allocation/bind.go
- pkg/controllers/provisioning/v1alpha1/reallocation/controller.go
- pkg/controllers/provisioning/v1alpha1/reallocation/suite_test.go
- pkg/controllers/provisioning/v1alpha1/reallocation/utilization.go
- pkg/controllers/terminating/v1alpha1/controller.go
- pkg/controllers/terminating/v1alpha1/suite_test.go
- pkg/controllers/terminating/v1alpha1/terminate.go
- pkg/test/expectations/expectations.go
- pkg/test/nodes.go
- pkg/utils/functional/functional.go
- pkg/utils/node/predicates.go
- Finalizers are added to nodes created by the allocation controller
- We no longer have a draining/drained phase for termination labels.
- Kubectl delete node works 
- Some testing and utils improvements
> Added finalizers addition and removal logic for nodes

- pkg/cloudprovider/aws/subnets.go
We allow pods to be constrained to a particular zone by using this tag `topology.kubernetes.io/zone: us-east-2a`. However, we don't constraint the subnets when calling fleet API and instance gets created in the incorrect zone.
> Constraint subnets based on zones

- charts/karpenter/templates/controller/deployment.yaml
- charts/karpenter/templates/webhook/deployment.yaml
N/A
There are a few ways that karpenter pods can get scheduled on bad compute nodes:
1. Karpenter pods can be scheduled to nodes that were provisioned by karpenter which is not a good idea
2. Karpenter pods can be scheduled to Windows nodes which we do not publish a docker image for yet
3. Karpenter pods can be scheduled to arm64 nodes which we do not publish an image for yet
This PR adds a default anti-affinity for the karpenter provisioner name label (`provisioner.karpenter.sh/name`) and affinity to linux and amd64 nodes. 
> add arch, os, and provisioner anti-affinities for the karpenter deployment

- docs/aws/README.md
Major differences I made throughout the doc
- Use [semantic line breaks](https://sembr.org/)
- By default assume someone creates a new cluster with 1.20
- Add commands to tag subnets as needed
- Add line breaks to long commands
- Use `--query` with aws cli instead of relying on `jq` where possible
- Add `helm repo update`
- Fix label match for karpenter pod
- Add cluster delete command to cleanup
> Updates for example deployment

- docs/aws/README.md
- docs/aws/eks-config.yaml
- docs/aws/karpenter.cloudformation.yaml
This updates the AWS getting started guide to create an EKS cluster using fargate instead of a managed node group. It also simplifies some of the karpenter cloudformation by including a service account with the EKS config.
I ran through the setup a few times and this morning did it on a personal account to verify costs. For the cluster I provisioned this setup should be slightly cheaper. I'm waiting for my bill to give an exact estimate but based on what I tried it's $.0864 with fargate vs $.096 with m5.large instance.
> Add getting started based on fargate

- pkg/controllers/allocation/filter.go
- pkg/controllers/reallocation/utilization.go
- pkg/controllers/termination/controller.go
- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
- pkg/utils/pod/scheduling.go
When draining nodes, we did not gracefully evict any daemonset pods, but left them to forcefully terminate along with the node, when no other pods remained. 
- This change makes it so that we evict all pods that won't be rescheduled even if the node is cordoned (tolerates unschedulable)
- Additionally, I remove the duplicated un-used Reconcile() function in the Reallocation controller.
> Termination now only evicts pods that don't tolerate Unschedulable

- docs/README.md
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/allocation/suite_test.go
- pkg/controllers/controller.go
- pkg/controllers/manager.go
- pkg/controllers/reallocation/suite_test.go
- pkg/controllers/termination/suite_test.go
- pkg/test/environment.go
- pkg/test/expectations/expectations.go
Issue #382, if available:
- Tests now run in ~40 seconds instead of 1:20
- Now calls reconcilers directly to make tests more deterministic. Previous approach launched the controllers and waited, which frequently was subject to GHA noisy neighbors.
> Finally decided to prevent tests from flaking 🤷

- pkg/apis/provisioning/v1alpha2/provisioner.go
- pkg/controllers/termination/controller.go
- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
- pkg/test/pods.go
- Users can now specify annotations on their pods `karpenter.sh/do-not-evict` where requesting to terminate that node will cordon it, but wait to drain until those pods are terminated.
> Added do-not-evict option for pods

- docs/working-group/README.md
Add working group notes for 07/08
> Add working group notes

- pkg/apis/provisioning/v1alpha3/provisioner.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/allocation/controller.go
- pkg/controllers/allocation/filter.go
- pkg/controllers/allocation/suite_test.go
- pkg/controllers/expiration/suite_test.go
- pkg/controllers/reallocation/suite_test.go
N/A
- Limits the number of times the error is logged when a provisioner is not found
- Fixes a bug where if pods are pending when karpenter starts up, they will be reconciled to any provisioner (previous racing behavior). The matchesProvisioner func was not completely correct when checking the default provisioner. 
- Moves the default provisioner to a reference in the apis pkg.  
Previous Log:
```
karpenter-controller-86cf989bcd-jkqfm manager 2021-07-16T15:41:13.188Z	ERROR	Retrieving provisioner, create a default provisioner, or specify an alternative using the nodeSelector karpenter.sh/provisioner-name …
```
> Limit "provisioner does not exist" logging and fix startup reconciliation bug

- go.mod
- go.sum
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/docs/README.md
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/node.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/types.go
- pkg/controllers/allocation/bind.go
- pkg/controllers/allocation/controller.go
- pkg/controllers/expiration/controller.go
- pkg/controllers/reallocation/utilization.go
- pkg/controllers/termination/terminate.go
- pkg/packing/packer.go
- pkg/utils/parallel/workqueue.go
Previously, the capacity API took multiple instances to allow cloud providers to batch create/get/delete API calls. However, this had a linearizing side effect such that all instances must be launched before karpenter was able to bind pods. This resulted in increased cases where the scheduler would schedule to capacity (launch by the linear loop) before Karpenter could execute the binds. Parallelizing also has the obvious side effect of making things launch a lot faster (unmeasured).
There are some long term considerations to this change:
1. Cloud providers will no longer (easily) be able to batch capacity API calls
2. Cloud providers will no longer be able to see multiple packings at once, which could allow for re-packing.
The primary benefits are:
1. The …
> Parallelizes capacity creation

- go.mod
- go.sum
- pkg/controllers/termination/controller.go
- pkg/controllers/termination/eviction.go
- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
- pkg/test/expectations/expectations.go
- pkg/test/pods.go
https://github.com/awslabs/karpenter/issues/452
- Pod evictions now have separate backoffs per pod
- Drain in termination controller queues up pods to a continually running queue processor as a goroutine in the background
- Accounts for different pod eviction errors 
> Added Per-pod eviction backoff and retry logic 

- website/config.toml
- website/netlify.toml
N/A
After wrestling with Github Pages for the last 24 hours, and failing to get it to play nicely with Karpenter's monorepo structure and Hugo, I propose we build and host the docs site on [Netlify](https://www.netlify.com/). Over time we can evolve this approach as needed, but for the near term, I believe this is good solution for the project.
This PR includes two changes, first is a `netlify.toml` config file that is essentially copied from the [Hugo Netlify docs](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify). The second change is a minor change to the Hugo configuration file to simplify the `baseURL` and remove the `publishDir` as its no longer needed.
By submitting this pull request, …
> Build and Host Website on Netlify

- pkg/cloudprovider/aws/launchtemplate.go
N/A
- Adds a Name tag to the default Karpenter Launch Template (this is the launch template hardcoded in Karpenter that is used when a user does not override the launch template).  The Name tag in EC2 is a special tag that is used to fill the Name column of the EC2 Web Console. 
- If a user overrides the launch template, they can specify any Name tag they'd like on the EC2 instance Karpenter will create.
The name format is `Karpenter/<Cluster-Name>` I can't add the K8s Node Name since the name doesn't exist until after an instance is launched. 
> add Name tag to default launch template

- website/content/en/docs/getting-started/_index.md
change link to non-fargate version, also use shorter link
#538 
changes the link to eks-config.yaml to the proper non-fargate version 
```bash
curl -fsSL  https://www.karpenter.sh/docs/getting-started/eks-config.yaml
```
> fix link to eks-config.yaml

- website/content/en/docs/getting-started/_index.md
- website/content/en/docs/getting-started/karpenter.cloudformation.yaml
bug: cloud formation url in getting started guide doesn't work
response:
in getting started guide, change cloud formation curl url to `https://www.karpenter.sh/docs/getting-started/eks-config.yaml` and eliminate inserting of github release tag
add karpenter cloudformation yaml to  static site
> change cloudformation link

- README.md
I updated the Docs and FAQ links in the README to point to the new documentation site. The current Docs link generates 404.
> Resolved docs 404 error and updated FAQ to new doc site

- pkg/cloudprovider/aws/instance.go
N/A
- Fixes a bug where API Machinery errors.IsNotFound() was being used to evaluate the error response from an AWS sdk call to EC2. The specific call is checking if the TerminateInstances API returns an "Instance ID does not exist" error which would indicate that the instance was already terminated or for whatever other reason, no longer exists. In this case, Karpenter should move along and delete the nodes from the k8s API server.  
TLDR: 
The logic was correct, but the wrong error check was used which caused nodes to hang when the ec2 instance had already been termianted.
> Fixed bug in aws cloudprovider where API machinery IsNotFound was incorrectly used on ec2 Terminate resp

- website/config.toml
Enable google analytics. 
Add google analytics tag to hugo config.
Google analytics only be included when `HUGO_ENV="production"`
New visits to live site will be logged in google analytics, including some info about viewer. 
> add google analytics

- website/config.toml
#560 
Enable lunr js -- https://lunrjs.com/guides/getting_started.html -- in hugo config.
When hugo is built, lunr runs and stores an index file of site contents. This is used for offline search. 
Add a search bar to the header. For example, you can search for "labels" and see relevant pages. 
> enable offline search with lunrjs

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/allocation/controller.go
- pkg/controllers/allocation/filter.go
- pkg/test/expectations/expectations.go
- pkg/utils/result/result.go
Before
```
karpenter-controller-59479cf58c-ngmt4 manager 2021-07-26T17:22:10.759Z	ERROR	controller.Allocation	Failed allocation, launching instances, AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; AuthFailure.ServiceLinkedRoleCreationNotPermitted; …
```
> Improve error logging from multiple packing errors

- website/content/en/docs/getting-started/_index.md
- website/content/en/docs/getting-started/eksctl.yaml
Switching from self managed node group to managed node group. This could help customers in the future if they keep a cluster around a while and want to update the EKS version.
Also specified the EKS version because depending on which version of `eksctl` the user has it may deploy a different version. I would use 1.21 but the official `eksctl` with 1.21 support isn't out yet. 1.20 has been covered for a while and gets us a semi-new version of a cluster to avoid unknown issues.
> Update getting started eksctl.yaml

- cmd/controller/main.go
- go.mod
- go.sum
- pkg/controllers/reallocation/controller.go
- pkg/controllers/reallocation/suite_test.go
- pkg/controllers/reallocation/utilization.go
- pkg/controllers/termination/suite_test.go
- pkg/test/expectations/expectations.go
- pkg/test/pods.go
- pkg/utils/node/predicates.go
- pkg/utils/pod/scheduling.go
This PR changes how reallocation controls the underutilization of nodes depending on their status. 
Previously we used to set nodes as underutilized and set a TTL (as specified in the Provisioner) for nodes, regardless of their status. This results in a race condition where nodes are brought up, and we could set a TTL before pods bind to them. This change now only allows us to do so for Ready nodes. 
In addition, this PR adds the feature to delete nodes that fail to become ready after 15 minutes, designed [here](https://github.com/awslabs/karpenter/blob/main/designs/termination.md#karpenter-availability-and-termination-cases). Since there are many reasons why nodes could become NotReady after becoming ready, we only consider nodes that were unable to come up, …
> Readjusted reallocation controller for nodes that fail to come up

- API.md
- cmd/controller/main.go
- pkg/apis/provisioning/v1alpha3/provisioner.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/controllers/allocation/bind.go
- pkg/controllers/node/controller.go
- pkg/controllers/node/finalizer.go
- pkg/controllers/node/readiness.go
- pkg/controllers/node/suite_test.go
- pkg/controllers/reallocation/suite_test.go
- pkg/controllers/termination/controller.go
- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
- pkg/test/nodes.go
- pkg/utils/node/predicates.go
- pkg/utils/result/result.go
Built a lightweight controller that helps enforce invariants (over time) in the codebase.
If kubeapi QPS is backed up, nodes may come online before we're able to create the node object. This means that the node object would be created by the kubelet, rather than patched by the kubelet. The result is that the node would not have the finalizer, and instances could leak. See: https://github.com/awslabs/karpenter/issues/549.
Now, we add the finalizer if it doesn't exist, unless the node is terminating.
Taint karpenter.sh/not-ready=NoSchedule to prevent the kube scheduler from scheduling pods before we're able to bind them ourselves. The kube scheduler has an eventually consistent cache of nodes and pods, so it's possible for it to see a …
> Resolves race conditions exposed at high scale

- website/content/en/docs/Reference/_index.md
This PR copies the auto generated API docs into the hugo site. 
Todo:
- brief intro on this page.
- (eventually) automate building and including this. 
> add api reference docs

- website/content/en/docs/getting-started/eksctl.yaml
**Issue, if available:** 
n/a
it seems like using Bottlerocket as the default is preferable here, no big deal if not though
> switch to Bottlerocket for example eksctl nodegroup

- .github/ISSUE_TEMPLATE/docs-request.md
None of the existing issue templates (bug, roadmap request, security vulnerability) are a good fit for docs. 
This new issue template asks relevant questions, while also being brief. 
> add docs issue template

- website/content/en/docs/getting-started/eksctl.yaml
**Is an existing page relevant?**
https://karpenter.sh/docs/getting-started/#create-a-cluster
**Description of issue:**
Running the command from the "Create a Cluster" section of the Getting Started guide fails with message: `Error: only AmazonLinux2 is supported for Managed Nodegroups`
**Description of change:**
Changed EKS cluster config's `amiFamily` from "Bottlerocket" to "AmazonLinux2".
> Fix eksctl error in Getting Started

- website/content/en/docs/getting-started/_index.md
**Description of problem:**
See https://karpenter.sh/docs/getting-started/#cleanup
The command `aws cloudformation delete-stack [...]` succeeds on the command line but in the AWS Console the CloudFormation Stack's status changes to `DELETE_FAILED` with the reason `The following resource(s) failed to delete: [KarpenterControllerPolicy].`  The policy is used by the IAM Service Account created manually during the setup.
**Description of change:**
Before attempting to delete the CloudFormation Stack:
1. Uninstall the *karpenter* helm chart -- since it utilizes the IAM Service Account
2. Delete the IAM Service Account
> Delete IAM Service Account before deleting CloudFormation Stack in Getting Starting guide

- pkg/controllers/node/liveness.go
- pkg/controllers/node/suite_test.go
- pkg/test/nodes.go
#613, #601
Fixes an issue where nodes don't terminate if they can't connect to the API Server, resulting in runaway scaling. 
The liveness controller will terminate nodes that don't ready up. This is critical, because pods will only survive on not ready nodes for 5 minutes by default (tolerations). The controller must differentiate between a node that never connected (cleanup) vs a node that connected but lost connection (e.g. network partition, don't cleanup). 
The previous code assumed that the timestamp would be nil. There is a note on this here: https://github.com/kubernetes/kubernetes/blob/release-1.17/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1012. The nodelifecycle controller writes status here: …
> Fixed a bug with liveness logic

- pkg/apis/provisioning/v1alpha3/provisioner.go
- pkg/apis/provisioning/v1alpha3/provisioner_validation.go
- pkg/apis/provisioning/v1alpha3/provisioner_validation_test.go
- pkg/controllers/allocation/suite_test.go
- pkg/controllers/node/liveness.go
> Migrates to upstream well known labels

- website/content/en/docs/development-guide.md
per @bwagner5, some users had issues with installing go lang via brew (something about paths?)
change guidance on installing go lang to the official go website. 
> change guidance on installing go lang

- website/content/en/docs/development-guide.md
in this guide https://karpenter.sh/docs/development-guide/ and the link embedded here (below) does not work:
> If you created your cluster on version 1.19 or above, you may need to tag your subnets as mentioned here.
I changed the link to use a hugo reference, instead of linking to the old github content. 
> fix link to subnet tagging in development guide

- pkg/controllers/allocation/binpacking/packable.go
- pkg/controllers/allocation/binpacking/packer.go
https://github.com/awslabs/karpenter/issues/625
- Increased performance of bin-packing. This specific optimization found a loop where a terminable case was not being checked which allowed a significant number of loop iterations to be skipped. 
- The loop was responsible for packing pods on to a specific packable node. Once the node was full, the loop would continue unnecessarily. This change also adds another small optimization to the check to determine if the node is full by passing through the smallest pod from the list (it's already sorted when passed thru) and adds it to the currently reserved resources in order to see if anymore progress could possibly be made by continuing through the loop. 
- The terminable case optimization in …
> improve bin-packing performance

- hack/toolchain.sh
- website/content/en/docs/development-guide.md
**Description of problem(s):**
1. `make codegen` fails, even after running `make toolchain`, because of missing executables
2. `make apply` fails because cluster namespace, "karpenter", does not exist
1. Add instruction to update `PATH` with Go workspace's `bin` after running `make toolchain`
2. Add instruction to create namespace, "karpenter"
> update development guide

- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/allocation/binpacking/packable.go
- pkg/controllers/allocation/binpacking/packer.go
N/A
Very minor change to add some clarifying comments and make the unit tests around which instance types you get for Pods that need GPUs more stringent.
Only test code/comments are changing here.
> Add some clarifying comments and make some tests more stringent

- designs/aws-launch-templates-options.md
- pkg/cloudprovider/aws/ami.go
- pkg/cloudprovider/aws/launchtemplate.go
- website/content/en/docs/provisioner-crd.md
https://github.com/awslabs/karpenter/issues/626
Changing the default Launch Template to use alinux2, for now. Will re-add support for Bottlerocket as part of further enhancements to the Launch template. 
Tested by launching nodes that only had taints, only had labels, had both taints and labels, and also ones that had neither.
> Amazon Linux 2 as default AMI

- pkg/controllers/allocation/controller.go
- pkg/controllers/allocation/filter.go
https://github.com/awslabs/karpenter/issues/656
```
karpenter-controller-7cdf8884cf-psvb9 manager 2021-09-08T21:43:22.851Z	ERROR	controller.allocation.provisioner/default	Failed reconciliation, getting subnets, no subnets exist given constraints	{"commit": "eb5139e"}
karpenter-controller-7cdf8884cf-psvb9 manager 2021-09-08T21:43:22.852Z	INFO	controller.allocation.provisioner/default	Watching for pod events	{"commit": "eb5139e"}
karpenter-controller-7cdf8884cf-psvb9 manager 2021-09-08T21:43:32.853Z	INFO	controller.allocation.provisioner/default	Starting provisioning loop	{"commit": "eb5139e"}
karpenter-controller-7cdf8884cf-psvb9 manager 2021-09-08T21:43:32.853Z	INFO	controller.allocation.provisioner/default	Waiting to batch …
```
> Added success logging to the provisioner

- pkg/controllers/node/controller.go
- pkg/controllers/node/emptiness.go
- pkg/controllers/node/expiration.go
- pkg/controllers/node/liveness.go
- pkg/controllers/node/suite_test.go
- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
- pkg/utils/injectabletime/time.go
@anguslees pointed out that we must allow the kubelet to delete pods that are terminating to avoid violating stateful set guarantees if a kubelet is partitioned. Instead, we simply ignore pods that are past their grace window and delete the node. This ensures the guarantee is met, since the pod will be deleted by KCM once the node no longer exists.
1. Modified my provisioner to have a bad endpoint.
2. Created pod
3. Node came online, didn't connect
4. Pod tolerations ran out after 5 minute, pod evicted (w/ grace period 30 sec default)
5. Node deleted by liveness controller (hanging)
6. Node waits for pod to terminate (grace period)
7. Node deleted by termination controller
8. Pod cleaned up by KCM (2 minutes later)
**3. Does this …
> Ignores stuck pods rather than deleting them to avoid stateful set edge cases

- pkg/cloudprovider/aws/launchtemplate.go
n/a
launch template generated by Karpenter no longer includes `yum install` of ssm-agent, which has been present in the eks optimized ami since https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210621 has it already
> remove yum install of ssm-agent

- designs/v1alpha4-api.md
https://github.com/awslabs/karpenter/issues/661
> v1alpha4 API Proposal

- WORKING_GROUP.md
N/A
Meeting group notes for 09/16/2021
> add working group notes for 09/16/2021

- pkg/controllers/allocation/bind.go
- pkg/controllers/allocation/controller.go
- pkg/controllers/allocation/scheduling/scheduler.go
- pkg/metrics/constants.go
#612 "Emit Metrics for Karpenter"
This PR does not fully resolve the issue. More changes will be needed.
Add a histogram metric to record the duration of scheduling operations.
> add allocation scheduling duration metric

- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/allocation/bind.go
- pkg/controllers/allocation/controller.go
- pkg/controllers/allocation/scheduling/suite_test.go
- pkg/controllers/allocation/suite_test.go
Remove decorator pattern from the implementation of the bind time metric to be consistent with the implementation of the scheduling time metric.
> remove bind metric decorator

- website/content/en/docs/faqs.md
N/A
While reading through the FAQ I noticed a few minor things. Might as well clean them up as I'm reading.
- [y] Yes, PR includes docs updates
- [n] Yes, issue opened: *link to issue*
- [n] No
> Minor doc fixes

- pkg/controllers/allocation/binpacking/packer.go
#612 "Emit Metrics for Karpenter"
This PR does not fully resolve the issue. More changes will be needed.
Add a histogram metric to record the duration of binpacking operations.
> add allocation binpacking duration metric

- website/content/en/docs/provisioner-crd.md
N/A
OS and Arch were backwards on provisioner example in docs.
> Fix provisioner docs example where OS and Arch were swapped

- pkg/cloudprovider/aws/launchtemplate.go
N/A
InstanceProfile was still hardcoded in the AWS CloudProvider launch template creation code. This change uses the required "InstanceProfile" parameter from the AWS CP API.
> use instanceProfile from aws cloudprovider constraints api

- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/allocation/controller.go
N/A
Taints configured on the provisioner were not being added to nodes provisioned by the provisioner. Now they are being added. 
> add provisioner taints to nodes

- website/content/en/docs/getting-started/_index.md
**1. The issue, if available:**
Fixed a typo in the getting started guide - "Provisioner", which I noticed when I go through the documentation.
> Fixed a typo in getting started guide.

- pkg/apis/provisioning/v1alpha4/register.go
- pkg/cloudprovider/aws/ami.go
- pkg/cloudprovider/aws/apis/v1alpha1/constraints_defaults.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/allocation/scheduling/scheduler.go
partial fix for https://github.com/awslabs/karpenter/issues/703 - just want to get this out there quickly so people don't run into weird errors
defaults to amd64 if no architectures specified
> default to amd64

- pkg/cloudprovider/aws/ami.go
- pkg/cloudprovider/aws/apis/v1alpha1/constraints_defaults.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/fake/instancetype.go
- pkg/cloudprovider/registry/register.go
- pkg/cloudprovider/types.go
- pkg/controllers/allocation/binpacking/packable.go
- pkg/controllers/allocation/binpacking/packer.go
- pkg/controllers/allocation/scheduling/preferences.go
- pkg/controllers/allocation/scheduling/suite_test.go
- pkg/controllers/allocation/suite_test.go
- pkg/controllers/termination/suite_test.go
https://github.com/awslabs/karpenter/issues/703
Now separates instance types by SSM parameter and passes separate LaunchConfigs to the Fleet API.
```
karpenter-controller-6c847fcb55-9cf2r manager 2021-09-29T01:05:17.055Z	INFO	controller.allocation.provisioner/default	Found 16 provisionable pods	{"commit": "551f2bf"}
karpenter-controller-6c847fcb55-9cf2r manager 2021-09-29T01:05:18.336Z	DEBUG	controller.allocation.provisioner/default	Discovered 309 EC2 instance types	{"commit": "551f2bf"}
karpenter-controller-6c847fcb55-9cf2r manager 2021-09-29T01:05:18.345Z	INFO	controller.allocation.provisioner/default	Computed packing for 15 pod(s) with instance type option(s) [m5.2xlarge]	{"commit": "551f2bf"} …
```
> AWS Cloudprovider now supports architecture flexibility in a single fleet request

- pkg/controllers/allocation/filter.go
- pkg/controllers/node/emptiness.go
- pkg/utils/pod/scheduling.go
N/A
I ran into a few problems running Karpenter on kOps because kube-proxy is deployed as a static pod. Static pods have owner references to the node resource they are running on. This change checks if a pod is a static pod when performing karpenter's node emptiness check. Static pods shouldn't hold up node eviction since they are effectively an agent similar to a daemonset which karpenter already ignores.
> ignore static pods owned by a node in node emptiness check

- pkg/cloudprovider/aws/launchtemplate.go
- pkg/controllers/allocation/bind.go
- pkg/controllers/node/liveness.go
N/A
- Output userdata script to EC2 Console for easier debugging
- Up the node liveness timeout from 5 to 15 mins to account for custom LTs that take longer to bootstrap (like when using the default kops LT).
> Increase node liveness timeout to 15 min

- charts/karpenter/templates/controller/deployment.yaml
- cmd/controller/main.go
- pkg/utils/env/env.go
N/A
- Allow ENV vars to be used to configure CLI args (easier w/ Helm). 
- Precedense: CLI Arg, ENV Var, hard coded default   
- Set default QPS for kubernetes client to 200 base, 300 burst QPS. 10x the default values to allow karpenter to bind pods to nodes without getting client-side throttled often. 
Docs Issue: https://github.com/awslabs/karpenter/issues/722
> add kube client qps configuration w/ env vars and cli overrides

- pkg/controllers/allocation/scheduling/preferences.go
- pkg/controllers/allocation/scheduling/suite_test.go
- pkg/scheduling/nodeaffinity.go
- pkg/utils/env/env.go
- website/content/en/docs/getting-started/_index.md
> Fixed a bug with the OR operator in Node Affinity

- website/content/en/docs/getting-started/_index.md
N/A
- Update getting started guide to reference latest version 0.3.4
> reference latest version 0.3.4 in getting started guide

- pkg/cloudprovider/aws/launchtemplate.go
n/a
Until can figure out how to get it working - was getting errors like
so:
Oct  4 16:57:28 ip-192-168-160-221 kubelet: E1004 16:57:28.770481    8031 remote_runtime.go:86] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
in kubelet logs on eks gpu optimized AMI-based instances
> temporarily switch back to docker for nvidia GPUs

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
https://github.com/awslabs/karpenter/issues/713
Label aws nodes w/ capacity-type via user-data (kubelet args) and when initially creating the node object.
> label capacity type on nodes in userdata and when creating initial node resource

- API.md
- Makefile
- charts/karpenter/templates/karpenter.sh_provisioners.yaml
- pkg/apis/provisioning/v1alpha4/provisioner_status.go
N/A
the latest controller-gen doesn't work with the `trivialVersions` flag
> upgrade to controller-gen 0.7.0

- cmd/controller/main.go
- pkg/cloudprovider/registry/register.go
- pkg/controllers/metrics/node/controller.go
- pkg/controllers/metrics/node/counter.go
#612 "Emit Metrics for Karpenter"
This PR does not fully resolve the issue. More changes will be needed.
Add a controller that runs periodically, and in response to some provisioner events, and publishes different counts of nodes broken out by zone, instance-type, etc.
> add node metrics controller

- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
n/a
Launch templates were getting generated spuriously if labels/taints (which make their way into the user data for the instance) were in a different order (even if equivalent). This fixes that by always sorting, and adds a unit test to catch (verified test failed with old code).
> [AWS] Fix spurious launch template generation

- pkg/cloudprovider/aws/launchtemplate.go
> Minor cleanup on launch template taint sorting logic

- TROUBLESHOOTING.md
- website/content/en/docs/getting-started/_index.md
> Updating EC2 Spot SLR guidance

- pkg/controllers/node/liveness.go
N/A
This sets a RequeueAfter on the liveness reconciler result, if it's been less than `LivenessTimeout` since the node was created. This ensures that even if there's no more subsequent node events we still consider the worker node for termination later. 
If you don't do so, you may enter into a runaway scaling problem where Karpenter will keep launching new nodes and pods indefinitely. The pods get stuck in `Terminating` state and the liveness reconciler never terminates the old `NotReady` worker nodes because no new node events are being generated and therefore the reconciler is never triggered. 
How to reproduce the issue?
Configure Karpenter to launch worker nodes in a subnet that has no network connectivity. For example my …
> Set RequeueAfter so liveness subreconciler fires when no more node events

- pkg/apis/provisioning/v1alpha5/provisioner.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instancetypes.go
N/A
1. The AWS CP InstanceTypes provider was using a defer func to cache results. If the DescribeInstanceTypes call err'd for any reason, the defer block still runs and caches an empty value. On subsequent reconciliations, the scheduler would not fill in well known labels causing this logging:
```
2021-11-08T22:39:28.831Z	INFO	controller.allocation.provisioner/default	Ignored pod test1-basic-0-774f48fcd-hkf85/koi-test3, kubernetes.io/arch is too constrained: 
kubernetes.io/os is too constrained: 
node.kubernetes.io/instance-type is too constrained: 
```
2. The test I was running received a RequestLimitExceeded on the DescribeInstanceTypes call and resulted in an empty set of instance types cached. 
```
2021-11-08T22:39:23.117Z …
```
> fix aws cp caching empty instance types set

- website/content/en/docs/getting-started/_index.md
N/A
- Update docs for Helm installing a default provisioner now. Just skip-crd install in getting started guide for now since we'll probably need to think through how to present that.
- Add `clusterName` and `clusterEndpoint` args to helm chart doc 
> modify docs for helm default provisioner crd

- pkg/controllers/allocation/scheduling/scheduler.go
- pkg/controllers/allocation/suite_test.go
- pkg/test/environment.go
> Fixed a bug where Karpenter node labels were accidentally removed

- WORKING_GROUP.md
> Added working group notes

- pkg/controllers/allocation/launcher.go
I remember it used to be there but seems to have gotten lost in some
PR
N/A
Just make sure to keep track of the errors from parallel Bind calls.
> fix error handling that somehow got dropped

- pkg/cloudprovider/aws/ami.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/securitygroups.go
- pkg/cloudprovider/aws/subnets.go
- pkg/controllers/allocation/scheduling/preferences.go
n/a
Clean up code to use `SetDefault` on caches rather than manually pass in the default value.
> Use cache.SetDefault instead of Set since we're always using default

- Makefile
- charts/karpenter/templates/controller/deployment.yaml
- charts/karpenter/templates/default_provisioner.yaml
- charts/karpenter/templates/webhook/deployment.yaml
- pkg/controllers/manager.go
- website/content/en/docs/getting-started/_index.md
N/A
- When adding the default provisioner to the helm chart (https://github.com/awslabs/karpenter/pull/786), there is a race condition if you rely on defaulting from the webhook deployment since the provisioner resource is applied at the same time the webhook pod is coming online.  
- This change moves the default provisioner to a helm `post-install-hook` resource. Helm resources applied in a post-install-hook are applied after the regular release resources are applied and are technically not part of the release. If you specify the `--wait` flag when helm installing, the post-install-hook will wait until release resources are in a Ready state. So, I have added readiness probes to both the controller and webhook deployments so that …
> move default provisioner to helm post-install hook

- designs/limits.md
Discusses limits to the amount of resources that Karpenter provisions. I've left implementation details out of here but wanted to document and align on our thinking about this before I move forward with code changes. 
N/A
Just a doc.
Docs will come in once we've implemented the thing.
> Adds design doc to discuss Karpenter limits

- pkg/cloudprovider/aws/apis/v1alpha1/tags.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
https://github.com/awslabs/karpenter/issues/793
- Tag all fleet launches w/ managed tags and provisioner tags. Previously this only worked when using the LT that karpenter generates. This now works with custom LTs.
> always tag instances with managed tags and provisioner tags

- pkg/controllers/provisioning/provisioner.go
N/A
- During scale tests, I ran into Karpenter running out of memory and restarting, with a large batch of pods that built up which causes Karpenter to continuously fall over.  The same thing can happen if Karpenter is started when there is already a large build up of pods. 
- This change adds a MaxPodsBatch set at 2,000 initially. This limit is very high for average cluster configurations and is adequate for large scale-ups as well. 
- If Karpenter does come back online w/ a huge batch of pods, it can progress a little more quickly as well since it doesn't need to wait for the 1 sec idle timeout:
```
karpenter-controller-7b69b7ff89-rpcbg manager 2021-11-19T19:13:06.789Z	INFO	controller.provisioning	Batched 2000 pods in 32.78526ms …
```
> add a max pod batch to prevent large build ups

- pkg/cloudprovider/aws/apis/v1alpha1/provider.go
- pkg/cloudprovider/aws/suite_test.go
https://github.com/awslabs/karpenter/issues/818
Tested by deleting my webhooks and then removing the provider from my provisioner spec. The error was identical to what the customer reported.
> Protect the aws cloud provider from panicing if the provider-non-nil invariant is violated

- pkg/apis/provisioning/v1alpha5/constraints.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/fake/instancetype.go
- pkg/controllers/provisioning/binpacking/packable.go
- pkg/controllers/provisioning/scheduler.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/suite_test.go
- pkg/test/daemonsets.go
- pkg/test/expectations/expectations.go
> Fixed a bug where daemonsets weren't correctly included in binpacking calculations

- website/content/en/_index.html
- website/content/en/pre-docs/getting-started/_index.md
- website/layouts/shortcodes/github.html
#828 
Add GitHub stars button to homepage and getting started guide.
It fetches the current star count with a basic get request to api.github.com
- [ x ] Yes, PR includes docs updates
> add GitHub stars button

- pkg/controllers/provisioning/binpacking/packer.go
- pkg/controllers/provisioning/scheduler.go
N/A
- The packing log that should tell how many nodes it packed to and how many pods it packed was incorrectly logging a single node packing even when node quantity was > 1. 
Example bad log: 
```
2021-11-09T17:48:28.330Z	INFO	controller.allocation.provisioner/default	Computed packing for 127 pod(s) with instance type option(s) [c6i.32xlarge m6i.32xlarge]	{"commit": "82226ca"}
2021-11-09T17:48:28.542Z	INFO	controller.allocation.provisioner/default	Computed packing for 71 pod(s) with instance type option(s) [c5.18xlarge c5d.18xlarge c5n.18xlarge c6i.24xlarge c5d.24xlarge c5a.24xlarge c5.24xlarge c5ad.24xlarge c6i.32xlarge m5d.24xlarge m6i.24xlarge m5.24xlarge m5a.24xlarge m5ad.24xlarge m5dn.24xlarge m5n.24xlarge m6i.32xlarge …
```
> fix binpacking log to show proper node quantity and pods

- website/content/en/pre-docs/getting-started/_index.md
- website/content/en/pre-docs/getting-started/grafana.md
the getting started guide is a bit lengthy
move the grafana dashboards section to a subpage
- reduces getting started guide length
- increases discoverability of grafana dashboards content 
- [ X ] Yes, PR includes docs updates
> move grafana to subpage

- website/content/en/pre-docs/cloud-providers/AWS/aws-spec-fields.md
- website/content/en/pre-docs/reference/_index.md
- website/content/en/pre-docs/reference/faqs.md
- website/content/en/pre-docs/reference/provisioner-crd.md
As per our new docs organization, I moved the FAQ and provisioner CRD files to a new Reference section. I believe @ellistarn suggested some of the FAQ info is out of date and we might want to enhance the provisioner section. So I'm making this a WIP to work on those sections.
> Moved faq and provisioner to new reference section

- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/scheduling/controller.go
N/A
- Fix pod binding issue where the provisioner would try to bind the pod twice resulting in bind failure logging. 
- Renamed helper func `IsUnschedulable` to `isSchedulable` 
- `IsUnschedulable` doesn't make sense to describe what the function does. Although the func does do one check to determine if kube-scheduler is failed to schedule the pod, it also does a number of other checks such as if the pod is not already scheduled to a node.  I think it makes more sense to name the func in the context of Karpenter's view of schedulable, hence, `isSchedulable`. 
> fix duplicate bind issues

- website/content/en/docs/getting-started/_index.md
Adding the documentation because of https://github.com/aws/karpenter/pull/817
> added default provisioner limits into docs

- go.mod
- go.sum
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/subnets.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/test/expectations/expectations.go
https://github.com/awslabs/karpenter/issues/371
Finally - the exhilirating conclusion to my set of code changes on ice caching! All the changes I've made fit nicely within the AWS cloud provider
* I added a cache in the InstanceProvider. I debated a bunch with myself for where this should live and decided that it was cleaner to do that than to have the InstanceProvider pass the ICEs back to the cloudprovider to manage it. I liked the idea that the InstanceProvider would encapsulate the interactions with Fleet. 
* After a discussion with Ellis regarding my confusion on the constraints being passed into GetInstanceTypes, I removed the erroneous filtering in the SubnetProvider that was constraining AvailabilityZones (the only place …
> Implement ICE caching for AWS cloud provider and fix bug in filtering for SubnetProvider

- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/node/suite_test.go
- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/scheduling/suite_test.go
- pkg/controllers/termination/suite_test.go
- pkg/test/expectations/expectations.go
@felix-zhe-huang brought up an odd behavior where unconstrained pods would schedule randomly if multiple provisioners were defined. Eventually I'd like to define a `provisioner.spec.priority` feature, but in the short term, we will just alphabetize to make this deterministic. 
> Priorize provisioners alphabetically if multiple match

- go.mod
- pkg/controllers/metrics/controller.go
- pkg/controllers/node/controller.go
- pkg/controllers/termination/controller.go
> Minor logging touchups

- website/content/en/docs/getting-started/_index.md
- website/content/en/pre-docs/getting-started/_index.md
N/A
- Move provisioner limits docs to pre-docs
> Fix provisioner limit docs

- pkg/controllers/node/controller.go
N/A
- Do not error in the node controller when no provisioners exist
> do not error when no provisioners exist in node controller

- website/content/en/pre-docs/getting-started/_index.md
> Reduced termination grace period for getting started

- website/content/en/pre-docs/tasks/_index.md
- website/content/en/pre-docs/tasks/running-pods.md
Added a new "Tasks" nav to the docs, along with a new Tasks section called "Running Pods" that describes how application developers can set pod constraints that are consumed by Karpenter
> Add Running Pods task to docs

- pkg/apis/provisioning/v1alpha5/limits.go
- pkg/apis/provisioning/v1alpha5/provisioner_validation.go
- pkg/apis/provisioning/v1alpha5/suite_test.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/launcher.go
- pkg/utils/parallel/workqueue.go
N/A
Some minor cleanups to `chan` usage per Concurrency in Go book. The main thing is it is good to close when possible, and also it should be clear who owns channel (usually owner should only be able to write/close and reader should only read), using either `<-chan` or `chan<-` types.
Also, I don't understand why provisioner limits are required, so reverted that. But I am probably missing something and someone will point out why :-)
> Some chan cleanups

- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/scheduling/scheduler.go
This bug is caused by the provisioners controller comparing the state of the current provisioner to the persisted provisioner state and the mutation happening in hostname topology. The scheduling logic mutates the provisioners' requirements, which causes the comparison to inadvertently force refresh the provisioner while nodes are being launched. This causes the provisioner to be drained, which can happen after launching capacity but before binding the pods. This results in multiple scale out (and eventual self-healing / scale-in).
The bug is due to me violating my own principles about not mutating state: https://github.com/aws/karpenter/blob/5d5798b5fefc757ef353889204c56138d8042066/pkg/controllers/provisioning/scheduling/topology. …
> Fixed a bug where hostname topology launched extra nodes

- website/content/en/pre-docs/AWS/constraints.md
- website/content/en/pre-docs/concepts/_index.md
- website/content/en/pre-docs/tasks/deprov-nodes.md
- website/content/en/pre-docs/tasks/provisioning-task.md
- website/content/en/pre-docs/tasks/running-pods.md
Pass through the docs to clean up broken links and formatting errors.
> Fixed broken links and formatting errors

- README.md
Removed to reduce confusion with GA launch.
> Remove pre-prod wording from README

- charts/karpenter/templates/webhook/deployment.yaml
- charts/karpenter/values.yaml
When using a custom CNI in AWS EKS, the control plane will not run in same CNI, so to use webhooks, they must be exposed via the host network.
Add hostNetwork flag to webhook deployment
> Support custom CNIs

- website/content/en/docs/getting-started/_index.md
The Getting Started link is pointing to the old version of the docs (v0.4.3-docs), to fix this the file `website/content/en/docs/getting-started/_index.md` should contains the same menu options as the one in `website/content/en/v0.4.3-docs/getting-started/_index.md`.
basically adding:
```
menu:
main:
weight: 10
```
> Fix the Getting Started link to point to the current docs

- charts/karpenter/templates/controller/rbac.yaml
- charts/karpenter/templates/webhook/rbac.yaml
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
#554 
reformat rbac file of webhook as per #554 
> chore: reformat webhook rbac file

- charts/karpenter/templates/controller/deployment.yaml
- charts/karpenter/templates/webhook/deployment.yaml
- charts/karpenter/values.yaml
**1. Issue:**
The number of replicas for the controler and the webhook are not currently exposed on the helm chart
I have modified both templates to use the value provided using helm (it's default value is still 1)
> Allow controller/webhook replicas to be set using helm values

- pkg/controllers/node/suite_test.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/scheduling/suite_test.go
- pkg/controllers/termination/suite_test.go
- pkg/test/expectations/expectations.go
https://github.com/aws/karpenter/issues/901
> Updated expectations to wire through contexts

- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/scheduling/controller.go
- AWS Cloud Provider defaults to [ on-demand ] if nothing is specified
- if [ on-demand, spot ] is specified, spot will be prioritized if offerings are available
- if spot offerings become unavailable, on demand will be selected
> Fixed a bug where spot capacity was not prioritized if flexible to both spot and on demand capacity

- charts/karpenter/templates/controller/deployment.yaml
- charts/karpenter/templates/webhook/deployment.yaml
We currently set `fsGroup` in the deployment spec for the `controller` and `webhook`, but this is fixed in k8s versions 1.19+. This was added into the spec a while ago, so committing the change here for future reference.
https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8#issuecomment-636888074
> Added note fsGroup removal from deployments

- cmd/controller/main.go
- pkg/controllers/manager.go
- pkg/test/expectations/expectations.go
> Cleaned up stray contexts in test expectations

- charts/karpenter/README.md
- charts/karpenter/templates/webhook/deployment.yaml
- charts/karpenter/values.yaml
No issue
This change allows the override of the port used by the webhook deployment when using the Helm chart. This is useful in clusters where the AWS CNI is not used (host networking is required) and we want to ensure pods don't accidentally step on each other's toes if we have other webhook admission controllers. We're specifically mapping the ports used by these controllers to prevent these types of collisions, so having the ability to override the port is quite useful.
> Allow override of webhook port in Helm chart

- charts/karpenter/crds/karpenter.sh_provisioners.yaml
- pkg/apis/provisioning/v1alpha5/provisioner.go
> Updated an inaccurate comment

- hack/toolchain.sh
N/A
- Upped k8s bins for testing from 1.19 to 1.21 
- Currently, Karpenter's `make toolchain` fails on arm64 (m1) macs because of kubebuilder's `setup-env` which downloads k8s component binaries which are not available for the darwin/arm64 platform.  Macs with arm64 processors are able to run x86 compiled binaries using Rosetta virtualization which happens transparently to the user when executing an x86 binary. 
This change overrides the machine's architecture to amd64 if running on an arm64 mac. Previously, the command would fail to fetch the binaries and tests could not be run.  
> fix toolchain install for arm64 mac

- website/config.toml
- website/content/en/docs/getting-started/_index.md
- website/content/en/docs/reinvent.md
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
#912 
an attempt toward docs release automation
we define a site param and use it in `docs` so that it stays consistent.
> docs: use site params to reference latest release

- website/content/en/docs/development-guide.md
> Updated developer guide with additional guidance

- website/content/en/docs/AWS/constraints.md
Is the capital letter S intended between the words 'Group' and 'Selector'?
> Fix a docs typo

- pkg/apis/provisioning/v1alpha5/register.go
- pkg/apis/provisioning/v1alpha5/requirements.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/fake/instancetype.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/binpacking/packable.go
- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/suite_test.go
https://github.com/aws/karpenter/issues/905
> Implemented support for kubernetes.io/os

- pkg/cloudprovider/fake/instancetype.go
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
i thought `kubernetes.io/os` values is from `runtime.GOOS` as defined by Go. the list is here 
https://github.com/golang/go/blob/a19e72cb89fd33e5bf1474887e267806f65b7a40/src/go/build/syslist.go#L10
```
const goosList = "aix android darwin dragonfly freebsd hurd illumos ios js linux nacl netbsd openbsd plan9 solaris windows zos "
```
in there, macOS is darwin instead of `mac`.
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-os
> fix: use darwin instead of mac for kubernetes.io/os label

- website/content/en/docs/concepts/_index.md
Related to #942
Hello 👋 
This notes has been confusing me since I read  it. At first, I thought `podAntiAffinity` would cause scalability issues for the deployments using them, but reading further around `topologySpreadConstraints` (especially its KEP), it seems to be an issue for scalability of the Kubernetes Scheduler.
Do they plan to deprecate `podAffinity`/`podAntiAffinity`? It has been mentioned, but no concrete action toward it.
Or do they plan to improve them? They seem to be some activity in this direction (e.g. kubernetes/enhancements#2249), thus should Karpenter plan to actually support them? (And update the doc to something like "Karpenter doesn't support them for the moment (You can follow their consideration by …
> docs(concepts): Clarify podAffinity/podAntiAffinity note

- pkg/controllers/metrics/nodes.go
Signed-off-by: Tuan Anh Tran <me@tuananh.org>
use `v1.ConditionTrue` instead of `true` string for comparison.
> use v1.conditiontrue instead of string true for compare

- pkg/controllers/scheduling/preferences.go
https://github.com/aws/karpenter/issues/917
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x196a938]
goroutine 10169 [running]:
github.com/aws/karpenter/pkg/controllers/scheduling.(*Preferences).removeRequiredNodeAffinityTerm(0xc000973a48, 0xc000a7cef8)
github.com/aws/karpenter/pkg/controllers/scheduling/preferences.go:93 +0x38
github.com/aws/karpenter/pkg/controllers/scheduling.(*Preferences).relax.func2(0x0)
github.com/aws/karpenter/pkg/controllers/scheduling/preferences.go:67 +0x25
github.com/aws/karpenter/pkg/controllers/scheduling.(*Preferences).relax(0xc00093bb00, {0x2630278, 0xc003b39dd0}, 0xc00058e000) …
```
> Fixed a crash when affinity is defined but requiredaffinity is nil

- pkg/controllers/node/emptiness.go
- pkg/utils/pod/scheduling.go
https://github.com/aws/karpenter/issues/946
There are 5 pod phases [here](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase) which we use to determine emptiness criteria. `Failed` and `Succeeded` are both phases that indicate that all containers on the pod are completed and terminated, so this will not interrupt pod workloads.
> Added succeeded pods to emptiness criteria

- website/content/en/docs/getting-started-with-terraform/_index.md
#926 
Created a Getting Started with Terraform doc
> Add getting started using Terraform doc

- website/content/en/docs/getting-started/_index.md
- website/content/en/docs/getting-started/grafana-values.yaml
- website/content/en/docs/getting-started/prometheus-values.yaml
N/A
- Save grafana and prometheus curl'd values.yaml files to a file so the next line can be copy and pasted.
> fix yaml download cmds in grafana docs

- pkg/cloudprovider/aws/apis/v1alpha1/provider_validation.go
- pkg/cloudprovider/aws/apis/v1alpha1/tags.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
- website/content/en/docs/AWS/provisioning.md
https://github.com/aws/karpenter/issues/944
These changes allow the EC2 "Name" tag to be set in the provisioner spec as:
```
spec:
provider: 
tags:
Name: <custom-name>
```
If the Name tag is not supplied in the spec, the logic falls back to the previous default value of `Name: karpenter.sh/<cluster-name>`
- [ X] Yes, PR includes docs updates
**4. Testing**
All local tests passed
```
$ make test
ginkgo -r
[1639147378] Validation - 18/18 specs •••••••••••••••••• SUCCESS! 1.195387ms PASS
[1639147378] CloudProvider/AWS - 23/23 specs ••••••••••••••••••••••• SUCCESS! 30.781316015s PASS
[1639147378] Node - 18/18 specs •••••••••••••••••• SUCCESS! 10.892751879s PASS
[1639147378] Controllers/Provisioning …
```
> Allow EC2 "Name" tag to be supplied in the provisioner spec

- pkg/controllers/provisioning/binpacking/packable.go
N/A
Packables GPUs were previously validated per GPU. This PR collapses the individual validations into one func that loops through the GPU resource requests and Instance Type Resource Quantity. 
> collapse packables indv gpu validation into one func

- pkg/controllers/node/emptiness.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/scheduling/topology.go
- pkg/test/expectations/expectations.go
- pkg/test/pods.go
- pkg/utils/apiobject/apiobject.go
- pkg/utils/pod/scheduling.go
https://github.com/aws/karpenter/issues/686
- Terminating and Terminal (e.g. Failed) pods are no longer considered in topology calculations
- Label Selectors are not properly applied 
> Resolved a couple topology bugs

- cmd/controller/main.go
The default user agent for rest clients is the binary name, in this case "controller".
This PR will instead make karpenter show as "karpenter" in access/audit logs, as field owner etc. 
> Set karpenter as user agent for the rest client

- pkg/apis/provisioning/v1alpha5/provisioner_validation.go
- pkg/apis/provisioning/v1alpha5/register.go
- pkg/apis/provisioning/v1alpha5/suite_test.go
- pkg/cloudprovider/aws/launchtemplate.go
**2. Description of changes:*
kOps require two labels set on Nodes: `kops.k8s.io/instancegroup` and `kops.k8s.io/gpu`.
The latter is especially important as any pod using the `nvidia` runtimeclass will get that label as nodeSelector.
To make this more future proof, I allowed the entire `kops.k8s.io` domain as there will not be a case where these labels are restricted from Karpenters point of view.
> Allow kOps to set labels required for cluster operations

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/utils/options/options.go
As of k8s 1.23, CCM supports both instance ID (resource name) and private dns (ip name) based naming.
It is not possible for karpenter to determine when which convention is used, and this may also depend on the installer used.
Therefore this is added as a CLI argument.
Fixes #927
This adds a CLI flag for the node naming convention.
This is AWS specifc, so I added an "AWS" prefix. I think this is the first "global" cloud provider setting, so I was not sure how you wanted to name this.
I think a CLI arg for this is the only way of fixing this issue. Trying to parse k8s version and whether or not the external CCM is used is a bit fragile. It is also not given that the external CCM is the "official" one.
**3. Does this change impact …
> Make it possible to set node naming convention

- charts/karpenter/templates/webhook/webhooks.yaml
The Webhooks resources generated by the Helm Chart are not the same that Karpenter redeploys.
This is annoying when using a tool like ArgoCD to deploy Karpenter because it never converges.
> fix: fix Helm Chart

- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/metrics/cloudprovider.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/provisioner.go
None
Previously, the latency recorded for the `CloudProvider.Create()` method may have missed some latency.  Now the latency "start time" is set correctly.
> fix CloudProvider metric

- Makefile
- charts/karpenter/Chart.yaml
#1048 helm search repo should show the app version feature good-first-issue help-wanted
Add 'appVersion' variable to Chart.yaml
> helm search repo should show the app version (#1048)

- .gitignore
- Makefile
- hack/feature_request_reactions.py
- hack/label_issue_count.py
N/A
This PR adds a couple simple python scripts to analyze the GitHub issues for the project. The first, `hack/feature_request_reactions.py`, creates a CSV file with the number of "+1s" for each feature request. The second, `hack/label_issue_count.py`, counts the number of open issues for each label. I've also included a Makefile target (`make issues`) for easy consumption.
> Adds GitHub Issue Analysis Scripts

- pkg/controllers/selection/controller.go
- pkg/utils/pod/scheduling.go
Fixes #1050 
When a pod can evict other pods due to preemption, scheduler sets `pod.Status.NominatedNodeName` to track that scheduler has considered the pod suitable for the given node. As such, Karpenter does not need to take action on the particular node and can instead focus on the evicted pods.
> Don't provision for pods with nominated node

- website/content/en/docs/getting-started/cloudformation.yaml
https://github.com/aws/karpenter/issues/507
eksctl configures CNI to get `AmazonEKS_CNI_Policy` permissions via IAM for Service accounts. The IAM permissions in `AmazonEKS_CNI_Policy` are broad and shouldn't be available for all pods running on the node. See EKS documentation: https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html
Yes, PR includes docs updates
> Remove AmazonEKS_CNI_Policy from KarpenterNodeRole

- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
Karpenter tries to evict mirror pods, but since the mirrored static pod is unaffected this doesn't have any effect other than unnecessary work for the API server.
This PR makes karpenter just skip any mirror pod.
> Do not try to evict mirror pods

- pkg/controllers/provisioning/provisioner.go
- pkg/test/expectations/expectations.go
```
ginkgo -r
[1640902878] Validation - 19/19 specs ••••••••••••••••••• SUCCESS! 1.219976ms PASS
[1640902878] CloudProvider/AWS - 24/24 specs •••••••••••••••••••••••• SUCCESS! 17.236281736s PASS
[1640902878] Node - 18/18 specs •••••••••••••••••• SUCCESS! 14.276780199s PASS
[1640902878] Controllers/Provisioning - 11/11 specs ••••••••••• SUCCESS! 16.538455717s PASS
PASS
testing: warning: no tests to run
Found no test suites, did you forget to run "ginkgo bootstrap"?[1640902878] Controllers/Scheduling - 39/39 specs ••••••••••••••••S•••••••••••••••••••••• SUCCESS! 40.300813943s PASS
[1640902878] Controllers/Scheduling - 3/3 specs ••• SUCCESS! 15.463171157s PASS
[1640902878] Termination - 6/6 specs •••••• SUCCESS! 15.919283898s PASS …
```
> Sped up tests by 1.5seconds/test

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/utils/options/options.go
#1067 
If we are using resource-based naming, we do not need to bail on private DNS name missing.
We still need the describeInstances call for emulating CCM.
> Don't fail on missing privatednsname if using RBN

- pkg/utils/options/options.go
https://github.com/aws/karpenter/issues/1072
> Default to IPName instead of ResourceName

- .github/actions/spelling/expect.txt
- charts/karpenter/templates/webhook/deployment.yaml
Attempting to override `KUBERNETES_MIN_VERSION` per this error log:
> 2022-01-03T22:23:16.180Z        FATAL   webhook Version check failed    {"commit": "5047f3c", "error": "kubernetes version \"1.19.13-eks-8df270\" is not compatible, need at least \"1.20.0-0\" (this can be overridden with the env var \"KUBERNETES_MIN_VERSION\")"}
`helm template` render shows that custom envVars placed in `values.yaml` have incorrect indentation.
Example:
```
env:
- name: CLUSTER_NAME
value: 
- name: CLUSTER_ENDPOINT
value: 
- name: SYSTEM_NAMESPACE
valueFrom:
fieldRef:
fieldPath: metadata.namespace
- name: KUBERNETES_MIN_VERSION 
value: 1.19.0-0 
```
Bumping indentation for envVars from `10` to `12`. This keeps the render consistent with …
> bump indents for webhook envVars to 12

- website/content/en/docs/AWS/provisioning.md
Looks like there was a copy/paste typo in the securityGroupSelector documentation example.
> docs/AWS: Fix typo for securityGroupsSelector

- pkg/controllers/provisioning/batcher.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/selection/controller.go
- pkg/test/expectations/expectations.go
https://github.com/aws/karpenter/issues/1065
The aim of this PR is to reduce the potential failure modes of the batching logic after reports of "pod stuck". We haven't been able to successfully reproduce this -- however, I have a theory as to how this could happen
- The current logic is count-based, and returns n messages to unblock n pods.
- If somehow the count is too low, one of the pods will remain stuck
- By moving to a channel (context) close mechanism, we remove this possibility.
> Rewrote batching logic to no longer rely on a results channel

- charts/karpenter/Chart.yaml
- charts/karpenter/templates/100-config-logging.yaml
- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/controller/deployment.yaml
- charts/karpenter/templates/controller/rbac.yaml
- charts/karpenter/templates/serviceaccount.yaml
- charts/karpenter/templates/webhook/deployment.yaml
- charts/karpenter/templates/webhook/rbac.yaml
- charts/karpenter/templates/webhook/webhooks.yaml
- charts/karpenter/values.yaml
Refactoring Helm labels like in [Helm documentation](https://helm.sh/docs/chart_best_practices/labels/)
> Refactoring Helm labels

- website/content/en/docs/getting-started-with-terraform/_index.md
N/A
This PR pins the version of the aws eks module to < 18. That project recently released some breaking changes that break the example in the docs without the pin.
Their release: https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v18.0.0
> Pin version for eks module in getting-started-with-terraform docs

- README.md
I noticed that README still references #provider-aws despite the recent introduction of dedicated #karpenter channel. I'm assuming that we'd want to refer users to the dedicated channel going forward.
> README.md: Refer to #karpenter slack channel

- charts/karpenter/templates/controller/deployment.yaml
- charts/karpenter/templates/webhook/deployment.yaml
N/A
- #1001 added standard k8s labels across all resources and the ability for users to provide labels that are propagated to all resources. Part of that PR also updated the selectorLabels with these additional labels, however, selectorLabels are immutable so when upgrading the chart from the previous, those resources fail to Patch.  This PR removes the additional selectors and sticks with the `karpenter: controller` and `karpenter: webhook` to maintain backwards compatibility.  
tested in my local cluster by updating a previous installation with helm.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix selector labels on helm chart

- website/content/en/docs/concepts/_index.md
- website/content/en/v0.4.3-docs/concepts/_index.md
- website/content/en/v0.5.0-docs/concepts/_index.md
- website/content/en/v0.5.2-docs/concepts/_index.md
Changed wording in the concepts docs from "provision pods" to "schedule pods" per a comment in slack.
> Change "provision pods" to "schedule pods" in docs

- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/scheduling/topology.go
https://github.com/aws/karpenter/issues/1021
Fixes #1021 where if the labelSelector was not provided for a topologySpread, then Karpenter would crash. This fix makes a nil labelSelector select everything per [labelSelector docs](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/#:~:text=An%20empty%20label%20selector%20matches%20all%20objects)
Wrote a unit-test to reproduce the issue, after the fix was implemented, the unit test now passes.
> fix topologySpread nil label selector bug

- website/content/en/docs/concepts/_index.md
- website/content/en/v0.4.3-docs/concepts/_index.md
- website/content/en/v0.5.0-docs/concepts/_index.md
- website/content/en/v0.5.2-docs/concepts/_index.md
Corrected wording in the docs that said scheduling nodes to scheduling pods.
> Fixed scheduling wording

- pkg/cloudprovider/aws/instance.go
https://github.com/aws/karpenter/issues/1088
Only include capacity-type options for the capacity-type being requested since Spot is not available in every region.
Tested provisioning OD and Spot nodes on a cluster
> [AWS] only include capacity-type options for the capacity-type being requested

- website/content/en/docs/AWS/provisioning.md
#1118
add short note clarifying that a security group is only selected when *all* criteria match. 
n/a
> update desc of selecting security groups by tag

- pkg/apis/provisioning/v1alpha5/requirements.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/provisioning/binpacking/packable.go
https://github.com/aws/karpenter/issues/1126
Fixes an issue where if an instance type offering is found to be unavailable and therefore placed in the ICE cache, the binpacking logic could still use the instance type in the packing. 
The bug is occurring in the bin packing's packable validation logic. Packables (Instance Type and Offering) are validated by zone and capacity type separately even though an offering is the tuple of (zone, capacity type). This change validates an offering and removes the independent zone and capacity-type validation.
The issue was originally found while doing load tests where I ran into an Insufficient Capacity Error (ICE). After the ICE, Karpenter behaved very strangely, by throwing "Security Group …
> ICE cache bin-packing validation fix

- charts/karpenter/templates/controller/deployment.yaml
No issue
Adding an explicit name to the metrics port for the controller Service. This is needed to define `ServiceMonitor` objects for Prometheus monitoring, as they can't reference ports by number (for some reason).
Not really tested as it's a pretty unobtrusive update.
> Explicitly name metrics port in deployment's Helm chart template

- website/content/en/docs/tasks/scheduling-pods.md
n/a
add links to description of persistent volume topology scheduling. 
specifically, links to desc of binding mode and CSI. 
netlify
> add links to desc of storage scheduling

- pkg/apis/provisioning/v1alpha5/register.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider_defaults.go
- pkg/cloudprovider/aws/apis/v1alpha1/tags.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/getting-started/_index.md
https://github.com/aws/karpenter/issues/1017
Removed discovery via cluster name to avoid tag limitations for multi-cluster discovery. Instead, users must define their own discovery mechanisms for their use case. Moved cluster-based discovery to the getting started guide.
> Remove subnet and security group selector defaulting.

- website/content/en/preview/concepts/_index.md
- website/content/en/preview/getting-started-with-terraform/_index.md
- website/content/en/preview/getting-started/_index.md
- website/content/en/v0.5.0/getting-started/_index.md
- website/content/en/v0.5.2/concepts/_index.md
- website/content/en/v0.5.2/getting-started/_index.md
- website/content/en/v0.5.3/concepts/_index.md
- website/content/en/v0.5.3/getting-started-with-terraform/_index.md
- website/content/en/v0.5.3/getting-started/_index.md
https://github.com/aws/karpenter/issues/1159
Issue 1159 noted some broken links. The directory structure changed since that was filed, so I made the corrections in this PR.
> Fixed broken links to provisioner docs

- website/content/en/preview/getting-started-with-terraform/_index.md
#1017
Updates the TF guide to...
1. Add tags to subnet and security groups
2. Use those tags in the Provisioner
> Update TF guide for removal of default subnet/security group selector

- website/content/en/preview/tasks/deprovisioning.md
**1. Does this change impact docs?**
> Added deprovisioning docs to preview folder

- website/content/en/preview/getting-started/cloudformation.yaml
- website/content/en/v0.5.3/getting-started/cloudformation.yaml
- website/content/en/v0.5.5/getting-started/cloudformation.yaml
https://github.com/aws/karpenter/issues/1185
Resolves issues where users without IRSA got node NotReady. Restoring this until we find a longer term path.
> Restore CNI Policy

- website/content/en/preview/provisioner.md
- website/content/en/preview/tasks/set-resource-limits.md
#1003 
add new task for setting resource limits.
From standup, @ellistarn indicated non-specific complexities associated with "eventual consistency" regarding resource limits? 
I'm open to moving this under the "run pods" task (subpage or new section), where do you think @chrisnegus ?
requesting review from @suket22 
tested on my own cluster (only tested CPUs)
> init draft of desc of resource limits

- charts/karpenter/README.md
- charts/karpenter/templates/controller/deployment.yaml
- charts/karpenter/templates/webhook/deployment.yaml
- charts/karpenter/values.yaml
- pkg/cloudprovider/aws/apis/v1alpha1/provider.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider_validation.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/utils/options/options.go
- website/content/en/preview/AWS/provisioning.md
- website/content/en/preview/getting-started-with-terraform/_index.md
- website/content/en/preview/getting-started/_index.md
#909 
- Adds the ability to set `-default-instance-profile` on the controller, which does as it suggests
- Update default constraints setting to use the default if one is provided
- Updated the Helm chart to allow setting of this flag and the website to provide a little bit of documentation about it
- Updated unit tests to test for both default setting and for overriding through a Provisioner
I'll fully admit I'm not the best Go programmer, so feel free to tell me how it should be made better. I tried to follow along with what was already there. But, might have missed an easier way …
> Allowing settings of a default instance profile

- pkg/cloudprovider/aws/apis/v1alpha1/tags.go
> Restore ability to override Name tag on AWS

- pkg/apis/provisioning/v1alpha5/constraints.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/metrics/cloudprovider.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/binpacking/packer.go
- pkg/controllers/provisioning/binpacking/packer_test.go
- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/provisioner.go
```
karpenter-controller-5fd6d774d7-vvx85 manager 2022-01-25T23:43:13.689Z	INFO	controller.provisioning	Launched instance: i-0f7267f0ba3b1b7eb, hostname: ip-192-168-81-214.us-west-2.compute.internal, type: m5.large, zone: us-west-2a, capacityType: spot{"commit": "6b76896", "provisioner": "default"}
karpenter-controller-5fd6d774d7-vvx85 manager 2022-01-25T23:43:13.690Z	INFO	controller.provisioning	Launched instance: i-03d5e9a4e6926ae3e, hostname: ip-192-168-78-88.us-west-2.compute.internal, type: m5.large, zone: us-west-2a, capacityType: spot{"commit": "6b76896", "provisioner": "default"}
karpenter-controller-5fd6d774d7-vvx85 manager 2022-01-25T23:43:13.690Z	INFO	controller.provisioning	Launched instance: i-0cfc706bc5b6e328b, …
```
> Parallelize packing and launching

- website/content/en/preview/getting-started-with-terraform/_index.md
Hi I tried [Terraform tutorial](https://karpenter.sh/v0.5.6/getting-started-with-terraform/) and found minor issues. This PR should fix them.
1. Add tag `"karpenter.sh/discovery" = var.cluster_name` because otherwise karpenter cannot find the subnet specified in [provisioner](https://karpenter.sh/v0.5.6/getting-started-with-terraform/#provisioner). (btw I'm very new to karpenter so please teach me if this fix is as expected...)
2. Add a step to create service linked role for spot. It's copied from the [other tutorial](https://karpenter.sh/v0.5.6/getting-started/#create-the-ec2-spot-service-linked-role).
I confirmed tutorial now works with those changes.
By …
> doc: fix getting started with terraform

- Makefile
- website/content/en/v0.5.0/getting-started/_index.md
- website/content/en/v0.5.2/getting-started/_index.md
- website/content/en/v0.5.3/getting-started-with-terraform/_index.md
- website/content/en/v0.5.3/getting-started/_index.md
- website/content/en/v0.5.5/getting-started-with-terraform/_index.md
- website/content/en/v0.5.5/getting-started/_index.md
- website/content/en/v0.5.6/getting-started-with-terraform/_index.md
- website/content/en/v0.5.6/getting-started/_index.md
N/A
- Snapshot docs versions pinned at a particular version were referencing the `latest_release` param. This change backfills the correct versions at each snapshot. [Here's an example of where the docs are wrong](https://karpenter.sh/v0.5.5/getting-started/#:~:text=serviceAccount.create%3Dfalse-,%2D%2Dversion%20v0.5.6%20%5C,-%2D%2Dset%20controller.clusterName) 
- I've also added a command to the `make website` target to replace the `latest_release` param with the version being released.  (used perl since that's more vendor neutral than sed, since mac's default sed is not gnu-sed)
`make website` resulted in the correct snapshot with a hardcoded version.
By …
> fix snapshot docs versions

- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/AWS/launch-templates.md
> support EBS vol encryption in default launch template

- website/content/en/preview/provisioner.md
- website/content/en/v0.5.6/provisioner.md
The `spec.limits.resources.cpu` field should be a string, not an int.
An example in the docs is incorrect
Updated example to be correct
N/A
> Update Provisioner Docs Example

- .github/workflows/ci.yaml
- Makefile
- hack/toolchain.sh
N/A
- added matrix testing for k8s versions 1.19 - 1.21 (for some reason 1.22 doesn't work and 1.18 is missing... so we can investigate those later). There's no added latency since these all kick off in parallel. 
- I removed the dependency of sudo in `make toolchain` since it's unnecessary to install the toolchain.
- https://github.com/bwagner5/karpenter/actions/runs/1767207765
> k8s backtesting within gha

- pkg/controllers/node/emptiness.go
- pkg/controllers/node/suite_test.go
- pkg/test/expectations/expectations.go
#993 
* If ttl has not expired, requeueAfter at the right time. 
* Added a unit test. 
* Tested this manually as well. 
Before it would take a long time to clear up (4 minutes)- 
```
2022-02-02T00:47:51.832Z	INFO	controller.node	Added TTL to empty node	{"commit": "4829931", "node": "ip-192-168-191-121.us-west-2.compute.internal"}
2022-02-02T00:47:54.791Z	INFO	controller.node	Removed emptiness TTL from node	{"commit": "4829931", "node": "ip-192-168-191-121.us-west-2.compute.internal"}
2022-02-02T00:48:11.846Z	INFO	controller.node	Added TTL to empty node	{"commit": "4829931", "node": "ip-192-168-191-121.us-west-2.compute.internal"}
2022-02-02T00:52:13.964Z	INFO	controller.node	Triggering …
```
> Fix emptiness reconciler when ttl not expired

- pkg/apis/provisioning/v1alpha5/requirements.go
https://github.com/aws/karpenter/issues/1109
Add missing region normalization.
> Added failure-domain.beta.kubernetes.io/region to NormalizedLabels

- website/content/en/preview/getting-started-with-terraform/_index.md
N/A
- The terraform getting started guide was referencing different regions
> fix region in tf docs

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
Partially addresses https://github.com/aws/karpenter/issues/1089
Changing the version we default to in-memory to be `$Latest` and not `$Default`
None. Just verified the API supports `$Latest` [in API docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_FleetLaunchTemplateSpecificationRequest.html)
Whoops, adding it now.
> Choose the latest version of the EC2 launchTemplate by default

- pkg/cloudprovider/aws/instance.go
When EC2 takes a longer time to assign the private DNS name of the newly created instance, Karpenter may failed all attends to create the node object due to missing private DNS name.
#1282 
Double the get instance retry to 6 times, one second apart.
This will double the time that a private DNS name can be assigned before Karpenter raises an error.
Unit tests, manually tested.
> Double the node creation retry

- pkg/cloudprovider/aws/ami.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider_defaults.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider_validation.go
- pkg/cloudprovider/aws/apis/v1alpha1/register.go
- pkg/cloudprovider/aws/launchtemplate.go
https://github.com/aws/karpenter/issues/923
Some AMIFamily updates to support:
- Validation
- Defaulting
- Fix a few userData generation issues  
Tested in an EKS cluster using both Bottlerocket and EKS Optimized AMI
> AMIFamily Defaulting and Validation

- pkg/controllers/termination/eviction.go
- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
- website/content/en/preview/tasks/deprovisioning.md
https://github.com/aws/karpenter/issues/1166
Previously, the`do-not-evict` annotation could block termination logic, even if the node was unreachable. This change modifies the `do-not-evict` logic to only apply to evictable pods. Currently, evictable pods exclude
- Pods owned by the node (a.k.a. static pods)
- Pods with deletion time stamp set past their graceful termination period (a.k.a. stuck termination)
- Pods that tolerate the nodes taints (i.e. would reschedule immediately) 
This means that the `do-not-evict` annotation will no longer work for pods in the above categories. Given that we already did not attempt to evict these pods, the semantic holds. However, previously, pods in these categories with the `do-not-evict` …
> Check DoNotEvict after filtering evictable pods to ensure termination can complete.

- website/content/en/preview/faq.md
Replaces the link to non-existent rbac.yaml into the four files it is broken down to after https://github.com/aws/karpenter/pull/1145
> Correct broken links to rbac.yaml

- website/content/en/preview/getting-started/_index.md
- website/content/en/v0.6.1/getting-started/_index.md
#1275 
update the document description on how Grafana dashboards are deployed.
> Update documents about Grafana dashboard deployment

- website/content/en/v0.6.1/faq.md
Replaces the link to non-existent rbac.yaml into the four files it is broken down to after https://github.com/aws/karpenter/pull/1145
> Correct broken links to rbac.yaml for v0.6.1

- pkg/cloudprovider/aws/instancetype.go
N/A
- The kube-reserved overhead calculation was not being applied correctly on the incremental core percentages.
- Printed the overhead calc when investigating the #1306 (this change does not fix that issue) and found that the overhead didn't include the incremental core calc. It only used the initial 100m cpu overhead. 
- After this change, I printed the overhead for r5.12xl and it correctly showed `cpu 290m` of overhead
> Fix overhead calculation to correctly apply kube-reserved cpu

- pkg/apis/provisioning/v1alpha5/provisioner_validation.go
- pkg/apis/provisioning/v1alpha5/requirements.go
- pkg/apis/provisioning/v1alpha5/suite_test.go
closes #1319 
Allow provisioner requirements to use NotIn and DoesNotExist operators
Unit tests
Manual tests with suitable test cases
> Allow NotIn and DoesNotExist operators for provisioner validation

- cmd/controller/main.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/controllers/manager.go
- pkg/controllers/metrics/node/controller.go
- pkg/controllers/node/controller.go
- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/selection/controller.go
- pkg/test/daemonsets.go
- pkg/test/nodes.go
- pkg/test/pods.go
- pkg/test/storage.go
When using functions that format strings (they  ends with an f suffix e.g. `fmt.Errorf`, or `fmt.Sprintf`)  there is no need to  use `err.Error()` in order to get the error message in string. It is sufficient to use `err` because errors in Go implement the `fmt.Stringer` interface allowing an automatic conversion to string when needed.
> Simplify conversion of errors to string in formatted function calls

- pkg/cloudprovider/aws/ami.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider_defaults.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider_validation.go
- pkg/cloudprovider/aws/apis/v1alpha1/register.go
- pkg/cloudprovider/aws/apis/v1alpha1/zz_generated.deepcopy.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/AWS/provisioning.md
- website/content/en/preview/development-guide.md
https://github.com/aws/karpenter/issues/923
- Changed EKSOptimized to AL2 because EKS Optimized is a class of AMIs that can be different AMI Families which are optimized for EKS. 
- Lowercased values expected in the provisioner
- Add support for `ubuntu` as an `amiFamily`
- Adds docs for `amiFamily`
- Tested on an EKS cluster with 2 deployments `inflate-amd64` and `inflate-arm64`. 
- I varied the provisioner `amiFamily` between `al2`, `bottlerocket`, and `ubuntu` scaling each to verify the node becomes ready and the pods go to running.
> support ubuntu amiFamily

- pkg/cloudprovider/aws/ami.go
- website/content/en/preview/AWS/provisioning.md
If the AMI family type used is Bottlerocket and the instance type is an NVIDIA GPU instance the drivers are not available in the generic Bottlerocket AMI. The lookup for arm64 architecture was also dependent on GPU instances but they're not mutually exclusive (eg G5g).
This adds a lookup for Bottlerocket AMIs to use the `-nvidia` variant along with arm64 AMI when needed.
I based the code off the existing AL2 lookups and ran linting and basic tests but did not have the infrastructure in place to deploy it into a live cluster.
> Bottlerocket nvidia

- website/content/en/v0.6.1/concepts/_index.md
None.
Fix typo in link to redirect from concepts to getting started.
It was not.
> website: fix typo in link to getting started

- pkg/controllers/termination/suite_test.go
- pkg/test/expectations/expectations.go
- pkg/test/pods.go
#638
- the pod must be in a non-pending state for eviction  to consider the PDB
- the Status.ObservedGeneration must be >= the pdb.Generation  or the eviction results in a 429 retry with a 10 second delay
Unit testing
> re-enable the PDB eviction test

- pkg/cloudprovider/aws/suite_test.go
Fixing ginkgo line swap, container nodes can't be within a subject node (https://onsi.github.io/ginkgo/#organizing-specs-with-container-nodes)
Unit tests
> fix test typo (Context/It swapped)

- .github/workflows/codeql-analysis.yml
N/A
Adds Github's security scanner to the workflows 
https://github.blog/2020-09-30-code-scanning-is-now-available/
Should be able to see it running on this PR
- [ X] No
> Add codeql security analysis workflow to the repo

- website/content/en/preview/faq.md
Update the FAQ to include update instructions for v0.6.2
> Include the update instructions

- website/content/en/preview/getting-started/_index.md
Few documentation improvements in the getting started guide.
1. Clarify what is meant by configuring the local `aws` cli tool
2. Add export to the environment variable that misses it
3. Add command to allow `kubectl` authenticate against the created EKS cluster
> A few getting started doc improvements

- pkg/cloudprovider/aws/apis/v1alpha1/provider_defaults.go
N/A
Fixing an issue where we'd default the AMIFamily even if a launch template was specified. That would then break in the [validation webhook](https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/apis/v1alpha1/provider_validation.go#L60). 
The provisioner I was using for testing manually - 
```
apiVersion: karpenter.sh/v1alpha5
metadata:
name: default
spec:
limits:
resources:
cpu: 1000
provider:
launchTemplate: myTemplate
subnetSelector:
karpenter.sh/discovery: myCluster
ttlSecondsAfterEmpty: 30
```
First I was able to replicate the failure -
```
for: "../testing/provisionerSpecAMIFix.yaml": admission webhook "validation.webhook.provisioners.karpenter.sh" denied the …
```
> Don't default AMI Family if LaunchTemplate specified

- website/content/en/preview/getting-started/_index.md
- adds missing `\` to command
- avoid using a temp file
- add verification steps for two of the steps
> add missing backsash character in the getting started guide

- website/content/en/preview/getting-started/_index.md
- website/content/en/v0.6.2/getting-started/_index.md
When installing the Helm chart, it throws an error  #1355
Added quotes for the annotation parameters and a missing backslash at the end of the command.
Manually tested by deploying the helm chart in my cluster.
> Fixed the Helm parameter to set the service account annotations #1355

- website/content/en/preview/getting-started/_index.md
- website/content/en/v0.6.3/getting-started/_index.md
N/A
The getting started guide `eksctl create cluster` command is broken.
the current guide has the following:
```
eksctl create cluster << 'EOF'
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
name: ${CLUSTER_NAME}
region: ${AWS_DEFAULT_REGION}
version: "1.21"
tags:
karpenter.sh/discovery: ${CLUSTER_NAME}
managedNodeGroups:
- instanceType: m5.large
amiFamily: AmazonLinux2
name: ${CLUSTER_NAME}-ng
desiredCapacity: 1
minSize: 1
maxSize: 10
iam:
withOIDC: true
EOF
```
if you run the above w/ `--dry-run` to see the generated config, the heredoc passed in does not apply and defaults are taken instead:
```
eksctl create cluster --dry-run << 'EOF'
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
name: …
```
> fix eksctl getting started guide create cluster command

- website/content/en/preview/AWS/provisioning.md
- website/content/en/v0.6.2/AWS/provisioning.md
- website/content/en/v0.6.3/AWS/provisioning.md
The value of `amiFamily` in a Document is incorrect.
[error]
```
$ kubectl apply -f provisioner.yaml
Error from server (BadRequest): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"karpenter.sh/v1alpha5\",\"kind\":\"Provisioner\",\"metadata\":{\"annotations\":{},\"name\":\"default\"},\"spec\":{\"limits\":{\"resources\":{\"cpu\":1000}},\"provider\":{\"amiFamily\":\"bottlerocket\",\"instanceProfile\":\"KarpenterNodeInstanceProfile-xxxxxxxxxx\",\"securityGroupSelector\":{\"karpenter.sh/discovery\":\"xxxxxxxxxx\"},\"subnetSelector\":{\"karpenter.sh/discovery\":\"xxxxxxxxxx\"}},\"requirements\":[{\"key\":\"karpenter.sh/capacity-type\",\"operator\":\"In\",\"valu …
```
> fix: amiFamily values

- charts/karpenter/templates/role.yaml
When installing with custom release name, webhook cannot be created. https://github.com/aws/karpenter/issues/1359
remove the hardcoded resourceName and make it `{{ include "karpenter.fullname" . }}-cert`
[same as secrets](https://github.com/aws/karpenter/blob/main/charts/karpenter/templates/secret-webhook-cert.yaml#L4)
```
helm install . --generate-name --namespace kube-system --version 0.6.3 --dry-run --debug
```
> Fix webhook cert update issue if resource name differs from Helm chart

- .github/workflows/ci.yaml
This will cause https://github.com/aws/karpenter/blob/main/.github/workflows/ci.yaml to run not only on pull_requests but also on push.
A few reasons this is a good idea
- It will update the coverage data of the `main` branch in coveralls.io
- GH will add a check icon to the commit, we currently have that since [this](https://github.com/aws/karpenter/commit/4c55110d70439135763404e24bd6937c0ba569fd) but with this change the check will be more meaningful as it would mean we have done all our tests on this specific commit
It will also have some other less important but possible effects
- An administrator can sometimes ignore the checks in a PR (a Github setting can disable this), the tests will still run and have a sign indicating …
> run GHA on push

- website/content/en/preview/AWS/provisioning.md
> chore: update provisioning configuration docs

- pkg/controllers/termination/eviction.go
Karpenter Controller says as `Did not to evict pod due to PDB violation`. However, it should ideally have messages as `Did not evict pod due to PDB violation`
Have made same changes in the Code for the Issue https://github.com/aws/karpenter/issues/1384
> Fix PDB debug log in the eviction controller

- .github/workflows/ci.yaml
- charts/karpenter/templates/role.yaml
…o.sum as key
Attempt to make the GHA for CI faster by properly caching the go modules and build. Currently it seems like the cache is not as effective since the dependencies are still being deployed 
> Fix GHA cache key for go modules

- .github/workflows/issues.yaml
This is an attempt to keep issues and PRs fresh and relevant
Closes stale issues and PRs.
It will label a PR or issue as stale after 10 days, and if the label is not removed or if there are no new comments it will close the issue or PR.
> Add GHA to close stale issues and PRs

- pkg/controllers/provisioning/binpacking/suite_test.go
https://github.com/aws/karpenter/issues/1338#issuecomment-1039410294
There's a warning in `make test`
```
make test
ginkgo -r
[1645488461] Validation - 52/52 specs •••••••••••••••••••••••••••••••••••••••••••••••••••• SUCCESS! 1.632009ms PASS
[1645488461] CloudProvider/AWS - 41/41 specs ••••••••••••••••••••••••••••••••••••••••• SUCCESS! 11.314522285s PASS
[1645488461] Node - 18/18 specs •••••••••••••••••• SUCCESS! 10.520671872s PASS
[1645488461] Volume - 3/3 specs ••• SUCCESS! 6.879056936s PASS
[1645488461] Controllers/Provisioning - 12/12 specs •••••••••••• SUCCESS! 9.398906116s PASS
PASS
testing: warning: no tests to run
Found no test suites, did you forget to run "ginkgo bootstrap"?[1645488461] Controllers/Scheduling - 44/44 specs …
```
> Add empty test suite to get rid of the Ginkgo warning

- pkg/cloudprovider/aws/launchtemplate.go
Using Bottlerocket with `spec.kubeletConfiguration.clusterDNS` in the provider will fail to generate valid user data (`"[ip]"` instead of `"ip"`), which leads to the nodes not becoming ready.
This change matches the Bottlerocket behavior to the AL2 one, where only the first IP will be picked into the option. Since Bottlerocket OS also only supports a single IP for that option this seems to be the only plausible way atm.
Built a custom controller image and used it in my own EKS cluster w/ IPv6 (where setting the cluster DNS is required). Used `spec.provider.amiFamily: Bottlerocket`.
By submitting this pull request, I confirm that my contribution is made under …
> Fix cluster DNS IP format in Bottlerocket userdata

- pkg/cloudprovider/aws/launchtemplate.go
https://github.com/aws/karpenter/issues/1404
In TOML, bare keys have limitations in the keys that they can contain
([A-Za-z0-9_-]) and strings _must_ be quoted. This change quotes all
keys to properly handle e.g. node labels with slashes in them and also
adds missing quotes for node taint values.
Manually, see https://github.com/aws/karpenter/pull/1406#issuecomment-1049307589
> fix: properly quote Bottlerocket config

- website/content/en/preview/AWS/provisioning.md
- website/content/en/preview/faq.md
- website/layouts/shortcodes/githubRelRef.html
https://github.com/aws/karpenter/issues/1310
- Update AWS Provisioner docs to: 
- use `karpenter.sh/discovery` tags in examples 
- use proper tag `Name` example (it was using the id rather than name)
- perma link code link to version and remove line number anchor
- Netlify preview on PR
> Update AWS Provisioner docs w/ proper tag examples

- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/AWS/provisioning.md
https://github.com/aws/karpenter/issues/1297
- EC2 Fleet only accepts one subnet per AZ. This change will favor subnets w/ more available IP addresses if the multiple subnets are found for an AZ.
- Unit testing 
- Manual testing that existing logic works after change
> [AWS] Favor subnets w/ more IP addresses when launching instances

- .golangci.yaml
- pkg/test/expectations/expectations.go
Enables a check that makes sure all errors are checked. This is good idea specially because we are already checking all errors except only in one test which this PR fixes.
There is really no good reason to leave errors unchecked. Beginners to Go are often surprised by how much error handling they have to do. In my perspective this is one of the beauties of Go. It makes the programmer think and react everywhere things can go wrong and we know at scale things that can go wrong will go wrong. Handling all errors therefore is  part of what it takes to produce high quality and reliable software.
By submitting this pull request, I confirm that my contribution is …
> Enforce error checking in CI

- website/content/en/preview/tasks/pod-density.md
#1216 
add task for configuring pod density
n/a
> new task for config pod density

- website/content/en/preview/provisioner.md
https://github.com/aws/karpenter/issues/1102
update description of Provisioner API
add kubelet to example
add further desc of ttl values
netlify preview
> revise provisioner api description 

- go.mod
- pkg/controllers/metrics/node/controller.go
- pkg/controllers/metrics/node/suite_test.go
- pkg/controllers/metrics/pod/controller.go
- pkg/controllers/metrics/pod/suite_test.go
- pkg/test/expectations/expectations.go
N/A
add some race testing and fix two identified issues
ginkgo -r --race
> Fix metrics controller races

- charts/karpenter/values.yaml
- website/content/en/preview/getting-started/_index.md
Users have been facing issues that would have been resolved by viewing debug logging. Given how we treat debug logging today, it's useful to leave on as default, and users can filter (or turn down) as necessary.
> Enable debug logging by default

- pkg/controllers/selection/controller.go
- pkg/controllers/selection/suite_test.go
- pkg/test/pods.go
- pkg/utils/pod/scheduling.go
N/A
- This adds a deeper check for podAffinity and podAntiAffinity. Before we were only checking if it was nil. There are some helm charts will will expose the podAffinity and anti-affinity in the values.yaml and will therefore populate them as empty instead of not specified. Karpenter would ignore these pods unnecessarily. 
- Tested a pod w/ anti-affinity -> Karpenter ignores pod
- Tested a pod w/ empty anti-affinity -> Karpenter schedules
- Tested a pod w/ no anti-affinity -> Karpenter schedules
> deeper podAffinity and anti-affinity checks

- website/content/en/preview/development-guide.md
Our configmap used to specify logging is no longer called `karpenter-config-logging`. Additionally, we default to `debug` level logs, adding lines to change it as developer desires.
> Fixed logging command

- pkg/controllers/termination/eviction.go
#1414
The eviction API is supposed to only return 429 or 500 status codes when an error is encountered while evicting a pod (per [k8s documentation](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#eviction-api)).  Today, Karpenter only writes a debug log when a 500 or 429 status code is returned from the eviction API, but doesn't account for the case where an unexpected error/status code is received.  This change adds a catch-all so Karpenter will also log unexpected errors from the eviction API.  
Edit: This change also introduces structured logging for log emitted by eviction attempts.  Also, logs the returned error messages reported by the eviction API for consistency, instead of using custom error …
> Add logging for unexpected pod eviction errors

- Makefile
N/A
- Add a make target that serves the hugo docs site locally
`make website` 
> Add Make target to serve the hugo docs site locally

- pkg/controllers/termination/suite_test.go
Fixes #706
Pods can enter/exit the eviction queue rapidly so looking for
them in the queue itself is flaky.  Instead, just check if they've
been evicted.
Unit tests
> remove the expect enqueued for eviction tests

- website/content/en/preview/troubleshooting.md
> Moved troubleshooting to the website

- website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
- website/layouts/shortcodes/script.html
…either release version or preview
This will change the behavior where the scripts are being read from the `preview` directory, and instead use the release directory that comes from the path of the page, for example for the preview version it will read from `./website/content/en/preview/...` and for v0.6.4 it will read from `./website/content/en/v0.6.4/...`.
This allows us to manage the scripts of each version independently should we need to.
> Make script path dynamic and related to the page path

- charts/karpenter/README.md.gotmpl
- website/content/en/preview/faq.md
- website/content/en/preview/tasks/provisioning.md
After https://github.com/aws/karpenter/pull/1456 `/getting-started/` is moved to `getting-started/getting-started-with-eksctl/` so all these anchor links need to be updated as well.
> Fix broken anchor link to getting started guide

- charts/karpenter/README.md
- charts/karpenter/README.md.gotmpl
- website/content/en/preview/faq.md
In FAQ under upgrade instructions use the same script used in getting started.
There's a missing backslash in all instances of this script that is also fixed.
> Reuse the upgrade script, and add trailing backslash where its missing

- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step06-add-spot-role.sh
Since the SLR is optional, and fails if already installed, adding in a `|| true` into this part of the script so it doesn't fail.
> Setup script does not fail if spot SLR already installed

- pkg/test/expectations/expectations.go
N/A
Remove grace period when cleaning up between tests.
Hard-coded a pod name in two different tests, without this change the second test fails due to 'object is being deleted'.  With this change, both tests pass.
> set a grace period of zero when cleaning up between tests

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
#1459 
This change will create GPU resources on any new nvidia, AMD or AWS Neuron capable nodes. 
All local dev tests pass. This change was deployed to a v1.21 EKS cluster with a GPU provisioner and test pod specs as below. The new g5.xlarge node was correctly created and had the expected `nvidia.com/gpu` resource applied. 
I also verified that the nvidia-device-plugin also still functioned as normal with no unusual logs. 
```
apiVersion: karpenter.sh/v1alpha5
metadata:
name: gpu
spec:
requirements:
- key: karpenter.sh/capacity-type
operator: In
values: ["spot", "on-demand"]
- key: "node.kubernetes.io/instance-type"
operator: In
values: ["g4dn.xlarge", "g5.xlarge"]
limits: …
```
> Create GPU resources on new node

- pkg/apis/provisioning/v1alpha5/suite_test.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/provisioning/scheduling/suite_test.go
N/A
This sets up some groundwork for beginning work on pod affinity/anti-affinity.
Unit tests
> add pod affinity/anti-affinity tests that are skip()'d

- pkg/controllers/selection/preferences.go
- pkg/controllers/selection/suite_test.go
#1433
When taints with the effect of `PreferNoSchedule` are applied to nodes, the behavior of kube-scheduler is to only schedule pods to said nodes when no other scheduling options exist.  Currently, Karpenter treats taints with the effect of `PreferNoSchedule` as `NoSchedule` and will not provision a node with the `PreferNoSchedule` taint unless the pod tolerates it explicitly.  
This change adds a blanket `PreferNoSchedule` toleration to pods when no other Provisioners are selectable and after attempting to relax Affinity terms.  In short, Provisioners with `PreferNoSchedule` taints which would otherwise meet the pods requirements will be used, but only as a last resort.  
A test was …
> Relax PreferNoSchedule Taint

- pkg/test/pods.go
We are seeing collisions in pod names which cause failures in tests. This adds a sequential number to pods making it easier to debug and also adds a random number to make collisions much harder.
Generates names like
```
P0002-Butterflyfire-060061
P0003-Knavesticky-007571
P0004-Whipflannel-031521
P0005-Ratpalm-084815
P0006-Turnersurf-050034
P0007-Toucanmesquite-005050
P0008-Faceveil-088540
P0009-Graspproud-027227
P0010-Thunderbevel-039678
P0011-Wizardpeat-023014
P0012-Banehollow-067513
P0013-Llamaplanet-021244
P0014-Finsprinkle-097644
P0015-Bootspiral-064129
P0016-Scourgecat-001877
P0017-Sharksand-029673
P0018-Bearthorn-073803
P0019-Lightningflax-050540
P0020-Swordspiral-095658
P0021-Flyplatinum-010365
P0022-Hawkwool-004579 …
```
> More random pod names in tests

- charts/karpenter/crds/karpenter.sh_provisioners.yaml
- pkg/apis/provisioning/v1alpha5/provisioner.go
Simple ease-of-use tweak to karpenter CRD.
```
k delete karpenter --all
provisioner.karpenter.sh "default" deleted
```
😮 
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories
https://book.kubebuilder.io/reference/markers/crd.html
> Enabled `kubectl delete karpenter --all` with crd categories

- website/content/en/preview/faq.md
- website/content/en/preview/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.5.6/getting-started/grafana-values.yaml
- website/content/en/v0.6.0/getting-started/grafana-values.yaml
- website/content/en/v0.6.1/getting-started/grafana-values.yaml
- website/content/en/v0.6.2/getting-started/grafana-values.yaml
- website/content/en/v0.6.3/getting-started/grafana-values.yaml
- website/content/en/v0.6.4/getting-started/grafana-values.yaml
- website/content/en/v0.6.5/getting-started/getting-started-with-eksctl/grafana-values.yaml
https://github.com/aws/karpenter/issues/1502
Fixes broken links to files in the getting started guide
> Fix broken links to files in getting started

- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/cleanup.sh
- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step16-cleanup.sh
We are missing a step in cleanup.sh to remove what we add in:
https://github.com/aws/karpenter/blob/db7ed9c7935332da0fbcdf17ab38c45b956d139a/website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step05-controller-iam.sh#L4
This causes the install.sh to fail after running cleanup.
To remove the role, the policy must be detached first. Otherwise the following errors occur:
```
An error occurred (DeleteConflict) when calling the DeleteRole operation: Cannot delete entity, must detach all policies first.
An error occurred (DeleteConflict) when calling the DeletePolicy operation: Cannot delete a policy attached to entities.
```
By …
> Remove IAM role and policy properly in cleanup.sh

- pkg/cloudprovider/aws/amifamily/bootstrap/eksbootstrap.go
- pkg/cloudprovider/aws/suite_test.go
Get rid of the equal sign because the bootstrap.sh will not properly parse it and assume it is empty. Which will result in it trying to find the API server automatically which works for EKS cluster but does not for others.
The extra `=`s were added in https://github.com/aws/karpenter/pull/1420
This is a problem introduced in 
> Get rid of the equal char when calling bootstrap.sh

- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/provisioning/scheduling/node.go
- pkg/controllers/provisioning/scheduling/suite_test.go
Fixes #1540
Pre-filter the available instance types by the provider constraints
> fix issue regarding not pre-filtering instance types by provider constraints

- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/provisioning/scheduling/node.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/utils/sets/sets.go
N/A
Adds a test and fixes a bug related to not checking pod node affinity.
Unit test + on EKS
> fix bug with pod node affinity testing

- website/content/en/preview/AWS/provisioning.md
- website/content/en/v0.5.5/AWS/provisioning.md
- website/content/en/v0.5.6/AWS/provisioning.md
- website/content/en/v0.6.0/AWS/provisioning.md
- website/content/en/v0.6.1/AWS/provisioning.md
- website/content/en/v0.6.2/AWS/provisioning.md
- website/content/en/v0.6.3/AWS/provisioning.md
- website/content/en/v0.6.4/AWS/provisioning.md
- website/content/en/v0.6.5/AWS/provisioning.md
- website/content/en/v0.7.0/AWS/provisioning.md
- website/content/en/v0.7.1/AWS/provisioning.md
- website/content/en/v0.7.2/AWS/provisioning.md
#1488 #1525 
[Documentation regarding the default tags](https://karpenter.sh/v0.7.2/aws/provisioning/#tags) applied to resources created by Karpenter do not match what is in the code.  This change updates docs going back to v0.5.5 to accurately reflect the set of default tags.
Built locally and validated content.
> Fix default tags in docs

- pkg/cloudprovider/aws/apis/v1alpha1/provider.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider_validation.go
- pkg/cloudprovider/aws/apis/v1alpha1/zz_generated.deepcopy.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/AWS/provisioning.md
https://github.com/aws/karpenter/issues/1538
- Support EBS `snapshotID` in blockDeviceMappings
- tested manually w/ a Bottlerocket setup. Used a snapshot of the bottlerocket secondary volume. 
```
spec:
provider:
amiFamily: Bottlerocket
apiVersion: extensions.karpenter.sh/v1alpha1
blockDeviceMappings:
- deviceName: /dev/xvda
ebs:
encrypted: true
volumeSize: 4G
volumeType: gp3
- deviceName: /dev/xvdb
ebs:
snapshotID: snap-0ab03fec22a151ecf
```
It successfully used the snapshot which carries over the volume configuration of the snapshot. 
> add support for EBS snapshotID in block device mappings

- pkg/apis/provisioning/v1alpha5/constraints.go
- pkg/apis/provisioning/v1alpha5/requirements.go
- pkg/apis/provisioning/v1alpha5/suite_test.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/utils/sets/sets.go
- pkg/utils/sets/suite_test.go
According to the second bullet at https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement, DoesNotExist and NotIn are compatible. For example, A Pod that requires `foo 'not in' bar` may schedule to a node without a label with key `foo`. 
Previously, we required the node to have the label `foo` with a value of something other than `bar`.
Node labels cannot repel a pod (see: taints), unless a pod has conflicting requirements. In this case, a pod with empty requirements should happily schedule to a node with an Exists requirement on a node.
Previously, the pod needed to have a requirement for label `foo` in order to schedule onto node with requirement `foo: Exists`.
*Note: ` provisioner only supports [In NotIn Exists]`, so it wasn't currently possible …
> Resolved two bugs with NodeAffinity and simplified compatibility logic

- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/fake/instancetype.go
- pkg/controllers/provisioning/binpacking/packer.go
- pkg/controllers/provisioning/scheduling/suite_test.go
N/A
Remove packing optimization that doesn't work with arbitrary price sorting.
Unit tests & by hand on EKS
> our price ordering no longer provides the guarantee that made this work

- pkg/cloudprovider/requirements.go
- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/scheduling/node.go
- pkg/controllers/provisioning/suite_test.go
Moved cloud provider specific requirements logic out of the provisioner/scheduling package to make it more accessible to other controllers.
> Moved a few libraries to be more generically accessible

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/suite_test.go
#1563 #1467 
In v0.7.2, when pods request `ephemeral-storage`, Karpenter cannot schedule those pods to a node as AWS instance types are not reporting any `ephemeral-storage` resources.  This change sets an arbitrarily high value for all instance-types to cause binpacking to ignore ephemeral-storage resources.  Values for `ephemeral-storages` resources are updated on the node once Kubelet is up and running.  A more robust solution is planned in #1467 .
Additional test were added to cover the case of deployments and daemonsets with ephemeral-storage requests.  Also, I manually validated the code changes in a live environment with both a deployment and daemonset with requests defined for …
> Setting static value for ephemeral-storage on aws instance-types

- pkg/apis/provisioning/v1alpha5/constraints.go
- pkg/controllers/provisioning/provisioner.go
Another touchup that moves logic out of the provisioner.
> Moved node generation logic to be owned by constraints

- Makefile
N/A
This is useful for resetting your cluster back to the latest released
version, or while releasing a new version testing out the newly
pushed public images.
> add a Makefile target for applying the latest known release

- cmd/controller/main.go
N/A
Adds a log line with the version number on startup
make apply
> log the version string on startup

- pkg/cloudprovider/fake/instancetype.go
- pkg/controllers/provisioning/scheduling/instance_selection_test.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/test/metadata.go
N/A
Adds additional unit tests to scheduling:
- ensures that all instance types passed to the cloud provider meet
the required constraints
- verify prov/pod constraints on OS
- verify prov/pod constraints on zone/capacity type
- verify mixed prov/pod constraints
Unit test, no functional changes were made.
> add more scheduling unit tests

- .github/workflows/codeql-analysis.yaml
- .github/workflows/deflake.yml
Changes the schedule so that both actions run every day at 12:00 UTC (5AM PST & 8AM EST) this is a better schedule because it runs right before people start working in our team hence giving us a chance to quickly respond to failures, also doesn't take the computing capacity when we need it (during working hours). Finally this will capture more changes than before because
there's a chance the code gets updated after hours.
>  Change the schedule of GA crons

- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/securitygroups.go
- pkg/cloudprovider/aws/subnets.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/metrics/cloudprovider.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/instance_selection_test.go
- pkg/controllers/provisioning/scheduling/suite_test.go
Moves from a batch create API to a single create semantic. The current implementation of the `Create` API is very Fleet specific, and will likely not port naturally to other providers. Further, it may not stand the test of time as we move to use ABS. It's currently written the way that it is to achieve performance gains for the AWS cloud provider for scale ups beyond 100 nodes. The current default CreateFleet limit is 100bucketed + 2/second. 
Additionally, I noticed that this parallelism was causing a large number of discovery calls. This problem already existed, but is much more noticable without batching. I've added a mutex to relevant cloud provider interfaces to avoid unnecessary discovery calls. Due to cache hits after the …
> Simplified Cloudprovider Create API and delgate batching the provider specific implementation

- website/config.yaml
Switch hugo theme code blocks to render with prism so code blocks have a copy button
It was not tested locally but I can verify it with the PR site provided by opening this PR.
I should mention the docs for it are here https://www.docsy.dev/docs/adding-content/lookandfeel/#code-highlighting-with-prism
- [ x ] Yes, PR includes docs updates
> Switch to prism syntax highlighting for website

- website/content/en/preview/tasks/deprovisioning.md
- website/content/en/v0.5.5/tasks/deprovisioning.md
- website/content/en/v0.5.6/tasks/deprovisioning.md
- website/content/en/v0.6.0/tasks/deprovisioning.md
- website/content/en/v0.6.1/tasks/deprovisioning.md
- website/content/en/v0.6.2/tasks/deprovisioning.md
- website/content/en/v0.6.3/tasks/deprovisioning.md
- website/content/en/v0.6.4/tasks/deprovisioning.md
- website/content/en/v0.6.5/tasks/deprovisioning.md
- website/content/en/v0.7.0/tasks/deprovisioning.md
- website/content/en/v0.7.1/tasks/deprovisioning.md
- website/content/en/v0.7.2/tasks/deprovisioning.md
- website/content/en/v0.7.3/tasks/deprovisioning.md
Added a note for current and past doc versions for defaulting behavior. 
Ran `make website` to check.
> Adding note for defaulting behavior of deprovisioning

- pkg/cloudprovider/aws/amifamily/al2.go
- pkg/cloudprovider/aws/amifamily/bootstrap/bootstrap.go
- pkg/cloudprovider/aws/amifamily/bootstrap/eksbootstrap.go
- pkg/cloudprovider/aws/amifamily/bottlerocket.go
- pkg/cloudprovider/aws/amifamily/resolver.go
- pkg/cloudprovider/aws/amifamily/ubuntu.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/suite_test.go
https://github.com/aws/karpenter/issues/1585
- The AL2 AMI Family now uses containerd by default and dockerd only when requesting GPUs for
- Fixed a bug where AMD GPU resources were counted as nvidia resources on the node.
- manual cluster test of nvidia gpu pods
- added unit-tests 
> use dockerd if requesting gpus

- Makefile
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/fake/instancetype.go
- pkg/controllers/provisioning/scheduling/instance_selection_test.go
- pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
N/A
Extends scheduling benchmark and adds a minimum pods/sec scheduling threshold to CI builds.
Unit tests & on EKS scaling up/down the inflate deployment.
> Scheduling benchmark

- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/provisioning/provisioner.go
N/A
- make node names unique with a sequential ID
- if the node already exists, log a debug message
Unit tests & scaling up/down inflate on EKS.
> make node names unique in tests

- .github/workflows/nightly.yaml
Needs to define this env variable after https://github.com/aws/karpenter/pull/1587/files or it'll break the [nightly](https://github.com/aws/karpenter/runs/5754161893?check_suite_focus=true)
> add the cloud provider env variable

- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/scheduling/topology.go
- pkg/controllers/selection/controller.go
- website/content/en/preview/provisioner.md
- website/content/en/preview/tasks/scheduling.md
https://github.com/aws/karpenter/issues/1557
* Allows using karpenter.sh/capacity-type as topologyKey in TopologySpreadConstraint
* Tested on EKS using the instructions here: https://karpenter.sh/v0.7.3/development-guide/ 
* Karpenter was able to spin up the correct `capacity-type` based on the PodSpec to respect the distribution. Tested for distribution of pods across on-demand and spot EC2 instances. 
* podSpec used for testing topologySpreadConstraint:
```
topologySpreadConstraints:
- labelSelector:
matchLabels:
app: <app-name>
maxSkew: 1
topologyKey: karpenter.sh/capacity-type
whenUnsatisfiable: DoNotSchedule
```
* Karpenter provisioner specified:
```
requirements:
- key: …
```
> Add support for using topologyKey=karpenter.sh/capacity-type in TopologySpreadConstraint

- .github/workflows/codeql-analysis.yaml
- .github/workflows/deflake.yml
- .github/workflows/nightly.yaml
- .github/workflows/release.yaml
Certain GAs only should run on the main repo not all the forks.
> Add a condition to run only on the main repo not forks

- website/content/en/preview/troubleshooting.md
Added troubleshooting items related to [Issue #1084](https://github.com/aws/karpenter/issues/1084), [Issue #1180](https://github.com/aws/karpenter/issues/1180) and [Issue #607](https://github.com/aws/karpenter/issues/607), as well as several slack discussions.
The following troubleshooting entries were added:
* Daemonsets can result in deployment failures (@felix-zhe-huang, please review)
* Unspecified resource requests cause scheduling/bin-pack failures (@tzneal, please review)
* Missing discovery tags causing provisioning failures (@bwagner5, please review)
> Adding troubleshooting docs items

- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/faq.md
https://github.com/aws/karpenter/issues/1336
https://github.com/aws/karpenter/issues/1371
Support Bare Metal Instance Types. 
Before this change, Bare Metal was filtered out of the universe of instance types making it impossible to use Bare Metal (even if directly specified in the Provisioner `node.kubernetes.io/instance-type` requirements). 
This PR removes the bare metal filter and instead prioritizes Bare Metal instance types as a last resort in the AWS Cloud Provider (similar to the way GPUs are utilized). Since bare metal instance types have the exact same resource specs as the largest instance type in an instance family, bare metal will only engage if the Provisioner is properly constrained to only bare metal instance types. …
> support baremetal instance types

- website/content/en/preview/troubleshooting.md
- website/content/en/v0.8.1/troubleshooting.md
N/A
- Fixed a 404 in the Troubleshooting docs
> fix link in troubleshooting docs

- website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.5.6/getting-started/_index.md
- website/content/en/v0.6.0/getting-started/_index.md
N/A
- Fix two broken links in previous website versions that shows up on the 404 checker when releasing. These sections should have been removed in those version since the dashboards are imported automatically beginning at v0.5.6. 
- Fix troubleshooting webhooks section which is out-dated since the webhook and controller are now in the same pod.
- Fix inconsistent casing on the Getting Started landing page. All other links have "Started" capitalized except "Getting started with eksctl" 
> fix two broken links and update troubleshooting webhooks

- hack/license-config.hcl
N/A
- go-toml's license isn't being detected properly because it's a dual MIT and Apache-2.0 license. I've overridden this in our license check config to `Apache-2.0` (https://github.com/pelletier/go-toml/blob/master/LICENSE). 
`make licenses`
> add go-toml license

- .github/workflows/ci.yaml
- Makefile
- hack/toolchain.sh
Change our default K8s version to 1.22 and add 1.22 to CI
N/A
Defaults developers to 1.22 if they re-run the toolchain script and adds 1.22
Unit tests.
> update to v1.22.x

- Makefile
- pkg/test/randomdelay.go
N/A
Add a special deflake test run that adds random delays to every Expect() call
Unit tests
> for deflake tests, add random delays to each gomega expect call

- charts/karpenter/README.md
- charts/karpenter/templates/configmap-logging.yaml
- charts/karpenter/values.yaml
https://github.com/aws/karpenter/issues/1637
- Add logEncoding to values.yaml so that users can configure between console and json logs
```
helm upgrade --install karpenter charts/karpenter --namespace karpenter \
--set serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn=arn:aws:iam::xxxxxxxxxx:role/eksctl-karpenter-demo-addon-iamserviceaccoun-Role1-1EYIC0TUBRWJV 
--set clusterName=karpenter-demo 
--set clusterEndpoint=https://xxxxxxxxxx.gr7.us-west-2.eks.amazonaws.com 
--set logEncoding=json 
--set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile-karpenter-demo \
--set controller.image=xxxxxxxxxx.dkr.ecr.us-east-2.amazonaws.com/karpenter/controller@sha256:c1fae686e87356a5f49c6e8a8c25 …
```
> add logEncoding to helm chart's values.yaml

- go.mod
- go.sum
https://github.com/aws/karpenter/pull/1610
- Update go-toml to the latest version 
- Booted a bottlerocket node (the toml lib is used to create the bottlerocket toml config)
> update go-toml to beta7

- hack/toolchain.sh
N/A
Updated ko version
Building & applying to my EKS cluster using both go 1.17 and 1.18 and ko v0.11.2
> update to ko release that works with go 1.18

- website/content/en/preview/testing-guide.md
This document details plans for making testing within Karpenter more comprehensive, accessible, and configurable.
> Added Guide for plans for Testing in Karpenter

- hack/toolchain.sh
N/A
- helm-docs v1.7.0 causes a checksum mismatch when using GOPROXY=direct, v1.8.1 is a stable release that matches the checksum 
- helm-docs v1.7.0 depends on golang.org/x/sys/unix@20190215142949 which doesn't work with go 1.18 on darwin
```
$ go verison 
go version go1.17.8 darwin/amd64
$ GOPROXY=direct go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.7.0
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20190215142949-d0b11bdaac8a/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable …
```
> upgrade helm-docs

- hack/toolchain.sh
N/A
golicense doesn't build with go 1.18+, so instead of installing golicense from source, install the last release.
Locally, this PR should test is with VI
> manually install golicense from the last release

- website/content/en/preview/testing-guide.md
- website/content/en/v0.8.2/testing-guide.md
Testing guide was reachable by URL but did not by navigation bar due to how Netlify works.
Added the Testing Guide to show up in the Navigation Bar
ran `make website` and saw the page appear locally.
> Fixed Testing Guide to show up in website

- pkg/cloudprovider/aws/instancetype.go
N/A
- include ephemeral storage in price calc for an instance type. This will order instance type priorities when using spot to differentiate between 'd' instance type variants (storage optimized). 
- Manual scale-up and printed instance type ordering compared to actual price:
https://gist.github.com/bwagner5/a571dc74a9c52f49efbc373752848fba
> [AWS CP] include ephemeral storage in instance type price

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetypes.go
N/A
- Use t1 or t2 only if no other instance types are available (this is similar to how we handle bare metal instance types)
- Manually in an EKS cluster
- constraints cluster to m5.16xlarge and t2.2xlarge
- Provisioned a pod that needs 1vcpu, Karpenter chose m5.16xlarge
- removed m5.16xlarge and Karpenter provisioned a t2.2xlarge 
> [AWS CP] use t1 and t2 if no other instance types are available

- charts/karpenter/templates/poddisruptionbudget.yaml
- charts/karpenter/values.yaml
Adds a pod disruption budget to the helm chart.
It's not exposed as a variable/value. Should it be?
Googling and copy pasting 
No, unless we want to add a variable to disable it or change the value. I'm not sure that's a good idea.
> Add pdb to helm chart

- Makefile
N/A
- use `--create-namespace` with helm upgrade 
- only use the base domain if a cluster name includes an FQDN like ekctl does
> dev improvements: helm create-namespace and truncate eksctl domain on CLUSTER_NAME

- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
topologySpreadConstraints was not available in the chart, resulting in karpenter deployment pods scheduled on the same node.
Added topologySpreadConstraints logic to values.yaml and deployment template.
Added a sample config as well, maybe you'll prefer to split on the hostname instead of the zone.
Locally, by deploying the chart and scaling the number of replicas to validate the syntax and the spread result.
> Add topologySpreadConstraints to helm chart

- .github/workflows/stale.yml
With the previous settings the bot wasn't finding anything in dry runs. This will try a different set of options that are also used in:
https://github.com/aws/aws-cdk/blob/master/.github/workflows/close-stale-prs.yml
> Stale bot try different tagging values

- hack/snapshot.sh
> use the karpenter-snapshot alias instead of z4v8y7u8

- website/assets/js/index.js
- website/assets/js/offline-search.js
- website/assets/js/offlineSearch/index.js
- website/content/en/_index.html
- website/content/en/preview/_index.md
- website/content/en/v0.4.3/_index.md
- website/content/en/v0.5.0/_index.md
- website/content/en/v0.5.2/_index.md
- website/content/en/v0.5.3/_index.md
- website/content/en/v0.5.5/_index.md
- website/content/en/v0.5.6/_index.md
- website/content/en/v0.6.0/_index.md
- website/content/en/v0.6.1/_index.md
- website/content/en/v0.6.2/_index.md
- website/content/en/v0.6.3/_index.md
- website/content/en/v0.6.4/_index.md
- website/content/en/v0.6.5/_index.md
- website/content/en/v0.7.0/_index.md
- website/content/en/v0.7.1/_index.md
- website/content/en/v0.7.2/_index.md
- website/content/en/v0.7.3/_index.md
- website/content/en/v0.8.0/_index.md
- website/content/en/v0.8.1/_index.md
- website/content/en/v0.8.2/_index.md
- website/package-lock.json
- website/package.json
N/A
This updates the documentation site's search to prioritize results from the version of the docs currently being viewed. It's largely built upon the JS from the Docsy theme's [`offline-search.js`](https://github.com/google/docsy/blob/main/assets/js/offline-search.js), but refactored to be slightly less imperative. 
This isn't a perfect solution, but I think it's a step in the right direction.
Manually on my locally hosted documentation site.
> Version-Aware Documentation Search

- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/poddisruptionbudget.yaml
N/A
- Use PDB v1 api on clusters >= 1.21 if < 1.21 then use v1beta1
- `helm template charts/karpenter`
Kind 1.20:
```
$ kind create cluster --image kindest/node:v1.20.70@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9 --kubeconfig /tmp/kubeconfig
$ export KUBECONFIG=/tmp/kubeconfig
$ make apply
$ kg pdb karpenter -n karpenter -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
annotations:
meta.helm.sh/release-name: karpenter
meta.helm.sh/release-namespace: karpenter
creationTimestamp: "2022-04-19T16:06:57Z"
generation: 1
labels:
app.kubernetes.io/managed-by: Helm
name: karpenter
namespace: karpenter
resourceVersion: "1004"
uid: …
```
> pdb api version switching

- .github/workflows/stale.yml
Should fix this err:
```
Unexpected input(s) 'exempt-issue-label', 'exempt-pr-label', valid inputs are ['entryPoint', 'args', 'repo-token', 'issue-types', 'stale-issue-message', 'stale-pr-message', 'days-before-stale', 'days-before-close', 'stale-issue-label', 'exempt-issue-labels', 'stale-pr-label', 'exempt-pr-labels', 'ancient-issue-message', 'ancient-pr-message', 'days-before-ancient', 'response-requested-label', 'closed-for-staleness-label', 'minimum-upvotes-to-exempt', 'loglevel', 'dry-run']
```
> fix stale bot label name issue

- website/content/en/preview/AWS/launch-templates.md
- website/content/en/v0.8.2/AWS/launch-templates.md
The current document about using the custom launch template will use a wrong template name in the provisioner.
Replace the incorrect name with the correct one.
N/A
> Fix the wrong launch template name in the doc

- website/content/en/preview/AWS/launch-templates.md
- website/content/en/v0.8.2/AWS/launch-templates.md
The example provisioner is missing the subnet selector. It will fail the validation webhook check.
Include the subnet selector to the example provisioner.
N/A
> Correct the example provisioner for AWS custom launch template doc

- .github/workflows/stale.yml
During testing Stalebot was scheduled to run every hour, it seems to be working as expected so we can go to the previous daily schedule.
> Return stale bot to normal schedule

- charts/karpenter/values.yaml
Fixed example of env vars in chart values.yaml: removed extra '-' symbol.
It's partially a pure cosmetic change, but personally I often change default charts values by uncommenting and modifying provided examples, so in this case almost missed it:)
> fix: env var example in chart values

- designs/runtime-defaulting.md
https://github.com/aws/karpenter/issues/1449
- Add runtime defaulting doc to designs
> add runtime defaulting doc

- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
N/A
- Cache unfulfillable capacity due to Max Spot Instance Limit Exceed, vcpu limit exceeded, and generic unfulfillable capacity  (in addition to the existing insufficient capacity error) 
- Added request-id on the fleet error returned to aid in future debugging and error reports. 
- Raised the Unfulfillable cache TTL from 45 secs to 60 secs. This may need to go up slightly more, but the idea is to continue to make progress on different instance type options. I found 45 secs to be a little limiting. 
- Default spot limits, restricted provisioner to r6i.metal:
```
karpenter-f4d59d8ff-nvf9v controller 2022-04-22T22:55:02.881Z	INFO	controller	Batched 1 pod(s) in 1.000856504s	{"commit": "64fe6ef"} …
```
> Spot failover

- hack/release.sh
…set -u an undefined variable error shows up.
After enabling strict mode (set -u) this line would throw an unbound variable error. This hyphen allows bash to safely handle the variable.
> Fix unbound variable error

- pkg/cloudprovider/aws/launchtemplate.go
https://github.com/aws/karpenter/issues/1743
- Don't panic on launch template hydration error
We may want to consider another initialization path for the cloud provider that does not use the constructor since the webhook instantiates a cloud provider but it doesn't really need to be hydrated...  
- Removed "DescribeLaunchTemplate" permission and noticed webhook container crashing (reproducing #1743)
- Removed panic on hydration error
- redeployed and observed no crash loop 
> don't panic on launch template hydration error

- charts/karpenter/crds/karpenter.sh_provisioners.yaml
- cmd/controller/main.go
- pkg/apis/provisioning/v1alpha5/constraints.go
- pkg/apis/provisioning/v1alpha5/provisioner_validation.go
- pkg/apis/provisioning/v1alpha5/suite_test.go
- pkg/apis/provisioning/v1alpha5/taints.go
- pkg/apis/provisioning/v1alpha5/util.go
- pkg/apis/provisioning/v1alpha5/zz_generated.deepcopy.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/node/emptiness.go
- pkg/controllers/node/initialization.go
- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/inflightnode.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/scheduling/topologygroup.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/controllers/state/suite_test.go
- pkg/events/recorder.go
- pkg/test/eventrecorder.go
- pkg/test/expectations/expectations.go
- pkg/test/provisioner.go
- website/content/en/preview/provisioner.md
- website/content/en/preview/tasks/provisioning.md
Fixes #628 and #972
- don't launch nodes if the pod can schedule on a recently launch
node that hasn't become ready
- support startup taints
Co-authored-by: Bryan Stenson <bryan.stenson@okta.com>
Unit testing & scaling cluster on EKS. I tested with two EKS clusters, one using Cilium and one standard cluster.
> support awareness of in-flight nodes & startup taints

- .github/workflows/release.yaml
This is very similar to nightlies in what it does, hence it doesn't require the toolchain. The toolchain inclusion was failing because it would require Go runtime.
> Remove extra steps from release GA

- website/content/en/preview/AWS/_index.md
- website/content/en/preview/AWS/launch-templates.md
- website/content/en/preview/AWS/provisioning.md
- website/content/en/preview/concepts/_index.md
- website/content/en/preview/development-guide.md
- website/content/en/preview/faq.md
- website/content/en/preview/getting-started/_index.md
- website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
- website/content/en/preview/getting-started/getting-started-with-kops/_index.md
- website/content/en/preview/getting-started/getting-started-with-terraform/_index.md
- website/content/en/preview/getting-started/migrating-from-cas/_index.md
- website/content/en/preview/tasks/_index.md
- website/content/en/preview/tasks/deprovisioning.md
- website/content/en/preview/tasks/pod-density.md
- website/content/en/preview/tasks/provisioning.md
- website/content/en/preview/tasks/scheduling.md
- website/content/en/preview/tasks/set-resource-limits.md
- website/content/en/preview/testing-guide.md
- website/content/en/preview/troubleshooting.md
- website/content/en/preview/upgrade-guide/_index.md
Description lines were missing from most of the Karpenter docs pages, so descriptions weren't displayed from _index pages (such as https://karpenter.sh/v0.9.1/). This PR adds a one-line description to each page where it was missing.
**2. Does this change impact docs?**
> Add one-line description to each docs page

- website/content/en/preview/faq.md
https://github.com/aws/karpenter/issues/1758
- Correct FAQs about the default provisioner and provisioner ordering. 
https://deploy-preview-1765--karpenter-docs-prod.netlify.app/preview/faq/#if-multiple-provisioners-are-defined-which-will-my-pod-use
- make website
> correct faq on provisioner ordering

- pkg/cloudprovider/aws/instancetypes.go
N/A
Filter out the G2 instance types as they use the K520 GPU which is not supported by the nvidia device plugin daemonset.
Launching on EKS.
> filter out the G2 instance types

- pkg/controllers/provisioning/provisioner.go
N/A
Without this log, no errors appear and we just repeated log that we
batched pods
Running on EKS with no provisioners.
> log an error if no provisioners exist

- pkg/cloudprovider/aws/instance.go
N/A
- Deprioritize a1 (graviton 1) instance types
- scaled up an inflate several times, observed a1s being provisioned
- made change
- scaled up an inflate, observed m6i's now
> deprioritize a1 (graviton 1) instance types

- pkg/controllers/provisioning/scheduling/scheduler.go
N/A
This can make the provisioner log output less confusing as it
directly displays the number of pods that we expect to schedule against
existing capacity.
Deploying to EKS
> log the number of pods that will schedule against existing capacity

- charts/karpenter/templates/deployment.yaml
…CLUSTER_ENDPOINT env variables (eg. configMap), we need to make them optional, so we can redefine them in values file.
https://github.com/aws/karpenter/issues/1539
Added IF statement around CLUSTER_NAME and CLUSTER_ENDPOINT env variables, so we can redefine source of their values in values.yaml file
By deploying karpenter via terraform and passing CLUSTER_NAME and CLUSTER_ENDPOINT values as ConfigMap values.
> Make Helm clusterName and clusterEndpoint optionally rendered so that env vars can be passed instead

- .golangci.yaml
- hack/toolchain.sh
```
V/w/w/k/karpenter (providerCrd) [127]> golangci-lint run
ERRO [runner] Panic: buildir: package "lo" (isInitialPkg: false, needAnalyzeSource: true): T: goroutine 12608 [running]:
```
Fixes the above error that has started showing up. Looks like we need to upgrade.
https://github.com/golangci/golangci-lint/issues/2664
> Upgrade golangci-lint to avoid error

- .github/workflows/snapshot-pr-approval.yaml
Try out adding the permission under the job itself.
This may be why the job starts with "Secret source: None" which leads to a failure. https://github.com/aws/karpenter/runs/6481950410?check_suite_focus=true
> Snapshot PR - Try adding permissions under the job

- pkg/apis/provisioning/v1alpha5/constraints.go
- pkg/apis/provisioning/v1alpha5/labels.go
- pkg/apis/provisioning/v1alpha5/register.go
- pkg/apis/provisioning/v1alpha5/util.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/node/emptiness.go
- pkg/controllers/node/initialization.go
- pkg/controllers/node/suite_test.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/inflightnode.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/test/expectations/expectations.go
- pkg/utils/options/options.go
- website/content/en/preview/concepts/_index.md
- website/content/en/preview/tasks/scheduling.md
- website/content/en/preview/upgrade-guide/_index.md
> Revert "don't pre-bind pods to nodes"

- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
When running karpenter on fargate and there is no nodes except for karpenter pod , karpenter fails in EKS as there is no coredns running on the cluster and by default dnsPolicy is ClusterFirst, causing karpenter to restart endless
issue #1836 
add an option to configure the dnsPolicy and dnsConfig for the helm chart.
running a EKS cluster with NO nodes only fargate pod for karpenter and have a provisioner setup, karpenter fails to start unless dnsPolicy is changed to 'Default'
> add the option to have dnsConfig and dnsPolicy set on the pod

- pkg/controllers/provisioning/scheduling/inflightnode.go
- pkg/controllers/provisioning/scheduling/node.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/controllers/state/hostportusage.go
N/A
Ensure we don't bind or assume that pods will schedule with conflicting hostport configurations. 
Unit testing & deploying to EKS.
> check for HostPort compatibility when scheduling

- pkg/controllers/counter/controller.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/scheduling/nodetemplate.go
- pkg/test/provisioner.go
- website/content/en/preview/provisioner.md
- website/content/en/preview/tasks/set-resource-limits.md
Fixes #1728
During the scheduling process, only provision from instance types that
won't violate limits.
Unit testing & deployed to EKS. I scaled up pods with an 8Gb memory limit set on my provisioner and the usage never exceeded 8Gb.
> during scheduling, filter instance types to those that won't violate limits

- website/content/en/preview/tasks/scheduling.md
None
Remove smart quotes from code block.
s/insure/ensure/
N/A, doc changes only
> Fix doc typos

- website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step02-create-cluster-fargate.sh
- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step02-create-cluster.sh
[Issue #1812](https://github.com/aws/karpenter/issues/1812), [Issue #1763](https://github.com/aws/karpenter/issues/1763), [Issue #1365](https://github.com/aws/karpenter/issues/1365),
Update the Karpenter [Getting started with eksctl guide](https://karpenter.sh/preview/getting-started/getting-started-with-eksctl/) with an example that creates a Fargate profile in which to run Karpenter.
I did it the most simple way I could think of. So let me know if I should have gone about it a different way.
I tested the whole eksctl getting started guide using both cluster creation examples. …
> Update getting started to use Fargate

- pkg/apis/provisioning/v1alpha5/labels.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/scheduling/topology.go
Fixes #1863
Allows affinity/anti-affinity/topology spread over arch
Unit testing & EKS.
> support affinity/anti-affinity/topology spead against arch

- website/content/en/preview/troubleshooting.md
[Issue #1812](https://github.com/aws/karpenter/issues/1812), [Issue #1762](https://github.com/aws/karpenter/issues/1763), [Issue #1365](https://github.com/aws/karpenter/issues/1365)
Running Karpenter on Fargate can fail if CoreDNS is not patched and restarted. This PR adds a description of that issue.
> Adding Karpenter on Fargate troubleshooting doc

- charts/karpenter/templates/poddisruptionbudget.yaml
Aligns PDB template with the rest of the templates by setting `metadata.namespace`. Without this change [deployment guide](https://karpenter.sh/v0.10.1/getting-started/migrating-from-cas/#deploy-karpenter), followed as:
```
helm --namespace karpenter template ... > karpenter.yaml
kubectl apply -f karpenter.yaml
```
will land PBD into `default` namespace, unlike all other resources.
Ran `helm template --namespace karpenter .` on my branch and validated `namespace` is present in PDB template.
> Set namespace on PBD

- pkg/cloudprovider/aws/amifamily/al2.go
- pkg/cloudprovider/aws/amifamily/bottlerocket.go
- pkg/cloudprovider/aws/amifamily/resolver.go
- pkg/cloudprovider/aws/amifamily/ubuntu.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/metrics/cloudprovider.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/instance_selection_test.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
#1467
Prior to this change, Karpenter would report an arbitrarily large value for the `ephemeral-storage` resource when discovering AWS instanceTypes.  This can result in Pending pods and node churn if the sum of the `ephemeral-storage` resources for pods being bound to a node exceeds that of the disk size of the launched node.  This change accurately reflects storage attached to instanceTypes so that binpacking of pods based on the `ephemeral-storage` resource type functions as expected.
The amount of storage used for binpacking is based on the size of the ~~"root" device~~ the device where `/var/lib/kubelet` resides.  If a BlockDeviceMapping is defined for the device in the AWS Provider Spec, then Karpenter will use the given …
> consider ephemeral-storage when bin-packing

- Makefile
- cmd/controller/main.go
- hack/docs/metrics_gen_docs.go
- pkg/cloudprovider/metrics/cloudprovider.go
- pkg/controllers/metrics/node/controller.go
- pkg/controllers/metrics/pod/controller.go
- pkg/controllers/metrics/provisioner/controller.go
- website/content/en/preview/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/preview/getting-started/getting-started-with-eksctl/karpenter-provisioner-metrics.json
- website/content/en/preview/tasks/metrics.md
Fixes #840
This adds three metrics for provisioners
- Limits
- Usage
- Usage Percentage (0-100)
Deploying to EKS
- [] No
> add metrics for provisioner usage

- pkg/apis/provisioning/v1alpha5/provisioner.go
N/A
Just updating the comment to make it clear that `containerRuntime` isn't a part of KubeletConfiguration and is a KubeletFlag.
None.
> Updating doc for KubeletConfiguration

- pkg/controllers/state/cluster.go
N/A
track node capacity correctly before kubelet reports it
Running on EKS
> track node capacity correctly before kubelet reports it

- pkg/cloudprovider/aws/apis/v1alpha1/register.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/cloudprovider/fake/instancetype.go
- pkg/cloudprovider/types.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/node.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/scheduling/nodetemplate.go
- pkg/scheduling/requirements.go
- pkg/utils/sets/sets.go
- pkg/utils/sets/suite_test.go
```
karpenter-6cf9b544fb-wn8sl controller 2022-06-06T21:01:48.488Z	ERROR	controller	Scheduling pod, incompatible with provisioner "default", incompatible requirements, for key karpenter.sh/capacity-type, [spot] not in [on-demand]	{"commit": "08998cb", "pod": "default/inflate-6776857d54-dmgn5"}
```
```
karpenter-6cf9b544fb-wn8sl controller 2022-06-06T21:05:08.529Z	ERROR	controller	Scheduling pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"1","pods":"1"} and requirements karpenter.sh/provisioner-name In [default], karpenter.sh/capacity-type In [invalid], kubernetes.io/arch In [amd64], eks.amazonaws.com/nodegroup DoesNotExist []	{"commit": "08998cb", "pod": …
```
> Simplify set and requirements logic

- pkg/controllers/provisioning/controller.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/utils/pod/scheduling.go
- Log lines are now only emitted when something has changed
- Log lines no longer start with integers (easier to parse)
- suffixed `cloudprovider` on the logging name for cloudprovider
```
controller.provisioning	Found 1 provisionable pod(s)
controller.provisioning	Computed 1 new node(s) will fit 1 pod(s)
controller.provisioning.cloudprovider	Discovered security groups: [sg-000d68e67c3fe53d8]
controller.provisioning.cloudprovider	Discovered kubernetes version 1.20
controller.provisioning.cloudprovider	Discovered ami-0ceb23c24bcb85ddd for query "/aws/service/eks/optimized-ami/1.20/amazon-linux-2/recommended/image_id"
controller.provisioning.cloudprovider	Created launch template
controller.provisioning.cloudprovider	Launched …
```
> Reduce logging noise on provisioning loop

- website/content/en/preview/AWS/provisioning.md
- website/content/en/preview/AWS/user-data.md
- Remove UserData from docs
N/A
* Removing UserData from docs so this will remain an undocumented feature until we complete the migration of all provider parameters to `providerRef`. 
* If anyone wants to try it out, I can just point them to a page that's not present in the left-nav like `http://localhost:1313/preview/aws/user-data/`.
I ran `make website` and ensured that UserData isn't present in the left-nav. 
> Remove UserData from docs

- examples/provisioner/general-purpose.yaml
`invalid value: label karpenter.k8s.aws/instance-family is restricted; specify a well known label: [karpenter.k8s.aws/instance.c
pu karpenter.k8s.aws/instance.family karpenter.k8s.aws/instance.gpu.count karpenter.k8s.aws/instance.gpu.manufacturer karpenter.k8s.aws/instance.gpu.memory karpenter.k8s.aws/instance.gpu.name ka
rpenter.k8s.aws/instance.memory karpenter.k8s.aws/instance.size karpenter.sh/capacity-type kubernetes.io/arch kubernetes.io/os node.kubernetes.io/instance-type topology.kubernetes.io/zone], or a
custom label that does use a restricted domain: [k8s.io karpenter.k8s.aws karpenter.sh kubernetes.io]`
> Fix example

- examples/provisioner/general-purpose.yaml
- pkg/cloudprovider/aws/apis/v1alpha1/register.go
- website/content/en/preview/tasks/scheduling.md
Fixes # 
See discussion thread: https://kubernetes.slack.com/archives/C02SFFZSA2K/p1655266249940299
* Unit, Manual
```release-note
AWS Well Known Labels now use - instead of . to align with upstream
```
> Fix: AWS Well Known Labels now use - instead of . to align with upstream

- Makefile
- hack/docs/instancetypes_gen_docs.go
- website/content/en/preview/AWS/instance-types.md
Fixes # 1329
Displays both labels and the resources that we use for bin-packing after overhead calculations.
* Preview with netlify.
```release-note
```
> docs: add tool to generate instance type docs

- Makefile
- hack/docs/instancetypes_gen_docs.go
- pkg/cloudprovider/aws/apis/v1alpha1/register.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/AWS/instance-types.md
Fixes # 
- Add instance-hypervisor label as an AWS node label so that you can filter for `xen` or `nitro` hypervisors. 
* `make test`
* manually tested on an EKS cluster 
```release-note
Add support for the AWS node label `karpenter.k8s.aws/instance-hypervisor` to select `nitro` or `xen` compatible instance types.
```
> feat: add instance-hypervisor as an AWS node label

- website/content/en/preview/tasks/scheduling.md
Fixes # 
- Add instance-hypervisor AWS label to scheduling docs
```release-note
```
> docs: add instance-hypervisor label to scheduling docs

- Makefile
- cmd/controller/main.go
- cmd/webhook/main.go
- hack/docs/configuration_gen_docs.go
- hack/docs/instancetypes_gen_docs.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/utils/env/env.go
- pkg/utils/options/options.go
- website/content/en/preview/tasks/configuration.md
Fixes # 
- Custom AMIs require different VM memory overhead due to other software or agents running on the machine. This PR makes the VM memory overhead parameter configurable via a CLI arg or env var.
- I've also added a script to generate a table with the env var / cli flag  and usage description for configuring the karpenter controller
* `make docgen` and observed the overhead calculation is the same as before.
* Varied the vm overhead parameter between 0, 1, and 0.075, observing correct docs gen of memory. 
```release-note
VM Memory Overhead is now configurable via an environment variable to the Karpenter controller (see the options here: …
```
> feat: make vm memory overhead configurable

- cmd/controller/main.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/utils/options/options.go
- website/content/en/preview/development-guide.md
> Implemented pprof

- Makefile
The `AWS_ACCOUNT_ID` variable query fetches the UserId, Account, and Arn rather than just the Account. This PR adds the `--query Account` flag to resolve this.
* Running `make apply` without an `AWS_ACCOUNT_ID` environmental variable set
```release-note
NONE
```
> fix: Makefile AWS_ACCOUNT_ID

- pkg/config/suite_test.go
Fixes # 
config was out-of-sync from out-of-order run causing assertion to fail sometimes:
https://github.com/aws/karpenter/runs/6990339852
```
------------------------------
• Failure [0.011 seconds]
Batch Parameter [It] should use default values if config map has invalid data 
/home/runner/work/karpenter/karpenter/pkg/config/suite_test.go:121
Expected
<time.Duration>: 2000000000
to equal
<time.Duration>: 1000000000
/home/runner/work/karpenter/karpenter/pkg/config/suite_test.go:122
------------------------------
•
Summarizing 1 Failure:
[Fail] Batch Parameter [It] should use default values if config map has invalid data 
/home/runner/work/karpenter/karpenter/pkg/config/suite_test.go:122
Ran 3 of 3 Specs in 11.611 seconds
```
test: deflake config test by reiniting config …
> test: deflake config test by reiniting config

- hack/release.sh
- website/content/en/v0.10.0/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.10.1/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.11.0/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.11.1/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.12.0/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.5.6/getting-started/grafana-values.yaml
- website/content/en/v0.6.0/getting-started/grafana-values.yaml
- website/content/en/v0.6.1/getting-started/grafana-values.yaml
- website/content/en/v0.6.2/getting-started/grafana-values.yaml
- website/content/en/v0.6.3/getting-started/grafana-values.yaml
- website/content/en/v0.6.4/getting-started/grafana-values.yaml
- website/content/en/v0.6.5/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.7.0/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.7.1/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.7.2/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.7.3/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.8.0/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.8.1/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.8.2/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.9.0/getting-started/getting-started-with-eksctl/grafana-values.yaml
- website/content/en/v0.9.1/getting-started/getting-started-with-eksctl/grafana-values.yaml
This adjusts the urls used for the grafana dashboards in the getting-started-with-eksctl guides to refer to the release versions that they're created at. Originally they were all pointing to preview.
This also changes future yamls to change preview to the proper release version. This has the potential downside of a comment that contains "preview" to be changed to the new version string, but this should be caught by PRs.
```release-note
```
> fix: Correct Grafana getting-started values to refer to proper release versions

- charts/karpenter/templates/role.yaml
On a fresh install of Karpenter, Karpenter needs to create leases for initial leader election records. With a recent change to scope down RBAC permissions, the permission to create these leases were removed. If a user is upgrading from a previous installation, where the lease is already created, the pod doesn't run into this issue. 
I created a new cluster and received this error when installing version v0.12.0. The webhook container in the Karpenter pod never becomes healthy, and the Karpenter pod then crash loops.
```
E0623 05:08:32.044105       1 leaderelection.go:329] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:karpenter:karpenter" cannot create resource "leases" …
```
> fix: Added back lease creation permissions for Karpenter RBAC Role

- charts/karpenter/templates/role.yaml
This essentially reverts this revert: https://github.com/aws/karpenter/pull/1984. Kubernetes does not allow specifying RBAC resourceNames for create verbs.
* Deleted the leases in the Karpenter namespace, ran`make install` and found the leases were created. 
```release-note
```
> fix: Adding in create permissions for RBAC

- charts/karpenter/templates/role.yaml
- cmd/controller/main.go
Fixes # 
- Switch to a `lease` only lock rather than a `ConfigMapLease` lock. 
- controller-runtime switched from a configmap lease pre v0.7.0 and starting w/ v0.7.0 went to a `ConfigMapLease` lock that does both in order to support a migration to a `Lease` only lock. Karpenter adopted v0.7.0 starting with v0.1.0 https://github.com/aws/karpenter/commit/2e3a63063e0faf6f37ef23dd3423b78bdec9aaf0 so we should be safe to switch to Lease only locks. This will remove one of the configmaps that Karpenter creates and gives permissions to.  
* Installed in an EKS cluster and deleted all leases and configmaps (related to election) and saw that the Karpenter pod created the lease resources.  …
> feat: move to lease only elections

- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/scheduling/topology.go
- pkg/controllers/provisioning/scheduling/topologygroup.go
Fixes #1975
For satisfying self affinity, prefer the domain of an inflight node.
Unit testing & deployed to EKS with a workload that exhibited the bug.
```release-note
```
> fix: prefer to satisfy self affinity from an existing inflight node

- pkg/controllers/provisioning/scheduling/inflightnode.go
- pkg/controllers/provisioning/scheduling/suite_test.go
Fixes # 
If a startup taint reappears after initialization, we can't assume that it will be removed again.
* Unit testing 
```release-note
```
> fix: don't consider startup taints once the node is initialized

- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
Fixes # 
- This change requires that Karpenter has the leader lease before hydrating the LT cache on startup. This is necessary since the LT provider in the AWS CP manages the deletion lifecycle of LTs. So if Karpenter is deployed in an HA setup, a Karpenter pod that is not the leader could hydrate the cache with existing LTs created by Karpenter and then they would be deleted once the TTL expires (currently 1 min). The other Karpenter pods would have the LT still in the cache and fail when trying to launch an instance.  
- In the case where the cache would get out-of-sync due to an operator manually deleting an LT, this change will invalidate the LTs in the cache that have caused errors which will result in a retry and a new LT being generated. 
**How was this change …
> fix: hydrate lt cache on election win and invalidate LTs in the cache that do not exist in the CP

- Makefile
Fixes # 
- Reduce deflake iteration since GHA hangs consistently
* n/a
```release-note
```
> chore: shorten deflake iteration since GHA hangs

- charts/karpenter/templates/webhooks.yaml
Because it doesn't make sense for an object to be mutated before it's deleted
Fixes https://github.com/aws/karpenter/issues/1971
The `DELETE` operations are both removed when running Karpenter hence they are practically ineffective. This causes a drift in some consumer clusters so it's better to not have it.
```release-note
```
> fix: Removing Delete operation from webhook

- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/suite_test.go
fix: use the correct number of pods when bin-packing if AWS_ENI_LIMITED_POD_DENSITY is false
* Unit testing and deploying a no-resource pod to EKS
```release-note
```
> fix: use the correct number of pods when bin-packing if AWS_ENI_LIMITED_POD_DENSITY is false

- website/content/en/preview/AWS/provisioning.md
- website/content/en/preview/getting-started/getting-started-with-eksctl/cloudformation.yaml
Fixes # 
restrict iam:PassRole to just the node role we create
* Tested in a new cluster using this cloudformation template and was unable to launch instances using an instance profile that was not the default.
```release-note
```
> fix: restrict iam:PassRole to just the node role we create

- charts/karpenter/templates/deployment.yaml
- cmd/webhook/main.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/types.go
Fixes # 
The webhook just needs the CP for Validate/Default, so let the CP know
this to allow it to skip some processing that isn't required if it
chooses to. Add an initial delay to our liveness probes to ensure that
any initial startup doesn't lead to restarts on the webhook/controller.
* Unit test & deployed to EKS
```release-note
```
> fix: add initial delay to liveness and let CP know it's run by the webhook

- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/scheduling/volumelimits.go
- pkg/test/storage.go
Fixes #1998
For static volumes, we pull the CSI driver name off of the PV
after it's bound instead of from the SC named on the PVC.  The SC
may not even exist in these cases and is informational.
* Unit testing & deploying a PVC/PV to EKS
```release-note
```
> fix: correctly handle static volumes

- Makefile
- pkg/apis/provisioning/v1alpha5/labels.go
- pkg/apis/provisioning/v1alpha5/register.go
- pkg/cloudprovider/aws/apis/v1alpha1/provider.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/test/awsnodetemplate.go
- pkg/test/expectations/expectations.go
- pkg/test/pods.go
- pkg/test/provisioner.go
- test/README.md
- test/infrastructure/management-cluster.cloudformation.yaml
- test/infrastructure/scripts/step-01-config.sh
- test/infrastructure/scripts/step-02-eksctl-cluster.sh
- test/infrastructure/scripts/step-03-tekton-controllers.sh
- test/infrastructure/scripts/step-04-aws-load-balancer.sh
- test/infrastructure/scripts/step-05-ebs-csi-driver.sh
- test/infrastructure/scripts/step-06-karpenter.sh
- test/infrastructure/scripts/step-07-provisioners.sh
- test/infrastructure/scripts/step-08-prometheus.sh
- test/infrastructure/scripts/step-10-tekton-permissions.sh
- test/infrastructure/setup-management-cluster.sh
- test/pkg/environment/environment.go
- test/pkg/environment/expectations.go
- test/suites/integration/pipeline.yaml
- test/suites/integration/suite_test.go
Fixes # 
Enables e2e tests against a local cluster. 
- test resources are all tagged with a special label for cleanup
- Made progress on CI infra setup (critical addons only, role name, etc), but gaps remain
```
~/w/g/s/g/aws/karpenter │ on testinfra !1  make e2etests                                2 ✘ │ at 18:00:08
ginkgo -r test -- --environment-name=karpenter-test-infrastructure
Running Suite: Integration Suite
================================
Random Seed: 1656550823
Will run 1 of 1 specs
• [SLOW TEST:85.879 seconds]
Sanity Checks
/Users/etarn/workspaces/go/src/github.com/aws/karpenter/test/suites/integration/suite_test.go:30
should provision nodes
/Users/etarn/workspaces/go/src/github.com/aws/karpenter/test/suites/integration/suite_test.go:31 …
```
> Test: Implemented ginkgo test against local kubeconfig

- website/content/en/preview/tasks/pod-density.md
Clarify how prefix assignment mode (AWS VPC CNI) can be used with Karpenter to increase pod densities per node.
`make website` and validated content.
```release-note
```
> docs: clarify use of prefix assignment mode

- charts/karpenter/templates/deployment.yaml
Fixes #2043
When try to use custom CNI, we need to setup hostNetwork to true in deployment.yaml.
According the readme & values.yaml, the variable would be hostNetwork, but the variable is `webhook.hostNetwork` in the deployment.yaml.
Based on the logic of https://github.com/aws/karpenter/pull/1145, because the variable is not in the webhook container section, it should be `hostNetwork` instead of `webhook.hostNetwork`
N/A
```release-note
NONE
```
> fix: hostNetwork variable is not aligned with docs in Helm chart (#2043)

- Makefile
- hack/toolchain.sh
Fixes # 
Uses go test instead of ginkgo cli. ginkgo is still used as a library.
Manually tested and injected failures.
- `make test`
- `make battletest`
- `make ci`
```release-note
None
```
> chore: use "go test" instead of "ginkgo"

- hack/docs/configuration_gen_docs.go
- hack/docs/metrics_gen_docs.go
- website/content/en/preview/tasks/configuration.md
- website/content/en/preview/tasks/metrics.md
Fixes #2042
Add more information about the metrics endpoint and document the default
values for the command line parameters.
Website preview
```release-note
```
> docs: add more information about metrics

- pkg/cloudprovider/aws/amifamily/bootstrap/bottlerocketsettings.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/cloudprovider/aws/testdata/br_userdata_input.golden
- pkg/cloudprovider/aws/testdata/br_userdata_merged.golden
Fixes # 
https://github.com/aws/karpenter/issues/2059
- adds network and NTP settings to Karpenter's bottlerocket userdata settings.
* Unit tested 
* EKS cluster manually tested with AWSNodeTemplate:
``` 
spec:
amiFamily: Bottlerocket
securityGroupSelector:
karpenter.sh/discovery: kdemo
subnetSelector:
karpenter.sh/discovery: kdemo
userData: |
[settings.network]
no-proxy = ["localhost", "127.0.0.1"]
hosts = [["100.0.0.0", ["test.example.com", "test1.example.com"]]]
[settings.ntp]
time-servers = ['169.254.169.123']
```
verified the node joins the cluster and that user-data matches in EC2. 
```release-note
``` …
> feat: add network related bottlerocket userdata settings

- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/fake/atomic.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- website/content/en/preview/faq.md
Fixes # 
- When falling back from Spot to OD, require that the current provisioning request includes at least 10 instance types. This will prevent a case where a capacity pool is constrained and fallback causes other spot instances to be interrupted due to falling back to OD. 
- Fixes the fake ec2api CreateFleet func to return the proper FleetErrors 
- Adds a mutex to the fake ec2api to prevent a race when resetting.
* Unit test + manual on EKS
```release-note
```
> feat: require 10 instance types when falling back from spot to OD

- hack/docs/instancetypes_gen_docs.go
- website/content/en/preview/AWS/instance-types.md
Ensure we don't list the capacity-type label in our instance type docs.  Since we generate the labels based on if there is a single value per instance, this can sometimes appear if an instance type isn't available via spot.
* Generating docs
```release-note
```
> docs: ensure we don't list capacity type on our instance type docs

- pkg/controllers/provisioning/scheduling/preferences.go
Record pod information in structured format with this log statement. When analyzing a log earlier it would have been helpful to know which pod this log referred to.
deployed to EKS
```release-note
```
> chore: add pod information to debug log

- pkg/controllers/provisioning/provisioner.go
TriggerAndWait() is used in unit tests to immediately trigger the batcher
and then wait on the condition variable.  It locks the mutex, and then
waits which unlocks it.  By locking on the mutex before broadcasting,
we ensure that we don't broadcast until the unit test is already
waiting on the condition variable.
```release-note
```
> test: fix batcher test flake

- website/content/en/preview/upgrade-guide/_index.md
- website/content/en/v0.12.0/upgrade-guide/_index.md
- website/content/en/v0.12.1/upgrade-guide/_index.md
- website/content/en/v0.13.0/upgrade-guide/_index.md
- website/content/en/v0.13.1/upgrade-guide/_index.md
- website/content/en/v0.13.2/upgrade-guide/_index.md
Fixes # 
https://github.com/aws/karpenter/issues/2082
- Add upgrade instructions for `awsnodetemplate` crd.
*  https://github.com/aws/karpenter/issues/2082
```release-note
```
> crd upgrade instruction backfill

- website/content/en/v0.10.0/provisioner.md
- website/content/en/v0.10.1/provisioner.md
- website/content/en/v0.11.0/provisioner.md
- website/content/en/v0.11.1/provisioner.md
- website/content/en/v0.12.0/provisioner.md
- website/content/en/v0.12.1/provisioner.md
- website/content/en/v0.13.0/provisioner.md
- website/content/en/v0.13.1/provisioner.md
- website/content/en/v0.13.2/provisioner.md
- website/content/en/v0.8.1/provisioner.md
- website/content/en/v0.8.2/provisioner.md
- website/content/en/v0.9.0/provisioner.md
- website/content/en/v0.9.1/provisioner.md
Adding the following to document defaulting behavior for every version since v0.8.1.
```
```
Architecture defaulting was added [here](https://github.com/aws/karpenter/pull/1603/files#diff-d7d1d4fc9c7bb1ec42a075b631a9c272475744575d1bf38581aa7870e6e9e766R141) where the release after was [v0.8.1](https://github.com/aws/karpenter/pull/1628).
My formatter seems to also want to remove some extra whitespaces.
```release-note
```
> docs: documenting defaulting behavior for architecture

- website/content/en/v0.13.2/getting-started/getting-started-with-terraform/_index.md
fixes the authentication error on api_version client.authentication.k8s.io/v1alpha1
Based on issue mentioned [here](https://github.com/helm/helm/issues/10975). Need to update helm version to respect the `client.authentication.k8s.io/v1alpha1` api_version variable.
- 
- Yes, PR includes docs updates
```release-note
- Updates docs to have an upgraded helm version to avoid failure caused due to helm `api_version` as shown [here](https://github.com/helm/helm/issues/10975)
```
> docs: helm version causing errors

- pkg/cloudprovider/aws/instance.go
C1 has odd #CPU <-> family mapping which can cause it to be preferred by bin-packing. De-prioritize to prevent this from occurring.
* Unit testing and `make e2etests`
```release-note
```
> fix: de-prioritize c1

- cmd/controller/main.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/node/controller.go
- pkg/controllers/node/emptiness.go
- pkg/controllers/node/suite_test.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/queue.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/controllers/state/suite_test.go
This eliminates some problems seen with short emptiness TTL
where we can delete the node too early (e.g. PVC binding) and
the 'boucing' of the emptiness annotation for newly launched nodes.
* Unit tests & `make e2etests`
```release-note
```
> feat: make emptiness controller aware of scheduling

- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/upgrade-guide/_index.md
Fixes # 
https://github.com/aws/karpenter/issues/2101
- Karpenter could hydrate the launch template cache w/ user created LTs if they used a naming pattern like `Karpenter-<cluster-name>-*`. This change adds a `karpenter.k8s.aws/managed-by` tag that is used for cache hydration instead of the name pattern. 
- Add Fleet, Network Interface, and launch template tags. 
* Deployed to EKS
```release-note
Karpenter now discovers AWS Launch Templates generated by Karpenter via the `karpenter.k8s.aws/managed-by: <Cluster-Name>` tag rather than the previously used name pattern.  See the upgrade guide for cleaning up old launch templates that Karpenter generated. 
```
By submitting this pull request, I …
> fix: discovering generated aws launch templates under karpenter management

- Makefile
- pkg/test/provisioner.go
- pkg/test/storage.go
- test/pkg/environment/expectations.go
- test/suites/integration/suite_test.go
- test/suites/storage/suite_test.go
Adds tests for provisioning nodes for pods with both static & dynamic persistent volume claims.
`E2E_TESTS=PVC make e2etests`
```release-note
```
> test: add dynamic/static PVC E2E tests

- pkg/controllers/metrics/node/suite_test.go
- pkg/controllers/metrics/pod/suite_test.go
- pkg/controllers/node/suite_test.go
Fixes # 
`make test`
```
❯ ps aux | grep etcd
etarn            57483   0.0  0.0 34122868    860 s000  R+    9:59AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox etcd
```
```release-note
None
```
> Test: Added missing env.Stop() to avoid leaking etcd/apiserver

- Makefile
- hack/add-snapshot-tag.sh
- hack/release_common.sh
- hack/snapshot.sh
Fixes # 
Adds a notification message when releases occur. 
*
```release-note
```
> chore: add notification when a release occurs

- hack/add-snapshot-tag.sh
Fixes # 
add-snapshot-tag.sh by adding missin gparameter
* make nightly
```release-note
```
> fix: add-snapshot-tag.sh by adding missin gparameter

- pkg/cloudprovider/aws/amifamily/bootstrap/bottlerocket.go
- pkg/cloudprovider/aws/amifamily/bootstrap/bottlerocketsettings.go
- pkg/cloudprovider/aws/testdata/br_userdata_merged.golden
Fixes # 
https://github.com/aws/karpenter/issues/2059
- Accept all bottlerocket config rather than limiting to a subset of config options.
* Unit Tests
```release-note
```
> feat: support all bottlerocket configuration

- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
Resolve issue where we failed to de-prioritize metal instance types.
Unit test & deployed to EKS where I inspected logs to see that the metal was now de-prioritized.
```release-note
```
> fix: de-prioritize bare metal instance types

- pkg/cloudprovider/aws/instancetypes.go
Fixes # 
- Remove unneeded instance type compression that is surprising to use since some fields are removed from the regular ec2.InstanceTypeInfo type. 
* `make test`
```release-note
```
> fix: remove instance type compression

- website/content/en/preview/AWS/provisioning.md
**Fixes**: [#2085](https://github.com/aws/karpenter/issues/2085)
Added note to [Provisioning Configuration](https://karpenter.sh/preview/aws/provisioning/) docs that tells users provisioning GPUs to the NVIDIA daemonset (`nvidia-device-plugin-daemonset`).
> Docs update to run daemonset plugin on GPU nodes

- Makefile
By default, go runs tests in different packages in parallel.  This
makes the e2etests fail as they create specific provisioners,
count nodes launched, etc.
```release-note
```
> test: run e2etests serially

- Makefile
- test/pkg/environment/environment.go
- test/pkg/environment/expectations.go
- test/suites/integration/suite_test.go
- test/suites/storage/suite_test.go
Fixes # 
Renamed environment name to align with upcoming PR for testing clusters. Now supports/requires --kubeconfig 
```release-note
None
```
> Test: Added kubeconfig to test environment

- test/pkg/environment/environment.go
Fixes # 
Even if kubeconfig was supplied, it was using the kubeconfig of the local env.
```
❯ go test ./test/suites/integration -cluster-name test --kubeconfig ./kubeconfig
Running Suite: Integration
==========================
Random Seed: 1657834980
Will run 4 of 4 specs
Failure [0.001 seconds]
[BeforeSuite] BeforeSuite
/Users/etarn/workspaces/go/src/github.com/aws/karpenter/test/suites/integration/suite_test.go:22
Unexpected error:
<*fs.PathError | 0xc0005ec030>: {
Op: "stat",
Path: "./kubeconfig",
Err: <syscall.Errno>0x2,
}
stat ./kubeconfig: no such file or directory
occurred
/Users/etarn/workspaces/go/src/github.com/aws/karpenter/test/suites/integration/suite_test.go:25
------------------------------
```
**Does this change impact …
> Test: Fixed a testing bug that ignored --kubeconfig

- Makefile
Fixes a change which caused ko to fail to push to ECR repositories when running `make apply`.
* Running `make apply`
```release-note
NONE
```
> fix: revert make apply to use -B rather than --bare

- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/instance.go
Fixes # 
- Unsupported configuration errors may be returned by fleet which in-large means that the capacity is not able to be fulfilled. The error can also be transient, so treat as unfulfillable capacity in the ICE cache. 
* `make test` && eks
```release-note
```
> fix: [AWS] treat Unsupported error code as unfulfillable fleet error in the ICE cache

- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/upgrade-guide/_index.md
Provide a more opinionated set of default instance types if the provisioner
doesn't supply its own list of instance types/families.
Unit testing & deployed to EKS.
```release-note
```
> feat: in the absence of instance-type/family filtering, provide a default

- pkg/controllers/termination/controller.go
Fixes # 
Ensures that the `karpenter_nodes_termination_time_seconds` metric is updated **once** per termination. Other operations in the termination controller are idempotent so multiple passes are a non-issue.
* Scale-up / scale-down events in EKS cluster
```release-note
NONE
```
> fix: duplicate termination event metrics

- pkg/cloudprovider/aws/amifamily/al2.go
- pkg/cloudprovider/aws/amifamily/bottlerocket.go
- pkg/cloudprovider/aws/amifamily/resolver.go
- pkg/cloudprovider/aws/amifamily/ubuntu.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/suite_test.go
Fixes #1959
This change will take the pod density setting in account when calculating memory overhead. This is important to avoid scheduling mistakes and endless loops like described in the linked issue.
* Real EKS cluster using the manifests from the issue
* Newly added automated tests
See new logs when testing against the reproducible setup (as expected, the c5n.xlarge instance type is now considered to be too small):
```console
2022-06-21T07:09:04.372Z	DEBUG	controller.provisioning	Relaxing soft constraints for pod since it previously failed to schedule, removing: spec.topologySpreadConstraints = {"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"ScheduleAnyway","labelSelector":{"matchLabels":{"app":"inflate"}}} …
```
> fix: consider pod density in memory overhead calc

- designs/metrics.md
- pkg/controllers/metrics/pod/controller.go
Instruments the `karpenter_pods_startup_time_seconds` metric as detailed in the metrics design doc.
* Scale-up / scale-down tests in EKS cluster.
```release-note
NONE
```
> feat: add pod startup summary metric

- pkg/cloudprovider/aws/apis/v1alpha1/register.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/AWS/instance-types.md
- website/content/en/preview/tasks/metrics.md
- website/content/en/preview/tasks/scheduling.md
Fixes # 
- Add an instance-category node label to filter by broader classes of instance types like "c" -> "..., c3, c4, c5, c6i, c6g, c7g"
- Add an instance-generation node label to filter by generation within a category i.e. "4" -> c4, m4, r4, ....
- Add a local-nvme node label to filter by local nvme stroage i.e, "local-nvme" -> "c5d", "i3" "i4i", ... 
* `make docgen` populated all categories properly.  
* EKS cluster:
```
apiVersion: karpenter.sh/v1alpha5
metadata:
name: default
spec:
limits:
resources:
cpu: 4k
providerRef:
name: default
requirements:
- key: karpenter.sh/capacity-type
operator: In
values:
- on-demand
- spot
- key: kubernetes.io/arch
operator: In
values:
- amd64
- arm64
- key: …
```
> feat: add karpenter.k8s.aws/instance-category, karpenter.k8s.aws/instance-generation, and karpenter.k8s.aws/instance-local-nvme node labels

- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/suite_test.go
This allows spreading across labels constructed via provisioner requirements.
Unit testing & deployed to EKS.
```release-note
```
> fix: record provisioner requirements as valid topology domains

- charts/karpenter/README.md
- charts/karpenter/templates/poddisruptionbudget.yaml
- charts/karpenter/values.yaml
Fixes # 
Add capability to use custom podDisruptionBudget name.
Added podDisruptionBudget name as a Helm Value that the consumer can customise. This will help to satisfy Cluster constraints that have requirements of specific naming conventions. 
* Tested locally.
```release-note
```
> Add capability to use custom podDisruptionBudget name

- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
Fixes # 
Currently Karpenter waits until pods are outside of their graceful termination period before terminating the instance. However, the kubelet doesn't start forcibly killing pods until this exact point in time, so Karpenter doesn't give the node the opportunity to force kill the pods. This causes the pods to become unowned and be cleaned up by the pod lifecycle controller's garbage collection mechanism.
I ran into this issue when testing large scale downs (50 pods) that would exceed the default 30 second grace period, and then the subsequent test would notice existing pods.
Long term, we probably should trigger node termination in EC2 without forcibly deleting the node object and build a mechanism for the instance to deregister from the API Server, but this change is …
> fix: add in a grace period when checking if pods are stuck terminating

- Makefile
- charts/karpenter/values.yaml
- pkg/cloudprovider/aws/suite_test.go
- pkg/test/awsnodetemplate.go
- pkg/test/metadata.go
- pkg/test/provisioner.go
- test/pkg/environment/environment.go
- test/pkg/environment/expectations.go
- test/pkg/environment/monitor.go
- test/suites/common/run-test.yaml
- test/suites/common/setup.yaml
- test/suites/common/suite.yaml
- test/suites/integration/launchtemplates_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/suite_test.go
- test/suites/storage/suite_test.go
- test/suites/upgrade/pipeline.yaml
- website/content/en/preview/upgrade-guide/_index.md
Fixes # 
- Print logs for each test
- Separated tests into logical files to keep things organized
- Made the tests generally more reliable
* `make e2etest`
```
❯ TEST_FILTER=TestIntegration make e2etests
go test -p 1 -timeout 60m -v ./test/suites/... -run=TestIntegration
=== RUN   TestIntegration
Running Suite: Integration
==========================
Random Seed: 1658530731
Will run 6 of 6 specs
{"level":"info","ts":1658530807.482953,"logger":"fallback","caller":"environment/expectations.go:127","msg":"2"}
logger.go:130: 2022-07-22T16:00:07.722-0700	INFO	environment/expectations.go:165	2022-07-22T22:58:56.065Z	INFO	controller.provisioning	Found 1 provisionable pod(s)	{"commit": "f752ee0"}
2022-07-22T22:58:56.065Z	INFO	controller.provisioning …
```
> Add log captures to e2e tests

- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/controllers/state/node.go
- pkg/controllers/state/pod.go
Fixes #2164 
This prevents an issue where we can over-shoot if many nodes are launched.
* Unit testing & deployed to EKS with a sleep call in the updateNode function.
```release-note
```
> fix: ensure cluster state is synced prior to scheduling

- website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
- website/content/en/preview/tasks/scheduling.md
Documents the usage of `Exists` in provisioners and a method for a spot to on-demand split for a workload.
```release-note
```
> docs: document some advanced scheduling techniques

- Makefile
- test/pkg/environment/environment.go
- test/pkg/environment/expectations.go
- test/suites/common/run-test.yaml
- test/suites/common/setup.yaml
- test/suites/integration/launchtemplates_test.go
- test/tools/Dockerfile
- test/tools/README.md
Fixes # 
* Uses the correct OCI helm chart
* Wires up kubeconfig correctly
* Speeds up testing by vendoring go modules
```release-note
None
```
> Test: Fixed a few bugs with running integration tests in the integration environment

- pkg/cloudprovider/aws/instance.go
- website/content/en/preview/faq.md
Fixes # 
- Lower spot-to-od threshold from requiring 10 diverse instance types to only 5. 
* `make test`
```release-note
```
> chore: lower spot to od threshold to 5

- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/provisioning/volumetopology.go
Fixes #2189
Validate storage class on pod and ignore any that can't be validated.
* Unit testing & deployed to EKS where I verified the fix.
```release-note
```
> fix: ignore pods that have an invalid storage class

- website/content/en/preview/getting-started/getting-started-with-terraform/_index.md
- website/content/en/v0.13.1/getting-started/getting-started-with-terraform/_index.md
- website/content/en/v0.13.2/getting-started/getting-started-with-terraform/_index.md
Fixes #2200
The api_version in the 'exec' section of the 'helm' provider was obsolete. From the kubernetes documentation of [Authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats), it should be 'v1beta1' or 'v1'.
Using the v1alpĥa1 will return the error: "no kind "ExecCredential" is registered for version "client.authentication.k8s.io/v1alpha1" in scheme "pkg/runtime/scheme.go:100"
The aws cli creates a EKS cluster where the 'v1alpha1' was deprecated and will not deploy.
I modified the api_version from 'v1alpha1' to 'v1' and the _'terraform apply'_ command succeeded
```release-note
"action required": Modify your terraform file to …
```
> docs: Update api_version in helm provider

- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/test/environment.go
- pkg/test/provisioner.go
- test/suites/integration/scheduling_test.go
- test/suites/utilization/suite_test.go
Fixes #2164
Currently, tests have spurious logging: `scheduling/scheduler.go:267	nodes failed to sync, may launch too many nodes which should resolve` on every test. Additionally, tests outside of the scheduling suite were using the retry behavior. 
- No longer emits spurious logs during tests
- Disables synchronization on all tests via the test env
- Enforce convergence of state before making progress (removing bimodal system behavior)
e.g. 500 node scale up.
```
karpenter-7489d86697-nwhvn controller 2022-07-26T20:55:50.753Z	INFO	controller.provisioning	Waiting for unschedulable pods	{"commit": "059ad60"}
karpenter-7489d86697-nwhvn controller 2022-07-26T20:56:01.354Z	INFO	controller.provisioning	waiting for cluster state to catch up, 227 nodes not known to cluster state …
```
> fix: Enforced state sync to eventually converge instead of giving up

- .gitignore
- Makefile
- charts/karpenter/values.yaml
- hack/toolchain.sh
- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step02-create-cluster-fargate.sh
- website/content/en/preview/troubleshooting.md
Fixes #2186 
Updates the default `dnsPolicy` for the `karpenter-controller` pod spec to be `Default` as opposed to `ClusterFirst`
* `make test`
* Manual deployment validation with `make apply`
```release-note
None
```
> chore: update default value of `dnsPolicy` in `values.yaml` to `Default`

- hack/release_common.sh
Fixes # 
`make snapshot` effectively expects two values:
1. The Registry path to the public repo where the images/chart will be published
2. The Public login endpoint for `docker login`
These values are currently under a single value `$RELEASE_REPO` which breaks some things when running `make snapshot`  
* Run `make snapshot` against a custom $RELEASE_REPO
```release-note
None
```
> fix: login to Public ECR Should Occur at `public.ecr.aws`

- cmd/controller/main.go
- go.mod
There doesn't seem to be a better way to turn these off.
* Deployed to EKS.
```release-note
```
> fix: eliminate controller-runtime debug log per event

- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/controllers/counter/controller.go
- pkg/controllers/state/cluster.go
Fixes # 
- Removed spurious error logging when scaling down nodes by deleting a provisioner
- Will only fall back to the instancetype if the node is not initialized. This prevents not found errors since nodes have already initialized by the time they're scaling down. If a node was never initialized, these logs may still occur, but this is quite rare
- Decoupled instance type and provisioner from the node object, since they were not needed after instantiation logic
Before 
```
-192-168-131-232.us-west-2.compute.internal", "namespace": "", "error": "getting providerRef, AWSNodeTemplate.karpenter.k8s.aws \"skullagate-1-myhb5tu32d\" not found"}
karpenter-5f78bb8cf8-rsq2m controller 2022-07-26T23:14:26.450Z	ERROR	controller.controller.node-state	Reconciler error	{"commit": …
```
> fix: Removed spurious error logging when scaling down nodes by deleting a provisioner

- pkg/test/provisioner.go
- test/pkg/environment/expectations.go
- test/pkg/environment/monitor.go
- test/suites/node/ttl_test.go
Tests that TTLSecondsUntilExpired and TTLSecondsAfterEmpty work at a basic level.
* Ran `go test -p 1 -timeout 60m -v ./test/suites/... -run=TestNodeTTL` locally.
```release-note
```
> test: Adding basic tests to for TTLExpired and TTLEmpty

- website/content/en/preview/tasks/pod-density.md
- website/content/en/v0.10.0/tasks/pod-density.md
- website/content/en/v0.10.1/tasks/pod-density.md
- website/content/en/v0.11.0/tasks/pod-density.md
- website/content/en/v0.11.1/tasks/pod-density.md
- website/content/en/v0.12.0/tasks/pod-density.md
- website/content/en/v0.12.1/tasks/pod-density.md
- website/content/en/v0.13.0/tasks/pod-density.md
- website/content/en/v0.13.1/tasks/pod-density.md
- website/content/en/v0.13.2/tasks/pod-density.md
- website/content/en/v0.7.0/tasks/pod-density.md
- website/content/en/v0.7.1/tasks/pod-density.md
- website/content/en/v0.7.2/tasks/pod-density.md
- website/content/en/v0.7.3/tasks/pod-density.md
- website/content/en/v0.8.0/tasks/pod-density.md
- website/content/en/v0.8.1/tasks/pod-density.md
- website/content/en/v0.8.2/tasks/pod-density.md
- website/content/en/v0.9.0/tasks/pod-density.md
- website/content/en/v0.9.1/tasks/pod-density.md
Fixes a misleading description in the controller flag `aws-eni-limited-pod-density` which enables nodes to have a higher pod density, up to 110 pods.  Updating description to the current behaviour.
https://github.com/aws/karpenter/blob/e37909b223fd7625b57b59d28681561895643f09/pkg/cloudprovider/aws/launchtemplate.go#L364-L368
> docs: fix misleading description on controller max-pods flag

- pkg/controllers/termination/eviction.go
- pkg/events/dedupe.go
- pkg/events/recorder.go
- pkg/test/eventrecorder.go
- test/suites/integration/cni_test.go
Fixes # 
Following up from a previous PR: Emit evictions as events instead of logging. Also renamed NominatePod to Nominate to be more in line with existing pod events (Pulled, Created, Started, etc), since they're already scoped to an object type
`16m         Normal    Evict                  pod/ogreveil-4-cjtyd9gst2-6d998fb8b6-z7xd8           Evicted pod`
```release-note
None
```
> fix: Emit evictions as events

- hack/release_common.sh
Reverts aws/karpenter#2204
This breaks the nightlies https://github.com/aws/karpenter/actions/runs/2753842941 let's revert and do it in a way that doesn't break the nightly builds if we need to.
> Revert "fix: login to Public ECR Should Occur at `public.ecr.aws`"

- test/suites/integration/cni_test.go
Fixes # 
Our linter currently excludes test files so it doesn't catch things like unused imports. I tried adding test files but there were a 100 or so changes needed so rather decided to unblock our releases first.
`TEST_FILTER=TestIntegration make e2etests` succeeded
```release-note
test: unused import breaking e2etests
```
> test: unused import breaking e2etests

- website/content/en/preview/getting-started/getting-started-with-eksctl/karpenter-performance-dashboard.json
Sets the unit for the termination latency panel to seconds.
* Deployed dashboard to Grafana
```release-note
NONE
```
> fix: termination latency dashboard unit set to seconds

- hack/github/community-contributors.sh
Fixes # 
```
./hack/github/community-contributors.sh
Comparing v0.13.2 and v0.14.0-rc.0
Community members contributed 13/134 (9.70149%)
[
{
"author": "flf2ko",
"message": "fix: hostNetwork variable is not aligned with docs in Helm chart (#2043) (#2044)"
},
{
"author": "Dan Shepard",
"message": "docs: adding Omaze to list of adopters (#2068)"
},
{
"author": "Vishal Vazkar",
"message": "fix: helm version causing errors (#2096)"
},
{
"author": "Ido Koren",
"message": "add revisionHistoryLimit option to chart (#2102)"
},
{
"author": "Bryant Biggs",
"message": "feat: Update Terraform getting started guide to default to multi-cluster tagging scheme (#1668)"
},
{
"author": "Shrikant Lavhate",
"message": "Documentation update under 'getting started' section (#1788)"
},
{
"author": …
```
> Chore: Add a script to parse community contributors in each release

- pkg/controllers/provisioning/scheduling/inflightnode.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/scheduling/taints.go
Fixes #https://github.com/aws/karpenter/issues/2164 
During large scale ups, nodes sometimes flip/flop from ready to not read as things come online. This change considers unready nodes as in flight to avoid overscaling. 
In the case of hardware, networking, or other failure, it's possible for a node to transition from ready to unready. Previously, Kubernetes would evict the pods on the node after 5 minutes (default), triggering additional scale out. Instead, Karpenter will consider these taints as ephemeral and the node as in flight. Intervention (automated or otherwise) is required to remove these nodes. 
This may also be considered as a safety feature. If some issue caused nodes to consistently transition Ready -> NotReady, Karpenter would keep scaling out to provisioner …
> fix: Consider unready nodes as in flight

- pkg/test/provisioner.go
Fixes # 
Some tests themselves test validation, so don't test inside of object construction. It's up to the test authors to construct valid test cases.
* `make test`
```release-note
None
```
> Test: Remove validation from test.Provisioner() since some tests test validation

- pkg/cloudprovider/aws/instancetypes.go
Fixes #2228
The set of zones for instance types was using the same cache key irrespective of the subnet selector. As a result, if two provisioners had distinct subnetSelectors that matched subnets in different availability zones, the karpenter controller would only see one of them and be unable to schedule nodes on some of the subnets.
Manually tested by patching this change on top of the v0.13.2-release branch in our cluster.
```release-note
Fix flakiness in setting up nodes in the right availability zone when provisioners target different subnets.
```
> fix: Separate zone caching by subnet selectors

- website/content/en/preview/faq.md
Fixes [#2171](https://github.com/aws/karpenter/issues/2171) 
Revises the description the AWS load balancer in the FAQ to change the reason for using the IP mode target type.
> Updated ALB description in FAQ

- Makefile
- website/content/en/preview/contributing/development-guide.md
Fixes #2225  
Adds another target for only building the controller and webhook images and pushing them without using helm to update the existing manifests 
* Running `make build` locally
* Running `make apply` locally
```release-note
None
```
> chore: Add `make build` target alongside `make apply`

- test/infrastructure/clusters/test-infra/karpenter-tests/test-suites.yaml
- test/suites/common/cleanup.yaml
- test/suites/common/run-test.yaml
- test/suites/common/setup.yaml
Fixes # 
- add limit ranges to automatically inject min resource requests in tekton task definitions
- 
* eks cluster
```release-note
```
> chore: add limit ranges

- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/fake/utils.go
- pkg/cloudprovider/aws/suite_test.go
Fixes # 
https://github.com/aws/karpenter/issues/2228
https://github.com/aws/karpenter/pull/2229
- add a test for multiple provisioners with different subnetSelectors to reproduce bug in #2228
- fixed Subnet and Security group mock filters
* `make test`  -> FAIL
* pulled down #2229 patch and ran tests where they passed
```release-note
```
> add multi-provisioner subnet selector test

- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/cloudprovider/aws/instance.go
**Fixes** # 
#2100 and #1796
If tag conditions are used in Karpenter IAM policies for the TerminateInstances action, Karpenter can get stuck in a loop trying to terminate instances which were previously terminated (and reaped) without Karpenter's knowledge.  This fix adds a step where if instance Termination fails, Karpenter will then try to call DescribeInstances to determine the instances state.  If the state is "terminated" or if the instance isn't found, then skip the TerminateInstance call and proceed with removing the node in K8S.
Manually reproduced the issue by adding tag conditions to the Karpenter IAM policies for the TerminateInstances action.  Then launched an instance with said tags.  Then, manually removed the tags from the …
> fix: check instance state on termination failure

- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
Fixes # 
Do not attempt to drain terminal pods. This helps resolve an issue where a disconnected node with terminal pods can get stuck.
Helping to merge @ese's change https://github.com/aws/karpenter/pull/2205
* `make test`
```release-note
```
> Fix: Don't attempt to drain terminal pods

- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
Fixes # 
N/A
- Fixes an issue in the type comparison for identifying a spot flexibility error where the type was actually `errors.ErrorString` rather than SpotFallbackError. This would cause a `launchInstance` retry and constrain requirements to just spot even if on-demand was a valid requirement. This could also cause Spot to become a requirement if there was an error other than `LaunchTemplateNotFound` returned by `launchInstance` even if the provisioner was not flexible to Spot. 
* `make test`
```release-note
```
> fix: spot error type comparison

- hack/add-snapshot-tag.sh
- hack/release_common.sh
- hack/snapshot.sh
Fixes # 
Pulls the images that were published for verification and activating pull through cache: https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html
*
```release-note
```
> Pull released images through pull through cache

- hack/release_common.sh
Fixes # 
It seems like sometimes the pull fails, attempting a retry logic to see if it's because the image publishing process is not atomic.
*
```release-note
```
> perf: add retry logic to image pull

- pkg/cloudprovider/aws/errors.go
- pkg/cloudprovider/aws/instance.go
- pkg/cloudprovider/aws/suite_test.go
- website/content/en/preview/upgrade-guide/_index.md
Fixes # 
- Warn instead of preventing provisioning when not enough instance types are available to support the 5 that are recommended for OD to Spot. 
* `make test`
```release-note
```
> fix: warn on not enough instance types

- .github/workflows/ci.yaml
… toolchain step
Fixes # 
It seems like the run is taking 5 minutes rebuilding libraries in this directory:
```
/home/runner/.kubebuilder/bin
/home/runner/.kubebuilder/bin/kube-apiserver
/home/runner/.kubebuilder/bin/etcd
/home/runner/.kubebuilder/bin/k8s
/home/runner/.kubebuilder/bin/k8s/1.22.1-linux-amd64
/home/runner/.kubebuilder/bin/k8s/1.22.1-linux-amd64/kube-apiserver
/home/runner/.kubebuilder/bin/k8s/1.22.1-linux-amd64/etcd
/home/runner/.kubebuilder/bin/k8s/1.22.1-linux-amd64/kubectl
/home/runner/.kubebuilder/bin/k8s/1.23.5-linux-amd64
/home/runner/.kubebuilder/bin/k8s/1.[23](https://github.com/aws/karpenter/runs/7737857970?check_suite_focus=true#step:7:23).5-linux-amd64/kube-apiserver
/home/runner/.kubebuilder/bin/k8s/1.23.5-linux-amd64/etcd …
```
> Add more to the cache to speed up `make toolchain`

- examples/provisioner/bottlerocket.yaml
- examples/provisioner/multiple-ebs.yaml
Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>
Fixes #1100
adds provisioner examples with EBS
*
```release-note
Adds two examples of provisioner with EBS volumes. One for Bottlerocket (root and data) and one with multiple EBS
```
> [docs] add provisioner examples with EBS

- pkg/apis/provisioning/v1alpha5/labels.go
- pkg/apis/provisioning/v1alpha5/provisioner_validation.go
- pkg/cloudprovider/aws/apis/v1alpha1/register.go
- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes.go
- pkg/cloudprovider/aws/suite_test.go
- pkg/scheduling/requirement_test.go
- pkg/scheduling/requirements.go
- pkg/scheduling/requirements_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/subnet_test.go
Fixes #2289
- Fixes an issue where validation logic didn't include normalization, preventing scheduling
- Removed the concept of IgnoredLabels, in favor of simply supporting them in the cloud provider
- From the test, I discovered that AWS deprecated have been broken for a while. They were only released for a few days, so I removed them entirely.
* `make test`
* `make e2etest`
```
• [SLOW TEST:97.744 seconds]
Scheduling
/Users/etarn/workspaces/go/src/github.com/aws/karpenter/test/suites/integration/scheduling_test.go:18
should support well known labels
/Users/etarn/workspaces/go/src/github.com/aws/karpenter/test/suites/integration/scheduling_test.go:19
------------------------------
SSSSSSSSSSSSS
Ran 1 of 21 Specs in 99.470 seconds
SUCCESS! …
```
> Fix: Support Region and Normalized Labels

- test/suites/integration/ttl_test.go
Fixes flake for test/suites/integration TTL Expired test to prevent node recreation.
```release-note
```
> test: Fixed node flakes

- pkg/controllers/state/cluster.go
- pkg/controllers/state/suite_test.go
https://github.com/aws/karpenter/pull/2212
* Created a job with Resource requests and completions: 1000. Confirmed that resource metrics remained the same over the course of jobs completing.
```release-note
```
> fix: only count active pods towards node requests

- test/suites/integration/security_group_test.go
This changes our Security groups test to use all security group ids that fit the tag filters.
* ran `make e2etests` locally
```release-note
```
> test: fix security groups used in tests

- test/pkg/environment/monitor.go
- test/suites/consolidation/suite_test.go
The E2E test would fail if your system nodes happened to be .large types.  Filter on the provisioner name to avoid this.
* Ran the consolidation E2E tests multiple times.
```release-note
```
> test: deflake consolidation replace e2e test

- test/suites/upgrade/pipeline.yaml
Fixes the upgrade tests to run the from-git-ref tests first
*
```release-note
```
> test: fix upgrade tests

- pkg/controllers/provisioning/scheduling/existingnode.go
- pkg/controllers/provisioning/scheduling/suite_test.go
If a DS pod schedules that we didn't expect due to the node looking
different upon creation (i.e. new dynamic labels or deprecated labels), we
would miscalculate the amount of ravailable node capacity.
```release-note
```
> fix: track existing node resources correctly in the event of unexpected DS pods

- test/pkg/environment/expectations.go
- test/suites/integration/scheduling_test.go
Fixes # 
- Adds e2etesting for weighting provisioners
```release-note
None
```
> test: Add e2etesting to weighted provisioners feature

- charts/karpenter/values.yaml
Fixes # 
- Run in HA mode by default
- Speeds up dev loop, since we don't need to wait for the pod to terminate after 30 seconds
*
```release-note
```
> Feat: Default to 2 replicas and a rolling deployment strategy

- website/content/en/preview/troubleshooting.md
Fixes Issue [#1391](https://github.com/aws/karpenter/issues/1391)
Added some error messages and advice related to Node NotReady troubleshooting.
> Added info to Node NotReady troubleshooting

- pkg/cloudprovider/aws/cloudprovider.go
Fixes # 
- 3rd generation general instance types should be allowed 
*
```release-note
```
> fix: [AWS] 3rd gen M C R are allowed by default

- charts/karpenter/values.yaml
Fixes # 
* Unconstrained pool, immediately rolls out two fresh replicas
* Constrained pool, waits for one pod to terminate, and rolls out one at a time
```release-note
```
> Fix: Allow rollout to proceed when capacity is not available

- pkg/cloudprovider/aws/cloudprovider.go
This reverts commit 326de8c7824d6ff55286af5a78fc797426c000c0.
Fixes # 
3rd generation general instance types should be allowed
*
```release-note
```
> fix: [AWS] allow 3rd gen M C R instance types

- charts/karpenter/templates/deployment.yaml
- go.mod
- pkg/controllers/consolidation/controller.go
- pkg/controllers/controllers.go
- pkg/utils/env/env.go
- pkg/utils/options/options.go
- pkg/webhooks/webhooks.go
This informs the go runtime of the amount of memory available to the
container.  It allows the runtime to sometimes delay GC when there is
plenty of headroom and to run GC more often to avoid exceeding the
container memory limit.
* 13k pod / 400 node scaleup
```release-note
```
> fix: dynamically set go 1.19 runtime soft memory limit to better avoid OOM conditions

- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/test/provisioner.go
Fixes # 
- Use OD capacity type on tests instead of spot. 
* `make test`
```release-note
```
> chore: use od on tests unless explicitly specified

- test/suites/consolidation/suite_test.go
Fixes # 
- Adds a E2E test for consolidating from a on-demand instance to a spot instance of the same type
```release-note
None
```
> test: Add E2E test for consolidating from on-demand to spot instance

- pkg/controllers/controllers.go
- pkg/controllers/state/provisioner.go
- pkg/controllers/state/suite_test.go
Fixes # 
- Allows consolidation to automatically be triggered if there is a change to the provisioner spec
- This allows immediate reconciliation when consolidation is turned on or when there is a change to provisioner requirements
* Manual validation of E2E
* `make test`
```release-note
None
```
> perf: Provisioner changes trigger consolidation to be re-considered

- pkg/controllers/controllers.go
- pkg/utils/options/options.go
Fixes # 
- Command line arguments were completely broken because `Options` was being returned by value instead of by reference
* Passed command line arguments 
```release-note
None
```
> fix: Fix broken command line arguments

- pkg/controllers/consolidation/controller.go
- pkg/controllers/consolidation/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/events/dedupe.go
- pkg/events/recorder.go
- pkg/test/eventrecorder.go
- pkg/test/expectations/expectations.go
Removes a check for un-initialized nodes that would block all
consolidation if a node fails to start and re-uses the nominated
node check from the emptiness controller to accomplish
a similar task.  Upon node deletion, wait for the node to be
deleted to pause consolidation which ensures we don't overshoot
consolidation due to a PDB throttling the deletion of a node.
```release-note
```
> fix: wait for node deletion before continuing consolidation

- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step02-create-cluster.sh
- website/content/en/v0.16.0/getting-started/getting-started-with-eksctl/scripts/step02-create-cluster.sh
Helm chart defaults to 2 replicas for Karpenter controller pod. On a fresh install, this could return these log lines:
```
karpenter-64df6c45c8-m97x2 controller 2022-08-26T21:09:05.443Z	ERROR	controller.provisioning	Could not schedule pod, incompatible with provisioner "default", incompatible requirements, key karpenter.sh/provisioner-name, karpenter.sh/provisioner-name DoesNotExist not in karpenter.sh/provisioner-name In [default]	{"commit": "639756a", "pod": "karpenter/karpenter-64df6c45c8-pttpz"}
```
Changing the default node group replicas to 2 so that this doesn't happen. 
* Incremented my desired capacity on my ASG and the pod scheduled and the errors no longer occurred.  …
> fix: change desired nodegroup replicas to match default controller replicas

- hack/docs/instancetypes_gen_docs.go
- pkg/controllers/consolidation/controller.go
- pkg/controllers/consolidation/suite_test.go
- pkg/test/expectations/expectations.go
This was broken after a previous refactor and the test failed to catch
it.  Updated the test to more explicitly catch this issue in the future.
```release-note
```
> fix: re-add node lifetime consideration to consolidation calculation

- website/content/en/preview/AWS/user-data.md
Fixes # 
- Add an example of modifying a kubelet-config property via user-data with the AWSNodeTemplate. 
```release-note
```
> docs: add kubelet-config example for awsnodetemplate userdata

- website/content/en/v0.16.0/tasks/deprovisioning.md
Fixes # 
**Description**: Simple docs change to put the the condition where the node applies first.
**How was this change tested?** Docs change only
*
```release-note
NONE
```
> docs: Minor re-phrase to put the condition where it applies first

- test/pkg/environment/expectations.go
- test/suites/common/cleanup.yaml
> test: increase delete-cluster timeout and log more during E2E tests

- examples/provisioner/launchtemplates/al2-custom-ami.yaml
- examples/provisioner/launchtemplates/custom-family.yaml
The example files in the repo incorrectly specify the amiSelector when using ami ids.
> Fix ami selector example

- pkg/cloudprovider/aws/cloudprovider.go
- pkg/cloudprovider/aws/suite_test.go
Fixes #2407
ensure the cloud provider sets it's defaulting/validate webhooks
* Unit testing & deployed to EKS
```release-note
```
> fix: ensure the cloud provider sets it's defaulting/validate webhooks

- charts/karpenter/templates/deployment.yaml
- test/pkg/environment/expectations.go
The healthchecks check locks which cluster state may hold for
a period of time.  We should solve that, but for now prevent
the controller from restarting if you get unlucky during a
large scale-up and the health checks hit when the lock is held.
* Discovered via an E2E test, I could reproduce locally and ran multiple times with the new deployment values with no reproductions.
```release-note
```
> fix: increase the liveness/readiness probe timeouts

- examples/provisioner/bottlerocket.yaml
the GPU bottlerocket AMI requires at least 3GB. otherwise you run into:
> 2022-08-30T13:27:52.897Z        ERROR   controller.provisioning Provisioning failed, launching node, creating cloud provider instance, with fleet error(s), InvalidBlockDeviceMapping: Volume of size 3GB is smaller than  snapshot 'snap-0c5c999fe56c48b6f', expect size >= 4GB        {"commit": "639756a"}
The normal bottlerocket AMI size is still 2GB, just GPU is a bit bigger.
There was also a typo with the volume size value.
* N/A
> docs: fix bottlerocket node template for GPU volume size

- test/suites/common/notify-slack.yaml
- test/suites/common/suite.yaml
Fixes # 
*
```release-note
```
> chore: add slack notification for failed tekton pipelines

- pkg/controllers/controllers.go
- pkg/events/loadshedding.go
These aren't useful during large scale-ups, so drop them instead
of loading the API server.  The case where these are useful is
if we believe a pod will schedule, but kube-scheduler won't.  In
this case, the pod nominations will be repeated indefinitely and
will be available on the pod.
*
```release-note
```
> fix: reduce pod nomination event counts

- website/content/en/v0.16.0/getting-started/getting-started-with-eksctl/scripts/step08-apply-helm-chart.sh
The comment after the wait command causes the `helm upgrade` command to fail with the following message:
> Error: "helm upgrade" requires 2 arguments
Removing the comment fixes this error.
Fixes # NA
This is a fix to the `helm upgrade` script in the getting started documentation. The documentation doesn't make it clear that users should remove this comment before running the command/script, otherwise it will fail.
* Removing the comment after the last command in the script resolved my issue.
```release-note
This is a change to the Getting Started document where developers could experience issues trying to install the Helm chart needed for Karpenter.
```
By submitting this pull request, I …
> fix: Remove comment after wait command

- website/content/en/preview/troubleshooting.md
Update docs for getting Kubelet logs on AL2 and add docs for Bottlerocket.
*
```release-note
```
> docs: document how to get kubelet logs with Bottlerocket

- website/content/en/preview/upgrade-guide/_index.md
- website/content/en/v0.16.0/upgrade-guide/_index.md
- website/content/en/v0.16.1/upgrade-guide/_index.md
Fixes #2440
Add v0.16+ upgrade instructions
```release-note
```
> doc: add upgrade note for v0.16+

- website/content/en/preview/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json
- website/content/en/preview/getting-started/getting-started-with-eksctl/karpenter-performance-dashboard.json
Get rid of statically assigned datasource uid. This enables users to import the dashboard to kube-prometheus-stack without altering it afterwards to search and replace the datasource uid.
using grafana config in kube-prometheus stack with my version results in directly showing graphs. With the old version it shows errors about not found datasource.
```
dashboards:
karpenter:
capacity-dashboard:
url: https://raw.githubusercontent.com/pyromaniac3010/karpenter/a811cda492d0a365ae922b666bbbe62439102883/website/content/en/preview/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json
datasource: Prometheus
performance-dashboard:
url: https://raw.githubusercontent.com/pyromaniac3010/karpenter/a811cda492d0a365ae922b666bbbe62439102883/website/c …
```
> feat: unify grafana dashboard datasource by use of a variable and add new karpenter 0.15.0 consolidation graphs

- hack/code/prices_gen.go
- hack/docs/configuration_gen_docs.go
- hack/docs/instancetypes_gen_docs.go
- hack/docs/metrics_gen_docs.go
Fixes # 
Use log.Fatalf
* make test
```release-note
```
> chore: Use log.Fatalf instead of log.Printf and os.Exit

- website/content/en/preview/faq.md
- website/content/en/v0.10.0/faq.md
- website/content/en/v0.10.1/faq.md
- website/content/en/v0.11.0/faq.md
- website/content/en/v0.11.1/faq.md
- website/content/en/v0.12.0/faq.md
- website/content/en/v0.12.1/faq.md
- website/content/en/v0.13.0/faq.md
- website/content/en/v0.13.1/faq.md
- website/content/en/v0.13.2/faq.md
- website/content/en/v0.14.0-rc.0/faq.md
- website/content/en/v0.14.0/faq.md
- website/content/en/v0.15.0/faq.md
- website/content/en/v0.16.0/faq.md
- website/content/en/v0.16.1/faq.md
- website/content/en/v0.6.0/faq.md
- website/content/en/v0.6.1/faq.md
- website/content/en/v0.6.2/faq.md
- website/content/en/v0.6.3/faq.md
- website/content/en/v0.6.4/faq.md
- website/content/en/v0.6.5/faq.md
- website/content/en/v0.7.0/faq.md
- website/content/en/v0.7.1/faq.md
- website/content/en/v0.7.2/faq.md
- website/content/en/v0.7.3/faq.md
- website/content/en/v0.8.0/faq.md
- website/content/en/v0.8.1/faq.md
- website/content/en/v0.8.2/faq.md
- website/content/en/v0.9.0/faq.md
- website/content/en/v0.9.1/faq.md
Fixes # N/A
Updates FAQs
* Ran website locally
```release-note
NONE
```
> Docs: Update FAQs

- website/content/en/preview/AWS/provisioning.md
Fixes #2456
Document and show some examples of using the AWS specific labels,
specifically using Lt/Gt.
* N/A
```release-note
```
> docs: document use of Lt/Gt

- Makefile
- test/suites/integration/kubelet_config_test.go
Fixes # 
- Number of DS in integration tests aren't consistent between environments. DS count should be used to determine the DS pod overhead.
```release-note
None
```
> test: Use daemonset count to calculate maxPods and podsPerCore

- Makefile
- pkg/cloudprovider/fake/cloudprovider.go
- pkg/controllers/consolidation/controller.go
- pkg/controllers/consolidation/suite_test.go
- pkg/controllers/consolidation/types.go
- pkg/controllers/node/expiration.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/suite_test.go
- pkg/controllers/state/cluster.go
- pkg/controllers/state/suite_test.go
- pkg/utils/node/node.go
- test/pkg/environment/expectations.go
- test/suites/integration/expiration_test.go
Fixes # 
- Enables pods that are under Expiry with PDBs to schedule a node that will fit all the pods that are on a node marked for deletion rather than slowly trickling the pending pods onto a large number of small nodes
* `make test`
* Latency testing with large scale-ups
```release-note
None
```
> fix: Mark nodes that are pending deletion in cluster state for scheduling
