aws/karpenter-provider-aws

README.md

*Description of changes:* Fix installation to target `main` branch instead of `master`

Fix installation to target `main` branch instead of `master`

---

pkg/autoscaler/algorithms/proportional.go
pkg/autoscaler/algorithms/proportional_test.go

HA Bottoms out at 1 DesiredReplica for Utilization and Value metrics

---

docs/DESIGN.md

n/a
Changed consumer term of reference from "customer" to "user".

Change consumer term of reference from "customer" to "user" in DESIGN.md

---

OWNERS

Reorganized OWNERS

---

releases/aws/v0.1.0.yaml

Updated release image to use public ecr

---

docs/working-group/README.md

Improved calendar invite for Working Group

---

docs/working-group/notes/notes_12-4-2020.md

Add working group meeting notes

---

pkg/apis/autoscaling/v1alpha1/metricsproducer.go

Fixed a small typo in metricsproducer.go

---

docs/working-group/README.md

Add notes from working group meeting Jan/19/21

Add notes from working group meeting

---

cmd/controller/main.go
config/rbac/role.yaml
docs/examples/provisioner/provisioner.yaml
pkg/cloudprovider/aws/capacity.go
pkg/cloudprovider/types.go
pkg/controllers/provisioner/v1alpha1/suite_test.go

Wired up controller to main and trivial test

---

.github/workflows/presubmit.yaml

enable build on provisioner branch too

---

pkg/apis/provisioning/v1alpha1/provisioner_defaults.go
pkg/apis/provisioning/v1alpha1/provisioner_validation.go
pkg/controllers/provisioner/v1alpha1/suite_test.go

More tweaks to test wiring

---

docs/examples/provisioner/provisioner.yaml
pkg/cloudprovider/aws/capacity.go
pkg/cloudprovider/fake/capacity.go
pkg/cloudprovider/types.go
pkg/controllers/provisioner/v1alpha1/allocation/greedyallocator.go

Add end to end functionality for pending pods

---

.github/workflows/presubmit.yaml

Update Github actions to build on provisioner-work branch

---

docs/working-group/README.md

Add working group notes

---

pkg/apis/autoscaling/v1alpha1/metricsproducer_defaults.go
pkg/metrics/producers/scheduledcapacity/producer.go

Defaults for Metrics Producers

---

pkg/test/environment/local.go

- Wait for namespaces to be torn down before shutting down API server.

Resolved shutdown concurrency issues in test framework

---

README.md

Removed metrics concepts from repo README

---

pkg/cloudprovider/aws/fleet/instance.go

*Issue #, if available:* n/a
Fixed a typo-ish type thing that could lead to nil ptr access.

Fix potential nil ptr access when Terminating instances

---

pkg/utils/scheduling/scheduling.go

Variadic parameter in GetResources followup

---

pkg/cloudprovider/aws/factory.go

Use STS regional endpoints

---

pkg/apis/provisioning/v1alpha1/provisioner_defaults.go

Fixed an issue with codegeneration for provisioners defaulting logic

---

cmd/controller/main.go
pkg/apis/provisioning/v1alpha1/provisioner.go
pkg/cloudprovider/aws/fleet/capacity.go
pkg/cloudprovider/aws/fleet/factory.go
pkg/cloudprovider/aws/fleet/launchtemplate.go
pkg/cloudprovider/aws/fleet/vpc.go

*Issue #, if available:* 260
Initial support for launching aarch64. This is just the first change needed to support multiple architectures, and the use of amd64 is still hard-coded; further changes are waiting on changes to the Packer, etc. 

Preliminary Arm64 support

---

docs/aws/README.md

N/A
Use ECR Public Gallery pause container rather than the GCR one. 

use ecr public pause container

---

README.md

* N/A, current Examples link returns 404
* Updating link path to what I think is the correct folder

fix examples link

---

pkg/cloudprovider/aws/capacity.go
pkg/cloudprovider/aws/nodefactory.go
pkg/cloudprovider/aws/packing/nodecapacity.go
pkg/cloudprovider/aws/packing/packing.go
pkg/controllers/provisioning/v1alpha1/allocation/constraints.go
pkg/utils/binpacking/binpacking.go
pkg/utils/resources/resources.go
pkg/utils/scheduling/scheduling.go

Reserve overhead calculations for node capacities

---

pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
pkg/controllers/provisioning/v1alpha1/reallocation/suite_test.go
pkg/controllers/provisioning/v1alpha1/reallocation/terminate.go
pkg/controllers/provisioning/v1alpha1/reallocation/utilization.go
pkg/test/objects.go

Added suite tests for the reallocator and fixed nil map edge cases

---

README.md
docs/ROADMAP.md

Added roadmap

---

docs/working-group/README.md

Added working group docs

---

README.md

Resized Provisioning diagram

---

docs/aws/README.md

Description of changes: just a few minor doc updates, upgrade to using 1.19

minor tweaks to AWS README

---

pkg/controllers/provisioning/v1alpha1/reallocation/suite_test.go

There's now a total of 3 tests. The removed test will be brought back in once further functionality is implemented. 
The remaining 3 tests ran 150 times locally successfully, so I think it should be good.

 Reallocator Tests GHA Fix

---

docs/ROADMAP.md

Updated roadmap

---

docs/aws/README.md
docs/aws/karpenter.cloudformation.yaml

Create cluster name specific roles

---

pkg/controllers/provisioning/v1alpha1/reallocation/terminate.go

N/A
Cordon and add draining label to nodes that have already been cordoned. This will allow the aws-node-termination-handler (NTH) to work with karpenter. NTH will cordon and drain instance when spot interruptions or rebalance events occur. Before, karpenter would never terminate these nodes because karpenter wasn't the one to cordon them. 

cordon and add draining label to nodes that are already cordoned

---

docs/aws/README.md
pkg/controllers/provisioning/v1alpha1/reallocation/controller.go

Readme fix

---

pkg/cloudprovider/aws/instanceprofile.go

Added clusterName to NodeInstanceProfile to align with docs

---

docs/aws/README.md
pkg/controllers/provisioning/v1alpha1/reallocation/controller.go

Added verbose logging to AWS demo

---

pkg/utils/functional/suite_test.go

Issue #, if available: n/a
Description of changes: preliminary unit tests for `functional` pkg

Preliminary unit tests for functional package

---

pkg/apis/provisioning/v1alpha1/provisioner_status.go
pkg/cloudprovider/aws/suite_test.go
pkg/cloudprovider/aws/utils/utils.go
pkg/controllers/provisioning/v1alpha1/allocation/bind.go
pkg/controllers/provisioning/v1alpha1/allocation/controller.go
pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
pkg/controllers/provisioning/v1alpha1/reallocation/suite_test.go
pkg/utils/functional/functional.go
pkg/utils/scheduling/scheduling.go
pkg/webhooks/provisioning/v1alpha1/suite_test.go
pkg/webhooks/provisioning/v1alpha1/validator.go

Description of changes: removed unused argument and unnecessary cast

A few minor cleanups

---

README.md

Fixed README.md to have v.0.2.0 commands

---

README.md

Add kewl status badge to Readme

---

docs/aws/examples/provisioner.yaml

Fixed up camelCased labels

---

docs/aws/provisioner-launch-templates-options.md

Update to doc to reflect potential clarification on behavior.

clarify node selector behavior

---

pkg/cloudprovider/aws/fake/ec2api.go
pkg/cloudprovider/aws/suite_test.go
pkg/controllers/provisioning/v1alpha1/allocation/constraints.go

Issue #, if available: 273
See summary

unit test to validate node selectors creating separate capacity

---

pkg/cloudprovider/aws/suite_test.go
pkg/controllers/provisioning/v1alpha1/allocation/suite_test.go
pkg/test/expectations/expectations.go

Issue #, if available: 273
See Summary

[unit testing] additional simplifications to node/pod unit tests

---

Makefile

Updates ECR Public repo name

---

docs/working-group/README.md

Added WG notes

---

README.md
docs/TERMS.md

Remove references to developer preview

---

README.md

Added a note on reallocation

---

.github/workflows/ci.yaml

Signed-off-by: Gábor Lipták gliptak@gmail.com

Bump Go to 1.16.3 in CI

---

README.md

Added invite to discuss in slack

---

config/controller.yaml

Set Karpenter Pod to high priority and guaranteed

---

hack/quick-install.sh

updated quick install Karpenter release version

---

README.md

Added a Talks section in the README

---

charts/karpenter/templates/controller.yaml
cmd/controller/main.go
pkg/controllers/manager.go

Added liveness probes to the karpenter controller

---

pkg/controllers/provisioning/v1alpha1/allocation/constraints.go
pkg/controllers/provisioning/v1alpha1/allocation/filter.go
pkg/controllers/provisioning/v1alpha1/reallocation/terminate.go
pkg/utils/node/predicates.go
pkg/utils/pod/scheduling.go
pkg/utils/pod/status.go

Evicted pods are not counted in utilization

---

docs/DEVELOPER_GUIDE.md
docs/aws/README.md

https://github.com/awslabs/karpenter/issues/404#issuecomment-845283904

Included notes for 1.19+ clusters

---

README.md

Signed-off-by: Gábor Lipták gliptak@gmail.com

Link to GoReportCard in README

---

pkg/utils/functional/functional.go

Signed-off-by: Gábor Lipták gliptak@gmail.com

Correct typo

---

docs/working-group/README.md

5/27 Working group notes

---

docs/working-group/README.md

fix markdown rendering

---

charts/karpenter/templates/controller.yaml

Switches deployment strategy to recreate to improve restart speed

---

docs/working-group/README.md

N/A
- Add working group notes for 6/10

Working Group Notes 6/10/21

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

Example: https://github.com/ellistarn/karpenter/releases/tag/v0.2.6-test

Updated release generation logic

---

pkg/cloudprovider/aws/ami.go
pkg/cloudprovider/aws/utils/predicates/strings.go
pkg/cloudprovider/aws/utils/predicates/tags.go
pkg/utils/conditions/conditions.go

Added missing license headers

---

.github/ISSUE_TEMPLATE/request.md
.github/PULL_REQUEST_TEMPLATE.md

**Issue, if available:** 
N/A
Removes the `[Request]` prefix from issues cut using the Request template and styles the PR template to look like this PR

Tidied Up Issue and PR Templates

---

docs/TROUBLESHOOTING.md

Added a `TROUBLESHOOTING.md` file to list known issues in Karpenter and ways to solve those problems that are not included in the Github issues. This doc will see changes when an issue about Karpenter is raised and solved. We will host the ways to reconcile these solutions here.  
As Karpenter is in alpha, I thought it was best to host these solutions in one guide rather than making a user sift through issues to see if it's been solved.

Added Troubleshooting guide for commonly known problems

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/request.md

Borrowed directly from https://github.com/knative/serving

Added a issue template for bug reports

---

cmd/controller/main.go
docs/README.md
pkg/apis/provisioning/v1alpha2/provisioner.go
pkg/apis/provisioning/v1alpha2/provisioner_validation.go
pkg/apis/provisioning/v1alpha2/provisioner_validation_test.go
pkg/cloudprovider/aws/suite_test.go
pkg/controllers/allocation/suite_test.go
pkg/controllers/expiration/controller.go
pkg/controllers/expiration/suite_test.go
pkg/controllers/reallocation/suite_test.go
pkg/controllers/reallocation/utilization.go
pkg/controllers/termination/suite_test.go
pkg/packing/packer.go
pkg/test/expectations/expectations.go
pkg/test/nodes.go
pkg/utils/apiobject/apiobject.go
pkg/utils/node/predicates.go

#451
```
Triggering termination after 1m40s (+1.132343ms) for expired node ip-192-168-41-123.us-west-2.compute.internal
```

Implemented support for TTLSecondsUntilExpired

---

pkg/apis/provisioning/v1alpha2/provisioner_validation.go
pkg/apis/provisioning/v1alpha2/provisioner_validation_test.go

Implemented validation for provisioner.spec.taints

---

WORKING_GROUP.md

Feel free to update the PR if anyone got more notes for the rest half of the call.

Adding WG notes (first half)

---

pkg/cloudprovider/aws/docs/README.md

Updated paths in Getting Started guide

---

website/content/en/docs/getting-started/_index.md

Add --create-namespace to the helm command.

---

website/content/en/docs/getting-started/_index.md

Fixed a broken docs link

---

pkg/cloudprovider/aws/instance.go
pkg/controllers/allocation/filter.go

Adds additional logging for Fleet Errors and removes a spurious reference to provisioner namespace.

Logging improvements

---

README.md

Removed stale README comment

---

README.md

Update Readme.md for Installation doc Broken link

---

README.md

Fix Developer Guide Documentation link to website

---

website/content/en/docs/getting-started/_index.md

Fixed a typo in getting started

---

charts/karpenter/templates/webhook/webhooks.yaml

Added a missing webhook

---

go.mod
go.sum
pkg/controllers/node/suite_test.go

Removed Monkey due to licencing

---

pkg/controllers/node/controller.go
pkg/controllers/node/emptiness.go
pkg/controllers/node/expiration.go
pkg/controllers/node/liveness.go
pkg/controllers/node/suite_test.go
pkg/utils/node/predicates.go

Reenabled time mocking for node tests

---

website/content/en/docs/getting-started/_index.md

#615 
Updated the documentation to call out the helm pre-req. If there's some verification step I'm supposed to do for doc changes please let me know.

Add helm as a pre-req in getting started guide

---

README.md

docs: fix FAQs link

---

CONTRIBUTING.md

Updated branch name reference from "master" to "main" in *CONTRIBUTING.md*.

update branch name in Contributing guide

---

pkg/controllers/allocation/controller.go
pkg/controllers/allocation/suite_test.go

https://github.com/awslabs/karpenter/issues/644

Added missing provisioner label omitted in a previous PR

---

pkg/cloudprovider/aws/cloudprovider.go
pkg/cloudprovider/aws/suite_test.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/cloudprovider/types.go
pkg/controllers/allocation/binpacking/packable.go
pkg/controllers/allocation/binpacking/packer.go
pkg/controllers/allocation/controller.go
pkg/controllers/allocation/scheduling/suite_test.go
pkg/controllers/allocation/suite_test.go

Refactor: Removed cloudprovider awareness of binpacked pods

---

website/config.toml

Set docsy to use main branch rather than master.
Reported by @haugenj

Set docsy to use main branch rather than master

---

pkg/cloudprovider/aws/cloudprovider.go

None
Fixed a panic I ran into when the webhook was validating a particularly ill-formed `apply` 

fixed nil pointer exception in webhook w/ bad provisioner yaml

---

README.md

N/A
This PR adds a brief statement about the maturity of the project to the README. Users should be aware of the possibility of future API changes and that support is community-based and best-effort.

README Pre-production Disclaimer

---

website/content/en/docs/Reference/_index.md
website/content/en/docs/faqs.md
website/content/en/docs/getting-started/_index.md
website/content/en/docs/provisioner-crd.md

https://github.com/awslabs/karpenter/issues/697

Reverted docs until v0.3.4 is released

---

website/package-lock.json
website/package.json

#712 
increase version of ansi-regex required in package.json 
in response to issue identified by dependabot 

upgrade version of ansi-regex

---

pkg/cloudprovider/aws/instance.go

Log Capacity type after node creation

---

pkg/controllers/allocation/scheduling/scheduler.go

Remove injected topology hostname label

---

WORKING_GROUP.md

Working group notes

---

pkg/cloudprovider/aws/apis/v1alpha1/constraints.go
pkg/cloudprovider/aws/apis/v1alpha1/constraints_defaults.go
pkg/cloudprovider/aws/apis/v1alpha1/constraints_validation.go
pkg/cloudprovider/aws/apis/v1alpha1/zz_generated.deepcopy.go
pkg/cloudprovider/aws/securitygroups.go
pkg/cloudprovider/aws/subnets.go
pkg/cloudprovider/aws/suite_test.go
pkg/controllers/allocation/scheduling/preferences.go
pkg/utils/pretty/pretty.go

[aws] Removed spurious 's' from SecurityGroupSelector and changed wildcard from ''->'*'

---

API.md
pkg/apis/provisioning/v1alpha4/doc.go
pkg/apis/provisioning/v1alpha4/register.go
pkg/cloudprovider/aws/apis/v1alpha1/doc.go
pkg/cloudprovider/aws/apis/v1alpha1/register.go

Added doc.go to fix codegen

---

.github/workflows/ci.yaml

Cache go modules/bins for faster builds

---

website/content/en/docs/getting-started/_index.md

Bump docs to v0.4.1

---

Makefile
charts/karpenter/templates/webhook/deployment.yaml
charts/karpenter/values.yaml
cmd/controller/main.go
cmd/webhook/main.go
pkg/utils/options/options.go

Fixes an issue with webhook crashlooping

---

Makefile

Fixed an issue where CRD generation went to the wrong path

---

website/content/en/docs/getting-started/_index.md

bump eks version in getting started guide
- [ X ] Yes, PR includes docs updates

bump eks version in getting started guide

---

pkg/cloudprovider/aws/subnets.go

N/A
Improving error message per offline conversation w/ @ellistarn 

Improve error message when subnets not found

---

pkg/cloudprovider/aws/cloudprovider.go

Do not panic on webhook errors

---

pkg/apis/provisioning/v1alpha5/constraints.go
pkg/controllers/provisioning/scheduling/suite_test.go

Removed Taint Generation (for now)

---

website/content/en/_index.html
website/content/en/pre-docs/getting-started/_index.md

GitHub star buttons too prominent 
remove GitHub star buttons from
- index
- getting started

remove github star buttons

---

charts/karpenter/templates/default_provisioner.yaml
charts/karpenter/values.yaml

N/A
- Add limits to default provisioner in helm chart

add limits to default provisioner

---

pkg/cloudprovider/aws/securitygroups.go

Fixed a formatting issue with security group exclusions

---

website/content/en/pre-docs/concepts/_index.md

Some of the docs have changed since the Concepts doc was written. So this PR removes references to some docs that don't exist and fixes broken links. I fixed a couple of typos too.

Fixed broken links in Concepts doc

---

website/content/en/pre-docs/tasks/deprov-nodes.md
website/content/en/pre-docs/tasks/running-pods.md

n/a
add task describing deprovisioning nodes 

task: deprovision nodes 

---

website/content/en/pre-docs/reinvent.md

- [X ] Yes, PR includes docs updates

added markdown doc for reinvent demo

---

website/content/en/pre-docs/tasks/provisioning-task.md

This is the first draft of the Provisioning task documentation. It's a bit sparse, but if everyone thinks this is a good structure to start with, we can add to it later.

Provisioning tasks docs first draft

---

website/content/en/docs/AWS/constraints.md
website/content/en/docs/concepts/_index.md
website/content/en/docs/tasks/running-pods.md

Fixed a couple of minor docs issues.

Small docs clean-up issues

---

README.md

Adding my recent comparison video and updating the container day link

Updated video links in README

---

charts/karpenter/templates/controller/deployment.yaml
charts/karpenter/templates/webhook/deployment.yaml
charts/karpenter/values.yaml

Fixes #881 
- Exposed controller resources to values.yaml of Helm chart
- Exposed webhook resources to values.yaml of Helm chart
- Copied existing resources as recommened/default resources in values.yaml of Helm chart

Added ability to provide custom resources to the controller from Helm

---

pkg/controllers/provisioning/provisioner.go

Fixed a logging bug in pod filtering logic

---

README.md

https://github.com/aws/karpenter/issues/955

Fixed some stale links on the README

---

pkg/controllers/provisioning/binpacking/packable.go

remove log noise when excluding instance types while packing

---

CONTRIBUTING.md

Invalid link.
Modifies the contributing guidelines file to fix an invalid link.

Fix invalid 404 link.

---

pkg/controllers/termination/suite_test.go

spelling: eviction

---

website/content/en/docs/getting-started-with-kops/_index.md

Fixes #907
Provides a getting started on kOps-guide.

Add kops documentation

---

cmd/controller/main.go

It removes duplicated validation for options.

fix: remove duplicated validation

---

.github/PULL_REQUEST_TEMPLATE.md

N/A
Until we have better CI in place, authors should describe whatever minimal testing they're performing on their changes. Whether it's unit tests, some manual tests or if it's not applicable.
- [x ] No
**4. How was this change tested?**
N/A

Update PR template with testing steps

---

pkg/controllers/provisioning/provisioner.go

N/A
- fix requery pod to fix batch timing issue on already scheduled pods
- Reproduced many times and tested this fix manually with scale-ups

fix requery pod to fix batch timing issue on already scheduled pods

---

website/content/en/v0.5.3-docs/_index.md
website/content/en/v0.5.3-docs/getting-started/_index.md

Fix v0.5.3 docs

---

.github/ISSUE_TEMPLATE/docs-request.md

Folks are currently filing opening docs requests as bugs, which need reclassifying.
add new docs issue template.
on my own GitHub repo.

revise docs request issue template

---

website/content/en/preview/getting-started/_index.md
website/content/en/v0.5.3/getting-started/_index.md

Fixed references to cloudformation template

---

website/config.yaml

add docs menu item

---

website/layouts/partials/hooks/body-end.html

version warning shows entire path for old verions
revise regex

fix regex for version string

---

website/content/en/preview/faq.md

Added FAQ question that answers: How does Karpenter "know" which instance type to use?

Added instance type question to FAQ

---

website/content/en/preview/concepts/_index.md
website/content/en/preview/tasks/provisioning.md

Fixed a few concepts links

---

website/content/en/preview/getting-started/_index.md
website/content/en/preview/reinvent.md
website/content/en/v0.4.3/concepts/_index.md
website/content/en/v0.4.3/getting-started/_index.md
website/content/en/v0.5.0/getting-started/_index.md
website/content/en/v0.5.2/getting-started/_index.md
website/content/en/v0.5.3/getting-started/_index.md
website/content/en/v0.5.5/getting-started/_index.md
website/content/en/v0.5.5/reinvent.md

* Changed yaml file links to read in the appropriate release tags.
* Fixed a few other broken links
*
**2. Does this change impact docs?**

Fixed yaml file links and other broken links

---

Makefile

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Co-authored-by: Morten Linderud <morten@linderud.pw>
Based on [reproducible builds](https://reproducible-builds.org/docs/source-date-epoch/) documents, we need to consider using SOURCE_DATE_EPOCH which is set by downstream build systems while preparing the BUILD_DATE. So, this PR will add that support.
cc: @Foxboron

chore(makefile): enhance reproducible build

---

website/config.yaml

fix "docs" top nav item pointing to previous version
update link
local preview

minor link fix

---

pkg/controllers/provisioning/scheduling/scheduler.go

Fix: minor change to invert pod namespace and name in log line

---

.github/dependabot.yml

Updated dependabot

---

Makefile

Added default instance profile to dev loop

---

website/content/en/preview/faq.md

update faq to reflect support for ebs volumes

---

.github/dependabot.yml

Slow dependabot's roll

---

.github/dependabot.yml
website/package-lock.json

Update website dependencies and dependabot configuration

---

designs/bin-packing.md
pkg/controllers/provisioning/binpacking/packer.go
pkg/controllers/termination/suite_test.go
pkg/controllers/termination/terminate.go
pkg/test/pods.go

N/A
- Update links in docs
- Fix bug in pod eviction order
Unit test only
- [X ] No

Fix eviction order

---

.gitignore
hack/toolchain.sh
website/.gitignore

Dependency in a language other than go? 🙅 

Added hugo to go toolchain

---

pkg/apis/provisioning/v1alpha5/requirements.go

Unhandled error here can cause unexpected outcomes
Adds error handling when JSON is being unmarshaled

Handle unhandled error when unmarshaling JSON

---

pkg/apis/provisioning/v1alpha5/requirements.go

Add failure-domain.beta.kubernetes.io/region to the ignore label list

---

pkg/apis/provisioning/v1alpha5/provisioner_validation.go
pkg/controllers/provisioning/controller.go

Fix the wrong field in the api error for provisoner validation

---

README.md

Removed outdated README warning

---

pkg/apis/provisioning/v1alpha5/provisioner_validation.go
pkg/cloudprovider/metrics/cloudprovider.go
pkg/controllers/node/emptiness.go
pkg/controllers/node/expiration.go
pkg/utils/functional/functional.go
pkg/utils/ptr/ptr.go

Removed dead code

---

TROUBLESHOOTING.md

Added NotReady to troubleshooting

---

.github/workflows/ci.yaml

Attempts to upload the coverage data to coveralls.io for coverage analysis
- [N] No

upload the coverage report to coveralls.io

---

hack/toolchain.sh

https://blog.chainguard.dev/auto-sboms-with-ko/
`make toolchain && make apply`

Upgrade to ko v0.10.0

---

.github/workflows/issues.yaml

Exempt roadmap and help-wanted issues from being closed 

Exempt some issue labels from staling

---

.github/workflows/issues.yaml

use `stale` instead of `Stale` as a label.

Use lowercase stale as a label

---

.github/workflows/issues.yaml

Adds a few more labels to the exemptions, this will affect around 100 issues

Add more labels to excemptions

---

pkg/cloudprovider/aws/launchtemplate.go

https://github.com/aws/karpenter/issues/1408
- Bottlerocket mounts two volumes, xvda is for bottlerocket system components (like the API, OS, bootloader, etc) and xvdb is for containers (container images, logs, etc). 
- Launched Bottlerocket node before the change to reproduce the second volume being unencrypted
- Launched Bottlerocket node w/ change and observed both volumes are now encrypted 

encrypt bottlerocket second volume

---

pkg/controllers/selection/controller.go

Bumped debug logging to error logging for unsupported pods

---

.github/workflows/issues.yaml

Don't close bugs as stale

---

website/content/en/preview/AWS/provisioning.md

1416
Quote the wildcard selector names
Updated the subnet selector in my provisioner and verified that it worked.

update docs to quote the wildcard name selectors

---

pkg/cloudprovider/aws/instance.go
pkg/cloudprovider/aws/suite_test.go

Pass provider tags to CreateFleet for volumes as well.
#1430
Configured a provisioner with tags and inspected the volumes created in the EC2 console to ensure that the tags were applied. 

tag volumes with the provider tags

---

website/content/en/preview/concepts/_index.md
website/content/en/preview/provisioner.md

Fixes a couple of documentation problems.

Fix broken link and typos

---

website/content/en/preview/concepts/_index.md
website/content/en/v0.6.4/concepts/_index.md

N/A
- Fix Getting Started link in Concepts guide 

Fix link in Concepts doc

---

pkg/apis/provisioning/v1alpha5/suite_test.go
website/content/en/preview/provisioner.md

N/A
- replace 'nil' with 'omitted' for clarification
- add tests to ensure omitted values are considered valid
Unit tests

update docs regarding the TTL times

---

pkg/cloudprovider/aws/suite_test.go
website/content/en/preview/AWS/provisioning.md

- Document that tags are applied to created volumes as well
- Reword to indicate that we both merge & override
Unit test & doc changes only.

update tags doc

---

website/content/en/preview/AWS/_index.md

N/A
- Add eks best practices guide for Karpenter on the AWS landing page in Karpenter docs.

add link to eks best practices guide for karpenter

---

website/content/en/preview/getting-started/getting-started-with-terraform/_index.md
website/content/en/v0.5.3/getting-started-with-terraform/_index.md
website/content/en/v0.5.5/getting-started-with-terraform/_index.md
website/content/en/v0.5.6/getting-started-with-terraform/_index.md
website/content/en/v0.6.0/getting-started-with-terraform/_index.md
website/content/en/v0.6.1/getting-started-with-terraform/_index.md
website/content/en/v0.6.2/getting-started-with-terraform/_index.md
website/content/en/v0.6.3/getting-started-with-terraform/_index.md
website/content/en/v0.6.4/getting-started-with-terraform/_index.md

Fixing a typo. missing code block closer
previewed on MD editor 

added missing code block closer

---

website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step03-iam-cloud-formation.sh
website/content/en/v0.6.5/getting-started/getting-started-with-eksctl/scripts/step03-iam-cloud-formation.sh

https://github.com/aws/karpenter/issues/1492
- Fix cfn links

fix cfn links

---

website/content/en/preview/AWS/launch-templates.md

doc fix to kickstart docgen

---

website/content/en/preview/AWS/provisioning.md
website/content/en/v0.7.0/AWS/provisioning.md

https://github.com/aws/karpenter/issues/939
- Fixes block device mappings example in docs

fix block device mappings docs

---

pkg/cloudprovider/aws/fake/ec2api.go
pkg/cloudprovider/aws/suite_test.go
pkg/controllers/provisioning/binpacking/packable.go
pkg/controllers/provisioning/binpacking/packer.go
pkg/controllers/provisioning/binpacking/packer_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/node.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/utils/resources/resources.go

N/A
Resolve issue related to pod compatibility leading to an impossible instance type construct
Unit tested + tested deployment scale-up/scale-down on EKS

introduce theoretical node

---

website/content/en/preview/faq.md

Closes #1493
Adds a FAQ entry regarding namespace provisioning
N/A

document issues that arise from namespace based provisioning selection

---

website/content/en/preview/upgrade-guide/_index.md

Adding upgrade notes
- [ x] Yes, PR includes docs updates

Add upgrade guide

---

charts/karpenter/templates/configmap-logging.yaml

Fix wrong YAML key

---

.github/workflows/ci.yaml
.github/workflows/deflake.yml
.github/workflows/nightly.yaml

Read go version from go.mod instead of hardcoding it so that we can change it one place and see the effect everywhere.

read go version from go.mod

---

README.md

Added link for AWS Community Day in Turkey

---

CODEOWNERS
OWNERS

Updated CODEOWNERS

---

.github/workflows/nightly.yaml
hack/nightly.sh

* s/nightly/Nightly
* Removes extra lines from nightly.sh

Rename role and simplify

---

website/content/en/preview/AWS/launch-templates.md

N/A
- Fix AWS EKS bootstrap script example parameter description
`make website`

fix bootstrap example

---

pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/selection/suite_test.go
pkg/test/expectations/expectations.go

N/A
updated tests for topology & pod affinity/anti-affinity
Skip'd for now until new PR is merged in.
Unit test

updated tests for topology & pod affinity/anti-affinity

---

website/content/en/preview/faq.md

N/A
- Clarify the metal docs to note that all non-metal instance types are prioritized ahead of metal ones.

clarify metal docs faq

---

website/content/en/preview/tasks/deprovisioning.md

fix anchor typo

---

website/content/en/preview/troubleshooting.md

Fixing tiny mistake in previous PR
Fixing tiny mistake in previous PR
N/A

fixing mistake in SGP Troubleshooting doc

---

.github/workflows/stale.yml

Fix typo in stale.yml

---

pkg/cloudprovider/aws/amifamily/ami.go

N/A
If the SSM parameter query fails, log the query that was made.
Deploying onto my EKS cluster

log the query that failed

---

website/content/en/preview/AWS/launch-templates.md

Added note about cleaning up LTs that Karpenter creates after sixty seconds. 

Added note about cleaning up Karpenter LTs

---

website/content/en/v0.8.2/faq.md

Fix typo in FAQ.md

---

hack/add-snapshot-tag.sh
hack/release.sh
hack/release_common.sh
hack/snapshot.sh
pkg/controllers/provisioning/scheduling/suite_test.go

Fix shebang arguments and typo

---

pkg/cloudprovider/aws/suite_test.go
pkg/controllers/metrics/node/suite_test.go
pkg/controllers/metrics/pod/suite_test.go
pkg/controllers/node/suite_test.go
pkg/controllers/persistentvolumeclaim/suite_test.go
pkg/controllers/provisioning/scheduling/instance_selection_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/termination/suite_test.go
pkg/test/expectations/expectations.go
pkg/test/pods.go
pkg/test/provisioner.go

Simplifies expectation sprawl in test code

---

.github/workflows/stale.yml

Enables stalebot with settings that work. 
The dry run is [here](https://github.com/aws/karpenter/runs/6099641933?check_suite_focus=true) and it seems to have worked as expected.

Enable StaleBoT to label and close old issues

---

.github/workflows/stale.yml

WIP try GitHub stale action

---

pkg/controllers/provisioning/batcher.go
pkg/controllers/provisioning/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/test/expectations/expectations.go

N/A
Remove item accumulation which was only used for unit testing.
Unit tests & deployed to EKS with scale up/scale down.

rework batching

---

pkg/cloudprovider/aws/fake/ec2api.go
pkg/cloudprovider/aws/suite_test.go

N/A
Synchronize just the InsufficientCapacityPools access, race is hard to reproduce locally. Pushing to test on GH CI.
Unit tested locally and ran the CI tests on GitHub four times with no failures.

synchronize access to the InsufficientCapacityPools in the fake ec2

---

website/content/en/preview/tasks/scheduling.md
website/content/en/v0.9.0/tasks/scheduling.md

N/A
Add docs for pod affinity/anti-affinity.
N/A

add docs describing pod affinity/anti-affinity

---

pkg/controllers/provisioning/suite_test.go
website/content/en/preview/tasks/provisioning.md

#1735
- fixes doc typo
- adds additional unit tests
Unit testing

fix typo in docs

---

pkg/apis/provisioning/v1alpha5/requirements.go
pkg/apis/provisioning/v1alpha5/suite_test.go

Fixes #1729
consistently render requirements that we rebuild
Unit testing, and deployed to EKS verified consistent rendering using reproduction steps from issue.

consistently render requirements that we rebuild

---

website/content/en/preview/troubleshooting.md

https://github.com/aws/karpenter/issues/933
- clarifies that the policy should be applied to the KMS key itself. 

clarify kms troubleshooting doc

---

.github/workflows/release.yaml

Similar to nightlies this also needs to have the aws-credntials tool set up.
- [ x] No

Add the aws-credentials tool

---

pkg/controllers/provisioning/scheduling/node.go

N/A
Show the tightened requirements in the log message as it will be more
useful than just the provisioner requirements.
Unit testing

improve log message upon failure to find an instance type

---

pkg/cloudprovider/aws/suite_test.go
pkg/controllers/provisioning/provisioner.go
website/content/en/preview/AWS/provisioning.md

Fixes #1766
register the provisioner used on the context
Unit testing & deployed to EKS to verify tags added to instance.

register the provisioner used on the context

---

.github/workflows/snapshot-pr-approval.yaml

Release PR snapshot upon approval message with `/release`

---

charts/karpenter/templates/role.yaml

Saw a duplication in rendered output from helm, looks to me it should be safe to remove.
Not tested yet, but I'm in the process of deploying `karpenter` in one of our cluster for testing. Also, I don't use `helm` so kindly inform me if there is something I can use or run to test it locally.

Remove duplicate in role helm template

---

website/content/en/preview/upgrade-guide/_index.md

…ve done in the doc rather than what was persecribed
Correcting this part of the doc because we started adding sections in the doc rather than files.

Fix upgrade guide to mention sections instead of separate pages

---

hack/release.sh
hack/release_common.sh
hack/snapshot.sh

Adds cosign to the snapshot release process.

Add cosign to snapshots

---

website/content/en/preview/concepts/_index.md

N/A
Update docs to reflect affinity/anti-affinity support.
Docs preview locally.

update docs regarding affinity/anti-affinity support

---

.github/workflows/snapshot-pr-approval.yaml

Trying out PR snapshot to test AWS auth

Add PR snapshot test to auth with AWS

---

.github/workflows/snapshot-pr-approval.yaml

Trying out new settings for PR snapshot.
- [x ] No

Test PR snapshots use different sha for configure aws creds

---

pkg/apis/provisioning/v1alpha5/constraints.go
pkg/apis/provisioning/v1alpha5/labels.go
pkg/apis/provisioning/v1alpha5/register.go
pkg/apis/provisioning/v1alpha5/util.go
pkg/cloudprovider/aws/instance.go
pkg/cloudprovider/aws/instancetype.go
pkg/cloudprovider/aws/instancetypes.go
pkg/cloudprovider/aws/suite_test.go
pkg/cloudprovider/fake/cloudprovider.go
pkg/controllers/node/emptiness.go
pkg/controllers/node/initialization.go
pkg/controllers/node/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/inflightnode.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/test/expectations/expectations.go
pkg/utils/options/options.go
website/content/en/preview/concepts/_index.md
website/content/en/preview/tasks/scheduling.md
website/content/en/preview/upgrade-guide/_index.md

Will update once it's not a draft
- Eliminate binding of pods to nodes
- Register extended resources as an annotation

don't pre-bind pods to nodes

---

.github/workflows/pr-approval-test1.yaml
.github/workflows/pr-approval-test2.yaml

Adding temp GAs with variation in library to troubleshoot GA auth problem.

Add test GAs for troubleshooting GA auth issue

---

pkg/controllers/provisioning/scheduling/scheduler.go

N/A
fix typo in the log message and display pod counts for existing/new capacity
New logs look like this: 
```
karpenter-765c768999-sn5p9 controller 2022-05-19T16:42:43.239Z	INFO	controller	Batched 30 pod(s) in 1.502638571s	{"commit": "f9b3dbb"}
karpenter-765c768999-sn5p9 controller 2022-05-19T16:42:43.254Z	INFO	controller	9 pod(s) will schedule against new capacity, 21 pod(s) against existing capacity	{"commit": "f9b3dbb"}
karpenter-765c768999-sn5p9 controller 2022-05-19T16:42:45.523Z	INFO	controller	Launched instance: i-08f1f60b073cdcfaa, hostname: ip-192-168-26-167.us-west-2.compute.internal, type: c5a.8xlarge, zone: us-west-2d, capacityType: spot	{"commit": "f9b3dbb", "provisioner": "default"}
karpenter-765c768999-sn5p9 …
```

fix the log message and display pod counts for existing/new capacity

---

website/content/en/preview/AWS/provisioning.md

[Issue #1779](https://github.com/aws/karpenter/issues/1779)
Add a Provisioner example to the Karpenter AWS Provisioner  section.

Adding AWS provisioner example

---

examples/provisioner/100-cpu-limit.yaml
examples/provisioner/bottlerocket.yaml
examples/provisioner/large-instances.yaml
examples/provisioner/node-ttls.yaml
examples/provisioner/spot.yaml

- instanceProfile unnecessary
- Missing subnetSelector in many

Fixed up examples

---

.github/workflows/release.yaml

Trying to fix our broken release workflow.
N/A
Following https://github.com/marvinpinto/actions/issues/340#issuecomment-983254674 since our failures seem to match and we just added permissions here - https://github.com/aws/karpenter/pull/1816/files
Not sure if this is something I can test outside of experimentation on our repo which is unfortunate.

Update permissions in release.yaml

---

.github/workflows/release.yaml

N/A
Removing permissions in hope to fix the release workflow
None

Update release.yaml - remove permissions for now.

---

charts/karpenter/templates/configmap.yaml
charts/karpenter/values.yaml
cmd/controller/main.go
pkg/cloudprovider/aws/suite_test.go
pkg/config/config.go
pkg/config/suite_test.go
pkg/controllers/provisioning/batcher.go
pkg/controllers/provisioning/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/test/config.go
website/content/en/preview/tasks/configuration.md

Fixes #1690
make batching window configurable
Unit testing & deploying to EKS to change config and see changes in batching behavior.

add a global config & make batching window configurable

---

website/content/en/v0.10.1/getting-started/migrating-from-cas/_index.md

Fixed the typo

---

pkg/cloudprovider/aws/instancetypes.go

N/A
As part of #1857 , @ellistarn modified how instanceTypes are cached in the AWS cloud provider.  With this change we no longer need to keep a separate key in the instanceType cache for each Provisioner/Provider.  With a separate key per Provisioner, memory usage would scale linearly with the number of provisioners.  With this change it will 
Automated tests still pass after this change.  Also tested manually to evaluate memory utilization before/after this change.
With 10 provisioners defined, max memory usage before the change was 430MB.  Max memory usage after this change was 232MB.
By submitting this pull request, I confirm that my contribution is made …

remove hashed provider as key from instanceType cache

---

website/content/en/preview/tasks/scheduling.md

Clarified os/arch docs

---

ADOPTERS.md
USERS.md

Adds a file so karpenter users can self report
**2. How was this change tested?**
it wasn't
**17. Does this change impact docs?**

Add ADOPTERS.md for user list

---

ADOPTERS.md

Fix typo in adopters

---

ADOPTERS.md

N/A
Added Codefresh as an adopter

Added Codefresh in Adopters

---

.vscode/settings.json
ADOPTERS.md

N/A
-  Added [Stytch](http://stytch.com/) to ADOPTERS.md
- N/A

Add Stytch to ADOPTERS.md

---

pkg/cloudprovider/aws/suite_test.go

N/A
deflake test by just clearing the instance type cache
Verified by finding a random seed from ginkgo that always failed,
which now works.

deflake test by just clearing the instance type cache

---

website/content/en/preview/upgrade-guide/_index.md

add notes to v0.11 upgrade docs about extended resource device plugins

---

pkg/controllers/counter/controller.go

This eliminates a lot of extra error logs

switch back to just retrying instead of returning an error

---

README.md

Fixes # 
KubeCon EU 2022 talk about Spot and Karpenter
N/A
```release-note
```

docs: add kubecon eu 2022 talk

---

charts/karpenter/templates/webhooks.yaml

chore: added missed DELETE method for provisioner

---

hack/docs/instancetypes_gen_docs.go
website/content/en/preview/tasks/configuration.md

Fixes # 
docs: fix instance type doc generator and update docs
* Locally
```release-note
```

docs: fix instance type doc generator and update docs

---

pkg/cloudprovider/aws/instance.go

Fixes # 
- Remove Fleet QPS throttles that don't make sense and aren't used :p 
* `make test` 
```release-note
```

chore: remove fleet qps throttles

---

pkg/cloudprovider/aws/fake/atomic.go
pkg/cloudprovider/aws/fake/ec2api.go
pkg/cloudprovider/aws/suite_test.go

Fixes # 
N/A
create atomic generic types and use them for the fake EC2 mock
* Ran make battletest 50x times with no races
```release-note
```

test: create atomic generic types and use them for the fake EC2 mock

---

pkg/config/config.go
pkg/config/suite_test.go

Fixes # 
* Running the config tests 125x times.
```release-note
```

test: wait on the config to be updated prior to starting test

---

.github/workflows/deflake.yml
Makefile

Fixes # 
- Fix deflake workflow, since GHA env wasn't parsing the for loop `{1..10}` syntax. So the deflake tests were only being executed twice rather than 10 times (it worked fine on a MBP) 
- Added `workflow_dispatch` so that we can manually trigger if we want to investigate a test
* tested on my fork within GHA
```release-note
```

test: fix deflake

---

website/content/en/preview/contributing/development-guide.md

Fixes # 
- Update required go version
```release-note
```

docs: update go version requirement in dev guide

---

pkg/cloudprovider/aws/fake/atomic.go

Fixes # 
Clone the object instead of storing it directly so that the fake API retains ownership of the cloned copy.
* Unit testing
```release-note
```

test: fix a fake ec2 api test flake

---

pkg/cloudprovider/aws/cloudprovider.go

Fixes # 
Perform a dry-run EC2 DescribeInstanceTypes call at startup so that if it fails, the error message is prefixed with "Checking EC2 API connectivity". 
Currently if Karpenter can't reach EC2 for some reason, it results in an error which doesn't give much of a hint about why it failed:
```
ERROR	controller.aws.launchtemplate	aws/launchtemplate.go:233	Unable to hydrate the AWS launch template cache, RequestCanceled: request context canceled
```
* Unit testing & deployed to EKS
```release-note
```

feat: at startup immediately perform a dry-run call to EC2

---

pkg/cloudprovider/aws/apis/v1alpha1/register.go
pkg/cloudprovider/aws/instancetype.go
pkg/cloudprovider/aws/suite_test.go
website/content/en/preview/tasks/scheduling.md

Fixes # 
Support for new label that will help users specify a minimum number of pods per node. Following up with GT/LT operators. 
* manual, unit
```release-note
Added support for well known label `karpenter.k8s.aws/instance-pods`
```

Feat: Support for instance-pods well known label

---

pkg/cloudprovider/aws/instancetypes.go
website/content/en/preview/upgrade-guide/_index.md

Fixes # 
*remove price warning and add upgrade info about permissions
```release-note
```

docs: remove price warning and add upgrade info about permissions

---

charts/karpenter/templates/role.yaml
cmd/controller/main.go

Cherry picked from https://github.com/aws/karpenter/pull/1988 and https://github.com/aws/karpenter/pull/1990
*
```release-note
```

fix: RBAC permissions for v0.12.0

---

pkg/controllers/state/cluster.go

Fixes # 
Bug introduced by mine and Suket's changes being merged together.
* Deployed to EKS
```release-note
```

fix: only check for a valid provisioner instead of the provider

---

pkg/controllers/provisioning/scheduling/suite_test.go

Fixes # 
add a test for inflight nodes combined with providerRef
* unit testing
```release-note
```

test: add a test for inflight nodes combined with providerRef

---

hack/toolchain.sh

Fixes # 
Upgrade to a newer version of cosign.
* make toolchain
```release-note
```

chore: Upgrade cosign to 1.9.0

---

website/content/en/preview/tasks/scheduling.md
website/content/en/v0.10.0/tasks/scheduling.md
website/content/en/v0.10.1/tasks/scheduling.md
website/content/en/v0.11.0/tasks/scheduling.md
website/content/en/v0.11.1/tasks/scheduling.md
website/content/en/v0.12.0/tasks/scheduling.md
website/content/en/v0.12.1/tasks/scheduling.md
website/content/en/v0.13.0/tasks/scheduling.md
website/content/en/v0.13.1/tasks/scheduling.md
website/content/en/v0.9.0/tasks/scheduling.md
website/content/en/v0.9.1/tasks/scheduling.md

Fixes # 
fixed inaccurate note about pod affinity
*
```release-note
None
```

docs: fixed inaccurate note about pod affinity

---

ADOPTERS.md

Fixes # 
*
```release-note
```

docs: adding Omaze to list of adopters

---

Makefile
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/cluster.go
pkg/test/daemonsets.go
pkg/test/deployment.go
pkg/test/pods.go
pkg/test/provisioner.go
test/pkg/environment/environment.go
test/pkg/environment/expectations.go
test/pkg/environment/monitor.go
test/suites/integration/suite_test.go

Fixes # 
Add initial integration tests.
* Unit testing
```release-note
```

test: add initial integration tests

---

pkg/scheduling/suite_test.go

Fixes # 
When we moved from ginkgo -> go test, this test was lost. 
*
```release-note
None
```

Test: Add a missing test directive to pkg/scheduling

---

charts/karpenter/templates/deployment.yaml
charts/karpenter/values.yaml

adding the ability to change the revisionHistoryLimit for the deployment on the helm chart
- [ X ] Yes, PR includes docs updates # Does it generate the docs automatically. 

feat: add revisionHistoryLimit option to chart

---

pkg/controllers/metrics/state/node.go
pkg/controllers/metrics/state/scraper.go

Fixes CI failures caused by #2031 
* Running `make verify` locally
```release-note
NONE
```

fix: metric CI failure

---

CODEOWNERS

Fixes # 
*
```release-note
None
```

Chore: Remove API Codeowners

---

pkg/cloudprovider/aws/cloudprovider.go
pkg/cloudprovider/aws/createfleetbatcher.go
pkg/cloudprovider/aws/createfleetbatcher_test.go
pkg/cloudprovider/aws/fake/ec2api.go
pkg/cloudprovider/aws/instance.go
pkg/cloudprovider/aws/suite_test.go
pkg/controllers/provisioning/scheduling/node.go
pkg/controllers/provisioning/scheduling/scheduler.go

Batches create fleet calls to reduce throttling.
*Unit testing  & deployed to EKS
```release-note
```

fix: batch create fleet calls

---

hack/docs/instancetypes_gen_docs.go
pkg/cloudprovider/aws/zz_generated.pricing.go
website/content/en/preview/AWS/instance-types.md
website/content/en/preview/tasks/metrics.md

Fixes # 
Modify instance type generator to fetch all types with new default filtering and re-gen.
*
```release-note
```

chore: update docs

---

pkg/controllers/termination/controller.go
pkg/controllers/termination/suite_test.go

Fixes # 
Fixes termination test errors caused by manual instantiation of controller in test.
* Running `make test`
```release-note
NONE
```

fix: termination test errors

---

website/content/en/preview/tasks/scheduling.md

Fixes # 
* 
```release-note
```

chore: fix instance label description for generation

---

go.mod
go.sum
pkg/cloudprovider/aws/fake/pricingapi.go
pkg/cloudprovider/aws/pricing.go
pkg/cloudprovider/aws/suite_test.go
pkg/cloudprovider/aws/zz_generated.pricing.go

Fixes # 
https://github.com/aws/aws-sdk-go/issues/4480
- Reverts a fix when upgrading the AWS SDK due to a breaking change in the SDK. The breaking change was reverted in the aws sdk, so reverting the fix. 
* `make release-gen`
```release-note
```

fix: aws pricing sdk types

---

ADOPTERS.md

Fixes # 
Adds Tyk Cloud as an end user utilizing karpenter to scale workloads on EKS.
*
```release-note
```

chore: add tyk cloud as an adopter

---

website/content/en/preview/tasks/scheduling.md

Fixes #2191
Add a warning about misspelled custom labels
*
```release-note
None
```

docs: Add a warning about misspelled custom labels

---

test/pkg/environment/expectations.go
test/suites/integration/cni_test.go

Fixes # 
* Tested them via `go test -v ./test/suites/integration/...`
```release-note
test: Add tests to verify maxPods on nodes
```

test: Add tests to verify maxPods on nodes

---

ADOPTERS.md

Fixes # 
*
```release-note
```

docs: Update ADOPTERS file with Beeswax organization

---

designs/consolidation.md

doc: add consolidation design doc

---

pkg/controllers/termination/eviction.go

Fixes # 
fix: Do not log evicted pods, since they are emitted as events
*
```release-note
None
```

fix: Do not log evicted pods, since they are emitted as events

---

test/suites/storage/suite_test.go

We now disallow missing StorageClasses so had to fix our tests.
```
Ran 2 of 2 Specs in 194.305 seconds
SUCCESS! -- 2 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestStorage (194.31s)
```
```release-note
test: Fix storage test for static volumes
```

test: Fix storage test for static volumes

---

website/content/en/preview/AWS/provisioning.md
website/content/en/preview/tasks/scheduling.md

Fixes # 
- Fixes dead link in the AWS provisioning doc
- Fixes ending of warning on scheduling doc
* Previewed docs
```release-note
None
```

docs: Fix dead link and end alert message

---

.github/workflows/ci.yaml
Makefile
pkg/test/expectations/expectations.go

* Unit tests
```release-note
```

chore: add k8s 1.23 to github CI and change default

---

pkg/cloudprovider/aws/instance.go

Fixes # 
- return last error instead of all errors. The errors are generally all the same, and the last one is really all that matters. 
- Remove unreachable branch and fixed propagated error on  resolving node name.
* manually in eks
```release-note
```

chore: remove unreachable err

---

pkg/controllers/state/cluster.go

Fixes #2266
*
```release-note
```

revert part of previous newnode optimization

---

ADOPTERS.md

Adds Anthropic to Adopters list.
* N/A
```release-note
NONE
```

Add Anthropic to ADOPTERS.md

---

hack/docs/instancetypes_gen_docs.go

Description: 
fix the release-gen output
```release-note
```

fix release-gen output

---

ADOPTERS.md

Add Cordial to adopters list.
```release-note
Add Cordial to list of adopters
```

add cordial to adopters list

---

ADOPTERS.md
pkg/apis/provisioning/v1alpha5/provisioner_validation.go
pkg/controllers/consolidation/controller.go
pkg/controllers/state/cluster.go

- Use ptr package instead of aws SDK in main code
- Fix sorting of adopters file
* Unit testing
```release-note
```

chore: use ptr instead of aws SDK

---

pkg/cloudprovider/aws/createfleetbatcher.go

Buffer the result channel to prevent any caller from blocking other callers.
*
```release-note
```

fix: resolve issue with triggering

---

test/pkg/environment/environment.go
test/pkg/environment/expectations.go
test/suites/integration/ami_test.go
test/suites/integration/block_device_mappings_test.go
test/suites/integration/cni_test.go
test/suites/integration/metadata_options_test.go
test/suites/integration/security_group_test.go
test/suites/integration/storage_test.go
test/suites/integration/subnet_test.go
test/suites/integration/tags_test.go
test/suites/integration/ttl_test.go
test/suites/utilization/suite_test.go

Fixes # 
- Adds aws integration test suite
```
> TEST_FILTER=Integration make e2etests
...
Ran 19 of 20 Specs in 1795.926 seconds
SUCCESS! -- 19 Passed | 0 Failed | 0 Pending | 1 Skipped
--- PASS: TestIntegration (1795.93s)
PASS
ok  	github.com/aws/karpenter/test/suites/integration	1796.956s
testing: warning: no tests to run
PASS
ok  	github.com/aws/karpenter/test/suites/utilization	0.715s [no tests to run]
```
```release-note
```

test: AWS Integration tests

---

examples/README.md

Fixes # 
- Add examples readme with envsubst command for applying to cluster w/ the cluster name
executed:
```
CLUSTER_NAME=kdemo envsubst < provisioner/spot.yaml | kubectl apply -f -
```
```release-note
```

chore: examples readme

---

test/infrastructure/README.md

Fixes # 
- Add karpenter test infra readme
* tested code blocks in readme
```release-note
```

chore: test infrastructure readme

---

hack/release_common.sh

Fixes # 
Removes the retry logic we added before since there's no need for it.
* make snapshot
```release-note
```

Remove the retry logic since there's no need for it.

---

pkg/controllers/controllers.go

Fixes # 
Fix error that was introduced by a re-base.
* E2E test
```release-note
```

re-add the consolidation controller that was removed after a rebase

---

website/content/en/preview/upgrade-guide/_index.md
website/content/en/v0.15.0/upgrade-guide/_index.md

Fixes # 
Add upgrade notes
*
```release-note
```

add v0.15.0 upgrade notes

---

website/content/en/_index.html

Fixes # N/A
Adds content to the landing page describing Karpenter's cost benefits now that #2123 has landed.
* Tested locally.
```release-note
NONE
```
**Screenshots**

Add Cost Benefits from Consolidation to Landing Page

---

test/infrastructure/clusters/test-infra/git-stats-exporter/git-stats-exporter.yaml
test/infrastructure/clusters/test-infra/git-stats-exporter/karpenter-repo.yaml
test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml
test/suites/common/setup.yaml

Fixes # 
- Cron for pipeline-run integ tests every 4 hours starting at the 7th minute.
* tested on eks cluster.
```release-note
```

chore: add pipeline-run cron for integ tests

---

pkg/cloudprovider/aws/apis/v1alpha1/tags.go
pkg/cloudprovider/aws/cloudprovider.go
pkg/cloudprovider/aws/errors.go
pkg/cloudprovider/aws/fake/ec2api.go
pkg/cloudprovider/aws/launchtemplate.go
pkg/controllers/node/emptiness.go
pkg/controllers/termination/controller.go
pkg/controllers/termination/suite_test.go
pkg/controllers/termination/terminate.go
pkg/utils/functional/functional.go
pkg/utils/functional/suite_test.go

Fixes # 
*
```release-note
```

Chore: Replace functional methods with samber/lo

---

website/content/en/preview/AWS/user-data.md

Fixes # 
*
```release-note
```

Docs: add a providerRef example in the custom userdata docs

---

pkg/cloudprovider/aws/amifamily/ami.go
pkg/cloudprovider/aws/amifamily/resolver.go
pkg/cloudprovider/aws/instancetypes.go
pkg/cloudprovider/aws/launchtemplate.go
pkg/cloudprovider/aws/pricing.go
pkg/cloudprovider/aws/securitygroups.go
pkg/cloudprovider/aws/subnets.go
pkg/cloudprovider/aws/suite_test.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/utils/pretty/changemonitor.go

Reduce log spam.
* Unit tested & deployed to EKS
```release-note
```

chore: reduce log spam

---

website/content/en/preview/tasks/deprovisioning.md
website/content/en/v0.15.0/tasks/deprovisioning.md

add information regarding spot node consolidation
```release-note
```

docs: add information regarding spot node consolidation

---

pkg/cloudprovider/aws/cloudprovider.go

This reverts commit 91a82ec86075c8dd765a2a6219d8e85a35c32033.
Fixes # 
- revert since in the middle of release 
*
```release-note
```

chore: Revert "fix 3rd gen filter (#2338)"

---

test/pkg/environment/expectations.go
test/pkg/environment/monitor.go
test/suites/integration/ttl_test.go

Fixes # 
*
```release-note
```

Test: improved test assertion error printing

---

Makefile

Fixes # 
- Up the e2e test timeout
*
```release-note
```

chore: up the e2e test timeout

---

pkg/cloudprovider/aws/cloudprovider.go
pkg/cloudprovider/aws/instancetypes.go
pkg/cloudprovider/aws/pricing.go
pkg/cloudprovider/aws/subnets.go
pkg/controllers/consolidation/controller.go
pkg/controllers/controllers.go
pkg/controllers/provisioning/controller.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/state/cluster.go
pkg/controllers/state/node.go

Acquire and release some locks during health checks to identify deadlock.
*
```release-note
```

fix: improve health checks

---

charts/karpenter/values.yaml

We've seen slight CPU throttling on the webhook and a user has reported an OOM at one point.
*
```release-note
```

chore: bump webhook resource requests

---

website/content/en/preview/tasks/scheduling.md
website/content/en/v0.16.0/tasks/scheduling.md

Fixes # 
- Updates language in the `Weighted Provisioner` section of the docs to make details more clear
*
```release-note
None
```

fix: Improve language and grammar in provisioner weighting doc

---

pkg/controllers/state/provisioner.go

Fixes # 
- Cleans up the provisioner state filters
* `make test`
* Manual validation
```release-note
None
```

chore: Add delete as a separate filter in provisioner state

---

.github/workflows/ci.yaml

Fixes # 
- Remove k8s 1.19 in the GHA test grid and add K8s 1.24. 
*
```release-note
```

chore: remove k8s versions 1.19 and add 1.24

---

website/content/en/preview/faq.md

Fixes # 
- Update docs with K8s versions tested
*
```release-note
```

chore: fix faqs for k8s versions

---

Makefile
pkg/controllers/controllers.go
pkg/utils/options/options.go
website/content/en/preview/contributing/development-guide.md
website/content/en/preview/tasks/scheduling.md

Fixes # 
Enable running the Karpenter controllers locally for faster dev loop and attaching a debugger 🎉 
* `make run`
```release-note
None
```

test: Enable karpenter controllers to run locally

---

.github/workflows/ci.yaml

Fixes # 
*
```release-note
```

ci.yaml > Fix typo "k8sVersioan"

---

ADOPTERS.md

Fixes # 
N/A
Added H2O as an adopter
N/A

Added H2O.ai to adopters.md

---

.golangci.yaml
hack/boilerplate.sh
hack/code/prices_gen.go
hack/code/vpc_limits_gen.go
hack/docs/configuration_gen_docs.go
hack/docs/instancetypes_gen_docs.go
pkg/cloudprovider/aws/instancetypes_test.go
pkg/cloudprovider/aws/launchtemplate_test.go
pkg/cloudprovider/aws/pricing_test.go
pkg/cloudprovider/aws/securitygroups_test.go
pkg/cloudprovider/aws/subnets_test.go
pkg/cloudprovider/aws/suite_test.go
pkg/config/suite_test.go
pkg/controllers/consolidation/suite_test.go
pkg/controllers/metrics/pod/suite_test.go
pkg/controllers/metrics/state/suite_test.go
pkg/controllers/node/suite_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/provisioning/suite_test.go
pkg/controllers/state/suite_test.go
pkg/controllers/termination/suite_test.go
pkg/scheduling/requirement_test.go
test/suites/integration/ami_test.go
test/suites/integration/cni_test.go
test/suites/integration/metadata_options_test.go
test/suites/integration/subnet_test.go
test/suites/integration/ttl_test.go
test/suites/utilization/suite_test.go

Fixes # 
- Enables linting on any files matching `*_test.go`
* `make test`
```release-note
None
```

chore: Enable linting on test files

---

test/suites/integration/ttl_test.go

Fixes # 
*
```release-note
```

test: fix other ttl test

---

test/pkg/environment/expectations.go

The test checked that a single pod had the expected environment
and was ready before allowing the next test to proceed. The second
controller pod would sometimes be pending causing the rest of the
tests to fail quickly due to a check in BeforeEach.
*
```release-note
```

test: ensure all controller pods are updated and running before allowing the next test to proceed

---

test/pkg/environment/expectations.go

Fixes # 
*
```release-note
```

test: reduce test cyclo complexity

---

test/suites/common/suite.yaml
test/suites/upgrade/pipeline.yaml

Fixes # 
Tested via kubectl apply --dry-run
*
```release-note
```

test: fix params specification

---

test/suites/common/notify-slack.yaml

Fixes # 
*
```release-note
```

test: add the namespace to the notify-slack task

---

pkg/cloudprovider/aws/cloudprovider.go

Remove a debug log that shouldn't have been committed
*
```release-note
```

chore: remove debug log

---

test/infrastructure/clusters/test-infra/git-stats-exporter/karpenter-repo.yaml

Fixes # 
*
```release-note
```

chore: remove the karpenter repo from git-stats-exporter for now

---

hack/release.sh

Fixes # 
Adds scripts for automating some of the manual steps for modifying configs for the website during the release process.
* make release
```release-note
```

chore: Automate website release changes

---

pkg/cloudprovider/aws/createfleetbatcher.go

fix: deep copy input to avoid race and modifying caller's input

---

website/content/en/preview/getting-started/getting-started-with-terraform/_index.md

Update to new module versions.
I used the updated instructions to create a new cluster and was able to scale up a deployment, nodes were created became ready and all pods were running.
```release-note
```

docs: update terraform instructions

---

README.md

Added YT video for Workload Consolidation with Karpenter
* N/A
- Added YT video for Workload Consolidation with Karpenter
```release-note
```

docs:  Added YT video for Workload Consolidation to README

---

website/content/en/preview/troubleshooting.md
website/content/en/v0.16.0/troubleshooting.md
website/content/en/v0.16.1/getting-started/getting-started-with-terraform/_index.md
website/content/en/v0.16.1/troubleshooting.md

Fixes #2487 
Previous PR #2387 fixed issue with Terraform MNG creation and replicas changes made in #2311. This PR updates v0.16.1 version of docs so this change is propagated everywhere
* `make verify`
```release-note
None
```

docs: Fix miss of v0.16.1 docs

---

.github/workflows/ci.yaml
.github/workflows/deflake.yml
.github/workflows/snapshots.yaml

Fixes # 
*
```release-note
```

chore: use latest go patch version

---

website/content/en/preview/AWS/provisioning.md
website/content/en/v0.16.1/AWS/provisioning.md

Fixes # 
- Fix AMI Tag Example in the docs
*
```release-note
```

docs: Fix AMI Tag Example

---

.github/workflows/ci.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/deflake.yml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/snapshots.yaml

Fixes # 
- Bump all GH actions to v3
* CI
```release-note
None
```

chore: Bump all GH actions to v3

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/docs-request.yaml
.github/ISSUE_TEMPLATE/request.yaml

Fixes # 
- Markdown is not currently included in Issue Templates, so we have to use a textarea for now
* Tested on fork
```release-note
None
```

chore: Fix community note in issue template

---

.github/ISSUE_TEMPLATE/bug.yaml
Makefile
pkg/controllers/consolidation/suite_test.go
test/suites/integration/emptiness_test.go
test/suites/integration/kubelet_config_test.go

Fixes # 
- Fixes flakiness due to instance type filtering on Kubelet Configuration testing
- Fixes Bug template to contain correct version prompt information
- Injects Karpenter version into `Makefile` automatically
```release-note
None
```

test: Flakiness Fix for Kubelet Configuration

---

pkg/controllers/node/initialization.go
pkg/utils/node/node.go
test/pkg/environment/expectations.go
test/suites/upgrade/pipeline.yaml

Fixes # 
- Add additional node info in testing for `BeforeEach`
- Bump upgrade tests to `v0.16.1` where we have fixed test flakiness
* `make test`
```release-note
None
```

test: Add additional node info to testing

---

website/content/en/preview/AWS/launch-templates.md
website/content/en/preview/AWS/provisioning.md
website/content/en/v0.12.0/AWS/launch-templates.md
website/content/en/v0.12.0/AWS/provisioning.md
website/content/en/v0.12.1/AWS/launch-templates.md
website/content/en/v0.12.1/AWS/provisioning.md
website/content/en/v0.13.0/AWS/launch-templates.md
website/content/en/v0.13.0/AWS/provisioning.md
website/content/en/v0.13.1/AWS/launch-templates.md
website/content/en/v0.13.1/AWS/provisioning.md
website/content/en/v0.13.2/AWS/launch-templates.md
website/content/en/v0.13.2/AWS/provisioning.md
website/content/en/v0.14.0-rc.0/AWS/launch-templates.md
website/content/en/v0.14.0-rc.0/AWS/provisioning.md
website/content/en/v0.14.0/AWS/launch-templates.md
website/content/en/v0.14.0/AWS/provisioning.md
website/content/en/v0.15.0/AWS/launch-templates.md
website/content/en/v0.15.0/AWS/provisioning.md
website/content/en/v0.16.0/AWS/launch-templates.md
website/content/en/v0.16.0/AWS/provisioning.md
website/content/en/v0.16.1/AWS/launch-templates.md
website/content/en/v0.16.1/AWS/provisioning.md
website/content/en/v0.5.0/AWS/provisioning.md

Fixes # 
Ran `make website` and ensured the changes were correct.
```release-note
```

docs: Update Website Launch Template Guidelines

---

test/suites/common/upgrade-crds.yaml

Fixes # 
*
```release-note
```

test: Add missing image field to Upgrade CRD Tekton Task

---

test/pkg/environment/expectations.go
test/suites/consolidation/suite_test.go
test/suites/utilization/suite_test.go

Fixes # 
- Watches pods and nodes during tests for better debugging
```release-note
None
```

test: Watch pods and nodes during tests

---

test/suites/common/suite.yaml
test/suites/upgrade/pipeline.yaml

Fixes # 
- Adds success messages for succeeded runs of Tekton
*
```release-note
None
```

test: Tekton Notify to Slack on Success

---

website/content/en/preview/AWS/provisioning.md
website/content/en/v0.16.1/AWS/provisioning.md
website/content/en/v0.16.2/AWS/provisioning.md

Fixes #2454
* This is a documentation-only change
```release-note
NONE
```

docs: AWS/provisioning doc - updated blockDeviceMappings

---

pkg/cloudprovider/aws/zz_generated.pricing.go

Fixes # 
Fake test to trigger api-code-gen
*
```release-note
```

Fake change to cause an update while testing the api-code-gen

---

.github/workflows/api-code-gen.yml

Fixes # 
Change the frequency to every week on Monday beginning of a working week.
*
```release-note
```

Change schedule to 6AM PT 13 UTC on every Monday

---

hack/github/community-contributors.sh

Fixes # 
Added github-actions bot to filter list.
*
```release-note
```

chore: Added github-actions bot to filter list

---

examples/workloads/spread-zone.yaml

Fixes # 
*
```release-note
```

example: update the maxSkew to one in the example

---

hack/release.sh

Fixes # 
Missing $ here will cause confusion on snapshot/stable release
*
```release-note
```

fix: add missing $

---

pkg/apis/provisioning/v1alpha5/provisioner_validation.go
pkg/apis/provisioning/v1alpha5/suite_test.go
website/content/en/preview/provisioner.md

Fixes # 
- Adds `evictionSoft` docs
- Adds additional validation of `evictionSoft`/`evictionSoftGracePeriod` pairs
* Manual view of docs
```release-note
None
```

docs: Write soft eviction threshold docs

---

hack/release.sh

Fixes # 
This should handle all different cases.
* make snapshot
```release-note
```

fix: check if SNAPSHOT_TAG exists for cases that it does not

---

website/content/en/v0.6.3/concepts/_index.md

docs: Update _index.md

---

pkg/cloudprovider/aws/amifamily/bottlerocket.go
pkg/cloudprovider/aws/amifamily/resolver.go
pkg/cloudprovider/aws/launchtemplate.go
pkg/cloudprovider/aws/launchtemplate_test.go
pkg/utils/ptr/ptr.go
test/suites/integration/block_device_mappings_test.go
test/suites/integration/tags_test.go

Fixes #2593
* Unit test
* e2e test
```release-note
```

fix: Correctly convert EBS Volume size from Gb to Gib

---

website/content/en/v0.17.0/getting-started/getting-started-with-terraform/_index.md

Fixes #2613  
Fixes #2617  
Docs were missing for terraform. 
* `terraform init`
```release-note
terraform docs enhancement for v0.17.0
```

docs: terraform docs change 

---

pkg/controllers/termination/suite_test.go

Fixes # 
- Fixes test panic in new race test for `termination_controller`
* Tested that test fails with data race without `mutex`
```release-note
None
```

test: Fix termination test panic

---

.github/pull-request-template.md

Fixes # 
update PR template to include adding upgrade notes
*
```release-note
```

chore: update PR template to include adding upgrade notes

---

website/content/en/preview/troubleshooting.md
website/content/en/preview/upgrade-guide/_index.md
website/content/en/v0.17.0/upgrade-guide/_index.md
website/content/en/v0.18.0/upgrade-guide/_index.md

Fixes # 
https://github.com/aws/karpenter/issues/2658
- Update helm OCI troubleshooting and upgrade guide. 
```release-note
```

docs: update helm oci troubleshooting and upgrade guide

---

website/content/en/preview/tasks/scheduling.md
website/content/en/v0.16.0/tasks/scheduling.md
website/content/en/v0.16.1/tasks/scheduling.md
website/content/en/v0.16.2/tasks/scheduling.md
website/content/en/v0.16.3/tasks/scheduling.md
website/content/en/v0.17.0/tasks/scheduling.md
website/content/en/v0.18.0/tasks/scheduling.md

Fixes # 
- Fixes the architecture/instance-type incompatability with the `["c4.large", "c4.xlarge"]` and `arm64` architecture
* 
```release-note
None
```

docs: Fix architecture/instance-type incompatability in docs

---

go.mod
go.sum
pkg/cloudproviders/aws/cloudprovider/amifamily/ami.go
pkg/cloudproviders/aws/cloudprovider/instance.go
pkg/cloudproviders/aws/cloudprovider/instancetype.go
pkg/cloudproviders/common/cloudprovider/fake/cloudprovider.go
pkg/cloudproviders/common/cloudprovider/fake/instancetype.go
pkg/cloudproviders/common/cloudprovider/types.go
pkg/controllers/consolidation/helpers.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/node.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topologygroup.go
pkg/controllers/provisioning/scheduling/topologynodefilter.go
pkg/controllers/state/cluster.go
pkg/controllers/state/zz_generated.deepcopy.go
pkg/controllers/termination/terminate.go
test/go.mod
test/go.sum
test/suites/integration/kubelet_config_test.go

Fixes # 
*
```release-note
```

chore: rely on karpenter-core scheduling libraries

---

pkg/cloudproviders/aws/cache/unavailableofferings.go
pkg/cloudproviders/aws/cloudprovider/cloudprovider.go
pkg/cloudproviders/aws/cloudprovider/instance.go
pkg/cloudproviders/aws/cloudprovider/instancetypes.go
pkg/cloudproviders/aws/cloudprovider/instancetypes_test.go
pkg/cloudproviders/aws/cloudprovider/launchtemplate.go
pkg/cloudproviders/aws/cloudprovider/suite_test.go
pkg/cloudproviders/aws/errors/errors.go

Fixes # 
- Moves components that will be shared when we add `cloudproviders/aws/controllers`
* `make test`
```release-note
None
```

chore: Move components that will be shared into top-level of `cloudproviders/aws`

---

test/suites/ipv6/pipeline.yaml

Fixes # 
*
```release-note
```

chore: add slack notification for ipv6 e2e tests

---

.gitignore
go.mod
go.sum
pkg/cloudproviders/aws/cloudprovider/amifamily/ami.go
pkg/cloudproviders/aws/cloudprovider/instance.go
pkg/cloudproviders/aws/cloudprovider/instancetype.go
pkg/cloudproviders/common/cloudprovider/fake/cloudprovider.go
pkg/cloudproviders/common/cloudprovider/fake/instancetype.go
pkg/cloudproviders/common/cloudprovider/types.go
pkg/controllers/consolidation/helpers.go
pkg/controllers/provisioning/provisioner.go
pkg/controllers/provisioning/scheduling/existingnode.go
pkg/controllers/provisioning/scheduling/node.go
pkg/controllers/provisioning/scheduling/scheduler.go
pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
pkg/controllers/provisioning/scheduling/topology.go
pkg/controllers/provisioning/scheduling/topologygroup.go
pkg/controllers/provisioning/scheduling/topologynodefilter.go
pkg/controllers/state/cluster.go
pkg/controllers/state/zz_generated.deepcopy.go
pkg/controllers/termination/terminate.go
test/go.mod
test/go.sum
test/suites/integration/kubelet_config_test.go

Fixes # 
* `make test`
* Manual push and build
```
karpenter     karpenter-64ffb68d4f-dqvks   2/2     Running   0          22m
karpenter     karpenter-64ffb68d4f-j8z6f   2/2     Running   0          22m
```
```release-note
```

chore: Migrate scheduling libraries to karpenter-core

---

cmd/controller/main.go
pkg/cloudproviders/aws/events/recorder.go
pkg/cloudproviders/common/cloudprovider/types.go
pkg/controllers/controllers.go
pkg/operator/options.go

Fixes # 
* Exposes an AWS event-recorder through `pkg/cloudproviders/aws/events`
* Injects `record.EventRecorder` into `cloudprovider.Options`
* `make test`
```release-note
None
```

chore: Expose an AWS event recorder

---

website/assets/js/versionWarning/index.js

Fixes # 
*
```release-note
```

chore: add more validation to old version check

---

pkg/apis/awsnodetemplate/v1alpha1/suite_test.go
pkg/controllers/consolidation/suite_test.go
pkg/controllers/provisioning/scheduling/suite_test.go
pkg/controllers/state/suite_test.go
pkg/test/deployment.go
pkg/test/storage.go

Fixes # 
This is all that's left
*
```release-note
```

chore: break dependency on aws-sdk-go for neutral libraries

---

pkg/cloudproviders/aws/controllers/interruption/events/events.go
pkg/cloudproviders/aws/events/events.go

Fixes # 
- Adds the `events.Event` interface for AWS cloudprovider events
- Adds the `events.EventTemplate` interface that can be used to create EventTemplates for events that are often fired
- Adds individual event types that will be used by `InterruptionController`
```go
n := &v1.Node{}
c.recorder.Publish(InstanceSpotInterrupted.For(n))
```
```release-note
None
```

chore: Extend AWS event recorder to specific event types

---

pkg/cloudprovider/aws/fake/ec2api.go
pkg/cloudprovider/aws/pricing.go
pkg/cloudprovider/aws/pricing_test.go

Fixes # 
Merging into v0.18.x
*
```release-note
```

fix: query for both forms of Linux/Unix OS on spot (#2678)

---

.golangci.yaml
hack/toolchain.sh

Update and turn on a few more linters.
*
```release-note
```

chore: update golangci-lint

---

pkg/cloudproviders/aws/cloudprovider/cloudprovider.go
pkg/cloudproviders/aws/cloudprovider/suite_test.go
pkg/operator/context.go
pkg/operator/manager.go
pkg/operator/scheme/scheme.go
pkg/test/environment.go

Fixes # 
*
```release-note
```

chore: decouple scheme

---

cmd/webhook/main.go
go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
*
```release-note
```

chore: migrate webhook

---

website/content/en/preview/provisioner.md
website/content/en/v0.18.1/provisioner.md

Fixes # 
* Docs only change, I used the provisioner requirements locally.
```release-note
```

docs: improve diversity on example provisioner

---

.github/workflows/api-code-gen.yml
.github/workflows/doc-gen.yml
hack/api-code-gen.sh

Fixes # 
*
```release-note
```

Test: Add api-code-gen to the doc-gen-ci test action

---

go.mod
go.sum
pkg/cloudprovider/instancetypes_test.go
pkg/cloudprovider/launchtemplate_test.go
pkg/cloudprovider/securitygroups_test.go
pkg/cloudprovider/subnets_test.go
pkg/cloudprovider/suite_test.go
test/go.mod
test/go.sum

Fixes # 
Corresponds to changes: 
- https://github.com/aws/karpenter-core/pull/23
- https://github.com/aws/karpenter-core/pull/33
- https://github.com/aws/karpenter-core/pull/32
* Bumps `karpenter-core` version to HEAD
```release-note
None
```

chore: Bump karpenter-core version to latest HEAD

---

hack/docs/instancetypes_gen_docs.go

Fixes # 
*
```release-note
None
```

fix: Fix docgen with RESTConfig

---

hack/toolchain.sh

…id key
Fixes # 
Snapshots (and other builds) that rely on are getting this error since this morning:
```
getting signer: getting key from Fulcio: verifying SCT: updating local metadata and targets: error updating to TUF remote mirror: tuf: invalid key
remote status:{
```
This upgrade should fix it.
* On a fork
```release-note
```

fix: upgrade cosign to v1.13.1

---

test/suites/common/run-test.yaml

Fixes # 
*
```release-note
```

test: Fix test filter change to focus

---

Makefile
hack/docs/metrics_gen_docs.go
website/content/en/preview/AWS/instance-types.md
website/content/en/preview/tasks/configuration.md

Fixes # 
- Fixes the `make docgen` script so that it works for multiple packages
```release-note
None
```

fix: Multiple package metrics generation

---

test/suites/upgrade/pipeline.yaml

Fixes # 
*
```release-note
None
```

fix: Fix upgrade pipeline for Integration tests

---

.github/workflows/codeql-analysis.yml
.github/workflows/doc-gen.yml

Fixes # 
* Adds make vulncheck to the periodic security scanner
```release-note
```

add make vulncheck as well, and upgrade the CodeQL lib

---

.github/actions/download-artifact/action.yml
.github/actions/upload-artifact/action.yml
.github/workflows/approval-comment-snapshot.yml
.github/workflows/approval-comment.yml
.github/workflows/release-tag.yml
.github/workflows/stable-release.yml

Fixes # 
* Adds ability to create snapshots on open PRs
* The process is triggered when a maintainer approves a PR with a message starting with `/karpenter snapshot`
```release-note
```

feat: Snapshots on PRs

---

test/suites/common/setup.yaml
test/suites/common/suite.yaml
test/suites/ipv6/pipeline.yaml
test/suites/upgrade/pipeline.yaml
website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step02-create-cluster-fargate.sh
website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step02-create-cluster.sh

Fixes # 
- Use K8s 1.23 in the Getting Started Guide
- 
* Testing Getting Started Guide on K8s 1.23
```release-note
```

docs: update getting started guide to use K8s 1.23

---

test/tools/Dockerfile

Fixes # 
- Bump eksctl to version `v0.116.0`
*
```release-note
None
```

test: Bump eksctl version in tools dockerfile

---

test/tools/Dockerfile

Fixes # 
* built on arm64 instance
```release-note
```

chore: arm compatible test tools

---

charts/karpenter/templates/webhooks-core.yaml
charts/karpenter/templates/webhooks.yaml

Fixes #2464 
remove namespace from webhook configuration
*
```release-note
```

remove namespace from webhook configuration

---

Makefile
hack/docs/instancetypes_gen_docs.go
test/suites/common/setup.yaml

Fixes # 
- Fixes failures in Docgen due to new settings migration
- Fixes setup Tests for E2E
```release-note
None
```

fix: Fix docgen and setup test for E2E

---

pkg/controllers/nodetemplate/controller.go

Fixes # 
*
```release-note
```

chore: use client.IgnoreNotFound

---

pkg/controllers/nodetemplate/infrastructure.go
test/suites/integration/cni_test.go

Fixes # 
- CNI E2E Tests rely on an update to the settings
* `FOCUS=CNITests make e2etests`
```release-note
None
```

test: Fix CNI E2E tests

---

test/suites/common/setup.yaml
test/suites/upgrade/pipeline.yaml
test/suites/upgrade/pre-upgrade-setup.yaml

Fixes # 
- Have a pre-upgrade script that has setup for the older version of Karpenter
* Deploying these updates directly to test cluster and running tests
```release-note
None
```

test: Have a pre-upgrade setup for older version of Karpenter

---

go.mod
go.sum
pkg/apis/config/settings/settings.go
pkg/apis/config/settings/suite_test.go
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/instance.go
pkg/cloudprovider/instancetype.go
pkg/cloudprovider/instancetypes.go
pkg/cloudprovider/instancetypes_test.go
pkg/cloudprovider/launchtemplate.go
pkg/cloudprovider/launchtemplate_test.go
pkg/cloudprovider/securitygroups.go
pkg/cloudprovider/securitygroups_test.go
pkg/cloudprovider/subnets.go
pkg/cloudprovider/subnets_test.go
pkg/cloudprovider/suite_test.go
test/go.mod
test/go.sum
test/pkg/environment/common/environment.go

Fixes # 
- Buddy change for https://github.com/aws/karpenter-core/pull/56\
- Waits for CM creation of configuration before continuing to start the controllers
```release-note
None
```

chore: Wait for configMaps to be created

---

charts/karpenter/templates/deployment.yaml

Fixes # 
- Numerical values should be quoted in the helm chart
* `make apply`
```release-note
None
```

fix: Fix quoting a number in helm chart

---

Makefile
test/go.mod
test/go.sum
test/suites/common/setup.yaml

Fixes # 
- Remove event policy role in E2E
*
```release-note
None
```

test: Remove event policy role in E2E

---

website/content/en/preview/getting-started/getting-started-with-terraform/_index.md
website/content/en/v0.19.0/getting-started/getting-started-with-terraform/_index.md

Fixes # 
*
```release-note
```

docs: wrong value - missing settings.

---

charts/karpenter/Chart.yaml
charts/karpenter/README.md
charts/karpenter/README.md.gotmpl
charts/karpenter/values.yaml

Fixes # 
*
```release-note
```

fix: `interruptionQueueName` propogated into the helm values

---

website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step08-apply-helm-chart.sh
website/content/en/v0.19.0/getting-started/getting-started-with-eksctl/scripts/step08-apply-helm-chart.sh

Fixes # 
*
```release-note
```

Parameters needs to be passed like settings.aws.

---

Makefile
hack/release/stable-pr.sh

Fixes # 
* Adds helm-docs to docgen so that it's run on each release and tested by [doc-gen](https://github.com/aws/karpenter/blob/main/.github/workflows/doc-gen.yml)
* Adds charts directory changes in the stable release PR
* Different fork
```release-note
```

fix: add helm-docs to docgen and include chart changes in the stable release PR

---

pkg/cloudprovider/pricing.go

Fixes # 
https://github.com/aws/karpenter/issues/2846
- Remove pricing endpoint in china since one doesn't exist. 
- See issue
```release-note
```

remove pricing endpoint for china since it doesn't exist

---

pkg/context/context.go
pkg/controllers/controllers.go
pkg/utils/project/project.go
test/pkg/environment/common/environment.go

Fixes # 
*  Moves project.Version back to this project from https://github.com/aws/karpenter-core/blob/main/pkg/utils/project/project.go
* Re-adds the line the logs app version similar to https://github.com/aws/karpenter/blob/5884672830187392e47081447680526e123412d8/pkg/controllers/controllers.go#L101
* Tested deployment locally
```release-note
```

fix: re-add application version injection

---

pkg/cloudprovider/instance.go

Fixes # 
https://github.com/aws/karpenter/issues/2872
* Changed subnet setting to use resource based hostnames:
Karpenter Logs
```
karpenter-786d45ff78-n6gr2 controller 2022-11-17T02:42:02.914Z	INFO	controller.provisioning	Found 1 provisionable pod(s)	{"commit": "455190a"}
karpenter-786d45ff78-n6gr2 controller 2022-11-17T02:42:02.914Z	INFO	controller.provisioning	Computed 1 new node(s) will fit 1 pod(s)	{"commit": "455190a"}
karpenter-786d45ff78-n6gr2 controller 2022-11-17T02:42:02.914Z	INFO	controller.provisioning	Launching node with 1 pods requesting {"cpu":"1125m","memory":"256M","pods":"3"} from types c5.xlarge, m5.xlarge, r5.xlarge, c5.2xlarge, m5.2xlarge and 19 other(s)	{"commit": "455190a", "provisioner": "default"} …
```

fix: resource based naming of nodes

---

website/content/en/preview/getting-started/migrating-from-cas/scripts/step09-generate-chart.sh
website/content/en/preview/getting-started/migrating-from-cas/scripts/step10-deploy.sh
website/content/en/preview/getting-started/migrating-from-cas/scripts/step11-create-provisioner.sh

Fixes # 
https://github.com/aws/karpenter/issues/2877
- update cas migration guide 
*
```release-note
```

docs: update cas migration

---

Makefile

Fixes # 
Makefile had a small issue for running `make ci` command 
Running the tests
*
```release-note
```

chore: remove unused make target

---

website/content/en/preview/troubleshooting.md

Fixes # 
N/A
- Fixes blockDeviceMappings kms key policy troubleshooting section.
*
```release-note
```

docs: fix kms troublshooting entry

---

test/pkg/environment/common/setup.go

Fixes # 
- Fixes a bug where the list call was not actually waiting, since the object that was being checked was always empty
* `FOCUS="KubeletConfiguration" make e2etests`
```release-note
None
```

test: Fix waiting for objects to be deleted

---

test/suites/upgrade/pre-upgrade-setup.yaml

Fixes # 
*
```release-note
```

chore: update pre-upgrade-setup to remove enableInterruption

---

website/content/en/preview/tasks/metrics.md
website/content/en/v0.19.2/tasks/metrics.md

Fixes # 
*
```release-note
```

docs: fix metrics globalsettings link

---

hack/github/community-contributors.sh

Fixes # 
*
```release-note
```

chore: Updated community contributor filter list

---

hack/docs/metrics_gen_docs.go

Fixes # 
- Fixes metrics docgen global setttings link
```release-note
None
```

chore: Fix metrics docgen global setttings link

---

pkg/cloudprovider/instance.go
pkg/cloudprovider/instancetypes_test.go
website/content/en/preview/AWS/instance-types.md
website/content/en/preview/upgrade-guide/_index.md

Fixes # 
BREAKING CHANGE: Customers who do not have specific instance categories specified in their Provisioner would now observe exotic instance types.
- InstanceTypes shouldn't know their underlying type and should prioritize based off of label requirements
```release-note
None
```

fix: Add labels and prioritize based on requirements

---

website/content/en/preview/faq.md
website/content/en/v0.19.0/faq.md
website/content/en/v0.19.1/faq.md
website/content/en/v0.19.2/faq.md

Fixes # 
- Updates docs with some common Native interruption handling questions
* Viewing the docs
```release-note
None
```

docs: Add interruption handling FAQ to the docs

---

pkg/controllers/interruption/controller.go

Fixes # 
- Logs that it is starting interruption handling and watching a given queue name
* `make apply`
```release-note
```

fix: Queue discovery logging when starting interruption handling

---

go.mod
go.sum
pkg/cloudprovider/instancetypes_test.go
pkg/cloudprovider/launchtemplate_test.go
pkg/cloudprovider/pricing.go
pkg/cloudprovider/securitygroups_test.go
pkg/cloudprovider/subnets_test.go
pkg/cloudprovider/suite_test.go
pkg/controllers/interruption/controller.go
pkg/controllers/interruption/interruption_benchmark_test.go
pkg/controllers/interruption/suite_test.go
test/go.mod
test/go.sum

Fixes # 
- Updates to support the Karpenter typed controller framework in Karpenter
Buddy change for karpenter-core: https://github.com/aws/karpenter-core/pull/51
```release-note
None
```

chore: Adapt karpenter controllers to generic controllers

---

test/suites/integration/ami_test.go

Fixes # 
- Adds AMIFamily testing to E2E to ensure we properly test that all families that we support (AL2, Bottlerocket, and Ubuntu) all work with a barebones configuration
* `FOCUS="AMIFamily" make e2etests`
```release-note
None
```

test: Add AMIFamily testing to E2E

---

Makefile
go.mod
go.sum
pkg/apis/crds/karpenter.sh_provisioners.yaml
test/go.mod
test/go.sum
test/suites/integration/aws_metadata_test.go
test/suites/integration/scheduling_test.go
website/content/en/preview/tasks/deprovisioning.md
website/content/en/preview/tasks/provisioning.md

Fixes # 
Buddy PR: https://github.com/aws/karpenter-core/pull/87
```release-note
```

feat: allow node annotations to be set by the provisioner

---

Makefile
website/content/en/preview/tasks/metrics.md

Fixes # 
*
```release-note
```

docs: fixed docgen

---

pkg/cloudprovider/amifamily/ami.go

Fixes # 
*
```release-note
```

fix: remove name filter

---

go.mod
go.sum
pkg/cloudprovider/createfleetbatcher_test.go
pkg/cloudprovider/instancetypes_test.go
pkg/cloudprovider/launchtemplate_test.go
pkg/cloudprovider/securitygroups_test.go
pkg/cloudprovider/subnets_test.go
pkg/cloudprovider/suite_test.go
pkg/fake/ec2api.go
test/go.mod
test/go.sum

Fixes # 
- Updates to use dynamic cluster state for testing
Buddy change to: https://github.com/aws/karpenter-core/pull/100
```release-note
None
```

chore: Update tests to work with dynamic cluster state

---

test/suites/integration/extended_resources_test.go

Skip the test that uses an exotic type.
*
```release-note
```

chore: skip habana e2e test

---

website/content/en/preview/concepts/_index.md
website/content/en/preview/tasks/deprovisioning.md
website/content/en/v0.19.3/concepts/_index.md
website/content/en/v0.19.3/tasks/deprovisioning.md

Signed-off-by: Marius Voila <marius@eclecticiq.com>
Fixes # 
*
```release-note
```

docs: fix Reblanace with the correct term

---

Makefile

Fixes # 
KO_DOCKER_REPO that was being used was set from the environment variable not from the makefile
By Running the command
*
```release-note
```

fix: Fix make build

---

website/content/en/preview/concepts/node-templates.md
website/content/en/v0.16.3/AWS/provisioning.md
website/content/en/v0.18.1/AWS/provisioning.md
website/content/en/v0.19.3/AWS/provisioning.md

Fixes # 
Update out of date link for the set of the AWS Neuron extended resource.
Old Link: https://github.com/aws/aws-neuron-sdk/blob/master/neuron-deploy/tutorials/tutorial-k8s.rst
New Link: https://github.com/aws-neuron/aws-neuron-sdk/tree/master/src/k8
Manually tested locally
*
```release-note
```

Doc changes to fix out of date link

---

website/content/en/preview/concepts/deprovisioning.md

Fixes #2938
*
```release-note
```

docs: report events about why nodes won't be consolidated

---

.github/workflows/snapshots.yml
.github/workflows/stable-release.yml
charts/karpenter-crd/.helmignore
charts/karpenter-crd/Chart.yaml
charts/karpenter-crd/templates/karpenter.k8s.aws_awsnodetemplates.yaml
hack/release/common.sh
hack/release/release.sh

Fixes # 
Add CRD chart that publishes to GHCR
*
```release-note
```

feat: add CRD chart to be later used as a dependency

---

website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step08-apply-helm-chart.sh

Fixes # 
* Helps prevent `Error: failed to download "oci://public.ecr.aws/karpenter/karpenter" at version "v0.19.2"` error that is commonly seen e.g. in https://github.com/aws/karpenter/issues/2933
* make website
```release-note
```

doc: add docker logout before helm upgrade, to avoid authentication problems

---

hack/release/release.sh

Fixes # 
*
```release-note
```

disable CRD GHCR helm publishing until the auth problem is resolved

---

go.mod
go.sum
pkg/cloudprovider/cloudprovider.go
test/go.mod
test/go.sum

Fixes # 
This is to add in the IsMachineDrifted Function into the cloud provider interface that was added here https://github.com/aws/karpenter-core/pull/124 and to add in a bug fix here https://github.com/aws/karpenter-core/pull/128
* make presubmit
```release-note
```

chore: upgraded karpenter-core to include IsMachineDrifted() and bug fix

---

website/content/en/v0.20.0/faq.md

Fixes # 
* Not tested
```release-note
Fix typo
```

docs: fix typo in faq.md

---

test/suites/integration/extended_resources_test.go

Fixes # 
*
```release-note
```

test: increase timeout to reduce test failures

---

test/suites/upgrade/pipeline.yaml

Fixes # 
*
```release-note
```

fix: bump upgrade test version to v0.19.3

---

website/content/en/preview/faq.md

Fixes # 
Document possible interactions between kube-scheduler and Karpenter when using preferred topology spreads.
*
```release-note
```

docs: document kube-scheduler/Karpenter interaction

---

website/content/en/preview/concepts/deprovisioning.md
website/content/en/preview/concepts/globalsettings.md

Fixes # 
Adds docs on how to enable drift detection for drift automatic deprovisioning.
* make website
```release-note
```

docs: added docs for drift

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
Partner PR: https://github.com/aws/karpenter-core/pull/130
*
```release-note
```

fix: Retrigger provisioning until all pods are scheduled

---

pkg/cloudprovider/suite_test.go

Fixes # 
- https://github.com/aws/karpenter/actions/runs/3708362090/jobs/6285843927
- https://github.com/aws/karpenter/actions/runs/3708151674/jobs/6285394006
* make presubmit x 10
```release-note
```

fix: deflake ami drift tests

---

test/suites/common/run-test.yaml
test/suites/common/setup.yaml
test/suites/upgrade/pre-upgrade-setup.yaml

Fixes # 
* Clone into current dir 
```release-note
```

fix: clone into current directory and

---

hack/release/common.sh

Fixes # 
*
```release-note
```

remove unused var

---

website/content/en/preview/troubleshooting.md

Fixes # 
*
```release-note
```

doc: add note about not needing to add helm repo

---

README.md

Fixes # 
Fix for https://github.com/badges/shields/issues/8671
*
```release-note
```

fix: fix broken badge

---

website/content/en/preview/concepts/provisioning.md

Fixes # 
Relates to #3000
*
```release-note
```

docs: Document provisioner defaults

---

test/suites/upgrade/pre-upgrade-setup.yaml

Fixes # 
The old version in this test is also now compliant with [this change](https://karpenter.sh/preview/upgrade-guide/#upgrading-to-v0190)
*
```release-note
```

fix: fix failing upgrade test, the old test now also has these settings

---

test/pkg/environment/common/expectations.go
test/suites/drift/suite_test.go

Fixes # 
- Fixes issue with test for the disabled feature gate
* `FOCUS=Drift make e2etests`
```release-note
None
```

test: Fix drift integration test

---

test/suites/common/run-test.yaml

Fixes # 
* Show commit SHA and git tags after checkout for easier troubleshooting
* Use none for tags when they don't exist for better string matching
*
```release-note
```

tests: Log git SHA and git tags in tests

---

.github/workflows/approval-comment-snapshot.yml
.github/workflows/approval-comment.yml

Fixes # 
* Adds a message to a PR that has a `/karpenter snapshot` approval message to notify a successful release of the snapshot.
* Add crd helm chart upon PR snapshot release
```release-note
```

feat: Add PR message upon successful snapshot release on PR

---

test/pkg/environment/common/expectations.go

Fixes # 
*
```release-note
```

test: Fix unneccesary offset argument

---

Makefile

Fixes # 
Fixes bad character/typo in `make e2etests` target
```release-note
None
```

test: Fix e2tests execution

---

.github/workflows/deflake.yml

Fixes # 
- Add a commit status update when the deflake cron is run
* Tested on local fork
```release-note
None
```

chore: Add a commit status message for deflake

---

.github/workflows/release.yml

Fixes # 
*
```release-note
```

Fix: add condition for safety

---

test/go.mod
test/go.sum

Fixes # 
*
```release-note
```

make ci-non-test

---

website/content/en/preview/troubleshooting.md

Fixes # 
*
```release-note
```

docs: update faq with some node health content

---

ADOPTERS.md

Fixes # 
*
```release-note
```

chore: change working group link in adopters to docs site

---

go.mod
go.sum
test/go.mod
test/go.sum
website/content/en/preview/upgrade-guide.md

Fixes #2354
Pulling in https://github.com/aws/karpenter-core/pull/150
*
```release-note
```

feat: support k8s-1.25, remove support for k8s-1.20

---

test/suites/common/cleanup.yaml
test/suites/common/setup.yaml
test/suites/upgrade/pre-upgrade-setup.yaml

Fixes # 
*
```release-note
```

fix: remove stutter, shorter name to allow longer overall name

---

test/cmd/cleanup/cleanup.sh
test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml

Fixes # 
*
```release-note
```

test: add periodic to periodic suite names

---

test/cmd/release-notification-listener/listener/tekton.go

Fixes # 
*
```release-note
```

test: fix ipv6 test by adding extra param

---

website/content/en/preview/concepts/node-templates.md
website/content/en/preview/faq.md
website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
website/content/en/preview/getting-started/getting-started-with-terraform/_index.md

Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>
Fixes # 
fixing typos in docs 
```release-note
```

docs: fix MD typos

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
Adds in https://github.com/aws/karpenter-core/pull/160, https://github.com/aws/karpenter-core/pull/159 and https://github.com/aws/karpenter-core/pull/158
* make presubmit
```release-note
```

chore: upgrade core for fixes

---

website/content/en/v0.22.0/concepts/_index.md

Fixes # 
Adds changes that were made to v0.21.1 and preview into v0.22.0 that were committed in https://github.com/aws/karpenter/pull/3151
*
```release-note
```

docs: update index to match previous PR

---

charts/karpenter/templates/configmap-logging.yaml

Fixes # 
*
```release-note
```

fix: An issue with the default logging config

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
*
```release-note
```

chore: upgrade karpenter-core to fix test failures

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
- Bump `karpenter-core` to v0.22.1
```release-note
None
```

chore: Bump karpenter-core to v0.22.1

---

test/cmd/release-notification-listener/listener/message.go
test/cmd/release-notification-listener/listener/tekton.go
test/cmd/release-notification-listener/listener/tekton_test.go

Fixes # 
* Runs upgrade tests in addition to other tests on notifications
* Adds a delay between each read to help not overwhelm the cluster
*
```release-note
```

test: add upgrade tests 

---

test/cmd/cleanup/cleanup.sh

Fixes # 
*
```release-note
```

chore: update cleanup script to remove old launch templates

---

test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml

… commit
Fixes # 
Changes the frequency of tests running periodically
*
```release-note
```

test: reduce frequency of periodics now that we have tests running on every commit

---

website/content/en/preview/troubleshooting.md
website/content/en/v0.19.3/troubleshooting.md
website/content/en/v0.20.0/troubleshooting.md
website/content/en/v0.21.0/troubleshooting.md
website/content/en/v0.21.1/troubleshooting.md
website/content/en/v0.22.0/troubleshooting.md
website/content/en/v0.22.1/troubleshooting.md

Fixes # 
*
```release-note
```

docs: add troubleshooting for argocd problem

---

test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml
website/content/en/preview/upgrade-guide.md

Fixes # 
* Removes to be implemented as this is done now
* Adds a missing export to fix the periodics
```release-note
```

test: add missing export command

---

website/content/en/v0.22.1/troubleshooting.md

Fixes # 
*
```release-note
```

docs: remove a troubleshooting step missed in the last PR

---

test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml

Fixes # 
Use the tools image here
*
```release-note
```

test: use tools image for periodics

---

hack/release/common.sh

Fixes # 
Adds two details on the notification message
* Github account of the originating message, so that we can react to forks and treat them differently than the main repo
* Latest tag from the branch of the commit, will facilitate this [TODO item](https://github.com/aws/karpenter/blob/main/test/cmd/release-notification-listener/listener/tekton.go#L114): 
* On fork
```release-note
```

chore: Add git tag and git account

---

website/content/en/v0.22.1/getting-started/getting-started-with-terraform/_index.md

EvnetBridge to EventBridge.
Fixes # 
*
```release-note
```

docs: correct spelling of EventBridge.

---

website/content/en/preview/getting-started/migrating-from-cas/scripts/step07-tag-security-groups.sh

Fixes #3250  
* SG IDs returned by the scrip doesn't result in error anymore
```release-note
Docs CA migration script query outputs correct SG ID value and doesn't return an error
```

docs: Update CA migration guide

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
*
```release-note
```

chore: update karpenter-core dep

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
*
```release-note
```

chore: update karpenter-core

---

.github/dependabot.yml

Fixes # 
* Dependabat should open a PR when there's a new karpenter-core 
*
```release-note
```

chore: Update karpenter-core when there's an update with Dependabot

---

.github/dependabot.yml

Fixes # 
* Try to make directory names unique
*
```release-note
```

fix: make directories unique for dependabot

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
- Bump `karpenter-core` for machine cluster state change
```release-note
```

chore: Bump `karpenter-core` for machine cluster state change

---

pkg/apis/crds/karpenter.sh_provisioners.yaml

Fixes # 
*
```release-note
```

chore: add gencode

---

cmd/controller/main.go
go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
- Bump `karpenter-core` to latest
```release-note
None
```

chore: Bump `karpenter-core` to latest

---

pkg/cloudprovider/amifamily/bootstrap/bottlerocket.go
pkg/cloudprovider/amifamily/bootstrap/bottlerocketsettings.go
pkg/cloudprovider/amifamily/bootstrap/eksbootstrap.go
pkg/cloudprovider/launchtemplate_test.go
test/suites/integration/kubelet_config_test.go

Add a new feature to support https://github.com/aws/karpenter/issues/3110
Add support for ImageGCHighThresholdPercent and ImageGCLowThresholdPercent.
Tested using unit tests and integration test

feat: support for ImageGCHighThresholdPercent and ImageGCLowThresholdPercent

---

test/pkg/environment/aws/setup.go
test/pkg/environment/common/environment.go
test/pkg/environment/common/expectations.go

Fixes # 
- Fix missing settings injection in E2E
- Restart Karpenter pods on changed settings
* `FOCUS=Integration make e2etests`
```release-note
```

test: Fix missing settings injection in E2E

---

.github/workflows/karpenter-comment.yaml

Fixes # 
*
```release-note
```

test: try checking for maintainer check on PR comments

---

.github/workflows/karpenter-comment.yaml

Fixes # 
*
```release-note
```

fix: user karpenter instead of aws/karpenter for team name

---

test/pkg/environment/aws/setup.go
test/pkg/environment/common/expectations.go

Fixes # 
- Add a fixed delay after a settings update
```release-note
```

test: Add a fixed delay after a settings update

---

hack/github/community-contributors.sh
pkg/apis/crds/karpenter.sh_provisioners.yaml

Fixes # 
*
```release-note
```

fix: added pagination to community contribution script

---

test/suites/integration/kubelet_config_test.go
test/suites/integration/webhook_test.go

Fixes # 
- Fix imageGCThresholdPercent tests
* `FOCUS=Webhooks make e2etests`
```release-note
None
```

test: Fix imageGCThresholdPercent tests

---

pkg/cloudprovider/instancetypes.go
website/content/en/preview/upgrade-guide.md

Fixes # 
https://github.com/aws/karpenter/issues/3305
- Remove internal instance type filtering to allow any explicit instance type usage
* 
```release-note
```

fix: remove internal instance type filtering

---

.github/actions/maintainer-check/action.yml
.github/workflows/approval-comment.yml

…eing able to merge, and check for maintainers
Fixes # 
* My fork
```release-note
```

chore: check for maintainers for PR snapshot command and do not require approval

---

pkg/apis/crds/karpenter.sh_provisioners.yaml
test/suites/integration/block_device_mappings_test.go

Fixes # 
- Fix block device mappings e2e testing
* `FOCUS=BlockDeviceMappings make e2etests`
```release-note
None
```

test: Fix block device mappings e2e testing

---

pkg/batcher/terminateinstances.go

Fixes # 
*
```release-note
```

fix: only log upon error

---

charts/karpenter/templates/_helpers.tpl
charts/karpenter/templates/deployment.yaml

Fixes # 
- Fix `karpenter-global-settings` spacing causing changed checksum
* `helm diff upgrade --namespace karpenter karpenter charts/karpenter --reuse-values  --three-way-merge`
```release-note
None
```

test: Fix `karpenter-global-settings` spacing causing changed checksum

---

website/content/en/preview/concepts/provisioners.md
website/content/en/v0.20.0/concepts/provisioning.md
website/content/en/v0.21.1/concepts/provisioners.md
website/content/en/v0.22.1/concepts/provisioners.md
website/content/en/v0.23.0/concepts/provisioners.md

Fixes # 
- Adds annotations to the provisioner example in the docs
*
```release-note
```

docs: add annotations to provisioner spec docs

---

test/pkg/environment/common/monitor.go

Fixes # 
- Fix race condition in test monitor
* `FOCUS=Expiration make e2etests`
```release-note
None
```

test: Fix race condition in test monitor

---

hack/release/common.sh
hack/release/stable-pr.sh

Fixes # 
*
```release-note
```

Update go.mod to match the karpenter-core version on stable releases PR

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
*
```release-note
```

chore: update karpenter core to v0.23.1-0.20230207002141-6abab235df9c

---

ADOPTERS.md

Nexxiot successfully migrated from EKS Manage Node Groups to Karpenter in January 2023.
Fixes # 
Added Nexxiot as an adopter
*
```release-note
```

Added Nexxiot to adopters.md

---

.github/workflows/ci-test.yaml
hack/toolchain.sh
pkg/apis/crds/karpenter.k8s.aws_awsnodetemplates.yaml
test/manifests/upgrade-suite.yaml

Fixes # 
- Update toolchain dependencies
- Add K8s 1.25 to CI matrix tests
- Update tag for Upgrade e2e test checkout point
*
```release-note
```

chore: update toolchain deps

---

charts/karpenter/README.md
charts/karpenter/templates/extra-manifests.yaml
charts/karpenter/values.yaml

…sources
Added extra objects deployment to helm chart to support dynamic creation of K8s manifests via helm values files
- helm template validation 
- helm lint 
- [ x] Yes, PR includes docs updates
```release-note
None
```

feat:add-extra-manifest-objects-to-helm-chart

---

test/cmd/sync-cluster/launch-and-sync
test/cmd/sync-cluster/sync-cluster

Fixes # 
- Disable imdsv1 on test cluster sync
- remove --no-rollback from cdk execution
*
```release-note
```

chore: disable imdsv1 on test cluster sync

---

test/manifests/notify-slack.yaml

Fixes # 
- Remove newline from webhook url secret
*
```release-note
```

chore: remove newlines from webhook secret url

---

test/manifests/setup.yaml

Fixes # 
*
```release-note
```

chore: disable IMDSv1 for setup of e2e test

---

charts/karpenter/templates/webhooks-core.yaml
charts/karpenter/templates/webhooks.yaml
pkg/apis/v1alpha1/awsnodetemplate_validation.go
pkg/apis/v1alpha5/provisioner.go

Fixes #https://github.com/aws/karpenter/issues/3409 https://github.com/aws/karpenter/issues/3243
*
```release-note
```

fix: Remove deletion webhooks

---

README.md

Fixes # 
Fix README CI badge
* Local fork testing
```release-note
None
```

chore: Fix README CI badge

---

hack/docs/metrics_gen_docs.go

Fixes # 
Fix metrics docgen for machine subsystem
```release-note
None
```

chore: Fix metrics docgen for machine subsystem

---

ADOPTERS.md

Just to add OccMundial in ADOPTERS.md

docs : Added OccMundial as an adopter

---

test/cmd/release-notification-listener/Dockerfile
test/cmd/tools/Dockerfile

Fixes # 
- Update go version in docker container that builds tools 
*
```release-note
```

chore: update go version in tools

---

hack/release/common.sh

Fixes # 
- Fix image signing in `make release`
*
```release-note
None
```

chore: Fix image signing in `make release`

---

Makefile
hack/release/common.sh

Fixes # 
- Update tag override in release automation
*
```release-note
None
```

chore: Update tag override in release automation

---

Makefile
hack/code/bandwidth_gen.go
pkg/cloudprovider/instancetypes_test.go
pkg/cloudprovider/zz_generated.bandwidth.go
pkg/providers/pricing/pricing.go
pkg/providers/pricing/zz_generated.pricing.go

Fixes # 
- Fix pricing codegen to reference correct unexported field in-pkg and through the pricing provider with IsolatedVPC for generating test instance types.
- Added license comment for bandwidth gen
```release-note
```

fix: Pricing and Bandwidth CodeGen

---

ADOPTERS.md

Fixes # 
*
```release-note
```

docs: Add Dig Security to adopters list

---

test/suites/integration/extended_resources_test.go

Fixes # 
- temporarily skip amd test
*
```release-note
```

test: temporarily skip amd test

---

charts/karpenter/README.md
charts/karpenter/values.yaml
website/content/en/preview/concepts/instance-types.md
website/content/en/preview/concepts/settings.md

Fixes # 
- Update `interruptionQueueName` to stable
```release-note
None
```

Update `interruptionQueueName` to stable

---

ADOPTERS.md

Adding Docker to the list of adopters
```release-note
```

docs: Add Docker to adopters list

---

test/suites/integration/daemonset_test.go

Fixes # 
*
```release-note
```

test: fix test panic

---

test/pkg/environment/common/expectations.go

Fixes # 
*
```release-note
```

test: if the test fails, identify the names of the created nodes

---

test/pkg/environment/common/expectations.go
test/pkg/environment/common/setup.go
test/suites/consolidation/suite_test.go
test/suites/integration/daemonset_test.go

Fixes # 
*
```release-note
```

chore: add more integration test logs

---

ADOPTERS.md

Fixes # 
*
```release-note
```

docs: Add Canva to Adopters

---

ADOPTERS.md

Adds Superbexperience to the list of adopters
```release-note
```

Add Superbexperience to Adopters

---

website/content/en/preview/concepts/node-templates.md
website/content/en/v0.20.0/concepts/node-templates.md
website/content/en/v0.21.1/concepts/node-templates.md
website/content/en/v0.22.1/concepts/node-templates.md
website/content/en/v0.23.0/concepts/node-templates.md
website/content/en/v0.24.0/concepts/node-templates.md
website/content/en/v0.25.0/concepts/node-templates.md
website/content/en/v0.26.1/concepts/node-templates.md
website/content/en/v0.27.0/concepts/node-templates.md

Fixes # 
- Fix note on `kubernetes.io/cluster` tag with ALB
- This PR is being taken up as #3425 has gone stale
```release-note
None
```

chore: Fix note on `kubernetes.io/cluster` tag with ALB

---

ADOPTERS.md

Fixes # 
Add Conveyor as adopter of Karpenter
```release-note
```

Add conveyor as adopter

---

test/manifests/pre-upgrade-setup.yaml

Fixes # 
- Fix upgrade E2E by referring to the correct path `website/content/en/preview/getting-started/getting-started-with-eksctl/cloudformation.yaml` rather than the new path `website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml` in the `pre-upgrade` job
*
```release-note
```

test: Fix upgrade E2E

---

ADOPTERS.md

Fixes # 
Adding The Scale Factory to the list of adopters
* n/a
```release-note
```

docs: Add The Scale Factory to Adopters list

---

ADOPTERS.md

`@Vadim Gusev` is no longer the contact at Codefresh
Relates to https://github.com/aws/karpenter/pull/1915 
Update ADOPTERS.md contacts for Codefresh
* doc change, not applicable
```release-note
NONE
```

docs: Update ADOPTERS.md contacts for Codefresh

---

website/content/en/v0.27.0/troubleshooting.md

I was blocked with provisionning until i discover that helm also needs to be cleared
Fixes # 
*
```release-note
```

add helm logout in troubleshooting

---

.github/workflows/publish-release-notification-listener.yaml
.github/workflows/publish-test-tools.yaml
test/push-docker.sh
tools/release-notification-listener/push-docker.sh

Fixes # 
- Fix docker build on GHA for TestTools/ReleaseNotificationListener
```release-note
None
```

test: Fix docker build on GHA for TestTools/ReleaseNotificationListener

---

ADOPTERS.md

Adding Cloud Posse to `ADOPTERS.md`

docs: add Cloud Posse component to ADOPTERS.md

---

pkg/providers/amifamily/al2.go
pkg/providers/amifamily/bootstrap/bottlerocket.go
pkg/providers/amifamily/resolver.go
pkg/providers/launchtemplate/suite_test.go
pkg/providers/launchtemplate/testdata/al2_userdata_merged.golden
pkg/providers/launchtemplate/testdata/al2_userdata_unmerged.golden
pkg/providers/launchtemplate/testdata/br_userdata_merged.golden
pkg/providers/launchtemplate/testdata/br_userdata_unmerged.golden

Fixes # 
https://github.com/aws/karpenter/issues/3610
- propagate discovered kube-dns service ip to bootstrap scripts
* `make test`
```release-note
```

feat: propagate discovered kube-dns service ip to bootstrap scripts

---

website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
website/content/en/v0.24.0/getting-started/getting-started-with-eksctl/_index.md
website/content/en/v0.25.0/getting-started/getting-started-with-eksctl/_index.md
website/content/en/v0.26.1/getting-started/getting-started-with-eksctl/_index.md
website/content/en/v0.27.0/getting-started/getting-started-with-eksctl/_index.md

docs: Add missing space

---

charts/karpenter/README.md
charts/karpenter/values.yaml

docs: typo

---

website/content/en/preview/getting-started/migrating-from-cas/_index.md

Fixes # 
Pod anti affinity was recently added [here](https://github.com/aws/karpenter/pull/3559/files), filling it into the CAS migration guide. 
*
```release-note
```

docs: change cas migration guide affinity

---

ADOPTERS.md

Adding Livspace to adopters
Fixes # 
*
```release-note
```

Adding Livspace to ADOPTERS

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
- Upgrade Karpenter-core
*
```release-note
```

chore: upgrade karpenter-core

---

Makefile
hack/docs/instancetypes_gen_docs.go

Fixes # 
* `make verify`
```release-note
```

chore: Fix docgen and makefile verify

---

.github/workflows/stale.yaml

Fixes # 
Include chore in ignored stale labels
* 
```release-note
None
```

chore: Include `chore` in ignored stale labels

---

hack/code/instancetype_testdata_gen.go
hack/docs/instancetypes_gen_docs.go
pkg/apis/v1alpha1/register.go
pkg/apis/v1alpha5/suite_test.go
pkg/fake/zz_generated.describe_instance_types.go
pkg/providers/instancetype/suite_test.go
pkg/providers/instancetype/types.go
test/suites/integration/scheduling_test.go
website/content/en/preview/concepts/instance-types.md

Fixes # 
- Added new accelerator labels that support aws neuron
- Manual testing 
```release-note
```

chore: Add Accelerator labels

---

website/content/en/preview/troubleshooting.md

Fixes # 
*
```release-note
```

docs: Format variable

---

pkg/apis/v1alpha1/register.go
pkg/cloudprovider/cloudprovider.go
pkg/fake/ec2api.go
pkg/providers/amifamily/al2.go
pkg/providers/amifamily/ami.go
pkg/providers/amifamily/ami_test.go
pkg/providers/amifamily/bottlerocket.go
pkg/providers/amifamily/custom.go
pkg/providers/amifamily/resolver.go
pkg/providers/amifamily/ubuntu.go
pkg/providers/launchtemplate/suite_test.go

Fixes # 
- Separating out the fetching of AMIs and the mapping of AMI to instance types
```release-note
```

chore: Default AMI Requirements

---

ADOPTERS.md

Fixes # 
*
```release-note
```

Add Wehkamp as adopter

---

website/content/en/preview/faq.md

Fixes # 
Update FAQ since https://karpenter.sh/v0.27.1/getting-started/migrating-from-cas/ now exists
*
```release-note
```

docs: Update FAQ about existing EKS

---

website/content/en/preview/concepts/provisioners.md

Fixes # 
Include instance-generation in provisioner example since it is a default
*
```release-note
```

docs: Include instance-generation in provisioner example

---

pkg/providers/amifamily/ami.go
pkg/providers/instance/instance.go
pkg/providers/instancetype/instancetype.go
pkg/providers/launchtemplate/launchtemplate.go

Fixes # 
*
```release-note
```

chore: logging touchups

---

website/content/en/preview/troubleshooting.md

Fixes # 
Added a general troubleshooting section and documented how to enable debug logging.
Automatic md formatting was also applied which adds lines before and after code blocks and changes * bullets to - (I think they're more portable for md renderers)
* locally
```release-note
Added docs for debug logging
```

docs: Update troubleshooting to include debug logging option

---

test/suites/machine/suite_test.go

Fixes # 
-  Fix stop call in AfterSuite for machines
```release-note
None
```

test: Fix stop call in AfterSuite for machines

---

test/manifests/upgrade-suite.yaml

Fixes # 
- Upgrade CRDs before upgrading chart
```release-note
```

test: Upgrade CRDs before upgrading chart

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
*
```release-note
```

chore: Bump karpenter-core

---

website/content/en/preview/concepts/deprovisioning.md
website/content/en/v0.27.3/concepts/deprovisioning.md

Fixes # 
Doc only update adding additional detail on spot interruption behavior 
*
```release-note
Doc only update adding additional detail on spot interruption behavior 
```

docs: add detail on spot interruption behavior

---

website/content/en/preview/upgrade-guide.md

Fixes # 
Add an upgrade note for machine migration
* Viewing the preview docs
```release-note
None
```

chore: Add an upgrade note for machine migration

---

website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
website/content/en/preview/upgrade-guide.md

Fixes # 
Add details to the docs on Karpenter's dependency on tags for Machine orchestration. This change adds the note to the Getting-Started guide as well as the Upgrade Guide
* Preview deployment of the docs
```release-note
```

docs: Add a note on Karpenter's dependency on tags for IAM

---

ADOPTERS.md

Fixes # 
*
```release-note
```

Add PITS Global Data Recovery Services

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
- Cherry-picks Node Termination Summary Metric (https://github.com/aws/karpenter-core/pull/335)
- Manually Checking Metrics in Prometheus

Release v0.27.5

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
- Update aws-sdk-go to 1.267
*
```release-note
```

chore: up aws-sdk-go to v1.267

---

.github/workflows/ci-test.yaml

Fixes # 
*
```release-note
```

add k8s 1.27.x to CI testing

---

pkg/controllers/machine/garbagecollection/controller.go
pkg/controllers/machine/link/controller.go

Fixes #3741
Rename controller names to respect the codebase structure.
```release-note
```

chore: fix machine controller names

---

test/Dockerfile
tools/release-notification-listener/Dockerfile

Fixes # 
Fixes alpine Linux's package resolution in our `Dockerfile`. The `helm@testing` and `kubectl@testing` packages no longer exist and were promoted to `helm@community` and `kubectl@community`
* `docker buildx . --platform linux/amd64`
```release-note
None
```

test: Fix alpine package resolution

---

ADOPTERS.md

Fixes # 
Add AppsFlyer to adopters
*
```release-note
```

docs: add AppsFlyer to adopters

---

ADOPTERS.md

Adding Next Insurance to list of adopters
N/A
- [ X] No

added Next Insurance to adopters list

---

website/content/en/preview/getting-started/_index.md

Fixes # 
*
```release-note
```

docs: Updated EKS Karpenter workshop links in getting started page

---

website/layouts/partials/navbar-version-selector.html

Fixes # 
- Fix website version links where duplicate versions were in the link which resulted in 404's 
```release-note
```

chore: fix version links on website

---

website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh
website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh
website/content/en/v0.26/getting-started/getting-started-with-eksctl/scripts/step09-add-prometheus-grafana.sh
website/content/en/v0.27/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh

Fixes # 
N/A
- Use raw github links for grafana and prometheus values.yaml for permanent links
* 
```release-note
```

use github raw links for grafana and prometheus values

---

website/content/en/preview/concepts/deprovisioning.md

Fixes # 
- Changes to reflect the way drift operates currently and the progress on implementing fields
* NA
```release-note
```

docs: Update Drift Docs

---

go.mod
go.sum
test/go.mod
test/go.sum
website/content/en/preview/concepts/instance-types.md
website/content/en/preview/concepts/metrics.md

Fixes # 
- Release v0.27.6 
*
```release-note
```

Release v0.27.6

---

website/config.yaml
website/content/en/docs/faq.md
website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
website/content/en/docs/getting-started/getting-started-with-karpenter/grafana-values.yaml
website/content/en/docs/getting-started/migrating-from-cas/_index.md
website/content/en/docs/upgrade-guide.md
website/content/en/v0.27/faq.md
website/content/en/v0.27/getting-started/getting-started-with-karpenter/_index.md
website/content/en/v0.27/getting-started/getting-started-with-karpenter/grafana-values.yaml
website/content/en/v0.27/getting-started/migrating-from-cas/_index.md
website/content/en/v0.27/upgrade-guide.md

Fixes # 
*
```release-note
```

v0.27.6 website updates

---

.github/workflows/e2e-upgrade.yaml
.github/workflows/e2e.yaml

Fixes # 
Update region for GHA runs to be in `us-east-2`
* Manual validation
```release-note
```

test: Update region for GHA runs to be `us-east-2`

---

go.mod
go.sum
test/go.mod
test/go.sum

Fixes # 
This changes the commit reference to be v0.28.0 from v0.28.0-rc.2, but refers to the same commit, so there should be no real change. 
```release-note
```

chore: update mod for release

---

.github/workflows/e2e-upgrade.yaml
.github/workflows/e2e.yaml
test/gha/cloudformation/grafana_cloudformation.yaml

Fixes # 
Update workspace ID and Grafana Permissions for E2E tests with Grafana
* Manual Validation in Account
```release-note
```

test: Update workspace id and permissions for Managed Grafana

---

website/config.yaml
website/static/_redirects

website: fix website versions list

---

.github/workflows/e2e-matrix.yaml

Fixes # 
Validate `workflow_run` success condition to ensure the workflow only runs when the previous workflow completes successfully
* Manual Validation on fork
```release-note
```

test: Validate `workflow_run` success condition

---

.github/actions/e2e/slack/notify/action.yaml
.github/workflows/e2e-upgrade.yaml
.github/workflows/e2e.yaml

Fixes # 
Updates the naming in GHA to match the Tekton test runs
* Manual validation of script
```release-note
```

test: Update naming from test runs to match Tekton

---

.github/workflows/e2e-matrix.yaml
.github/workflows/e2e-upgrade.yaml
.github/workflows/e2e.yaml
test/gha/README.md
test/gha/cloudformation/README.md
test/gha/cloudformation/iam_cloudformation.yaml

Fixes # 
Github offers a way to reference [repository environment variables](https://docs.github.com/en/actions/learn-github-actions/variables#defining-configuration-variables-for-multiple-workflows). These can be defined in the UI and changed easily vs. being defined in code. 
This PR allows you to define a `ENABLE_E2E` value in your fork which will allow you to run the E2Es in your account through a workflow_dispatch action
* Validation on Fork
```release-note
None
```

test: Favor repository environment variables over workflow ones

---

.github/workflows/e2e-matrix.yaml

Fixes # 
When running from a `/karpenter snapshot`, resolve the `git-ref` from the artifact as opposed to using the current branch
* Testing on Fork
```release-note
```

test: Resolve the git-ref from the snapshot artifact

---

.github/workflows/sweeper.yaml
test/gha/cloudformation/iam_cloudformation.yaml
test/hack/cleanup/cleanup.sh

Fixes # 
Adds the sweeper job to the Github Actions pipeline to cleanup left-behind resources that weren't cleaned up during their workflow run
* Manual run on fork
```release-note
None
```

test: Add sweeper job to GHA

---

.github/workflows/e2e-matrix.yaml
.github/workflows/e2e-scale-trigger.yaml

Fixes # 
- Adds the scale test periodic to GHA
- Remove the `vars.ENABLE_E2E` so anyone who triggers a dispatch in their fork always has the workflow run
*
```release-note
None
```

test: Add scale test periodic to GHA

---

.github/actions/e2e/slack/notify/action.yaml
.github/workflows/e2e-matrix.yaml
.github/workflows/e2e-upgrade.yaml
.github/workflows/e2e.yaml

Fixes # 
Send back the PR number that a snapshot run is associated with
* Manual run on fork
```release-note
None
```

test: Specify PR number on a snapshot run

---

.github/workflows/sweeper.yaml

Fixes # 
Fix crontab for the sweeper task to not run every minute on the 12th hour
* 
```release-note
```

test: Fix crontab for the sweeper task

---

.github/workflows/e2e-matrix.yaml

Fixes # 
- Increase periodic frequency to match Tekton
*
```release-note
```

test: Increase periodic frequency to match Tekton

---

website/content/en/docs/getting-started/migrating-from-cas/scripts/step10-deploy.sh
website/content/en/preview/getting-started/migrating-from-cas/scripts/step10-deploy.sh
website/content/en/v0.28/getting-started/migrating-from-cas/scripts/step10-deploy.sh

Fixes #4057 
Adds in docs for applying CRDs for migrating from CAS guide
*
```release-note
```

docs: add in crd upgrade link

---

pkg/controllers/interruption/controller.go

Fixes #4028 
Changes interruption delete message to show that delete has been initiated, but hasn't actually finished.
```release-note
```

chore: make logging more clear for interruption delete

---

ADOPTERS.md

Fixes # 
Add Sentra to the adopters
*
```release-note
```

docs: add Sentra to the adopters

---

.github/actions/e2e/create-cluster/action.yaml
.github/workflows/e2e-upgrade.yaml
test/gha/cloudformation/iam_cloudformation.yaml

Fixes # 
- Adds the `cloudformation:GetTemplateSummary` permission for evaluating cluster upgrade in upgrade testing
- Adds a separate checkout step for checking out the actions from the updated git ref
*
```release-note
```

chore: Add GetTemplateSummary permission & fix upgrade

---

.github/actions/e2e/install-karpenter/action.yaml
.github/actions/e2e/install-prometheus/action.yaml
.github/actions/e2e/install-prometheus/values.yaml
test/gha/cloudformation/iam_cloudformation.yaml

Fixes # 
- Adds the `cloudformation:GetTemplate` permission to the `GithubActions` role
- Handles `AlreadyExists` errors for `kubectl create ns` by favoring `kubectl apply -f`
```release-note
```

test: Add GetTemplate and idempotently create namespace

---

.github/pull-request-template.md

chore: Simplified PR template

---

test/gha/cloudformation/iam_cloudformation.yaml

Fixes #N/A 
Adds upgrade permissions to IAM policy for GithubActions and scopes some parts of policy Creation/Deletion down

test: Add Upgrade Permissions to IAM and Scope Policy

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/feature.yaml

Fixes #N/A 
Fix formatting on issue template

chore: Fix formatting on issue template

---

.github/workflows/e2e-upgrade.yaml

Fixes #N/A 
- Fix `k8s_version` input to the `e2e-upgrade` test suite

test: Fix `k8s_version` input to upgrade test

---

.github/actions/e2e/commit-status/end/action.yaml

Fixes #N/A 
- Fix bug in responding with commit status on success

test: Fix bug in responding with commit status on success
