aws/karpenter-provider-aws

- website/content/en/preview/faq.md
Fixes: Issue [#2432](https://github.com/aws/karpenter/issues/2432), [#1807](https://github.com/aws/karpenter/issues/1807), and [#2269](https://github.com/aws/karpenter/issues/2269).
There have been requests to be able to add SSH keys to instances used for Karpenter nodes, via provisioners or similar means. Because the Karpenter project prefers not to add SSH keys via provisioners, this PR recommends alternate ways to access Karpenter nodes, but also describes how to use userData in custom launch templates to add SSH keys when those alternate ways are not suitable.
> docs: Add info to FAQ about SSH keys and node access

- charts/karpenter/templates/clusterrole.yaml
- pkg/cloudprovider/aws/amifamily/ami.go
- pkg/cloudprovider/aws/launchtemplate.go
- pkg/controllers/consolidation/controller.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/state/cluster.go
- website/content/en/preview/faq.md
- Monitor for deployment/stateful set updates when reducing the stabilitization window
- Consider the last node creation time as part of the stabilization window
- Reduce some more log spam
- Add a FAQ entry explaining why sometimes an extra node appears when updating a deployment image
* Unit tested and deployed to EKS.
```release-note
```
> feat: consolidation enhancements

- website/content/en/preview/provisioner.md
- website/content/en/preview/tasks/pod-density.md
Fixes # 
Adds docs for the implementation of #2444 
* Manual view of Netlify docs
```release-note
None
```
> docs: Add docs on additional kubeletConfiguration for `kubeReserved`, `evictionHard`, and `podsPerCore`

- pkg/utils/node/node.go
- test/pkg/environment/environment.go
- test/pkg/environment/expectations.go
- test/pkg/environment/monitor.go
Fixes # 
- Fixes failures due to calling `env.Monitor.Reset()` within a test
- Ignores pods that are `Terminating` for scheduling
```release-note
None
```
> test: Fix integration test monitor flakiness

- website/content/en/preview/provisioner.md
Fixes # 
Another migration of `provider` to `providerRef` in Provisioner API docs
* Manual view of Preview docs
```release-note
None
```
> docs: Migrate from `provider` to `providerRef`

- website/content/en/preview/faq.md
- website/content/en/preview/troubleshooting.md
Fixes # 
- Adds an additional place in the troubleshooting docs to point users to upgrade their CRDs
* Manual view of Preview Docs
```release-note
None
```
> docs: Add troubleshooting guidance for CRD upgrades

- website/content/en/preview/troubleshooting.md
Fixes [Issue #2485](https://github.com/aws/karpenter/issues/2485) 
This PR updates troubleshooting docs to note that clusters on a private subnet are unable to access pricing data because no VPC endpoint is available to get that data. The result is an error message noting that existing pricing data will be used.
> docs:Troubleshooting note on stale pricing data

- test/pkg/environment/expectations.go
- test/suites/integration/emptiness_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/storage_test.go
Fixes # 
- Removes redundant `BeforeEach()`/`AfterEach()` calls that are causing the tests to panic
```release-note
None
```
> test: Remove redundant before/after each calls

- pkg/controllers/termination/suite_test.go
- pkg/controllers/termination/terminate.go
Fixes # N/A
Currently, when Karpenter drains and then deletes a Node from the
cluster, if that node is registered in a Target Group for an ALB/NLB the
corresponding EC2 instance is not removed. This leads to the potential
for increased errors when deleting nodes via Karpenter.
In order to help resolve this issue, this change adds the well-known
`node.kubernetes.io/exclude-from-external-balancers` label, which will
case the AWS LB controller to remove the node from the Target Group
while Karpenter is draining the node. This is similar to how the AWS
Node Termination Handler works (see
aws/aws-node-termination-handler#316).
In future, Karpenter might be enhanced to be able to wait for a
configurable period before deleting the Node and terminating the
associated instance as …
> feat: Add LB exclusion label when deleting node

- test/suites/common/setup.yaml
- test/suites/common/upgrade-crds.yaml
- test/suites/upgrade/pipeline.yaml
Fixes # 
- Fix miss in Tekton `upgrade-crd` task
*
```release-note
None
```
> test: Add cluster name to upgrade crd task

- pkg/test/expectations/expectations.go
- test/pkg/environment/expectations.go
Fixes # 
- Updates all helper functions to have `WithOffset` options so that the caller function line number will be referenced on failure rather than just pointing to the inner failure in the helper function which may not be useful.
```release-note
```
> test: Update `WithOffset` so that failures point to outer call to helper function

- pkg/controllers/provisioning/scheduling/preferences.go
- pkg/controllers/provisioning/scheduling/suite_test.go
Fixes #2545
We would sometimes remove the incorrect topology spread constraint,  resulting in removing a non-preferred constraint which lead to an invalid scheduling decision.
```release-note
```
> fix: correct removal of preferred topology spread constraint

- pkg/cloudprovider/aws/fake/atomic.go
- pkg/cloudprovider/aws/fake/ec2api.go
- pkg/controllers/node/controller.go
- pkg/controllers/state/cluster.go
- pkg/controllers/state/suite_test.go
- pkg/utils/atomic/slice.go
Fixes # 
- Adds an observer reconcile event when node nomination eviction occurs
- This fixes a bug where a node that has a scale down while being nominated will not have `ttlSecondsAfterEmpty` triggered
```release-note
None
```
> fix: Add an observer reconcile event on node nomination eviction

- pkg/controllers/controllers.go
- pkg/utils/injection/injection.go
- pkg/webhooks/webhooks.go
Fixes #2515 
- Adds a log-level watcher to the webhook container
* `make test`
* Manual testing of changing log level
```release-note
None
```
> fix: Add log level watcher for webhook

- Makefile
- pkg/webhooks/webhooks.go
Fixes #2562 
- Revert leader-election for webhooks with Karpenter in HA mode
* Manual install of Karpenter
```release-note
None
```
> fix: Disable leader election for webhooks

- pkg/apis/provisioning/v1alpha5/labels.go
- pkg/test/provisioner.go
- test/pkg/environment/expectations.go
- test/suites/integration/security_group_test.go
- test/suites/integration/webhook_test.go
Fixes # 
E2E validation for defaulting/validating webhooks
```release-note
None
```
> test: Add E2E validation for defaulting/validating webhooks

- pkg/controllers/state/suite_test.go
- test/pkg/environment/expectations.go
Fixes # 
- Based on the way that we are deleting objects, we wait for node scaledown as a blocker until we continue on to future tests; however, it's possible for there to be termianting pods to still be around since we don't technically block for the deletion operation to completely remove the object, just for it to initiate the call
- This will add a blocking operation to ensure that all objects are deleted before starting the next test 
```release-note
None
```
> test: Wait for object deletion after test

- test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-cleanup-cron.yaml
- test/infrastructure/clusters/test-infra/karpenter-tests/test-suites.yaml
Fixes # 
- Adds a cleanup cronjob which will delete any pipelineruns that are beyond 7 days from when the job runs. This task will run daily.
- Adds `ephmeral-storage` requests for the PipelineRun so that the containers generated by the pipeline run account for the resource usage of the ephemeral volume
* Deployment of `CronJob` to local cluster, testing with shorter timeframes
```release-note
None
```
> test: Add ephemeral storage requests and pipelinerun cleanup cron

- Makefile
… the version from git
Fixes # 
Fixes the problem where the application version is not set properly in GA when the tag is not passed down to a workflow that runs on workflow dispatch. 
*
```release-note
```
> fix: use the SNAPSHOT_TAG env variable for application version when available

- .github/workflows/release-tag.yaml
- .github/workflows/stable-release.yaml
Fixes # 
move the release action back to release-tag because it runs only on a Github tag event
* 
```release-note
```
> fix: Undo moving release action

- charts/karpenter/crds/karpenter.sh_provisioners.yaml
- pkg/apis/provisioning/v1alpha5/provisioner.go
- pkg/apis/provisioning/v1alpha5/provisioner_validation.go
- pkg/apis/provisioning/v1alpha5/suite_test.go
- pkg/apis/provisioning/v1alpha5/zz_generated.deepcopy.go
- pkg/cloudprovider/aws/amifamily/al2.go
- pkg/cloudprovider/aws/amifamily/bootstrap/eksbootstrap.go
- pkg/cloudprovider/aws/amifamily/bottlerocket.go
- pkg/cloudprovider/aws/amifamily/custom.go
- pkg/cloudprovider/aws/amifamily/resolver.go
- pkg/cloudprovider/aws/amifamily/ubuntu.go
- pkg/cloudprovider/aws/amifamily/userData.go
- pkg/cloudprovider/aws/instancetype.go
- pkg/cloudprovider/aws/instancetypes_test.go
- pkg/cloudprovider/aws/launchtemplate_test.go
- test/suites/integration/kubelet_config_test.go
Fixes # 
- Adds `evictionSoft` support into `kubeletConfiguration`
- This adds the fields `evictionSoft`, `evictionSoftGracePeriod` and `evictionMaxPodGracePeriod`
```yaml
apiVersion: karpenter.sh/v1alpha5
metadata:
name: default
spec:
...
kubeletConfiguration:
evictionSoft:
memory.available: "50%"
evictionSoftGracePeriod:
memory.available: 180s
evictionMaxPodGracePeriod: 120
```
* `make test`
```release-note
Add `evictionSoft` support into `kubeletConfiguration`
```
> feat: Add `evictionSoft` support to `kubeletConfiguration`

- pkg/controllers/consolidation/controller.go
- pkg/controllers/consolidation/metrics.go
- pkg/controllers/controllers.go
- pkg/controllers/node/emptiness.go
- pkg/controllers/node/expiration.go
- pkg/controllers/provisioning/provisioner.go
- pkg/metrics/constants.go
- pkg/metrics/metrics.go
- website/content/en/preview/tasks/metrics.md
Fixes #2443 
__!! BREAKING CHANGE !!__ 
- Removes `karpenter_consolidation_nodes_created` in favor of `karpenter_nodes_created` with `reason=consolidation`
- Removes `karpenter_consolidation_nodes_terminated` in favor of `karpenter_nodes_terminated` with `reason=consolidation`
- Adds a global metric that counts the number of nodes that Karpenter has terminated and created
- Serves as a pre-req for changes that will come like `notification_controller` that will add its own reason to the set of termination metrics.
NOTE: This doesn't remove consolidation-based create/delete metrics, only deprecates them to be removed sometime in the future
* Deployed to EKS cluster and validated metrics through Prometheus Operator stack
**Does this change …
> BREAKING CHANGE: Migrate termination and creation metrics to shared metrics

- website/content/en/preview/tasks/deprovisioning.md
Tiny change to the wording on spot node consolidation.
It wasn't clear if the deletion consolidation mechanism was only used when working with spot nodes (and not available for on-demand) or when managing spot nodes it only uses the deletion consolidation mechanism.
> docs: Spot consolidation wording change

- Makefile
Fixes # 
Correctly propagate error codes coming from `make tidy` and `make download`
* `make tidy` with error in `go.mod` resolution
```release-note
None
```
> chore: Propagate errors correctly in make tidy and make download

- website/content/en/v0.17.0/getting-started/getting-started-with-terraform/_index.md
Fixes #2633
Fixes docs for Terraform + Helm instalation. The repository should be `repository = "oci://public.ecr.aws/karpenter"`, as the last `/karpenter` is the chart name that is defined in Line 293
I installed it using the guide. The 
```release-note
Fixes docs for Helm Terraform instalation 
```
> docs: Fixes OCI Helm repository

- Makefile
Fixes # 
Show the changed files when running `make verify` and files have been changed during that process:
```
make verify
go mod tidy
go mod download
controller-gen \
object:headerFile="hack/boilerplate.go.txt" \
crd \
paths="./pkg/..." \
output:crd:artifacts:config=charts/karpenter/crds
hack/boilerplate.sh
golangci-lint run
New file modification detected in the Git working tree. Please check in before commit.
- Makefile
- test/go.work.sum
```
```release-note
```
> chore: show changed files in verify

- .github/workflows/stable-release.yaml
…files in the repo
Fixes # 
Changes the order of jobs such that at the time of releasing the binary there are no changes to the code base hence not showing "{commit-id}-dirty in the binary.
* My fork
```release-note
```
> fix: swap action order to get a clean git commit message

- pkg/utils/options/options.go
- website/content/en/preview/tasks/configuration.md
- website/content/en/preview/troubleshooting.md
Added a description of how to disable pricing look-ups by Karpenter. Someone might want to do this to avoid seeing look-up error messages when a cluster is on an isolated, private subnet that doesn't have access to the AWS pricing endpoint.
> docs: Describe how to disable pricing look-ups

- website/content/en/preview/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json
- website/content/en/preview/upgrade-guide/_index.md
Fixes # 
https://github.com/aws/karpenter/pull/2595
https://github.com/aws/karpenter/pull/2595 moved the consolidation metrics around which was a breaking change. This backfills the upgrade guide entry and updates the grafana dashboard. 
```release-note
```
> docs: update grafana metrics and add upgrade entry

- hack/docs/metrics_gen_docs.go
- pkg/metrics/metrics.go
- website/content/en/preview/tasks/metrics.md
Fixes # 
N/A
Fixes an issue with `make docgen` which was introduced in https://github.com/aws/karpenter/pull/2595.  Adds mapping for identifiers to values.
```
% make docgen
go run hack/docs/metrics_gen_docs.go pkg/ website/content/en/preview/tasks/metrics.md
2022/10/11 18:12:36 parsing code in pkg/
2022/10/11 18:12:36 unsupported value *ast.Ident Namespace
exit status 1
make: *** [docgen] Error 1
```
* Ran `make docgen` after fix.  
* Validated that the metrics documentation was created successfully.
```
% make docgen
go run hack/docs/metrics_gen_docs.go pkg/ website/content/en/preview/tasks/metrics.md
2022/10/11 18:13:12 parsing code in pkg/
2022/10/11 18:13:12 writing output to website/content/en/preview/tasks/metrics.md
go run …
```
> fix: metrics docs generation

- pkg/cloudprovider/aws/amifamily/ami.go
- pkg/cloudprovider/aws/launchtemplate_test.go
- test/suites/integration/ami_test.go
From https://github.com/aws/karpenter/pull/2330
* ran `make dev`
* applied changes to my local cluster and found the nodes with new AMIs created.
```release-note
```
> fix: AMI Selection to use latest AMI

- pkg/utils/atomic/cached_val.go
- pkg/utils/atomic/lazy.go
- pkg/utils/atomic/suite_test.go
- pkg/utils/ptr/ptr.go
Fixes # 
- Adds an implementation of lazy evaluation which allows us to cache an api call persistently internally with lazy evaluation
```go
var queueURL atomic.Lazy[string]
queueURL.Resolve = func(ctx context.Context) (string, error) {
ret, err := provider.client.GetQueueUrlWithContext(ctx, provider.getQueueURLInput)
if err != nil {
return "", fmt.Errorf("fetching queue url, %w", err)
}
return aws.StringValue(ret.QueueUrl), nil
}
queueURL.Set("new-url")
```
* `make test`
```release-note
```
> chore: Add an implementation of `atomic.Lazy` which caches values internally

- pkg/cloudproviders/aws/cloudprovider/cloudprovider.go
- pkg/cloudproviders/aws/cloudprovider/instance.go
- pkg/cloudproviders/aws/cloudprovider/instancetypes.go
- pkg/cloudproviders/aws/cloudprovider/instancetypes_test.go
- pkg/cloudproviders/aws/cloudprovider/suite_test.go
- pkg/cloudproviders/aws/cloudprovider/unavailableofferingscache.go
Fixes # 
- `UnavailableOfferingsCache` becomes an encapsulated concept and is injected into the `InstanceTypeProvder`
- This preps initializing `UnavailableOfferingsCache` at the top-level and injecting it into the `notification_controller` with the spot interruption PR
* `make test`
```release-note
None
```
> chore: Create a struct object for ICE cache

- pkg/cloudproviders/aws/apis/v1alpha1/register.go
- pkg/cloudproviders/aws/cloudprovider/instance.go
- pkg/cloudproviders/aws/cloudprovider/launchtemplate_test.go
- pkg/cloudproviders/aws/fake/ec2api.go
This adds AMI-ID as a label on provisioned nodes. 
* `make dev`
* `make apply` and saw a node provisioned with the AMI ID label.
```release-note
```
> feat: Label provisioned nodes with AMI ID

- go.mod
- go.sum
- pkg/cloudproviders/aws/cloudprovider/amifamily/ami.go
- pkg/cloudproviders/aws/cloudprovider/instance.go
- pkg/cloudproviders/aws/cloudprovider/instancetype.go
- pkg/cloudproviders/common/cloudprovider/fake/cloudprovider.go
- pkg/cloudproviders/common/cloudprovider/fake/instancetype.go
- pkg/cloudproviders/common/cloudprovider/types.go
- pkg/controllers/consolidation/helpers.go
- pkg/controllers/provisioning/provisioner.go
- pkg/controllers/provisioning/scheduling/existingnode.go
- pkg/controllers/provisioning/scheduling/node.go
- pkg/controllers/provisioning/scheduling/scheduler.go
- pkg/controllers/provisioning/scheduling/scheduling_benchmark_test.go
- pkg/controllers/provisioning/scheduling/topology.go
- pkg/controllers/provisioning/scheduling/topologygroup.go
- pkg/controllers/provisioning/scheduling/topologynodefilter.go
- pkg/controllers/state/cluster.go
- pkg/controllers/state/zz_generated.deepcopy.go
- pkg/controllers/termination/terminate.go
- test/go.mod
- test/go.sum
- test/suites/integration/kubelet_config_test.go
This reverts commit 883584bb547de1299f8b489af2e76ee1c4f35c22.
Fixes # 
- Breaking e2etests due to webhook crashing on startup
```
➜  karpenter git:(main) ✗ kl deploy/karpenter -n karpenter -c webhook
Found 2 pods, using pod/karpenter-797d9c54b5-bjgf2
2022-10-15T19:40:32.587Z	DEBUG	Successfully created the logger.
2022-10-15T19:40:32.587Z	DEBUG	Logging level set to: debug
{"level":"info","ts":1665862832.5933642,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
2022-10-15T19:40:32.694Z	INFO	webhook	Setting GC memory limit to 94371840, container limit = 104857600	{"commit": "bfe0b14-dirty"}
2022/10/15 19:40:32 Registering 2 clients
2022/10/15 19:40:32 Registering 2 informer factories
2022/10/15 19:40:32 Registering 3 informers
2022/10/15 …
```
> Revert "chore: rely on karpenter-core scheduling libraries (#2667)"

- pkg/controllers/controllers.go
- pkg/operator/options.go
Fixes # 
- Fixes not having `karpenter-global-settings` added to the configMapWatcher informer
```release-note
None
```
> fix: Fix adding CMW before call to start informer

- Makefile
- pkg/controllers/consolidation/controller.go
- pkg/controllers/consolidation/suite_test.go
- pkg/controllers/consolidation/types.go
Fixes #2370
- Use a consolidation TTL of 15 seconds which allows removing the stabilization window
* Unit testing, E2E tests and deployed to EKS.
```release-note
```
> feat: add a node TTL for consolidation

- pkg/cloudproviders/aws/cloudprovider/pricing.go
- pkg/cloudproviders/aws/cloudprovider/pricing_test.go
- pkg/cloudproviders/aws/fake/ec2api.go
Fixes #2568 
Depending on account settings, instances may be listed under one of two product descriptions.  We should query for them both to ensure we don't fail to launch spot instances.
- Unit testing
- Deployed to EKS and verified that my spot instance prices were still fetched.
```release-note
```
> fix: query for both forms of Linux/Unix OS on spot

- Makefile
- go.mod
- go.sum
- pkg/cloudproviders/aws/cloudprovider/instance.go
- pkg/cloudproviders/aws/cloudprovider/instancetypes_test.go
- pkg/cloudproviders/aws/cloudprovider/launchtemplate_test.go
- pkg/cloudproviders/aws/cloudprovider/suite_test.go
- pkg/cloudproviders/aws/fake/ec2api.go
- pkg/cloudproviders/common/cloudprovider/fake/cloudprovider.go
- pkg/cloudproviders/common/cloudprovider/fake/instancetype.go
- pkg/controllers/consolidation/controller.go
- pkg/controllers/consolidation/helpers.go
- pkg/controllers/consolidation/suite_test.go
- pkg/controllers/provisioning/scheduling/instance_selection_test.go
- pkg/controllers/provisioning/scheduling/suite_test.go
- pkg/controllers/provisioning/suite_test.go
- pkg/test/provisioner.go
- test/go.mod
- test/go.sum
- test/suites/consolidation/suite_test.go
- test/suites/integration/webhook_test.go
Fixes # 
*
```release-note
```
> chore: rely on neutral capacity type and break dependency on gpu vendor strings

- hack/docs/instancetypes_gen_docs.go
- pkg/cloudproviders/aws/cloudprovider/cloudprovider.go
Fixes # 
The current AWS CP needs the K8s DNS ip for detecting IPV6, so provide a  mock K8s client that returns it.
*
```release-note
```
> fix: provide a mock k8s client for use in generating instance type docs

- .github/workflows/doc-gen.yml
Fixes # 
* Runs `make docgen` after a successful run of CI
* Should help find out if a change broke `make docgen`
```release-note
```
> Add doc-gen to a post CI test

- cmd/controller/main.go
- cmd/webhook/main.go
- hack/docs/instancetypes_gen_docs.go
- pkg/cloudproviders/aws/cloudprovider/amifamily/resolver.go
- pkg/cloudproviders/aws/cloudprovider/cloudprovider.go
- pkg/cloudproviders/aws/cloudprovider/instancetypes.go
- pkg/cloudproviders/aws/cloudprovider/launchtemplate.go
- pkg/cloudproviders/aws/cloudprovider/securitygroups.go
- pkg/cloudproviders/aws/cloudprovider/subnets.go
- pkg/cloudproviders/aws/cloudprovider/suite_test.go
- pkg/cloudproviders/aws/context.go
- pkg/cloudproviders/aws/context/context.go
- pkg/cloudproviders/common/cloudprovider/types.go
- pkg/webhooks/webhooks.go
Fixes # 
- Initializes the cloudprovider using `aws.Context` which wraps the `cloudprovider.Context`
```release-note
None
```
> chore: Create a `cloudprovider.Context` and `aws.Context` to initialize components

- pkg/cloudproviders/aws/cloudprovider/launchtemplate.go
Fixes # 
- Migrates logger being instantiated in the constructor to using `logging.FromContext(ctx)`
```release-note
None
```
> chore: Migrate launch template provider to use logger context

- pkg/controllers/provisioning/scheduling/queue.go
- pkg/controllers/provisioning/scheduling/suite_test.go
This is a minor fix, but allows us to schedule to lager nodes in the case where pods have inter-dependencies that can be satisfied as long as they are scheduled in the correct order. There was a test for this, but the test was incorrect in that it didn't actually verify that the pods scheduled.
```release-note
```
> fix: cycle through pods multiple times as required when scheduling

- cmd/controller/main.go
- pkg/cloudproviders/aws/cloudprovider/instance.go
- pkg/cloudproviders/aws/controllers/controllers.go
- pkg/cloudproviders/aws/utils/utils.go
- pkg/cloudproviders/common/cloudprovider/types.go
- pkg/controllers/controllers.go
Fixes # 
- Adds AWS-specific controllers to `cloudproviders/aws/controllers`
- Adds a `GetControllers()` function that does provider instantiation
* `make test`
* Manual deployment to EKS cluster
```release-note
None
```
> chore: Initialize cloudprovider-specific controllers

- charts/karpenter/templates/clusterrole.yaml
This is required for handling topology spreads with namespace selectors where we need to look up namespaces matching a selector.
Fixes #2702
* Deployed to EKS
```release-note
```
> fix: add permission for listing namespaces

- hack/release/add-snapshot-tag.sh
Fixes # 
Adds `v0-` to the helm chart tag for nightlies. 
*
```release-note
```
> fix: Add v0 to helm repo chart of nightly

- cmd/webhook/main.go
- go.mod
- go.sum
- pkg/apis/apis.go
- test/go.mod
- test/go.sum
- test/pkg/environment/common/expectations.go
- test/pkg/environment/common/setup.go
- test/suites/integration/webhook_test.go
This bug was introduced in the recent code split between karpenter and `karpenter-core`
Fixes # 
* `make e2etest`
```release-note
```
> fix: resolve a bug where AWSNodeTemplate webhooks were no longer registered

- hack/api-code-gen.sh
- hack/code/prices_gen.go
- hack/code/vpc_limits_gen.go
Fixes # 
```
❯ make api-code-gen
GOFLAGS="-ldflags=-X=github.com/aws/karpenter/pkg/utils/project.Version=v0.18.0-49-g6f4e5e12" ./hack/api-code-gen.sh
M	hack/api-code-gen.sh
M	hack/code/prices_gen.go
M	hack/code/vpc_limits_gen.go
Already on 'api-code-gen'
2022/10/24 11:30:09 waiting on pricing update...
2022/10/24 11:30:10 waiting on pricing update...
{"level":"info","ts":1666636210.25562,"logger":"fallback.pricing","caller":"cloudprovider/pricing.go:416","msg":"updated spot pricing with 560 instance types and 2631 offerings"}
2022/10/24 11:30:11 waiting on pricing update...
2022/10/24 11:30:12 waiting on pricing update...
{"level":"info","ts":1666636212.653006,"logger":"fallback.pricing","caller":"cloudprovider/pricing.go:267","msg":"updated on-demand pricing with 560 …
```
> fix: Fixed API Code Gen

- website/content/en/preview/getting-started/getting-started-with-eksctl/prometheus-values.yaml
Fixes # 
#2480
Prior to this change, static scrape targets were configured for the Karpenter service in the Prometheus scrape config.  When only a single Karpenter pod exists, this was fine given Prom would always scrape the one existing Karpenter pod.  When more than one replica exists, Prometheus will potential hit one or the other pod at each scrape interval which can skew metrics.  This change uses the Endpoint discovery mechanism to discover the service endpoints and then scrape them each directly.
* Manually validated that queries used by Grafana are aggregating metrics.  
* I also manually validated that Grafana dashboards still are returning what looks like accurate data. …
> fix: updating prom scrape target

- cmd/controller/main.go
- go.mod
- go.sum
- pkg/cloudprovider/instancetypes_test.go
- pkg/cloudprovider/launchtemplate_test.go
- pkg/cloudprovider/suite_test.go
- pkg/controllers/controllers.go
- test/go.mod
- test/go.sum
Fixes # 
- Adds a `settings.Controller` that watches the `karpenter-global-settings` ConfigMap
- Creates a wrapper around the configMap.Data called `settings.Settings`
- Injects this settings into `Reconcile` context using the `InjectSettings` decorator
__NOTE: This PR doesn't fix dynamically updating the `nominationPeriod`. That needs some more thought and should be done in a separate PR.__
The use-case of this is to be able to do the following:
```go
operatorsettings.FromContext(ctx).BatchMaxDuration
```
Or for cloudproviders, something like
```go
awssettings.FromContext(ctx).EnablePodENI
```
```release-note
None
```
By …
> chore: Migrate from `config.Config` to `settings.Settings` injection

- hack/release/add-snapshot-tag.sh
Fixes # 
Nightlies were broken by https://github.com/aws/karpenter/pull/2728
*
- [ x ] No
```release-note
```
> fix: nightlies do not try to tag webhook as it's now removed

- pkg/cloudprovider/amifamily/bottlerocket.go
- pkg/cloudprovider/amifamily/resolver.go
- pkg/cloudprovider/launchtemplate_test.go
- pkg/context/context.go
Fixes # 
*
```release-note
```
> chore: remove non generic ptr libraries

- test/pkg/environment/aws/setup.go
- test/pkg/environment/common/options.go
- test/pkg/environment/common/setup.go
- test/suites/consolidation/suite_test.go
- test/suites/integration/suite_test.go
- test/suites/ipv6/suite_test.go
- test/suites/utilization/suite_test.go
Fixes # 
- Always prints test logs now since log dump is in a separate `AfterEach` block
- Always do ForceCleanup to avoid test pollution
*
```release-note
None
```
> test: Always print test logs, even if cleanup fails

- test/pkg/environment/common/setup.go
- test/suites/integration/expiration_test.go
Fixes # 
- Expiration tests are flaking because a previous test is provisioning a node in the middle of two tests. This causes an extra node to exist on the cluster when the test starts
* `FOCUS=Expiration make e2etests`
```release-note
None
```
> test: Fix flaky expiration test

- pkg/apis/v1alpha5/provisioner.go
- pkg/apis/v1alpha5/suite_test.go
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/launchtemplate_test.go
- pkg/cloudprovider/suite_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/webhook_test.go
- website/content/en/preview/upgrade-guide/_index.md
Fixes # 
This change will force a minor version bump as specified in https://karpenter.sh/docs/upgrade-guide/
Instance category defaults are now explicitly persisted in the Provisioner, rather than handled implicitly in memory. By default, Provisioners will limit instance category to c,m,r. If any instance type constraints are applied, it will override this default. If you have created Provisioners in the past with unconstrained instance type, family, or category, Karpenter will now more flexibly use instance types than before. If you would like to apply these constraints, they must be included in the Provisioner CRD.
This also helps to decouple instance type from provisioner, enabling upcoming work.
* `make test`
**Does this change impact …
> BREAKING CHANGE: Move instance type filtering from implicit to explicit at defaulting time

- pkg/cloudprovider/amifamily/al2.go
- pkg/cloudprovider/amifamily/resolver.go
- pkg/cloudprovider/cloudprovider.go
Fixes # 
https://github.com/aws/karpenter/issues/2787
- Do not fail on startup if kube-dns cannot be discovered. Some users have a custom dns setup and are not using kube-dns. Karpenter should still function if that is the case. 
* Removed rbac permissions and Karpenter started up successfully whereas before it would go into a CrashLoopBackoff.
```release-note
```
> fix: do not fail when discovering kube-dns cluster ip

- hack/docs/metrics_gen_docs.go
- pkg/controllers/interruption/metrics.go
- pkg/controllers/nodetemplate/metrics.go
- website/content/en/preview/tasks/metrics.md
Fixes # 
- Fixes metrics docgen by manually mapping identifiers
```release-note
None
```
> fix: Fix metrics docgen with manual subsystem

- pkg/controllers/nodetemplate/infrastructure.go
- test/suites/common/setup.yaml
Fixes # 
- Adds policy binding for new `KarpenterEventPolicy-${CLUSTER_NAME}` policy to service account
* Tested in Tekton pipelines
```release-note
None
```
> test: Add policy-binding for interruption E2E

- pkg/controllers/interruption/interruption_benchmark_test.go
- pkg/controllers/nodetemplate/infrastructure.go
- pkg/controllers/nodetemplate/suite_test.go
- pkg/errors/errors.go
- test/suites/interruption/suite_test.go
- website/content/en/preview/getting-started/getting-started-with-eksctl/cloudformation.yaml
Fixes # 
- Fixes cloudformation template to use tags
- Fixes backoff when queue was recently deleted
* 
```release-note
None
```
> fix: Fix cloudformation and sqs queue backoff

- test/pkg/environment/aws/environment.go
- test/pkg/environment/common/environment.go
- test/pkg/environment/common/setup.go
- test/suites/consolidation/suite_test.go
- test/suites/integration/ami_test.go
- test/suites/integration/block_device_mappings_test.go
- test/suites/integration/cni_test.go
- test/suites/integration/emptiness_test.go
- test/suites/integration/expiration_test.go
- test/suites/integration/kubelet_config_test.go
- test/suites/integration/metadata_options_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/security_group_test.go
- test/suites/integration/storage_test.go
- test/suites/integration/subnet_test.go
- test/suites/integration/suite_test.go
- test/suites/integration/tags_test.go
- test/suites/integration/webhook_test.go
- test/suites/interruption/suite_test.go
- test/suites/ipv6/suite_test.go
- test/suites/utilization/suite_test.go
Fixes # 
- Fixes getting cluster name and other details from settings context
* `FOCUS="KubeletConfiguration" make e2etests`
```release-note
None
```
> test: Add settings injection into E2E testing

- cmd/controller/main.go
- test/suites/common/upgrade-crds.yaml
Fixes # 
- Upgrade CRDs points to the wrong location in E2E tests with #2792 
- Settings injection can be simplified in `main.go`
```release-note
None
```
> test: Fix upgrade E2E test for upgrade CRDs

- pkg/cloudprovider/cloudprovider.go
- website/content/en/preview/faq.md
Fixes # 
https://github.com/aws/karpenter/issues/2721
- Increase the flexibility of instance type options passed to each EC2 Fleet call. 
* scaled out a flexible pod and checked cloudtrail for the fleet request. It successfully added 180 instance types (60*3 AZs)
```release-note
```
> feat: increase instance type flexibility on each fleet call

- test/suites/integration/ami_test.go
Fixes # 
Test was flaking. 
Test relies on the SSM alias for the recommended EKS Optimized AMI but rather than referring to a previous release, just decrements the kubernetes version. These all have the CreationTimestamp as the same, so it doesn't always succeed.
*
```release-note
```
> test: removed test to add back in later

- Makefile
- test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml
- test/pkg/environment/common/environment.go
- test/pkg/environment/common/setup.go
- test/suites/chaos/suite_test.go
- test/suites/common/setup.yaml
- test/suites/upgrade/pre-upgrade-setup.yaml
Fixes # 
- Creates chaos tests that validate that we stay under some node count while constantly tainting a node after creation
Relates to #2821 
* `FOCUS=Chaos make e2etests`
```release-note
None
```
> test: Chaos testing for Runaway Scale-up Issue

- test/pkg/environment/aws/environment.go
- test/pkg/environment/aws/expectations.go
- test/suites/interruption/suite_test.go
Fixes # 
- Adds test for checking that global tags exist on interruption infra
* `FOCUS=Infrastructure make e2etests`
```release-note
None
```
> test: Add test for adding global tags to interruption infra

- Makefile
- charts/karpenter/templates/deployment.yaml
Fixes # 
Fixes `make run` by creating ConfigMap that was broken by #2746 
* `make run`
```release-note
None
```
> chore: Fix `make run` target

- hack/docs/metrics_gen_docs.go
- website/content/en/preview/tasks/globalsettings.md
- website/content/en/preview/tasks/metrics.md
Fixes # 
Fix metrics titling so all titles in `metrics.md` are capitalized correctly
```release-note
None
```
> docs: Fix metrics titling from gen code

- website/content/en/preview/getting-started/getting-started-with-eksctl/cloudformation.yaml
Fixes # 
- Scopes Cloudformation down to only operate on the InterruptionQueue
*
```release-note
None
```
> fix: Scope cloudformation for queue operations

- go.mod
- go.sum
- test/go.mod
- test/go.sum
Fixes # 
- Upgrade Karpenter Core to pull ownerless pod eviction
* N/A
```release-note
```
> chore: upgrade karpenter-core to pull in ownerless pod eviction

- go.mod
- go.sum
- test/go.mod
- test/go.sum
- test/pkg/environment/common/expectations.go
- test/suites/integration/scheduling_test.go
Fixes # 
- Tests E2E for node initialization when extended resources are expected on the node
Buddy change and testing for https://github.com/aws/karpenter-core/pull/69
* `FOCUS="Extended Resources" make e2etests`
```release-note
None
```
> test: Test that instances are able to initialize for extended resources

- website/content/en/preview/getting-started/getting-started-with-eksctl/_index.md
Fixes broken link to Deprovisioning task page
Fixes # 
*
```release-note
```
> docs: Fix a broken link

- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step13-automatic-node-provisioning.sh
Upstream has a newer container image
Fixes # 
*
```release-note
```
> chore: Bump pause container to latest

- pkg/controllers/interruption/controller.go
- pkg/controllers/interruption/sqs.go
- pkg/controllers/interruption/suite_test.go
Fixes # 
- Error with backoff when queue does not exist but `interruptionQueueName` is set
```release-note
None
```
> fix: Error when queue does not exist

- website/content/en/preview/AWS/provisioning.md
Fixes # 
N/A
Adds some more contextual information for Pod ENIs and Security Groups for pods.  Also adds a Helm value for enablePodENIs to make configuration a bit easier.
* Followed instructions in the documentation to enable POD ENI support.
* Tested that Karpenter provisions nodes when pod-eni resource is requested.
```release-note
adds more information regarding Pod ENI support
```
> docs: adds more pod-eni info

- test/pkg/environment/common/expectations.go
- test/suites/integration/scheduling_test.go
Fixes # 
- Fix enabling `ENABLE_POD_ENI` when testing `pod-eni`
* `FOCUS="Extended Resources" make e2etests`
```release-note
```
> test: Fix enabling POD_ENI on aws-cni DS

- test/pkg/environment/aws/environment.go
- test/suites/integration/scheduling_test.go
- test/suites/upgrade/pipeline.yaml
Fixes # 
- Add 3 retries for AWS API calls that have retryable errors like throttling.
- Up the starting Karpenter version in the Upgrade test to v0.18.1
* `make e2etsts`
```release-note
```
> test: retry aws api calls in tests, up version in upgrade test

- charts/karpenter/templates/webhooks.yaml
Signed-off-by: smcavallo <smcavallo@hotmail.com>
Fixes # 
Small change to update the webhook rules to be sorted alphabetically.
The sorting was changed as part of this commit ->  https://github.com/aws/karpenter/commit/b358e0040153183d2df720e39b9530f50251889f
The api group names are similar enough to confuse the way ArgoCD detects differences, which means these webhooks are constantly appearing as OutOfSync.  I am assuming this is also causing issues with Flux and other tools.
Either way, reverting the order so they are now properly sorted alphabetically.
*
```release-note
```
> fix: helm chart webhook sort order

- test/pkg/environment/aws/environment.go
Fixes # 
- Up AWS API call retries during e2e tests to avoid throttling flakes.
```release-note
```
> test: up AWS API retries on e2e tests to combat throttling flakes

- go.mod
- go.sum
- test/go.mod
- test/go.sum
Fixes # 
- https://github.com/aws/karpenter-core/pull/71 and fixes a bug introduced where the Consolidation TTL wasn't considered for empty nodes, resulting in cases where empty nodes would get more aggressively terminated.
*
```release-note
```
> chore: upgraded karpenter-core to pull in deprovisioning interface changes

- Makefile
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Fixes # 
- Update Karpenter core to pull in "track pending pods when consolidating https://github.com/aws/karpenter-core/pull/79" 
- Add make target to update karpenter-core in the main go module and the test module. 
*
```release-note
```
> fix: update Karpenter core to track pending pods when consolidating

- charts/karpenter/templates/webhooks.yaml
Fixes # 
Minor fix for `validation.webhook.karpenter.k8s.aws` webhook.
It seems like DELETE method for karpenter.k8s.aws group was removed in #2754.
I see no reason for the deletion, and think it was a mistake.
*
```release-note
```
> fix: add missing DELETE method for validating webhook

- pkg/cloudprovider/instance.go
Fixes # 
https://github.com/aws/karpenter/issues/2896
- The price-capacity-optimized allocation strategy for Spot has not been launched in China regions yet, so revert to using capacity-optimized-prioritized until it is launched.
* Deployed to EKS Cluster in us-east-2, verified in CloudTrail that price-capacity-optimized was being used. Changed the `strings.HasPrefix` calls to use "us-" instead of "cn-" and redeployed. Observed CreateFleet requests in CloudTrail using capacity-optimized-prioritized with Priorities assigned in the requests.
```release-note
```
> fix: use Spot capacity-optimized-prioritized in China regions until price-capacity-optimized is launched there

- website/content/en/v0.17.0/provisioner.md
- website/content/en/v0.18.0/provisioner.md
- website/content/en/v0.18.1/provisioner.md
- website/content/en/v0.19.0/provisioner.md
- website/content/en/v0.19.1/provisioner.md
- website/content/en/v0.19.2/provisioner.md
Fixes #2890 
Add a warning note on `evictionSoft` and relevant eviction soft signals not being supported in Bottlerocket
* Viewing the new docs
```release-note
None
```
> docs: Add note on eviction soft support in BR

- website/content/en/preview/getting-started/getting-started-with-terraform/_index.md
Fixes # 
- Update Terraform getting started guide to utilize latest module versions
- Add support for Karpenter native instance termination handling to the guide
- Update helm release to use credentials pulled from ECR now that OCI chart is on ECR
- Changes were pulled down locally to provision resources and then exercise the scaling out and scaling in as defined in the updated guide
```release-note
```
> docs: Update Terraform getting started guide to include recent changes

- .github/actions/authenticate-aws/action.yml
…Github Actions
Fixes # 
Upgrade to the plugin version shipped with node 16 to avoid the following warning:
*Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: aws-actions/configure-aws-credentials@v1
* My own fork
```release-note
```
> chore: Use the auth library version that comes with node 16

- .github/workflows/ci-test.yml
Per docs, AWS stopped supporting 1.20 on November 1, 2022
*
```release-note
```
> chore: remove K8s 1.20 from CI

- test/pkg/environment/common/expectations.go
Fixes # 
Add sleep to allow settings to be injected in tests when changing settings.
* make apply && make e2etests
```release-note
```
> test: fix test settings flakes

- .github/workflows/stable-release.yml
- hack/release/common.sh
Fixes # 
Adds snapshot release on stable releases
This was happening naturally before but now it will happen for cherry picked stable releases as well
* Different fork
```release-note
```
> fix: Rm/add snapshots on cherry picked releases

- go.mod
- go.sum
- pkg/apis/v1alpha1/provider.go
- pkg/apis/v1alpha5/provisioner.go
- pkg/apis/v1alpha5/suite_test.go
- pkg/cloudprovider/amifamily/ami.go
- pkg/cloudprovider/amifamily/resolver.go
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/instance.go
- pkg/cloudprovider/instancetypes_test.go
- pkg/cloudprovider/launchtemplate.go
- pkg/cloudprovider/pricing.go
- pkg/cloudprovider/suite_test.go
- test/go.mod
- test/go.sum
- test/suites/integration/backwards_compatability_test.go
- test/suites/integration/kubelet_config_test.go
Fixes # 
- Use Machine spec in memory to launch instances through `cloudprovider.Create`
This is a buddy change for: https://github.com/aws/karpenter-core/pull/102
* `FOCUS="Scheduling" make e2etests`
```release-note
None
```
> chore: Use Machine Spec in Memory for `cloudprovider.Create`

- ADOPTERS.md
Adds PlanetScale to list of adopters. 🎊 
While we've not completely migrated our workloads, Karpenter has launched more than 50% of our node globally, so I'll consider that an official adoption if I've ever seen one.
* Human eyeballs.
```release-note
Added PlanetScale to list of adopters.
```
> docs: Add PlanetScale to list of adopters.

- pkg/cloudprovider/amifamily/al2.go
- pkg/cloudprovider/launchtemplate_test.go
- website/content/en/preview/concepts/provisioning.md
Fixes # 
- Previously, neuron (inferentia) instance types needed to use dockerd rather than containerd. This was fixed though so that the neuron device plugin works with containerd now, so removing this weird logic of different defaults for different instance types and using containerd as the default always. This also fixes inferentia support for K8s 1.24+ since docker is no longer available. 
* Deployed an inf1 and neuron workload on containerd
```
> kgpa
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
default       eks-neuron-test-6574755847-6kg7d       1/1     Running   0          11m
default       eks-neuron-test-6574755847-gmr4g       1/1     Running   0          11m
default …
```
> fix: use containerd for neuron

- website/assets/js/versionWarning/index.js
Fixes # 
When clicking on "latest verison" from the old version pop-up this should retain the current path so the user isn't send back to the main docs page. If the path doesn't exist in the new version they'll get the standard 404 page.
* running docs locally with multiple versions
```release-note
```
> docs: Retain current path in new version docs link

- test/suites/integration/testdata/amd_driver_input.sh
Fixes # 
- Fix AMD test flake when the kernel is updated
```
FOCUS="should provision nodes for a deployment that requests amd.com/gpu" make e2etests
``` 
```release-note
```
> fix: amd test flake

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/suite_test.go
Fixes # 
- Adds a check to make sure that providerRef is defined for IsMachineDrifted()
* make presubmit
```release-note
```
> fix: remove panic on IsMachineDrifted on provider ref nil reference

- Makefile
Fixes # 
- Bump ginkgo timeout so that it doesn't panic on 60m default timeout
```release-note
None
```
> test: Bump ginkgo timeout so that ginkgo doesn't panic

- website/assets/js/versionWarning/index.js
Reverts aws/karpenter#3013
Avoid DOM-based cross site scripting risk
> Revert "docs: Retain current path in new version docs link"

- website/content/en/preview/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json
- website/content/en/v0.19.3/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json
- website/content/en/v0.20.0/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json
Fixes [kubernetes slack-link](https://kubernetes.slack.com/archives/C02SFFZSA2K/p1669673009999729)
* local grafana dashboard
oard
```release-note
Replaced deprecated `karpenter_consolidation_actions_performed` metric with `karpenter_deprovisioning_actions_performed` on Karpenter Capacity grafana dashboard.
```
> fix: Replace consolidation panel for deprovisioning panel in karpenter capacity dashboard

- website/content/en/preview/getting-started/migrating-from-cas/scripts/step11-create-provisioner.sh
- website/content/en/v0.19.3/getting-started/migrating-from-cas/scripts/step11-create-provisioner.sh
- website/content/en/v0.20.0/getting-started/migrating-from-cas/scripts/step11-create-provisioner.sh
* Changed key `karpenter.k8s.aws/instance-family` to `karpenter.k8s.aws/instance-category`, current example configuration gives "no instance type satisfied resources" error. 
* Bump `karpenter.k8s.aws/instance-generation` value from `2` to `4`, as per AWS current generation doc.  
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html#AvailableInstanceTypes
Fixes #3078 
* Read rendered doc to make sure correct example configuration appears.
```release-note
* Changed key `karpenter.k8s.aws/instance-family` to `karpenter.k8s.aws/instance-category`, current example configuration gives "no instance type satisfied resources" error. 
* Bump …
```
> docs: Update step11-create-provisioner.sh

- pkg/cloudprovider/subnets.go
- pkg/cloudprovider/subnets_test.go
- test/suites/integration/subnet_test.go
- website/content/en/preview/concepts/node-templates.md
- website/content/en/v0.20.0/concepts/node-templates.md
Fixes # 
Closing out: https://github.com/aws/karpenter/pull/2859
Support comma separated tag values in subnetSelector - (wildcard search is not flexible enough.)
Consider the use case where Private1,Private2 subnets should be used but Private3 excluded.
This is a simple enough change to split the string and supported by the ec2 tag filters.
It is done this same exact way for aws-ids searches.
*
```release-note
```
> Feat: Support comma separated tag values in subnetSelector

- website/content/en/preview/concepts/scheduling.md
Fixes # 
- Clarify details on the scheduling section on what happens with user-defined labels
Related to #3075
*
```release-note
None
```
> docs: Clarify details on what to do with user-defined labels

- website/content/en/preview/concepts/_index.md
- website/content/en/preview/concepts/overview.md
- website/content/en/v0.20.0/concepts/_index.md
- website/content/en/v0.20.0/concepts/overview.md
preview and v0.20.0 docs don't have tasks directory unlike previous releases. Probably because all required files were moved to concepts directory.
This fixes 4 unique links (4x4 = 16 broken links that are present in _index.md and overview.md of preview and v0.20.0 docs )
Yes. Using netlify docs generated by this PR. All 4 unique links are working fine.
> docs: fix broken links related to tasks directory

- test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml
Fixes # 
Adds the e2e drift test into the e2e testing suites.
*
```release-note
```
> test: add drift into e2e test suites cron

- pkg/cloudprovider/securitygroups.go
- pkg/cloudprovider/securitygroups_test.go
- test/suites/integration/security_group_test.go
- website/content/en/preview/concepts/node-templates.md
- website/content/en/v0.19.3/AWS/provisioning.md
Fixes # 
Finishing out https://github.com/aws/karpenter/pull/2923
Support comma separated tag values in securityGroupSelector - (wildcard search is not flexible enough.)
Consider the use case where sg-1,sg-2 security groups should be used but sg-3 excluded.
This is a simple enough change to split the string and supported by the ec2 tag filters.
It is done this same exact way for aws-ids searches.
Similar to https://github.com/aws/karpenter/pull/2859
*
```release-note
```
> Feat: Support comma separated tag values in securityGroupSelector

- test/suites/integration/testdata/amd_driver_input.sh
Fixes # 
- Bumps the time before we restart to 60s for the eks bootstrap script to get started so we have enough time for the kubelet service to get setup before reboot
*
```release-note
None
```
> test: Bump time before the reboot to give kubelet enough time to start

- website/content/en/v0.16.3/provisioner.md
- website/content/en/v0.18.1/provisioner.md
- website/content/en/v0.19.3/provisioner.md
- website/content/en/v0.20.0/concepts/provisioning.md
Fixes # 
- Propagate provisioner defaults across all docs versions
*
```release-note
None
```
> docs: Propagate provisioner defaults across all docs versions

- test/suites/common/dump-logs.yaml
- test/suites/common/suite.yaml
- test/suites/ipv6/pipeline.yaml
- test/suites/upgrade/pipeline.yaml
…f Karpenter pods, and nodes to help troubleshooting failures before the cluster is cleaned up
Fixes # 
* Keeps controlelr and node logs when a step fails. These are currently inaccessible for troubleshooting since the cluster is removed as a next step.
* running in my own fork
```release-note
```
> test: dump controller logs on failures

- .github/workflows/deflake.yml
- Makefile
- hack/toolchain.sh
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/suite_test.go
Fixes # 
- Deflake cloudprovider testing by moving pricing provider reset after api and cache clear
* `make deflake-until-it-fails`
```release-note
None
```
> test: Deflake cloudprovider testing by moving pricing provider reset after api and cache clear

- pkg/cloudprovider/pricing_test.go
Fixes # 
Checking on-demand last updated causes a test flake due to a race condition 
* `make deflake-until-it-fails`
```release-note
None
```
> test: Check for spot last updated, not on-demand

- test/pkg/environment/common/expectations.go
- test/suites/integration/extended_resources_test.go
- test/suites/integration/testdata/amd_driver_input.sh
Fixes # 
- Updates the `userData` to reboot after bootstrapping the node to EKS
* `FOCUS=ExtendedResources make e2etests`
```release-note
None
```
> test: Run reboot after running the EKS bootstrap script

- go.mod
- go.sum
- test/go.mod
- test/go.sum
Fixes # 
Bump `go.mod` to use karpenter-core v0.21.0
*
```release-note
None
```
> chore: Bump `go.mod` to use karpenter-core v0.21.0

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/suite_test.go
- pkg/controllers/drift/controller.go
- pkg/controllers/drift/suite_test.go
Fixes #3120
No longer errors on drift controller if a provider is not set. Also disables the drift controller if the drift feature flag is not enabled. 
* `make apply` and validate described behavior.
```release-note
```
> fix: do not error for drift if disabled or using provider

- go.mod
- go.sum
- pkg/cloudprovider/amifamily/resolver.go
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/instance.go
- pkg/cloudprovider/instancetypes.go
- pkg/cloudprovider/launchtemplate.go
- pkg/cloudprovider/launchtemplate_test.go
- pkg/cloudprovider/securitygroups.go
- pkg/cloudprovider/subnets.go
- pkg/cloudprovider/suite_test.go
- pkg/controllers/drift/controller.go
- pkg/fake/cloudprovider.go
- test/go.mod
- test/go.sum
Fixes # 
- Abstract provider calls into interface to enable the underlying implementation to be swapped out for use-cases like for testing. This also makes the public API smaller and the interface cleaner
```release-note
None
```
> chore: Migrate to `v1alpha5` and cleanup some provider cross-pollination

- pkg/cloudprovider/cloudprovider.go
- website/content/en/preview/concepts/settings.md
Fixes # 
There are 3-possible node naming conventions:
- IP name: `ip-10-0-2-200.ec2.internal`
- Resource Based DNS Name: `i-0123456789.ec2.internal`
- Resource Based Naming w/ External Cloud Provider: `i-0123456789`
This change supports all 3 with the previous Karpenter configuration of `nodeNameConvention`. `ip-name` will refer to both dns-based naming since this is the default and is by far the most common configuration. If using the external AWS Cloud Provider with node naming enabled, then the `resource-name` value can be used for the `nodeNameConvention` to name nodes without the DNS suffix. 
This change updates the docs to clarify the nodeNameConvention parameter.
* Tested on an EKS cluster by:
* Launching nodes in subnets with RBN …
> Fix resource-based naming node names 

- charts/karpenter/templates/poddisruptionbudget.yaml
- charts/karpenter/templates/webhooks-core.yaml
- charts/karpenter/templates/webhooks.yaml
Added additional annotations to all Kubernetes resources.
* Rendering helm chart manually
> fix: Add missing additional annotations

- pkg/cloudprovider/instance.go
This reverts commit 470aa83476d121f9215d7a209d6725b2d0e11738.
Fixes # 
- This change reverts a previous commit that special cased the spot allocation strategy used in regions within China since the Price Capacity Optimized allocation strategy had not been released there yet. It is now available, so removing this special case. 
```release-note
```
> Use Spot Price-Capacity-Optimized in China regions

- .github/workflows/approval-comment-snapshot.yml
- .github/workflows/approval-comment.yml
- hack/release/common.sh
- hack/release/release.sh
Fixes # 
* Adds PR number to the notification message where available
* Removes crd release from the GHA because it was shown to not work in some cases
*
```release-note
```
> fix: Add pr number to notification

- cmd/controller/main.go
- go.mod
- go.sum
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/instancetypes_test.go
- pkg/cloudprovider/launchtemplate.go
- pkg/cloudprovider/suite_test.go
- pkg/controllers/controllers.go
- test/go.mod
- test/go.sum
Fixes # 
- Bump karpenter/core for compatability with new cluster `state.Node`
* `FOCUS=Scheduling make e2etests`
```release-note
None
```
> chore: Bump karpenter/core for compatability with new cluster `state.Node`

- website/content/en/preview/concepts/deprovisioning.md
- website/content/en/v0.21.1/concepts/deprovisioning.md
- website/content/en/v0.22.0/concepts/deprovisioning.md
Fixes # 
Adds Drift into list of deprovisioning methods that are blocked by do-not-evict pods. 
* make website
```release-note
```
> docs: fix docs about disabling deprovisioning

- test/suites/common/suite.yaml
- test/suites/ipv6/pipeline.yaml
- test/suites/upgrade/pipeline.yaml
Fixes # 
Removing the cleanup notification failure. Since task status only reflects the status of the tasks not those under the finally this does not work as expected. It would not cause a notification when a failure occurs. It also causes a double notification each time any of the tasks e.g. tests fail.
*
```release-note
```
> test: remove failure notification on cleanup

- pkg/controllers/interruption/controller.go
- pkg/controllers/interruption/suite_test.go
Fixes # 
- Ignore K8s NotFound error on interruption delete
- The wrong error type was checked prior to this fix. We were checking for the `awserrors.NotFound` error rather than the K8s NotFound error
```release-note
None
```
> fix: Ignore K8s NotFound error on interruption delete

- hack/code/instancetype_testdata_gen.go
- pkg/apis/v1alpha1/register.go
- pkg/cloudprovider/instancetype.go
- pkg/cloudprovider/instancetypes_test.go
- pkg/fake/zz_generated.describe_instance_types.go
- website/content/en/preview/concepts/scheduling.md
Adds support for "karpenter.k8s.aws/instance-encryption-in-transit-supported" label to allow to select instances that support the in-transit encryption
* running test suites locally
* on an EKS cluster when specifying "karpenter.k8s.aws/instance-encryption-in-transit-supported" either in provisioner's requirements or pod's nodeSelector / nodeAffinity
```release-note
```
> feat: add support for "karpenter.k8s.aws/instance-encryption-in-transit-supported" label

- hack/release/common.sh
- test/cmd/release-notification-listener/listener/listener.go
- test/cmd/release-notification-listener/listener/message.go
- test/cmd/release-notification-listener/listener/tekton.go
- test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml
- test/infrastructure/clusters/test-infra/release-notification-listener/release-notification-listener.yaml
Fixes # 
* In the upgrade tests uses the last stable version from the message, previously we used to hard code this and had to keep maintaining it
* Remembers the last stable releases from the last message and uses it when it's not given
* Ignores the message if it's not coming from the main repo
- [ x] No
```release-note
```
> test: use last stable release version in upgrade tests

- pkg/cloudprovider/instance.go
Fixes # 
N/A
- If the DescribeInstances call fails after 6 tries, the err message tries to dereference the `instance` which is nil if it can't be looked up which results in Karpenter crashing rather than just reporting an error back to the provisioner. 
*
```release-note
```
> fix: a crash when instance can't be looked up on node creation

- pkg/cache/unavailableofferings.go
- pkg/cloudprovider/createfleetbatcher.go
- pkg/cloudprovider/instance.go
- pkg/cloudprovider/instancetypes.go
- pkg/providers/subnet/subnet.go
- pkg/utils/utils.go
- test/suites/interruption/suite_test.go
and adjusting the batching window parameters
Fixes # 
https://github.com/aws/karpenter/issues/2756
- Removes the vcpu resource limit on the Karpenter controller
- Fixes the subnet filter hashing to use slicesAsSets
- Moves the regex compilation to a pkg var
- Remove unneeded lock when Listing instance types
- Cache fully initialized instance types per all instance types, zones, unavailableOfferings cache, node template, and kubelet configuration from the provisioner
- Adjust the CreateFleetBatcher idle and max timeout from 10ms / 100ms to 50ms / 1,000ms
Before tuning, scale up inflate with a hostname topology spread (1 pod / node):
```
> kubectl scale deploy/inflate --replicas=250 
```
```
karpenter-857dc6c5f7-fzct6 controller 2023-01-18T15:42:39.427Z	INFO …
```
> fix: improve createfleet batching by caching fully initialized instance types

- website/content/en/preview/concepts/provisioners.md
- website/content/en/v0.22.1/concepts/provisioners.md
So that they are more easily found!
Fixes # 
* Used the preview link from the bot!
```release-note
docs:  Add link to well-known labels from spec.requirements section
```
> docs:  Add link to well-known labels from spec.requirements section

- charts/karpenter/README.md
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
Fixes #3220
Fix sidecar config. Unfortunately did not spend enough time testing it the first time so sending a fixed version now.
This is now tested and included commented out test values. Once uncommented it creates a proper sidecarContainer now and depending if set volumeMounts will contain any volume mounts specified in extraVolumeMounts or sidecarVolumeMounts.
Unfortunately didn't find any nice way of merging the volume mounts without creating a separate value for it.
* Uncommented all the values for sidecar / helm template -f values.yaml .
* See sidecar config making it to the chart
* See volume mounts when extraVolumeMounts uncommented added to the sidecar VolumeMounts
```release-note …
```
> fix: SideCar config in chart

- pkg/cloudprovider/instance.go
- pkg/cloudprovider/instancetypes_test.go
Fixes # 
Only launch spot instance types that are cheaper than the cheapest on-demand instance type would have been.  This ensures that adding spot support to your provisioners won't increase your cluster cost.
*
```release-note
```
> feat: filter out more expensive spot instance types

- pkg/batcher/describeinstances.go
- pkg/batcher/describeinstances_test.go
Fixes # 
- Filters were not being passed through to the individual describeinstances calls
*
```release-note
```
> fix: describeinstancebatcher filter passing

- go.mod
- go.sum
- pkg/apis/v1alpha1/provider.go
- pkg/cloudprovider/launchtemplate.go
- pkg/cloudprovider/launchtemplate_test.go
- test/go.mod
- test/go.sum
Fixes #3302
- Round up when launching a node with block device mappings
- Include the blockDeviceMapping volumeSize requests in the hashing to notice a change in the volume size
```release-note
None
```
> fix: Round up when launching a node with block device mappings

- go.mod
- go.sum
- pkg/cloudprovider/instancetypes_test.go
- pkg/cloudprovider/launchtemplate_test.go
- pkg/cloudprovider/suite_test.go
- pkg/controllers/interruption/suite_test.go
- pkg/controllers/machinehydration/suite_test.go
- test/go.mod
- test/go.sum
Fixes # 
- Alter tracking bindings in testing
- Bindings are now returned from the ExpectProvisioned functions and are used to create the bindings to bind the pods to the nodes during scheduling
- Bump `karpenter-core` to latest
```release-note
None
```
> chore: Update `ExpectProvisioned` with new bindings tracking

- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/configmap.yaml
- charts/karpenter/values.yaml
- pkg/apis/settings/settings.go
- pkg/apis/settings/suite_test.go
- test/suites/integration/tags_test.go
- website/content/en/preview/concepts/settings.md
- website/content/en/preview/upgrade-guide.md
Fixes #3197 
- Fix bug where backslashes couldn't be in global tag keys
* `FOCUS=Tags make e2etests`
```release-note
None
```
> fix!: Fix bug where backslashes couldn't be in global tag keys

- charts/karpenter/README.md
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
Signed-off-by: Robert van Veelen <vanveele@users.noreply.github.com>
Fixes #3118 
Updates chart to configure custom listening ports. Useful when combined with `hostNetwork: true` in the case where an existing agent or daemonset is using these ports.
* Deployed chart using the custom values to resolve conflict
```release-note
Expose container ports as chart values
```
> feat: make ports configurable with chart values

- website/content/en/preview/concepts/node-templates.md
Fixes # 
Docs update for AWSNodeTemplate Status. The update are to include the subnet and security groups.
```release-note
```
> docs: Add status section for subnet and securityGroups

- go.mod
- go.sum
- hack/release/stable-pr.sh
- test/go.mod
- test/go.sum
Fixes # 
* Adds git add for `go.mod` and `go.sub` files so that they can be part of the opened PR, should have been part of https://github.com/aws/karpenter/pull/3366
* Updates values for v0.24.0
*
```release-note
```
> chore: Update go mod for v0.24.0 and also add the missing files to stable-pr.sh

- ADOPTERS.md
QuestDB is using Karpenter to power our service nodes for the managed version of our open source time-series database. Adding ourselves to the adopters list and happy to chat in our slack group about our experience
> docs: Adding QuestDB to the adopters list

- test/cmd/release-notification-listener/listener/listener.go
- test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml
- test/infrastructure/clusters/test-infra/release-notification-listener/release-notification-listener.yaml
Fixes # 
- Retrieve the account id that the test is running in to link to the right release queue. 
*
```release-note
```
> fix: retrieve account id for release queue

- pkg/cloudprovider/instancetypes.go
- pkg/cloudprovider/instancetypes_test.go
- pkg/cloudprovider/launchtemplate_test.go
Fixes # 
Currently, we will hit cache misses on startup for the DescribeInstanceTypes calls due to parallel calls to GetInstanceTypes. This results in a larger memory footprint (> 1GB) at startup that eventually reduces over time to around ~300MB. This ensures that the calls to the API are synchronous so we reduce our cache misses which means we are consistently sitting around 300MB throughout the pod's lifetime.
```release-note
None
```
> perf: Reduce multiple describe instances calls on start

- Makefile
- charts/karpenter/README.md
- go.mod
- go.sum
- pkg/cloudprovider/cloudprovider.go
- pkg/controllers/machine/garbagecollect/controller.go
- pkg/controllers/machine/garbagecollect/suite_test.go
- pkg/controllers/machine/link/controller.go
- test/go.mod
- test/go.sum
- test/suites/integration/backwards_compatability_test.go
- website/content/en/preview/concepts/instance-types.md
Fixes # 
Adds a garbage collection controller for cloudprovider Machines that have been launched but have not stored their providerID inside of their Machine owner (due to crashing or upgrade)
```release-note
None
```
> chore: Add garbage collection controller for Machines

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/instance.go
- pkg/controllers/machine/garbagecollect/controller.go
- pkg/controllers/machine/garbagecollect/suite_test.go
- pkg/controllers/machine/link/controller.go
- pkg/controllers/machine/link/suite_test.go
- test/suites/integration/backwards_compatability_test.go
Fixes # 
Add tagging of `karpenter.sh/managed-by` after attaching the existing instance to a machine to bring tagging parity with new machines that are launched
```release-note
None
```
> chore: Add Machine Link Tagging to Link Flow

- hack/release/release.sh
Fixes # 
https://github.com/aws/karpenter/issues/3414
- The `-dirty` suffix on the commit hash of releases is because the snapshot changes are still present when building the stable release. 
- Fix by Resetting all tracked files after the snapshot release process since it modifies the Chart.yaml and values.yaml of the charts it publishes. Snapshots do not PR chart changes back into the repo, so it is safe to reset all tracked files. 
```release-note
```
> fix: clean -dirty release on stable release commit hash

- pkg/cloudprovider/amifamily/bootstrap/eksbootstrap.go
- pkg/cloudprovider/launchtemplate_test.go
- pkg/cloudprovider/testdata/al2_no_mime_userdata_input.golden
- test/suites/integration/ami_test.go
- test/suites/integration/testdata/al2_no_mime_userdata_input.sh
- website/content/en/preview/concepts/node-templates.md
Fixes # 
- Allow for a standard shell script to be passed in and default to a shellscript mime format. Multi-part mime input will still work but should be the exception (if using more advanced cloud-init features) rather than the normal. 
Applied the following user-data and observed  a proper multi-part mime conversion and launched with the kubelet-config mutated to use 150 QPS.
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
name: default
spec:
securityGroupSelector:
karpenter.sh/discovery: wagnerbm-karpenter-dev-us-east-2
subnetSelector:
Name: test-ips
userData: |
#!/bin/bash
echo "$(jq '.kubeAPIQPS=150' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
```
Launch …
> feat: default user-data as a shellscript if no mime format is provided

- pkg/cloudprovider/instance.go
- pkg/cloudprovider/suite_test.go
- pkg/fake/ec2api.go
- pkg/providers/subnet/subnet.go
Fixes # 
https://github.com/aws/karpenter/issues/3364
https://github.com/aws/karpenter/issues/3380
- When a provisioner has two subnets within the same AZ, Karpenter selects the subnet with the most available IPs when creating the instance. However, the availableIPs comes from the EC2 DescribeSubnets API which is only synchronized every minute. This causes issues when multiple instances are launched with the stale available IPs such that the IP drops below 0. This PR introduces inflight IP tracking which approximates the IPs that will be used by the instance that is being launched by using the minimum maxPods value in the instance type options list. The inflight IP tracking is best effort and is resynchronized when the subnet cache is updated. The inflight IP tracking can …
> fix: track inflight ip usage for subnet selection between ec2 api resyncs

- website/content/en/preview/concepts/deprovisioning.md
- website/content/en/preview/upgrade-guide.md
Fixes # 
Remove do-not-evict preventing eviction when the Node is forcefully deleted through kubectl delete node or some other forceful deletion mechanism (like AWS interruption). do-not-evict should only be considered for Karpenter's voluntary disruption mechanisms (like emptiness/underutilization/consolidation, expiration, drift, etc.)
BREAKING CHANGE: Customers who are currently deleting nodes with pods that have do-not-evict annotations will no longer have nodes hang on draining for this, meaning that they can't use do-not-evict as a stop-gap
* Manual deletion of nodes with pods that have `karpenter.sh/do-not-evict`
```release-note
None
```
By submitting this pull …
> fix!: Stop blocking termination on `karpenter.sh/do-not-evict`

- pkg/fake/utils.go
- pkg/providers/securitygroup/securitygroup.go
Fixes # 
- Fixes a case on processing the security group selector to ec2 filter where a wildcard key was not transformed to a tag-key filter and instead was a full `tag:key -> value` filter which never returned security groups since wildcards are not supported within the Filter name, only Values.
* Fixed the ec2 mock for security groups to correctly evaluate wildcard filters. Ran the tests before the fix, observed failure, and after the fix, passed. 
```release-note
```
> fix: security group selector wildcard key

- pkg/test/awsnodetemplate.go
Fixes # 
* Test awsnodetemplates should only have one kay value pair  for  SecuirtyGroup and Subnets
```release-note
```
> fix: e2etests for node templates

- Makefile
- charts/karpenter/values.yaml
- test/manifests/pre-upgrade-setup.yaml
- test/manifests/setup.yaml
- website/content/en/preview/getting-started/getting-started-with-eksctl/scripts/step08-apply-helm-chart.sh
- website/content/en/preview/getting-started/migrating-from-cas/scripts/step09-generate-chart.sh
- website/content/en/preview/upgrade-guide.md
feat: Allow to deploy chart without any cpu limit
Fixes # 
* Removing the default cpu limit as can't be removed if used as dependency
* CPU limit should be removed on every deployment (not requests)
[#1](https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718)
[#2](https://www.howtogeek.com/devops/should-you-set-kubernetes-cpu-limits/)
[#3](https://home.robusta.dev/blog/stop-using-cpu-limits)
* Other examples / writings can be found around that, still possible for someone to add back the cpu limit
Can't remove this param by using the chart as a dependency.
Removing it here is the only way and follows some good practices.
```release-note
```
By …
> feat: Allow to deploy chart without any cpu limit

- Makefile
- charts/karpenter/README.md
- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
- hack/release/common.sh
- website/content/en/preview/upgrade-guide.md
This updates the `controller.image` value in the helm chart to be broken out to a map consisting of `controller.image.repository`, `controller.image.tag`, and `controller.image.digest`.
This enables users to provide just a repository override while leaving the tag and digest as the chart default. This is a very common approach that can be found in other widely adopted open source charts such as the [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L490) and [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/values.yaml#L235)
* `helm lint`
* `helm template` with test values
**Release …
> BREAKING CHANGE: Refactor controller image values

- ADOPTERS.md
Astradot is using Karpenter to power our entire backend on K8s. Adding ourselves to the adopters list.
> docs: Add Astradot to Adopters list

- hack/release/common.sh
Fixes # 
- Fix image signing args parsing in `make release`
```release-note
None
```
> Fix image signing args parsing in `make release`

- ADOPTERS.md
Target Australia uses Karpenter in our EKS clusters for the Online platform
* NA
```release-note
```
> docs: Add Target Australia to adopters list

- website/content/en/preview/concepts/pod-density.md
- website/content/en/v0.21.1/concepts/pod-density.md
- website/content/en/v0.22.1/concepts/pod-density.md
- website/content/en/v0.23.0/concepts/pod-density.md
- website/content/en/v0.24.0/concepts/pod-density.md
- website/content/en/v0.25.0/concepts/pod-density.md
Fixes # 
https://github.com/aws/karpenter/issues/3461
- Fix docs ref links to provisioner kubelet configuration
```release-note
```
> docs: fix pod density ref links

- test/suites/integration/ami_test.go
Fixes # 
Adds in e2e test for https://github.com/aws/karpenter/pull/3204
* `make apply`
* `FOCUS="ami selector" make e2etests`
```release-note
```
> test: add test for ami owners and name

- pkg/cloudprovider/instance.go
Fixes # 
- Spot Fleet generally uses lowerCamelCased allocation strategy names (i.e. priceCapacityOptimized), whereas EC2 Fleet generally uses kebab-cased allocation strategy names (i.e. price-capacity-optimized). Change to use the EC2 Fleet recommended way. 
* manual testing of spot nodes in a cluster
```release-note
```
> chore: fix pco allocation strategy for ec2 fleet

- pkg/cloudprovider/suite_test.go
- pkg/providers/subnet/subnet.go
Fixes #3512
- Fixes a nil dereference while updating the inflight IPs when CreateFleetOutput is nil due to CreateFleet error
```release-note
```
> fix: inflight IP tracking when CreateFleet returns an error

- charts/karpenter/README.md
- charts/karpenter/values.yaml
Fixes # 
Added the feature gate drift to the helm chart values in karpenter. It was added in karpenter-core but needed to be populated here. 
Did the command and saw it populated to the configmap.
```
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version v0.26.1 --namespace karpenter --create-namespace \
--set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${KARPENTER_IAM_ROLE_ARN} \
--set settings.featureGates.driftEnabled=true \
--set clusterName=${CLUSTER_NAME} \
--set clusterEndpoint=${CLUSTER_ENDPOINT} \
--set aws.defaultInstanceProfile=KarpenterNodeInstanceProfile${CLUSTER_NAME}
```
```release-note
```
By submitting this pull request, I confirm …
> feat: add featureGates.driftEnabled to helm chart values

- website/content/en/preview/concepts/node-templates.md
- website/content/en/preview/concepts/settings.md
- website/content/en/v0.24.0/concepts/node-templates.md
- website/content/en/v0.24.0/concepts/settings.md
- website/content/en/v0.25.0/concepts/node-templates.md
- website/content/en/v0.25.0/concepts/settings.md
- website/content/en/v0.26.1/concepts/node-templates.md
- website/content/en/v0.26.1/concepts/settings.md
Update docs for `aws.tags` (global tags).
New version of #3530. Applied changes retrospectively to previous versions' docs.
* n/a
```release-note
NONE
```
> docs: cleanup `aws.tags` and `specs.tags` docs

- test/suites/integration/daemonset_test.go
Fixes # 
- Fix daemonset preemption in testing
- PriorityClass should default to `PreemptLowerPriority` for this E2E testing
```release-note
```
> test: Fix daemonset preemption in testing to be `PreemptLowerPriority`

- website/content/en/preview/concepts/node-templates.md
Fixes #3528
Adds docs for default blockDeviceMappings
```release-note
NONE
```
> docs: Add default blockdevicemapping info

- charts/karpenter/README.md
- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
Fixes # 
This PR fixes the formatting of the deployment `topologySpreadConstraints` (`-` on a separate line). It also removes the undocumented behaviour of **ALWAYS** adding the default `labelSelector` even if one has been explicitly provided to the chart values.
I've also added the same label selector logic to the `afinity.podAffinity` & `affinity.podAntiAffinity` patterns. This has the benefit of removing the requirement to use the `tpl`, which can have unintended side effects if used incorrectly, and will remove the potential for an (unlikely) issue if multiple charts were deployed with the same instance label.
- Templated locally
```release-note
NONE
```
By submitting this pull request, …
> fix: Fixed chart topologySpreadConstraints formatting & logic

- pkg/providers/amifamily/bootstrap/bottlerocket.go
- pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
- pkg/providers/launchtemplate/suite_test.go
- test/suites/integration/kubelet_config_test.go
Fixes #3563 
Conversion to Bottlerocket settings and userData from `kubeletConfiguration` for `imageGCHighThresholdPercent` and `imageGCLowThresholdPercent` was broken prior to this change.
If you specified either in your `kubeletConfiguration`, a Bottlerocket instance would fail to connect to the cluster due to kubelet not starting
Relates to https://github.com/bottlerocket-os/bottlerocket/issues/2883
* Manual deployment of Bottlerocket instance
```release-note
None
```
> fix: Fix Bottlerocket Image GC conversion

- test/suites/integration/expiration_test.go
Fixes # 
- Fix test flake where the replacement node from the previous expiration test is not bootstrapped yet, so when we delete the node object for the cleanup stage of the test, it re-registers via eks bootstrap on node startup and hangs around for the next test where we fail the expectation of 1 node exists at the end.  
- Fix by waiting for the pod to go healthy on the replacement node in the first test.
- 
* `FOCUS=Expiration make e2etests`
```release-note
```
> test: fix expiration test flake

- charts/karpenter/README.md
- go.mod
- go.sum
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
- pkg/providers/launchtemplate/suite_test.go
- test/go.mod
- test/go.sum
- website/content/en/preview/concepts/instance-types.md
Fixes # 
Updates the instance type overhead calculation by:
1. Ensuring that there are no defaults for `systemReserved` values since AL2, Ubuntu, BR and other images (including kubelet itself) does not assume defaults for system reserved values
2. Updates the eviction threshold overhead calculation to ensure that `nodefs.available` is taken into account when determining the amount of available ephemeral storage that can be leveraged by pods
* Manual deployment and validation of allocatable on AL2, Ubuntu, and BR
```release-note
None
```
> fix: Update InstanceType Overhead Calculation

- hack/code/prices_gen.go
- pkg/context/context.go
- pkg/controllers/controllers.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/pricing/controller.go
- pkg/providers/pricing/pricing.go
- pkg/providers/pricing/suite_test.go
- pkg/test/environment.go
Fixes #3459
The pricingProvider contains async reconcile flows to hydrate its cache. This seems like a good fit for a standard Reconcile flow.
```release-note
```
> chore: Add singleton pricing controller

- hack/release/common.sh
- hack/release/release.sh
- hack/release/stable-pr.sh
- test/manifests/upgrade-suite.yaml
- tools/release-notification-listener/listener/message.go
- tools/release-notification-listener/listener/tekton.go
Fixes # 
Sets a static preUpgradeVersion for the release-listener and updates this static version any time there is a new release through the `stable-pr.sh`
* Manual testing of script changes in local environment
```release-note
```
> test: Fix pre-upgrade release tag pinning

- charts/karpenter/templates/clusterrole-core.yaml
Fixes # 
https://github.com/aws/karpenter/issues/3673
- Removes webhook update permission for `defaulting.webhook.karpenter.sh` which was removed a while back
*
```release-note
```
> chore: remove old webhook permission

- pkg/fake/ec2api.go
- pkg/fake/eksapi.go
- pkg/fake/sqsapi.go
- pkg/fake/types.go
Fixes # 
Calling any `MockedFunction` with `WithDefault()` simultaneously could result in a race where the the `defaultOutput` value would be used for both calls to the function by the time Invoke was called. This is because using the result from the `WithDefault` function wasn't an atomic operation with the `Invoke` function. 
This PR removes the `WithDefault()` call and adjust `Invoke` so that it takes in the `input` value as well as a `defaultTransformer` which transforms the input into some expected output
```release-note
None
```
> test: Fix issue where `MockedFunction` results would leak into other calls

- website/content/en/preview/faq.md
Update the supported kubernetes versions from FAQ notes
Fixes # 
FAQ notes still mention the supported kubernetes versions are 1.20-1.24, while upgrade notes mention 1.20 support was dropped from 0.22.
* n/a
```release-note
```
> docs: update supported versions from FAQ

- pkg/controllers/machine/garbagecollect/controller.go
- pkg/controllers/machine/garbagecollect/suite_test.go
- pkg/controllers/machine/link/controller.go
Fixes # 
Reduce garbage collection eventual consistency timeout. This is meant to make the controllers quicker to react to overlaunching that might occur during the time that we are performing an upgrade or when we the Karpenter controllers crash. When this is the case, the garbage collection mechanism should ensure that it cleans up the Machines that it creates relatively quickly while the new capacity is launched.
* Manual testing
```release-note
```
> chore: Reduce garbage collection eventual consistency timeout

- pkg/providers/amifamily/al2.go
- website/content/en/preview/concepts/node-templates.md
Fixes # 
https://github.com/aws/karpenter/issues/3217
- Docs about AL2 arm64 GPU AMI being unsupported
- Changed SSM construction to not ignore architecture so that the propagated error is an SSM lookup error rather than an arch mismatch on launch.
*
```release-note
```
> chore: better error for AL2 arm64 gpu ami not existing

- pkg/providers/instance/instance.go
Fixes # 
Log the selected instance type capacity based on the GetInstanceTypes() cloudprovider API. This helps users to discover the capacity that Karpenter expected to launch through the logs which should ease some of the issues with expected ephemeral-storage like mentioned in #3676
Logs for launched capacity now look like
```console
2023-04-04T16:28:07.644Z        INFO    controller.provisioner.cloudprovider    launched new instance   {"commit": "ef5c076", "provisioner": "default", "id": "i-0e9db85152cbdb3bd", "hostname": "ip-192-168-27-76.us-west-2.compute.internal", "instance-type": "c6a.4xlarge", "zone": "us-west-2b", "capacity-type": "on-demand", "capacity": {"cpu":"16","ephemeral-storage":"20Gi","memory":"30310Mi","pods":"234"}}
2023-04-04T16:44:43.324Z        INFO …
```
> chore: Log selected instance capacity on launch

- charts/karpenter/values.yaml
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.27.0/troubleshooting.md
Fixes # 
Managing the Provisioners and AWSNodeTemplate as extraObjects generate a race condition since the karpenter pods are not ready to handle calls.
`Error: Internal error occurred: failed calling webhook "defaulting.webhook.karpenter.k8s.aws": failed to call webhook: Post "[https://karpenter.karpenter.svc:443/?timeout=10s](https://karpenter.karpenter.svc/?timeout=10s)": no endpoints available for service "karpenter"`
Adding the helm hooks annotation has fixed this issue on 100% of the tests.
Not sure if you want to document this behavior elsewhere.
* Deployed on 2 production clusters
```release-note
``` …
> docs: Enrich examples on how to handle AWSNodeTemplates and Provisioners inside the chart

- website/content/en/preview/troubleshooting.md
Fixes # 
Add volume mount troubleshooting for volume limits
Relates to https://github.com/aws/karpenter-core/issues/260
* Manually viewed docs
```release-note
None
```
> docs: Add volume mount troubleshooting for volume limits

- pkg/batcher/describeinstances.go
- pkg/batcher/describeinstances_test.go
- pkg/batcher/terminateinstances.go
- pkg/batcher/terminateinstances_test.go
Fixes # 
Fixes a bug where passing the same instance ID in two separate calls in the same batch would result in an empty output which would throw off the callers to the EC2 API and result in panics. This occurred because we were only looking at the last index that represented an instance ID rather than looking at ALL the indexes that request that instance ID
```release-note
None
```
> fix: Fix Duplicate InstanceID Batching Bug

- hack/code/instancetype_testdata_gen.go
- hack/codegen.sh
- pkg/fake/zz_generated.describe_instance_types.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
Fixes #3696
Fixes a bug in max pods calculations
Unit + Manually. In flight checks no longer complain.
Before
```
karpenter-f79844559-xpxpd controller 2023-04-06T17:58:37.241Z	INFO	controller.provisioner.cloudprovider	launched new instance	{"commit": "982c35f", "provisioner": "default", "id": "i-0bd719348e7171937", "hostname": "ip-192-168-172-64.us-west-2.compute.internal", "instance-type": "m6idn.32xlarge", "zone": "us-west-2a", "capacity-type": "on-demand"}
karpenter-f79844559-xpxpd controller 2023-04-06T18:06:23.208Z	DEBUG	controller.aws	deleted launch template	{"commit": "982c35f"}
karpenter-f79844559-xpxpd controller 2023-04-06T18:08:37.249Z	INFO	controller.inflightchecks	Inflight check failed for node, Expected 688 of resource pods, …
```
> fix: Correctly calculate max pods when multiple network cards are available

- test/pkg/environment/common/setup.go
- test/suites/integration/expiration_test.go
Fixes # 
* `FOCUS=Expiration make e2etests`
```release-note
```
> test: Fix node leaking through expiration tests

- website/content/en/preview/getting-started/migrating-from-cas/scripts/step05-controller-iam.sh
Fixes #3712
Permissions from the documentation do not work if instances use some value of the `Name` tag that does not contain the word `karpenter`. At the same time, Karpenter adds to all nodes a tag with the name of the provisioner. It seems quite logical to use this tag.
We use this permissions and it works well in production
```release-note
```
> docs: Change AWS IAM permissions example

- cmd/controller/main.go
- go.mod
- go.sum
- hack/docs/instancetypes_gen_docs.go
- hack/docs/metrics_gen_docs.go
- pkg/controllers/controllers.go
- pkg/operator/operator.go
- pkg/operator/suite_test.go
- test/go.mod
- test/go.sum
- website/content/en/preview/concepts/instance-types.md
- website/content/en/preview/concepts/metrics.md
Fixes # 
Removes the dependency on `cloudprovider.Context` so that we can pull this concept out of the `types.go` file in `karpenter-core` and stop relying on this concept. Rather, wrap the current `core.Operator` and create a bigger version of the operator that has all the core operator concepts + the AWS cloudprovider operator concepts.
This PR is a buddy change for https://github.com/aws/karpenter-core/pull/286
```release-note
```
> chore: Wrap `operator` and remove deps on `cloudprovider.Context`

- go.mod
- go.sum
- hack/docs/instancetypes_gen_docs.go
- website/content/en/preview/concepts/instance-types.md
Fixes # 
- Fix `make docgen` by using a fake manager
- Dedupes entries in the instance_types_gen doc
* `make docgen` with no KUBECONFIG
* Validated that no duplicates were coming from instance types generation script
```release-note
```
> chore: Fix `make docgen` by using a fake manager

- test/pkg/debug/events.go
- test/pkg/debug/machine.go
- test/pkg/debug/monitor.go
- test/pkg/debug/node.go
- test/pkg/debug/pod.go
- test/pkg/debug/setup.go
- test/pkg/environment/aws/environment.go
- test/pkg/environment/common/environment.go
- test/pkg/environment/common/setup.go
- test/suites/chaos/suite_test.go
- test/suites/consolidation/suite_test.go
- test/suites/drift/suite_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/suite_test.go
- test/suites/interruption/suite_test.go
- test/suites/ipv6/suite_test.go
- test/suites/utilization/suite_test.go
Fixes # 
Debugging logging is moved out of the main `environment` package to create separation between the debug logging portion of the package code and the expectation portion of the code. node/pod watchers were transferred to controller-runtime due to increased complexity in adding a machine watcher. Adding a machine watcher using the informer pattern would have required using a dynamic informer factory. Instead, controller-runtime patterns are familiar and support the code quality in the future.
1. Moves test debugging to a separate package
2. Migrates node/pod watchers to use controller-runtime
3. Adds the machine watcher to stage out the Machine testing 
* `FOCUS=KubeletConfiguration make e2etests` …
> test: Move test debugging to separate package

- pkg/providers/amifamily/ami.go
Fixes # 
- When user specify amiSelector to `aws::name: "*"` karpenter logs will become filled with all the AMI IDs that are discovered by ec2.
- `2023-04-14T16:56:32.980Z	DEBUG	controller.node	discovered images	{"commit": "b4f1d60-dirty", "node": "ip-192-168-112-220.us-west-2.compute.internal", "ids": "ami-0789036840ebc8c25, ami-0123d5874c000c92e, ami-01e2c4303a7750e9f, ami-0438e722aaf2037af, ami-0696f65e1894f23c1, ami-06d0b3b36f79ffd17, ami-0386da4fafcdb3286, ami-0f4af98dc9062fc55, ami-055613971ee89acd7, ami-06055064d6004521f, ami-065a7f1c72ec3164b, ami-05692094f77d6c828, ami-0fe99b168ad207a9e, ami-07d7dd2821eadc9b7, ami-093107ba06ec290c8, ami-019f57bd424d44fd3, ami-01fc410639698b4ca, ami-0ccdef9b637fc187c, ami-0e8c547337376a477, ami-0d44c92d6423bd06b, …
> chore: Concatenate AMI IDs in logs

- website/content/en/preview/concepts/node-templates.md
- website/content/en/v0.26.1/concepts/node-templates.md
- website/content/en/v0.27.2/concepts/node-templates.md
Fixes # 
Discovering AMIs by name was added in v0.26.0, but the docs don't clarify that you can use wildcards to discover these AMIs.
```release-note
```
> docs: clarify that aminame can use wildcard

- pkg/apis/settings/settings.go
- pkg/apis/settings/suite_test.go
- pkg/apis/v1alpha1/awsnodetemplate_validation.go
- pkg/apis/v1alpha1/register.go
- pkg/apis/v1alpha1/suite_test.go
- pkg/providers/instance/instance.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/launchtemplate/suite_test.go
- test/suites/integration/webhook_test.go
- website/content/en/preview/concepts/node-templates.md
- website/content/en/preview/upgrade-guide.md
Fixes # 
Adds validation to the AWSNodeTemplate that keys provided in the `spec.tags` section are not within a "restricted set" of tags for Karpenter that Karpenter and other automation use for auto-discovery.
BREAKING CHANGE: Users who use the following restricted tag key set in either the AWSNodeTemplate `spec.tags` or the `karpenter-global-settings` `aws.tags` will experience validation errors 
1. `kubernetes.io/cluster/<cluster-name>`
2. `karpenter.sh/provisioner-name`
3. `karpenter.sh/managed-by`
* `FOCUS=Webhooks make e2etests`
```release-note
```
> BREAKING CHANGE: Add tag key checking to `AWSNodeTemplate` validation

- test/manifests/upgrade-crds.yaml
- test/manifests/upgrade-suite.yaml
Fixes # 
The `kubectl replace` directive does not work when the object doesn't already exist. Anyways, we should not have to specify new CRDs when we add them. This change applies _every_ CRD from the pkg/apis/crds directory
```release-note
```
> test: Fix upgrading CRDS from older version

- test/suites/integration/termination_test.go
- test/suites/machine/garbage_collection_test.go
- test/suites/machine/machine_test.go
Fixes # 
- Add additional machine e2e for node finalizer compatibility
- Changes "shutting-down" check to an eventual consistency check
* `FOCUS=Machine make e2etests`
```release-note
None
```
> chore: Add additional machine e2e for node finalizer compatability

- pkg/cloudprovider/cloudprovider.go
- pkg/controllers/machine/link/controller.go
- pkg/controllers/machine/link/suite_test.go
- pkg/providers/instance/instance.go
- test/suites/machine/link_test.go
Fixes # 
Handles linking nodes to machines that were linked to be managed by karpenter by just using the `karpenter.sh/provisioner-name` label on the nodes. These nodes would not have the `karpenter.sh/provisioner-name` tag attached to the instance so the only way to discover that they are managed by Karpenter is to look at the node labels.
* `FOCUS=Machine make e2etests`
```release-note
None
```
> chore: Handle re-owned nodes linking

- hack/docs/metrics_gen_docs.go
- pkg/providers/pricing/metrics.go
- pkg/providers/pricing/pricing.go
- pkg/providers/pricing/suite_test.go
- website/content/en/preview/concepts/metrics.md
Fixes #3614
Adds a new metric `karpenter_cloudprovider_instance_price_estimate` that reflects the currently known on-demand and spot prices for a given instance type in a given region and availability zone.
This metric is intended to be used when trying to calculate cost of an EC2 node.
Future improvements would be to add a `vcpu` and `memory` label to this metric which would reflect the CPU and memory of the given node to make it easier to calculate a CPU cost and memory cost per Pod.
* `make test`
```release-note
```
> feat: adds new karpenter_cloudprovider_instance_price_estimate prometheus metric

- charts/karpenter/README.md
- charts/karpenter/templates/extra-manifests.yaml
- charts/karpenter/values.yaml
- website/content/en/preview/concepts/metrics.md
- website/content/en/preview/troubleshooting.md
- website/content/en/preview/upgrade-guide.md
Fixes # 
Reverts #3370 which allowed the ability to add extra manifests into the helm chart. This is being removed from the Karpenter project for a few reasons:
1. It couples the install of Karpenter with the layer that manages and controls the nodes. Since Provisioners own Machines, Karpenter cannot be uninstalled without carefully tearing down the Provisioners before uninstalling the Provisioners and the Karpenter deployment
2. The `extraObjects` field did not work for new installs since the webhooks were not up before the objects were applied. This meant that `helm installs` would often fail for users that were installing their manifests in this way.
Since Helm offers no in-chart dependency mechanisms (beyond hooks, which do not work in this case), the Karpenter …
> BREAKING CHANGE: Remove `.Values.extraObjects`

- test/hack/cleanup/cleanup.sh
- test/manifests/cleanup.yaml
Fixes #
Delete launch templates associated with the cluster during the cleanup step on the E2E test run. This ensures that we don't leak launch templates in our account when tearing down the cluster
* Running the command manually
```release-note
None
```
> test: E2ETesting Delete launch templates in cleanup step

- test/manifests/cleanup.yaml
Fixes # 
`xargs` shouldn't fail when receiving no output piped through to it. This adds the `-r` option which ignores empty input.
* Manual deploy to Tekton
```release-note
```
> test: Ignore empty output when running xargs

- website/content/en/preview/concepts/node-templates.md
- website/content/en/v0.26.1/concepts/node-templates.md
- website/content/en/v0.27.3/concepts/node-templates.md
The AMI Selector as shown on the [merged pr](https://github.com/aws/karpenter/pull/3204) uses the `aws::` prefixes on the tags. 
We tested using the AMISelector without the `aws::` prefix and it breaks. So thought of updating the docs to reflect this.
Update AWSNodeTemplate docs for ami selectors to reflect the `aws::` prefix requirements.
> docs: Update AWSNodeTemplate docs for ami selectors

- test/pkg/environment/aws/setup.go
- test/pkg/environment/common/expectations.go
- test/suites/integration/scheduling_test.go
Fixes # 
Create a `ExpectSettingsReplaced` function that will completely replace all of the data in the `karpenter-global-settings`. This is used to retain the settings from before the test run due to settings that might be updated throughout the testing.
```release-note
```
> test: Fix settings override logic in AfterEach

- charts/karpenter/templates/aggregate-clusterrole.yaml
Fixes # 
- Add `machines` permission to the aggregate clusterRole that is automatically assigned to the `cluster-admin`
* `make apply`
```release-note
```
> chore: Add machine permission to aggregate clusterrole

- pkg/apis/v1alpha1/register.go
- pkg/apis/v1alpha1/suite_test.go
Fixes # 
The PR that validates the tags on the `v1alpha1.AWSNodeTemplate` (https://github.com/aws/karpenter/pull/3784) contains checking against tags based on regex. This regex needs all the special characters escaped. The current state will match more tags than it should.
* `FOCUS=Webhooks make e2etests`
```release-note
```
> chore: Fix escaping regex special characters

- hack/docs/instancetypes_gen_docs.go
- pkg/apis/v1alpha1/register.go
- pkg/apis/v1alpha5/suite_test.go
- pkg/controllers/nodetemplate/suite_test.go
- pkg/providers/amifamily/al2.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/bottlerocket.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
- test/suites/integration/scheduling_test.go
- website/content/en/preview/concepts/instance-types.md
Fixes # 
Changes the instance type labels to more closely align with the `describe-instance-types` API response for EC2. It also changes the AMI selection logic to use the `DoesNotExist` and `Exist` requirement rather than selecting AMIs on very specific labels by manufacturer name
* `FOCUS=Scheduling make e2etests`
```release-note
```
> chore: Restore GPU labels and use DoesNotExist

- website/content/en/preview/upgrade-guide.md
Fixes # 
Update the "Custom Resource Definition (CRD) Upgrades" in the "Upgrade Guide" to include Machines. This change also fixes some formatting in the upgrade section of "Upgrading to v0.28.0+" and references the "CRD Upgrade" section 
* Manual Viewing of Docs
```release-note
None
```
> docs: Add upgrade note on CRDs for machines

- pkg/providers/amifamily/bootstrap/eksbootstrap.go
- pkg/providers/launchtemplate/testdata/al2_userdata_merged.golden
- pkg/providers/launchtemplate/testdata/al2_userdata_unmerged.golden
- test/suites/integration/kubelet_config_test.go
Fixes #3818
Fixes a bug in the Ubuntu AmiFamily where any `kubeletConfiguration` that generated kubelet arguments with the `<` symbol would not be properly parsed by the AMIFamily's bootstrap script, thus causing the Node never to join. This PR fixes this bug by wrapping all string values in the kubelet arguments with double-quotes so that these values will be treated as strings when parsed.
* `FOCUS=KubeletConfiguration make e2etests`
```release-note
```
> fix: Stringify the kubeletExtraArgs values for AL2/Ubuntu

- test/pkg/environment/common/expectations.go
- test/suites/machine/machine_test.go
Fixes # 
Fix re-getting the StatusConditions when checking whether the Machine is Ready at the end of some E2E tests
* `FOCUS=Machine make e2etests`
```release-note
```
> test: Fix missed Eventually() checks in happiness check

- pkg/providers/amifamily/ami.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/providers/subnet/subnet.go
- pkg/providers/subnet/suite_test.go
Fixes # 
The current `ChangeMonitor` for subnets, security groups, and images only considers __one set__ of selectors to get the resolved values. This means that, if there are multiple `AWSNodeTemplates`, this ChangeMonitor value will be continually changing and will continue to print the logs message "discovered..." so long as the value associated with the key keeps changing. 
Rather than using a singleton key value, the value should be keyed based on the `AWSNodeTemplate` name. This will allow us to print different values once (every 24h) and then scope that value to its associated `AWSNodeTemplate`
```console
2023-04-25T16:35:37.670Z        DEBUG   controller.awsnodetemplate      discovered subnets      {"commit": "ce030bd", "awsnodetemplate": "default", "subnets": …
```
> chore: Fix change monitor changing on different node templates

- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/metrics.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/pricing/suite_test.go
- pkg/test/environment.go
- website/content/en/preview/concepts/metrics.md
This adds `karpenter_cloudprovider_instance_type_cpu_cores` and `karpenter_cloudprovider_instance_type_memory_bytes` metrics for each instance type that Karpenter understands.
These new metrics can be combined with the `karpenter_cloudprovider_instance_price_estimate` metric to give you a price per VCPU and price per 1 GiB of memory to help calculate your hourly cost per Pod.
* `make test`
```release-note
```
> feat: Adds vcpu and memory metrics per instance type

- charts/karpenter/values.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Fixes #3867
Buddy PR to https://github.com/aws/karpenter-core/pull/334
```release-note
```
> feat: Include knative webhooks in readiness probes

- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.26.1/getting-started/getting-started-with-eksctl/cloudformation.yaml
- website/content/en/v0.27.3/getting-started/getting-started-with-karpenter/cloudformation.yaml
Enables best practice of serverside encryption for SQS queues
```
aws cloudformation deploy --stack-name "Karpenter-${CLUSTER_NAME}" --template-file /Users/etarn/go/src/github.com/aws/karpenter/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml --capabilities CAPABILITY_NAMED_IAM --parameter-overrides "ClusterName=${CLUSTER_NAME}"
```
Using AWS FIS to force an interruption.
```
karpenter-5f898d848c-vxhbr controller 2023-05-12T17:12:54.720Z	DEBUG	controller.interruption	removing offering from offerings	{"commit": "6ebe0b7", "queue": "dev", "messageKind": "SpotInterruptionKind", "machine": "default-gcvxv", "action": "CordonAndDrain", "node": "ip-192-168-104-43.us-west-2.compute.internal", "reason": …
```
> chore: Add SQS Server Side Encryption to interruption queue in getting started guide

- tools/release-notification-listener/Dockerfile
Fixes # 
- Bump `tektoncli` from v0.28.0 to v0.31.0, due to cluster update from 1.21 to 1.24, which required updates tekton crds.  
*
```release-note
```
> test: Bump Tektoncli for e2etests

- test/pkg/environment/common/expectations.go
- test/suites/machine/link_test.go
Fixes # 
This PR fixes test flakiness caused by not properly polling for new pods to be completely spun up and the webhook endpoint running in the container. This was causing issues since our polling would assume that the new containers were ready when they were not completely up. This meant that we would have no service endpoints available sometimes which would cause issues with applying provisioners and nodeTemplates when the test runs started.
This change performs a deployment update and rollout through the `kubectl.kubernetes.io/restartedAt` annotation similar to `kubectl rollout restart`.
* Snapshot runs of E2E tests
```release-note
None
```
By submitting this pull …
> test: Properly wait for a full pod restart on E2Es

- test/suites/drift/suite_test.go
- test/suites/integration/ami_test.go
Fixes # 
- The newer AMI contains some security updates that would be good to include for our testing
* Manually tested
```release-note
```
> fix: Update E2E old drift AMI

- pkg/apis/crds/karpenter.k8s.aws_awsnodetemplates.yaml
- pkg/apis/v1alpha1/awsnodetemplate.go
- pkg/controllers/nodetemplate/controller.go
- pkg/controllers/nodetemplate/suite_test.go
- pkg/fake/ec2api.go
- pkg/providers/amifamily/resolver.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/providers/securitygroup/suite_test.go
- website/content/en/preview/concepts/node-templates.md
Fixes # 
- Added to name for SecurityGroups in the `AWSNodeTemplate.status `
* Manually tested
```release-note
```
> feat: Add SecurityGroup Name to AWSNodeTemplate Status

- pkg/controllers/nodetemplate/suite_test.go
- pkg/providers/subnet/suite_test.go
Fixes # 
- Improving the `nodetempate.status` testing for subnets by validating the whole API surface 
* Unite tests
```release-note
```
> test: Cleanup Subnet tests

- Makefile
- test/manifests/run-test.yaml
Fixes # 
Currently, our tests run scoped based off of the `--ginkgo.focus` parameter. This works across test suites and uses regex to determine which suites to select. While this works for _most_ suites, we should scope the suite to a particularly directory so that we make sure that Regex doesn't leak between test suites
* `make e2etests` with `FOCUS=Integretion`
```release-note
None
```
> test: Run the tests scoped to the test suite with `TEST_SUITE`

- test/pkg/environment/aws/expectations.go
- test/suites/machine/garbage_collection_test.go
- test/suites/machine/link_test.go
Fixes # 
- For better security posture, our e2etests need to enable IMDSv2 on all instance that are launched
* Ran e2etests 
```release-note
```
> fix: Enable IMDSv2

- Makefile
- test/manifests/setup.yaml
- test/suites/scale/deprovisioning_test.go
- test/suites/scale/provisioning_test.go
Fixes # 
1. Updates the `SpecTimeouts` for each of the shorter tests since the current `SpecTimeouts` were too constrained
2. Updates the `--grace-period` for Ginkgo so that clean-ups on `SpecTimeouts` have enough time to clean-up after a failure
3. Updates the E2E test suite manifests to use a different instance type when running scale testing
* Tekton runs of Scale Testing
```release-note
None
```
> test: Fix failures in Scale Testing Suite

- pkg/controllers/machine/garbagecollection/controller.go
- pkg/controllers/machine/link/controller.go
Fixes # 
Prior to this change, it was possible for a call to `ec2.DescribeInstances` to take a long time. Machines were listed prior to this API call, which meant that if this `DescribeInstances` call took a long time, that the instances returned from the EC2 API would be more updated than the Machines that were retrieved from the List. To solve this, we should reverse the order of execution. This way, if the `DescribeInstances` takes longer, we will still get the Machines at the end of the call.
With this new order of execution, even if the Machine LIST takes a lot longer and the EC2 data is old, Machines should be a superset of the instances data, meaning that we will only ever delete _less_ instances than we should, not _more_.
* `make …
> fix: Ensure that our cluster Machine list is more updated than our CloudProvider Machine list

- test/manifests/run-test.yaml
- test/pkg/environment/aws/metrics.go
- test/suites/scale/deprovisioning_test.go
- test/suites/scale/provisioning_test.go
Fixes # 
- adds in more test dimensions 
- reduces the git-ref that's used to only be commits
* `TEST_SUITE=scale ENABLE_CLOUDWATCH=true make e2etests`
```release-note
```
> test: add in more scale test dimensions

- test/pkg/environment/aws/metrics.go
- test/pkg/environment/common/environment.go
- test/suites/scale/deprovisioning_test.go
- test/suites/scale/provisioning_test.go
Fixes # 
- With a missing environment variable, the context value would get inputted as an empty string, which isn't a valid cloudwatch dimension string.
* `unset GIT_REF`
* `TEST_SUITE=scale ENABLE_CLOUDWATCH=true FOCUS="Emptiness" make e2etests`
```release-note
```
> test: fix cloudwatch importing with missing env variable

- pkg/controllers/machine/link/controller.go
- pkg/controllers/machine/link/suite_test.go
Fixes # 
The Machine Linker Controller shouldn't delete instances that have the `v1alpha5.ProvisionerName` label but do not have Provisioners present on the cluster. These instances should either be assumed to be actively deleting (in which case a delete is unnecessary) or be assumed to have been orphaned when the provisioner is deleted. If the Node/Instance was orphaned when the Provisioner was deleted, we shouldn't take any action on the instance.
```release-note
None
```
> fix: Don't Delete Instances if Orphaned

- test/suites/scale/deprovisioning_test.go
- test/suites/scale/provisioning_test.go
Fixes # 
- reduce the instance size used for scale tests since prefix delegation is enabled. 
* `TEST_SUITE=scale ENABLE_CLOUDWATCH=true FOCUS="Emptiness" make e2etests` and saw a successful test. Other tests use the same shared spec.
```release-note
```
> test: reduce scale test instance size

- go.mod
- go.sum
- test/go.mod
- test/go.sum
Fixes # 
Bumps the version of `karpenter-core` to the latest to be up-to-date with the released version of `karpenter-core` `v0.28.0-rc.2`
```release-note
None
```
> Bump karpenter-core to latest for `v0.28.0-rc.2`

- test/manifests/pre-upgrade-setup.yaml
- test/manifests/setup.yaml
Fixes # 
Bumps up the instance size used for upgrade tests to fix resource requirement failures for having two Karpenter pods colocated on a node
* Has to test through e2e triggered here
```release-note
```
> test: adjust upgrade instance size

- test/infrastructure/clusters/test-infra/karpenter-tests/scripts/cleanup.sh
- test/infrastructure/clusters/test-infra/karpenter-tests/sweeper-cron.yaml
Fixes # 
Fixes the `cleanup.sh` failures occurring from empty responses
`grep` will return an exit code `1` if there are no lines matching the search filter. In this case, we should not cause an exit code `1`; else, this will cause the entire script to fail due to `set -o pipefail` and `set -e`
Adds metrics to the sweeper so that we know how many objects are cleaned up on each run
* Script run on the CI test cluster
```release-note
None
```
> test: Fix `cleanup.sh` script failures from empty responses

- test/infrastructure/clusters/test-infra/karpenter-tests/kustomization.yaml
- test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-scale-trigger-cron.yaml
- test/infrastructure/clusters/test-infra/karpenter-tests/pipeline-trigger-cron.yaml
- test/infrastructure/clusters/test-infra/karpenter-tests/scripts/pipeline-scale-trigger.sh
- test/infrastructure/clusters/test-infra/karpenter-tests/test-trigger-sa.yaml
Fixes # 
Adds the periodic trigger for scale testing to trigger a run daily. This frequency can be reduced in the long-run once more metrics are created and the stability of scale testing is ensured.
Fixes a misspelling with the `pipeline-trigger` cron
* Manual Deployment to CI cluster
```release-note
```
> test: Add periodic trigger for scale testing

- test/pkg/environment/common/setup.go
Fixes # 
- Getting 504s on deletecollection calls for the finalizable objects. Separating them out to reduce the chance of throttling since these are called in rapid succession. 
```release-note
```
> test: separate cleanup objects for finalizable and non finalizable objects

- charts/karpenter/templates/poddisruptionbudget.yaml
Fixes #3980 
By running `helm template -s templates/poddisruptionbudget.yaml .` into the `charts/karpenter/` folder.
Result is:
```
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
name: karpenter
namespace: karpenter
labels:
helm.sh/chart: karpenter-0.27.5
app.kubernetes.io/name: karpenter
app.kubernetes.io/instance: release-name
app.kubernetes.io/version: "0.27.5"
app.kubernetes.io/managed-by: Helm
spec:
maxUnavailable: 1
selector:
matchLabels:
app.kubernetes.io/name: karpenter
app.kubernetes.io/instance: release-name
```
```release-note
NONE
```
> fix: add labels on PodDisruptionBudget

- .github/actions/install-deps/action.yaml
- .github/workflows/ci-test.yaml
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Fixes # 
- Fixes a caching issues on `.github/actions/install-deps` where the cache wouldn't be differentiated on the K8s Version, which meant that we would use a single K8s version for testing
- Fixes a compatibility issue with a K8s test on 1.27
```release-note
```
> fix: Edit the cache for `install-deps` to use K8s version

- examples/provisioner/launchtemplates/al2-custom-ami.yaml
- examples/provisioner/launchtemplates/al2-custom-userdata.yaml
- examples/provisioner/launchtemplates/br-custom-userdata.yaml
- examples/provisioner/launchtemplates/custom-family.yaml
- website/content/en/preview/concepts/provisioners.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step12-add-provisioner.sh
Fixes # 
- Update docs to introduce consolidation on the getting started guide for new users
* Manually tested
```release-note
```
> docs: Update docs to switch ttlSecondsAfterEmpty to consolidation

- test/pkg/environment/aws/metrics.go
- test/suites/scale/deprovisioning_test.go
- test/suites/scale/provisioning_test.go
Fixes # 
Fixes an issue where labels were being aggregated oddly in the grafana dashboard, and failures when non-nitro instances were picked.
* `TEST_SUITE=scale ENABLE_CLOUDWATCH=true make e2etests`
```release-note
```
> test: fix test labels and testing failures

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/upgrade-guide.md
Fixes # 
- Fixes a few places missed in the /docs update where github relrefs should have been replaced with the static latest version. This is automated in the release process, but must have made an update to the script I was using to do the release updates locally in these files. 
* 
```release-note
```
> docs: fix github-relref for /docs

- pkg/providers/amifamily/bootstrap/bottlerocket.go
- pkg/providers/launchtemplate/testdata/br_userdata_input.golden
- pkg/providers/launchtemplate/testdata/br_userdata_merged.golden
- website/content/en/docs/concepts/node-templates.md
- website/content/en/preview/concepts/node-templates.md
- website/content/en/v0.27/concepts/node-templates.md
Fixes # 
https://github.com/aws/karpenter/issues/4013
- Fixes Node Labels merging in Bottlerocket's user-data.
- Fixes invalid toml in docs
* tested manually by:
* adding labels that should be overridden like `karpenter.sh/capacity-type` and observed it being properly overridden. 
* adding labels that should not be overridden and observing them properly merged
* make test
- [ x Yes, PR includes docs updates
```release-note
```
> fix bottlerocket node-labels merge in user-data

- Makefile
- test/infrastructure/clusters/test-infra/karpenter-tests/scripts/pipeline-scale-trigger.sh
- test/manifests/ipv6-suite.yaml
- test/manifests/run-test.yaml
- test/manifests/suite.yaml
- test/manifests/upgrade-suite.yaml
Fixes # 
Add `TEST_TIMEOUT` to `Makefile` so that we can pass through test timeouts for E2E tests that need longer timeouts in "go test"
*
```release-note
```
> test: Add `TEST_TIMEOUT` for scale test run

- website/content/en/docs/troubleshooting.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.26/troubleshooting.md
- website/content/en/v0.27/troubleshooting.md
Fixes # 
Update documentation to include troubleshooting information on what to do if you receive `CreateContainerSandbox` errors during IP address assignment to pods
This points PRs like #3380 toward troubleshooting guidance around IP exhaustion when IP address constrained, either due to pod density or to subnet constraints.
* Manual view of Docs
```release-note
```
> docs: Troubleshooting Docs for IP Address Exhaustion

- test/suites/scale/provisioning_test.go
- test/suites/scale/suite_test.go
Fixes # 
Disable Prefix delegation on the node-dense scale test to reduce the number of allocated IPs that are given to ENIs when an ENI is brought up by the CNI.
```release-note
```
> test: Disable prefix delegation

- .github/actions/e2e/create-cluster/action.yaml
Fixes # 
A `yq` command had an additional `.` in the command that was causing failures in the `create-cluster` action
* Manual run of the script
```release-note
```
> test: Fix syntax error in GHA `yq` command

- test/suites/scale/deprovisioning_test.go
Fixes # 
- Fix node template reference for drift `AWSNodeTemplate`
* `FOCUS="should run consolidation, emptiness, expiration, and drift simultaneously" make e2etests`
```release-note
None
```
> test: Fix node template reference for drift `AWSNodeTemplate`

- .github/actions/e2e/slack/notify/action.yaml
- hack/release/common.sh
Fixes # 
Remove `notifyRelease` to disable Tekton runs on merge and on snapshot
* Manual validation
```release-note
None
```
> test: Disable notify release to disable Tekton runs on Merge and Snapshot

- test/suites/scale/provisioning_test.go
Fixes # 
the pod dense and node dense tests were labeled incorrectly, 
```release-note
```
> test: fix provisioning scale test labels

- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes # 
Allow manual dispatch of re-usable workflows that are called by the `E2EMatrix` trigger
* Manual validation on fork
```release-note
None
```
> test: Allow manual dispatch of individual workflows

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/install-prometheus/action.yaml
- .github/actions/e2e/slack/notify/action.yaml
- .github/actions/e2e/upgrade-crds/action.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes # 
- Removes separate `actions/checkout` calls for the Action and the Repo and favors checking out the `inputs.git_ref` a single time
- Remove the `git_repo` parameter since that parameter will reference whichever repository that the action context is running inside of
* Manual runs on fork
```release-note
```
> test: Reference `git_ref` in action calls to allow testing updates to actions

- .github/workflows/e2e-matrix.yaml
Fixes # 
The GHA action actions were not available until `v0.28.0`; therefore, we are temporarily bumping the `from_git_ref` for the upgrade test to that version to enable the Upgrade tests to start working
*
```release-note
None
```
> test: Bump `from_git_ref` to fix e2e-upgrade

- examples/provisioner/large-instances.yaml
Fixes # 
Looks like this example was added before https://github.com/aws/karpenter/pull/2051 got implemented so, unless I'm missing something else that the example wishes to demonstrate, the requirements can be simplified so they don't require hard-coding the instance types. 
* Currently using a provisioner with similar requirements.
```release-note
```
> docs: Simplify large-instances example using `Gt` operator

- .github/actions/e2e/create-cluster/action.yaml
Fixes #N/A 
- Fixes syntax error in `create-cluster` with missing `"` character
- Uses the `inputs.k8s_version` value instead of the old `kubernetes_version` value
> test: Fix `k8s_version` value in create-cluster and Matching `"`

- .github/workflows/e2e-upgrade.yaml
> test: Fix `kubernetes_version` reference in old create-cluster call

- .github/actions/e2e/slack/notify/action.yaml
Fixes #N/A 
PR number was removed erroneously by #4099. This adds the PR number used to trigger the call back to the Slack notification
> test: Add PR number back to notify call

- .github/actions/e2e/commit-status/end/action.yaml
- .github/actions/e2e/commit-status/start/action.yaml
- .github/actions/e2e/slack/notify/action.yaml
- .github/actions/e2e/slack/send-message/action.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Adds commit status to a PR when running the `/karpenter snapshot` command
- Running the `e2e.yaml` and `e2e-upgrade.yaml` in my fork
> test: Add PR commit status reporting for `/karpenter snapshot` runs

- website/content/en/preview/getting-started/getting-started-with-karpenter/karpenter-controllers-allocation.json
- website/content/en/preview/getting-started/getting-started-with-karpenter/karpenter-controllers.json
Fixes #4094
The `DS_PROMETHEUS` variable is not available in more recent Grafana versions. Therefore, it was replaced with a variable based on a data source query that resolves the local default Prometheus data source.
I changed the files in the `preview` directory, I'm not sure whether we want to port the changes back to the latest releases (`v0,27`, `v0..28`).
Tested on Grafana `9.5.3`. 
> fix: replace DS_PROMETHEUS with datasource variable

- pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
- pkg/providers/launchtemplate/testdata/br_userdata_input.golden
- pkg/providers/launchtemplate/testdata/br_userdata_merged.golden
Fixes  https://github.com/aws/karpenter/issues/4118
- Adds Bottlerocket `settings.kubernetes.cloud-provider` config for toml user-data config.
> chore: add bottlerocket cloud-provider config

- .github/actions/e2e/slack/notify/action.yaml
Fixes #N/A 
Adds a helpful link to the test run. You can follow that to the trigger (dispatch, pr, etc)
> chore: link to testrun

- website/static/_redirects
Fixes #N/A 
v0.26 had the guide named `getting-started-with-eksctl`, and afterwards it's `getting-started-with-karpenter`. Adding a redirect so there aren't any 404s.
- `make website` doesn't properly test redirects, so I tested this with the website deploy.
> docs: add redirect for changed getting started guide

- go.mod
- go.sum
- test/pkg/environment/common/expectations.go
Fixes #N/A 
- Update the propagation policy to be `ForegroundDeletion` for all `ExpectDeleted` operations that take place during E2E testing
- This also pulls in the `karpenter-core` change that adds the `testing.karpenter.sh` discovery label onto pods that are deployed by deployments: https://github.com/aws/karpenter-core/pull/384
> test: Update prop policy for deletion and propagate discovery label to pods

- charts/karpenter/templates/service.yaml
- website/content/en/preview/upgrade-guide.md
- Fixed an issue were we see that metrics and Webhook ports were not able to configured.
> BREAKING CHANGE: Adjust Metrics and Webhook service port to align with pod ports 

- charts/karpenter/templates/webhooks-core.yaml
- charts/karpenter/templates/webhooks.yaml
- Due to https://github.com/aws/karpenter/pull/4142, the Webhook service port will not be defaulting to port 443. The port will need to be set. 
> chore: Set Webhook port from Helm values

- .github/actions/e2e/create-cluster/action.yaml
- pkg/providers/instance/instance.go
- test/manifests/pre-upgrade-setup.yaml
- test/manifests/setup.yaml
- website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.27/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.28/getting-started/getting-started-with-karpenter/cloudformation.yaml
Fixes # 
Updates CloudFormation permissions in the "Getting Started Guide" to be scoped to sufficiently restrict the tags that can be used when provisioning nodes with Karpenter. It also enforce tag-based authz on the karpenter controller by default.
Note that the CloudFormation file and the permissions that are provided there-in only serve as a starting point for users. The permissions will most likely have to be extended to some degree for most use-cases.
```release-note
```
> chore: Scope CloudFormation Permissions

- website/content/en/docs/concepts/provisioners.md
- website/content/en/preview/concepts/provisioners.md
- website/content/en/v0.26/concepts/provisioners.md
- website/content/en/v0.27/concepts/provisioners.md
- website/content/en/v0.28/concepts/provisioners.md
Cilium start taints documentation link was broken, this commit adds the updated doc link.
Just a markdown change, link manually tested.
- [] No
> docs: Update provisioners.md doc for Cilium start taints

- pkg/providers/instance/instance.go
Fixes #N/A 
- The cloudprovider list call used `DescribeInstancesWithContext` which wouldn't handle paginated results appropriately
- This change uses the proper `DescribeInstancesPagesWithContext` to handle the paginated results.
> fix: Use paginated result for `DescribeInstancesPagesWithContext`

- examples/provisioner/windows2019.yaml
- examples/provisioner/windows2022.yaml
- website/content/en/preview/concepts/node-templates.md
- website/content/en/preview/concepts/pod-density.md
- website/content/en/preview/concepts/provisioners.md
- website/content/en/preview/concepts/scheduling.md
- website/content/en/preview/faq.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/troubleshooting.md
Fixes #1131 
Karpenter will be adding Windows support in an upcoming change and this pull request contains documentation updates related to Karpenter Windows support.
Doc changes have been verified by checking the [Netlify deploy preview 4074](https://deploy-preview-4074--karpenter-docs-prod.netlify.app).
No release notes required for this PR. Release notes regarding Windows support will be included in PR #3698 with the following text.
```release-note
Add Windows support by introducing new Windows AMI Families.
```
> docs: Add Karpenter support for Windows docs

- .github/actions/e2e/install-prometheus/action.yaml
- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
This adds in the git ref and cluster name into all metrics so that we can differentiate all metrics by run.
It also adds in the mostRecentTag and commitsAfterTag so that users can aggregate off of the most recent tag or use the commitsAfterTag to isolate different commits.
- karpenter snapshot
> test: add cluster name and git ref into prometheus common labels

- website/content/en/docs/concepts/deprovisioning.md
- website/content/en/preview/concepts/deprovisioning.md
- website/content/en/v0.26/concepts/deprovisioning.md
- website/content/en/v0.27/concepts/deprovisioning.md
- website/content/en/v0.28/concepts/deprovisioning.md
Fixes #4144 
- The Node annotation example for deprovisioning was erroneously set to `karpenter.sh/v1alpha5` when it should have been set to `v1` from the Kubernetes `core/v1` api package.
- [] No
> docs: Fix node `apiVersion` in annotation example

- pkg/controllers/nodetemplate/suite_test.go
- pkg/fake/ssmapi.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/ami_test.go
In some region without specific AMI such as `cn-northwest-1` , launching would fail with errors like:
```
2023-06-26T08:13:14.481Z	ERROR	controller.provisioner	launching machine, creating cloud provider instance, creating instance, getting launch template configs, getting launch templates, getting ssm parameter "/aws/service/bottlerocket/aws-k8s-1.26-nvidia/arm64/latest/image_id", ParameterNotFound: 	{"commit": "698f22f-dirty"}
```
This error should be ignored since we do not need this kind of AMIs.
Tested with  AWS `cn-northwest-1`
> fix: only warn for ssm query errors

- .github/actions/commit-status/end/action.yaml
- .github/actions/commit-status/start/action.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/snapshot-release.yaml
Fixes #N/A 
Adds a commit status entry for the `SnapshotRelease` GH Action when it is triggered by `/karpenter snapshot`
Tested manually on my fork
> test: Add check for snapshot release run

- .github/actions/e2e/create-cluster/action.yaml
- website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.26/getting-started/getting-started-with-eksctl/cloudformation.yaml
- website/content/en/v0.27/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.28/getting-started/getting-started-with-karpenter/cloudformation.yaml
Fixes #N/A 
- Remove tag restriction scoping on CloudFormation policy deployed with the Getting Started Guide
- [] No
> docs: Remove tag restriction scoping on policy

- website/content/en/docs/upgrade-guide.md
- website/content/en/preview/upgrade-guide.md
- website/content/en/v0.28/upgrade-guide.md
Fixes #4201 
- Adds a note on the version of Karpenter that _does_ support Kubernetes Version 1.26+
- [] No
> docs: Fix v0.28.0 version compatibility mention in the docs

- test/cloudformation/README.md
- test/cloudformation/iam_cloudformation.yaml
Fixes # 
- Better handle test load, us-west-2 and us-west-1 will be add to better support testing
- Conformance testing will take place in us-west-2
- Scale testing will take place in us-west-1
```release-note
```
> test: Add more regions for e2etests

- README.md
Fixes: N/A
Added link to karpenter working group call to readme to increase visibility.
N/A
- [] No
> docs: Add karpenter working group call link to readme

- test/pkg/environment/aws/setup.go
- test/pkg/environment/common/environment.go
- test/pkg/environment/common/setup.go
- test/suites/machine/machine_test.go
- test/suites/scale/provisioning_test.go
Fixes #N/A 
`DeleteAllOf` calls were timing out in the case of pod deletions due to the scale of pods that were trying to be deleted in a single call. 60s wasn't sufficient time for all the pods to have their `DeletionTimestamps` set. 
- Manual testing of Provisioning Scale Testing
> test: Remove `DeleteAllOf` and bump client-side QPS

- .github/actions/e2e/create-cluster/action.yaml
- .github/actions/e2e/install-eksctl/action.yaml
Fixes #N/A 
- Need to pin eksctl to v0.147.0
- v0.148.0 is failing on e2etest runs
- 
- manually tested
> fix: eksctl version v0.147.0

- website/content/en/docs/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
Fixes #4249
- Change the `Capacity Dashboard`
- Only `Provisioner Summary` panel 
- Fix the `Memory Limit Utilization` column always print the **zeros**
- `Provisioner Summary` and `Node Summary` panels
- Print the bars like *eks-node-viewer* style, Red-Yellow-Green gradient.
Installed from [my PR branch's code](https://raw.githubusercontent.com/flavono123/karpenter/feature/improve-capacity-dashboard/website/content/en/docs/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json) to my Grafana.
<details>
<summary>
AS-IS
</summary>
</details>
TO-BE
- [] Yes, issue opened: #4249
By submitting this pull request, I confirm that my contribution is made …
> docs: improve the capacity dashboard (#4249)

- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/install-prometheus/action.yaml
- .github/actions/e2e/install-prometheus/values.yaml
Fixes #N/A 
- Move metric relabelings that add additional info to the metrics into the `ServiceMonitor`
- Reduces metric duplication between both performing a separate scrape job and using the servicemonitor for service discovery
`make apply` on local cluster
> test: Move metric relabeling to service monitor layer

- go.mod
- go.sum
Fixes #N/A 
- Bump karpenter-core 
- Bump includes https://github.com/aws/karpenter-core/pull/402
- Related to https://github.com/aws/karpenter/issues/4145
> chore: Bump karpenter-core with the knative health port workaround

- pkg/providers/amifamily/bootstrap/bottlerocket.go
- pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
- pkg/providers/launchtemplate/suite_test.go
Adds support to set the cfs quota field and have it passed through to Bottlerocket config. Currently `spec.kubeletConfiguration.cpuCFSQuota: false` is ignored on Bottlerocket hosts.
Deployed this image into a test cluster - this meant when `spec.kubeletConfiguration.cpuCFSQuota: false` was set this properly was fed down to the Kubelet on a Bottlerocket host.
> fix: Add support for CFS quota field in Bottlerocket

- .github/workflows/e2e.yaml
Fixes #N/A 
- Our conformance tests are experiencing throttling limitation on cluster creation, so we should add jitter to reduce throttling. 
- Tested in a forked account
> ci: Add jitter for E2Etests to prevent throttling  

- .github/dependabot.yaml
Fixes #N/A 
- Group dependabot updates together into a single PR using the new [group feature](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
- Fix the github action dependabot update checking
> ci: Group dependabot updates together

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- Updating git ref to v0.29.1 E2EUpgrade
- We should not notify on any of the conformance E2E tests. Bumping version to include the notification updates. 
- Upgrade tests currently look at GitHub actions from a pined karpenter repo
> ci: Update E2EUpgrade git ref

- .github/workflows/e2e-conformance-trigger.yaml
Fixes #N/A 
- Conformance tests should run every Sunday Evening, so that the E2E tests can be reviewed for karpenter ops meeting
> ci: Conformance tests should run on Sunday evenings

- go.mod
- go.sum
- pkg/apis/crds/karpenter.k8s.aws_awsnodetemplates.yaml
Fixes #N/A 
Buddy change to https://github.com/aws/karpenter-core/pull/416
This change fixes a file descriptor resource leak in `v0.29.1` due to our readiness/liveness checks leaving open connections due to not closing its response body.
> fix: Bump karpenter core to fix fd resource leak

- .github/pull-request-template.md
Fixes #N/A 
- Add "ci:" option to PR template
- Reorder existing suggestions
- Update some of the description lingo for existing suggestions
> docs: Add "ci:" to PR template

- hack/release/common.sh
- hack/release/release.sh
Fixes #3711 
Karpenter has been running dirty commits on release for some time. These dirty commits existed because the [`pullPrivateReplica`](https://github.com/aws/karpenter/blob/main/hack/release/common.sh#L115) function would result in untracked files from the `helm pull` operation. These files can be removed with a `git clean` operation after the `git reset --hard`
```console
➜  karpenter git:(test-release) ✗ git status
On branch test-release
Untracked files:
(use "git add <file>..." to include in what will be committed)
karpenter-crd-v0-cfb942221f59593b96a1a6203028bc20765dd08b.tgz
karpenter-v0-cfb942221f59593b96a1a6203028bc20765dd08b.tgz
```
```console
➜  karpenter git:(test-release) ✗ make install
Upgrading to v0-34d50bf6b02e72096dc6ff6dcdc8b8f52d6a437b
helm upgrade …
```
> ci: Fix dirty commit on release

- website/config.yaml
- website/content/en/v0.26/getting-started/getting-started-with-eksctl/scripts/step09-add-prometheus-grafana.sh
Fixes #4319
v0.26 has a different name for the getting started guides. Rectifying this so that it refers to an actual manifest file.
- [] No
> website: fix ref to v0.26 prometheus and grafana

- charts/karpenter/templates/deployment.yaml
Fixes #N/A 
- Adds a readiness probe delay `initialDelaySeconds: 5` to the Karpenter deployment to account for the time that it takes for the readiness probe to go up in the general case.
- In the general, case we should not be firing error events for readiness probe failures
```console
Events:
Type     Reason     Age   From               Message
----     ------     ----  ----               -------
Normal   Scheduled  22s   default-scheduler  Successfully assigned karpenter/karpenter-7b6844d679-ms86m to ip-192-168-63-116.us-west-2.compute.internal
Normal   Pulling    22s   kubelet            Pulling image "public.ecr.aws/karpenter/controller:v0.29.2@sha256:bac5ea470c09df21eb3742cf9448e9b806138ed5b6321d4e04697bbdf122eac6"
Normal   Pulled     20s   kubelet …
```
> fix: Add readiness probe `initialDelaySeconds`

- .github/workflows/e2e-conformance-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Due to request rate limit, we will run three e2etest at a time to allow conformance tests to run 
> ci: limit conformance test parallelism

- .github/workflows/stale.yaml
Fixes #N/A 
- Adds the `needs-review` and `needs-design` PR labels to be ignored by the stalebot
> ci: Add more exempt PR labels from Stalebot

- .github/actions/e2e/install-prometheus/action.yaml
Fixes #N/A 
- Add relabelings to add additional details into the kubelet serviceMonitor scraping
- Currently, only the karpenter serviceMonitor has these labelings
> ci: Add relabelings to kubelet serviceMonitor

- charts/karpenter/templates/clusterrole-core.yaml
- test/suites/drift/suite_test.go
- website/content/en/preview/concepts/deprovisioning.md
Fixes #N/A 
- Adding e2etests for provisioner static drift 
- Updating docs to include provisioner drift 
> test: Adding Provisioner Static Drift

- pkg/apis/v1alpha1/awsnodetemplate.go
- pkg/apis/v1alpha1/provider.go
- pkg/apis/v1alpha1/register.go
- pkg/apis/v1alpha1/suite_test.go
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/suite_test.go
- website/content/en/preview/concepts/deprovisioning.md
Fixes #N/A 
- Karpenter will create a provisioner hash of the fields that the team considers to be statically drifted
- The will contain the values of each of those fields
- `make battletest`
> chore: Adding AWSNodeTemplate Hash Annotation

- charts/karpenter/templates/clusterrole.yaml
- pkg/controllers/nodetemplate/controller.go
- pkg/controllers/nodetemplate/suite_test.go
- test/suites/integration/hash_test.go
Fixes #N/A 
- Added AWSNodeTemplate hash to be included in the AWSNodeTemplate Annotations 
- Unit and manual testing
> chore: Update Controller to Include Hash

- test/suites/integration/hash_test.go
Fixes #N/A 
- The test is grabbing the CRD before the controller hash updated the CRDs with their hash
> test: Fix flaky tests on grabbing CRDs to fast

- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
- For the e2e tests, we would like to make sure that the tests do not launch any instance with IMDSv1
- Needed to remove lines to prevent from hitting the IAM Policy character size limit of 6,144
- Tested in a local account
> ci: Deny all IMDSv1 to instances

- .github/actions/e2e/cleanup/action.yaml
- pkg/cloudprovider/drift.go
- pkg/cloudprovider/suite_test.go
- test/cloudformation/iam_cloudformation.yaml
- test/suites/drift/suite_test.go
- website/content/en/preview/concepts/deprovisioning.md
- website/content/en/preview/upgrade-guide.md
Fixes #N/A 
- Adding static one-way drift for the AWSNodeTemplate.
- The fields that will statically drift:
- Instance Profile  
- AMI Family
- UserData
- Tags 
- Metadata Options
- Block Device Mappings 
- Detailed Monitoring 
- Context
- Drift will check the hash that is produced from the AWSNodeTemplate against all its machines to validate the machines have not drifted
- Unit and Integration testing
> feat: AWSNodeTemplate Static Drift

- website/content/en/docs/concepts/deprovisioning.md
- website/content/en/preview/concepts/deprovisioning.md
- website/content/en/v0.26/concepts/deprovisioning.md
- website/content/en/v0.27/concepts/deprovisioning.md
- website/content/en/v0.28/concepts/deprovisioning.md
- website/content/en/v0.29/concepts/deprovisioning.md
Fixes #N/A 
Fixes a mistake surrounding the `NoSchedule` taint with respect to the `do-not-evict` annotation and cleans up some wording and grammar.
Viewing the preview docs
> docs: Add updated guidance on `do-not-evict` annotation

- .github/actions/e2e/install-prometheus/action.yaml
- .github/actions/e2e/install-prometheus/values.yaml
Fixes #N/A 
Add metric relabelings to kubelet cAdvisor and disable other endpoints
> ci: Add metric relabelings to kubelet cAdvisor and disable other endpoints

- Makefile
- website/content/en/docs/contributing/development-guide.md
- website/content/en/preview/contributing/development-guide.md
- website/content/en/v0.29/contributing/development-guide.md
Fixes #NA
Simplify dev loop to use a single ECR Repo. Respects existing KO_DOCKER_REPO if set.
```
❯ make apply
2023/08/04 11:40:21 Using base cgr.dev/chainguard/static:latest@sha256:6b35c7e7084349b3a71e70219f61ea49b22d663b89b0ea07474e5b44cbc70860 for github.com/aws/karpenter/cmd/controller
2023/08/04 11:40:22 Building github.com/aws/karpenter/cmd/controller for linux/amd64
2023/08/04 11:40:25 Publishing 767520670908.dkr.ecr.us-west-2.amazonaws.com/dev:latest
2023/08/04 11:40:26 existing blob: sha256:eb0ae35341366ba2c164b0c88e84954fdb05fe9a8bbdf4228f5e7354546a0e6e
2023/08/04 11:40:26 pushed blob: sha256:ee527539410af8964e835a154c6a0166f666d042d876fec78d900ce51d9c6adb
2023/08/04 11:40:26 pushed blob: …
```
> docs: Simplify developer guide to use a single ECR repository across multiple projects

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.26/faq.md
- website/content/en/v0.27/faq.md
- website/content/en/v0.28/faq.md
- website/content/en/v0.29/faq.md
The only ways to know how to configure the logging in Karpenter are to dig through past issues where configuration is discussed, or to be aware of the underlying logging library and how to use it already. This can be a higher burden than necessary to make small modifications to the logs.
This adds a section to the FAQ about logging. The new section links out to where to update, what to update, and how to update, to make changes to the logging configuration. This makes it easier for others to find and update their logging configurations.
> docs: Add FAQ section to answer logging questions

- .github/actions/e2e/create-cluster/action.yaml
Fixes #N/A 
- E2E tests will are getting rate limited on `ListOpenIDConnectProviderTags` when multiple E2E tests are running
- Removing the List call and using the cluster name to tag the OIDC
> ci: Tag OIDC using cluster name for clean-up

- test/suites/drift/suite_test.go
Fixes #N/A 
- Startup taints seem to be failing due to the node object being changed while e2e test removes start-up taints on the nodes. 
> ci: Flaky Start-up Taint Drift Test 

- go.mod
- go.sum
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/drift.go
- pkg/cloudprovider/suite_test.go
- pkg/fake/cloudprovider.go
Fixes #N/A 
- Bumping karpetner-core version and passing drift reason to karpenter-core
- `make battletest`
> chore: Update Cloudprovider interface with driftReason 

- go.mod
- go.sum
Fixes #N/A 
- We keep seeing flaky e2e test failures on the machine suite. 
- Fix in karpenter-core https://github.com/aws/karpenter-core/pull/463
> chore: Bump karpenter-core

- hack/release/common.sh
Fixes #N/A 
- Release action is failing due to not defining `MAIN_GITHUB_ACCOUNT: unbound variable` 
- https://github.com/aws/karpenter/actions/runs/5827248497/job/15803358804
> fix: unblock release Stable-PR

- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
- e2e tests are failing on Cluster Create due to a missing eks:TagResource permission on the Node Group resource.
> chore: eks:TagResource on nodegroup for e2e tests

- test/suites/integration/ami_test.go
Fixes #N/A 
- There's a bug in the Ubuntu bootstrap script when an instance type is not included in the max-pods.txt file which generally affects new instance types. This change will only use gen 6 and below for the ubuntu e2e test to stop the flakey failures. 
> chore: mitigate ubuntu issue causing flakey tests on new instance types

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/suite_test.go
Fixes #N/A 
https://github.com/aws/karpenter/issues/4441
- When a providerRef selects 0 node templates, all provisioning would stop until fixed. This patch will allow other provisioners to continue working.
- manually on an EKS cluster and added to a suite test
> fix: invalid provider ref caused all provisioning to stop

- test/suites/integration/ami_test.go
- test/suites/integration/kubelet_config_test.go
- test/suites/integration/scheduling_test.go
Fixes #N/A 
- Fix test flakes in windows due to missing ENI data in VPC RC and ref tracking issue in TODO comment
> chore: mitigate new instance types causing flakey windows tests

- website/content/en/preview/faq.md
Fixes #2572 
#2572 is a task to update Karpenter docs to reference a solution to when the Kubernetes scheduler places pods on nodes that do not fulfill desired zonal Topology Spread Constraints. With minDomains enabled by default in Kubernetes 1.27, added to FAQ that minDomains should be used for zonal constraints. Also mentioned prior workaround of scheduling lower priority pause pods in desired zones.
Tested Karpenter with EKS 1.27, with and without minDomains in Pod spec, to demonstrate that minDomains fixed the issue.
> docs: Add Topology Spread Constraints and minDomains to FAQ

- test/Dockerfile
> chore: use go 1.21 in test docker image

- .github/actions/install-deps/action.yaml
Fixes #N/A 
Bumps `install-go-deps` to `1.27.x`
> ci: Bump `install-go-deps` version

- charts/karpenter/values.yaml
- pkg/apis/settings/settings.go
- pkg/apis/settings/suite_test.go
- pkg/operator/operator.go
- website/content/en/preview/concepts/settings.md
Adding clusterCABundle as a Karpenter setting. This is needed for our use case where a Karpenter controller needs to communicate with a cluster, but does not use TLS itself - instead it talks to a local proxy over HTTP. Without this change, the CA bundle would be unresolvable and the CA bundle passed to the node would be empty, preventing that node from joining the cluster.
One call out I had was that this was failing silently for our use case before I caught this - this is because the validation below assumes that the rest config is TLS-enabled. Should we add a separate check to verify that the CAData string isn't empty before returning?
https://github.com/neerajvshah/karpenter/blob/main/pkg/operator/operator.go#L210-L223
EDIT - technically Kubernetes api-servers can be …
> Cluster ca bundle setting

- go.mod
- go.sum
- hack/docs/metrics_gen_docs.go
- test/pkg/environment/common/expectations.go
Fixes #N/A 
- Bumps `karpenter-core` to the latest version with more `v1beta1` conversion logic
> chore: Bump karpenter-core to latest

- website/content/en/docs/concepts/provisioners.md
- website/content/en/preview/concepts/provisioners.md
- website/content/en/v0.26/concepts/provisioners.md
- website/content/en/v0.27/concepts/provisioners.md
- website/content/en/v0.28/concepts/provisioners.md
- website/content/en/v0.29/concepts/provisioners.md
- website/content/en/v0.30.0-rc/concepts/provisioners.md
Fixes #N/A 
docs: Fix ttlSecondsAfterEmpty capailtilization in docs for consistency
n/a
> docs: Fix ttlSecondsAfterEmpty capailtilization in docs for consistency

- charts/karpenter/README.md
- hack/docs/metrics_gen_docs.go
- website/content/en/preview/concepts/instance-types.md
- website/content/en/preview/concepts/metrics.md
Fixes #N/A 
Fix `make docgen` for `nodeSubsystem`
`make docgen`
> ci: Fix `make docgen` node namespace

- go.mod
- go.sum
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/launchtemplate/suite_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/webhook_test.go
Fixes #N/A 
This change allows users to pass labels prefixed with `node-restriction.kubernetes.io` into Karpenter labels and requirements and ensures that labels that have this domain are not passed into the userData and into the kubelet startup CLI arguments (which would cause the kubelet to fail startup).
> Allow `node-restriction.kubernetes.io/` prefix in the label set

- go.mod
- go.sum
Fixes #N/A 
- Bump `karpenter-core` to the latest with more `v1beta1` conversion logic changes
> chore: Bump `karpenter-core`

- hack/docs/metrics_gen_docs.go
Fixes #N/A 
- Fix docgen metrics generation for `nodePoolSubsystem`
`make docgen`
> ci: Fix docgen metrics generation for `nodePoolSubsystem`

- test/pkg/environment/common/expectations.go
- test/suites/drift/suite_test.go
- test/suites/integration/expiration_test.go
Fixes #N/A 
- Testing to ensure that expiration and drift do not continue if a machine fails to initialize and register 
- E2E testing for https://github.com/aws/karpenter-core/pull/451
> test: Prevent Drift from deleting nodes for unhealthy replacement nodes

- .github/actions/e2e/install-karpenter/action.yaml
- charts/karpenter/README.md
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
Fixes #4278 
This change is to set the default securityContext for controller pod within the Helm chart values file to enforce secure by default.
Tried scaling the pods and Karpenter was able to provision the new nodes as expected.
> chore:Add default securityContext and podSecurityContext to Karpenter deployment #4278

- pkg/apis/v1alpha1/awsnodetemplate_validation.go
- pkg/apis/v1alpha1/provider_validation.go
- pkg/apis/v1alpha1/suite_test.go
- pkg/apis/v1beta1/nodeclass_validation.go
- pkg/apis/v1beta1/suite_test.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/providers/subnet/subnet.go
- test/suites/integration/webhook_test.go
- website/content/en/preview/upgrade-guide.md
Fixes #N/A 
This PR adds validation to ensure that the `id` field that can be specified in selectors through `aws-ids` and `aws::ids` is mutually exclusive with other fields that can be specified in the selector like `tags`, `owners`, and `names`
> chore: Add validation to ensure `id` field is mutually exclusive in selectors

- website/content/en/preview/upgrade-guide.md
Fixes #N/A 
This PR adds a breaking change notice for `v0.30.0` as a result of hardening the pod and container-level security contexts to adhere to [upstream Kubernetes pod security best practices](https://kubernetes.io/docs/concepts/security/pod-security-standards/).
> docs: Add a breaking change note on pod security hardening

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/suites/drift/suite_test.go
- test/suites/expiration/expiration_test.go
- test/suites/integration/emptiness_test.go
Fixes #N/A 
This PR separates the expiration tests into a separate test suite that runs in parallel so that the long-running tests in that suite don't bottleneck the overall test time.
> test: Separate the expiration test suite and cleanup deprovisioning failure checks

- test/suites/chaos/suite_test.go
- test/suites/consolidation/suite_test.go
- test/suites/drift/suite_test.go
- test/suites/interruption/suite_test.go
Fixes #N/A 
Rename the test packages to suffix them all with `_test`
> test: Rename test packages suffixed with `_test`

- cmd/controller/main.go
- go.mod
- go.sum
- hack/docs/instancetypes_gen_docs.go
- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/events/events.go
- pkg/cloudprovider/suite_test.go
- pkg/controllers/machine/garbagecollection/suite_test.go
- pkg/controllers/machine/link/suite_test.go
- pkg/providers/instance/suite_test.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
When a NodeTemplate fails to resolve in the cloudprovider code for a NotFoundError, Karpenter ignores it. Since this may happen very quickly and will not resolve itself, Karpenter now emits an event for this. 
Additionally, this change will not include cloudprovider.InstanceTypes() if they have no offerings. In the case of `karpenter-core`'s scheduling and deprovisioning logic, this means that Karpenter will consider less instance types in some cases when the zones fail to resolve. 
This is also the buddy change for https://github.com/aws/karpenter-core/pull/491
- make presubmit && snapshot tests.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> fix: emit events when node template fails to resolve

- go.mod
- go.sum
Fixes #N/A 
Updates the go.mod to use v0.30.0, which maps to the same commit as it already is
- make presubmit
> chore: update core to v0.30.0

- test/pkg/environment/common/environment.go
- test/pkg/environment/common/expectations.go
- test/pkg/environment/common/setup.go
- test/suites/chaos/suite_test.go
- test/suites/consolidation/suite_test.go
- test/suites/drift/suite_test.go
- test/suites/expiration/expiration_test.go
- test/suites/integration/suite_test.go
- test/suites/interruption/suite_test.go
- test/suites/ipv6/suite_test.go
- test/suites/machine/suite_test.go
- test/suites/scale/suite_test.go
- test/suites/utilization/suite_test.go
Fixes #N/A 
This PR replaces the direct client in the E2E testing code to use the `client.DelegatingClient`. This reduces the load on the APIServer for the large number of LIST calls that we make as we are trying to validate whether test conditions are met. 
> test: Use delegating client in E2E testing

- test/pkg/environment/common/expectations.go
- test/pkg/environment/common/setup.go
- test/suites/integration/extended_resources_test.go
Fixes #N/A 
Wait for a second on cleanup of the E2E test to let the caches catch-up for the cleanup stage.
> test: Wait for a second on cleanup to let the caches catch-up

- test/hack/cleanup/main.go
Fixes #N/A
- The sweeper is trying references object that `nil` from aws responses
-  https://github.com/aws/karpenter/actions/runs/6043801050/job/16401428378
- Ran the sweeper
> chore: skipping items that cause an error from the sweeper

- pkg/cloudprovider/cloudprovider.go
- pkg/cloudprovider/drift.go
- pkg/cloudprovider/events/events.go
- pkg/controllers/nodetemplate/controller.go
- pkg/controllers/nodetemplate/suite_test.go
- pkg/fake/atomic.go
- pkg/fake/ec2api.go
- pkg/fake/utils.go
- pkg/providers/amifamily/al2.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/ami_test.go
- pkg/providers/amifamily/bootstrap/bootstrap.go
- pkg/providers/amifamily/bottlerocket.go
- pkg/providers/amifamily/custom.go
- pkg/providers/amifamily/resolver.go
- pkg/providers/amifamily/ubuntu.go
- pkg/providers/amifamily/windows.go
- pkg/providers/instance/instance.go
- pkg/providers/instance/suite_test.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/launchtemplate/suite_test.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/providers/securitygroup/suite_test.go
- pkg/providers/subnet/subnet.go
- pkg/providers/subnet/suite_test.go
- test/suites/integration/security_group_test.go
- test/suites/integration/subnet_test.go
Fixes #N/A 
This PR adds support for `v1beta1/NodeClass` and `v1beta1/NodePool` conversion in the CloudProvider. This change is meant to stage out the `v1beta1` changes so that the CRDs can be released more formally later.
Now, with the `v1beta1/NodeClass` APIs, if you add multiple terms to the set of `subnetSelectors`, `securityGroupSelectors`, or `amiSelectors`, this will generate multiple requests to the respective EC2 APIs (unless the selectors reference ids, in which case we combine all id filters into a single request).
> chore: Enable `v1beta1/NodeClass` conversion for CloudProvider

- pkg/controllers/interruption/controller.go
- pkg/controllers/interruption/events/events.go
Fixes #N/A 
This change adds support for the `v1beta1/NodeClaim` in the interruption controller that currently only handles machines. This change stages out the `v1beta1` changes so that the `v1beta1` APIs can be released at a later time.
> chore: Add support for `v1beta1/NodeClaim` to the interruption controller

- pkg/controllers/controllers.go
- pkg/controllers/nodetemplate/controller.go
- pkg/controllers/nodetemplate/suite_test.go
- pkg/utils/nodeclass/nodeclass.go
Fixes #N/A 
This change adds support for the `v1beta1/NodeClass` in the nodetemplate controller that currently only handles `v1alpha1/AWSNodeTemplate`. This change stages out the `v1beta1` changes so that the `v1beta1` APIs can be released at a later time.
> chore: Add support for `v1beta1/NodeClaim` to the NodeTemplate controller

- pkg/cloudprovider/drift.go
- pkg/fake/ec2api.go
- pkg/operator/operator.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/ami_test.go
- pkg/providers/amifamily/resolver.go
- pkg/test/environment.go
Fixes #N/A 
This PR reduces the memory utilization from the `DescribeImages` call for calls that are wide-open and grab an extremely high number of images from the API >> 1000 images. This changes the call to be paginated and to cap the number of results in a page at 500 images. Each page only stores an image if the set of requirements for the image is different from the existing set of image requirements OR if the requirements already exist but the image is newer. This reduces the amount of things that are stored in the cache for a request.
For the following test `AWSNodeTemplate`, these are the memory footprints before and after the PR
```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
name: …
```
> perf: Reduce memory by using `DescribeImages` paginated call

- website/content/en/preview/concepts/provisioners.md
Fixes #N/A 
https://github.com/aws/karpenter/issues/4558
- Update supported operators in provisioners docs and linked upstream k8s docs
> chore: update supported operators in provisioners docs

- pkg/cloudprovider/cloudprovider.go
- pkg/providers/amifamily/al2.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/bootstrap/bootstrap.go
- pkg/providers/amifamily/bottlerocket.go
- pkg/providers/amifamily/custom.go
- pkg/providers/amifamily/resolver.go
- pkg/providers/amifamily/ubuntu.go
- pkg/providers/amifamily/windows.go
- pkg/providers/instance/instance.go
- pkg/providers/instance/types.go
- pkg/providers/instancetype/types.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/securitygroup/suite_test.go
- pkg/providers/subnet/suite_test.go
Fixes #N/A 
This PR adds handling to return the `v1beta1` API Group as the prefix to all the current `karpenter.k8s.aws` requirements. The new requirements will now be prefixed with `compute.k8s.aws`. This change returns these different requirements based on whether you are launching a Machine (`v1alpha5`) or NodeClaim (`v1beta1`)
> chore: Handle `v1beta1` labels for requirements and tags

- test/suites/integration/extended_resources_test.go
Fixes #N/A 
Disallows the `m7a` instance family for the following test: `should provision nodes for a deployment that requests vpc.amazonaws.com/pod-eni (security groups for pods)`. Currently this test will fail if an `m7a` type instance is provisioned due to it not being supported by the vpc resource controller.
`go test`
> test: disallow m7a instance types for pod-eni test

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Revert changes from https://github.com/aws/karpenter/pull/4569
- N/A
> ci: Revert upgrade test to local reference for `create-cluster`

- pkg/providers/amifamily/bootstrap/eksbootstrap.go
- pkg/providers/launchtemplate/suite_test.go
- pkg/providers/launchtemplate/testdata/al2_userdata_content_type_first_input.golden
Fixes #N/A 
https://github.com/aws/karpenter/issues/4581
- Allow a mime formatted user-data to have the Content-Type header before the MIME-Version header since both are valid. 
- Added suite test and tested on EKS cluster
> fix: allow user-data mime content-type before mime-version header

- pkg/errors/errors.go
Fixes #N/A 
https://github.com/aws/karpenter/issues/3380
- Treat Insufficient IP addresses in Subnet as an ICE so that it's cached for a period of time before retrying. This will also cause the instance pool to not be in the candidate set on the next scheduling round so that it can potentially use another AZ.  
> chore: treat insufficient IPs as ICE

- test/suites/integration/ami_test.go
- test/suites/integration/kubelet_config_test.go
Fixes #N/A 
Windows tests will now use the default instance family and generations as they would have if the provisioners were not configured for Windows. This is to address test flaking caused by provisioning instances with extremely slow boot times (e.g. t2.nano / micro).
`go test`
> test: use default instance family / generation for Windows tests

- .github/workflows/approval-comment.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/resolve-args.yaml
Fixes #N/A 
This PR allows users to run `/karpenter scale` which will trigger scale testing runs from a PR build.
`/karpenter scale`
> Enable scale test running from a PR

- pkg/controllers/nodeclass/suite_test.go
- pkg/operator/operator.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/ami_test.go
- pkg/providers/launchtemplate/suite_test.go
- pkg/providers/version/version.go
- pkg/test/environment.go
Fixes #N/A 
- Creating a provider for k8s version to separate it out from the AMI provider to retirve the k8s version without need to define the AMIProvider 
> chore: k8s Version Provider

- test/suites/integration/ami_test.go
Fixes #N/A 
This PR fixes the Windows UserData test flakes by removing the `m7a` family from the Windows UserData test until the `vpc-resource-controller` supports this family
> test: Fix Windows UserData test flakes by removing m7a family

- website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.27/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.28/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.29/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.30/getting-started/getting-started-with-karpenter/cloudformation.yaml
Fixes #N/A 
This PR collapses the CloudFormation permissions that are shipping as part of the Getting Started down into less statements and makes the `SSM:GetParameter` permission to be more restrictive by only allowing it to read SSM parameters from the same region that are AWS service managed paths
> docs: Collapse CloudFormation permissions

- test/pkg/environment/common/expectations.go
Fixes #N/A 
This PR fixes a call to `ExpectUpdated` in `ExpectCreatedOrUpdated` which was passing all of the objects to `ExpectUpdated` rather than just passing the single object that we were evaluating
`/karpenter scale`
> test: Fix `ExpectUpdated` passing a single object

- website/content/en/preview/concepts/deprovisioning.md
- website/content/en/v0.30/concepts/deprovisioning.md
Fixes #4609 
- Remove from docs as this is not true anymore
- N/A
> docs: Remove `karpenter.sh/voluntary-disruption` annotation from docs

- test/suites/integration/ami_test.go
- test/suites/integration/extended_resources_test.go
- test/suites/integration/kubelet_config_test.go
Fixes #N/A 
This PR disable the `r7a` family instance types in tests that require the `vpc-resource-controller` to be running appropriately until the limits for these instance types is rolled out.
> test: Disable r7a instance types until supported by vpc-rc

- examples/provisioner/launchtemplates/al2-kubelet-log-query.yaml
- examples/provisioner/launchtemplates/ubuntu-kubelet-log-query.yaml
Add additional examples for customizing userdata on AL2 and Ubuntu OS. Shows examples extending KUBELET_EXTRA_ARGS which was undocumented other places.
Creating multiple clusters with AL2 and Ubuntu provisioners
The Ubuntu example currently doesn't work with the feature I was trying to get working (see https://github.com/kubernetes/kubernetes/issues/120618 ) but I still think it's valuable to have an example of how to do these customizations on Ubuntu as well as AL2.
> docs: Add more userdata examples for node log query

- pkg/controllers/nodeclass/controller.go
- pkg/controllers/nodeclass/suite_test.go
- pkg/providers/amifamily/ami.go
Fixes #N/A 
This PR ensures that all pieces of the `NodeTemplate` output are sorted so that it always has a consistent output and doesn't perform additional `Patch` operations. Previously, it was possible that the `SecurityGroup` ordering or the AMI requirements ordering could change because they were stored in a map.
> fix: Ensure a consistent ordering for all NodeTemplate status fields

- designs/unmanaged-launch-template-removal.md
Fixes #N/A 
This PR adds a RFC design doc recommending that Karpenter drop the `spec.launchTemplateName` field from the new `v1beta1/EC2NodeClass` and provides the rationale behind the decision, including alternative options.
N/A
> docs: [RFC] Add Unmanaged Launch Template Removal RFC

- designs/v1beta1-api.md
- designs/v1beta1-full-changelist.md
Fixes #N/A 
This PR proposes the `v1beta1` APIs and full Change List into the design directory
> docs: [RFC] Add v1beta1 API RFC

- cmd/controller/main.go
- hack/docs/version_compatibility.go
- pkg/operator/operator.go
- pkg/providers/version/version.go
Fixes #N/A 
- Log incompatibility  k8s version every time karpenter retrieves the API version
- N/A
> chore: Log Incompatible version of the API version

- pkg/providers/launchtemplate/nodeclass_test.go
Fixes #N/A 
This change fixes a rebase miss from merging in the launch template testing to change the `corev1beta1.KubeletConfiguration` references to `corev1beta1.Kubelet`
> test: Fix rebase miss in launch template testing

- .github/workflows/approval-comment.yaml
- .github/workflows/e2e-conformance-trigger.yaml
Fixes #N/A 
- This PR allows users to run /karpenter conformance which will trigger scale testing runs from a PR build.
- `/karpenter conformance`
> ci: Enable conformance test running from a PR

- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/v1beta1/ec2nodeclass.go
- pkg/apis/v1beta1/ec2nodeclass_validation.go
- pkg/apis/v1beta1/suite_test.go
- pkg/apis/v1beta1/zz_generated.deepcopy.go
- pkg/controllers/nodeclass/nodeclass_test.go
- pkg/test/nodeclass.go
- pkg/utils/nodeclass/suite_test.go
Fixes #N/A 
This PR enforces the `AMIFamily` and `Role` is required for `v1beta1/EC2NodeClass`
This PR also changes the persisted defaulting logic for `MetadataOptions`
> chore: Enforce fields are required for `v1beta1/EC2NodeClass`

- .github/workflows/approval-comment.yaml
This is a minor fix to one of the GitHub Actions workflows. It is a security best practice to sanitize any GitHub Actions variables that can contain arbitrary values in a `run` step.
N/A
> ci: Sanitize user-controlled variable.

- .github/actions/install-deps/action.yaml
- Makefile
- hack/toolchain.sh
Fixes #N/A 
This PR updates the installation path for kubebuilder to change it from a path in your home directory to the default expected installation path `/usr/local/kubebuilder/bin`. This means that you no longer need to set the `KUBEBUILDER_ASSETS` variable in testing
> ci: Set the toolchain kubebuilder install path to be the default one

- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/v1beta1/ec2nodeclass.go
- pkg/apis/v1beta1/ec2nodeclass_validation.go
- pkg/apis/v1beta1/suite_test.go
- pkg/providers/instancetype/types.go
- pkg/providers/launchtemplate/nodeclass_test.go
Fixes https://github.com/aws/karpenter/issues/3962 
* Karpenter doesn't support specifying root volumes within block device mappings. This update introduces a `RootVolume` flag to the `BlockDeviceMapping`, enabling Karpenter to utilize the configured volume size for pod packing.
Unit tests.
> fix: Allow specifying root volume in block device mappings

- .github/actions/install-deps/action.yaml
Fixes #N/A 
This change fixes the `actions/cache` step which was broken due to directory permissions on restore
Running the CI jobs
> ci: Fix caching on `install-deps`

- pkg/apis/v1beta1/labels.go
- pkg/controllers/nodeclaim/tagging/controller.go
- pkg/controllers/nodeclaim/tagging/suite_test.go
- pkg/fake/ec2api.go
- pkg/providers/instance/instance.go
- pkg/providers/launchtemplate/nodeclass_test.go
- test/suites/integration/tags_test.go
Fixes #3342 
This PR introduces a new controller for v1beta1 responsible for tagging ec2 instances with their in-cluster name. This replaces the previous behavior where each instance's name corresponded to it's `Provisioner` (e.g. `karpenter.sh/provisioner/default`). It is not possible to do this as part of the `CreateFleet` call since the node name is not yet known. Instead, this controller observes `NodeClaim`s, waiting for their node name to be populated. 
Additionally, while this PR does not introduce custom dynamic tags, it does open up a path for them in the future (see issues #2783 and #4228).
`make test` and `make e2e` …
> feat: instance tagging controller

- pkg/providers/instance/nodeclass_test.go
- pkg/providers/instance/nodetemplate_test.go
- pkg/providers/instance/suite_test.go
Fixes #N/A 
This PR adds testing for the cloudprovider instance provider for the `v1beta1/EC2NodeClass` APIs
> test: Add `v1beta1/EC2NodeClass` instance testing for cloudprovider

- pkg/controllers/interruption/machine_test.go
- pkg/controllers/interruption/nodeclaim_test.go
- pkg/controllers/interruption/suite_test.go
- pkg/operator/suite_test.go
Fixes #N/A 
This PR adds testing for the interruption handling controller for the `v1beta1/NodeClaim` APIs
> test: Add interruption testing for `v1beta1/NodeClaim` APIs

- charts/karpenter/templates/deployment.yaml
- website/content/en/docs/upgrade-guide.md
- website/content/en/preview/upgrade-guide.md
- website/content/en/v0.30/upgrade-guide.md
Fixes #4660, #4657 
This PR changes the default configuration of Karpenter deployed with helm from specifying the `securityContext` at the pod-wide level to specifying it at the container-level for Karpenter. This allows sidecar containers to use their defaults without having to manually override the security context for the container.
> BREAKING CHANGE: Move default `securityContext` down to the container-level

- pkg/controllers/nodeclass/controller.go
- pkg/providers/instanceprofile/instanceprofile.go
Fixes #N/A 
- This PR adds a detailed comment on why there cannot be more than 1 role assigned to an instance profile.
- This change also validates that the Finalization loops doesn't run for the `AWSNodeTemplate`
> chore: Add comment on 1:1 mapping from role to instance profile and AWSNodeTemplate Finalization check

- test/suites/integration/instance_profile_test.go
Fixes #N/A 
Adds a skip so we don't run tests until v1beta1 is released.
- make e2etests
> test: skip instance profile generation tests

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- The E2E Upgrade tests post run action are failing due to GHA step difference. Bumping the older version of the repo to keep the two version of the `create-cluster` to match
> chore: Bump upgrade test version

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
This PR bumps the `from_git_ref` to the latest version that has the `eksctl_version` as the passthrough for setting the version. 
The long-term fix for having to do this in the `e2e-upgrade` is handle the checkouts to the old version in the action in a way that doesn't override the actions directory.
> ci: Bump to a version that uses `eksctl` version

- .github/actions/e2e/create-cluster/action.yaml
- .github/actions/install-deps/action.yaml
- .github/workflows/ci-test.yaml
- .github/workflows/e2e-conformance-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- pkg/providers/version/version.go
Fixes #N/A 
Bumps the GitHub Actions infrastructure to use EKS 1.28 by default. Additionally bumps the max supported kubernetes version to 1.28.
N/A
> chore: bump to EKS 1.28

- .github/actions/e2e/slack/notify/action.yaml
- .github/workflows/e2e-conformance-trigger.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/resolve-args.yaml
Fixes #N/A 
Drop passing through the `event_name` through `inputs.event_name` since the `github` context always stores the top-level event in `github.event_name`
> ci: Fix passing through the `event_name` correctly

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
Bumps eksctl version for GHA to support EKS 1.28.
> chore: bump eksctl version

- go.mod
- go.sum
- pkg/providers/version/version.go
Fixes #N/A 
- update to latest karpenter-core
- mark EKS 1.28 as supported
> prepare for release

- pkg/providers/pricing/pricing.go
Fixes #4658
Pricing endpoint for China was wrong as the generated auth tokens are not valid in the Asia Pacific region. Also it's best to get prices from the same region.
> fix: China Pricing Endpoint

- .github/workflows/ci-test.yaml
Fixes #N/A 
- Remove k8s 1.22 from unit testing.
- karpenter does not support 1.22
- N/A
> ci: Remove 1.22 from our testing

- pkg/controllers/nodeclass/nodeclass_test.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/ami_test.go
- pkg/providers/launchtemplate/nodeclass_test.go
- pkg/providers/launchtemplate/nodetemplate_test.go
Fixes #N/A 
This PR drops support for tag-based AMI requirements for `v1beta1/NodeClass` (as specified in the [v1beta1 proposal design](https://github.com/aws/karpenter/blob/main/designs/v1beta1-api.md))
> chore: Drop support for tag-based ami requirements with `v1beta1/NodeClass`

- charts/karpenter/README.md
- charts/karpenter/templates/clusterrole-core.yaml
- charts/karpenter/templates/clusterrole.yaml
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/templates/role.yaml
- charts/karpenter/templates/service.yaml
- charts/karpenter/templates/webhooks-core.yaml
- charts/karpenter/templates/webhooks.yaml
- charts/karpenter/values.yaml
- website/content/en/preview/concepts/settings.md
- website/content/en/preview/upgrade-guide.md
Fixes #N/A 
This enables webhook metrics to be exposed on port 8001 and allows this port to be configured through the `webhook.metrics.port` and to allow disabling the webhooks through the `webhook.enabled` chart value
`make apply` (manual validation)
> chore: Expose webhooks on port 8001 and enable disabling webhooks

- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
Fixes #N/A 
Adds id-token permissions to the snapshot and release workflows, enabling AWS authentication.
N/A
> fix: id-token permission for release / snapshot

- .github/actions/e2e/install-karpenter/action.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
Replaces the repository variables in the `install-karpenter` composite action with inputs.
N/A
> ci: use inputs for composite action

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/actions/e2e/install-eksctl/action.yaml
- .github/actions/e2e/install-helm/action.yaml
- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/install-prometheus/action.yaml
Fixes #N/A 
Helm has a bug in `v3.13.0` here: https://github.com/helm/helm/issues/12423 which prevents anonymous pulling from succeeding. We should be pinning the version anyways versus pulling against latest.
> ci: Pin helm version in action due to `v3.13.0` bug

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
Bumps the `from_git_ref` field to to the commit that uses the pinned version of helm to fix anonymous pulls
> ci: Bump `from_git_ref` to version that pins helm version

- cmd/controller/main.go
- go.mod
- go.sum
Fixes #N/A 
Using this to test through snapshots.
> chore: update core to get new termination singleton controller

- test/suites/integration/kubelet_config_test.go
Fixes #N/A 
- Remove c7a instance type for
- `KubeletConfiguration Overrides All kubelet configuration set Windows AMIFamilies [It] when the AMIFamily is Windows2022`
> test: Remove c7a instancetype for windows E2E test on KubeletConfiguration Overrides

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/actions/e2e/create-cluster/alpha-controller-policy.json
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
Fixes #N/A 
Updates the CloudFormation template shipped with the Getting Started guide to use v1beta1 permissions. This also ensures that we are deploying the Karpenter controller IAM permissions with an additional policy that gives the controller the alpha permissions so that we can ensure that scenarios that are testing alpha and beta simultaneously will work.
`make apply` with the new permissions
> docs: Update CloudFormation to handle v1beta1 permissions

- website/content/en/preview/concepts/scheduling.md
Fixes #N/A 
This PR updates the `scheduling` doc to use the v1beta1 terminology and concepts.
> docs: Update scheduling doc to v1beta1

- website/content/en/docs/faq.md
- website/content/en/docs/upgrade-guide.md
- website/content/en/preview/faq.md
- website/content/en/preview/upgrade-guide.md
- website/content/en/v0.27/faq.md
- website/content/en/v0.27/upgrade-guide.md
- website/content/en/v0.28/faq.md
- website/content/en/v0.28/upgrade-guide.md
- website/content/en/v0.29/faq.md
- website/content/en/v0.29/upgrade-guide.md
- website/content/en/v0.30/faq.md
- website/content/en/v0.30/upgrade-guide.md
- website/content/en/v0.31/faq.md
- website/content/en/v0.31/upgrade-guide.md
Fixes #4782 
This docs change backports the compatibility matrix to older version so it's clear which versions that Karpenter supports.
> docs: Backport the compatibility matrix

- .github/actions/e2e/create-cluster/action.yaml
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
Fixes #N/A 
This PR drops the instance profile creation from the "Getting Started Guide" cloudformation policy in favor of auto-generated instance profiles in `EC2NodeClasses`
> docs: Drop instance profile creation from policy

- hack/github/community-contributors.sh
Fixes #N/A 
Exclude APICodeGen in community-contributors.sh so it's not counted as an external contributor.
Ran community-contributors.sh.
> chore: Exclude APICodeGen in community-contributors.sh

- website/content/en/preview/concepts/setup.md
- website/content/en/preview/reference/_index.md
- website/content/en/preview/reference/cloudformation.md
**Description**: This PR adds new documentation describing how CloudFormation is used to setup permissions needed by Karpenter to manage cloud and EKS resources. This is part of a larger effort to describe Karpenter requirements for those migrating existing clusters to use Karpenter.
> docs: Describe cloudformation.yaml for docs

- charts/karpenter/README.md
- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/configmap-logging.yaml
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
Fixes #N/A 
This change adds logging configuration values in the helm chart under the `logConfig` values block. You can now selectively disable the `logging-config` ConfigMap with `logConfig.enabled=false`. The global `logLevel` helm value now sets the `LOG_LEVEL` environment variable to configure the Karpenter controller log level. 
Also, with this change, combined with https://github.com/aws/karpenter-core/pull/553, Karpenter will now configure the logging ConfigMap to be mounted as a volumeMount in the container by default.
> chore: Add handling for v1beta1 logging configuration migration

- .github/actions/e2e/create-cluster/action.yaml
- .github/workflows/e2e-matrix.yaml
- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
This change adds the `cloudformation:DescribeStackResources` IAM permission to the CI policy so that the upgrade `create-cluster` action can succeed to update permissions.
> test: Provide IAM permission to `cloudformation:DescribeStackResources`

- .github/actions/e2e/create-cluster/action.yaml
Fixes #N/A 
This PR ensures that we don't fail if the instance profile creation fails because the instance profile already exists
> ci: Ensure that instance profile creation and assignment is idempotent

- charts/karpenter/README.md
- hack/docgen.sh
Fixes #N/A 
This change fixes the error in `make docgen` that was caused by the documentation directory move
> ci: Fix docgen failure due to directory move

- .github/workflows/release.yaml
Fixes #N/A 
Add permission in release workflow for GH release generation
> ci: Add permission in release workflow for GH release generation

- website/content/en/preview/concepts/disruption.md
Fixes #N/A 
This PR updates the disruption documentation to the v1beta1 APIs and conceptual terms. This change also re-organizes and reformats the document to be more clear with its headings and structure.
> docs: Update the disruption doc to v1beta1

- pkg/providers/launchtemplate/suite_test.go
- test/pkg/environment/aws/expectations.go
- test/pkg/environment/common/expectations.go
- test/suites/drift/suite_test.go
- test/suites/expiration/expiration_test.go
- test/suites/integration/emptiness_test.go
Fixes #4189 
We allow the stack tracing to be handled directly by GinkgoHelper() as we did in https://github.com/aws/karpenter-core/pull/578 instead of doing it manually by offset approach
```make presubmit```
> test: replaced offsets with GinkgoHelper()

- .github/actions/e2e/cleanup/action.yaml
Fixes #N/A 
This test change ensures that we delete _all_ instance profiles that have the cluster discovery tag during the `cleanup.yaml` composite action
> test: Fix cleanup of drift vpc elements

- Makefile
- tools/karpenter-convert/pkg/convert/convert.go
- tools/karpenter-convert/pkg/convert/convert_test.go
- tools/karpenter-convert/pkg/convert/testdata/nodeclass_no_amifamily.yaml
- tools/karpenter-convert/pkg/convert/testdata/nodetemplate_no_amifamily.yaml
- tools/karpenter-convert/pkg/convert/testdata/provisioner.yaml
Fixes #N/A 
This change sets the `amiFamily` in the NodeClass to be `AL2` if its undefined in the previous `Provisioner`
> chore: Hydrate AMIFamily with AL2 when using nil in Provisioner

- hack/release/release.sh
- hack/release/snapshot.sh
Fixes #4807  
This PR ensures that a release can not happen with a dirty commit.
Manual test w/ `echo`
> ci: ensure release can't be dirty

- go.mod
- go.sum
- pkg/controllers/nodeclaim/garbagecollection/machine_test.go
- pkg/controllers/nodeclaim/garbagecollection/nodeclaim_test.go
- pkg/controllers/nodeclaim/garbagecollection/suite_test.go
- pkg/providers/instance/instance.go
- pkg/providers/instance/nodeclass_test.go
- pkg/providers/instance/nodetemplate_test.go
- pkg/providers/instance/suite_test.go
Fixes #N/A 
This PR makes a change so that reconciliations do not fail if you create some NodePools and NodeClaims with v1beta1 and then choose to rollback to an earlier version of Karpenter where these concepts are not understood.
`make apply`
> fix: Handle rollback to earlier version of Karpenter

- website/content/en/preview/concepts/nodeclasses.md
Fixes #4841
This PR updates the `nodeclass` doc to fix some misses in field renaming with respect to `amiSelectorTerms` and `securityGroupSelectorTerms`
> docs: Fix field rename misses in the EC2NodeClass docs

- website/content/en/preview/concepts/_index.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/preview/upgrade-guide.md
Fixes #N/A 
This PR updates the documentation for the conceptual section index to align with v1beta1 APIs and concepts. This also re-organizes the doc and drops other details that are duplication in other places in the documentation
> docs: Update conceptual index doc to v1beta1 APIs and concepts

- examples/v1beta1/100-cpu-limit.yaml
- examples/v1beta1/al2-custom-ami.yaml
- examples/v1beta1/al2-custom-userdata.yaml
- examples/v1beta1/al2-kubelet-log-query.yaml
- examples/v1beta1/bottlerocket.yaml
- examples/v1beta1/br-custom-userdata.yaml
- examples/v1beta1/custom-family.yaml
- examples/v1beta1/general-purpose.yaml
- examples/v1beta1/large-instances.yaml
- examples/v1beta1/multiple-arch.yaml
- examples/v1beta1/multiple-ebs.yaml
- examples/v1beta1/node-ttls.yaml
- examples/v1beta1/spot.yaml
- examples/v1beta1/ubuntu-kubelet-log-query.yaml
- examples/v1beta1/windows-custom-userdata.yaml
- examples/v1beta1/windows2019.yaml
- examples/v1beta1/windows2022.yaml
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodepools.md
Fixes #N/A 
This PR updates all of the files in the `examples/provisioner` directory to be v1beta1 examples. It also collapses the two separate directories into a single directory called `v1beta1`
> docs: Update examples to v1beta1

- .github/actions/e2e/create-cluster/action.yaml
- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
This PR updates the `create-cluster.yaml` action to create clusters with log retention enabled for 30d.
`/karepenter snapshot`
> ci: Enable control plane logging for e2e tests

- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
Changes `INTERRUPTION_QUEUE_NAME` to `INTERRUPTION_QUEUE` and adds env vars to upgrade test.
N/A
> ci: update env vars for e2e tests

- website/static/_redirects
Fixes #N/A 
This change fixes the docs redirects so that the previous route of "Upgrade Guide" gets routed appropriately. This change also adds the redirects for the `v0.32` version of the docs
> docs: Fix docs redirects

- pkg/apis/v1beta1/labels.go
- pkg/providers/instance/instance.go
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/preview/reference/cloudformation.md
- website/content/en/preview/upgrading/v1beta1-controller-policy.json
Fixes #N/A 
This change enforces that `karpenter.k8s.aws/ec2nodeclass` is the tag that is used for tagging instances and entities provisioned by the AWS cloudprovider's EC2NodeClass
`make apply`
> fix: Enforce `karpenter.k8s.aws` tags on instance profiles and instances

- .github/workflows/e2e.yaml
Fixes #N/A 
This ensures that the generated cluster name contains a hyphen instead of a slash since slashes aren't allowed
> test: Fix cluster name containing slash

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/providers/launchtemplate/nodeclass_test.go
- test/suites/beta/drift/suite_test.go
- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
This PR bumps `karpenter-core` to the latest which also contains validations built-in to the OpenAPI spec as well as a change to the ObjectMeta type for the `v1beta1.NodeClaimTemplate`
> chore: Bump `karpenter-core` to latest

- website/content/en/docs/troubleshooting.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.27/troubleshooting.md
- website/content/en/v0.28/troubleshooting.md
- website/content/en/v0.29/troubleshooting.md
- website/content/en/v0.30/troubleshooting.md
- website/content/en/v0.31/troubleshooting.md
Fixes #4629 
Add section regarding c1.medium and m1.small swap provisioning failures to the troubleshooting doc.
N/A, just a doc update.
- [] No
> docs: Add section regarding c1.medium and m1.small swap provisioning failures.

- .github/pull-request-template.md
- README.md
As the project doesn't include the CONTRIBUTING.md, a clear guide on where to find the contribution guidelines would make it easy for developers who want to get involved with the Karpenter project. 
> docs: Add contribution info

- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/v1beta1/ec2nodeclass.go
- pkg/apis/v1beta1/ec2nodeclass_validation.go
- pkg/apis/v1beta1/ec2nodeclass_validation_cel_test.go
- pkg/apis/v1beta1/ec2nodeclass_validation_webhook_test.go
- tools/karpenter-convert/pkg/convert/convert.go
Fixes #N/A 
Disallow `owner` from being set with `tags` in `amiSelectorTerms`. This doesn't make sense in a term since tags are private to the owner.
> chore: Restrict owner key in `amiSelectorTerms` from being set with tags

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/pkg/environment/common/environment.go
- test/pkg/environment/common/expectations.go
- test/suites/beta/expiration/expiration_test.go
Fixes #N/A 
This PR adds Integration E2E tests for the beta release
> test: Add Expiration testing for E2E for v1beta1

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/suites/beta/chaos/suite_test.go
Fixes #N/A 
This PR adds Chaos E2E tests for the beta release
> test: Add Chaos testing for E2E for v1beta1

- .github/workflows/e2e-upgrade.yaml
- test/cloudformation/iam_cloudformation.yaml
- test/pkg/environment/aws/environment.go
- test/pkg/environment/aws/expectations.go
- test/pkg/environment/common/monitor.go
- test/suites/alpha/drift/suite_test.go
- test/suites/alpha/expiration/expiration_test.go
- test/suites/alpha/integration/ami_test.go
- test/suites/alpha/integration/extended_resources_test.go
- test/suites/alpha/integration/kubelet_config_test.go
- test/suites/alpha/integration/utilization_test.go
- test/suites/alpha/machine/garbage_collection_test.go
- test/suites/alpha/scale/deprovisioning_test.go
- test/suites/beta/drift/suite_test.go
- test/suites/beta/integration/ami_test.go
- test/suites/beta/integration/cni_test.go
- test/suites/beta/integration/emptiness_test.go
- test/suites/beta/integration/extended_resources_test.go
- test/suites/beta/integration/instance_profile_test.go
- test/suites/beta/integration/kubelet_config_test.go
- test/suites/beta/integration/scheduling_test.go
- test/suites/beta/integration/utilization_test.go
Fixes #N/A 
- This PR updates the IAM Cloudformation permissions used for the permission boundary for the GithubActions role.
- This PR also updates test that is run during the upgrade test to be `Beta/Integration`
- It updates the Monitor to handle watching nodes that are owned by NodePools so consolidation tests work
- It updates bugs in the Integration test cases
- It merges the Utilization test case/suite into the Integration test suite
- The cloudformation policy had to be condensed here to avoid going over the managed instance profile character limit
> test: Fix E2E test permissions, upgrade, consolidation, and integration tests

- test/suites/alpha/drift/suite_test.go
- test/suites/alpha/expiration/expiration_test.go
Fixes #N/A 
Fixes an inconsistency in logic where we were using the new v1beta1 taint logic with v1alpha APIs.
make presubmit, test with e2e
> test: use legacy taint logic for disruption

- .github/workflows/e2e-matrix.yaml
- test/suites/beta/expiration/suite_test.go
Fixes #N/A 
This change drops the Utilization and Scale test suites from the matrix run and fixes a bug in the Expiration test for Beta.
> chore: Add more E2E test fixes for the Beta Suites

- .github/actions/upload-artifact/action.yaml
- .github/workflows/approval-comment.yaml
- .github/workflows/codegen.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pr-snapshot.yaml
- .github/workflows/publish-test-tools.yaml
- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
- .github/workflows/stale.yaml
- .github/workflows/sweeper.yaml
Fixes #N/A 
Reading GH doc samples, it appears the read contents is no longer required to check out the repo. 
I suspect this will break things, as testing these permissions is hard. 
1. Will test the snapshot workflow after merging
1. I'm doing the release there, and will feel the pain myself :) 
2. Other workflows occur on merge/cron, I'll fix in response.
> chore: Audited and documented permissions for gha

- website/content/en/preview/faq.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
Fixes #N/A 
Bump the K8s version used in the "Getting Started Guide" to 1.28 as well as other references to "1.27" version in docs
> docs: Bump k8s version in docs to `1.28`

- website/config.yaml
- website/content/en/preview/faq.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
Fixes #N/A 
This changes makes it so that you just need to update the `latest_k8s_version` parameter inside of the `config.yaml` file to update the latest version of K8s across the docs.
> docs: Make the latest K8s version to a parameter

- charts/karpenter/templates/configmap-logging.yaml
- charts/karpenter/templates/configmap.yaml
- charts/karpenter/templates/deployment.yaml
- charts/karpenter/values.yaml
- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
This change updates the ordering of helm values for evaluation in the chart to ensure that the old values are always considered first. This ensures that the defaults that are specified in the default `values.yaml` file do not override any existing values were set by the user on a previous version.
Note that this PR also contains a breaking change to defaults for log encoding. If you did not previously set the log encoding for Karpenter and relied on the default log encoding of `console`, this will now be changed in the helm chart to `json`, unless this value is updated by specifying the `logConfig.logEncoding` value like `--set logConfig.logEncoding=console`
By submitting this pull request, I …
> BREAKING: Fix helm ordering of values and set default log encoding to `json`

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
Fixes #4845 
- Conformance tests should not be triggering slack messages for all suites. Stop upgrade suite from firing messages
- N/A
> fix: Stop firing conformance testing Notifications 

- pkg/cloudprovider/drift.go
- pkg/cloudprovider/machine_test.go
- pkg/cloudprovider/nodeclaim_test.go
- pkg/fake/utils.go
- test/suites/alpha/drift/suite_test.go
- test/suites/beta/drift/suite_test.go
Fixes #N/A 
- Incompatible requirements of instance types on AMIS causing drift not to occur
- `make test`
- E2E tests are run locally 
> fix: Fix bug in drift ami resolution with incompatible requirements

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
Adds the ability to run workflows in different regions as well as a mechanism to disable cluster cleanup for runs
> ci: Add cleanup and region parameters to workflow runs

- .github/workflows/e2e-conformance-trigger.yaml
Fixes #N/A 
Fix miss on adding cleanup and region inputs to conformance test trigger
> ci: Fix conformance testing failure with inputs

- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/v1beta1/ec2nodeclass.go
- pkg/apis/v1beta1/ec2nodeclass_validation_cel_test.go
Fixes #N/A 
- Should not allow empty role to be set on a EC2NodeClass
> chore: Not allowing empty role to be set on EC2NodeClass

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/actions/e2e/install-karpenter/action.yaml
- .github/workflows/e2e-cleanup.yaml
Fixes #N/A 
This change ensures that the E2ECleanup workflow has permissions to use the OpenID connect token as well as configures credentials to talk to the AWS test account.
This also drops configuring credentials in composite actions in favor of having the credentials configured once at the workflow level.
> ci: Fix cleanup permissions and configure credentials

- .github/workflows/approval-comment.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e-version-compatibility-trigger.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Wanted to update conformance testing to version compatibility to be more descriptive on the testing 
- N/A
> ci: Change conformance testing to versionCompatibility

- website/content/en/preview/concepts/disruption.md
Fixes #N/A 
Update the docs to reference the `karpenter.sh/disruption:NoSchedule` taint rather than the `node.kubernetes.io/unschedulable` cordon taint. 
> docs: add docs with new taint

- test/pkg/environment/aws/expectations.go
- test/pkg/environment/common/expectations.go
- test/suites/alpha/scale/deprovisioning_test.go
- test/suites/beta/scale/deprovisioning_test.go
> test: fix some scale test bugs

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-version-compatibility-trigger.yaml
Fixes #N/A 
- E2EVersionCompatibilityTrigger is getting throttled on cluster creation. To prevent test failure, the E2E test will be limited to run two suites are a time for each k8s version. 
- https://github.com/aws/karpenter/actions/runs/6686719803
- N/A
> ci: Limit parallelism for `E2EVersionCompatibilityTrigger`

- tools/karpenter-convert/cmd/karpenter-convert/main.go
- tools/karpenter-convert/pkg/convert/convert.go
- tools/karpenter-convert/pkg/convert/convert_test.go
- tools/karpenter-convert/pkg/convert/testdata/nodetemplate_launch_template_name.yaml
- tools/karpenter-convert/pkg/convert/testdata/unknown_kind.yaml
Fixes #N/A 
Throw an error to the user of `karpenter-convert` when trying to convert an `AWSNodeTemplate` with a `spec.launchTemplate` since this conversion is currently unsupported
> chore: Error on `spec.launchTemplate` for `karpenter-convert`

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
This PR bumps the e2e testing to `v0.164.0` to apply: https://github.com/eksctl-io/eksctl/pull/7217 which fixes an error that we were seeing in cleanup where there would be a call on a closed channel that was closed too early
> ci: Bump eksctl to v0.164.0

- website/content/en/preview/reference/threat-model.md
Fixes #N/A 
**Description**'
Karpenter `v0.32.0` adds the ability for the controller to generate instance profiles based on the role passed into the `EC2NodeClass`. This PR adds doc information to the threat model around how new threats surfaced through this permission are mitigated.
> docs: Add updated information for threat model

- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/v1beta1-migration.md
Fixes #N/A 
This change updates the docs so that `v0.31.2` is the version that is called out as the version to use for rollback from `v0.32.0`
> docs: Add callouts for `v0.31.2` version for rollback

- .github/workflows/release.yaml
Fixes #N/A 
This removes the `install-helm` action from the `release.yaml` to ensure that we don't get a dirty commit
> ci: Remove e2e install helm action for `release.yaml`

- .github/actions/e2e/install-helm/action.yaml
- .github/workflows/release.yaml
Fixes #N/A 
Pins helm version to `v3.12.3` in the release process since the ubuntu version used by GHA is still using a broken helm version right now (`v3.13.0`)
> ci: Pin helm version for `release.yaml`

- hack/docs/metrics_gen_docs.go
- website/content/en/preview/reference/metrics.md
- website/content/en/v0.32/reference/metrics.md
Fixes #N/A 
This PR updates the doc that describes the metrics for v0.32.0 to align with the correct naming
> docs: Update naming of `v0.32` metrics

- website/content/en/docs/_index.md
- website/content/en/docs/reference/metrics.md
- website/content/en/preview/_index.md
- website/content/en/v0.32/_index.md
Fixes #N/A 
This PR updates the top-level index file to no longer refer to Provisioners but refer to NodePools and EC2NodeClasses instead
> docs: Update the top-level index file

- charts/karpenter/templates/deployment.yaml
- charts/karpenter/templates/secret-webhook-cert.yaml
- charts/karpenter/templates/service.yaml
Fixes #4979 
An extra line was added when disabling webhooks on the Karpenter deployment. Additionally, additional ports were exposed while disabling the webhook that shouldn't be exposed when Karpenter is not running the webhook.
`make apply` with `--set webhook.enabled=false`
> fix: Fix disabling webhooks in helm chart

- pkg/providers/instancetype/instancetype.go
Fixes #N/A 
N/A
- A new SupportedUsageClass was released called `capacity-block`. This maps to a capacity-type in Karpenter. This was throwing an error since Karpenter was not aware of `capacity-block`, only `on-demand` and `spot`. 
```
karpenter-b8b6f98dc-l8r7r controller {"level":"ERROR","time":"2023-10-31T17:48:41.639Z","logger":"controller.disruption","message":"Received unknown capacity type capacity-block for instance type p5.48xlarge","commit":"4a56c66"}
```
```
> aws ec2 describe-instance-types --filters "Name=instance-type,Values=p5.48xlarge" --region us-east-2 | jq -r '.InstanceTypes[] .SupportedUsageClasses'
[
"capacity-block",
"on-demand",
"spot"
]
```
`make apply` observed no more error logs
By …
> fix: do not error on capacity-block capacity-type

- pkg/providers/instance/instance.go
- pkg/providers/instancetype/nodeclass_test.go
- pkg/providers/instancetype/nodetemplate_test.go
Fixes #N/A 
- Karpenter should deprioritize metal instance types since they are the same price as non-metal and take a lot longer to startup. EC2 previously only had instance types of the form `x.metal`. EC2 recently added metal sized variants `x.metal-24xl` and `x.metal-48xl`. The size variants were not being deprioritized properly, only `x.metal` was being deprioritized. This change checks if `metal` is contained anywhere in the size.
> fix: deprioritize metal-24xl and metal-48xl in addition to non-suffixed metal instance types

- website/content/en/preview/faq.md
Fixes Issue [#4944](https://github.com/aws/karpenter/issues/4944)
**Description** Added a link to the Karpenter [Reporting Security Issues](https://github.com/aws/karpenter/security/policy) page from the FAQ.
> Add FAQ info for security issues

- test/hack/cleanup/main.go
Fixes #N/A 
- Add NodePool tag to be able clean-up v1beta1 launched instances 
> ci: Add NodePool tag for sweeper

- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
**Description** There have been requests for more information about how the [Getting Started with Karpenter](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/) guide sets up permissions. This PR adds a pointer to the new [CloudFormation](https://karpenter.sh/docs/reference/cloudformation/) page to explain the setup that the `cloudformation.yaml` file does in that guide.
> Add cloudformation pointer to getting started

- test/pkg/environment/aws/environment.go
- test/suites/beta/integration/tags_test.go
Fixes #N/A 
- Add cluster tag for instance profiles to allow cleanup by the sweeper 
- N/A
> test: Instance profiles on EC2NodeClass to allow for cleanup 

- .github/actions/e2e/cleanup/action.yaml
- test/hack/cleanup/go.mod
- test/hack/cleanup/go.sum
- test/hack/cleanup/main.go
Fixes #N/A 
- Consolidate the clean-up logic for the E2E tests to the clean-up script that is used by the sweeper, such that all clean-up logic is in one place.
- Tested in a forked account 
> ci: Combine E2E clean-up with sweeper

- .github/actions/e2e/cleanup/action.yaml
Fixes #N/A 
- The `go.mod` and `go.sum` was used from the cache as opposed to installing the packages.
- Forked Repo
> ci: Fix cleanup script for go cache

- Makefile
- test/pkg/environment/aws/expectations.go
Fixes #N/A 
https://github.com/aws/karpenter/actions/runs/6748112420/job/18345778936 Failed to run instances due to an invalid instance profile name, but this was confirmed to be a valid name. This may be due to eventual consistency delays with IAM. 
FOCUS="GarbageCollection" TEST_SUITE="nodeclaim" make e2etests
> test: add in IAM instance profile wait for RunInstances() 

- website/content/en/docs/concepts/nodepools.md
- website/content/en/preview/concepts/nodepools.md
- website/content/en/v0.32/concepts/nodepools.md
Fixes #N/A 
Removes an older docs note for webhook defaulting for `karpenter.sh/capacity-type`. This resolves a docs issue that was mentioned in #5015
> docs: Fix old defaulting note for capacity-type

- .github/workflows/ci-test.yaml
- hack/toolchain.sh
Fixes #N/A 
- Update to use https://github.com/mattn/goveralls directly
> ci: Use `mattn/goveralls` instead of `shogo821/goveralls`

- .github/workflows/ci-test.yaml
Fixes #N/A 
- Due the multiple runs of the CI-test goveralls was failing to send reports. 
- N/A
> ci: Scope goveralls to one k8s version of `ci-test` 

- website/content/en/docs/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh
- website/content/en/preview/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh
- website/content/en/v0.32/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh
Fixes #N/A 
- Customers migrating from CAS to Karpenter are seeing permission issues as instanceProfile changes were not included
> docs: Add instanceProfile to CAS Migration guide

- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/v1beta1/ec2nodeclass.go
- pkg/apis/v1beta1/ec2nodeclass_validation.go
- pkg/apis/v1beta1/ec2nodeclass_validation_cel_test.go
- pkg/apis/v1beta1/ec2nodeclass_validation_webhook_test.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/ami_test.go
- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/v0.32/concepts/nodeclasses.md
Fixes #5013 
- Karpenter should allow tags and owner to be placed for `amiSelectorTerm` for shared AMIs between accounts.
> fix: Allow tags and owners for private AMIs

- .github/actions/e2e/create-cluster/action.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
This PR adds support for the E2E test suites to have private cluster creation and a PrivateCluster suite. Currently, this private cluster suite will just run the Integration test suite on private clusters; however, we should have follow-up PR that selects a subset of tests from across all test suites to run against a private cluster
> test: Add support for E2E testing for private clusters

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
This PR disables the `PrivateCluster` suite until we figure out how to handle the private networking apply that GHA needs to do in order to get the install of Karpenter onto the private cluster working
> test: Disable PrivateCluster suite until private networking works

- pkg/providers/instance/instance.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/launchtemplate/suite_test.go
- test/pkg/environment/aws/expectations.go
- test/suites/integration/tags_test.go
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #4550
This PR adds tags to the `spot-instance-requests` resource type when launching instances so that these resources are scoped to Karpenter and are easily tracked by users who are tracking resources through tags.
> feat: Add support for `spot-instance-requests` tagging for launched instances

- website/content/en/docs/upgrading/v1beta1-migration.md
- website/content/en/preview/upgrading/v1beta1-migration.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
Fixes #N/A 
This PR adds the note for `karpenter.k8s.aws/instance-pods` being dropped in v1beta1
> docs: Add note on instance-pods dropped in v1beta1

- website/content/en/docs/upgrading/v1beta1-migration.md
- website/content/en/preview/upgrading/v1beta1-migration.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
Fixes #N/A 
This change re-orders the v1beta1 migration guide so that the migration of the CRDs from alpha to beta comes first
> docs: Reorder v1beta1 migration guide to place CRD migration first

- pkg/controllers/nodeclass/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
- pkg/utils/nodeclass/nodeclass.go
- pkg/utils/nodeclass/suite_test.go
Fixes #4738
- Karpenter should still support the comma-delimited list with spaces in it. , this config works with karpenter <v0.31:
```
subnetSelector:
aws-ids: subnet-123, subnet-456, subnet-789
```
> fix: Parsing Selector IDs and Names with spaces

- test/pkg/environment/aws/expectations.go
- test/suites/drift/suite_test.go
Fixes #N/A 
- We are seeing failures on our [E2EVersionCompatibility](https://github.com/aws/karpenter/actions/runs/6844076381) tests for AMI drift testing 
- The test was requesting 1.28 EKS AMI, however that should depend on the k8s version 
> test: Fix Kubernetes Version for AMI drift

- tools/karpenter-convert/README.md
When running `go install` to install karpenter-convert with an older go version without the `slices` package (introduced in go 1.21), we get the following error: `package slices is not in GOROOT`
Upgrading to go 1.21 fixes the problem
> docs: update README.md to reflect go version requirement

- .github/actions/e2e/create-cluster/action.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Move installing prometheus and karpenter in create cluster for better abstraction 
- Manually tested in a forked repo
> ci: Move prometheus and karpenter install to create_cluster action

- pkg/apis/apis.go
- pkg/cloudprovider/cloudprovider.go
- pkg/operator/operator.go
- pkg/test/environment.go
- test/pkg/environment/aws/environment.go
- test/suites/integration/scheduling_test.go
Fixes #N/A 
This PR moves the `init` statements that were present in the `cloudprovider.go` file to put them in the top-level `operator.go` file since all operator concepts rely on `karpenter-core`. This makes the dependencies required here clearer and serves as a paradigm that will be used going forward for declaring all base-level dependencies in `operator.go` files
> chore: Move `init()` to operator.go

- hack/toolchain.sh
Fixes #N/A 
This change bumps the `toolchain.sh` version of `envtest` to `1.28.x` so that it matches the version that is used over in `karpenter-core`: https://github.com/aws/karpenter-core/blob/main/hack/toolchain.sh#L4
`arm64/darwin` is now supported by kubebuilder as described here: https://github.com/kubernetes-sigs/kubebuilder/pull/2785, https://github.com/kubernetes-sigs/kubebuilder/issues/1932#issuecomment-1112564792
> ci: Bump the envtest default version to 1.28.x

- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
This PR edits the docs to move the placement of the upgrade warning around instance profiles around the "Upgrading to v0.32.x+" section
> docs: Fix the placement of the upgrade guide warning for instance profiles

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
Fixes #N/A 
This PR adds the `needs-triage` issue to each of the issue templates. This enables us to filter for issues that still need to have their category verified. 
N/A
> chore: add needs-triage to issue templates

- .github/actions/authenticate-ghcr/action.yaml
- .github/actions/commit-status/end/action.yaml
- .github/actions/commit-status/start/action.yaml
- .github/actions/download-artifact/action.yaml
- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/create-cluster/action.yaml
- .github/actions/e2e/dump-logs/action.yaml
- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/install-prometheus/action.yaml
- .github/actions/e2e/slack/notify/action.yaml
- .github/actions/e2e/upgrade-crds/action.yaml
- .github/actions/install-deps/action.yaml
- .github/workflows/approval-comment.yaml
- .github/workflows/ci-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/codegen.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/deflake.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pr-snapshot.yaml
- .github/workflows/publish-test-tools.yaml
- .github/workflows/release.yaml
- .github/workflows/resolve-args.yaml
- .github/workflows/snapshot.yaml
- .github/workflows/stale.yaml
- .github/workflows/sweeper.yaml
Fixes #5112
This PR pins action versions to specific commits SHAs as per [GitHub's security recommendations](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
> ci: pin gha versions to hashes

- .github/actions/e2e/create-cluster/action.yaml
- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/troubleshooting.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/preview/getting-started/migrating-from-cas/_index.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.29/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/v0.29/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.29/troubleshooting.md
- website/content/en/v0.30/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/v0.30/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.30/troubleshooting.md
- website/content/en/v0.31/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/v0.31/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.31/troubleshooting.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/v0.32/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.32/troubleshooting.md
Fixes #5099
This doc change is meant to aid in bringing awareness to a requirement for running Windows nodes. Windows nodes have the kube-proxy binary running on the node, and as such, the node requires the necessary RBAC cluster permissions to allow access to the resources required by the `kube-proxy` component. Therefore, anyone intending to have Karpenter launch Windows nodes should specify this group. Without this change when creating the Karpenter node role, service communication and DNS resolution for pods fails.
Created a cluster and configured a cluster using the following snippet.
```
...
iamIdentityMappings:
- arn: "arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/KarpenterNodeRole-${CLUSTER_NAME}"
username: …
```
> docs: Add note about RBAC permissions requirement for Windows support

- go.mod
- go.sum
- pkg/cloudprovider/cloudprovider.go
Fixes #N/A 
This PR drops the `nodepool.Key` that was used to differentiate NodePools from Provisioners when they were modeled as the same entity in memory. Now that they are no longer modeled together, we can drop this key concept
> chore: Drop NodePool Owner Key from codebase

- .github/workflows/approval-comment.yaml
- .github/workflows/codegen.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e-version-compatibility-trigger.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pr-snapshot.yaml
- .github/workflows/publish-test-tools.yaml
- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
- .github/workflows/sweeper.yaml
Fixes #N/A 
Ensure that permissions are explicitly called out for callers of workflows, including callers to `workflow_run`. This PR also ensures that the permissions are scoped to the job rather than the workflow to enforce tighter scoping for permissions.
> ci: Ensure workflow callers to `workflow_run` describe permissions

- test/suites/scale/provisioning_test.go
- test/suites/scale/suite_test.go
Fixes #N/A 
- Currently, our scale tests are experiencing a race condition between the object read and writes for updating the daemonSet `aws-node` after each test run.  The patch operation for enabling and disabling of the prefix delegation after each test creates a race between the object that's being written and the object that received for updating, causing the prefix delegation not to be enabled.   
- N/A
> test: Fix Prefix Delegation enabling race condition

- test/suites/integration/scheduling_test.go
Fixes #N/A 
- We are seeing that nodes launched by karpenter and entering a race condition for pods scheduling on the nodes. Three nodes were expected to be launched with pods having  topology spread with a maxSkew of one. `kube-scheduler` assigned one node with two pods. This is caused if there is a delay with one of the nodes coming up.
- make e2etests
> test: Fix Zonal Topology Spread E2E test

- website/content/en/docs/concepts/scheduling.md
- website/content/en/preview/concepts/scheduling.md
- website/content/en/v0.28/concepts/scheduling.md
- website/content/en/v0.29/concepts/scheduling.md
- website/content/en/v0.30/concepts/scheduling.md
- website/content/en/v0.31/concepts/scheduling.md
- website/content/en/v0.32/concepts/scheduling.md
Fixes #N/A 
This PR adds the `labelSelector` field to the topology spread constraint example under advanced scheduling in the docs. Although it opts to not define a selector, indicating that the field should exist avoid confusion in issues like #5171.
N/A
> docs: add label selector to workload topology spread constraint example

- .github/workflows/e2e-version-compatibility-trigger.yaml
Fixes #N/A 
This changes increases the frequency of our version compatibility testing to run on both Monday and Thursday
> ci: Run version compat on Thursday as well

- pkg/fake/sqsapi.go
- website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/upgrading/v1beta1-controller-policy.json
- website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/preview/reference/cloudformation.md
- website/content/en/preview/upgrading/v1beta1-controller-policy.json
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/cloudformation.yaml
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.32/upgrading/v1beta1-controller-policy.json
Fixes #N/A 
This drops the `sqs:GetQueueAttributes` permission from the default IAM policy that is shipped with the Getting Started Guide. This permission isn't needed since we only get the QueueURL of the queue which we can achieve through a different permission scope.
> chore: Drop `sqs:GetQueueAttributes` from cloudformation policy

- website/content/en/docs/concepts/scheduling.md
- website/content/en/preview/concepts/scheduling.md
- website/content/en/v0.28/concepts/scheduling.md
- website/content/en/v0.29/concepts/scheduling.md
- website/content/en/v0.30/concepts/scheduling.md
- website/content/en/v0.31/concepts/scheduling.md
- website/content/en/v0.32/concepts/scheduling.md
Fixes #5194 
Adds a note in the docs that Karpenter supports several deprecated labels, translating them to their stable counterparts under the hood.
N/A
> docs: note about deprecated label support

- test/hack/resource/clean/main.go
- test/hack/resource/count/main.go
- test/hack/resource/pkg/resourcetypes/eni.go
- test/hack/resource/pkg/resourcetypes/instance.go
- test/hack/resource/pkg/resourcetypes/instanceprofile.go
- test/hack/resource/pkg/resourcetypes/launchtemplate.go
- test/hack/resource/pkg/resourcetypes/oidc.go
- test/hack/resource/pkg/resourcetypes/resourcetypes.go
- test/hack/resource/pkg/resourcetypes/securitygroup.go
- test/hack/resource/pkg/resourcetypes/stack.go
- test/hack/resource/pkg/resourcetypes/vpc_endpoint.go
Fixes #N/A 
- Differentiate  between global and regional resources for the sweeper and counter for the metrics that are pushed to Timestream.  
- N/A
> ci: Adjust regions for metrics of resource counter and sweeper

- .golangci.yaml
- go.mod
- go.sum
- pkg/providers/instance/instance.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/nodeclass_test.go
- pkg/providers/instancetype/nodetemplate_test.go
Fixes #N/A 
Cherry picks the following commits into the v0.31.3 release and bumps karpenter-core.
- https://github.com/aws/karpenter/pull/4991
- https://github.com/aws/karpenter/pull/4994
> chore: release v0.31.3

- test/suites/integration/ami_test.go
- test/suites/integration/kubelet_config_test.go
Fixes #N/A 
This PR reverts the change made in #5210. New Ubuntu AMIs were released today which appear to fix the issue that prompted us to pin the AMI.
A node was spun up with the following ami:
```
ubuntu-eks/k8s_1.28/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20231204.1
```
and successfully joined the cluster.
> test: unpin ubuntu AMIs

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- This change pins the version that is used for the pre-upgrade step to contain the change that involves updating the create cluster step (https://github.com/aws/karpenter/pull/5203)
- N/A
> ci: Pin e2e-upgrade for E2E action update

- pkg/providers/amifamily/ami.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/providers/subnet/subnet.go
- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #5219 
Dropping support for comma-delimited lists on subnetSelectorTerms, securityGroupTerms, and amiSelectorTerms. 
Users will now need to specify each tag key and value for all tags that may start with the same key 
Before 
```
amiSelectorTerms:
- test-1: "ami-name1,ami-name2"
```
After
```
amiSelectorTerms:
- test-1: "ami-name1"
- test-1: "ami-name2"
```
- `make presubmit` and `/karpenter snapshot`
> BREAKING CHANGE: Drop comma-delimited-list on tags for `subnetSelectorTerms`, `securityGroupSelectorTerms`, and `amiSelectorTerms`

- Makefile
- go.mod
- go.sum
Fixes #N/A 
Update kubernetes-sigs/karpenter.
> chore: use karpenter@v0.33.0

- test/suites/scale/deprovisioning_test.go
Fixes #N/A 
- Scale tests were failing as expired nodes were not being validated to see if the new nodes were properly launched and cleanup. This was impacting the next test.
> test: Expect nodes to be spun up on Expiration Scale test

- pkg/utils/nodeclass/nodeclass.go
- pkg/utils/nodeclass/suite_test.go
Fixes #N/A 
- Convert CDL values on tags into multiple selectors
- This will affect subnet, security group, and AMI selectors
> chore: Convert CDL values on tags for SelectorTerms 

- pkg/utils/nodeclass/nodeclass.go
Fixes #N/A 
- To ensure that values are properly converted, we will enforce ordering on converted tags
> chore: Update enforce ordering on converted values for `karpenter-convert`

- test/hack/resource/clean/main.go
- test/hack/resource/count/main.go
- test/hack/resource/go.mod
- tools/allocatable-diff/go.mod
- tools/allocatable-diff/go.sum
- tools/allocatable-diff/main.go
- tools/kompat/cmd/kompat/main.go
- tools/kompat/go.mod
Fixes #N/A 
This change updates the tools directory to use the correct naming for `karpenter-provider-aws`
> chore: Rename `karpenter-provider-aws` in tools

- .github/actions/e2e/dump-logs/action.yaml
Fixes #N/A 
This PR updates the `dump-logs` action to refer to the `kube-system` namespace rather than the `karpenter` namespace since the E2E tests are now deploying Karpenter to the `kube-system` namespace since #5192
> ci: Fix dump logs action to refer to the `kube-system` namespace

- .github/workflows/codegen.yaml
- hack/codegen.sh
Fixes #N/A 
This PR updates CodeGen so that it won't fail when the branch is left around after a merge.
This change also allows you to manually trigger the CodeGen by running a `workflow_dispatch` operation against the action.
> ci: Fix codegen failure when the branch exists

- .github/actions/e2e/slack/notify/action.yaml
- .github/workflows/codegen.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
This PR adds handling to send slack messages over to the notification channel when the codegen for Karpenter fails
> ci: Notify slack of `codegen` failures

- .github/actions/e2e/install-karpenter/action.yaml
Fixes #N/A 
- E2E testing is failing due daemonSet not having the same level of security context (vpc-cni and pod identity)
Note: This PR will follow-up with a change that checks the warning that's output if Karpenter were to apply pods that weren't in the restricted bucket so that we ensure that Karpenter always adheres to the restricted policy
> ci: Update pod-security context for `kube-system` namespace

- charts/karpenter/README.md
- go.mod
- hack/docs/metrics_gen_docs.go
- pkg/operator/operator.go
- pkg/operator/suite_test.go
- website/content/en/preview/reference/metrics.md
Fixes #N/A 
This updates the `build_info` metric that was added in #5213 so that it uses `commit` as a label to match the logging. It also adds testing and fixes the break in `make docgen` for not having a subsystem
> chore: Update the `build_info` metric label naming and tests

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/operator/operator.go
- pkg/operator/suite_test.go
Fixes #N/A 
This moves the original PR for the #5213 for the `build_info` metric over to `kuberntes-sigs` by using the new version that leverages it.
> chore: Move `build_info` metric to `kubernetes-sigs` and bump

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- The old commit was not creating the E2E upgrade cluster with the updated resources we are now using (pod-identity-association, and pod-identity add-on), therefore the upgrade step was not properly upgrading the resources
- N/A
> chore: Bump E2E upgrade tests

- .github/actions/e2e/install-prometheus/action.yaml
- .github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
- Use IRSA for Prometheus pods as the container dependency on AWS does not support pod identity. The AWS package should be at v1.47.11 for support. 
- https://github.com/prometheus-operator/prometheus-operator/blob/3c13f057abc914f841f8675eefab8e46a8ad73ae/go.mod#L64
- N/A
> ci: Use IRSA for Prometheus in E2E environment 

- test/hack/resource/pkg/resourcetypes/vpc_endpoint.go
Fixes #N/A 
- VPC endpoint is not a global resources in AWS, and should be tracked as such
- N/A
> ci: Make VPC endpoints a regional resources

- hack/release/common.sh
- hack/release/snapshot.sh
Fixes #N/A 
Calls to the pull-through cache are unneeded since this was only do local cache hydration into the account. Since we are pulling snapshots from a different ECR anyways, there's no need to do pull-through cache hydration here on release.
> ci: Drop unneeded calls to pull-through cache

- .github/workflows/codeql-analysis.yaml
- .github/workflows/e2e-soak-trigger.yaml
- .github/workflows/resource-count.yaml
Fixes #N/A 
This change adds CodeQL scanning for Github Actions specified in this repo to check for things like Github Action pinning and script injection. More details here: https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure/#2-enable-code-scanning-for-workflows
Create script injection vulnerabilities on fork and test that CodeQL can catch these
> ci: Enable codeql for github actions

- pkg/controllers/nodeclass/suite_test.go
- pkg/fake/ec2api.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
Fixes #5239 
Updates instance type discovery to use zones from the instance type offerings rather than via `DescribeAvailabilityZones`. This maintains a single source of truth for zones while also discovering non-az zones (e.g. local zones).
Note: originally local-zone e2e testing was going to be included here, this is going to be decoupled into a separate PR (coming soon).
> fix: discover instances in all available zones

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
Fixes #N/A 
Adds a line at the top of bug and feature issue templates so that users can redirect to upstream karpenter for cutting issues.
> update templates to point to kubernetes-sigs

- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
This change drops provisioning the Github OIDC provider into our AWS account from this CloudFormation file since it is being provisioned by a different mechanism
> ci: Drop provisioning OIDC provider for Github from IAM CF

- .github/workflows/codegen.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-soak-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pr-snapshot.yaml
- .github/workflows/release.yaml
- .github/workflows/resource-count.yaml
- .github/workflows/snapshot.yaml
- .github/workflows/sweeper.yaml
- hack/release/common.sh
Fixes #N/A 
This migrates the ECR snapshot push repo to another account. This also updates the vars that are leveraged from the repository environment variables to ensure that every role that is auth-ed with has a unique account id, role, and region
> ci: Migrate private snapshot ECR to CI account and update vars
