- .github/actions/e2e/slack/notify/action.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
Remove PR notification in slack on `/karpenter snapshot` runs
> test: Remove PR notification in slack on snapshot runs

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
- .github/pull-request-template.md
Fixes #N/A 
* Combine issue template into a single text area. 
* Default to "no docs required" to minimize clicks in the default case.
> chore: Combine issue template sections

- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Enable cloudwatch metrics to fire on scale testing
> test: Enable cloudwatch metrics to fire on scale testing

- .github/workflows/e2e.yaml
Fixes #N/A 
- Fix workflow syntax error on boolean type
> test: Fix workflow syntax error on boolean type

- Makefile
- go.mod
- go.sum
Fixes #N/A 
Bumps karpenter-core to latest
> chore: Bump karpenter-core to latest

- website/content/en/preview/concepts/node-templates.md
- Add AWSNodeTemplate.status.amis  to the Node Templates enable configuration page
- [] No
> docs: Include AWSNodeTemplate.status.amis 

- Makefile
- hack/toolchain.sh
- pkg/apis/crds/karpenter.k8s.aws_awsnodetemplates.yaml
- pkg/apis/v1alpha1/awsnodetemplate_defaults.go
- pkg/apis/v1alpha5/provisioner.go
- pkg/batcher/batcher.go
- pkg/cloudprovider/cloudprovider.go
- pkg/controllers/nodetemplate/controller.go
- pkg/fake/ec2api.go
- pkg/fake/pricingapi.go
- pkg/fake/ssmapi.go
- pkg/operator/operator.go
- pkg/providers/amifamily/al2.go
- pkg/providers/amifamily/resolver.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/pricing/pricing.go
- pkg/providers/subnet/subnet.go
- pkg/test/environment.go
- pkg/webhooks/webhooks.go
Fixes #N/A 
- Update tools to use `@latest` 
- Except hugo because it won't build on anything > v0.110.0 🤷‍♂️ 
- make website
- make apply
> update tools to latest versions

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.28/faq.md
Fixes #4056 
This updates our FAQ to accurately reflect which kubernetes versions we test with in our e2e tests. 
- [] No
> docs: update supported versions in FAQ

- test/gha/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
GHA [updated their thumbprint](https://github.com/aws-actions/configure-aws-credentials/issues/357#issuecomment-1605290219) for OIDC provider token communication using the `configure-aws-credentials` action
> test: Update GHA thumbprint for OIDC

- .github/workflows/stale.yaml
Fixes #N/A 
- Update stalebot to close stale PRs
> chore: Update stalebot to close stale PRs

- .github/actions/e2e/install-prometheus/action.yaml
Fixes #N/A 
Uses rev-parse to get the commit from head.
- snapshot and manually
> test: add rev-parse into gitRef

- .github/actions/e2e/install-prometheus/values.yaml
Fixes #N/A 
Adds the job name for additional scrape configs
manually
> test: add job name for additional prometheus configs

- test/gha/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
- Add `sts:AssumeRole` for Root in IAM
```console
➜  cloudformation git:(add-trust-policy) ✗ aws cloudformation deploy --stack-name GithubActionsIAM \
--template-file iam_cloudformation.yaml \
--parameter-overrides "Repository=aws/karpenter" "PrometheusWorkspaceID=ws-d4d85b73-ac6d-4448-b858-363834e66ff4" Branches="refs/heads/main"\
--capabilities CAPABILITY_NAMED_IAM 
Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - GithubActionsIAM
```
> test: Add `sts:AssumeRole` for Root in IAM

- .github/workflows/stale.yaml
Fixes #N/A 
- Update stalebot labels to add back `roadmap`
> chore: Update stalebot labels to add back `roadmap`

- .github/actions/e2e/install-prometheus/values.yaml
Fixes #N/A 
Adds in the kubernetes_sd_configs for scrape configs.
- manually
> test: e2e prometheus endpoint metrics scraping

- website/content/en/docs/concepts/node-templates.md
- website/content/en/preview/concepts/node-templates.md
- website/content/en/v0.26/concepts/node-templates.md
- website/content/en/v0.27/concepts/node-templates.md
- website/content/en/v0.28/concepts/node-templates.md
Fixes #N/A 
- Fix guidance on ALB and `securityGroupSelector`
- [] No
> docs: Fix guidance on ALB and `securityGroupSelector`

- go.mod
- go.sum
> update to v0.29.0 karpenter-core

- hack/release/stable-pr.sh
> remove tekton from release script

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- failing on wrong workflow inputs
> test: e2e_upgrade for wrong inputs

- .github/actions/e2e/cleanup/action.yaml
Fixes #N/A 
- Need to add the version of eksctl
- 
> fix: clean_up script for EKSCTL

- ADOPTERS.md
Fixes #N/A 
Add Stone Pagamentos as a Karpenter adopter
N/a
> chore: add stone pagamentos to ADOPTERS.md

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- update to a new git-ref to take in new changes to GHA
> fix: E2E-Upgrade test failing due EKSCTL bug

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- fixing incorrect git ref 
> fix: E2E-Upgrade Git ref

- .github/workflows/E2E-matrix-trigger.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- test/README.md
Fixes #N/A 
- Added the option of us-west-2 and us-west-1 for when launching E2EMatrix 
> test: Expand Region Options for E2ETesting

- .github/workflows/e2e-scale-trigger.yaml
Fixes #N/A 
- Scale testing will now run in us-west-2
> test: Move scale testing into us-west-2

- test/cloudformation/grafana_cloudformation.yaml
- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
- Fix timestream IAM permissions needed for pushing metrics and Grafana talking to Timestream
Validation in Scale Testing dashboard
> test: Fix Timestream IAM Permissions

- .github/actions/e2e/slack/notify/action.yaml
- .github/workflows/e2e-conformance-trigger.yaml
Fixes 
- Expand the conformance testing suite to include all E2E test suites
- GHA was tested in a fork repo 
> test: Expand conformance testing

- website/content/en/preview/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
- website/content/en/v0.26/getting-started/getting-started-with-eksctl/karpenter-capacity-dashboard.json
- website/content/en/v0.27/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
- website/content/en/v0.28/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
- website/content/en/v0.29/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
Fixes #N/A 
Propagate changes in #4250 out to all docs directories
- Manual deploy and view of Grafana Dashboard
> docs: Propogate capacity dashboard changes throughout docs

- .github/workflows/e2e.yaml
Fixes #N/A 
- Stop notification for conformance testing
- Tested inside of forked repo 
> test: Stop notification for conformance testing

- ADOPTERS.md
Fixes #N/A 
Adding Logz.io to Karpenter Adopters
> Add lozio adopters

- .github/workflows/release.yaml
- hack/docs/metrics_gen_docs.go
Fixes #N/A 
- We expect the website update on minor version changes. 
> ci: GHA release prepare-website 

- hack/release/common.sh
- website/content/en/docs/concepts/instance-types.md
- website/content/en/docs/concepts/metrics.md
- website/content/en/docs/concepts/threat-model.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/grafana-values.yaml
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/upgrade-guide.md
- website/content/en/preview/concepts/metrics.md
- website/content/en/v0.29/concepts/instance-types.md
- website/content/en/v0.29/concepts/metrics.md
- website/content/en/v0.29/concepts/threat-model.md
- website/content/en/v0.29/faq.md
- website/content/en/v0.29/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.29/getting-started/getting-started-with-karpenter/grafana-values.yaml
- website/content/en/v0.29/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.29/upgrade-guide.md
Fixes #N/A 
-  Add `v0.29` changes to docs that weren't added by the GHA Release action
Manual view of the website
> docs: Add v0.29 changes to docs

- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/v0.29/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
> docs: step02-create-cluster.sh - upgrade to eks 1.27

- charts/karpenter/README.md
- charts/karpenter/README.md.gotmpl
- hack/release/common.sh
Fixes #N/A 
- Fix erroneous `config.yaml` updates and some docs references
- Update the Helm README to point to the correct link on auto-generation
> ci: Fix website script updates during release process

- hack/release/common.sh
Fixes #3952 
- Sets the `SOURCE_DATE_EPOCH` and `KO_DATA_DATE_EPOCH` values during the release process
Link to Slack discussion and relevant documentation on reproducible builds:
1. https://kubernetes.slack.com/archives/C01T7DTP65S/p1689879771932759?thread_ts=1689878295.033159&cid=C01T7DTP65S
2. https://www.chainguard.dev/unchained/conquer-your-build-horizon-with-chainguard-enforce-in-2023
3. https://reproducible-builds.org/docs/source-date-epoch/
> ci: Set creation timestamp on containers

- .github/workflows/e2e-conformance-trigger.yaml
Fixes #N/A 
- In order to avoid throttling, we need to reduce our test to one for our conformance tests until the testing account receive limit incress 
> ci: Reduce conformance tests

- test/suites/machine/machine_test.go
Fixes #N/A 
-  Creating machine as on-demand to validate we can launch instances for the tests
> test: conformance testing failing due to limitation on instances

- website/content/en/docs/concepts/provisioners.md
- website/content/en/preview/concepts/provisioners.md
- website/content/en/v0.27/concepts/provisioners.md
- website/content/en/v0.28/concepts/provisioners.md
- website/content/en/v0.29/concepts/provisioners.md
> docs: Add missing colon for karpenter.k8s.aws/instance-generation

- go.mod
- go.sum
- test/suites/drift/suite_test.go
- website/content/en/preview/concepts/deprovisioning.md
Fixes # 
- Added e2e testing for node requirement drift
```release-note
```
> chore: Add testing for NodeRequirement Drift

- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
- Failing tests, as node groups were not able to be launched 
- Tested in a forked account 
> ci: Update Resource IMDSv1 Permissions 

- Makefile
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_provisioners.yaml
- pkg/providers/launchtemplate/testdata/al2_userdata_merged.golden
- pkg/providers/launchtemplate/testdata/al2_userdata_unmerged.golden
- pkg/providers/launchtemplate/testdata/br_userdata_merged.golden
- pkg/providers/launchtemplate/testdata/br_userdata_unmerged.golden
- test/suites/integration/daemonset_test.go
- test/suites/integration/testdata/amd_driver_input.sh
- test/suites/machine/testdata/al2_userdata_custom_labels_input.sh
- test/suites/machine/testdata/al2_userdata_input.sh
Fixes #N/A 
- Changed the testing labels in core to be used in tagging AWS resources during e2etests
> test: Update e2e test discovery tag

- .github/actions/e2e/cleanup/action.yaml
Fixes #N/A 
- failing on clean-up as other resources were clean-up by other runs
How was this change tested?**
- locally
> ci: Handle Multiple Clean-up Script

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.26/faq.md
- website/content/en/v0.27/faq.md
- website/content/en/v0.28/faq.md
- website/content/en/v0.29/faq.md
Fixes #N/A 
Update version guidance in the Karpenter FAQ to reference the EKS supported versions of Kubernetes.
Manual viewing of the docs
> docs: Update version guidance in the FAQ

- website/content/en/docs/concepts/deprovisioning.md
- website/content/en/preview/concepts/deprovisioning.md
- website/content/en/v0.28/concepts/deprovisioning.md
- website/content/en/v0.29/concepts/deprovisioning.md
Fixes #N/A 
- Docs on drift are out of date
> docs: Update docs for drift

- hack/docs/metrics_gen_docs.go
Fixes #N/A 
- Fix docgen resolution of `nodeClaimSubsystem`
`make docgen`
> ci: Fix docgen resolution of `nodeClaimSubsystem`

- .github/pull-request-template.md
Fixes #N/A 
PR Template change to minimize docs PR churn.
> docs: Updated PR template to include preview documentation recommendation

- go.mod
- go.sum
Fixes #N/A 
Pulls in https://github.com/aws/karpenter-core/commit/04ab9b9a8259337d64ee8af2f03df67fac82f239
- make presubmit
> chore: update karpenter-core for drift changes

- go.mod
- go.sum
Fixes #N/A 
- Updated karpenter-core for version release
> chore: Bump core for version release

- test/hack/cleanup/main.go
Fixes #N/A 
- Adding instanceProfile as part of the clean-up process to fix any leaks of instanceProfiles
> chore: Cleanup instanceProfiles created during testing

- pkg/cloudprovider/drift.go
- pkg/cloudprovider/suite_test.go
Fixes #N/A 
- Updates drift reason to reflect changes with our docs and streamline drift reason
- karpenter-core bump to include PR: https://github.com/aws/karpenter-core/pull/474
- Related to docs: https://github.com/aws/karpenter/pull/4436
> chore: Update drift reason

- website/content/en/preview/concepts/deprovisioning.md
Fixes #N/A 
- Remove static, and dynamic categorization
- N/A
> docs: Update drift docs to remove drift concepts 

- .github/dependabot.yaml
Fixes #N/A 
Don't update `karpenter-core` automatically from `dependabot`
> ci: Don't update `karpenter-core` automatically

- charts/karpenter/templates/role.yaml
- charts/karpenter/templates/rolebinding.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_machines.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/apis/crds/karpenter.sh_provisioners.yaml
- test/suites/integration/lease_garbagecollection_test.go
Fixes #N/A 
- Adding permissions to run `leasegarbagecollection` controller 
- Bumping core to include https://github.com/aws/karpenter-core/pull/471
- /kapenter snapshot
> chore: Permission for leasegarbagecollection controller 

- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Install go on e2e workflow
> chore: install go on e2e workflows

- test/suites/integration/kubelet_config_test.go
Fixes #N/A 
- make apply && make e2etests with focus
> test: add instance generation requirements for kubelet config tests

- .github/actions/maintainer-check/action.yaml
Fixes #N/A 
Adds jmdeal as a maintainer for testing infrastructure.
> chore: add jmdeal as maintainer

- pkg/apis/v1alpha1/suite_test.go
Fixes #N/A 
This PR adds static hash checking for `AWSNodeTemplate`s. This involves comparing templates with different specs against known expected hash values. This ensures that the same node template does not hash to different values.
`make test`
> test: add static hash checking for AWSNodeTemplate

- pkg/controllers/machine/garbagecollection/controller.go
Fixes #N/A 
This change adds support for the `v1beta1/NodeClaim` in the Machine garbage collection controller that currently only handles `v1alpha5/Machine`. This change stages out the `v1beta1` changes so that the `v1beta1` APIs can be released at a later time.
> chore: Add support for `v1beta1/NodeClaim` garbage collection

- .github/actions/e2e/cleanup/action.yaml
- test/hack/cleanup/main.go
Fixes #N/A 
- Our E2E testing is seeing an increased number of ENI leaks. Adding ENIs are part of our clean-up script to delete any leaks.
- `/karpenter` snapshot
> ci: Clean-up elastic network interface

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Add workaround provided by GitHub to mitigate post run failures 
- https://github.com/aws/karpenter/actions/runs/6067597873
- `/karpenter` snapshot
> fix: Workaround GHA Post run failure 

- .github/workflows/e2e-upgrade.yaml
> fix: Upgrade-test create-cluster typo

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Change from v0.27.1 tag to v0.23.1 tag
- N/A
> fix: Upgrade test is failing due to needing an updated tag

- .github/workflows/approval-comment.yaml
- .github/workflows/snapshot-release.yaml
Fixes #N/A 
This PR fixes the PR number resolution in the `approval-comment` workflow
> ci: Fix PR resolution in comment

- tools/kompat/cmd/kompat/main.go
- tools/kompat/pkg/kompat/kompat.go
Fixes #N/A 
- For importing kompat adjusted the directory 
- N/A
> chore: Update `kompat` directories for importing

- tools/allocatable-diff/go.mod
- tools/allocatable-diff/go.sum
- tools/allocatable-diff/main.go
Fixes #N/A 
Bumps the `allocatable-diff` tool deps up to the latest
> chore: Bump allocatable diff `go.mod` deps

- pkg/cloudprovider/drift.go
- pkg/providers/amifamily/bottlerocket.go
- pkg/providers/instancetype/types.go
Fixes #N/A 
This PR fixes a few misses in the v1beta1 migration that enable `NodeClaim` launching to succeed
- Manual creation of `NodeClaim`
> chore: Fix some misses in v1beta1 migration

- pkg/controllers/nodeclaim/garbagecollection/machine_test.go
- pkg/controllers/nodeclaim/garbagecollection/nodeclaim_test.go
- pkg/controllers/nodeclaim/garbagecollection/suite_test.go
- pkg/fake/cloudprovider.go
- pkg/fake/utils.go
Fixes #N/A 
This PR adds `v1beta1` testing for the garbage collection controller for the `NodeClaim` resource
> test: Add `v1beta1` testing for the garbage collection controller

- pkg/cloudprovider/drift.go
- pkg/cloudprovider/suite_test.go
Fixes #N/A 
This reorders the IsDrifted() check to first check the node class annotations before making any real API calls. 
- make presubmit
> chore: reorder drift checks to save on computation

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/apis/v1beta1/zz_generated.deepcopy.go
- pkg/cloudprovider/cloudprovider.go
- pkg/providers/amifamily/al2.go
- pkg/providers/amifamily/bootstrap/bootstrap.go
- pkg/providers/amifamily/bottlerocket.go
- pkg/providers/amifamily/custom.go
- pkg/providers/amifamily/resolver.go
- pkg/providers/amifamily/ubuntu.go
- pkg/providers/amifamily/windows.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
Fixes #N/A 
This PR bumps `karpenter-core` to persist some `v1beta1` changes
> chore: Update small API changes consistent with `karpenter-core`

- .github/workflows/e2e-conformance-trigger.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Increases  jitter to prevent cluster creation failure
- `/karpenter conformance`
> ci: Add jitter for conformance testing

- .github/actions/e2e/slack/notify/action.yaml
- .github/workflows/e2e-conformance-trigger.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Add the commit status for conformance e2e test runs. 
- NA
> ci: Add commit status for conformance PR runs

- .github/workflows/e2e.yaml
Fixes #N/A 
- Fix the commit status that posted at the end to match the commit status of the start
- N/A
> ci: Update commit status of at end of PR run

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Update commit status for E2E Upgrade tests 
- N/A 
> chore: E2E Upgrade commit status

- .github/workflows/sweeper.yaml
Fixes #N/A 
- Enable sweeper for forked accounts that are using the E2E tests
- Forked account
> ci: sweep resources created with E2E testing

- .github/actions/e2e/slack/notify/action.yaml
- .github/workflows/e2e-conformance-trigger.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/resolve-args.yaml
> Revert "ci: Fix passing through the `event_name` correctly"

- website/content/en/preview/concepts/node-templates.md
> docs: specify merging behavior for custom AMI family

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
- Bump karpenter-core
> chore: bump karpenter-core to include CEL validation

- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
Fixes #N/A 
Fixes the removal of the `actions/checkout@v4` action from the release and snapshot workflows.
N/A
> fix: add checkout to snapshot / release workflows

- designs/limits.md
- [X ] Yes, PR includes docs updates
> docs: Update limits.md with correct Kubernetes CPU Limits reference link

- website/content/en/preview/concepts/threat-model.md
Fixes #N/A 
This PR updates the `threat-model` docs to use the v1beta1 terminology and concepts.
> docs: Update the threat model to v1beta1

- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/install-prometheus/action.yaml
Fixes #N/A 
Fixes a miss to use the block `with:` to pass through custom values
> ci: Call composite action with values

- test/suites/integration/ami_test.go
Fixes #N/A 
- Remove `c7a` instance type
> test: Remove c7a instancetype for windows test 

- tools/kompat/README.md
> docs: Update README.md with correct go installation repository link

- website/content/en/preview/concepts/settings.md
Fixes #N/A 
This PR updates the `settings` doc to use the v1beta1 terminology and concepts.
> docs: Update settings doc to v1beta1 apis

- README.md
> docs:  Update README.md

- test/pkg/environment/aws/setup.go
- test/pkg/environment/common/expectations.go
- website/content/en/preview/concepts/disruption.md
Fixes #N/A 
Fix a bug in the scale testing code that was causing scale testing failures
`/karpenter scale`
> test: Fix scale testing

- test/hack/cleanup/main.go
Fixes #N/A 
Fix a bug where we were comparing a date value that could set an instance profile that was created at `23:59:59` to be created at `00:00:00` due to it only capturing the date value with the expiration time. If we got unlucky and the instance profile was created late in the day, the instance profile could get deleted while the tests were running.
> ci: Fix sweeper bug with instance profiles

- website/content/en/preview/concepts/nodepools.md
- website/content/en/preview/concepts/scheduling.md
- website/content/en/preview/faq.md
Fixes #N/A 
This PR updates the documentation for the FAQ to align with v1beta1 APIs and concepts.
> docs: Update the FAQ doc to v1beta1 apis and concepts

- ADOPTERS.md
Adds Rapid7 to the list of Karpenter users
> docs: Add Rapid7 to the list of Karpenter adopters

- website/content/en/docs/concepts/provisioners.md
- website/content/en/preview/concepts/nodepools.md
- website/content/en/v0.27/concepts/provisioners.md
- website/content/en/v0.28/concepts/provisioners.md
- website/content/en/v0.29/concepts/provisioners.md
- website/content/en/v0.30/concepts/provisioners.md
- website/content/en/v0.31/concepts/provisioners.md
Fixes #N/A 
While looking at the test cases it seems like the requirements also are considered with pod.spec.topologySpreadConstraints,  pod.spec.affinity.podAffinity, and pod.spec.nodeSelector rules. and we should mention in them docs if we are mentioning affinity too
- [] No
> docs: nodeselector,affinities and topology considerations for requirements

- pkg/providers/instancetype/nodeclass_test.go
- pkg/providers/instancetype/nodetemplate_test.go
- pkg/providers/instancetype/types.go
Fixes #N/A 
This PR removes the vestigial business logic associated with `settings.enablePodEni`. 
`make test` and `/karpenter snapshot`
> chore: remove EnablePodENI logic

- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
This PR adds more detail to the cleanup story, post-migration so that users cleanup their alpha CRDs and the policy on the controller role associated with the alpha APIs.
> docs: Add more detail on removing CRDs and removing the IAM policy

- website/config.yaml
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.31/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Patch release didn't update getting-started guide 
looking at website preview
> docs: change getting started guide to refer to patch version

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/pkg/environment/common/expectations.go
- test/suites/alpha/integration/kubelet_config_test.go
- test/suites/alpha/scale/deprovisioning_test.go
- test/suites/alpha/scale/provisioning_test.go
- test/suites/beta/integration/ami_test.go
- test/suites/beta/integration/aws_metadata_test.go
- test/suites/beta/integration/block_device_mappings_test.go
- test/suites/beta/integration/cni_test.go
- test/suites/beta/integration/daemonset_test.go
- test/suites/beta/integration/emptiness_test.go
- test/suites/beta/integration/extended_resources_test.go
- test/suites/beta/integration/hash_test.go
- test/suites/beta/integration/instance_profile_test.go
- test/suites/beta/integration/kubelet_config_test.go
- test/suites/beta/integration/lease_garbagecollection_test.go
- test/suites/beta/integration/scheduling_test.go
- test/suites/beta/integration/security_group_test.go
- test/suites/beta/integration/storage_test.go
- test/suites/beta/integration/subnet_test.go
- test/suites/beta/integration/suite_test.go
- test/suites/beta/integration/tags_test.go
- test/suites/beta/integration/termination_test.go
- test/suites/beta/integration/testdata/al2_no_mime_userdata_input.sh
- test/suites/beta/integration/testdata/al2_userdata_input.sh
- test/suites/beta/integration/testdata/amd_driver_input.sh
- test/suites/beta/integration/testdata/br_userdata_input.sh
- test/suites/beta/integration/testdata/windows_userdata_input.ps1
- test/suites/beta/integration/validation_test.go
Fixes #N/A 
This PR adds Integration E2E tests for the beta release
> test: Add Integration E2E testing for v1beta1

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/suites/beta/consolidation/suite_test.go
Fixes #N/A 
Adds in v1beta1 Consolidation tests
Haven't tested yet
> test: add in consolidation v1beta1 tests

- .github/workflows/e2e-matrix.yaml
- test/suites/beta/nodeclaim/garbage_collection_test.go
- test/suites/beta/nodeclaim/nodeclaim_test.go
- test/suites/beta/nodeclaim/suite_test.go
- test/suites/beta/nodeclaim/testdata/al2_userdata_custom_labels_input.sh
- test/suites/beta/nodeclaim/testdata/al2_userdata_input.sh
Fixes #N/A 
This PR adds NodeClaim E2E tests for the beta release
> test: Add NodeClaim testing for E2E for v1beta1

- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Fix typo of NodePools in `upgrade-guide.md`
> docs: Fix typo of NodePools in `upgrade-guide.md`

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/suites/beta/interruption/suite_test.go
Fixes #N/A 
This PR adds Interruption E2E tests for the beta release
> test: Add Interruption testing for E2E for v1beta1

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/suites/beta/ipv6/suite_test.go
Fixes #N/A 
This PR adds IPv6 E2E tests for the beta release
> test: Add IPv6 testing for E2E for v1beta1

- website/content/en/preview/upgrading/v1beta1-controller-policy.json
Fixes #N/A 
The guide sets the `AWS_REGION` variable, not the `REGION` variable
> chore: fix env vars for v1beta1 controller policy

- Makefile
- go.mod
- go.sum
- hack/validation/labels.sh
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/apis/v1beta1/nodepool_validation_cel_test.go
Fixes #N/A 
- Partner PR: https://github.com/aws/karpenter-core/pull/633
- Adding CEL validation in the effort of moving away from webhook validation.
- https://github.com/aws/karpenter-core/issues/103
- `make test`
> feat: CEL Validation for `NodePool.Spec.Template` Labels

- .github/workflows/pr-snapshot.yaml
Fixes #N/A 
Hopefully resolves: https://github.com/aws/karpenter/actions/runs/6632903336/job/18019570959
> fix: Restore PR write permissions to PRSnapshot

- charts/karpenter/values.yaml
Fixes #N/A 
Fix a failure in CI due to a helm evaluating a nil interface
> chore: Fix helm error with AWS settings

- .github/workflows/alpha-e2e-scale-trigger.yaml
- .github/workflows/approval-comment.yaml
- .github/workflows/e2e.yaml
- test/suites/beta/scale/deprovisioning_test.go
- test/suites/beta/scale/provisioning_test.go
- test/suites/beta/scale/suite_test.go
Fixes #N/A 
This adds in v1beta1 Scale testing and adds in a alpha-e2e-scale trigger that would trigger the Alpha scale tests. 
- make verify
- make e2etests
> test: add beta scale test

- .github/workflows/alpha-e2e-scale-trigger.yaml
- test/suites/beta/scale/deprovisioning_test.go
Fixes #N/A 
Fixes the new alpha-e2e-scale-trigger scale action
Committing here
> chore: fix alpha scale github action

- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-conformance-trigger.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
Fix failures in GHA linting
> ci: Fix failures in GHA linting

- test/suites/alpha/scale/deprovisioning_test.go
- test/suites/beta/scale/deprovisioning_test.go
- test/suites/beta/scale/provisioning_test.go
Fixes #N/A 
Fixes the beta scale tests so each Node Pool and  NodeClass will be unique. 
local test
> test: fix beta scale test

- go.mod
- go.sum
Fixes #N/A 
Update karpenter-core to include https://github.com/aws/karpenter-core/pull/641
make presubmit and through snapshots
> chore: update core to include new taint

- website/content/en/preview/concepts/disruption.md
- website/content/en/v0.30/concepts/deprovisioning.md
- website/content/en/v0.31/concepts/deprovisioning.md
Fixes #N/A 
- Update docs to conceptually categorize drift as Specified and Discovered drift
- N/A
> docs: Update drift docs for Specified and Discovered drift

- .github/actionlint-matcher.json
- .github/workflows/approval-comment.yaml
- .github/workflows/ci.yaml
- .github/workflows/codegen.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pr-snapshot.yaml
- .github/workflows/release.yaml
- .github/workflows/resolve-args.yaml
- .golangci.yaml
- Makefile
- hack/toolchain.sh
- pkg/test/expectations/expectations.go
- test/pkg/debug/setup.go
- test/pkg/environment/aws/environment.go
- test/pkg/environment/aws/expectations.go
- test/pkg/environment/aws/metrics.go
- test/pkg/environment/aws/setup.go
- test/pkg/environment/common/expectations.go
- test/pkg/environment/common/setup.go
Fixes #N/A 
Add linting for GHA workflows
`actionlint` does not currently support composite action checking but this feature appears to be in the works (https://github.com/rhysd/actionlint/pull/366). When that feature is implemented, we could also add that feature to our CI
`actionlint -oneline`
> ci: Add GHA linting

- go.mod
- go.sum
Fixes #N/A 
Pulls in https://github.com/aws/karpenter-core/pull/642
make presubmit && test snapshot
> chore: update core to pull in topology fix

- go.mod
- go.sum
Fixes #N/A 
Updates `karpenter-core` to v0.32.1 in preparation for patch release.
N/A
> deps: update karpenter-core to v0.32.1

- charts/karpenter/values.yaml
> docs: Helm comment referencing deprecated aws.assumeRoleARN

- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/v0.32/upgrading/upgrade-guide.md
Fixes #N/A 
Add docs to alert users about https://github.com/aws/karpenter/issues/4985
> chore: add docs about regression

- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- Makefile
Fixes #N/A 
We moved tests back away from having an alpha or beta directory, so this is no longer needed. 
🙏  and make e2etests with the new focus. 
> chore: remove Makefile directory prefix for e2e tests

- charts/karpenter/README.md
- hack/docs/compatibility-karpenter.yaml
- hack/docs/instancetypes_gen_docs.go
- website/content/en/preview/reference/instance-types.md
- website/content/en/preview/reference/metrics.md
Fixes #N/A 
Fix `make docgen` for `instance-types.md` generation
`make docgen`
> docs: Fix docgen for instance-types generation

- website/content/en/docs/upgrading/v1beta1-migration.md
- website/content/en/preview/upgrading/v1beta1-migration.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
Fixes #N/A 
This change adds documentation detail about why we decided to drop certain settings fields from the project. This help answers the question similar to #5031 
> docs: Add docs detail about `aws.enablePodENI` 

- .github/actions/e2e/create-cluster/action.yaml
- pkg/errors/errors.go
- test/pkg/environment/aws/expectations.go
- test/suites/integration/instance_profile_test.go
- test/suites/nodeclaim/garbage_collection_test.go
Fixes #N/A 
Add back instance profile creation for Garbage collection test. 
make presubmit
> test: fix flake for nodeclaim test

- ADOPTERS.md
Adding Grafana Labs as an adopter to `Adopters.md`
N/A
- Sort of, it does not impact user-facing documentation
- [] No
> docs: Adding Grafana Labs to list of adopters of Karpenter

- go.mod
- go.sum
- pkg/cloudprovider/cloudprovider.go
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/ami_test.go
- test/pkg/environment/common/expectations.go
Fixes #N/A 
Update core to bring in some more alpha removal changes (https://github.com/aws/karpenter-core/pull/780)
make presubmit && make apply
> chore: update core and remove v1alpha5 well known labels

- test/pkg/environment/common/expectations.go
- test/suites/drift/suite_test.go
- test/suites/expiration/suite_test.go
Fixes #N/A 
This removes the legacy expectations and changes language around cordoning to tainting.
make verify && make e2etests
> test: remove legacy helpers and comments

- .github/actions/e2e/create-cluster/action.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Remove redundant upgrade for Prometheus and Karpenter
> ci: Cleanup cluster creation for upgrade suite

- .ko.yaml
Fixes #N/A 
Use the `eks-distro-minimal-base` image rather than `ko`'s default.
> ci: use EKS base image

- test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
- Separate EKS and IAM Policy
- The `GithubActionPoilcy` is limited on the number of characters that is able to inside the policy
> ci: Separate `GithubActionPoilcy` into EKS and IAM Policy

- .github/workflows/ci-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/publish-test-tools.yaml
- .github/workflows/snapshot.yaml
Fixes #N/A 
Enable CI checks to run on merge to release branches
> ci: Enable CI on release branch

- .github/workflows/ci-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/publish-test-tools.yaml
- .github/workflows/snapshot.yaml
> ci: Enable CI on release branch (#5129)

- go.mod
- go.sum
Fixes #N/A 
Pin `go.mod` to `karpenter-core` `v0.32.2`
Manual validation of install
> Pin go.mod to v0.32.2

- test/suites/scale/deprovisioning_test.go
Fixes #N/A 
- fixes scale testing failures  
- Enable consolidation for consolidation tests 
- Fix expiration test 
- `/karpenter scale`
> test: Fix Scale testing timeouts on consolidation 

- .github/workflows/release.yaml
Fixes #N/A 
Constrain release tagging to be semantic
- Ran Github Actions on local repo to test pattern matching
> ci: Constrain release trigger to be semantic

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/docs/upgrading/v1beta1-migration.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/upgrading/v1beta1-migration.md
- website/content/en/v0.32/faq.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.32/reference/threat-model.md
- website/content/en/v0.32/upgrading/upgrade-guide.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
- website/hugo.yaml
Fixes #N/A 
Auto-generated doc updates for v0.32.3 release
> docs: Stable Release updates Release v0.32.3

- .github/actions/e2e/setup-cluster/action.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
- Adjusted naming of `create-cluster` action to `setup-cluster`
- N/A
> ci: Change create-cluster to setup-cluster

- test/suites/integration/ami_test.go
- test/suites/integration/kubelet_config_test.go
Fixes #N/A 
Pins the Ubuntu AMI to the latest working version until a fix is released.
> test: pin ubuntu AMI

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Update E2E upgrade test to include `setup-cluster` action 
- N/A
> ci: `setup-cluster` for E2E Upgrade workflow

- hack/release/common.sh
Fixes: https://github.com/aws/karpenter/actions/runs/7105310532
Updates scripts to point to files renamed in https://github.com/aws/karpenter/pull/4718/files
Ran the script locally🤞 
> fix: Website generation scripts

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
- Update karpenter version to the latest 
- N/A
> docs: Update karpenter version

- website/content/en/docs/getting-started/getting-started-with-karpenter/prometheus-values.yaml
- website/content/en/preview/getting-started/getting-started-with-karpenter/prometheus-values.yaml
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/prometheus-values.yaml
Fixes #N/A 
- Update Prometheus namespace to be kube-system
- N/A
> docs: Update Prometheus namespace

- tools/allocatable-diff/go.mod
- website/go.mod
Fixes #N/A 
This change updates the module paths for the last two modules that don't contain the name change:
1. `tools/allocatable-diff`
2. `website`
> chore: Update module paths for the website and the allocatable-diff tool

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart.sh
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart.sh
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart.sh
Fixes 
- Related #5195 
- This enhancement provides a seamless and easy to configure experience that lets you define required IAM permissions for your applications in [Amazon Elastic Kubernetes Service (Amazon EKS)](https://aws.amazon.com/eks/) clusters so you can connect with AWS services outside the cluster
- Adapt for better security posture
- https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/
> docs: Update Create Cluster with Pod Identity

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.33/faq.md
Fixes #N/A 
Adds an FAQ about pod autoscaling being outside of Karpenter's scope and gives recommendations.
N/A
> docs: add faq for pod autoscaling

- pkg/controllers/nodeclaim/garbagecollection/controller.go
Fixes #N/A 
- Update Nodeclaim controller garbage collection name
- N/A 
> chore: Update Nodeclaim Garbage Collection Controller Name

- .github/actions/e2e/slack/send-message/action.yaml
Fixes #N/A 
The `$MESSAGE` environment variable was not being interpolated correctly.
Manually tested
> ci: Fix notify message for slack notification

- .github/workflows/pr-snapshot.yaml
Fixes #N/A 
Environment variables were being passed to the wrong step so environment variables in the comment-posting step of the github-script were returning `undefined`
> ci: Fix passing environment variable snapshot comment post

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.32/faq.md
- website/content/en/v0.33/faq.md
- website/go.mod
- website/go.sum
Fixes #N/A 
Updates the FAQ so that it accurately reflects the default images used for Karpenter nodes. 
make website
- [] No
> update faq for ami family defaults

- Makefile
- website/content/en/docs/contributing/development-guide.md
- website/content/en/preview/contributing/development-guide.md
- website/content/en/v0.32/contributing/development-guide.md
- website/content/en/v0.33/contributing/development-guide.md
Fixes #N/A 
Changes `make apply` to default to debug log level, since this should be used for development.
> chore: update contributing log level guidelines

- .github/workflows/pr-snapshot.yaml
Fixes #N/A 
Add a note about logging into ECR.
N/A
> ci: improve snapshot published message

- website/content/en/preview/concepts/disruption.md
- website/content/en/preview/concepts/nodepools.md
Fixes #N/A 
Adds documentation for budgets 
make website
> docs: update docs to include budgets

- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Adds a note into the upgrade guide for disruption budgets.
make website
> docs: add disruption budgets upgrade guide

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart.sh
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart.sh
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart.sh
Fixes #N/A 
- To allow the default experience to be smooth for customers, remove comments from the helm chart installation and placed inside of a warning for customers.
-  Manually tested
> docs: Update IRSA Annotation on Karpenter Installation 

- pkg/providers/instancetype/instancetype.go
Fixes #N/A 
Cherry-picks the following commits into release v0.32.4:
- https://github.com/aws/karpenter-provider-aws/pull/5308
N/A
> fix: cherry-pick local zone fix to v0.32.x

- pkg/providers/instancetype/instancetype.go
Fixes #N/A 
Cherry-picks the following commits into release v0.33.1:
- https://github.com/aws/karpenter-provider-aws/pull/5308
N/A
> fix: cherry-pick local zone fix

- website/content/en/docs/upgrading/compatibility.md
- website/content/en/preview/upgrading/compatibility.md
- website/content/en/v0.30/upgrade-guide.md
- website/content/en/v0.31/upgrade-guide.md
- website/content/en/v0.32/upgrading/compatibility.md
- website/content/en/v0.33/upgrading/compatibility.md
- website/hugo.yaml
Fixes #N/A 
Updates our description of snapshot releases to reflect the new(ish) snapshot ECR infrastructure.
N/A
> docs: update snapshot release description

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/feature.yaml
Fixes #N/A 
The issue template wasn't hyperlinked. This makes it easier to see where to create a new issue.
> chore: update github issue template to use a hyperlink 

- .github/workflows/e2e.yaml
- .github/workflows/snapshot.yaml
- hack/release/common.sh
Fixes #N/A 
Updates the snapshot and e2e workflows to use new repo. 
N/A
> ci: run snapshot / e2e on merge to release-v0.32.x

- .github/workflows/approval-comment.yaml
- .github/workflows/codegen.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e-version-compatibility-trigger.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pr-snapshot.yaml
- .github/workflows/publish-test-tools.yaml
- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
- .github/workflows/sweeper.yaml
Fixes #N/A 
Cherry picks #5164 to ensure workflows have the correct permissions.
N/A
> ci: cherry-pick workflow permissions updates

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
- Update warning box to a Notice to draw attention during cluster creation
- N/A
> docs: Update Warning Labels Into Notices

- .github/workflows/pr-snapshot.yaml
- go.mod
- go.sum
- hack/release/common.sh
Fixes #N/A 
Bumps [kubernetes-sigs/karpenter](https://www.github.com/kubernetes-sigs/karpenter) to v0.33.1.
> deps: bump kubernetes-sigs/karpenter to v0.33.1

- website/content/en/docs/upgrading/v1beta1-migration.md
- website/content/en/preview/upgrading/v1beta1-migration.md
- website/content/en/v0.32/faq.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.32/reference/threat-model.md
- website/content/en/v0.32/upgrading/upgrade-guide.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
- website/content/en/v0.33/upgrading/v1beta1-migration.md
Fixes #N/A 
Updates refs to v0.32.3 with v0.32.4.
N/A
> docs: replace refs to v0.32.3 to v0.32.4

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/faq.md
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.33/reference/cloudformation.md
- website/content/en/v0.33/reference/threat-model.md
- website/content/en/v0.33/upgrading/upgrade-guide.md
- website/hugo.yaml
Fixes #N/A 
Updates references to v0.33.0 to v0.33.1 where relevent.
N/A
> docs: update website for v0.33.1 release

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/v0.32/concepts/nodeclasses.md
- website/content/en/v0.33/concepts/nodeclasses.md
Fix typo `s/neccesary/necessary/`
Fix typo `s/neccesary/necessary/`
It's just doc update.
> fix: typo s/neccesary/necessary/

- website/content/en/docs/reference/cloudformation.md
- website/content/en/preview/reference/cloudformation.md
- website/content/en/v0.33/reference/cloudformation.md
Fixes #N/A 
I added a resource for `KarpenterControllerPolicy` that is present in `cloudformation.yaml` in the [docs](https://github.com/aws/karpenter-provider-aws/blob/main/website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml) and [preview](https://github.com/aws/karpenter-provider-aws/blob/main/website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml), but missing from the reference in the docs.
There may be other missing, but in this PR I only added the missing `"arn:${AWS::Partition}:ec2:${AWS::Region}:*:spot-instances-request/*`.
If create a policy with this resource missing, karpenter will not be able to create a spot instance.
And conversely, I deleted resources that only existed in reference …
> docs: add missing resource tag associated with spot

- website/content/en/docs/upgrading/v1beta1-migration.md
- website/content/en/preview/upgrading/v1beta1-migration.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
- website/content/en/v0.33/upgrading/v1beta1-migration.md
Fixes #N/A 
This change adds a documentation update which clarifies some points around IAM permissions that weren't explicitly called out in the ChangeLog section of the v1beta1 Migration Guide. This mentions that ABAC-based scoping that relied on the `karpenter.sh/provisioner-name` tag needs to be updated to the new tag (`karpenter.sh/nodepool`) in v1beta1 and that the use of the managed instance profile feature requires that you add `iam:` permissions to your controller policy.
Relates to #5381
> docs: Add changelog detail on IAM permissions updates

- go.mod
- go.sum
Fixes #N/A 
Brings in https://github.com/kubernetes-sigs/karpenter/pull/917
make verify && make presubmit
> chore: update core to pull in metrics

- .github/workflows/codegen.yaml
Fixes #N/A 
Checks the number of changes that have been committed between codegen and main when evaluating whether to create a PR 
Ran the commit count checking in my local environment
> ci: Update codegen diff checking

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/v0.32/concepts/nodeclasses.md
- website/content/en/v0.33/concepts/nodeclasses.md
Fixes #N/A 
- Update docs to to use KmsKeyId instead of ARN 
- Related PR: https://github.com/aws/karpenter-provider-aws/pull/5152
- N/A
> docs: Remove KmsKeyId ARN 

- .github/workflows/e2e-matrix-trigger.yaml
> ci: update repo name for workflow trigger check

- go.mod
- go.sum
Fixes #N/A 
Bumps karpenter-core to the latest version.
N/A (its the same commit, new tag)
> deps: bump karpenter-core to v0.32.5

- website/content/en/v0.32/faq.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.32/reference/threat-model.md
- website/content/en/v0.32/upgrading/upgrade-guide.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
> docs: update refs for v0.32.4 to v0.32.5

- go.mod
- go.sum
Fixes #N/A 
This bumps `sigs.k8s.io/karpenter` to the latest version
> chore: Bump sigs.k8s.io/karpenter

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.33/faq.md
docs: Updated faq.md to reflect correct default behavior for Drift.  
> Issue 5466

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Update the account were older snapshots are pulled 
- N/A
> ci: Update `Snapshot_Account_ID` for E2E Upgrade

- pkg/cloudprovider/drift.go
- pkg/cloudprovider/suite_test.go
Fixes #5443 
- Currently, Karpenter uses the subnet and security group status to evaluate drift for these fields while the launch code uses the security groups/subnets/ami cache. The status of the subnet and security group will get reconciled every 5 minutes. This creates a race where the status might not have updated, but the cache has expired which means that we re-get a newer value from the cache.
- N/A  
> fix: Subnet and Security Groups to use in-memory values for evaluating Drift

- hack/docs/compatibility-karpenter.yaml
- hack/release/stable-pr.sh
Fixes #N/A 
- Update karpenter  compatibility list during release
- Tested locally
> ci: Fixing compatibility list to be updated during release

- website/content/en/docs/concepts/scheduling.md
- website/content/en/preview/concepts/scheduling.md
- website/content/en/v0.30/concepts/scheduling.md
- website/content/en/v0.31/concepts/scheduling.md
- website/content/en/v0.32/concepts/scheduling.md
- website/content/en/v0.33/concepts/scheduling.md
Fixes #N/A 
Add a note about zonal balancing
N/A
- [] No
> docs: Add a note about zonal balancing

- website/content/en/v0.32/faq.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.32/reference/threat-model.md
- website/content/en/v0.32/upgrading/upgrade-guide.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
Fixes #N/A 
- Update docs to point to v0.32.6 release of Karpenter
- N/A 
> docs: Update docs for v0.32.6 release

- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
Fixes #N/A 
Bump remaining eksctl version references.
> ci: bump eksctl in e2e

- .github/actions/e2e/install-karpenter/action.yaml
Fixes #N/A 
This change enables debug logging in our E2E testing
> ci: Enable debug logging in e2es

- .github/workflows/snapshot.yaml
Fixes #N/A 
- Allow snapshot creation for release branches to allow running the E2E tests 
- N/A
> ci: Allow snapshot creation for `release-v0.33.x`

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/faq.md
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.33/reference/cloudformation.md
- website/content/en/v0.33/reference/threat-model.md
- website/content/en/v0.33/upgrading/upgrade-guide.md
- website/hugo.yaml
Fixes #N/A 
Update docs to point to v0.33.2 release of Karpenter
> docs: Update docs for v0.33.2 release

- test/suites/alpha/drift/suite_test.go
- test/suites/alpha/expiration/suite_test.go
- test/suites/alpha/integration/scheduling_test.go
- test/suites/beta/drift/suite_test.go
- test/suites/beta/expiration/suite_test.go
- test/suites/beta/integration/scheduling_test.go
Fixes #N/A 
Cherrypicking E2E fixes 
- https://github.com/aws/karpenter-provider-aws/pull/5173
- https://github.com/aws/karpenter-provider-aws/pull/5460
- make e2etests
> test: Fix E2E test for release-v0.32.x

- test/suites/integration/ami_test.go
- test/suites/integration/kubelet_config_test.go
Fixes #N/A 
Use 1.28 AMIs with the Ubuntu AMI family in end-to-end testing. This change can be reverted when we implement a long term strategy to address #5572.
> test: use 1.28 AMIs for Ubuntu on k8s 1.29

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
Fixes #N/A 
- Update the helm chart versions of karpenter for v0.33.x
- N/A
> chore: Update Helm Chart Version for `release-v0.33.x` branch

- test/suites/expiration/suite_test.go
Fixes #N/A 
Disables expiration at the end of a test where we're expecting replacement nodes. This ensures we don't leak in the AfterEach. 
Focused the test with the expiration with the failing test after. 
> test: fix test leak by disabling expiration e2e

- go.mod
- go.sum
Fixes #N/A 
- Bump karpenter to v0.34.0
- N/A 
> chore: Update Karpenter to v0.34.0

- ADOPTERS.md
Fixes #N/A 
Adding VictoriaMetrics to list of adopters
N/A
> docs: Adding VictoriaMetrics to the list of adopters

- hack/release/common.sh
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/faq.md
- website/content/en/v0.33/faq.md
- website/content/en/v0.34/faq.md
- website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Fix `release.sh` script to succeed when running with `xargs`
Running a local `Dockerfile` that uses ubuntu and ensures that the script succeeds 
> ci: Fix release script to succeed with xargs

- charts/karpenter/templates/servicemonitor.yaml
Fixes #N/A 
- Fix serice Monitor indentation 
> chore: Fix service monitors indentation 

- .github/workflows/ci-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/snapshot.yaml
Fixes #N/A 
Add triggering CI/E2E testing from a release branch
> ci: Add trigger release branch

- .github/workflows/docgen.yaml
- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
- hack/release/common.sh
Fixes #N/A 
Update the accounts and roles to point to the correct accounts for `release-v0.31.x`
> ci: Port workflow fixes for `release-v0.31.x`

- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- Update the Permission for E2E testing
- N/A
> ci: Fix permission on E2E for the `release-v0.31.x`

- go.mod
- go.sum
Fixes #N/A 
- Bumping Karpetner version for v0.32.7 release 
- N/A
> chore: Bump Karpetner version for v0.32.7 release

- website/content/en/v0.32/faq.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.32/reference/threat-model.md
- website/content/en/v0.32/upgrading/upgrade-guide.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
Fixes #N/A 
- Update docs for v0.32.7
- N/A
> docs: Update docs for v0.32.7

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter for v0.31.4
- N/A
> chore: Bump karpenter for v0.31.4

- cmd/controller/main.go
- go.mod
- go.sum
- pkg/cloudprovider/suite_test.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
This change bumps `kubernetes-sigs/karpenter` to the latest version
> chore: Bump `kubernetes-sigs/karpenter` to latest

- website/content/en/docs/concepts/disruption.md
- website/content/en/preview/concepts/disruption.md
- website/content/en/v0.34/concepts/disruption.md
Fixes #N/A
Description
How was this change tested?
Does this change impact docs?
Yes, PR includes docs updates
> docs: adding missing @ at Schedule details

- hack/release/common.sh
Fixes #N/A 
Fix typo that was including an additional `/` in the cosign command
> ci: Fix typo in cosigning chart

- cmd/controller/main.go
- go.mod
- go.sum
- hack/toolchain.sh
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/cloudprovider/suite_test.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
Updated `go.mod` for sigs.k8s.io/karpenter by running  `go get -u sigs.k8s.io/karpenter@release-v0.34.x`
- https://github.com/aws/karpenter-provider-aws/pull/5672
N/A
> chore: Update go.mod for sigs.k8s.io/karpenter

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v0.34/faq.md
- website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.34/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.34/reference/cloudformation.md
- website/content/en/v0.34/reference/threat-model.md
- website/content/en/v0.34/upgrading/upgrade-guide.md
Fixes #N/A 
This PR updates docs to point to the latest release i.e v0.34.1
N/A
> docs: Update docs to point to v0.34.1

- .github/workflows/pr-snapshot.yaml
Fixes #N/A 
This change escapes the back-slash since by default this wasn't being respected inside of the script
Ran a GH action on my private fork
> ci: Escape newline with back-slash

- hack/release/common.sh
Fixes #N/A 
Fix pushing the `artifacthub-repo.yaml` file
> ci: Fix oras ArtifactHub config push

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bumps `kubernetes-sigs/karpenter` to the latest version
> chore: Bump `kubernetes-sigs/karpenter` to the latest

- examples/v1beta1/al2023-custom-userdata.yaml
Fixes #N/A 
Adds example `NodePool` / `EC2NodeClass` manifests for AL2023.
N/A
> chore: add al2023 example manifests

- go.mod
- go.sum
Fixes #N/A 
Bumps upstream karpenter to the latest release
N/A - same commit, new tag
> deps: bump upstream to v0.35.0

- go.mod
- go.sum
> chore: Bump nodeadm to point to a commit on main

- pkg/providers/instancetype/instancetype.go
> fix: add InstanceStorePolicy to instance list cache (#5763)

- hack/code/prices_gen/main.go
- pkg/controllers/controllers.go
- pkg/controllers/pricing/controller.go
- pkg/controllers/pricing/suite_test.go
- pkg/providers/pricing/pricing.go
Fixes #N/A 
This moves the pricing controller and the `suite_test.go` into the controllers package to put it in a logical location for organization
> chore: Move pricing controller into controllers package

- go.mod
- go.sum
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
Fixes #N/A 
Updates the go.mod to point to sigs.k8s.io/karpenter's release-v0.35.x branch.
> chore: update v0.35.x go.mod

- pkg/providers/instancetype/metrics.go
- website/content/en/preview/reference/metrics.md
Fixes #N/A 
Fix typo in `instance_type_offering_price_estimate` metric description
> docs: Fix typo in `instance_type_offering_price_estimate` metric description

- go.mod
- go.sum
Fixes #N/A 
- Update go.mod for v0.34.2 release
- N/A
> chore: Update go mod for v0.34.2 release

- go.mod
- go.sum
Fixes #N/A 
Update go.mod for v0.35.1 release
N/A
> chore: Update go mod for v0.35.1 release

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v0.35/faq.md
- website/content/en/v0.35/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.35/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.35/reference/cloudformation.md
- website/content/en/v0.35/reference/threat-model.md
- website/content/en/v0.35/upgrading/upgrade-guide.md
Fixes #N/A 
Update docs for v0.35.1
N/A
> docs: Update docs for v0.35.1

- hack/docs/compatibility-karpenter.yaml
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v0.34/faq.md
- website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.34/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.34/reference/cloudformation.md
- website/content/en/v0.34/reference/threat-model.md
- website/content/en/v0.34/upgrading/compatibility.md
- website/content/en/v0.34/upgrading/upgrade-guide.md
- website/content/en/v0.35/upgrading/upgrade-guide.md
Fixes #N/A 
- Update docs to be v0.34.2 instead of v0.34.1
- N/A
> docs: Update docs for v0.34.2 release

- pkg/providers/instancetype/instancetype.go
Fixes #N/A 
- Since volumeSize hash is not included in the instancetype cache key https://github.com/aws/karpenter-provider-aws/issues/5447. Karpenter will hash the volumeSize as a string. 
- `kubeReserved`, and `systemReserved` hash are also not included in the instancetype cache key https://github.com/kubernetes-sigs/karpenter/issues/1080. Karpenter will hash them as a string. 
- N/A
> chore(cherry-pick to v0.35.x): Include volumeSize, kubeReserved, and systemReserved in Instancetype hash calculations

- pkg/providers/instancetype/instancetype.go
Fixes #N/A 
- Since volumeSize hash is not included in the instancetype cache key https://github.com/aws/karpenter-provider-aws/issues/5447. Karpenter will hash the volumeSize as a string. 
- `kubeReserved`, and `systemReserved` hash are also not included in the instancetype cache key https://github.com/kubernetes-sigs/karpenter/issues/1080. Karpenter will hash them as a string. 
- N/A
> chore(cherry-pick to v0.34.x): Include volumeSize, kubeReserved, and systemReserved in Instancetype hash calculations

- go.mod
- go.sum
> chore: Bump release-v0.34.x to latest karpenter

- go.mod
- go.sum
> chore: Bump release-v0.32.x to latest karpenter-core

- go.mod
- go.sum
> chore: Bump release-v0.35.x to latest karpenter

- cmd/controller/main.go
- go.mod
- go.sum
- pkg/cloudprovider/suite_test.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
> chore: Bump release-v0.33.x to latest karpenter

- go.mod
- go.sum
> chore: Pin release to v0.32.8

- go.mod
- go.sum
> chore: Pin release to v0.33.3

- go.mod
- go.sum
> chore: Pin release to v0.35.2

- go.mod
- go.sum
> chore: Pin release to v0.34.3

- examples/v1beta1/minValues-family.yaml
- examples/v1beta1/minValues-multiple-keys.yaml
- website/content/en/docs/concepts/nodepools.md
- website/content/en/preview/concepts/nodepools.md
- website/content/en/v0.35/concepts/nodepools.md
This PR adds details in the public doc related to `minValues` in the NodePool requirement.
RFC: https://github.com/kubernetes-sigs/karpenter/pull/966/files
> docs: Documentation on minValues in NodePool requirement.

- hack/release/common.sh
Fixes #N/A 
Fixes removing an extra slash in the helm chart repo path
> ci: Fix helm chart push for artifacthub file

- website/content/en/docs/tasks/managing-amis.md
- website/content/en/preview/tasks/managing-amis.md
- website/content/en/v0.32/tasks/managing-amis.md
- website/content/en/v0.33/tasks/managing-amis.md
- website/content/en/v0.34/tasks/managing-amis.md
- website/content/en/v0.35/tasks/managing-amis.md
Update explanation to match sample config
Fixes #N/A 
> docs: Update managing-amis.md

- go.mod
- go.sum
Fixes #N/A 
Bump `sigs.k8s.io/karpenter` to latest HEAD
> chore: Bump `sigs.k8s.io/karpenter` to latest HEAD

- website/content/en/docs/troubleshooting.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.32/troubleshooting.md
- website/content/en/v0.33/troubleshooting.md
- website/content/en/v0.34/troubleshooting.md
- website/content/en/v0.35/troubleshooting.md
issue #5876
Updated troubleshooting to reference new crd names for kubectl label/annotate calls on helm errors.
> CRD troubleshooting guide needs updating for Beta CRDs #5876

- website/content/en/_index.html
Fixes #N/A 
- Update language 
> docs: Update landing page for NodePool from Provisioner

- go.mod
- go.sum
- pkg/cloudprovider/cloudprovider.go
- pkg/fake/cloudprovider.go
Fixes #N/A 
- Bump karpenter version  
- N/A
> chore: Bump Karpenter version

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/providers/amifamily/bootstrap/bootstrap.go
- pkg/providers/amifamily/bootstrap/bottlerocket.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/launchtemplate/suite_test.go
- test/suites/integration/kubelet_config_test.go
- test/suites/nodeclaim/nodeclaim_test.go
Fixes #N/A 
- Bump to include these two PRs:
- https://github.com/kubernetes-sigs/karpenter/pull/1141
- https://github.com/kubernetes-sigs/karpenter/pull/1148
> chore: Bump Karpenter Version to include the kubeReserved and systemReserved fix

- .github/actions/e2e/slack/notify/action.yaml
Fixes #N/A 
- fix slack messaging
- N/A 
> fix: Fix slack messaging for E2E tests

- .github/actions/e2e/slack/notify/action.yaml
Fixes #N/A 
The slack message for E2E tests was wrongly modified in one of the PR's earlier. This PR should fix that messaging.
> fix: Fix slack message for tests

- .github/actions/e2e/slack/notify/action.yaml
Fixes #N/A 
Fix syntax error in slack notification step
> fix: Fix Slack Notification Step

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter 
- N/A
> chore: Update Karpenter for v0.33.4

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter 
- N/A
> chore: Update Karpenter for v0.32.9

- website/content/en/v0.32/faq.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.32/reference/threat-model.md
- website/content/en/v0.32/upgrading/upgrade-guide.md
- website/content/en/v0.32/upgrading/v1beta1-migration.md
Fixes #N/A 
- Update our docs for v0.32.8 to v0.32.9
- N/A
> docs: Update docs for v0.32.9

- website/content/en/v0.33/faq.md
- website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.33/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.33/reference/cloudformation.md
- website/content/en/v0.33/reference/threat-model.md
- website/content/en/v0.33/upgrading/upgrade-guide.md
Fixes #N/A 
- Update our docs for v0.33.3 to v0.33.4
- N/A
> docs: Update docs for v0.33.4 

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter 
- N/A
> chore: Update Karpenter for v0.34.5

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter version 
- N/A
> chore: Update Karpenter for v0.35.4

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/v0.35/faq.md
- website/content/en/v0.35/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.35/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.35/reference/cloudformation.md
- website/content/en/v0.35/reference/threat-model.md
- website/content/en/v0.35/upgrading/upgrade-guide.md
- website/hugo.yaml
Fixes #N/A 
- Update the docs for v0.35.4
- N/A
> docs: Update docs for v0.35.4

- website/content/en/v0.34/faq.md
- website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.34/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.34/reference/cloudformation.md
- website/content/en/v0.34/reference/threat-model.md
- website/content/en/v0.34/upgrading/upgrade-guide.md
Fixes #N/A 
- Update our docs for v0.34.3 to v0.34.5
- N/A
> docs: Update docs for v0.34.5

- website/content/en/docs/getting-started/_index.md
- website/content/en/preview/getting-started/_index.md
- website/content/en/v0.32/getting-started/_index.md
- website/content/en/v0.33/getting-started/_index.md
- website/content/en/v0.34/getting-started/_index.md
- website/content/en/v0.35/getting-started/_index.md
Fixes #5942 
- Updating a broken link
- N/A
> docs: Update broken link for Advanced EKS Immersion Karpenter Workshop

- go.mod
- go.sum
- pkg/operator/operator.go
Fixes #N/A 
- Bump Karpenter version to include 
- https://github.com/kubernetes-sigs/karpenter/pull/1147
> chore: Bump Karpetner Version

- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh
- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh
- website/content/en/v0.35/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh
- website/content/en/v0.35/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
Fix missing "v" in CloudFormation download URL.
> docs: Fix CloudFormation download URL

- pkg/operator/operator.go
Fixes #N/A 
Allow commonly-used operator helper functions to be accessed publicly
> chore: Allow operator functions to be accessed publicly

- go.mod
- go.sum
Fixes #N/A 
Bumps upstream karpenter to the latest release
N/A
> chore: Update Karpenter to v0.36.0

- website/content/en/docs/concepts/scheduling.md
- website/content/en/docs/troubleshooting.md
- website/content/en/preview/concepts/scheduling.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.32/concepts/scheduling.md
- website/content/en/v0.32/troubleshooting.md
- website/content/en/v0.34/concepts/scheduling.md
- website/content/en/v0.34/troubleshooting.md
- website/content/en/v0.35/concepts/scheduling.md
- website/content/en/v0.35/troubleshooting.md
- website/content/en/v0.36/concepts/scheduling.md
- website/content/en/v0.36/troubleshooting.md
Fixes #6087 
This flag has been removed from Helm chart some time ago. Lets cleanup some docs to not confuse users.
- [x ] Yes, PR includes docs updates 
- [] No
> docs: Remove settings.aws.enablePodENI from docs

- go.mod
- go.sum
> deps: bump upstream Karpenter to v0.36.1

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v0.36/faq.md
- website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.36/getting-started/migrating-from-cas/_index.md
- website/content/en/v0.36/reference/cloudformation.md
- website/content/en/v0.36/reference/threat-model.md
- website/content/en/v0.36/upgrading/upgrade-guide.md
- website/hugo.yaml
Fixes #N/A 
Updates the docs for v0.36.1
> docs: release v0.36.1

- .github/workflows/ci-test.yaml
- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/dryrun-gen.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/snapshot.yaml
Fixes #N/A 
This change updates our workflow files to run E2E testing and CI on staging branches
> test: Run E2E and CI on staging branches

- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- pkg/providers/instancetype/types.go
Fixes #N/A 
This ensures that we always update the log retention to 30d, regardless of whether we succeed or fail or cancel the test.
> ci: Always update log retention

- .github/actions/e2e/setup-cluster/action.yaml
- .github/workflows/e2e-upgrade.yaml
- test/suites/consolidation/suite_test.go
- test/suites/drift/suite_test.go
- test/suites/expiration/suite_test.go
> test: fix remaining DaemonSet induced flakes

- pkg/providers/instancetype/types.go
Fixes #N/A 
Pointing to the latest ENI Max pods file since our current pointer isn't the latest one
> chore: Update to latest ENI Max Pods file

- .github/actions/e2e/setup-cluster/action.yaml
> ci: pin cloudwatch addon version

- .github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
Fix NotFound error that's returned when trying to delete DS
> test: Fix NotFound error on upgrade

- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/providers/amifamily/ami.go
- pkg/providers/amifamily/suite_test.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/securitygroup/securitygroup.go
- pkg/providers/securitygroup/suite_test.go
- pkg/providers/subnet/subnet.go
- pkg/providers/subnet/suite_test.go
> Cherry pick v0.36.2

- .github/workflows/codegen.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/deflake.yaml
- .github/workflows/docgen.yaml
- .github/workflows/e2e-matrix-trigger.yaml
- .github/workflows/e2e-scale-trigger.yaml
- .github/workflows/e2e-version-compatibility-trigger.yaml
- .github/workflows/publish-test-tools.yaml
- .github/workflows/stale.yaml
- hack/github/feature_request_reactions.py
- hack/github/label_issue_count.py
> chore: Cherry pick repo check

- test/suites/integration/ami_test.go
- test/suites/integration/instance_profile_test.go
- test/suites/integration/security_group_test.go
- test/suites/integration/subnet_test.go
Fixes #N/A 
Fixes status condition E2E check to validate message is set to empty
> ci: Fix status condition E2E check

- test/suites/drift/suite_test.go
Fixes #N/A 
Fix dropped call to List which ensures that this drift test succeeds
> ci: Fix drift failure

- go.mod
- go.sum
> deps: bump karpenter-core to v0.31.5

- go.mod
- go.sum
> deps: bump karpenter-core to v0.32.10

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.33.5

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.34.6

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.35.5

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.36.2

- pkg/operator/operator.go
- pkg/providers/amifamily/bootstrap/bootstrap.go
- pkg/providers/amifamily/bootstrap/bottlerocket.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
- pkg/test/environment.go
- test/pkg/environment/common/expectations.go
- test/suites/integration/emptiness_test.go
- test/suites/integration/kubelet_config_test.go
- test/suites/integration/scheduling_test.go
- test/suites/integration/validation_test.go
- test/suites/interruption/suite_test.go
- test/suites/scale/deprovisioning_test.go
Fixes #N/A 
Changes knative ptr to lo ptr
make presubmit
> chore: change knative ptr to lo ptr

- website/content/en/docs/reference/cloudformation.md
- website/content/en/preview/reference/cloudformation.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.34/reference/cloudformation.md
- website/content/en/v0.35/reference/cloudformation.md
- website/content/en/v0.36/reference/cloudformation.md
> docs: Fix to add cury brackets

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/run-tests-private-cluster/action.yaml
- .github/actions/e2e/setup-cluster/action.yaml
- .github/actions/install-deps/action.yaml
- .github/workflows/ci-test.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e-version-compatibility-trigger.yaml
- .github/workflows/e2e.yaml
> ci: enable eks 1.30

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.35/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Adds a note in the getting started guide about https://github.com/eksctl-io/eksctl/issues/7775. 
N/A
> docs: add note about eksctl breaking change

- ADOPTERS.md
Fixes #N/A 
Adding Homa to list of adopters
N/A
> docs: Adding Homa to the list of adopters

- test/hack/resource/clean/main.go
- test/hack/soak/get_clusters.go
Fixes #N/A 
Unpins cluster `soak-periodic-2785632730` since it is no longer required for investigation.
N/A
> ci: unpin soak cluster

- .github/workflows/sweeper.yaml
Fixes #N/A 
- After https://github.com/aws/karpenter-provider-aws/pull/6137, the sweeper jobs is evaluating any increased number of instance profiles. Since the sweeper will need to get all the instance profiles tags for each instance profiles, We saw an increases in the call volume that is happening when running the sweeper job in parallel.  
- We are seeing increased throttling in the CI account due to request volume of Instance Profile Tags. That has resulted in the CI script not properly analyzing the instance profiles to terminate.
- Sweeper Run: https://github.com/aws/karpenter-provider-aws/actions/runs/9349837641/job/25732030282 
```
operation error IAM: ListInstanceProfileTags, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: …
```
> ci: Limit Sweeper Parallelism to avoid throttling  

- go.mod
Fixes #N/A 
Bump go version to 1.22.4
N/A
> deps: bump go to 1.22.4

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.32/faq.md
- website/content/en/v0.35/faq.md
- website/content/en/v0.36/faq.md
- website/content/en/v0.37/faq.md
Fixes #N/A 
Updates an FAQ section to first link to the best practices for upgrading AMIs. 
make website
> docs: update website recommendations

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.35/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.37/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
I ran into this while following the get started guide and trying to follow along using terraform, adding this little blurb would help relay the importance.
Wasn't 👀 
> docs: adds more of ec2 spot heads up

- website/content/en/docs/troubleshooting.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.32/troubleshooting.md
- website/content/en/v0.35/troubleshooting.md
- website/content/en/v0.36/troubleshooting.md
- website/content/en/v0.37/troubleshooting.md
Fixes #N/A 
Fix the recommended KMS policy to wildcard the `kms:Describe*` permissions.
> docs: fix KMS policy to wildcard Describe

- test/hack/resource/clean/main.go
- test/hack/soak/get_clusters.go
Fixes #N/A 
- Remove clusters that were used for investigation
- N/A
> chore: Remove clusters used for investigation

- charts/karpenter/values.yaml
Fixes #N/A 
Addresses https://github.com/aws/karpenter-provider-aws/pull/6354
> feat: default to multizone karpenter deployment

- pkg/cloudprovider/suite_test.go
> Update tests to use amdAMIID

- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/v1beta1/ec2nodeclass.go
- pkg/providers/instancetype/suite_test.go
Fixes #N/A 
Disables IMDS access from pods by reducing hop limit to 1
> feat: Reduce hop token count

- website/content/en/docs/troubleshooting.md
- website/content/en/preview/troubleshooting.md
- website/content/en/v0.32/troubleshooting.md
- website/content/en/v0.35/troubleshooting.md
- website/content/en/v0.36/troubleshooting.md
- website/content/en/v0.37/troubleshooting.md
> chore: fix grammar in troubleshooting.md

- .github/actions/e2e/setup-cluster/action.yaml
- website/static/_redirects
Fixes #N/A 
Drop old redirects from docs and drop old path checking in testing
> docs: Drop old redirects

- website/content/en/preview/concepts/disruption.md
Fixes #N/A 
Adds documentation for disruption budget by reason
make website
> docs: add disruption budgets by reason documentation

- website/content/en/docs/reference/cloudformation.md
- website/content/en/preview/reference/cloudformation.md
- website/content/en/v0.32/reference/cloudformation.md
- website/content/en/v0.35/reference/cloudformation.md
- website/content/en/v0.36/reference/cloudformation.md
- website/content/en/v0.37/reference/cloudformation.md
Fixes #N/A 
Update CloudFormation reference to discuss TLS SQS queue policy
> docs: Update cloudformation reference with tls queue policy

- website/content/en/preview/concepts/disruption.md
Fixes #N/A 
Changes the docs to reflect the changes in upstream for expiration becoming forceful. 
make website
> docs: change expiration to forceful

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/cloudprovider/suite_test.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
- test/pkg/environment/common/expectations.go
- test/suites/expiration/suite_test.go
Fixes #N/A 
Updates E2E tests for forceful expirations (plus a minor function signature update for cluster state).
> chore: forceful expiration updates

- README.md
add additional talks to README
n/a
> chore: Add talks to README

- charts/karpenter/templates/clusterrole-core.yaml
> chore: update node permissions

- go.mod
- go.sum
> chore: bump go.mod

- test/hack/resource/pkg/resourcetypes/instance.go
Fixes #N/A 
Fixes an issue with the sweeper where if more than 1000 instances are leaked, it fails to clean up the instances since the id count exceeds the maximum that can be provided to terminate-instances.
> ci: don't exceed max ids to terminate instances

- cmd/controller/main.go
- go.mod
- go.sum
- hack/docgen.sh
- hack/docs/metrics_gen/main.go
- pkg/controllers/controllers.go
- website/content/en/preview/reference/metrics.md
Fixes #N/A 
Add `operator_status_condition_count` and `operator_status_condition_transition_seconds` from operatorpkg for NodePool and NodeClaim
> chore: Add operator status condition metrics

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
Fix test for upgrade suite by upgrading CRDs before upgrading Karpenter.
> test: fix upgrade suite

- pkg/utils/utils.go
Fixes #N/A 
Taking in the change that was suggested in a previous PR - https://github.com/aws/karpenter-provider-aws/pull/6508
NA
> chore: Fix error returned when resolving nodePool from nodeClaim (utils)

- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/operator/options/options.go
- pkg/utils/utils.go
Fixes #N/A 
- Bump upstream Karpenter
> chore: Bump upstream Karpenter

- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step03-iam-cloud-formation.sh
- website/content/en/preview/getting-started/migrating-from-cas/scripts/step09-deploy.sh
Fixes #N/A 
- The preview docs should reference the main branch as the is the branch where permission and API changes are pushed
- N/A
> chore: Update preview docs to refer to the main branch

- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh
Fixes #N/A 
- The preview docs should reference the main branch as the is the branch where permission and API changes are pushed
- These changes impact the MNG and Fargate steps 
- N/A
> docs: Update preview for getting started guide for MNG and Fargate

- ADOPTERS.md
Fixes #N/A 
Adding X3M ads to adopters
> docs: Adding X3M to the list of adopters

- website/content/en/preview/concepts/disruption.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodepools.md
- website/content/en/preview/concepts/scheduling.md
- website/content/en/preview/faq.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh
- website/content/en/preview/getting-started/migrating-from-cas/scripts/step10-create-nodepool.sh
- website/content/en/preview/tasks/managing-amis.md
- website/content/en/preview/troubleshooting.md
Updating Karpenter docs examples to v1.
- [X ] Yes, PR includes docs updates 
> docs: Updated examples to v1

- test/suites/expiration/suite_test.go
Fixes #N/A 
Removed `do-not-disrupt` annotation from pods that was blocking node deletion.
Tested on local cluster.
> test: fix failure in expiration tests

- test/suites/expiration/suite_test.go
Fixes #N/A 
Fix test failure due to blocking pods with `do-not-disrupt` annotation.
Tested on local cluster.
> test: fix expiration test failure

- test/suites/drift/suite_test.go
Fixes #N/A 
- Update `TaintEffectNoExecute` to `TaintEffectPreferNoSchedule` for Start-Up Taint  Drift for the existence check
- Tested locally 
> test: Update Taint Existence check for Start-Up Drift

- charts/karpenter/templates/deployment.yaml
Fixes #N/A 
- Remove the drift env on the karpenter deployment. 
> ci: Update deployment to remove drift feature gate

- go.mod
- go.sum
> fix: bump go.mod

- go.mod
- go.sum
Fixes #N/A 
Updates the upstream karpenter reference to use the latest 
make verify && here
> chore: update mod

- charts/karpenter/README.md
- charts/karpenter/values.yaml
Fixes #N/A 
Return to `DoNotSchedule`
make test
> fix: return to DoNotSchedule

- ADOPTERS.md
Fixes #N/A 
Adding contact to X3M adopters
> docs: Adding contact to X3M adopters

- website/content/en/docs/concepts/_index.md
- website/content/en/preview/concepts/_index.md
- website/content/en/v0.32/concepts/_index.md
- website/content/en/v0.35/concepts/_index.md
- website/content/en/v0.36/concepts/_index.md
- website/content/en/v0.37/concepts/_index.md
Fixes #N/A
Enhanced documentation by adding missing sentence-ending periods.
N/A
> docs: Add missing sentence-ending periods

- hack/docs/metrics_gen/main.go
- website/content/en/preview/reference/metrics.md
Fixes #N/A 
Update metrics in the docs to the latest and fix docgen for subsystems which weren't defined
`make docgen`
> docs: Update docgen to latest

- go.mod
- hack/docs/metrics_gen/main.go
- website/content/en/preview/reference/metrics.md
Fixes #N/A 
Add stability value for metrics.
> docs: add stability for metrics

- charts/karpenter/templates/deployment.yaml
Fixes #N/A 
Cleanup extra parenthesis in helm chart that are unneccesary
> chore: Cleanup extra parenthesis in chart

- charts/karpenter/templates/clusterrole-core.yaml
- charts/karpenter/templates/post-install-hook.yaml
Fixes #N/A 
- Adding a post install hook to allow user to configure conversion webhooks on the CRDs on installation.  
> chore: Add post install hook

- charts/karpenter/templates/post-install-hook.yaml
- test/hack/e2e_scripts/diff_karpenter.sh
Fixes #N/A 
- Update the diff the karpenter helm chart to not consider helm hooks
> chore: Update GHA Karpenter helm chart diff action

- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
Fixes #6465 
Update supported description in the document of "Getting Started with Karpenter"
```make website```
> docs: Update supported description.

- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/apis/v1/nodepool_validation_cel_test.go
- pkg/cloudprovider/suite_test.go
- pkg/controllers/nodeclaim/garbagecollection/suite_test.go
- pkg/controllers/nodeclass/hash/suite_test.go
- pkg/providers/instance/suite_test.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
- test/suites/consolidation/suite_test.go
- test/suites/drift/suite_test.go
- test/suites/integration/tags_test.go
- test/suites/scheduling/suite_test.go
Fixes #N/A 
Fixes warning logs for the nodepool in https://github.com/kubernetes-sigs/karpenter/pull/1501
```
logger.go:146: 2024-08-01T12:51:20.830-0700	INFO	KubeAPIWarningLogger	log/warning_handler.go:65	unknown field "spec.template.spec.resources"
```
make apply
> chore: update to nodeclaimtemplate in nodepool

- go.mod
- go.sum
- website/content/en/preview/reference/metrics.md
Fixes #N/A 
Updated metric description for `karpenter_nodes_total_pod_requests` and `karpenter_nodes_total_pod_limits` to include daemonSet pods by running `make docgen`.
NA
> docs: Update metrics description

- charts/karpenter/templates/post-install-hook.yaml
Fixes #N/A 
- Update to use helm template flow control
- Update post install hook name 
> chore: Update post install hook naming

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bumps `sigs.k8s.io/karpenter` to latest version
> chore: Bump `sigs.k8s.io/karpenter` to latest

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Fixes #N/A 
- Bump Karpenter version
> chore: Add nodeclaim status validation for v1 on v0.33.x

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
Fixes #N/A 
- Bump Karpenter version
> chore: Add nodeclaim status validation for v1 on v0.34.x

- website/content/en/preview/reference/cloudformation.md
**Description**: This PR updates the [Cloudformation](https://karpenter.sh/docs/reference/cloudformation/) docs to match the new cloudformation.yaml for v1.
- [X ] Yes, PR includes docs updates 
> docs: Update cloudformation.yaml docs for v1

- website/content/en/preview/concepts/disruption.md
- website/content/en/preview/concepts/nodepools.md
Fixes #N/A 
Adds consolidateAfter docs
> docs: add docs on consolidateAfter

- charts/karpenter/README.md
- hack/docs/metrics_gen/main.go
- website/content/en/docs/contributing/development-guide.md
- website/content/en/docs/reference/metrics.md
- website/content/en/docs/reference/settings.md
- website/content/en/preview/contributing/development-guide.md
- website/content/en/preview/reference/metrics.md
- website/content/en/preview/reference/settings.md
Fixes #N/A 
Addresses metrics port change in development guide.
make presubmit
> docs: update metrics port info

- charts/karpenter/README.md
- website/content/en/preview/reference/instance-types.md
- website/content/en/preview/reference/settings.md
Fixes #N/A 
Ran `make docgen`
make presubmit
> docs: run docgen

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter version  
> chore: Bump upstream version for v0.33

- .github/actions/e2e/install-karpenter/action.yaml
- go.mod
- go.sum
Fixes #N/A 
- Enable webhooks for v0.33.x
- N/A
> ci: Enables webhooks for v0.33.x

- website/content/en/preview/reference/cloudformation.md
**Description**: Fix minor formatting issues in Karpenter CloudFormation docs.
> docs: Fix formatting in cloudformation docs

- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/v1-migration.md
Fixes #N/A 
- Add steps for rollback from v1 to v1beta1 resources
> docs: Update Add v1 Rollback

- go.mod
- go.sum
- test/pkg/environment/common/environment.go
- test/suites/chaos/suite_test.go
- test/suites/consolidation/suite_test.go
- test/suites/expiration/suite_test.go
- test/suites/integration/daemonset_test.go
- test/suites/integration/validation_test.go
- test/suites/scale/deprovisioning_test.go
- test/suites/termination/emptiness_test.go
- test/suites/termination/termination_grace_period_test.go
Fixes #N/A 
Bumps sigs.k8s.io/karpenter to include https://github.com/kubernetes-sigs/karpenter/pull/1545.
Tested locally
> deps: bump sigs.k8s.io/karpenter

- charts/karpenter/README.md
- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/post-install-hook.yaml
- charts/karpenter/values.yaml
Fixes #6701 
Makes the post-install hook version configurable
make apply
> chore: make image configurable

- charts/karpenter-crd/values.yaml
- charts/karpenter/README.md
- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/post-install-hook.yaml
- charts/karpenter/values.yaml
- go.mod
- go.sum
- pkg/apis/v1/ec2nodeclass.go
- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
- test/pkg/environment/common/environment.go
- test/suites/chaos/suite_test.go
- test/suites/consolidation/suite_test.go
- test/suites/expiration/suite_test.go
- test/suites/integration/emptiness_test.go
- test/suites/integration/validation_test.go
- test/suites/scale/deprovisioning_test.go
Fixes #N/A 
Backports #6699 and bumps sigs.k8s.io/karpenter
> Ubuntu Backport and Version Bump v0.35.x

- charts/karpenter-crd/values.yaml
- charts/karpenter/README.md
- charts/karpenter/templates/_helpers.tpl
- charts/karpenter/templates/post-install-hook.yaml
- charts/karpenter/values.yaml
- go.mod
- go.sum
- pkg/apis/v1/ec2nodeclass.go
- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
- test/pkg/environment/common/environment.go
- test/suites/chaos/suite_test.go
- test/suites/consolidation/suite_test.go
- test/suites/expiration/suite_test.go
- test/suites/integration/emptiness_test.go
- test/suites/integration/validation_test.go
- test/suites/scale/deprovisioning_test.go
- website/content/en/preview/concepts/nodeclasses.md
Fixes #N/A 
- Backports 
- https://github.com/aws/karpenter-provider-aws/pull/6699
- https://github.com/aws/karpenter-provider-aws/pull/6716
- bumps sigs.k8s.io/karpenter
- `make presubmit` 
> Ubuntu Backport and Version Bump v0.37.x

- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
- Adding a note as part of Karpenter 1.0 release, that all support for pre-v0.32 of Karpenter will be dropped
- N/A
> docs: Adding Karpenter version support note

- test/suites/integration/ami_test.go
Fixes #N/A 
Fix AMI discovery on v0.37.x
> test: Fix AMI Discovery for v0.37.x

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.37.1

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.35.6

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.36.3

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.34.7

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.33.6

- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/preview/upgrading/v1-migration.md
Fixes #N/A 
Miscellaneous small corrections and updates to the EC2NodeClass docs ahead of the v1 release.
> docs: v1 NodeClass doc updates

- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/v1-migration.md
Fixes #N/A 
Updated upgrade guide to include wait for instance termination change.
NA
> docs: Add wait for instance termination to changelog

- charts/karpenter/README.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v0.35/upgrading/upgrade-guide.md
- website/content/en/v0.36/upgrading/upgrade-guide.md
- website/content/en/v0.37/upgrading/upgrade-guide.md
> docs: run docgen and correct hyperlink

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v1.0.0

- website/content/en/docs/contributing/documentation-updates.md
- website/content/en/preview/concepts/disruption.md
- website/content/en/preview/contributing/documentation-updates.md
Fixes #N/A 
This PR fixes some typos in the docs.
NA
> docs: fix typos

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodeclasses.md
Fixes #N/A 
- Update group on the nodeClassRef in the nodeclass page
- N/A
> docs: Update for the Group for nodeclassref docs

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.37/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
This PR fixes typo in the docs (getting-started-with-karpenter).
NA
> docs: fix typo

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/docs/concepts/nodepools.md
- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodepools.md
- website/content/en/preview/upgrading/v1-migration.md
- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
This PR updates docs to add information about status conditions.
NA
> docs: Update docs for status conditions

- pkg/providers/amifamily/resolver.go
Fixes #N/A 
This fixes a failure that we had in our golang-ci job by ignoring the `gosec` check on this line
> chore: Fix golang-ci failure for integer conversion

- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/preview/upgrading/v1-migration.md
- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
Updating CRD can trigger`label validation error` or `annotation validation error`. The troubleshooting guide has details about this, but these details are not referenced in the migration page. This commit adds pointers to the troubleshooting page to help those upgrading who may receive these errors.
Yes. Deploy preview link shows changes correctly and links work.
> docs: Adding pointer to troubleshooting guide for crd update errors v1-migration.md

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- charts/karpenter-crd/values.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
Fixes #N/A 
- Bump upstream karpenter 
> chore: Bump Upstream Karpenter for v0.33.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- charts/karpenter-crd/values.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
Fixes #N/A 
- Bump upstream karpenter
- N/A
> chore: Bump Upstream Karpenter for v0.34.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- charts/karpenter-crd/values.yaml
- hack/mutation/conversion_webhooks_injection.sh
> chore: Backport serviceNamespace for v1.0.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- charts/karpenter-crd/values.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
Fixes #N/A 
- Bump upstream karpenter
- N/A
> chore: Bump Upstream Karpenter for v0.35.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- charts/karpenter-crd/values.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
Fixes #N/A 
- Bump upstream karpenter
- N/A
> chore: Bump Upstream Karpenter for v0.36.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- charts/karpenter-crd/values.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
Fixes #N/A 
- Bump upstream karpenter 
- N/A
> chore: Bump Upstream Karpenter for v0.37.x

- website/content/en/docs/faq.md
- website/content/en/preview/faq.md
- website/content/en/v0.32/faq.md
- website/content/en/v0.36/faq.md
- website/content/en/v0.37/faq.md
- website/content/en/v1.0/faq.md
Fixes #N/A 
Updates wording around provisioning.
N/A
> docs: Update provisioning wording

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- Bump commit to use a commit that lives in the snapshot repo 
- N/A 
> ci: Update Karpenter commit used for upgrade testing

- test/pkg/environment/common/expectations.go
- test/suites/termination/termination_test.go
> test: Add E2E tests to validate pod grouping and waiting fix

- .golangci.yaml
- pkg/providers/instancetype/suite_test.go
- test/pkg/environment/common/monitor.go
Fixes #N/A 
Address golangci warnings
make verify
> chore: update golangci 35

- .golangci.yaml
- pkg/providers/instancetype/suite_test.go
- test/pkg/environment/common/monitor.go
Fixes #N/A 
Address golangci warnings.
make verify
> chore: update golangci 34

- .golangci.yaml
- pkg/providers/instancetype/suite_test.go
- test/pkg/environment/common/monitor.go
Fixes #N/A 
Address golangci warnings.
make verify
> chore: update golangci 37

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bump karpenter core
make presubmit
> chore: Bump karpenter core 33

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bump karpenter core
make verify
> chore: bump karpenter core 34

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bump karpenter core
make verify
> chore: bump karpenter core 35

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bump karpenter core
make verify
> chore: bump karpenter core 36

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- hack/mutation/conversion_webhook_injection.sh
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bump Karpenter core
make verify
> chore: bump karpenter core 37

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/apis/v1/ec2nodeclass.go
- pkg/apis/v1beta1/ec2nodeclass.go
- pkg/cloudprovider/cloudprovider.go
- pkg/providers/amifamily/resolver.go
- pkg/providers/instance/instance.go
Fixes #N/A 
Bump Karpenter core
make presubmit
> chore: bump go mod v1

- go.mod
- go.sum
> chore: bump go mod v0.36

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
> ci: Fix CI failure in GHA

- charts/karpenter/README.md
- hack/docs/compatibilitymatrix/main.go
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/reference/instance-types.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v0.36/upgrading/upgrade-guide.md
Fixes #N/A 
Update docs and upgrade guides
make docgen
> docs: run docgen and make upgrade guide update v0.37.x

- go.mod
- go.sum
> chore: Bump v1 core

- go.mod
- go.sum
> chore: Bump v037 core

- go.mod
- go.sum
> chore: Bump v036 core

- go.mod
- go.sum
> chore: Bump v035 core

- go.mod
- go.sum
> chore: Bump v034 core

- go.mod
- go.sum
> chore: Bump v033 core

- website/content/en/v0.36/upgrading/upgrade-guide.md
- website/content/en/v0.37/upgrading/upgrade-guide.md
> docs: changelog for v36 and v37 website

- ADOPTERS.md
> Add Postnord to Karpenter Adopters list

- go.mod
- go.sum
Fixes #N/A 
Bump `sigs.k8s.io/karpenter` to the latest version with build fixes
> chore: Bump sigs.k8s.io/karpenter to latest

- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
Fixes #N/A 
Cherry-pick #6777 
> cherry-pick(1.0.x): fix: ensure alias version isn't dropped round-trip (#6777)

- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
Fixes #N/A 
Cherry picks #6777 
> cherry-pick(0.33.x): fix: ensure alias version isn't dropped round-trip (#6777)

- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
Fixes #N/A 
Cherry picks #6777 
> cherry-pick(0.36.x): fix: ensure alias version isn't dropped round-trip (#6777)

- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
Fixes #N/A 
Cherry picks #6777 
> cherry-pick(0.35.x): fix: ensure alias version isn't dropped round-trip (#6777)

- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
Fixes #N/A 
Cherry pick #6777 
> cherry-pick(0.37.x): fix: ensure alias version isn't dropped round-trip (#6777)

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Updates gomod for cherry-pick for 1662
testing here
> chore: update gomod for cherry-pick

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- hack/toolchain.sh
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/apis/v1/ec2nodeclass.go
- pkg/apis/v1beta1/ec2nodeclass.go
Fixes #N/A 
Updates gomod for cherrypick for 1662
testing here
> chore: update gomod for cherrypick

- go.mod
- go.sum
Fixes #N/A 
Added metrics -
karpenter_nodeclass_termination_duration_seconds
Added test
> chore: bump operatorpkg

- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/apis/v1/labels.go
Fixes #N/A 
Cherry picks #6777 
> cherry-pick(0.34.x): fix: ensure alias version isn't dropped round-trip (#6777)

- go.mod
- go.sum
- pkg/controllers/nodeclass/status/controller.go
- pkg/controllers/nodeclass/termination/controller.go
Fixes #N/A 
Cherry-pick change from #1658 onto `release-v1.0.x`
> chore: Cherry pick patch with conflict fix onto `release-v1.0.x`

- pkg/controllers/nodeclass/status/ami_test.go
- pkg/providers/amifamily/types.go
> cherry-pick(v1.0.x): fix: Correct the AMI selector label requirements for NVIDIA and Neuron Variants

- pkg/operator/operator.go
- pkg/providers/amifamily/resolver.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/test/environment.go
Fixes #N/A 
Add a missed interface for `amifamily.Resolver`
> chore: Add an `amifamily.Resolver` interface

- pkg/test/environment.go
Fixes #N/A 
Fix missed `instanceTypeCache` assignment in `test.Environment`
> test: Fix missed instance type cache assignment

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.0/upgrading/v1-migration.md
- website/hugo.yaml
Fixes #N/A 
- Update our docs to use the current version of Karpenter
> docs: Update website to use karpenter `1.0.2` 

- pkg/operator/operator.go
- pkg/providers/instance/instance.go
- pkg/test/environment.go
Fixes #N/A 
Remove InstanceTypeProvider dead dependency in Instance Provider
> chore: Remove InstanceTypeProvider dependency from Instance Provider

- charts/karpenter/templates/clusterrole-core.yaml
- go.mod
- go.sum
- pkg/apis/v1/ec2nodeclass_conversion.go
- pkg/apis/v1/ec2nodeclass_conversion_test.go
- pkg/controllers/controllers.go
- test/suites/integration/migration_test.go
> chore: Storage version migration v1.0.x

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/docs/concepts/nodepools.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.0/faq.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.0/reference/cloudformation.md
- website/content/en/v1.0/reference/threat-model.md
- website/content/en/v1.0/upgrading/v1-migration.md
> docs: update patch refs 1.0.3

- .github/workflows/e2e-matrix.yaml
> ci: Update Commit used for the Upgrade tests for release-v0.33.x

- .github/workflows/e2e-matrix.yaml
> ci: Update Commit used for the Upgrade tests for release-v0.34.x

- .github/workflows/e2e-matrix.yaml
> ci: Update Commit used for the Upgrade tests for release-v0.35.x 

- .github/workflows/e2e-matrix.yaml
> ci: Update Commit used for the Upgrade tests for release-v0.37.x

- .github/workflows/e2e-matrix.yaml
> ci: Update Commit used for the Upgrade tests for release-v1.0.x

- go.mod
- go.sum
> chore: bump core 36

- go.mod
- go.sum
> chore: bump core 35

- go.mod
- go.sum
> chore: bump core v1.0.x

- go.mod
- go.sum
> chore: bump core v0.37.x

- go.mod
- go.sum
> chore: bump core v34

- go.mod
- go.sum
> chore: bump core v33

- cmd/controller/main.go
- hack/docs/instancetypes_gen/main.go
- pkg/cloudprovider/cloudprovider.go
- pkg/controllers/controllers.go
- pkg/controllers/providers/instancetype/controller.go
- pkg/controllers/providers/instancetype/suite_test.go
- pkg/operator/operator.go
- pkg/providers/instancetype/instancetype.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
- pkg/providers/launchtemplate/suite_test.go
- pkg/test/environment.go
Fixes #N/A 
Add `instancetype.Resolver` to generate instance types in a single place
> chore: Add instance type resolver for creating instance types

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/setup-cluster/action.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e.yaml
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Bumps the eksctl version used in CI to v0.191.0 to support EKS 1.31.
> ci: bump eksctl version

- .github/actions/e2e/cleanup/action.yaml
- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/run-tests-private-cluster/action.yaml
- .github/actions/e2e/setup-cluster/action.yaml
- .github/actions/install-deps/action.yaml
- .github/workflows/ci-test.yaml
- .github/workflows/e2e-cleanup.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e-upgrade.yaml
- .github/workflows/e2e-version-compatibility-trigger.yaml
- .github/workflows/e2e.yaml
- pkg/providers/version/version.go
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/hugo.yaml
> cherry-pick(1.0.x): chore: update support for 1.31 (#7126)

- go.mod
- go.sum
- test/suites/ami/suite_test.go
Fixes #N/A 
Also includes upstream dep bump
> cherry-pick(1.0.x):  test: bump pinned AMIs for 1.31 (#7136)

- hack/docs/metrics_gen/main.go
- website/content/en/preview/reference/instance-types.md
- website/content/en/preview/reference/metrics.md
- website/content/en/preview/reference/settings.md
Fixes #N/A 
Fix `make docgen` failure on `main`
`make docgen`
> chore: Fix docgen failures

- test/suites/integration/scheduling_test.go
Fixes #N/A 
Addresses test failure by pinning AMI
Make e2etests
> fix: gpu label test v0.37.x

- go.mod
- go.sum
> chore: bump core

- website/content/en/docs/concepts/disruption.md
- website/content/en/preview/concepts/disruption.md
- website/content/en/v1.0/concepts/disruption.md
Fixing the current documentation.
In markdown reader
> docs: Fix Karpenter disruption node taint

- go.mod
- go.sum
Fixes #N/A 
Pin sigs.k8s.io/karpenter to v1.0.4
> deps: bump sigs.k8s.io/karpenter to v1.0.4

- go.mod
- go.sum
Fixes #N/A 
Pin sigs.k8s.io/karpenter to v0.37.5
> deps: bump sigs.k8s.io/karpenter to v0.37.5

- go.mod
- go.sum
Fixes #N/A 
Pin sigs.k8s.io/karpenter to v0.36.7
> deps: bump sigs.k8s.io/karpenter to v0.36.7

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.35.10

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.33.10

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v0.34.11

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/v0.36/faq.md
- website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.36/upgrading/upgrade-guide.md
- website/content/en/v0.37/faq.md
- website/content/en/v0.37/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.37/upgrading/upgrade-guide.md
- website/content/en/v1.0/faq.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/upgrading/v1-migration.md
- website/hugo.yaml
Fixes #N/A 
Updates references to patch release for the following versions:
- `v0.33.10`
- `v0.34.11`
- `v0.35.10`
- `v0.36.7`
- `v0.37.5`
- `v1.0.6`
n/a
> docs: update patch release refs

- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/setup-cluster/action.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/hack/e2e_scripts/install_karpenter.sh
- test/suites/webhook/suite_test.go
- test/suites/webhooks/suite_test.go
Fixes #N/A 
Adds conditional in workflows for running smoke tests for webhooks.
> test: add smoke test for webhooks

- charts/karpenter/templates/deployment.yaml
> cherry-pick(0.33.x): disable webhooks appropriately in chart (#7177)

- charts/karpenter/templates/deployment.yaml
> cherry-pick(0.34.x): disable webhooks appropriately in chart (#7177)

- charts/karpenter/templates/deployment.yaml
> cherry-pick(0.36.x): disable webhooks appropriately in chart (#7177)

- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/setup-cluster/action.yaml
- .github/workflows/e2e-matrix.yaml
- .github/workflows/e2e.yaml
- test/suites/webhooks/suite_test.go
Fixes #N/A 
Backports webhook smoke test.
> fix: Backport webhook smoke test v0.33.x

- pkg/aws/sdk.go
Fixes #N/A 
Removing STSAPI  because we don't mock anything for STS
make test
> Removed STSAPI

- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.37/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Fixes the eksctl installation page URL in the docs
N/A
> docs: update eksctl installation page URL

- test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
Fixes bool parsing in test for webhooks.
> fix: env var in test

- test/hack/e2e_scripts/install_karpenter.sh
> fix: remove skip-crds

- examples/v1/max-node-lifetime.yaml
Fixing a typo inside an example
It's an example it's not tested
> fix: Fix typo in example

- website/content/en/docs/troubleshooting.md
- website/content/en/v0.32/troubleshooting.md
- website/content/en/v0.36/troubleshooting.md
- website/content/en/v0.37/troubleshooting.md
- website/content/en/v1.0/troubleshooting.md
Fixes #N/A 
- Fixed a typo
- N/A
> docs: Fix a typo in the troubleshooting guide

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/docs/concepts/nodepools.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.0/faq.md
- website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.0/reference/cloudformation.md
- website/content/en/v1.0/reference/threat-model.md
- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
- Update docs to reflect v1.06
> docs: Update migration docs to v1.0.6

- website/content/en/docs/getting-started/migrating-from-cas/scripts/step08-generate-chart.sh
- website/content/en/preview/getting-started/migrating-from-cas/scripts/step08-generate-chart.sh
- website/content/en/v0.32/getting-started/migrating-from-cas/scripts/step08-generate-chart.sh
- website/content/en/v0.36/getting-started/migrating-from-cas/scripts/step08-generate-chart.sh
- website/content/en/v0.37/getting-started/migrating-from-cas/scripts/step08-generate-chart.sh
- website/content/en/v1.0/getting-started/migrating-from-cas/scripts/step08-generate-chart.sh
> docs: fix missing setting INTERRUPTION_QUEUE

- website/content/en/preview/concepts/scheduling.md
Modified a statement in Topology spread section
Fixes #N/A 
**Description** Modified a statement in Topology spread section
> Update Topology spread section in scheduling.md

- .github/actions/e2e/install-karpenter/action.yaml
- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- hack/mutation/conversion_webhook_injection.sh
- hack/mutation/ec2nodeclasses.sh
- hack/mutation/nodeclaims.sh
- hack/mutation/nodepools.sh
- test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
Templates karpenter-crd charts so that apiserver is able to correctly perform lookups if upgrading/installing to this version with webhooks disabled.
Webhook test suite.
> fix: Cherry pick chart change v0.33.x

- .github/actions/e2e/install-karpenter/action.yaml
- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- hack/mutation/conversion_webhook_injection.sh
- hack/mutation/ec2nodeclasses.sh
- hack/mutation/nodeclaims.sh
- hack/mutation/nodepools.sh
- test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
Templates karpenter-crd charts so that apiserver is able to correctly perform lookups if upgrading/installing to this version with webhooks disabled.
Webhook test suite.
> fix: Cherry pick chart change v0.35.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- hack/mutation/conversion_webhook_injection.sh
- hack/mutation/ec2nodeclasses.sh
- hack/mutation/nodeclaims.sh
- hack/mutation/nodepools.sh
- test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
Templates karpenter-crd charts so that apiserver is able to correctly perform lookups if upgrading/installing to this version with webhooks disabled.
Webhook test suite.
> fix: Cherry pick chart change v0.36.x

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/cloudprovider/suite_test.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
Bumps sigs.k8s.io/karpenter to run E2Es in preparation for patch release
> deps: bump sigs.k8s.io/karpenter to pseudo-version

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v1.0.5

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/docs/concepts/nodepools.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.0/faq.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.0/reference/cloudformation.md
- website/content/en/v1.0/reference/threat-model.md
- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
Updates references of `v1.0.6` and `v1.0.7`.
> docs: update docs for v1.0.7 release

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter/templates/clusterrole-core.yaml
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
> fix: scope CRD update permissions v0.37.x

- charts/karpenter/templates/clusterrole-core.yaml
> fix: scope CRD update permissions v0.36.x

- charts/karpenter/templates/clusterrole-core.yaml
> fix: scope CRD update permissions v0.35.x

- charts/karpenter/templates/clusterrole-core.yaml
> fix: scope CRD update permissions v0.34.x

- .github/workflows/resource-count.yaml
- charts/karpenter/templates/clusterrole-core.yaml
> fix: scope CRD update permissions v0.33.x

- go.mod
- go.sum
Fixes #N/A 
bump sigs.k8s.io/karpenter
NA
> bump sigs.k8s.io/karpenter

- test/suites/ipv6/suite_test.go
Fixes #N/A 
IPv6 e2e tests have incorrect instance ID passed. Also removed the ec2 API call to use existing helper function from env.
> fix e2e ipv6 test issue

- pkg/controllers/nodeclass/status/instanceprofile_test.go
- pkg/providers/instanceprofile/instanceprofile.go
Fixes #N/A 
Made instance profile tagging optional.
`manually tested`
> chore: instance profile tags optional

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/docs/concepts/nodepools.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/v0.36/faq.md
- website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.36/upgrading/upgrade-guide.md
- website/content/en/v0.37/faq.md
- website/content/en/v0.37/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v0.37/upgrading/upgrade-guide.md
- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.0/faq.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.0/reference/cloudformation.md
- website/content/en/v1.0/reference/threat-model.md
- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
Update docs for patch releases.
NA
> docs: Update docs for patch releases

- test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
- Enable node repair for our E2E testing
- N/A
> ci: Enable Node Repair for the E2E testing

- website/content/en/preview/reference/settings.md
Fixes #N/A 
- Add feature flag for node repair 
- N/A
> docs: Add feature flag for node Repair

- website/content/en/docs/upgrading/v1-migration.md
- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
Pins the get-policy script used in the v1 migration guide.
> docs: pin get-policy script

- go.mod
- go.sum
> deps: bump sigs.k8s.io/karpenter to v1.1.0

- ADOPTERS.md
Fixes #N/A 
Adding Kaltura to list of adopters
#N/A
> docs: Adding Kaltura to the list of adopters 

- pkg/providers/instanceprofile/instanceprofile.go
- pkg/providers/instanceprofile/suite_test.go
Fixes #5470
Adds support for IAM roles with custom paths
Verified by using a node role with custom paths. 
Prior to this change, the node class was not ready and logs showed `api error ValidationError: The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-`
Post this change, node class becomes ready.
> feat: support paths in IAM roles

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/docs/concepts/nodepools.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step03-iam-cloud-formation.sh
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/v1.1/concepts/disruption.md
- website/content/en/v1.1/concepts/nodeclasses.md
- website/content/en/v1.1/faq.md
- website/content/en/v1.1/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.1/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.1/reference/cloudformation.md
- website/content/en/v1.1/reference/threat-model.md
- website/content/en/v1.1/upgrading/upgrade-guide.md
Fixes #N/A 
Adds in docs changes needed for v1.1.1 based on changes in https://github.com/aws/karpenter-provider-aws/pull/7519/files
> docs: add docs for v1.1.1

- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
fix typo in kubectl command
N/A
> docs: fix typo in kubectl command

- ADOPTERS.md
Add Legit Security to adopters
> docs: Add Legit Security to ADOPTERS

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/docs/concepts/nodepools.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step03-iam-cloud-formation.sh
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/v1.1/faq.md
- website/content/en/v1.1/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.1/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.1/reference/cloudformation.md
- website/content/en/v1.1/reference/threat-model.md
- website/hugo.yaml
Fixes #N/A 
updated doc changes for 1.1.2
make website
> docs: 1.1.2 doc changes

- test/suites/ami/suite_test.go
Fixes #N/A 
Needed to bump the ami version to fix integration test
make presubmit
> Chore: Ami test fix for 1.32

- go.mod
- go.sum
Fixes #N/A 
bump sigs.k8s.io/karpenter to v1.2.0
> deps: bump sigs.k8s.io/karpenter to v1.2.0

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/v1.1/faq.md
- website/content/en/v1.1/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.1/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.1/reference/cloudformation.md
- website/content/en/v1.1/reference/threat-model.md
- website/content/en/v1.2/faq.md
- website/content/en/v1.2/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.2/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.2/reference/cloudformation.md
- website/content/en/v1.2/reference/threat-model.md
- website/hugo.yaml
Fixes #N/A 
- Update the docs for v1.1.3 and v1.2.1 releases
- N/A
> docs: Update to Karpenter version reference after patch releases

- website/content/en/docs/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
- website/content/en/preview/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
- website/content/en/v1.1/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
> docs: update nodes eligible dashboard name

- go.mod
- go.sum
Fixes #N/A 
- Bump sigs.k8s.io/karpenter to v0.36.9
- N/A
> chore: Bump sigs.k8s.io/karpenter to v0.36.9

- go.mod
- go.sum
Fixes #N/A 
- Bump sigs.k8s.io/karpenter to v0.37.7
- N/A
> chore: Bump sigs.k8s.io/karpenter to v0.37.7

- website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
- Update patch version for pre-v1.0 version of Karpenter
- N/A
> docs: Update the v1 migration doc for patches

- go.mod
- pkg/cloudprovider/suite_test.go
- pkg/controllers/nodeclass/ami_test.go
- pkg/controllers/providers/ssm/invalidation/suite_test.go
- pkg/fake/ec2api.go
- pkg/fake/utils.go
- pkg/providers/amifamily/suite_test.go
- pkg/providers/amifamily/types.go
- pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
Cherry-picks #7672.
`make test` and `/karpenter snapshot`
> cherry-pick(v1.2.x): fix: only select available AMIs (#7672)

- website/content/en/docs/getting-started/_index.md
add the link to karpenter-provider-alibabacloud
No need.
> docs: add the link to karpenter-provider-alibabacloud

- go.mod
Fixes #N/A 
Bump go minor version to 1.23.6
N/A
> chore: Bump go minor version to 1.23.6

- website/content/en/docs/concepts/disruption.md
- website/content/en/preview/concepts/disruption.md
- website/content/en/v1.0/concepts/disruption.md
- website/content/en/v1.1/concepts/disruption.md
- website/content/en/v1.2/concepts/disruption.md
Fixes #7708
Updates the disruption docs to reflect the interaction between TGP and the `do-not-disrupt` annotation.
> docs: update pod level controls for TGP

- go.mod
Fixes #N/A 
Bumps go to 1.24.0.
> deps: bump go to 1.24.0

- test/pkg/environment/aws/default_nodepool.yaml
Fixes #N/A 
- Use EC2NodeClass
> chore: Update to use EC2NodeClass for the default nodeclass

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- go.mod
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/controllers/nodeclass/ami_test.go
- pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
- pkg/providers/amifamily/bottlerocket.go
- pkg/providers/amifamily/suite_test.go
- website/content/en/preview/concepts/nodeclasses.md
> chore: Backport neuron support for bottlerocket 1.2.x

- pkg/controllers/nodeclass/controller.go
- pkg/controllers/nodeclass/validation.go
- pkg/controllers/nodeclass/validation_test.go
Fixes #N/A 
Clear entries for deleted nodeclasses from the validation cache. This isn't strictly necessary, but was brought to our attention by some failing E2E tests which were recreating NodeClasses with the same name and spec. We could have modified these tests to ensure we have a cache miss, but deleting the nodeclass clearing the cache is more intuitive regardless.
`make e2etests` and `make test`
> chore: delete validation cache entry when resource deleted

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
> chore: bump core for E2Es 1.0.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
> chore: bump core for E2Es 1.1.x

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
> chore: bump core for E2Es 1.2.x

- go.mod
- go.sum
Fixes #N/A 
- Update Karpenter to v1.1.2
> chore: Update Karpenter to v1.1.2

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.0/faq.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.0/reference/cloudformation.md
- website/content/en/v1.0/reference/threat-model.md
- website/content/en/v1.0/upgrading/v1-migration.md
- website/content/en/v1.1/faq.md
- website/content/en/v1.1/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.1/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.1/reference/cloudformation.md
- website/content/en/v1.1/reference/threat-model.md
- website/content/en/v1.2/faq.md
- website/content/en/v1.2/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.2/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.2/reference/cloudformation.md
- website/content/en/v1.2/reference/threat-model.md
- website/hugo.yaml
Fixes #N/A 
Update docs to new release tags
N/A
> docs: update docs to new release tags

- go.mod
- go.sum
Fixes #N/A 
Pin sigs.k8s.io/karpenter to v1.3.0 
`/karpenter snapshot` (from the same commit on main)
> chore: Pin sigs.k8s.io/karpenter to v1.3.0

- go.mod
- go.sum
Fixes #N/A 
Pin sigs.k8s.io/karpenter to v1.3.1
> chore: Pin sigs.k8s.io/karpenter to v1.3.1

- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
Bump upstream Karpenter version
N/A
> chore: Bump upstream Karpenter version

- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v1.3/upgrading/upgrade-guide.md
Fixes #N/A 
Add a 1.3.0 upgrade section to the upgrade guide
> docs: Add a 1.3.0 upgrade section to the upgrade guide

- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v1.3/upgrading/upgrade-guide.md
Fixes #N/A 
Add note about using the `karpenter.sh/capacity-type: reserved` for the ODCR feature flag
> docs: Add note about using the reserved capacity type

- pkg/cloudprovider/cloudprovider.go
Fixes #7850 
Treat terminating as NotFound in NodeClass resolution and avoid returning instance types when the NodeClass is terminating or NotFound
> Fix spurious logging while NodeClass is terminating

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/v1.3/faq.md
- website/content/en/v1.3/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.3/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.3/reference/cloudformation.md
- website/content/en/v1.3/reference/threat-model.md
- website/hugo.yaml
> Docs: updates for 1.3.2 release

- pkg/errors/errors.go
Just a tiny typo fix I spotted.
Thanks to all contributors for the hard work! 💝 
---
> Chore: minor typo fix in errors.go

- go.mod
- pkg/cloudprovider/suite_test.go
- pkg/controllers/providers/pricing/suite_test.go
- pkg/fake/atomic.go
- pkg/fake/ec2api.go
- pkg/fake/pricingapi.go
- pkg/fake/types.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/pricing/pricing.go
> cherry-pick(1.2.x): fix: Fix spot pricing data being overridden when fetched (#7877)

- go.mod
- pkg/cloudprovider/suite_test.go
- pkg/controllers/providers/pricing/suite_test.go
- pkg/fake/atomic.go
- pkg/fake/ec2api.go
- pkg/fake/pricingapi.go
- pkg/fake/types.go
- pkg/providers/instancetype/suite_test.go
- pkg/providers/pricing/pricing.go
> cherry-pick(1.1.x): fix: Fix spot pricing data being overridden when fetched (#7877)

- website/content/en/v1.1/faq.md
- website/content/en/v1.1/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.1/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.1/reference/cloudformation.md
- website/content/en/v1.1/reference/threat-model.md
- website/content/en/v1.2/faq.md
- website/content/en/v1.2/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.2/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.2/reference/cloudformation.md
- website/content/en/v1.2/reference/threat-model.md
Fixes #N/A 
- Update our docs for the patch releases for v1.1.x and v1.2.x
- N/A
> docs: Update the docs for the patch releases

- website/content/en/docs/concepts/disruption.md
- website/content/en/preview/concepts/disruption.md
- website/content/en/v0.32/concepts/disruption.md
- website/content/en/v1.0/concepts/disruption.md
- website/content/en/v1.1/concepts/disruption.md
- website/content/en/v1.2/concepts/disruption.md
- website/content/en/v1.3/concepts/disruption.md
> Docs: Update spot disruption docs for more clarity

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/v1.3/faq.md
- website/content/en/v1.3/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.3/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.3/reference/cloudformation.md
- website/content/en/v1.3/reference/threat-model.md
Fixes #N/A 
Bumps refs to 1.3.2 to 1.3.3
> docs: bump latest release to v1.3.3

- Makefile
Fixes #1387 
Adds race detections to e2e testing
make e2etest
> test: add race detection to E2Es

- website/content/en/docs/concepts/nodepools.md
- website/content/en/preview/concepts/nodepools.md
- website/content/en/v0.32/concepts/nodepools.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.1/concepts/nodepools.md
- website/content/en/v1.2/concepts/nodepools.md
- website/content/en/v1.3/concepts/nodepools.md
docs: Fix broken link in concepts/nodepools 
> docs: Fix broken link

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- go.mod
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
Fixes #N/A 
- Bump go mod version to avoid vulnerability-check
> chore: Bump Go mod version

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter version
> chore: Bump go mod for Karpenter

- website/content/en/docs/concepts/disruption.md
Fixes #N/A 
Fix typo the feature flag name is NodeRepair while this line refers to drift.
- [] No
> docs: Fix Feature Flag Name 

- website/content/en/preview/concepts/disruption.md
- website/content/en/v1.2/concepts/disruption.md
- website/content/en/v1.3/concepts/disruption.md
- website/content/en/v1.4/concepts/disruption.md
Fixes #N/A 
- Fix typo the feature flag name is NodeRepair while this line refers to drift.
- N/A
> docs: Update Node Repair Feature Flag

- website/content/en/preview/concepts/nodeclasses.md
Fixes #N/A 
Adds a note about the IAM actions required for `EC2NodeClass` `spec.capacityReservationSelectorTerms`.
> docs(concepts): note IAM action required for capacity reservations

- go.mod
- go.sum
Fixes #N/A 
Bump upstream karpenter version.
N/A
> chore: bump upstream version

- hack/docs/metrics_gen/main.go
- pkg/batcher/createfleet.go
- pkg/batcher/describeinstances.go
- pkg/batcher/terminateinstances.go
- pkg/cloudprovider/drift.go
- pkg/controllers/nodeclaim/capacityreservation/controller.go
- pkg/controllers/nodeclass/capacityreservation.go
- pkg/fake/ec2api.go
- pkg/fake/ssmapi.go
- pkg/operator/options/options_validation.go
- pkg/providers/amifamily/al2.go
- pkg/providers/amifamily/al2023.go
- pkg/providers/amifamily/bottlerocket.go
- pkg/providers/amifamily/types.go
- pkg/providers/amifamily/windows.go
- pkg/providers/instanceprofile/instanceprofile.go
- pkg/providers/launchtemplate/launchtemplate.go
- pkg/providers/ssm/provider.go
- pkg/providers/subnet/subnet.go
- pkg/providers/version/version.go
- pkg/utils/utils.go
Fixes #N/A 
Add structured errors to Karpenter using the `serrors` package
> chore: Add structured errors

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
Bumps the upgrade source ref to v1.3.3 since the previous snapshot was garbage collected.
> ci: bump upgrade source ref to v1.3.3

- .github/workflows/e2e.yaml
Fixes #N/A 
- Add source to workflow dispatch call
- N/A
> ci: Add source workflow dispatch call

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- Add the source field from the matrixs change 
- N/A
> ci: Add source from E2E testing calls

- Makefile
Fixes #N/A 
- Import Karpenter packages before using the upstream testing packages
> test: Discover Karpenter imported Packages

- hack/code/instancetype_testdata_gen/main.go
- pkg/fake/zz_generated.describe_instance_types.go
Fixes #N/A 
Sort the instance types in the fake instance type offerings to avoid inconsistent ordering and unnecessary `make codegen` PRs
`make codegen`
> chore: Sort instance types in fake instance type offerings to avoid unneccessary PRs

- pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
Add tests for additional properties in kubelet configuration for Bottlerocket
N/A
> test: Add tests for additional properties in kubelet configuration for Bottlerocket

- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v1.4/upgrading/upgrade-guide.md
Fixes #N/A 
Off by one char fix
> docs: typo fix in 1.4.0 upgrade guide

- website/content/en/docs/concepts/disruption.md
- website/content/en/preview/concepts/disruption.md
- website/content/en/v1.0/concepts/disruption.md
- website/content/en/v1.2/concepts/disruption.md
- website/content/en/v1.3/concepts/disruption.md
- website/content/en/v1.4/concepts/disruption.md
Fixes #N/A 
Typo fix in the `Disruption` article.
> docs: typo fix in the `Disruption` article

- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
- pkg/apis/v1/nodepool_validation_cel_test.go
Fixes #N/A 
- Bump Karpenter in the go.mod
> chore: Bump Karpenter in the `go.mod`

- go.mod
- go.sum
Fixes #N/A 
- Bump Karpenter Version
> chore: Bump Karpenter `go.mod`

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Add source environment for E2E upgrade suite
> chore: Add environment E2E Upgrade tests

- .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Update all source E2E upgrade workflow 
- N/A
> ci: Update All source Upgrade workflow

- website/content/en/v1.2/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json
Fixed a typo on a dashboard pane that was bugging me
N/A
> chore(grafana): typo fix

- .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- Update the git ref on the upgrade suite
- N/A
> ci: Update the Git Ref for the upgrade suite

- kwok/Makefile
- kwok/README.md
Fixes #N/A 
Add README and install KWOK commands in Makefile
> docs: Add README and install KWOK commands in Makefile

- kwok/ec2/ec2.go
Fixes #N/A 
Add `kwok.x-k8s.io/node: fake` to the annotations block to fix lack of Kwok reconciliation
`make apply`
> fix: Add kwok fake node annotation

- website/content/en/docs/contributing/community-meetings.md
- website/content/en/preview/contributing/community-meetings.md
- website/content/en/v0.32/contributing/community-meetings.md
- website/content/en/v1.0/contributing/community-meetings.md
- website/content/en/v1.2/contributing/community-meetings.md
- website/content/en/v1.3/contributing/community-meetings.md
- website/content/en/v1.4/contributing/community-meetings.md
Fixes #N/A 
Updates the issue triage schedule to reflect the new monthly cadence.
> docs: update issue triage meeting schedule

- go.mod
- go.sum
Fixes #N/A 
Bumps in preparation of v1.5.x release.
make presubmit
> chore: bump for v1.5.x release

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
- Bump go mod for v1.1.x branch of Karpenter: https://github.com/kubernetes-sigs/karpenter/tree/release-v1.1.x
- Merge and E2E test runs
> chore: Update Karpenter in the go mod for release-v1.1.x 

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
- Bump go mod for v1.3.x branch of Karpenter: https://github.com/kubernetes-sigs/karpenter/tree/release-v1.3.x
- Merge and E2E test runs
> chore: Update Karpenter in the go mod for release-v1.3.x

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml
- charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml
- go.mod
- go.sum
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.sh_nodeclaims.yaml
- pkg/apis/crds/karpenter.sh_nodepools.yaml
Fixes #N/A 
- Bump go mod for v1.2.x branch of Karpenter: https://github.com/kubernetes-sigs/karpenter/tree/release-v1.2.x
- Merge and E2E test runs
> chore: Update Karpenter in the go mod for release-v1.2.x

- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v1.5/upgrading/upgrade-guide.md
Fixes #N/A 
Add the changelog to the upgrade guide for v1.5.0
> docs: Add changelog for v1.5.0

- go.mod
- go.sum
Fixes #N/A 
Pins upstream Karpenter to the [v1.1.3 release](https://github.com/kubernetes-sigs/karpenter/releases/tag/v1.1.3)
Same version as merged, just pinned
> deps: pin sigs.k8s.io/karpenter to v1.1.3

- go.mod
- go.sum
Fixes #N/A 
Pins upstream Karpenter to the [v1.2.3 release](https://github.com/kubernetes-sigs/karpenter/releases/tag/v1.1.3)
Same version as merged, just pinned
> deps: pin sigs.k8s.io/karpenter to v1.2.3

- go.mod
- go.sum
Fixes #N/A 
Pins upstream Karpenter to the [v1.3.3 release](https://github.com/kubernetes-sigs/karpenter/releases/tag/v1.1.3)
Same version as merged, just pinned
> deps: pin sigs.k8s.io/karpenter to v1.3.3

- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodepools.md
- website/content/en/v1.0/faq.md
- website/content/en/v1.0/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.0/reference/cloudformation.md
- website/content/en/v1.0/reference/threat-model.md
- website/content/en/v1.0/upgrading/v1-migration.md
- website/content/en/v1.3/faq.md
- website/content/en/v1.3/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.3/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.3/reference/cloudformation.md
- website/content/en/v1.3/reference/threat-model.md
Fixes #N/A 
Includes doc updates for the v1.0.10, and v1.3.4 release. There are no updates for the v1.1.6 and v1.2.4 releases since docs for those minor versions are no longer published.
n/a
> docs: updates for patch releases

- go.mod
- go.sum
Fixes #N/A 
- Update the Karpenter Dependency to pull a change to fix a flake for our NodeClaim E2E test
- Commit Diff: https://github.com/kubernetes-sigs/karpenter/compare/27776b571a4b...5ceb635163fa
- `make e2etests`
> chore: Update Karpenter Dependency

- go.mod
- go.sum
Fixes #N/A 
- Update the Karpenter deps
- Karpenter Diff: https://github.com/kubernetes-sigs/karpenter/compare/5ceb635163fa..1b5c30b3299f
- N/A
> core: Update Upstream Karpenter

- kwok/ec2/ec2.go
Fixes #N/A 
Update the KWOK logic to only delete nodes when they are not already deleted and also attempt to create nodes more than just one time by adding retry logic into the create node thread.
> chore: Fix double delete on kill node thread

- pkg/providers/instancetype/suite_test.go
- pkg/providers/instancetype/types.go
Fixes #N/A 
Cherry-pick https://github.com/aws/karpenter-provider-aws/commit/7ed2a35608dbe2466c49af1e61ae33e52228f6b2 to the release branch.
N/A
> fix: kube-reserved memory calculation should match AL2/AL2023 calculation

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v1.5/faq.md
- website/content/en/v1.5/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.5/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.5/reference/cloudformation.md
- website/content/en/v1.5/reference/threat-model.md
- website/content/en/v1.5/upgrading/upgrade-guide.md
- website/hugo.yaml
Fixes #N/A 
Update website for v1.5.2 release
> chore: Update website for v1.5.2 release

- go.mod
- go.sum
Fixes #N/A 
**Description** 
N/A
Will run integration tests as part of this PR
> chore: update upstream karpenter to latest

- go.mod
- go.sum
- website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Tests were run with the pseudo-tag already with the same upstream commit. 
> chore: update upstream karpenter to latest release

- go.mod
- go.sum
> chore: update to latest upstream commit

- go.mod
- go.sum
> chore: update karpenter to v1.5.3

- website/content/en/v1.5/faq.md
- website/content/en/v1.5/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.5/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.5/reference/cloudformation.md
- website/content/en/v1.5/reference/threat-model.md
- website/content/en/v1.5/upgrading/upgrade-guide.md
> docs: update 1.5.2 references to 1.5.3

- pkg/controllers/nodeclass/controller.go
> chore: handle resource not found during Patch

- website/content/en/docs/concepts/nodeclasses.md
- website/content/en/preview/concepts/nodeclasses.md
- website/content/en/v1.0/concepts/nodeclasses.md
- website/content/en/v1.4/concepts/nodeclasses.md
- website/content/en/v1.5/concepts/nodeclasses.md
- website/content/en/v1.6/concepts/nodeclasses.md
> docs: Update nodeclasses.md incorrect indentation in docs

- go.mod
Fixes #N/A 
Address CVE: https://github.com/advisories/GHSA-j5pm-7495-qmr3
make presubmit
> chore: bump go version to 1.24.6

- pkg/providers/instancetype/offering/offering.go
- pkg/providers/instancetype/suite_test.go
> cherry-pick: fix: mark expiring capacity blocks as unavailable (#8362)

- website/content/en/docs/tasks/odcrs.md
- website/content/en/preview/tasks/odcrs.md
- website/content/en/v1.6/tasks/odcrs.md
Fixes #N/A 
Clarifies Karpenter's behavior with open ODCRs.
N/A
> docs: clarify open ODCR behavior

- charts/karpenter-crd/Chart.yaml
- charts/karpenter/Chart.yaml
- charts/karpenter/README.md
- charts/karpenter/values.yaml
- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/docs/tasks/odcrs.md
- website/content/en/docs/upgrading/upgrade-guide.md
- website/content/en/preview/tasks/odcrs.md
- website/content/en/preview/upgrading/upgrade-guide.md
- website/content/en/v1.6/faq.md
- website/content/en/v1.6/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.6/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.6/reference/cloudformation.md
- website/content/en/v1.6/reference/settings.md
- website/content/en/v1.6/reference/threat-model.md
- website/content/en/v1.6/tasks/odcrs.md
- website/content/en/v1.6/upgrading/upgrade-guide.md
- website/hugo.yaml
Fixes #N/A 
Update docs for the latest patch. Key update includes the addition of `DisableDryRun` as a configuration option.
> docs: Update docs for latest 1.6.x patch

- go.mod
- go.sum
> chore: update sigs/karpenter

- .github/workflows/e2e-matrix.yaml
> ci: update the Git Ref for the upgrade suite (#8394)

- charts/karpenter/templates/deployment.yaml
Fixes https://github.com/aws/karpenter-provider-aws/issues/8422
> add env var for CPU_REQUESTS to helm chart

- charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml
- pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
Fixes #N/A 
https://github.com/aws/karpenter-provider-aws/actions/runs/17331439806/job/49209511547 shows the build failing. Reproduced locally and saw that these files were getting updated.
> chore: update kubebuilder version to fix build failures

- website/content/en/docs/faq.md
- website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/docs/getting-started/migrating-from-cas/_index.md
- website/content/en/docs/reference/cloudformation.md
- website/content/en/docs/reference/threat-model.md
- website/content/en/v1.7/faq.md
- website/content/en/v1.7/getting-started/getting-started-with-karpenter/_index.md
- website/content/en/v1.7/getting-started/migrating-from-cas/_index.md
- website/content/en/v1.7/reference/cloudformation.md
- website/content/en/v1.7/reference/threat-model.md
Fixes #N/A 
Updates refs of 1.7.0 to 1.7.1
N/A
> docs: update docs for 1.7.1 patch release

- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/install-prometheus/action.yaml
- .github/workflows/release.yaml
Fixes #N/A 
* bump helm from v3.12.3 to v3.18.6
* make presubmit
> chore: bump helm

- pkg/providers/instanceprofile/instanceprofile.go
- pkg/providers/instanceprofile/suite_test.go
Fixes #N/A 
- When validation calls were made to check the instance profile's existence before the cache entry expired, these calls would inadvertently reset the instance profile cache expiration time. As a result, if the underlying instance profile was deleted, the the instance profile provider would continue to use the cached data instead of creating a new instance profile as intended. This prevented proper instance profile recreation when needed
> chore: Fix instance profile idempotent Create

- .github/actions/e2e/install-karpenter/action.yaml
- .github/actions/e2e/install-prometheus/action.yaml
- .github/workflows/release.yaml
Fixes #N/A 
Bumps helm version
> chore: bump helm version
