.github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e-soak-trigger.yaml, test/hack/soak/get_clusters.go
Fixes #N/A 
- We are currently seeing failures on our E2E soak testing as the E2E tests are running against a build of karpenter that does not support all the feature that are being tested
- We should run the e2e tests of the commit the karpenter snapshot is built on to avoid test failures 
- N/A
=> ci: Adding `git_ref` of the karpenter snapshot for E2E each test

.github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
- Need to pass values in tags. Git_ref need to be defined
- N/A
=> ci: Add `git_ref` for E2E test runs on Head 

.github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
- fix `GIT_REF` on tagging OIDC provider 
- forked account 
=> ci: Fix `GIT_REF` on tagging OIDC

pkg/controllers/nodeclass/controller.go
Fixes #N/A 
This removes the Generation Predicate filter which drops events that don't change the spec. If a user changes the nodeclass hash, the controller won't be requeued until there's another event for this nodeclass, effectively stopping nodeclass drift until the controller is triggered again.
tested manually
=> fix: remove event filtering generation predicate for nodeclass controller

test/pkg/environment/common/expectations.go
Fixes #N/A 
I was making some tests, and noticed that changes Karpenter had been making were overwritten since the update logic effectively ignores patches on objects that have outdated resource versions.
make verify
=> test: add log warning for updating objects with outdated resource versions

pkg/cache/cache.go, pkg/providers/instancetype/instancetype.go
Fixes #5196, #5225
- Clearing out the cache for the instance types provider on expired items. 
- Save items based on the EC2NodeClass resolution instead of EC2Nodeclass UUID
**E2E  Integration Periodic Run** 
**Memory Utilization** 
**CPU Utilization** 
**E2E Integration with PR Run** 
**Memory Utilization** 
**CPU Utilization** 
- E2E integration was used comparing the memory usage  
=> perf: Reduce Memory Usage from the InstanceType Provider 

pkg/cache/cache.go, pkg/providers/instancetype/instancetype.go
- Clearing out the cache for the instance types provider on expired items. 
- Save items based on the EC2NodeClass resolution instead of EC2Nodeclass UUID
**E2E  Integration Periodic Run** 
**Memory Utilization** 
**CPU Utilization** 
**E2E Integration with PR Run** 
**Memory Utilization** 
**CPU Utilization** 
- E2E integration was used comparing the memory usage  
=> perf: Cherry-pick Reduction of Memory Usage from the InstanceType Provide into v0.32.x

.github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
- Disable Pod Identity for Karpenter on K8s 1.23. Pod Identity is not supported on K8s 1.23 https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html#pod-id-considerations 
- Forked account
=> ci: Disable Pod Identity for karpenter on K8s 1.23

website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Adding more about how budgets can change the parallelism in v0.34+
make website
=> docs: add more upgrade notes about disruption budgets

go.mod, go.sum
Fixes #N/A 
Bumps [kubernetes-sigs/karpenter](https://www.github.com/kubernetes-sigs/karpenter) to a pseudo-tag for the targeted v0.32.4 release. Changes to the GHA workflows make it difficult to test from the PR so the strategy is going to be to merge in this change, let the tests run, and if they're successful create a follow-up PR with the proper tag.
Will be tested by e2e suite post-merge.
=> deps: bump `kubernetes-sigs/karpenter`

go.mod, go.sum
Fixes #N/A 
Bumps `kubernetes-sigs/karpenter` to the latest release. This PR replaces the pseudo-tag with the proper tag.
Due to significant changes to the github workflows, changes were tested via a workflow dispatch to the previous commit on this branch where upstream was pinned via a pseudo tag. Link to the [test results](https://github.com/aws/karpenter-provider-aws/actions/runs/7256788775).
=> deps: bump kubernetes-sigs/karpenter to v0.32.4

website/static/_redirects
Fixes #N/A 
We haven't copied over redirects for newer versions so this adds redirects for the new versions of the docs as well as adding redirects for older versions of the docs going from the new paths in v0.32 to the old paths.
=> docs: Add additional redirects for new to old paths and new versions

website/content/en/docs/reference/cloudformation.md, website/content/en/preview/reference/cloudformation.md, website/content/en/v0.32/reference/cloudformation.md, website/content/en/v0.33/reference/cloudformation.md
Fixes #N/A 
fix incorrect resource tag in `AllowScopedResourceTagging`
If use `"aws:ResourceTag/karpenter.sh/cluster/${ClusterName}": "owned"`, the controller cannot add some tag to the node
N/A
=> docs: fix incorrect resource tag

go.mod, go.sum, test/pkg/environment/common/expectations.go, test/pkg/environment/common/setup.go, test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go
Fixes #N/A 
Updates upstream karpenter one more commit and adds in e2e tests for budgets for Drift and Expiration. Consolidation will be added as a followup. 
make presubmit && make e2etests
=> test: add disruption budget e2es

go.mod, go.sum, pkg/controllers/interruption/controller.go, pkg/controllers/nodeclaim/garbagecollection/controller.go
Fixes #N/A 
This change drops the NodePool and NodeClaim utils functions that were dropped by the main library in `kubernetes-sigs/karpenter` as part of #907
=> chore: Drop NodePool and NodeClaim utils functions

hack/code/vpc_limits_gen/main.go, hack/codegen.sh
Fixes #N/A 
This change updates the `codegen.sh` script to ignore updates based off of the `--ignore-matching-lines` regex argument for `git diff` instead of checking the `git stat` which will be much more fragile to change
`make codegen`
=> ci: Fix codegen diff check

website/content/en/docs/concepts/nodeclasses.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/v0.32/concepts/nodeclasses.md, website/content/en/v0.33/concepts/nodeclasses.md
Fixes #N/A 
This adds a clarifying statement about the `amiSelector` overriding the default amis selected-on by the `amiFamily` in the `spec.amiSelector` section of the docs
=> docs: Clarify amiSelector overriding default amis in amiFamily

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml
Fixes #N/A 
This updates the issue template to use [Github alert syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) for surfacing the important routing detail in markdown at the top of issues, but not to include this note in the rendered issue once it's created.
Issue creation will now look like this when someone goes through the issue creation form:
=> chore: Update issue templates to not include ticket routing in rendered issue

tools/karpenter-convert/README.md
Fixes #N/A
Description
The go install command was pointing to latest, which doesn't have the karpenter-convert tool.
How was this change tested?
tested the command manually
=> chore: update go install command

test/suites/expiration/suite_test.go
Fixes #N/A 
fixes a flake with expiration e2es where newly created nodes would get expired, causing the testing logic to wait for the wrong nodes to be NotFound.
make e2etests
=> test: update expiration e2e

website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Fix typo where `v0.33` should have been `v0.34` in the upgrade guide
=> docs: Fix typo in upgrade guide warning

test/cloudformation/iam_cloudformation.yaml
Fixes #N/A 
Previously, the `GithubActions` role did not have `iam:TagRole` permission. This meant that the CloudFormation deployment was not actually not able to tag the roles that it creates with `eksctl`
=> ci: Add `TagRole` permission to GithubActions policy

hack/toolchain.sh
Fixes #N/A 
go checksum mismatch error when running make toolchain command due to go install of cosign. This is the reference for the change https://docs.sigstore.dev/system_config/installation/#with-go-120
Ran make toolchain that succeeded.
=> Updating toolchain cosign install path

.github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e-matrix.yaml, .github/workflows/e2e.yaml, test/pkg/environment/aws/expectations.go, test/suites/localzone/suite_test.go
Fixes #4513 
In light of a recent regression (#5239) this PR adds support for end to end tests in local zones. Since local zones come with a number of caveats, rather than adapting the entire test suite to run in local zones, a new suite is added and will be run in it's own region with a local zone enabled. This test suite may be expanded in the future but for the time being it will at least guarantee that we can launch instances in local zones.
=> ci: E2E testing for local zones

hack/code/bandwidth_gen/main.go
Fixes #N/A 
This changes fixes `make codegen` when generating network bandwitdth for HPC instances
`make codegen`
=> ci: Fix `make codegen` for network bandwidth

.github/actions/e2e/install-karpenter/action.yaml, .github/actions/e2e/install-prometheus/action.yaml
Fixes #N/A 
-  For k8s 1.23, the E2E test relay on IRSA instead of pod identity. Therefore, the karpenter service account will need the karpenter role name annotated 
- Forked account 
=> ci: Add IRSA Annotation for k8s 1.23 Karpenter Deployment 

charts/karpenter/templates/configmap.yaml
Fixes #5448
Fix global tag parsing in v0.32.x
`make apply` with `aws.tags` set
=> fix: Fix global tag parsing for helm chart

test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go
Fixes #N/A 
Fixes an issue where our current SSM alias was pointing to an AMI (AL) that has been deprecated since December. This change updates the SSM alias to point it to AL2 instead.
=> ci: Update SSM parameter to use AL2 instead of AL

charts/karpenter/templates/clusterrole-core.yaml
Fixes #N/A 
This change removes an unneeded Create permission on nodes that is no longer needed by Karpenter since it has been allowing kubelet to create the nodes on behalf of the instance rather than Karpenter orchestrating the Node creation directly
=> chore: Remove create node permission from ClusterRole

charts/karpenter/values.yaml, website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md, website/content/en/preview/upgrading/upgrade-guide.md
Fixes #4947 
This effectively reverts #2199 which changed the `dnsPolicy` that was shipped with Karpenter to be `Default`. This did allow scenarios where customers wanted Karpenter to manage the dns service pod's node capacity, but caused more harm than good when it came to other scenarios where Karpenter needs access to in-cluster services (like in the case of service meshes).
=> docs: Update dnsPolicy to ClusterFirst away from Default

test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go, test/suites/integration/emptiness_test.go
Fixes #N/A 
This change adds testing for ensuring that fully blocking budgets (both with and without a schedule) will block particular disruption actions either all of the time or at specified times during the day as dictated by the schedule.
Note: Consolidation tests to come later when I add testing for consolidation budgets in a follow-on
=> test: Add E2E testing for fully blocking budgets with and without schedule

website/content/en/docs/_index.md, website/content/en/preview/_index.md, website/content/en/v0.32/_index.md, website/content/en/v0.33/_index.md
Fixes #5495
Fixes minor typo where "consolidastion" should be "consolidation" (there is currently an extra "s")
- [] Yes, PR includes docs updates 
- [] No
=> docs: issue-5495: typo "consolidastion"

website/content/en/v0.32/upgrading/v1beta1-migration.md
Fixes documentation issue in migration guide 
In step 16, `ROLE_NAME="KarpenterNodeRole-${ClusterName}"` resolves to `KarpenterNodeRole-` as `${ClusterName}` is not used, hence subsequent commands fail. Changed to `${CLUSTER_NAME}`
=> chore: Fixing variable name in migration guide

.github/workflows/e2e-matrix.yaml
Fixes #N/A 
- Bump E2E Upgrade test to include changes to IRSA for 1.23
- https://github.com/aws/karpenter-provider-aws/pull/5445
- N/A
=> ci: Bump E2E Upgrade tests to support 1.23 

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v0.32/concepts/disruption.md, website/content/en/v0.33/concepts/disruption.md
Fixes #N/A 
- Update Behavioral Fields to include the disruption field 
- Update docs to include CRD field path in reference to drift 
- N/A
=> docs: Update Drift fields include correct CRD path

cmd/controller/main.go, pkg/controllers/controllers.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/suite_test.go, pkg/fake/ec2api.go, pkg/fake/utils.go, pkg/providers/amifamily/resolver.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go, test/suites/integration/launch_template_test.go
Fixes #995 
Added a method to delete the launch templates on deletion of EC2NodeClass. Added tests for the same.
Deployed the changes on my local EKS cluster. Steps followed -
1. Install Karpenter
2. Created Nodepool that references a Nodeclass
3. Deployed sample applications
4. Removed sample applications
5. Removed the Nodeclass object
Performing the nodeclass object deletion will trigger a flow that deletes the launch templates.
=> Delete Launch templates on deletion of EC2NodeClass

website/content/en/docs/getting-started/getting-started-with-karpenter/prometheus-values.yaml, website/content/en/preview/getting-started/getting-started-with-karpenter/prometheus-values.yaml, website/content/en/v0.33/getting-started/getting-started-with-karpenter/prometheus-values.yaml
Fixes #N/A
It is recommended to set the installation namespace for Karpenter controllers to `kube-system`, but it can interfere with other endpoints located there. This fix specifies for Prometheus job to scrap only the karpenter endpoint.
=> fix: target down in Prometheus

pkg/controllers/controllers.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/suite_test.go
Fixes #N/A 
This change cleans up the calls to `NewController` in the NodeClass controller package to remove some additional indirection that was present from the alpha -> beta migration
=> chore: Clean NodeClass controller from unnecessary wrapping

cmd/controller/main.go, pkg/controllers/controllers.go, pkg/controllers/nodeclaim/garbagecollection/controller.go
Fixes #N/A 
This change updates the garbage collection controller to use the cloudprovider interface rather than the direct implementation
=> chore: Change garbage collection controller to use interface

pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
Fixes #5507
This PR adds support for [settings.kubernetes.credential-providers](https://bottlerocket.dev/en/os/1.18.x/api/settings/kubernetes/#credential-providers) for Bottlerocket.
By building a dev version of Karpenter with the changes of this PR, pushing the image to a private ECR repository and switched the image URL of Karpenter with the dev image on an existing EKS cluster which was already using Karpenter.
When Karpenter was deployed, it spun up a new Bottlerocket instance with the example configuration of [the original issue](https://github.com/aws/karpenter-provider-aws/issues/5507).
After going into the node with SSM I was able to confirm the configuration was updated as expected (which wasn't the case before).
**Does this change …
=> chrore: Add CredentialProvider to Bottlerocket settings

go.mod, go.sum, hack/toolchain.sh
Fixes #N/A 
- Bumping karpenter-core version to v0.32.6 to include these changes:
- https://github.com/kubernetes-sigs/karpenter/pull/959
- https://github.com/kubernetes-sigs/karpenter/pull/958
=> deps: Bump `karpenter-core` to `v0.32.6`

test/pkg/environment/common/expectations.go, test/suites/consolidation/suite_test.go, test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go, test/suites/integration/emptiness_test.go
=> Add testing for consolidation budgets e2e

.github/actions/e2e/install-karpenter/action.yaml, .github/actions/e2e/setup-cluster/action.yaml, .github/actions/install-deps/action.yaml, .github/workflows/ci-test.yaml, .github/workflows/e2e-matrix.yaml, .github/workflows/e2e-upgrade.yaml, .github/workflows/e2e-version-compatibility-trigger.yaml, .github/workflows/e2e.yaml, hack/toolchain.sh, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
Fixes #N/A 
Bumps the default k8s version to 1.29 for CI testing. This does **not** bump the supported version for the provider.
N/A
=> ci: bump k8s versions to 1.29

pkg/providers/launchtemplate/launchtemplate.go
Fixes #5535
If we delete EC2NodeClass and there is a cache eviction later, we see errors like these -
`{"level":"ERROR","time":"2024-01-25T05:33:52.210Z","logger":"controller","message":"failed to delete launch template, InvalidLaunchTemplateId.NotFound: The specified launch template, with template ID lt-019c5be5798f24ca7, does not exist.\n\tstatus code: 400, request id: 86bff5c8-9bc6-485a-a5a8-1619d6c81283","commit":"7cdc79a-dirty","launch-template":"karpenter.k8s.aws/2686062690276844038"}`
The change in the PR handles this case by instead printing a debug log that indicates that the LT is already deleted.
By submitting this pull request, I confirm that my contribution is made under …
=> Cache eviction should not throw error if the LT is already deleted

.github/actions/e2e/cleanup/action.yaml, .github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
Bumps eksctl to a version which supports EKS 1.29.
N/A
=> ci: bump eksctl version for EKS 1.29

pkg/controllers/nodeclaim/garbagecollection/suite_test.go, pkg/providers/instance/instance.go, pkg/providers/instance/suite_test.go, test/suites/nodeclaim/garbage_collection_test.go
Fixes #N/A 
This change scopes the call to list out instance to EC2NodeClass-owned instances
=> chore: Scope list call with EC2NodeClass tag

website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/preview/reference/cloudformation.md
Fixes #N/A 
This change adds scoping to launch template access during `RunInstances` and `CreateFleet`. This ensures that Karpenter is only able to access launch templates that were created by Karpenter (ones that have the `kubernetes.io/cluster/${ClusterName}` and `karpenter.sh/nodepool`
=> docs: Add scoping for controller launch template access

go.mod, go.sum, hack/toolchain.sh
Fixes #N/A 
Bumping kuberntes-sigs/karpenter version to v0.33.2 to include these changes:
- https://github.com/kubernetes-sigs/karpenter/pull/959
- https://github.com/kubernetes-sigs/karpenter/pull/958
workflow-dispatch after the PR is merged
=> deps: Bump kuberntes-sigs/karpenter to v0.33.2

test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go
Fixes #N/A 
- Include changes of this PR https://github.com/aws/karpenter-provider-aws/pull/5460
- This should fix drift and expiration test for `release-v0.33.2` branch
- This will prevent future failure for the release process
- N/A
=> test: Remove deprecated SSM alias from E2E tests

hack/release/common.sh
Fixes #N/A 
Removing the private replicas for helm chart due to AMI permission failure
=> ci: Remove the private replica for helm chart

website/content/en/preview/upgrading/compatibility.md, website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Adds a warning to the upgrade docs for Karpenter v0.34.x about the Ubuntu AMI family. More details can be found in #5572.
N/A
=> docs: add warning for Ubuntu AMI family on k8s 1.29+

test/suites/drift/suite_test.go
Fixes #N/A 
Pods fail to schedule to the old static AMI used to trigger drift in the affected test. They failed with the following error:
```
time=2024-01-31T01:19:06Z type=Warning reason=FailedCreatePodSandBox from=kubelet message=Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "e7834551c5c56e7eeb7af397b425c5fa403867fd9d40827fcf903db48183c6d5" network for pod "spikealder-40-pcqkph2ugu-74bbf85989-rhdvd": networkPlugin cni failed to set up pod "spikealder-40-pcqkph2ugu-74bbf85989-rhdvd_default" network: unsupported CNI result version "1.0.0"
```
Triggering off of a newer AMI for 1.29+ resolves this error. The original AMI is still used for previous versions since we still run these tests in our compatibility matrix for k8s …
=> test: update old static AMI for k8s 1.29+ for drift

go.mod, go.sum, test/pkg/debug/node.go
Fixes #N/A 
This change updates `kubernetes-sigs/karpenter` package to the latest
=> chore: Bump kubernetes-sigs/karpenter to latest version

go.mod, go.sum, test/pkg/environment/aws/expectations.go, test/suites/integration/scheduling_test.go
Fixes #N/A 
This PR adds some minimal end-to-end tests for init container resource computation in light of this upstream PR: https://github.com/kubernetes-sigs/karpenter/pull/569.
`/karpenter snapshot` + local `make e2etests`
=> test: init container e2e tests

hack/docgen.sh, pkg/providers/version/version.go
Fixes #N/A 
Bumps the supported kubernetes version for v0.34.x to 1.29. Additionally, updates the docgen to include all supported versions (1.23 - 1.29). 
N/A
=> chore: bump k8s support to 1.29 for v0.34.x

website/content/en/docs/concepts/nodeclasses.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/v0.32/concepts/nodeclasses.md, website/content/en/v0.33/concepts/nodeclasses.md
Fixes #N/A 
This change adds documentation to the `karpenter.k8s.aws/ec2nodeclass` tag always being specified when Karpenter launches instances, volumes, launch templates, ENIs, etc.
Validated with resources in the EC2 console
=> docs: Add EC2NodeClass tag to pre-defined tags

test/pkg/environment/common/expectations.go, test/suites/consolidation/suite_test.go, test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go
Fixes #N/A 
Adds tests to test concurrent disruption replacements
make e2etests
=> test: add budgets replacement tests

test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go
Fixes #N/A 
Fix some tests with disruption that had unnecessary cordon logic causing replacement nodes when we wanted delete actions only.
TEST_SUITE="Expiration" make e2etests
TEST_SUITE="Drift" make e2etests
=> test: fix drift/expiration test flakes

hack/release/common.sh
Fixes #N/A 
- Adding `-y` to cosign our karpenter images
- N/A 
=> chore: Adding `-y` to cosign prompt to allow signing images

charts/karpenter/README.md, hack/docs/compatibility-karpenter.yaml, website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md, website/content/en/docs/reference/instance-types.md, website/content/en/docs/reference/metrics.md, website/content/en/docs/upgrading/compatibility.md, website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md, website/content/en/preview/reference/instance-types.md, website/content/en/preview/reference/metrics.md, website/content/en/preview/upgrading/compatibility.md, website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.34/reference/instance-types.md, website/content/en/v0.34/reference/metrics.md, website/content/en/v0.34/upgrading/compatibility.md, website/hugo.yaml
Fixes #N/A 
- Update v0.34 docs using `make docgen`
- N/A
=> docs: Update to v0.34 using `docgen`

website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md, website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Bumps the minimum version of eksctl called out in the v0.34+ docs to v0.169.0 for EKS 1.29 support: https://github.com/eksctl-io/eksctl/releases/tag/v0.169.0
N/A
=> docs: bump min eksctl version to v0.169.0

charts/karpenter/templates/servicemonitor.yaml
Fixes #N/A 
The indentation for `serviceMonitor` endpoints was set too high, causing bad yaml to be rendered
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: karpenter
namespace: foo
spec:
namespaceSelector:
matchNames:
- foo
selector:
matchLabels:
bar
endpoints:
- port: http-metrics
path: /metrics
- path: /metrics
port: webhook-metrics
```
=> fix: Reduce indentation for servicemonitor endpoints

hack/toolchain.sh, pkg/cloudprovider/cloudprovider.go
Fixes #5613
This fixes an issue where a user has deployed a NodeClaim to their cluster with a Node and a NodeClaim that has entered a terminating state. This ensures that we don't try to retrieve the parent NodePool information for the Node when we are getting the node from the CloudProvider.
`make apply` and validate rollback scenario
=> fix: Fix retrieving NodePool when rolling back to v0.31.x

pkg/providers/instancetype/instancetype.go
Fixes #5578 
When a AWSNodeTemplate and EC2NodeClass are contain identical values in the configurations, Karpenter would treat the set of instance types as the same even if they have different requirements. This is a problem as the v1beta1 well-known labels and v1alpha5 well-known labels have a one label difference in that being karpenter.k8s.aws/instance-pods. So if the cached instance types were from a AWSNodeTemplate would have karpenter.k8s.aws/instance-pods in the requirement set for its list of instancetypes, which will result in a Compatibility check with NodeClaims invalid for all the instancetypes. This will prevent Karpenter from launching any nodes. 
By submitting this pull …
=> fix: Cache Instance Types for both AWSNodeTemplate and EC2NodeClass

pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1beta1/ec2nodeclass.go, pkg/apis/v1beta1/ec2nodeclass_validation_cel_test.go, pkg/apis/v1beta1/ec2nodeclass_validation_webhook_test.go, pkg/apis/v1beta1/labels.go, pkg/controllers/nodeclaim/tagging/controller.go, pkg/controllers/nodeclaim/tagging/suite_test.go, test/suites/integration/validation_test.go
Fixes #N/A 
This change adds additional restricted tag keys (`karpenter.k8s.aws/ec2nodeclass` and `karpenter.sh/nodeclaim`) for values that are fully managed by Karpenter
=> chore: Add additional restricted tag keys

.github/workflows/e2e-matrix-trigger.yaml, .github/workflows/e2e-matrix.yaml
Fixes #N/A 
- adding `contents` permission to E2E testing
- N/A
=> ci: Adding `contents` permission to E2E testing for `release-v0.31.x`

test/suites/drift/suite_test.go, test/suites/expiration/expiration_test.go, test/suites/integration/scheduling_test.go
Fixes #N/A 
- Cherrypicking E2E fixes
- https://github.com/aws/karpenter-provider-aws/pull/5173
- https://github.com/aws/karpenter-provider-aws/pull/5460
- N/A
=> test: Fix E2E test for `release-v0.31.x`

test/cloudformation/grafana_cloudformation.yaml
Fixes #N/A 
This change rotates the X509 certificate that is used to establish a self-signed certificate connection with the Grafana instance and the IDP
=> ci: Update IDP certificate for grafana

pkg/cloudprovider/cloudprovider.go
Fixes #5656
This updates our error that we send back to users when EC2NodeClasses that are in a terminating state that we are treating as NotFound
`make apply`
=> chore: Improve error message for deleting EC2NodeClass

website/content/en/docs/concepts/nodeclasses.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/v0.32/concepts/nodeclasses.md, website/content/en/v0.33/concepts/nodeclasses.md, website/content/en/v0.34/concepts/nodeclasses.md
Fixes #N/A 
This updates the docs to clarify that only one of `spec.role` and `spec.instanceProfile` is needed since the previous wording might have been confusing with respect to this.
=> docs: Remove the word "necessary" from optional fields

test/pkg/environment/common/expectations.go, test/suites/consolidation/suite_test.go, test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go
Fixes #N/A 
Ensure that nodes don't leak into subsequent tests when validating replacement logic for budgets
=> test: Add fix for nodes leaking into subsequent tests for budgets

pkg/errors/errors.go
Fixes #N/A 
If we delete EC2NodeClass and there is a cache eviction later, we see errors like these -
`{"level":"ERROR","time":"2024-01-25T05:33:52.210Z","logger":"controller","message":"failed to delete launch template, InvalidLaunchTemplateId.NotFound: The specified launch template, with template ID lt-019c5be5798f24ca7, does not exist.\n\tstatus code: 400, request id: 86bff5c8-9bc6-485a-a5a8-1619d6c81283","commit":"7cdc79a-dirty","launch-template":"karpenter.k8s.aws/2686062690276844038"}`
The fix that was added earlier to handle this scenario was checking if `InvalidLaunchTemplateName.NotFoundException` has occurred when it should have been checking for `InvalidLaunchTemplateId.NotFound`.
**Does this change impact …
=> Fix for InvalidLaunchTemplateId.NotFound error

pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go, website/content/en/preview/concepts/nodeclasses.md
Fixes #N/A 
Updates network interface generation to respect `AssociatePublicIPAddress` for EFA interfaces. This originally wasn't rejected due to a potential footgun: setting this value to true when launching instances with multiple EFAs will result in launch failure. The following error will be reported:
```
{"level":"ERROR","time":"2024-02-15T05:41:31.594Z","logger":"controller","message":"Reconciler error","commit":"95f42f1-dirty","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"efa-tt6zp"},"namespace":"","name":"efa-tt6zp","reconcileID":"45b919ce-8b3a-480f-b0cd-a10eec71ff91","error":"launching nodeclaim, creating instance, with fleet error(s), InvalidParameterCombination: The associatePublicIPAddress …
```
=> chore: respect AssociatePublicIPAddress with EFA

hack/toolchain.sh
Fixes #N/A 
This pins to the latest version of the `v1.25.x` version of etcd and the apiserver to fix some CEL problems that we were seeing in the 1.25 version and not in newer versions. This pins in the same way that `kubernetes-sigs/karpenter` pins
=> ci: Pin to the latest patch version of 1.25.x in toolchain

charts/karpenter/README.md, hack/docs/metrics_gen_docs.go, website/content/en/preview/reference/metrics.md
Fixes #N/A 
Fix failures in docgen due to not discovering `stateSubsystem`
=> docs: Fix docgen

hack/release/common.sh, hack/toolchain.sh
Fixes #N/A 
This PR signs the released Helm charts with `cosign`. I've not updated the docs as it's probably best to do a release with this code and then check it's functioning correctly.
```bash
cosign verify --certificate-oidc-issuer=https://token.actions.githubusercontent.com --certificate-identity-regexp='https://github\.com/aws/karpenter-provider-aws/\.github/workflows/release\.yaml@.+' --certificate-github-workflow-repository=aws/karpenter-provider-aws --certificate-github-workflow-name=Release "public.ecr.aws/karpenter/karpenter:${KARPENTER_VERSION}"
```
This PR has been split out of https://github.com/aws/karpenter-provider-aws/pull/5561.
Ad-hoc.
By submitting this pull request, I confirm that my …
=> feat(chart): Added cosign signature

hack/release/common.sh, hack/toolchain.sh
Related to #5306
This PR adds the ability to add _Artifact Hub_ metadata to the chart OCI registry once the organisation and repos have been created (see #5306).
This PR has been split out of #5561.
Ad-hoc (I use this pattern for all of my Helm charts).
=> chore(chart): Added Artifact Hub config support

.github/actions/e2e/install-karpenter/action.yaml, hack/release/common.sh
Fixes #N/A 
Fix `helm diff` command in our E2E test jobs
Fix the call to `crane` to make sure that it is pulling the digest from the correct repo
=> ci: Fix `helm diff` and `crane digest` command

.github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e.yaml
Fixes #N/A 
This change updates our testing CI so that disabling cleanup also disables CFN rollback
=> test: Ignore CFN cleanup when flag is set

go.mod, go.sum
Fixes #N/A 
Update `go.mod to` latest version of k8s/karpenter-provider-aws i.e `v0.34.1`
N/A
=> chore: Update go.mod to latest version of kubernetes-sigs/karpenter

cmd/controller/main.go, go.mod, go.sum, pkg/cloudprovider/suite_test.go, pkg/providers/instancetype/suite_test.go, pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
This change bumps the v0.32.x release version to use the latest `v0.32.x` patch update
=> chore: Bump v0.32.x to use latest patch

website/content/en/docs/getting-started/getting-started-with-karpenter/prometheus-values.yaml, website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh, website/content/en/preview/getting-started/getting-started-with-karpenter/prometheus-values.yaml, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh, website/content/en/v0.32/getting-started/getting-started-with-karpenter/prometheus-values.yaml, website/content/en/v0.32/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh, website/content/en/v0.33/getting-started/getting-started-with-karpenter/prometheus-values.yaml, website/content/en/v0.33/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh, website/content/en/v0.34/getting-started/getting-started-with-karpenter/prometheus-values.yaml, website/content/en/v0.34/getting-started/getting-started-with-karpenter/scripts/step09-add-prometheus-grafana.sh
Fixes #N/A
The Monitoring with Grafana part of the getting started guide for Karpenter hardcodes the Karpenter namespace to "kube-system" in the prometheus scrape targets configuration.  This is a configurable option in the walk-through. This PR templates the prometheus values file.
=> docs: Template prometheus values based on Karpenter namespace

.github/workflows/dryrun-gen-pr.yaml, .github/workflows/dryrun-gen.yaml, .github/workflows/snapshot-pr.yaml, .github/workflows/snapshot.yaml
Fixes #N/A 
Dry-run the `make prepare-website` generation as part of merge into main
=> ci: Dry run `prepare-website` on merge to main and presubmit

Makefile
Fixes #N/A 
Defaults KOCACHE to `~/.ko` to speed up image builds.
`make image`
=> ci: use KOCACHE for image build

.ko.yaml, Makefile, charts/karpenter/README.md, hack/docs/compatibility-karpenter.yaml, hack/release/common.sh, hack/release/prepare-website.sh, hack/release/release-crd.sh, hack/release/release.sh, hack/release/snapshot.sh, hack/release/stable-pr.sh, tools/kompat/pkg/kompat/kompat.go, website/content/en/preview/faq.md, website/content/en/preview/reference/settings.md, website/content/en/preview/reference/threat-model.md, website/content/en/preview/troubleshooting.md, website/content/en/preview/upgrading/compatibility.md, website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
This PR changes the OCI tag pattern to be the SemVer version without the `v` prefix.
=> feat: Changed OCI tag format

website/package-lock.json, website/package.json
Reverts aws/karpenter-provider-aws#5729
Fixes #5734
Something in the latest `hugo-extended` package broke how scripts are rendered. We should revert this so that the website starts rendering normally again, but should track down what needs to be changed here before we re-upgrade back to the version that contains this break.
=> Revert "chore(deps-dev): bump the website-deps group in /website with 1 update"

website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md, website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.33/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
While setting up a private cluster if a VPC endpoint for `com.amazonaws.<region>.eks` is not added then we see this error -
`"message":"unable to detect the cluster endpoint, failed to resolve cluster endpoint, RequestError: send request failed\ncaused by: Get \"https://eks.<region>.amazonaws.com/clusters/<clusterName>\": dial tcp 54.188.62.0:443: i/o timeout"`
Docs have been updated with this information, so that while setting up a private cluster, if this endpoint is added then Karpenter will be able to discover the endpoint.
=> docs: Add VPC endpoint for eks while setting up a private cluster

.github/workflows/snapshot-pr.yaml
Fixes #N/A 
This fixes the snapshot command install path that is printed back to users when running `/karpenter snapshot`
=> ci: Fix snapshot command path

website/content/en/v0.32/upgrading/v1beta1-controller-policy.json
Fixes #N/A 
In the IAM policy for the v0.32 upgrade guide, one ARN is hard-coded to use `aws` as the partition instead of an environment variable, causing the upgrade procedure to fail in other partitions.
Tested following the upgrade instructions in AWS GovCloud.
=> docs: Fix hard-coded AWS partition in IAM policy

website/content/en/preview/concepts/nodeclasses.md
Fixes #N/A 
Doc updates for the AL2023 AMI family.
=> docs: AL2023 AMI Family docs

website/content/en/preview/tasks/amitasks.md, website/content/en/v0.34/tasks/amitasks.md
Updated the [Managing AMIs](https://karpenter.sh/v0.34/tasks/amitasks/) docs after a formal review.
=> Enhance AMI task docs after review

pkg/providers/instancetype/instancetype.go
=> fix: add InstanceStorePolicy to instance list cache

.github/workflows/e2e.yaml
Fixes #N/A 
Skips the cluster cleanup process if the kubelet is not ready on one of the MNG nodes. This is to help diagnose the following failure: https://github.com/aws/karpenter-provider-aws/actions/runs/8032556917/job/21942085645. 
=> ci: don't remove cluster with unhealthy mng

test/hack/resource/clean/main.go, test/hack/resource/go.mod, test/hack/resource/pkg/resourcetypes/eni.go, test/hack/resource/pkg/resourcetypes/instance.go, test/hack/resource/pkg/resourcetypes/instanceprofile.go, test/hack/resource/pkg/resourcetypes/launchtemplate.go, test/hack/resource/pkg/resourcetypes/oidc.go, test/hack/resource/pkg/resourcetypes/resourcetypes.go, test/hack/resource/pkg/resourcetypes/securitygroup.go, test/hack/resource/pkg/resourcetypes/stack.go, test/hack/resource/pkg/resourcetypes/vpc_endpoint.go, test/hack/soak/get_clusters.go
Fixes #N/A 
Adds an exclusion list to our cleanup script to keep clusters around for investigation purposes. Motivated by ongoing SQS failures in our soak tests.
N/A
=> ci: add cluster exclusion list to cleanup

website/package-lock.json, website/package.json
Fixes #N/A 
- Revet Hugo Version bump 
- https://github.com/aws/karpenter-provider-aws/pull/5774
- N/A
=> docs: Revert PR #5774 (Hugo version bump)

website/content/en/docs/concepts/nodepools.md, website/content/en/preview/concepts/nodepools.md, website/content/en/v0.32/concepts/nodepools.md, website/content/en/v0.33/concepts/nodepools.md, website/content/en/v0.34/concepts/nodepools.md, website/content/en/v0.35/concepts/nodepools.md
Fixes #N/A 
Fix weighted nodepools link in all docs versions
=> docs: Fix weighted nodepools link in all docs versions

website/content/en/docs/concepts/nodepools.md, website/content/en/preview/concepts/nodepools.md, website/content/en/v0.32/concepts/nodepools.md, website/content/en/v0.33/concepts/nodepools.md, website/content/en/v0.34/concepts/nodepools.md, website/content/en/v0.35/concepts/nodepools.md
Fixes #5676 
Adds a note about how kubeReserved defaults effect ephemeral storage calculation
N/A
=> docs: add kubeReserved default note

pkg/providers/pricing/pricing.go
code to look similar
- Improve pricing mutex locks before calling apis for spot and onDemand
- Previous code could potentially call AWS multiple times in parallel, the mutex now protects that only one thread talks to AWS at same time
- Refactor spot code to look like onDemand code
=> fix: Move mutex in pricing before AWS api calls, refactor spot and onDemand

go.mod, go.sum, pkg/controllers/interruption/controller.go, pkg/providers/instancetype/suite_test.go
Fixes #N/A 
- Bump Karpenter version to include 
- https://github.com/kubernetes-sigs/karpenter/pull/1016
=> chore: Bump Karpenter version to include Drift hash Versioning for `NodePool`

go.mod, go.sum
Fixes #N/A 
Updates the go.mod to point to the updated release-v0.34.x branch.
make verify
=> chore: update upstream karpenter to release-v0.34.x

website/content/en/docs/concepts/scheduling.md, website/content/en/preview/concepts/scheduling.md, website/content/en/v0.32/concepts/scheduling.md, website/content/en/v0.33/concepts/scheduling.md, website/content/en/v0.34/concepts/scheduling.md, website/content/en/v0.35/concepts/scheduling.md
Fixes #N/A 
This change is to fix the quote mistake in topology zone value list in docs.
Different zone values need to be separate strings, thus should be quoted separately in the list.
This only includes the docs change. 
- [] No
=> docs: fix topology zone list value quote issue in docs

pkg/providers/instancetype/instancetype.go
Fixes #N/A 
- Since volumeSize is not hashed included https://github.com/aws/karpenter-provider-aws/issues/5447. Karpenter will hash the volumeSize as a string
=> chore: Include `volumeSize`, `kubeReserved`, and `systemReserved` in Instancetype hash calculations

pkg/providers/instancetype/instancetype.go
Fixes #N/A 
- Since volumeSize hash is not included in the instancetype cache key https://github.com/aws/karpenter-provider-aws/issues/5447. Karpenter will hash the volumeSize as a string. 
- `kubeReserved`, and `systemReserved` hash are also not included in the instancetype cache key https://github.com/kubernetes-sigs/karpenter/issues/1080. Karpenter will hash them as a string. 
- N/A
=> chore(cherry-pick to v0.33.x): Include volumeSize, kubeReserved, and systemReserved in Instancetype hash calculations

charts/karpenter/templates/deployment.yaml, charts/karpenter/values.yaml
Fixes #N/A 
This change corrects the `runAsUser` and `runAsGroup` to run using the `nonroot` user. This was previously mapping to another non-root, random user, but [wasn't within the valid set of UIDs on older linux kernels (65535)](https://www.baeldung.com/linux/user-ids-reserved-values#:~:text=integer.%20After%20the-,Linux%20kernel%20version%202.4,-%2C%20the%20upper%20limit). Additionally, distroless and scratch images use a standard "nonroot" user (65532) by default and give permission to certain filepaths on the image. Karpenter uses the `public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base` image by default, [which assigns file permission to user `65532`](https://github.com/aws/eks-distro-build-tooling/blob/main/eks-distro-base/Dockerfile.minimal-base#L57) …
=> chore: Correct security context to use `nonroot` user

go.mod, go.sum, test/pkg/environment/common/expectations.go, test/pkg/environment/common/setup.go, test/suites/chaos/suite_test.go, test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go, test/suites/integration/emptiness_test.go, test/suites/integration/storage_test.go
Fixes #N/A 
This change converts all `client.MergeFrom` calls in the Karpenter E2E testing to `client.StrategicMergeFrom`. This [doc](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#use-a-strategic-merge-patch-to-update-a-deployment) in the upstream Kubernetes documentation details how using this patch strategy improves consistency of calls for lists. 
E2E tests were failing (like [here](https://github.com/aws/karpenter-provider-aws/actions/runs/8223237781/job/22485698904)) 
```
[FAILED] Expected success, but got an error:
<*errors.StatusError | 0xc00182c6e0>: 
Node "ip-192-168-1-200.us-east-2.compute.internal" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new …
```
=> test: Fix flake in patching out finalizers

.github/actions/install-deps/action.yaml, go.mod, test/hack/resource/go.mod, test/hack/soak/go.mod, tools/allocatable-diff/go.mod, tools/kompat/go.mod, website/go.mod
Fixes #N/A 
Bumps go to the latest release: [release notes](https://tip.golang.org/doc/go1.22)
Justification for pinning to the patch version: https://github.com/golang/go/issues/62278
=> deps: bump go version to 1.22

test/pkg/environment/common/expectations.go, test/suites/drift/suite_test.go
Fixes #N/A 
- Add E2E tests for NodePool Hash Versioning
- https://github.com/kubernetes-sigs/karpenter/pull/1016
- N/A
=> test: Add E2E tests for NodePools Hash Version

tools/kompat/pkg/kompat/kompat.go, website/content/en/docs/upgrading/compatibility.md, website/content/en/preview/upgrading/compatibility.md, website/content/en/v0.32/upgrading/compatibility.md, website/content/en/v0.33/upgrading/compatibility.md, website/content/en/v0.34/upgrading/compatibility.md, website/content/en/v0.35/upgrading/compatibility.md
Fixes #5841  
Change semantic version comparison for Karpenter/Kubernetes in the Compatibility Matrix.
- [] No
=> docs: better compatibility matrix

pkg/cache/cache.go, pkg/cache/unavailableofferings.go, pkg/providers/instancetype/instancetype.go
Fixes #N/A 
This change fixes a bug that causes us to keep ICEd offerings in the cache for beyond their unavailability cache interval (up to 8m using the current code [3m unavailable offering expiry + 5m instance type expiry]). The current code handles the addition of unavailable offerings to the cache, but it doesn't handle the eviction from the cache. This update ensures that cache eviction triggers the sequence number to increase. 
This also drops the cleanup interval for the cache so that we react quicker to this eviction.
```
{"level":"INFO","time":"2024-03-12T07:02:54.767Z","logger":"controller.interruption","message":"initiating delete from interruption message","commit":"1d7f91c-dirty","queue":"joinnis-karpenter-demo","messageKind":"SpotInterruptionKind","nodeclaim" …
```
=> fix: Fix InstanceType cache invalidation on ICE eviction 

website/content/en/docs/upgrading/compatibility.md, website/content/en/preview/upgrading/compatibility.md, website/content/en/v0.34/upgrading/compatibility.md, website/content/en/v0.35/upgrading/compatibility.md
Fixes #N/A 
Removes the warning for the Ubuntu AMI family and EKS 1.29. Ubuntu has since made 20.04 available on EKS 1.29 so users can upgrade safely from 1.28. 
N/A
=> docs: drop 1.29 Ubuntu warning

go.mod, go.sum
Fixes #N/A 
This updates `kubernetes-sigs/karpenter` to be updated to the latest HEAD
=> chore: Bump karpenter to latest HEAD

charts/karpenter-crd/artifacthub-repo.yaml, charts/karpenter/artifacthub-repo.yaml
Fixes #N/A 
This PR adds Artifact Hub metadata to the Helm charts which will flag them as being verified and will support removing the invalid releases from being processed (this could/should also be handled manually or with a cleanup rule?). It also adds the placeholder to set the email address of the person claiming the repository for AWS (see #5306).
=> chore: Added ArtifactHub Helm metadata

tools/kompat/pkg/kompat/kompat.go
Fixes #5841  
Fix kompat tool to generate correct semantic versioning for Karpenter/Kubernetes compatibility matrix
=> docs: fix kompat tools to support semantic versioning correctly

hack/release/common.sh
Fixes #N/A 
This change ensures that we only upload ArtifactHub metadata to the release ECR repo. The snapshot repo has tag immutability enabled and it really isn't needed there anyway.
=> fix: only upload artifacthub metadata to release repo

.github/workflows/e2e.yaml, test/hack/resource/clean/main.go, test/hack/soak/get_clusters.go
Fixes #N/A 
Reverts the changes for the MNG creation failure investigation and removes the soak cluster from the cleanup cluster exclusion list.
Explicitly reverts the following PR:
- https://github.com/aws/karpenter-provider-aws/pull/5746
N/A
=> ci: revert MNG and SQS diagnostic changes

website/content/en/docs/concepts/nodepools.md, website/content/en/preview/concepts/nodepools.md, website/content/en/v0.35/concepts/nodepools.md
Fixes #N/A 
Add minor edits to documentation around `minValues` including alpha field disclosure
=> docs: Add minor edits for minValues with formatting

test/hack/resource/clean/main.go, test/hack/resource/pkg/resourcetypes/instance.go, test/hack/resource/pkg/resourcetypes/securitygroup.go, test/hack/resource/pkg/resourcetypes/stack.go
Fixes #N/A 
- We need to some investigation on flakey windows test failures, so we will leave the cluster around.
- N/A
=> ci: Exclude `soak-periodic-2213793` Cluster from cleanup for Windows investigation

website/content/en/docs/concepts/nodeclasses.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/v0.32/concepts/nodeclasses.md, website/content/en/v0.33/concepts/nodeclasses.md, website/content/en/v0.34/concepts/nodeclasses.md, website/content/en/v0.35/concepts/nodeclasses.md
Fixes #N/A 
Adds a note under `amiSelectorTerms` which calls out that the only requirement Karpenter can detect is architecture. Gives a specific example for accelerated GPU AMIs since Karpenter can differentiate and select the right AMI when no `amiSelectorTerms` are provided.
N/A
=> docs: add AMI requirement note

pkg/providers/amifamily/bootstrap/bootstrap.go, pkg/providers/amifamily/resolver.go, pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Cherry pick of https://github.com/aws/karpenter-provider-aws/pull/5882
=> cherrypick (v0.33): fix: include capacity type and resource.Quantity in launch template cache key

pkg/providers/amifamily/bootstrap/bootstrap.go, pkg/providers/amifamily/resolver.go, pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Cherry pick of https://github.com/aws/karpenter-provider-aws/pull/5882
=> cherrypick(v0.35): fix: include capacity type and resource.Quantity in launch template cache key

pkg/providers/amifamily/bootstrap/bootstrap.go, pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Cherry pick of https://github.com/aws/karpenter-provider-aws/pull/5882. Drops the capacity type caching since https://github.com/aws/karpenter-provider-aws/pull/4911 isn't included in v0.32.x.
=> cherrypick(v0.32): fix: include resource.Quantity in launch template cache key

go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1beta1/ec2nodeclass.go, pkg/apis/v1beta1/labels.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/drift.go, pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/suite_test.go, test/pkg/environment/common/expectations.go, test/suites/drift/suite_test.go
Fixes #N/A 
- Cherrypicked PRs:
- https://github.com/aws/karpenter-provider-aws/pull/5770
- https://github.com/aws/karpenter-provider-aws/pull/5803
=> cherrypick(v0.35): feat: Add Versioned for EC2NodeClass Hash to Prevent Drift on EC2NodeClass CRD Upgrade

go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1beta1/ec2nodeclass.go, pkg/apis/v1beta1/labels.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/drift.go, pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/suite_test.go, test/pkg/environment/common/expectations.go, test/suites/drift/suite_test.go
Fixes #N/A 
- Cherrypicked PRs:
- https://github.com/aws/karpenter-provider-aws/pull/5770
- https://github.com/aws/karpenter-provider-aws/pull/5803
=> cherrypick(v0.34): feat: Add Versioned for EC2NodeClass Hash to Prevent Drift on EC2NodeClass CRD Upgrade

go.mod, go.sum, pkg/apis/v1beta1/ec2nodeclass.go, pkg/apis/v1beta1/labels.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/drift.go, pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/suite_test.go, test/pkg/environment/common/expectations.go, test/suites/drift/suite_test.go
Fixes #N/A 
- Cherrypicked PRs:
- https://github.com/aws/karpenter-provider-aws/pull/5770
- https://github.com/aws/karpenter-provider-aws/pull/5803
=> cherrypick(v0.33): feat: Add Versioned for EC2NodeClass Hash to Prevent Drift on EC2NodeClass CRD Upgrade

go.mod, go.sum, pkg/apis/v1beta1/ec2nodeclass.go, pkg/apis/v1beta1/labels.go, pkg/cloudprovider/drift.go, pkg/cloudprovider/nodeclaim_test.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/nodeclass_test.go, pkg/utils/nodeclass/nodeclass.go, test/pkg/environment/common/expectations.go, test/suites/beta/drift/suite_test.go, test/suites/beta/integration/hash_test.go
Fixes #N/A 
- Cherrypicked PRs:
- https://github.com/aws/karpenter-provider-aws/pull/5770
- https://github.com/aws/karpenter-provider-aws/pull/5803
=> cherrypick(v0.32): feat: Add Versioned for EC2NodeClass Hash to Prevent Drift on EC2NodeClass CRD Upgrade

pkg/apis/v1beta1/ec2nodeclass.go, pkg/apis/v1beta1/ec2nodeclass_hash_test.go, pkg/cloudprovider/suite_test.go, pkg/providers/instancetype/instancetype.go, pkg/providers/launchtemplate/launchtemplate.go, test/suites/drift/suite_test.go
Fixes #5447
This change applies the change that was added in #3330 and ensures that we won't regress on this issue again by adding the relevant testing into functional and E2E testing. Hashing the resource quantity value as a string was missed with the changes were ported over and duplicated from the AWS provider struct in v1alpha1.
=> fix: Hash volume size quantity value as a string

test/pkg/environment/aws/environment.go, test/pkg/environment/common/environment.go, test/suites/consolidation/suite_test.go, test/suites/drift/suite_test.go, test/suites/integration/ami_test.go, test/suites/integration/block_device_mappings_test.go, test/suites/integration/extended_resources_test.go
Fixes #N/A 
Migrates the AMI family used for E2E tests to AL2023. This is done where applicable, tests which rely on GPU support will continue to use AL2 until an AL2023 accelerated AMI is released.
=> test: migrate e2e tests to use AL2023

pkg/controllers/nodeclass/controller.go
Fixes #N/A 
- fix Error handling for the node class controller 
=> chore: Fix error checking for the node class controller

.github/actions/e2e/cleanup/action.yaml, .github/actions/e2e/install-helm/action.yaml, .github/actions/e2e/install-karpenter/action.yaml, .github/actions/e2e/install-prometheus/action.yaml, .github/actions/e2e/run-tests-private-cluster/action.yaml, .github/actions/e2e/setup-cluster/action.yaml, .github/actions/e2e/slack/notify/action.yaml, .github/dependabot.yaml, .github/workflows/e2e-private-cluster-trigger.yaml, .github/workflows/e2e.yaml, test/hack/e2e_scripts/clean_private_cluster.sh, test/hack/e2e_scripts/configure_private_cluster.sh, test/hack/e2e_scripts/diff_karpenter.sh, test/hack/e2e_scripts/install_helm.sh, test/hack/e2e_scripts/install_karpenter.sh, test/hack/e2e_scripts/install_prometheus.sh, test/hack/e2e_scripts/noderole_bootstrap_permission.sh, test/hack/resource/clean/main.go, test/hack/resource/count/main.go, test/hack/resource/pkg/resourcetypes/vpc_peering_connection.go, test/pkg/environment/aws/environment.go, test/suites/integration/extended_resources_test.go, test/suites/integration/instance_profile_test.go, test/suites/integration/scheduling_test.go, test/suites/integration/tags_test.go
Fixes #N/A 
These changes create a scheduled trigger to run E2E tests for private cluster that will run on every Wednesday at 00:07. Since any `kubectl` command on a private cluster only works from inside the VPC of the cluster, all such installations have been moved under `hack/scripts` that will allow these scripts to be reused for public and private clusters.
The E2E tests for private cluster will run inside a codebuild job. The buildspec file for codebuild job consists of set of commands that will be executed in order to install karpenter, prometheus etc and then to run the `Integration` test suite. Since private clusters can't pull image from the internet, there are changes to pull it from the ECR within the VPC. More details about private clusters can be found …
=> test: Changes to run e2e for private cluster

website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md, website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh, website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh, website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart-fargate.sh, website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart-fargate.sh, website/content/en/v0.34/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.34/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh, website/content/en/v0.34/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh, website/content/en/v0.34/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart-fargate.sh, website/content/en/v0.35/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.35/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh, website/content/en/v0.35/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh, website/content/en/v0.35/getting-started/getting-started-with-karpenter/scripts/step08-apply-helm-chart-fargate.sh
Fixes #5677
The Karpenter pods fails to come up when the helm command provided in the documentation used for deploying Karpenter pods on Fargate. To fix this Cluster launch command and Karpenter installation helm commands needs slight modification. This PR will create separate tabs for Cluster launch command and for Karpenter installation commands for Node Group as well as Fargate.
In my test account EKS deployment and document changes were tested locally with "hugo server -D" command.
=> docs changes in getting-started-with-karpenter doc to fix #5677

website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/docs/reference/cloudformation.md, website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/preview/reference/cloudformation.md, website/content/en/v0.32/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.32/reference/cloudformation.md, website/content/en/v0.33/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.33/reference/cloudformation.md, website/content/en/v0.34/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.34/reference/cloudformation.md, website/content/en/v0.35/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.35/reference/cloudformation.md
Use reference to `${KarpenterNodeRole.Arn}` for `"Sid": "AllowPassingInstanceRole"` in CloudFormation (like it is already done in case of `"Sid": "AllowInterruptionQueueActions"` definition)
Deploy CloudFormation...
=> chore: Use "${KarpenterNodeRole.Arn}" in policy definition

website/content/en/docs/concepts/scheduling.md, website/content/en/preview/concepts/scheduling.md, website/content/en/v0.32/concepts/scheduling.md, website/content/en/v0.33/concepts/scheduling.md, website/content/en/v0.34/concepts/scheduling.md, website/content/en/v0.35/concepts/scheduling.md
Fixes #5238
Add more documentation examples of how to schedule based on node attributes
Documentation change
=> docs: Add more scheduling examples

pkg/providers/subnet/suite_test.go
Fixes #N/A 
- Adding testing to validate the subnets cache is caching expected values
- N/A
=> test: Add unit cache tests for subnets

pkg/providers/securitygroup/suite_test.go
Fixes #N/A 
- Adding testing to validate the security groups cache is caching expected values
- N/A
=> test: Add unit cache tests for security groups

hack/code/prices_gen/main.go, pkg/cloudprovider/cloudprovider.go, pkg/controllers/controllers.go, pkg/controllers/interruption/controller.go, pkg/controllers/interruption/interruption_benchmark_test.go, pkg/controllers/interruption/suite_test.go, pkg/controllers/nodeclaim/tagging/controller.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/pricing/controller.go, pkg/controllers/pricing/suite_test.go, pkg/fake/utils.go, pkg/operator/operator.go, pkg/providers/amifamily/ami.go, pkg/providers/amifamily/resolver.go, pkg/providers/instance/instance.go, pkg/providers/instance/suite_test.go, pkg/providers/instanceprofile/instanceprofile.go, pkg/providers/instancetype/instancetype.go, pkg/providers/instancetype/suite_test.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go, pkg/providers/pricing/pricing.go, pkg/providers/securitygroup/securitygroup.go, pkg/providers/securitygroup/suite_test.go, pkg/providers/sqs/sqs.go, pkg/providers/subnet/subnet.go, pkg/providers/subnet/suite_test.go, pkg/providers/version/version.go, pkg/test/environment.go, test/pkg/environment/aws/environment.go
Fixes #N/A 
This change adds interfaces for all of the provider clients to allow for mocking of the Providers to ease some of the testing burden for mocking out the underlying data.
=> chore: Convert all AWS providers to interfaces

pkg/operator/operator.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/test/environment.go
Fixes #N/A 
Fix missed launch template provider using the `DefaultProvider` instead of the Provider interfaces.
=> chore: Update launch template provider to leverage interfaces

pkg/controllers/nodeclass/suite_test.go, pkg/providers/instanceprofile/instanceprofile.go
Fixes #N/A 
Supports the call to `GetInstanceProfile` as part of the Instance Profile provider interface
=> chore: Support `GetProfileName()` through Instance profile interface

pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
- Adding testing to validate the LaunchTemplate cache key is generated as expected
=> test: Add unit cache tests for LaunchTemplate

website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
- Inform customers to use to the latest patch release version of the v1beta1 version of Karpetner during rollback if they have updated to v0.36.x
- N/A
=> docs: Upgrade guide note on rollbacking to the latest patch release for v1beta1

test/hack/resource/clean/main.go, test/hack/soak/get_clusters.go
Fixes #N/A 
- Exclude `soak-periodic-2785632730` from being terminated for an investigation 
- N/A
=> ci: Exclude cluster from termination for Windows investigation 

website/hugo.yaml
Fixes #N/A 
Karpenter website currently says v0.32 is the latest version when it should ideally be v0.36.
N/A
=> chore: Fix the website to correctly point to the latest release

pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Update call from `DeleteLaunchTemplate` to use `context.Context` like other SDK functions
=> chore: Delete launch template with context

pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Use `v1beta1.Group` constants for launch template naming and keys
=> chore: Use group constants for launch template naming

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v0.36/concepts/disruption.md
This adds documentation about the `consolidateAfter` configuration for `NodePool`s not being available when `consolidationPolicy: WhenUnderutilized` is set.
=> docs: add information about consolidateAfter not working with WhenUnderutilized

.github/workflows/e2e-matrix.yaml
Fixes #N/A 
Upgrade test suite is failing because it is trying to look for Karpenter snapshot that was deleted due to the cleanup policy. 
=> test: Pinning Karpenter version for upgrade test suite

pkg/cloudprovider/suite_test.go
Fixes #N/A 
Add a test for returning `ec2nodeclass-hash-version` on `Create()`
=> test: Add a test for returning `ec2nodeclass-hash-version` on `Create()`

pkg/operator/operator.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/test/environment.go
Fixes #N/A 
- Remove instanceProfileProvider from launchTemplateProvider, since it's not used in the provider 
- N/A
=> chore: Remove instanceProfileProvider from the launchTemplateProvider

pkg/apis/v1beta1/ec2nodeclass.go, pkg/controllers/nodeclass/suite_test.go, pkg/operator/operator.go, pkg/providers/instanceprofile/instanceprofile.go, pkg/test/environment.go
Fixes #N/A 
This adds an interface for the NodeClass to be passed into the instance profile provider for testability
=> chore: Add an instance profile interface to instance profile provider

go.mod, pkg/controllers/controllers.go, pkg/controllers/interruption/interruption_benchmark_test.go, pkg/controllers/interruption/suite_test.go, pkg/providers/sqs/sqs.go, test/pkg/environment/aws/environment.go
Fixes #N/A 
Use queueURL in sqs.Provider constuctor
=> chore: Use queueURL instead of queueName for sqs provider

test/hack/soak/get_clusters.go
Fixes #N/A 
- Prevent Excluded cluster from running in soak testing suite 
- N/A 
=> ci: Excluded cluster should not be run for Soak Testing

pkg/controllers/nodeclass/hash/controller.go, pkg/controllers/nodeclass/status/controller.go
Fixes #N/A 
- Adding rate limiter to make the stats and hash controller more consistent with the old NodeClass controller 
- N/A
=> chore: Add Rate limiter for Hash and Status Controller

charts/karpenter/values.yaml
Fixes #N/A 
- Update the `endpointConfig` helm field to be used as additional fields for `http-metrics` endpoint.
- N/A
=> chore: Update `endpointConfig` comment for the helm values

charts/karpenter/templates/servicemonitor.yaml
Fixes #N/A 
This fixes the pattern in the Helm `ServiceMonitor` template where the code was broken by #5571 (I have no idea why it was merged, but I suspect it was a fix for the pre-refactored chart version) and incorrectly fixed by #5624; the `nindent` value should match the indentation of the `{{}}` block.
I've tested this locally.
=> fix(chart): Correct fix for ServiceMonitor indentation

pkg/apis/v1beta1/labels.go, pkg/apis/v1beta1/register.go
Fixes #N/A 
Update apigroup from const to var
=> chore: Update apigroup from const to var

.github/workflows/postsubmit.yaml
Fixes #N/A 
Add postsubmit task for automatically hydrating go proxy for commit after merge
=> ci: Add postsubmit task for hydrating proxy

pkg/apis/v1beta1/labels.go, pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Move tag for managed launch templates to v1beta1 package
=> chore: Move launch template managed tag

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v0.35/concepts/disruption.md, website/content/en/v0.36/concepts/disruption.md
Fixes #N/A 
This change clarifies a note around whether budget schedules are UTC or not depending on the image. Since the latest patch on v0.35, budgets are _always_ treated as UTC.
=> docs: Drop note on budget schedules sometimes being in utc

cmd/controller/main.go, pkg/cloudprovider/suite_test.go, pkg/controllers/controllers.go, pkg/controllers/providers/instancetype/controller.go, pkg/controllers/providers/instancetype/suite_test.go, pkg/providers/instance/suite_test.go, pkg/providers/instancetype/instancetype.go, pkg/providers/instancetype/suite_test.go, pkg/providers/launchtemplate/suite_test.go, pkg/test/environment.go
Fixes #N/A 
- Asynchronously hydrate with instance type data. The controller will attempt to refresh the data every 12 hours, and implement a exponential backoff for delay: 1ms and max: 1000s
- `make presubmit` 
- E2E testing will be added in a separate PR
=> chore: Add an Instancetype Controller to Asynchronously Hydrate InstanceType Data

hack/docs/instancetypes_gen_docs.go
Fixes #N/A 
- Hydrate instance type data for docs-gen
- N/A
=> chore: Hydrate Instance Type Data for docs-gen 

website/content/en/docs/concepts/scheduling.md, website/content/en/preview/concepts/scheduling.md, website/content/en/v0.32/concepts/scheduling.md, website/content/en/v0.34/concepts/scheduling.md, website/content/en/v0.35/concepts/scheduling.md, website/content/en/v0.36/concepts/scheduling.md
Fixes #6058
Clarify some details around the `Exists` operator that caused confusion inside of the conceptual docs.
=> docs: Clarify conceptual docs around `Exists` operator

website/content/en/docs/concepts/nodepools.md, website/content/en/preview/concepts/nodepools.md, website/content/en/v0.32/concepts/nodepools.md, website/content/en/v0.34/concepts/nodepools.md, website/content/en/v0.35/concepts/nodepools.md, website/content/en/v0.36/concepts/nodepools.md
Fixes #N/A 
Node pool `limits` field is incorrectly commented in the example as constraining the total size of the cluster
N/A
=> docs: Fix reference to total cluster size constraint

pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1beta1/ec2nodeclass.go
Fixes #6055
This fixes the volume size string validation that should have already been performed to ensure that the resource value must be one of `T`, `Ti`, `G`, or `Gi`. You could bypass this check by specifying an integer; however, etcd would store this value as a string somewhere down the line which would cause us to fail to delete the EC2NodeClass.
There's [an open issue against `controller-gen`](https://github.com/kubernetes-sigs/controller-tools/issues/928) to try and dig deeper into what causes the integer to be able to circumvent this validation but then pass through the validation later, causing it to fail.
By submitting this pull request, I confirm that my contribution is made …
=> fix: Fix volume size validation

.github/actions/e2e/run-tests-private-cluster/action.yaml, .github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e-upgrade.yaml, .github/workflows/e2e.yaml
Fixes #N/A 
- Add log forwarding for containers to CloudWatch
- Tested in a forked repo
=> chore: Forward Container logs for E2E tests

pkg/cloudprovider/drift.go, pkg/cloudprovider/suite_test.go, pkg/providers/instance/suite_test.go, pkg/providers/instancetype/suite_test.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
- Asynchronously hydrate with Security Group data. The controller will attempt to refresh the data every 5 minutes, and implement a exponential backoff for delay: 1ms and max: 1000s
=> chore: Use Security Group Status Controller to Asynchronously Hydrate Security Group  Data

website/content/en/docs/upgrading/upgrade-guide.md, website/content/en/preview/upgrading/upgrade-guide.md, website/content/en/v0.36/upgrading/upgrade-guide.md
Fixes #N/A 
Reverts some version bumps in the upgrade doc mistakenly made in https://github.com/aws/karpenter-provider-aws/pull/6101.
=> docs: revert version bump in upgrade guide

test/pkg/environment/common/expectations.go, test/suites/consolidation/suite_test.go, test/suites/drift/suite_test.go, test/suites/expiration/suite_test.go, test/suites/integration/scheduling_test.go, test/suites/integration/utilization_test.go
Fixes #N/A 
Fixes several tests which are sensitive to the number of daemonsets in the test environment. This is due to assumptions about the size of node a given pod would fit on. This assumption was broken by #5982 which added an additional daemonset.
`karpenter snapshot`
=> test: fix daemonset sensitive tests

go.mod, go.sum, pkg/controllers/nodeclaim/tagging/controller.go, pkg/controllers/nodeclass/hash/controller.go, pkg/controllers/nodeclass/status/controller.go, pkg/controllers/nodeclass/termination/controller.go
Fixes #N/A 
Utilizes https://github.com/awslabs/operatorpkg/blob/main/reasonable/reasonable.go
=> chore: Replace ratelimiters with those from awslabs/operatorpkg

hack/docs/instancetypes_gen_docs.go, pkg/cloudprovider/cloudprovider.go, pkg/providers/instancetype/instancetype.go, pkg/providers/instancetype/types.go, website/content/en/preview/reference/instance-types.md
Fixes #N/A 
This change fixes calling `make docgen` and the instance types generation by calling the providers directly.
`make docgen`
=> ci: Fix docgen by calling providers directly

.github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
This change removes Daemonsets in the CWA add-on that we don't care about and ensures that we don't miscalculate DaemonSet capacity during scheduling due to: https://github.com/kubernetes-sigs/karpenter/issues/715. This also patches on the priority class so that we ensure that we always schedule these pods.
=> ci: Remove daemonsets causing testing issues

pkg/providers/amifamily/ami.go, pkg/providers/subnet/subnet.go
Fixes #5997
- Karpenter currently does not have any locking mechanism during its read and write operation for AMIs that are stored in the cache. Adding in locks to synchronize the cache for identical AMISelectorTerms
- The DescribeImages API does not filter out AMIs before fetching AMIs by tags. This will result in the DescribeImages API sending empty pages(This is currently expected behavior). The best mitigation here will for Karpenter to increases page sizes to reduce the number of request that are made.
- Result from testing 
- I had 20 EC2NodeClass with Identical AMISelectorTerms set 
```
amiSelectorTerms:
- tags:
testing: aengeda
```
- Number of DescribeImages call from main: 1604
- Number of DescribeImages call from with Improvements: …
=> pref: Reduce the number of `DescribeImages` calls

website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Add Getting Started note for IAM private clusters on v0.32
=> docs: Add Getting Started note for IAM private clusters

pkg/providers/amifamily/ami.go, pkg/providers/amifamily/suite_test.go
Fixes #N/A 
Fixes a bug with the AMI ordering logic. This was only reached if Karpenter was trying to order AMIs that had both the same creation timestamp and the same name. 
make presubmit
=> fix: correct AMI ordering function

.github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e-matrix.yaml
Fixes #N/A 
Bumps the source version for the upgrade suite to be after the cloudwatch infrastructure changes.
N/A (can't test top-level workflow changes w/ `/karpenter snapshot`)
=> ci: bump upgrade suite source commit

test/suites/drift/suite_test.go, test/suites/integration/ami_test.go, test/suites/nodeclaim/garbage_collection_test.go
Fixes #N/A 
Fix AMI selection during version compat E2Es to not use `lo.Ternary` since that function doesn't allow short-circuiting like an `if` statement, causing failure when we never wanted to resolve the second argument.
=> test: Fix AMI selection when performing version compat e2e

.github/workflows/e2e-matrix.yaml
Fixes #N/A 
Pins the upgrade test to the following commit:
- https://github.com/aws/karpenter-provider-aws/pull/6169
This ensures that we create the cluster for the upgrade suite with the pinned version of the cloudwatch addon. The latest version, 1.6.0, causes failures in some tests which binpack based on ds count (podsPerCore and maxPods scheduling tests).
=> ci: pin upgrade test

pkg/providers/amifamily/ami.go, pkg/providers/amifamily/suite_test.go, pkg/providers/instancetype/instancetype.go, pkg/providers/instancetype/suite_test.go, pkg/providers/securitygroup/securitygroup.go, pkg/providers/securitygroup/suite_test.go, pkg/providers/subnet/subnet.go, pkg/providers/subnet/suite_test.go
Fixes #N/A 
Ensure the slices are deep copied before returning back cached data from the caller. This ensures if the slice of the data is manipulated by the caller (like sorted), it doesn't affect the original copy that is stored and cached.
This can particularly be a problem when sorts are occurring on the original data in a multi-threaded manner. Because of swaps, this can cause the same data to appear multiple times or to be altered in ways that are inconsistent.
=> fix: Ensure shallow copy of data when returning back cached data

pkg/cache/cache.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/subnet/subnet.go, pkg/providers/subnet/suite_test.go
Fixes #N/A 
- Before this change https://github.com/aws/karpenter-provider-aws/pull/6057, If a customer did not set `associatePublicIPAddress` in their nodeclass, Karpenter would auto discover setting `associatePublicIPAddress` on launch templates by seeing if any of the subnets can add public IPs. If not, the field would be set to `nil` on launch templates. After PR 6057, we would set `associatePublicIPAddress` to false in the launch template. This PR looks to make feature parity by setting `associatePublicIPAddress` on launch template to `nil`.
- N/A
=> chore: Update `associatePublicIPAddress` to not be set in the launch templets

go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/v1beta1/ec2nodeclass_status.go, pkg/controllers/nodeclass/hash/controller.go, pkg/controllers/nodeclass/hash/suite_test.go, test/pkg/debug/nodeclaim.go, test/pkg/environment/common/expectations.go, test/suites/drift/suite_test.go, test/suites/nodeclaim/nodeclaim_test.go, website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
This change converts knative's status conditions to operatorpkg `status.Conditions` package. This allows us to onboard to things like `status.Controller` that will give us additional metrics on our status conditions for free.
BREAKING: The `severity` field is removed from the conditions object. This field is not present in `metav1.Condition` but was present in the knative representation. 
=> BREAKING: Add operatorpkg status conditions

pkg/controllers/interruption/controller.go, pkg/controllers/interruption/metrics.go, pkg/providers/subnet/subnet.go
Fixes #6093 
Understanding/Filtering actions being performed by interruption message based on what nodepool is useful, especially if a lot of different nodepools are used. Some of the nodepools need are more important than other, so viewing just specific events helps debugging events in cluster.
Tested in personal cluster.
=> feat: Add nodepool label to karpenter_interruption_actions_performed

test/suites/integration/ami_test.go, test/suites/integration/instance_profile_test.go, test/suites/integration/security_group_test.go, test/suites/integration/subnet_test.go
Fixes #N/A 
Fixes failing E2E testing to validate the correct message value for the "Ready" condition on the NodeClass
=> test: Fix failing testing to validate correct message value

test/pkg/environment/common/expectations.go, test/suites/drift/suite_test.go
Fixes #N/A 
Fixes a flake in a drift test. The test eventually expects the original replacement nodeclaim to be deleted, and checks for this by expecting on the number of nodeclaims. The problem is a new replacement nodeclaim may be created between checks in the eventually block. 
=> test: fix race in flakey drift test

.github/actions/e2e/install-prometheus/values.yaml, test/hack/e2e_scripts/install_karpenter.sh, test/pkg/environment/common/setup.go, test/suites/scale/deprovisioning_test.go
Fixes #N/A 
1.) We are finding that nodes launched on with c6g.medium can't fit all the nodes provisioned by karpenter when using Bottlerocket AMIs. When we receive these instance type, we the scheduler not placing all the expected pods on those nodes. https://github.com/aws/karpenter-provider-aws/issues/5161. CW daemonset was added that that totaled  to `158Mi`.
- Reported memory values: 
- AL2023 c6g.medium: 1425680Ki
- Bottlerocket c6g.medium: 1216348Ki
- AL2023 m6g.medium: 3433832Ki
- Bottlerocket m6g.medium: 3224432Ki
- From looking at the memory overhead usage we see that, instance memory for c6g.medium: 2048 https://karpenter.sh/docs/reference/instance-types/#c6gmedium and m6g.medium: 4096 https://karpenter.sh/docs/reference/instance-types/#m6gmedium
2.) …
=> fix: Increase to large instance size for scale tests

.github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
- Add Cloudwatch policy to scrape container logs from Karpenter launched nodes. This mainly to pull Kubelet logs from Windows nodes to track down flaky failures on Node joining failures. 
- Link on imported kubelet logs:https://aws.amazon.com/blogs/containers/fluent-bit-integration-in-cloudwatch-container-insights-for-eks/
=> ci: Add Cloudwatch Policy on Karpetner nodes for Windows nodes

go.mod, go.sum, pkg/providers/instance/instance.go
Fixes #N/A 
This change adds an `instanceTypes.Truncate()` call back to the CloudProvider on 60 instance types. This will make no difference in the standard codepath since we already truncate in the scheduler but matters for cases when users launch standalone NodeClaims.
This should fix all failures in the NodeClaim suite in our [VersionCompatability suite](https://github.com/aws/karpenter-provider-aws/actions/workflows/e2e-version-compatibility-trigger.yaml) that run in `eu-west-1`. This test suite was failing consistently because we were sending too many instance types to EC2 Fleet, causing an error for too large of a response body to come back.
Running the NodeClaim suite on a local cluster in …
=> fix: Add truncating back to cloudprovider, considering minValues

website/content/en/docs/getting-started/migrating-from-cas/_index.md, website/content/en/preview/getting-started/migrating-from-cas/_index.md, website/content/en/v0.32/getting-started/migrating-from-cas/_index.md, website/content/en/v0.34/getting-started/migrating-from-cas/_index.md, website/content/en/v0.35/getting-started/migrating-from-cas/_index.md, website/content/en/v0.36/getting-started/migrating-from-cas/_index.md
Fixes #N/A 
The migrating from CAS guide incorrectly split the affinity terms into two different match expressions, which will treat the two terms as an OR semantic, only requiring one of them to be true. If the items are within the same MatchExpressions block, they're treated as an AND.
Tested with manual application of deployment on my own cluster
=> docs: fix migrating from cas node affinity guide

pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go, pkg/providers/subnet/subnet.go, pkg/providers/subnet/suite_test.go
Fixes #N/A 
Drops implicit public IP association as called out in the [v1 roadmap](https://github.com/kubernetes-sigs/karpenter/pull/1222/files#diff-055dd5f24ba5dd20e449cb25f9e8a572200b3bd059ce75b1fbaae860e6284e27R201-R205).
`make presubmit` and `/karpenter snapshot`
=> chore: drop implicit public IP association config

hack/docs/instancetypes_gen_docs.go, website/content/en/docs/reference/instance-types.md, website/content/en/preview/reference/instance-types.md, website/content/en/v0.34/reference/instance-types.md, website/content/en/v0.35/reference/instance-types.md, website/content/en/v0.36/reference/instance-types.md
Fixes #N/A 
Updates the instance-type reference page to be generated using AL2023 rather than AL2. Additionally, drops reference to droppend `enableENILimitedPodDensity` flag.
=> docs: update instance type generation for AL2023

pkg/providers/amifamily/ami.go, pkg/providers/amifamily/resolver.go
Fixes #N/A 
Fixed the Log message listing all AMIs details
```
{"level":"DEBUG","time":"2024-05-17T12:58:20.632-0500","logger":"controller.nodeclass.status","message":"discovered amis","ec2nodeclass":"critical-addons-only","ids":[{"Name":"amazon-eks-arm64-node-1.29-v20240514","AmiID":"ami-06882dd1807dd93be","CreationDate":"2024-05-14T16:59:11.000Z","Requirements":{"karpenter.k8s.aws/instance-accelerator-count":{"Key":"karpenter.k8s.aws/instance-accelerator-count","MinValues":null},"karpenter.k8s.aws/instance-gpu-count":{"Key":"karpenter.k8s.aws/instance-gpu-count","MinValues":null},"kubernetes.io/arch":{"Key":"kubernetes.io/arch","MinValues":null}}},{"Name":"amazon-eks-gpu-node-1.29-v20240514","AmiID":"ami-086598116d98d2953","CreationDate":"2024-05-14T16:59:11.000Z","Requir …
```
=> chore: Use AMI IDs in the logs for AMI discovery

go.mod, go.sum, pkg/apis/v1beta1/ec2nodeclass_status.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/status/readiness.go, pkg/controllers/nodeclass/status/readiness_test.go, pkg/controllers/nodeclass/status/securitygroup_test.go, pkg/controllers/nodeclass/status/subnet_test.go, pkg/providers/instancetype/suite_test.go, pkg/providers/launchtemplate/suite_test.go, test/pkg/environment/common/expectations.go, test/suites/integration/ami_test.go, test/suites/integration/instance_profile_test.go, test/suites/integration/security_group_test.go, test/suites/integration/subnet_test.go
Fixes #N/A 
Readjusts the status conditions to not use two root conditions and pulls in the latest for sigs.k8s.io/karpenter and awslabs/operatorpkg
make presubmit and snapshots here
=> fix: adjust status conditions to only use root condition

pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
Currently, no topology-manager-policy setting appears in instance userdata if it is set in EC2NodeClass userdata
It seems like this setting was inadvertently removed in https://github.com/aws/karpenter-provider-aws/pull/3264/files#diff-a3cbfce28a0ecf65dea19fa09613d36dc9d5c653ff993472e70820de27f03efeL70
Fixes #N/A 
=> add back TopologyManagerPolicy to bottlerocketsettings

go.mod, go.sum, pkg/controllers/interruption/controller.go, pkg/controllers/nodeclaim/garbagecollection/controller.go, pkg/controllers/nodeclaim/tagging/controller.go, pkg/controllers/nodeclass/hash/controller.go, pkg/controllers/nodeclass/status/controller.go, pkg/controllers/nodeclass/termination/controller.go, website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Drop logger name injection at the top of controllers and add consistent formatting for K8s objects
```
{"level":"DEBUG","time":"2024-05-22T18:56:55.832Z","logger":"controller.nodeclass.status","message":"discovered amis","commit":"d39fdb5","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"5bc00b9a-2d9a-4622-84ee-55c67f0aad1a","ec2nodeclass":"default","ids":["ami-06882dd1807dd93be","ami-086598116d98d2953","ami-0ef5558292b11416e"]}
```
```
{"level":"DEBUG","time":"2024-05-22T18:48:29.569Z","logger":"controller","message":"discovered amis","commit":"1169b7a","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","contro …
```
=> BREAKING: Drop logger name injection and add consistent formatting for K8s objects

pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
Fixes #5517
Adds support for seccomp-default and cluster-domain to the settings.kubernetes struct.
Deployed to a development EKS cluster, resulting user data and Kubelet `configz` checked to include the new fields when specified in an EC2NodeClass.
=> feat: Add extra fields to Bottlerocket k8s config

.github/actions/e2e/run-tests-private-cluster/action.yaml, .github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e-upgrade.yaml, .github/workflows/e2e.yaml
Fixes #N/A 
Remove the cloudwatch agent used for log forwarding to unblock testing with EKS 1.30. The cloud watch agent is currently unsupported on EKS 1.30 and blocks cluster creation in our E2E suite.
N/A
=> ci: drop cloudwatch agent

.github/workflows/e2e-matrix.yaml
Fixes #N/A 
Pins the upgrade source commit to #6269. This removes the cloudwatch agent and fixes the upgrade suite when running on EKS 1.30.
N/A
=> ci: pin upgrade source commit

go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/providers/version/version.go
Fixes #N/A 
- updates the upstream karpenter dependency to v0.37.0
- bumps the max k8s version to 1.30
=> chore: bump karpenter to v0.37.0

hack/release/common.sh
This partially reverts commit bc653f0e1e09589e9b8c712a221ae64f6cb69b55.
Fixes #N/A 
Reverts the AH config duplication fix introduced in #6022. This change would require us to add permissions for `ecr-public:BatchDeleteImage` to our release IAM role. To avoid expanding the scope of the release role, we should set up a separate process for handling image cleanup or setup a lifecycle policy for the repo if they eventually become available for public ECR ([tracking issue](https://github.com/aws/containers-roadmap/issues/1268)).
N/A
=> ci: revert AH config duplication fix

website/content/en/docs/upgrading/upgrade-guide.md, website/content/en/preview/upgrading/upgrade-guide.md, website/content/en/v0.37/upgrading/upgrade-guide.md
Fixes #N/A 
Adds an explicit note in the upgrade guide for the required CRD update. This adds the readiness condition to the EC2NodeClass, without which v0.37.0 will be unable to provision new nodes.
N/A
=> docs: explicitly call out CRD upgrade requirement

test/suites/integration/ami_test.go
Fixes #N/A 
Updates the "old ami image" used in the "should use the most recent AMI" test to a release with a 1.30 version. This test will need to be updated each time a new EKS version is released.
=> test: fix recent AMI test for EKS 1.30

website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md, website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.32/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.35/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.36/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v0.37/getting-started/getting-started-with-karpenter/_index.md
Fixes #N/A 
Drops the note on the eksctl breaking change and bumps the min version to v0.180.0 for Karpenter versions which previously required v0.179.0. This is in light of the [v0.180.0 release](https://github.com/eksctl-io/eksctl/releases/tag/v0.180.0) that reverts the breaking change.
N/A
=> docs: drop eksctl note and bump min version

.github/actions/e2e/cleanup/action.yaml, .github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e-cleanup.yaml, .github/workflows/e2e-upgrade.yaml, .github/workflows/e2e.yaml
Fixes #N/A 
Upgrades eksctl to `v0.180.0` for CI. This release includes https://github.com/eksctl-io/eksctl/pull/7784, dropping the behavior where a service account is created for a pod identity association by default. 
N/A
=> ci: upgrade eksctl to v0.180.0

test/hack/resource/clean/main.go, test/hack/soak/get_clusters.go
Fixes #N/A 
- Exclude clusters from deleted for investigation 
- soak-periodic-55897225
- soak-periodic-465714144
- N/A
=> ci: Exclude soak testing clusters from deletion 

website/content/en/docs/concepts/scheduling.md, website/content/en/preview/concepts/scheduling.md
Fixes #N/A 
Documents Karpenter behavior around soft affinities.
Docs only change.
=> docs: update karpenter docs around soft affinity behavior

test/hack/resource/pkg/resourcetypes/eni.go, test/hack/resource/pkg/resourcetypes/instance.go, test/hack/resource/pkg/resourcetypes/launchtemplate.go, test/hack/resource/pkg/resourcetypes/securitygroup.go, test/hack/resource/pkg/resourcetypes/stack.go, test/hack/resource/pkg/resourcetypes/vpc_endpoint.go, test/hack/resource/pkg/resourcetypes/vpc_peering_connection.go
Fixes #6268
Updated to using [aws-sdk-go-v2 pagination](https://aws.github.io/aws-sdk-go-v2/docs/making-requests/#using-paginators) from manually paginating each API call.
Local testing for expected count and clean behavior for each resource changed.
=> chore: Paginate resources with aws-sdk-go-v2 pagination (aws#6268)

.github/workflows/e2e-version-compatibility-trigger.yaml
Fixes #N/A 
- Without `git_ref` PR runs are currently broken for versionCompatibility. Adding it to fix `/karpenter versionCompatibility` 
- https://github.com/aws/karpenter-provider-aws/actions/runs/9452050051
- N/A
=> ci: Add `git_ref` for versionCompatibility 

website/content/en/preview/concepts/nodepools.md, website/content/en/preview/contributing/documentation-updates.md, website/content/en/preview/faq.md
I spent several days tracking down why Karpenter would create several unnecessary nodes in order to schedule pending pods in our clusters. Ultimately, I discovered this behavior was occurring.
1. Karpenter sees a pending pod that cannot be scheduled without a new node.
2. Karpenter creates a new nodeclaim, followed by a new node joining the cluster.
3. Karpenter's provisioning logic correctly determines that the pending node will satisfy the still pending pod.
4. Cilium's agent daemonset starts up on the new unready node, setting a startup taint to block pods from scheduling until the CNI is ready.
5. Karpenter sees that the still pending pod can no longer be scheduled to the node due to the cilium not-ready taint and provisions a second nodeclaim.
6. The original new node …
=> docs: add FAQ entry clarifying that startup taints are necessary to avoid excess node provisioning

website/content/en/docs/upgrading/compatibility.md, website/content/en/preview/upgrading/compatibility.md, website/content/en/v0.32/upgrading/compatibility.md, website/content/en/v0.35/upgrading/compatibility.md, website/content/en/v0.36/upgrading/compatibility.md, website/content/en/v0.37/upgrading/compatibility.md
Fixes #6348 
Updates the wording for stable releases and release candidates to indicate the tags are no longer prefixed by a `v`. Additionally, this drops the wording around a weekly release cadence.
N/A
=> docs: update stable release / rc wording

test/suites/scale/provisioning_test.go
Fixes #N/A 
We have been seeing spikes in the scale tests for provisioning. That's because there are two different tests that are captured by the same metric and the execution times are different for both.
1. Metric `node-dense` for node dense scale-up and node dense scale-up with minValues
2. Metric `pod-dense` for pod dense scale-up and pod dense scale-up with minValues
Created a different metric for scale up with and without min values. Now we have `node-dense`, `node-dense-min-val`, `pod-dense`, `pod-dense-min-val`.
=> test: Fix scale test provisioning spike

test/hack/resource/clean/main.go
Fixes #N/A 
- We are experiencing throttling in our [sweeper](https://github.com/aws/karpenter-provider-aws/actions/runs/9564694974/job/26366008036) and will need to increase the default retry attempt 
```
operation error IAM: ListInstanceProfileTags, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: f4676348-05c7-47e8-aae5-6402e1ce5040,
```
- Since the retry strategy is exponential backoff, increasing the number of retry attempts from 3 to 10 to make sure that call will be spread out exponentially and increase the likelihood of call succeeding 
=> ci: Increase max retry for the sweeper

website/content/en/docs/troubleshooting.md, website/content/en/preview/troubleshooting.md, website/content/en/v0.32/troubleshooting.md, website/content/en/v0.35/troubleshooting.md, website/content/en/v0.36/troubleshooting.md, website/content/en/v0.37/troubleshooting.md
Fixes #N/A 
Adds a note in the troubleshooting guide on Security Groups Per Pod and the impact on max pods.
N/A
=> docs: add troubleshooting note on SGPP and max-pods

website/content/en/docs/concepts/scheduling.md, website/content/en/preview/concepts/scheduling.md, website/content/en/v0.32/concepts/scheduling.md, website/content/en/v0.35/concepts/scheduling.md, website/content/en/v0.36/concepts/scheduling.md, website/content/en/v0.37/concepts/scheduling.md
Quoting bool value in gpu taint example
Fixes #N/A 
Following this documentation, I applied the taint as shown
```
taints: 
- key: nvidia.com/gpu
value: true
effect: "NoSchedule"
```
and got an error
```
NodePool.karpenter.sh "gpu" is invalid: [spec.template.spec.taints[0].value: Invalid value: "boolean": spec.template.spec.taints[0].value in body must be of type string: "boolean"
```
Quoting the `true` applied successfully. Also see here where the same example is already quoted:
https://karpenter.sh/docs/concepts/nodepools/
Previewed the scheduling.md
=> docs: Scheduling concept doc GPU taint example value: true bool should be a string

test/suites/integration/validation_test.go
Fixes #N/A 
We have been seeing failure in the private cluster test run. This PR adds a fix for it. 
Tested on private cluster in my account
=> test: Fix private cluster test failure

pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1beta1/ec2nodeclass.go
Fixes #N/A 
- Update storage version of the Karpenter CRDs, since v1 APIs are not currently being used in code
=> chore: Update storage version of EC2NodeClass to be v1beta1 APIs

pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1/ec2nodeclass.go
Fixes #N/A 
- Old EC2NodeClass Column 
```
NAME      AGE
default   2d8h
```
- New EC2NodeClass Column 
```
NAME           READY   AGE   ROLE
default        True    14h   KarpenterNodeRole-aengeda-karpenter-playground-us-west-2
```
- v1 RFC: https://github.com/kubernetes-sigs/karpenter/pull/1222
=> chore: Adding print columns for v1 EC2NodeClass 

go.mod, go.sum, pkg/apis/v1/doc.go, pkg/apis/v1/labels.go, pkg/apis/v1beta1/doc.go, pkg/apis/v1beta1/labels.go, pkg/operator/operator.go, pkg/webhooks/webhooks.go
Fixes #N/A 
Add Prometheus metrics for the AWS SDK Go. This used https://github.com/jonathan-innis/aws-sdk-go-prometheus to hydrate client-side metrics into the AWS SDK Go calls until the upstream `aws-sdk-go` or `aws-sdk-go-v2` support metrics out-of-the box.
See: https://github.com/aws/aws-sdk-go-v2/issues/1744
```
aws_sdk_go_request_total{action="CreateFleet",code="200",service="EC2"} 12
aws_sdk_go_request_total{action="CreateLaunchTemplate",code="200",service="EC2"} 48
aws_sdk_go_request_total{action="CreateTags",code="200",service="EC2"} 24
aws_sdk_go_request_total{action="DeleteLaunchTemplate",code="200",service="EC2"} 24
aws_sdk_go_request_total{action="DeleteMessage",code="200",service="SQS"} 89
aws_sdk_go_request_total{action="DescribeCluster",code="200",service="E …
```
=> chore: Add prometheus metrics for AWS client calls

charts/karpenter/README.md, hack/docgen.sh, hack/docs/instancetypes_gen_docs.go, hack/docs/metrics_gen_docs.go, website/content/en/preview/reference/instance-types.md, website/content/en/preview/reference/metrics.md, website/content/en/preview/reference/settings.md
Fixes #N/A 
Add metric generation for `controller_runtime`, `workqueue`, `aws_sdk_go`, and `client_go`
`make docgen`
=> docs: Fix `make docgen` for metrics generation

hack/codegen.sh, pkg/fake/ec2api.go, pkg/fake/zz_generated.describe_instance_types.go, pkg/providers/instancetype/suite_test.go, pkg/providers/instancetype/types.go, test/pkg/environment/aws/environment.go, test/suites/ami/suite_test.go, test/suites/integration/extended_resources_test.go, test/suites/integration/kubelet_config_test.go, test/suites/scheduling/suite_test.go
Fixes #N/A 
This change fixes a bug in the returned instance types from the Windows AMI to ensure that we don't allow instance types that don't have PrivateIPv4Addresses reported on the VPC limits.go file to be launched with the Windows AMI. Even though we can know the private IP address count from the EC2 DescribeInstances API, the `vpc.amazonaws.com/PrivateIPv4Address` resource won't be reported unless the VPC resource controller is aware of it.
=> fix: Fix failure launching windows pod when instance type isn't in vpc resource controller config

website/content/en/docs/concepts/nodepools.md, website/content/en/docs/concepts/scheduling.md, website/content/en/preview/concepts/nodepools.md, website/content/en/preview/concepts/scheduling.md, website/content/en/v0.32/concepts/nodepools.md, website/content/en/v0.32/concepts/scheduling.md, website/content/en/v0.35/concepts/nodepools.md, website/content/en/v0.35/concepts/scheduling.md, website/content/en/v0.36/concepts/nodepools.md, website/content/en/v0.36/concepts/scheduling.md, website/content/en/v0.37/concepts/nodepools.md, website/content/en/v0.37/concepts/scheduling.md
Fixes #N/A 
We have increased the limit on nodepool requirements to 100. This PR updates the doc to call out that change.
NA
=> docs: Update docs to indicate requirements limit on NodePool is 100

pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
Fixes #N/A 
Add [pod-pids-limit](https://bottlerocket.dev/en/os/1.19.x/api/settings/kubernetes/#pod-pids-limit) to bottlerocket settings.
=> chore: Add pod-pids-limit to bottlerocket settings

cmd/controller/main.go, go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1/suite_test.go, pkg/apis/v1beta1/suite_test.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/suite_test.go, pkg/controllers/interruption/suite_test.go, pkg/controllers/nodeclaim/garbagecollection/suite_test.go, pkg/controllers/nodeclaim/tagging/suite_test.go, pkg/controllers/nodeclass/hash/suite_test.go, pkg/controllers/nodeclass/status/suite_test.go, pkg/controllers/nodeclass/termination/suite_test.go, pkg/controllers/providers/instancetype/suite_test.go, pkg/controllers/providers/pricing/suite_test.go, pkg/fake/cloudprovider.go, pkg/operator/suite_test.go, pkg/providers/amifamily/suite_test.go, pkg/providers/instance/suite_test.go, pkg/providers/instancetype/suite_test.go, pkg/providers/launchtemplate/suite_test.go, pkg/providers/securitygroup/suite_test.go, pkg/providers/subnet/suite_test.go
Fixes #N/A 
This PR adds a change to return `[]status.object` from `GetSupportedNodeClasses`
Tested on local cluster
=> chore: Update GetSupportedNodeClasses to return []status.Object

pkg/apis/v1/ec2nodeclass_status.go, pkg/apis/v1beta1/ec2nodeclass_status.go, pkg/controllers/nodeclass/status/ami.go, pkg/controllers/nodeclass/status/ami_test.go, pkg/controllers/nodeclass/status/instanceprofile.go, pkg/controllers/nodeclass/status/instanceprofile_test.go, pkg/controllers/nodeclass/status/launchtemplate_test.go, pkg/controllers/nodeclass/status/readiness.go, pkg/controllers/nodeclass/status/readiness_test.go, pkg/controllers/nodeclass/status/securitygroup.go, pkg/controllers/nodeclass/status/securitygroup_test.go, pkg/controllers/nodeclass/status/subnet.go, pkg/controllers/nodeclass/status/subnet_test.go, test/suites/ami/suite_test.go, test/suites/integration/instance_profile_test.go, test/suites/integration/security_group_test.go, test/suites/integration/subnet_test.go
Fixes #N/A 
This PR adds status conditions to EC2nodeClass.
=> chore: Add status conditions on nodeClass

pkg/providers/securitygroup/securitygroup.go, pkg/providers/subnet/subnet.go
Fixes #N/A 
This fixes an issue where Karpenter was spurious logging "discovered subnets" any time there was a change in the subnet's IP availability. This change ensures that we will only log subnets when there is a change in the ids that are being selected on.
```console
{"level":"DEBUG","time":"2024-07-10T07:08:41.539Z","logger":"controller","message":"discovered subnets","commit":"ff0dc7d","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default"},"namespace":"","name":"default","reconcileID":"54da3ce7-88e7-42e3-ad25-6c0d9fef954f","subnets":[{"id":"subnet-0c89532267e680e6f","zone":"us-west-2a","zoneID":"usw2-az1"},{"id":"subnet-09d3d3e0bd7f68ee9","zone":"us-west-2b","zoneID":"usw2-az2"},{"id":" …
```
=> chore: Fix spurious `discovered subnets` lines in logging

pkg/providers/amifamily/bootstrap/bottlerocket.go, pkg/providers/launchtemplate/testdata/br_userdata_merged.golden, pkg/providers/launchtemplate/testdata/br_userdata_unmerged.golden
Fixes #N/A 
Updates the bottlerocket taint format such that a taint with no value still has a leading colon before effect. Failure to do so results in the bottlerocket instance being unable to register with the cluster.
=> fix: bottlerocket settings taint format

test/suites/scheduling/suite_test.go
Fixes #N/A 
The NodePool readiness controller checks for updates to NodeClasses based on their APIVersion along with the kind and name. Since this NodePool did not set the group, if the nodeclass was not ready before the first NodePool readiness reconciliation it would not be rereconciled and the NodePool would remain unready.
=> fix: scheduling flake due to nodepool readiness

test/suites/nodeclaim/testdata/al2023_userdata_custom_labels_input.yaml
Fixes #N/A 
This PR adds a fix for nodeclaim test suite failure `should create a NodeClaim with custom labels passed through the userData`. This test is failing because we were double quoting the labels being passed due to which nodeadm is not able to parse the labels correctly.
=> test: fix nodeclaim test for custom labels in userData

test/suites/scheduling/suite_test.go
Fixes #N/A 
Fixes a flake in the zone-id scheduling tests, where we might get the node before the label with the expected zone-id has been propagated by the nodeclaim lifecycle controller.
=> fix: scheduling zone-id flake

test/suites/scale/deprovisioning_test.go, test/suites/scale/provisioning_test.go
Fixes #N/A 
Deprovisioning scale tests were timing out since we merged the "Wait for instance termination PR". This was happening because the disruption budget of 10% would not allow all the nodes to be gone together thereby increasing the time taken for nodes to be deleted. To fix this, the budget has been increased to 70% in this PR.
Ran these tests on local cluster.
=> test: Fix time out in scale tests

test/suites/drift/suite_test.go
Fixes #N/A 
Drift where the nodepool would be altered during each update and then open up the nodepool to all possible EC2 instances. Some of these instances would be too small and use swap memory which causes kubelet to fail.
Example error:
```
Jul 12 20:24:01 kubelet[1596]: E0712 20:24:01.933476    1596 run.go:74] "command failed" err="failed to run Kubelet: running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename\t\t\t\tType\t\tSize\t\tUsed\t\tPriority /dev/zram0                              partition\t416>
```
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> test: fix drift suite

pkg/apis/apis.go, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/labels.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/drift.go, pkg/controllers/nodeclass/hash/controller.go, pkg/controllers/nodeclass/hash/suite_test.go, pkg/utils/utils.go, test/suites/integration/ec2nodeclass_kubelet_test.go
Fixes #N/A 
Added change to update nodeClaim hash when kubelet configuration on ec2nodeclass changes. This change has been added to orchestrate the conversion from v1beta1 to v1 apis specifically for the case where we have moved kubelet configuration from nodePool to nodeClass. We don't want to drift the nodeClaim if kubelet config is moved from nodePool to nodeClass if it's unchanged.
Added functional tests for this change.
=> chore: update kubelet hash annotation on nodeclaim

pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, pkg/providers/amifamily/ami.go
Fixes the following issues with AMI conversion:
- Fail closed when the AMI family we're convering from is Ubuntu
- Don't create an alias when the AMI family is non-custom but selector terms are specified
Fixes #N/A 
This PR fixes two issues with the conversion webhooks for AMI family and selector terms:
- Fail closed when the AMI family is Ubuntu
- Don't create an alias when the AMI family is non-custom but AMISelectorTerms are defined
`make test`
=> fix: ami family conversion

pkg/controllers/nodeclass/hash/suite_test.go, pkg/utils/utils.go
Fixes #N/A 
NodeClaim tests are failing because the standalone nodeClaims do not reference any nodePool. While adding the kubelet compatibility hash if this reference is empty, we should not throw an error and rather fall back to nodeClass kubelet config.
Tested on local cluster.`make test`
=> chore: fix nodeClaim tests failure

Makefile
Fixes #N/A 
When go timeouts happen, the test suite panics and does not enter after suite clean up steps. This allows the ginkgo timeout to be run before the go timeout, which actually runs the after test clean up.
=> test: prevent resource leaks from go timeout

test/suites/drift/suite_test.go
Fixes #N/A 
- The start-up taints that are racing with the start-up condition being added and removed by registration controller. There was a race when the start-up taint was and removed. This PR ensures that the start-up is added before our the will attempt to remove the taint. 
- tested locally
=> test: Fix Drift Start-up Taint Test Flake

test/suites/expiration/suite_test.go
Fixes #N/A 
ExpireAfter has been now moved to nodeClaim. With this change, if we modify expireAfter, nodeClaim will drift causing test failures. Updated the tests to have expireAfter set to a lower value at the beginning of the test.
Tested on local cluster
=> tests: fix expiration test failing due to drift when we modify expireAfter

test/suites/expiration/suite_test.go
Fixes #N/A 
- Add zero CPU limits instead removing nodepool limits 
- Tested Locally
=> test: Add zero CPU limits to expiration

website/hugo.yaml
Fixes #N/A 
- Update k8s version to say 1.30 instead of 1.3 on the preview page of the docs
=> docs: Update k8s version to be 1.30 instead of 1.3 on preview

test/suites/drift/suite_test.go
Fixes #N/A 
- Making sure that only the start-up taint is on the node before we patch the taints. This should help with having conflicting patch calls.
- Repeatedly tested that only start-up taint remaining before it's removed 
=> test: Validate that only the start-up is remaining before Drift check

.github/actions/e2e/install-karpenter/action.yaml, test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
We are seeing test failures in integration suite because webhooks are disabled while installing Karpenter on the cluster. Added a change to enable webhooks.
=> test: fix failure happening due to webhook being disabled

website/content/en/preview/getting-started/getting-started-with-karpenter/karpenter-capacity-dashboard.json, website/content/en/preview/reference/metrics.md
Fixes #N/A 
This PR updates docs for counter metrics to have suffix `_total`.
NA
=> docs: Update counter metrics to have suffix _total

.github/workflows/e2e-matrix.yaml, test/pkg/environment/common/expectations.go, test/suites/termination/emptiness_test.go, test/suites/termination/suite_test.go, test/suites/termination/termination_grace_period_test.go, test/suites/termination/termination_test.go
Fixes #N/A 
This PR adds tests for termination grace period seconds.
Tested on local cluster.
=> test: Add tests for termination grace period

website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/docs/reference/cloudformation.md, website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/preview/reference/cloudformation.md, website/content/en/v0.32/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.32/reference/cloudformation.md, website/content/en/v0.35/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.35/reference/cloudformation.md, website/content/en/v0.36/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.36/reference/cloudformation.md, website/content/en/v0.37/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.37/reference/cloudformation.md
Fixes #N/A 
- Scoping down instance profile permission to wild card only on instance profiles
=> chore: Scope down the IAM permission on instance profiles for Karpenter

designs/v1-api.md, designs/v1-roadmap.md
Fixes #N/A 
Adds the AWS CloudProvider-specific v1 RFC to the `aws/karpenter-provider-aws` repo. This is an API and roadmap extension of the https://github.com/kubernetes-sigs/karpenter/pull/1222 PR
=> docs: Add v1 RFC to the AWS CloudProvider repo

test/suites/scale/provisioning_test.go
Fixes #N/A 
There is a flakiness in provisioning scale tests where we want the created nodeclaim and node count to be equal to an expected value. We can skip this assertion and instead only check if all the pods were successfully provisioned which make sure that our underlying assumption is satisfied as well.
Tested on local cluster
=> test: fix scale testing flakes

go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, test/pkg/environment/common/environment.go, test/pkg/environment/common/expectations.go, test/suites/chaos/suite_test.go, test/suites/consolidation/suite_test.go, test/suites/integration/daemonset_test.go, test/suites/integration/validation_test.go, test/suites/scale/deprovisioning_test.go, test/suites/termination/emptiness_test.go, website/content/en/preview/concepts/disruption.md, website/content/en/preview/concepts/nodepools.md, website/content/en/preview/getting-started/getting-started-with-karpenter/_index.md, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/preview/getting-started/migrating-from-cas/scripts/step10-create-nodepool.sh, website/content/en/preview/tasks/managing-amis.md
Fixes #N/A 
This updates the go mod for upstream karpenter to use the latest to https://github.com/kubernetes-sigs/karpenter/commit/a3ce73eb8a7cd8ce0515c4f138afc876bc8eb679
Here and locally
=> chore: upgrade go mod and update tests

go.mod, go.sum, hack/docs/metrics_gen/main.go, pkg/controllers/interruption/controller.go, pkg/controllers/interruption/messages/statechange/model.go, pkg/controllers/interruption/messages/types.go, pkg/controllers/interruption/metrics.go, pkg/controllers/interruption/suite_test.go, website/content/en/preview/reference/metrics.md
Fixes #N/A 
Reconfigured `karpenter_nodeclaims_terminated_total` to `karpenter_nodeclaims_disrupted_total` metrics in case of interruption. Label type now indicates the kind of interruption message. Updated metrics would now look like -
1. karpenter_nodeclaims_disrupted_total {type="scheduled_change"}
2. karpenter_nodeclaims_disrupted_total {type="instance_terminated"}
3. karpenter_nodeclaims_disrupted_total {type="spot_interruption"}
4. 2. karpenter_nodeclaims_disrupted_total {type="instance_stopped"}
`make test`
=> chore: reconfigure nodeclaim terminated metrics due to interruption

test/pkg/environment/aws/environment.go, test/suites/consolidation/suite_test.go, test/suites/drift/suite_test.go
Fixes #N/A 
Adds e2e tests to verify that lastPodEvent is set at the correct times
FOCUS="LastPodEventTime" make e2etests
=> test: add lastPodEventTime e2es

test/pkg/environment/aws/environment.go
Fixes #N/A 
- Update AMIFamily for non-AL2023 versions 
=> fix: Update AMIFamily for non-AL2023 AMIs

charts/karpenter/templates/post-install-hook.yaml
Fixes #N/A 
- Support upgrade and rollback with Karpenter with the helm chart for the CRDs
- Updated the image to use `public.ecr.aws/bitnami/kubectl:1.30`
=> chore: Include post upgrade on Helm Hook

charts/karpenter/templates/clusterrole-core.yaml, test/pkg/environment/common/setup.go, test/suites/storage/suite_test.go
Fixes #N/A 
Add tests that validate [Karpenter PR 1294's](https://github.com/kubernetes-sigs/karpenter/pull/1294) solution to 6+ minute delays for disrupted stateful workloads outlined in #6336.  
Add two storage E2E tests that ensure:
- Disrupted stateful workloads run on a new node within 5 minutes
- Un-drain-able stateful workloads (due to tolerations) do not block node deletion
<ins>Also adds read RBAC permissions for `volumeattachment` objects. (Let me know if this should be a separate `fix` PR)</ins>
Running `FOCUS="StatefulSets" make e2etests` locally on cluster with and without modified Karpenter from [Karpenter PR 1294](https://github.com/kubernetes-sigs/karpenter/pull/1294). 
NOTE: The test `should run a disrupted stateful workload …
=> test: Ensure no 6+ minute delays for disrupted stateful workloads

website/content/en/preview/concepts/disruption.md, website/content/en/preview/concepts/nodepools.md
Fixes #N/A 
Adds documentation on TerminationGracePeriod for NodePool and adjusts some of the expireAfter docs. 
Testing here
=> docs: add terminationGracePeriod docs

charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/suite_test.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go, test/suites/nodeclaim/nodeclaim_test.go
Fixes #N/A 
This change updates our code so that we intentionally delete a NodeClaim when we know that the NodeClass is in a False state. This ensures that we retry the NodeClaim as quickly as possible by rescheduling it to another NodePool that has a NodeClaim that is ready.
=> chore: Update so NodeClassNotReady is returned when NodeClass is failing

website/content/en/preview/concepts/nodepools.md
Fixes #N/A 
Our docs currently suggest that we only need to set value for `consolidateAfter` on nodePool when `consolidationPolicy` is `WhenEmpty`. This is not true anymore. Updated the docs for the same.
NA
=> docs: Update comment associated with consolidateAfter

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/ec2nodeclass_validation_cel_test.go, pkg/providers/amifamily/windows.go
Fixes #N/A 
When using a Windows alias, the only version that may be specified is 'latest'. This PR moves this check from runtime to validation time via a CEL check.
`make presubmit` and `/karpenter snapshot`
=> chore: enforce Windows version via CEL

pkg/providers/amifamily/bootstrap/nodeadm.go, pkg/providers/launchtemplate/testdata/al2023_mime_userdata_merged.golden, pkg/providers/launchtemplate/testdata/al2023_shell_userdata_merged.golden, pkg/providers/launchtemplate/testdata/al2023_yaml_userdata_merged.golden, website/content/en/preview/concepts/nodeclasses.md
Fixes #N/A 
Changes AL2023's generated userData order to place the Karpenter generated config at the end of the MIME document. This change makes AL2023 consistent with the other AMI families (AL2, Bottlerocket, and Windows)
`make presubmit` and `/karpenter snapshot`
=> chore: consistent userData override ordering

pkg/providers/instancetype/types.go
We observed that `g2.xlarge` has `.EbsInfo.EbsOptimizedSupport == "default"`, but no `.EbsInfo.EbsOptimizedInfo`:
```
$ aws ec2 describe-instance-types --region us-west-2 --instance-types 'g2.xlarge' | jq '.InstanceTypes[0].EbsInfo'
{
"EbsOptimizedSupport": "default",
"EncryptionSupport": "supported",
"NvmeSupport": "required"
}
```
This can cause a nil pointer dereference when gathering instance info, following the support for EBS maximum bandwidth introduced in #5925 
```
{"level":"INFO","time":"2024-08-05T18:52:30.307Z","logger":"controller","message":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","commit":"490ef94","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"ut …
```
=> fix: Make sure EbsOptimizedInfo exists when selecting instances by EBS maximum bandwidth

.github/actions/e2e/install-karpenter/action.yaml, go.mod, go.sum
Fixes #N/A 
- Enable webhooks for the 0.34.x branch 
**How was this change tested?*
- N/A
=> ci: Enable webhooks for v0.34.x

pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, pkg/apis/v1/labels.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/status/ami.go, pkg/controllers/nodeclass/status/ami_test.go, website/content/en/preview/concepts/nodeclasses.md, website/content/en/preview/upgrading/v1-migration.md
Fixes #N/A 
Updates the EC2NodeClass conversion to successfully convert unpinned Ubuntu NodeClasses. This changes the failure mode from failing at conversion, to failing at NodeClass readiness. 
=> feat: convert unpinned Ubuntu EC2NodeClasses

test/pkg/environment/common/expectations.go, test/suites/termination/termination_grace_period_test.go
Fixes #N/A 
Deflakes termination Grace Period e2e tests that were failing, and speeds them up by directly deleting the nodeclaim rather than waiting for 90s expiration
make e2etests
=> test: deflake termination grace period tests

charts/karpenter-crd/values.yaml, go.mod, go.sum, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, pkg/apis/v1/labels.go, test/pkg/environment/common/environment.go, test/suites/chaos/suite_test.go, test/suites/consolidation/suite_test.go, test/suites/expiration/suite_test.go, test/suites/integration/emptiness_test.go, test/suites/integration/validation_test.go, test/suites/scale/deprovisioning_test.go
Fixes #N/A 
Backports #6699's conversion webhook updates, bumps sigs.k8s.io/karpenter, and disables webhooks in the CRD chart by default.
=> Ubuntu Backport and Version Bump v0.34.x

website/content/en/preview/concepts/nodeclasses.md
Fixes #N/A 
Updates the wording for the Ubuntu AMIFamily warning and includes an example. Additionally specifies that `alias` is mutually exclusive and may not be specified with any other fields.
N/A
=> docs: NodeClass Ubuntu and Alias Updates

charts/karpenter-crd/values.yaml, charts/karpenter/README.md, charts/karpenter/templates/_helpers.tpl, charts/karpenter/templates/post-install-hook.yaml, charts/karpenter/values.yaml, go.mod, go.sum, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, pkg/apis/v1/labels.go, test/pkg/environment/common/environment.go, test/suites/chaos/suite_test.go, test/suites/consolidation/suite_test.go, test/suites/expiration/suite_test.go, test/suites/integration/emptiness_test.go, test/suites/integration/validation_test.go, test/suites/scale/deprovisioning_test.go
Fixes #N/A 
Backports #6699's conversion webhook changes, bumps sigs.k8s.io/karpenter, and disables webhooks by default
=> Ubuntu Backport and Version Bump v0.33.x

charts/karpenter-crd/values.yaml, charts/karpenter/README.md, charts/karpenter/templates/_helpers.tpl, charts/karpenter/templates/post-install-hook.yaml, charts/karpenter/values.yaml, go.mod, go.sum, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, pkg/apis/v1/labels.go, test/pkg/environment/common/environment.go, test/suites/chaos/suite_test.go, test/suites/consolidation/suite_test.go, test/suites/expiration/suite_test.go, test/suites/integration/emptiness_test.go, test/suites/integration/validation_test.go, test/suites/scale/deprovisioning_test.go
Fixes #N/A 
- Backports 
- https://github.com/aws/karpenter-provider-aws/pull/6699 
- https://github.com/aws/karpenter-provider-aws/pull/6716
- bumps sigs.k8s.io/karpenter
=> Ubuntu Backport and Version Bump v0.36.x

go.mod, go.sum, test/suites/integration/conversion_webhook_test.go
Fixes #N/A 
- As part of the conversion webhooks, it is possible to apply the same resource multiple times and have the resource generation increase each time. Adding testing to make sure the resource generation does not increases for applying the same resource multiple times. 
=> test: Add testing to verify consistent generation for a no change update

website/content/en/docs/concepts/nodeclasses.md, website/content/en/docs/concepts/nodepools.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/preview/concepts/nodepools.md, website/content/en/v0.32/concepts/nodeclasses.md, website/content/en/v0.32/concepts/nodepools.md, website/content/en/v0.35/concepts/nodeclasses.md, website/content/en/v0.35/concepts/nodepools.md, website/content/en/v0.36/concepts/nodeclasses.md, website/content/en/v0.36/concepts/nodepools.md, website/content/en/v0.37/concepts/nodeclasses.md, website/content/en/v0.37/concepts/nodepools.md
Fixes #N/A
While reading the docs I stumbled upon broken URLs. It appears to be broken since [this move](https://github.com/aws/karpenter-provider-aws/pull/6609).
I ran this command to fix them: `for f in $(find . -type f -name '*.md'); do sed -i '' 's,https://github.com/aws/karpenter/blob/main/examples/v1beta1,https://github.com/aws/karpenter/blob/main/examples/v1,g' $f; done`
I clicked a new URL.
=> docs: Update URLs moved from v1beta1 to v1

test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
Private tests are currently failing because we are trying to pull the kubectl image from public ecr which can't work in private vpc.
Tested on my private cluster.
=> chore: update karpenter install script for private cluster testing

pkg/cache/cache.go, pkg/fake/ssmapi.go, pkg/providers/amifamily/al2.go, pkg/providers/amifamily/al2023.go, pkg/providers/amifamily/bottlerocket.go, pkg/providers/amifamily/windows.go, pkg/providers/ssm/provider.go
Fixes #N/A 
Reverts to using `ssm:GetParameter` over `ssm:GetParametersByPath` to increase granularity on caching.
TODO
=> chore: revert to using ssm:GetParameter

.github/workflows/e2e-matrix.yaml, .github/workflows/e2e-version-compatibility-trigger.yaml
Fixes #N/A 
- Limit the number of suites that run as part of our version compatibility testing. Prior to this change, the version compatibility workflow would create 3 suite (using [2 suites from our matrix job](https://github.com/aws/karpenter-provider-aws/blob/c7201b0a5c41befaf13ebe9bc84290878ac01dae/.github/workflows/e2e-matrix.yaml#L60) and upgrade suite). This PR will do two things: first reduce the number tests that are running at any given time from 18 suites to 12 suites, and reorder the test suites to reduce churn from similar operation correlating in one suite. 
- **Reducing the test suites from 18 -> 12:** Reducing the test runs to have at most 12 test suite running at a time. This will be to reduce the amount of transient errors due to throttling or issues …
=> chore: Limit parallelism on our GitHub action for version compatibility 

hack/toolchain.sh, pkg/cache/cache.go, pkg/operator/operator.go, pkg/providers/amifamily/ami.go, pkg/providers/ssm/provider.go, pkg/test/environment.go
=> feat: cache SSM values (v0.33.x)

hack/toolchain.sh, pkg/cache/cache.go, pkg/operator/operator.go, pkg/providers/amifamily/ami.go, pkg/providers/ssm/provider.go, pkg/test/environment.go
=> feat: cache SSM calls (v0.34.x)

hack/toolchain.sh, pkg/cache/cache.go, pkg/operator/operator.go, pkg/providers/amifamily/ami.go, pkg/providers/ssm/provider.go, pkg/test/environment.go
=> feat: cache SSM calls (v0.35.x)

pkg/cache/cache.go, pkg/operator/operator.go, pkg/providers/amifamily/ami.go, pkg/providers/ssm/provider.go, pkg/test/environment.go
=> feat: cache SSM calls (v0.36.x)

pkg/cache/cache.go, pkg/operator/operator.go, pkg/providers/amifamily/ami.go, pkg/providers/ssm/provider.go, pkg/test/environment.go
=> feat: cache SSM calls (v0.37.x)

test/suites/scheduling/suite_test.go
Fixes #N/A 
Updates the nvidia scheduling test to use AL2 over AL2023. This needed to be changed in light of #6726 since we will no longer use non-accelerated AMIs for GPU workloads with AL2023.
=> test: use AL2 for nvidia E2E test

pkg/providers/amifamily/bottlerocket.go, test/suites/ami/suite_test.go
Fixes #N/A 
Fixes a regression in #6726 to enable `v` prefixes for bottlerocket aliases. Additionally updates the E2E tests to ensure this doesn't regress again.
=> fix: allow v prefix for bottlerocket aliases

test/suites/scheduling/suite_test.go
Fixes #N/A 
Use AL2 for an accelerator test since AL2023 AMIs aren't compatible.
=> test: use AL2 for accelerator test

website/content/en/preview/upgrading/v1-migration.md
Fixes #N/A 
Updates the migration guide where needed to reflect that v0.33 and v0.34 both have a v prefix in their OCI release.
N/A
=> docs: update migration guide for variable release prefix

website/content/en/docs/reference/settings.md, website/content/en/preview/reference/settings.md, website/content/en/v0.36/reference/settings.md, website/content/en/v0.37/reference/settings.md
Fixes #N/A 
- Update docs to indicate that spot-to-spot consolidation is an alpha feature flag 
=> docs: Update spot-to-spot consolidation feature flag to be alpha

website/content/en/docs/troubleshooting.md, website/content/en/preview/troubleshooting.md, website/content/en/v1.0/troubleshooting.md
Fixes #N/A 
Remove references to Karpenters v1alphaX apis from the troubleshooting guide.
N/A
=> docs: drop alpha refs in troubleshooting guide

test/hack/resource/clean/main.go
Fixes #N/A 
- Currenlty no metric is fired as part of our sweeper when no resources is being cleaned up. Adjusting script to add in zeros when we are not cleaning resources. 
- N/A
=> ci: Fire metric when no resources is cleaned

go.mod, go.sum, pkg/cloudprovider/cloudprovider.go, pkg/fake/cloudprovider.go
Fixes #N/A 
Updates to bring in https://github.com/kubernetes-sigs/karpenter/pull/1574
here
=> chore: update gomod and add cloudprovider method

website/content/en/docs/upgrading/v1-migration.md, website/content/en/preview/upgrading/v1-migration.md, website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
We orchestrate releases by pushing tags, which triggers a github action to create a PR to modify the docs. This means that referencing the raw github files at the tagged commit for the `docs` folder will have missed any docs updates added during the release automation. This updates it to use `preview` so that the cloud formation references what was staged for each release, which was eventually brought in through release automation.
Looking at the links manually, seeing CFN updates for v1 that were expected only in the preview link
=> docs: fix cloud formation resources

website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/docs/getting-started/migrating-from-cas/scripts/step10-create-nodepool.sh, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/preview/getting-started/migrating-from-cas/scripts/step10-create-nodepool.sh, website/content/en/v1.0/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/v1.0/getting-started/migrating-from-cas/scripts/step10-create-nodepool.sh
Fixes #N/A 
Nodepool's yaml in Getting Started doesn't have a v1 spec
Deployed NodePool.yaml and checked
=> docs: invalid Getting Started NodePool yaml

website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh, website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh, website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step03-iam-cloud-formation.sh, website/content/en/docs/getting-started/migrating-from-cas/scripts/step09-deploy.sh, website/content/en/v1.0/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster-fargate.sh, website/content/en/v1.0/getting-started/getting-started-with-karpenter/scripts/step02-create-cluster.sh, website/content/en/v1.0/getting-started/getting-started-with-karpenter/scripts/step03-iam-cloud-formation.sh, website/content/en/v1.0/getting-started/migrating-from-cas/scripts/step09-deploy.sh
Fixes #6790
Fixes references that were erroneously overridden from preview to v1.0.0
- Viewed the preview docs
=> docs: Fix doc link references to preview

website/content/en/docs/upgrading/v1-migration.md, website/content/en/preview/upgrading/v1-migration.md, website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
the previous order was using variables before they were defined
with the preview tab 
=> fix: right order to environment variable exports

charts/karpenter/templates/post-install-hook.yaml
The default image for the post-install hook runs exclusively on `amd64`. Without the ability to define a `nodeSelector`, scheduling it onto the appropriate node pool(s) is challenging. This pull request introduces support for `nodeSelector` in the post-install hook. To maintain consistency, I have extended the existing approach used for `tolerations`, which inherit their values from the deployment, rather than defining a new field.
This change is not associated with any existing issues. If you find it irrelevant, I will close it.
Thank you in advance for reviewing.
The chart was packaged and pushed to our internal registry. …
=> chore: add support for `nodeSelector` to post-install hook

website/content/en/docs/getting-started/migrating-from-cas/_index.md, website/content/en/preview/getting-started/migrating-from-cas/_index.md, website/content/en/v1.0/getting-started/migrating-from-cas/_index.md
Fixes #N/A 
The current docs still link to examples in a folder `v1beta1` that doesn't exist anymore. Changed the link to the correct path `v1`.
I searched for `v1beta1` in the website folder to find other occurrences and it's still often used in examples. That might be worth checking for consistency's sake but shouldn't cause issues.
<sup>p.s. congrats on the big release!</sup>
Clicked the links :^)
=> docs: fix example link to example NodePools

pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, pkg/apis/v1/labels.go
Fixes #6776 
Ensures that the version pin for an alias is maintained via a compatibility annotation applied to the v1beta1 nodeclass.
`make test`
=> fix: ensure alias version isn't dropped round-trip

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md
Clarify which terminationGracePeriod we are talking about. The page already talks about the pod's terminationGracePeriod so in this sentence it's not clear what terminationGradePeriod is referenced. 
I assume this kind of change does not have to go to `preview/`. 
Fixes #N/A 
- [] No
=> docs: clarify terminationGracePeriod

hack/docs/compatibilitymatrix_gen/compatibility.yaml, hack/docs/instancetypes_gen/main.go, hack/docs/version_compatibility_gen/main.go, website/content/en/preview/reference/instance-types.md, website/content/en/preview/upgrading/compatibility.md
Fixes #6606
Add support for pulling instance type data from different regions. This allows us to pull the `c7i-flex` instance type which isn't available in `us-east-1` but is available in `us-west-2`
`make docgen`
=> Add support for pulling instance types from multiple regions

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1beta1/ec2nodeclass.go, pkg/cloudprovider/cloudprovider.go, pkg/providers/instance/instance.go
Fixes #N/A 
This updates Karpenter Provider to use the latest version of go, `go1.23`
=> chore: Bump go.mod to use go 1.23

test/pkg/environment/common/expectations.go, test/pkg/environment/common/setup.go
Fixes #N/A 
Added test that would run after each test to ensure that we are not leaking any leases.
Ran test on my local cluster
=> test: monitor leaked node lease using tests

charts/karpenter/templates/role.yaml, charts/karpenter/templates/rolebinding.yaml, go.mod, go.sum
Fixes #N/A 
We intend to drop the node lease garbage collection controller - https://github.com/kubernetes-sigs/karpenter/pull/1586
This PR removes the RBAC permissions for interacting with leases.
=> chore: Remove RBAC permissions for node lease garbage collection

.golangci.yaml, pkg/providers/instancetype/suite_test.go, test/pkg/environment/common/monitor.go
Fixes #N/A 
Replace `exportloopref` with `copyloopvar` (see https://go.dev/blog/loopvar-preview for more detail)
```console
cd . && golangci-lint run 
WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
```
=> ci: Enable `copyloopvar` in linter

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, charts/karpenter-crd/values.yaml, hack/mutation/conversion_webhooks_injection.sh
Fixes #N/A 
Allow `webhook.serviceNamespace` override in conversion block
`helm upgrade --install karpenter-crd ./charts/karpenter-crd
=> chore: Alow service namespace override

website/content/en/docs/concepts/nodeclasses.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/v1.0/concepts/nodeclasses.md
Fixes #N/A 
Add details for how to discover available alias versions for AL2, AL2023, and Bottlerocket.
N/A
=> docs: detail how to discover alias versions

charts/karpenter-crd/values.yaml, charts/karpenter/values.yaml
Fixes #N/A 
Fixes an issue where k8s expects a conversion webhook is enabled (but it isn't) due to applying CRDs from the repo but the webhook.
Make presubmit.
=> fix: enable webhooks by default

website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/docs/reference/cloudformation.md, website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/preview/reference/cloudformation.md, website/content/en/v0.32/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.32/reference/cloudformation.md, website/content/en/v0.36/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.36/reference/cloudformation.md, website/content/en/v0.37/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.37/reference/cloudformation.md, website/content/en/v1.0/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v1.0/reference/cloudformation.md
Fixes #6843
This change fixes `User <role> is not authorized to perform: iam:PassRole on resource...` error in AWS China
Manually in aws-cn partition.
=> fix: "iam:PassRole" defined in CFN to work properly in AWS China

website/content/en/docs/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/docs/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh, website/content/en/docs/reference/cloudformation.md, website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/preview/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh, website/content/en/preview/reference/cloudformation.md, website/content/en/v0.36/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.36/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh, website/content/en/v0.36/reference/cloudformation.md, website/content/en/v0.37/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v0.37/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh, website/content/en/v0.37/reference/cloudformation.md, website/content/en/v1.0/getting-started/getting-started-with-karpenter/cloudformation.yaml, website/content/en/v1.0/getting-started/migrating-from-cas/scripts/step04-controller-iam.sh, website/content/en/v1.0/reference/cloudformation.md
Fixes #N/A 
`ec2:DescribeAvailabilityZones` permission has not been needed for a little bit since we dropped this call from our GetInstanceTypes() call path. We can remove this READ permission from our policy
=> chore: Drop `ec2:DescribeAvailabilityZones` permissions

charts/karpenter/templates/_helpers.tpl, charts/karpenter/templates/deployment.yaml
Fixes #N/A 
Backports logOutputPath and logErrorOutputPath fixes.
=> fix: backport consume log path values (#6875)

pkg/controllers/nodeclaim/garbagecollection/controller.go
Fixes #N/A 
Fix conflicting `nodeclaim.garbagecollection` controller name to now be `instance.garbagecollection`
=> fix: Fix conflicting nodeclaim.garbagecollcation controller name

test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
- Fix e2e test matrix script syntax
You can reproduce locally with the following:
Current, throws error:
```sh
#!/bin/bash
if (( "$PRIVATE_CLUSTER" == 'true' )); then
echo "Private cluster is enabled"
else
echo "Private cluster is disabled"
fi
```
Fixed, no error:
```sh
#!/bin/bash
if (( "$PRIVATE_CLUSTER" == "true" )); then
echo "Private cluster is enabled"
else
echo "Private cluster is disabled"
fi
```
=> chore: Fix e2e test matrix script syntax

test/pkg/debug/node.go, test/pkg/debug/nodeclaim.go, test/pkg/debug/pod.go
Fixes #N/A 
Fix failures in the test monitor that were being caused by conflicting controller names. These checks were red herrings because the names are being stored as a global but we are creating multiple managers within a single process.
=> test: Fix failures in the test monitor

test/suites/chaos/suite_test.go
Fixes #N/A 
Fix duplicate name error on chaos testing
=> test: Fix duplicate controller name on chaos testing

test/pkg/environment/common/expectations.go, test/suites/interruption/suite_test.go, test/suites/nodeclaim/nodeclaim_test.go
Fixes #N/A 
This change ensures that we check the deletion timestamp of the node rather than waiting for the node to be gone within a 2m timeframe. This can flake often now due to the change that we made in https://github.com/kubernetes-sigs/karpenter/pull/1195
=> test: Fix interruption testing to check node deletion

pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
This change always disables instance metadata tags. Not passing this setting _explicitly_ to the instance launch can cause an account that [has configured account defaults for instance metadata settings](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html#instance-metadata-options-order-of-precedence) to override the instance default. If the account default has IMDS tags set to `enabled`, EC2 will use this, causing Karpenter to fail to launch instances with
```
- lastTransitionTime: "2024-09-15T05:00:09Z"
message: 'creating instance, with fleet error(s), InvalidParameterValue: ''kubernetes.io/cluster/scale-test''
is not a valid tag key. Tag keys must match pattern ([0-9a-zA-Z\\-_+=,.@:]{1,255}),
and must not be a …
```
=> chore: Always disable instance metadata tags

test/suites/integration/tags_test.go
Fixes #N/A 
Tests that involve checking tags on managed instance profiles for private cluster are failing. This happens because we create and manage instance profiles manually for private clusters. Skipping these tests.
`manually tested`
=> test: fix private cluster test

website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/v0.32/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/v0.36/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/v0.37/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh, website/content/en/v1.0/getting-started/getting-started-with-karpenter/scripts/step12-add-nodepool.sh
Fixes #N/A 
Updates the getting started guide nodepool to use od, to ensure users can test without having to worry about spot capacity
=> docs: update getting started guide nodepool to use od

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/providers/launchtemplate/suite_test.go, pkg/utils/utils.go
Fixes #7011
Fixes #6890
Fixes #6979
This PR fixes a bug where both `GetKubeletConfigurationWithNodeClaim` and `GetKubeletConfigurationWithNodePool` were returning the `nodeClass.Spec.Kubelet` back to the caller when Kubelet was specified and there was no Kubelet compatibility annotation.
This would be fine; however, this call returned back the original pointer for the Kubelet data -- meaning that any caller could then mutate the original data for other callers without knowing it. In this case, the launch template resolver was inadvertently mutating the maxPods data across instance type combinations, leading to incorrect maxPods values being specified sometimes.
- Print-lining and validating that we are no longer seeing …
=> fix: Fix pointer mutation causing incorrect maxPods values

charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/drift.go, pkg/controllers/nodeclass/hash/controller.go, pkg/controllers/nodeclass/hash/suite_test.go, pkg/utils/utils.go, test/suites/scheduling/suite_test.go
Fixes https://github.com/aws/karpenter-provider-aws/issues/6987
Add a test to validate that we properly propagate the kubelet configuration annotation on the NodeClaim during NodeClaim creation
=> test: Add testing for propagating the kubelet annotation on the NodeClaim

Makefile, charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, hack/toolchain.sh, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1beta1/ec2nodeclass.go
Fixes #N/A 
Updating gomod for cherry pick for 1662
testing here
=> chore: update gomod for cherrypick

pkg/cloudprovider/cloudprovider.go, test/pkg/environment/common/expectations.go, test/suites/nodeclaim/garbage_collection_test.go
Fixes #N/A 
Fix `EventuallyExpectNotFound` not having a `Should(Succeed())`
=> test: Fix NotFound check in EventuallyExpectNotFound

pkg/controllers/nodeclass/status/ami_test.go, pkg/providers/amifamily/types.go
Fixes #N/A 
- Correct the AMI selector label requirements for NVIDIA and Neuron variants
- Instances backed with NVIDIA GPUs should have the label `karpenter.sh/instance-gpu-count`
- Instances backed with Neuron devices should have the label `karpenter.sh/instance-accelerator-count`
- `make test`
=> fix: Correct the AMI selector label requirements for NVIDIA and Neuron variants

pkg/providers/amifamily/resolver.go, pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
Add launch template test expectations from #7020
Thanks to @jigisha620 and @jmdeal for tracking down this same issue that was plaguing `release-v1.0.x` in `main`
=> test: Add launch template test expectations from #7020

go.mod, go.sum, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, test/suites/integration/migration_test.go
=> chore: add e2es and drop annotation on conversion v0.33.x

go.mod, go.sum, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, test/suites/integration/migration_test.go
=> chore: add e2es and drop annotation on conversion v0.34.x

go.mod, go.sum, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, test/suites/integration/migration_test.go
=> chore: add e2es and drop annotation on conversion v0.35.x

go.mod, go.sum, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, test/suites/integration/migration_test.go
=> chore: add e2es and drop annotation on conversion v0.37.x

go.mod, go.sum, pkg/apis/v1/ec2nodeclass_conversion.go, pkg/apis/v1/ec2nodeclass_conversion_test.go, test/suites/integration/migration_test.go
=> chore: add e2es and drop annotation on conversion v0.36.x

charts/karpenter/README.md, charts/karpenter/values.yaml, website/content/en/preview/reference/settings.md, website/content/en/v0.32/reference/settings.md, website/content/en/v0.36/reference/settings.md, website/content/en/v0.37/reference/settings.md, website/content/en/v1.0/reference/settings.md
Fixes [#6612 ](https://github.com/aws/karpenter-provider-aws/issues/6612)
Just a minor change in the docs with a simple explanation. Happy to revisit the wording if required. 
By running `make website` and checking the changed line is correct.
=> docs: modifying doc on vmMemoryOverheadPercent

test/suites/integration/termination_test.go, test/suites/nodeclaim/garbage_collection_test.go, test/suites/nodeclaim/nodeclaim_test.go
Fixes #N/A 
Fixes issue where create fleet calls can fail. This will only fail in the test suite due to filtering being done on the scheduler side, so it only affects standalone nodeclaims (which are unsupported).
E2Es
=> fix: update test to reduce create fleet payload size v0.35.x

test/suites/integration/termination_test.go, test/suites/nodeclaim/garbage_collection_test.go, test/suites/nodeclaim/nodeclaim_test.go
Fixes #N/A 
Fixes issue where create fleet calls can fail. This will only fail in the test suite due to filtering being done on the scheduler side, so it only affects standalone nodeclaims (which are unsupported).
E2Es.
=> fix: update test to reduce create fleet payload size v0.36.x

.github/workflows/e2e-matrix.yaml
=> ci: Update Commit used for the Upgrade tests for release-v0.36.x

pkg/providers/instancetype/instancetype.go
Fixes #N/A 
Adds an optional mutator to the instance profile provider, allowing up-the-tree mutations without additional locking
=> feat: add optional mutator to instancetype provider

test/suites/integration/scheduling_test.go
Fixes #N/A 
Overrides nodeclass AMI to be AL2 for the GPU test since AL2023 GPU instances are unsupported on v0.36.x.
E2E
=> fix: fix gpu label test v0.36.x

test/suites/integration/scheduling_test.go
Fixes #N/A 
Overrides nodeclass AMI to be AL2 for the GPU test since AL2023 GPU instances are unsupported on v0.35.x.
E2Es
=> fix: fix gpu label test v0.35.x

.github/actions/e2e/install-karpenter/action.yaml, .github/actions/e2e/run-tests-private-cluster/action.yaml, .github/actions/e2e/setup-cluster/action.yaml, .github/actions/install-deps/action.yaml, .github/workflows/ci-test.yaml, .github/workflows/e2e-matrix.yaml, .github/workflows/e2e-upgrade.yaml, .github/workflows/e2e-version-compatibility-trigger.yaml, .github/workflows/e2e.yaml, go.mod, go.sum, pkg/providers/version/version.go, website/hugo.yaml
Fixes #N/A 
Update CI to use 1.31 and drop 1.25
here
=> chore: update support for 1.31

charts/karpenter/templates/clusterrole-core.yaml, cmd/controller/main.go, go.mod, go.sum, pkg/controllers/controllers.go, test/suites/integration/migration_test.go
Fixes #N/A 
Fixes caches failing to sync on latest patch when webhooks are disabled by not starting migration controllers when webhooks are disabled. This also moves `crd/status` `patch` to a conditional block and scopes `crd` `update` to only Karpenter CRDs.
=> fix: enable migration controllers if webhooks are enabled

charts/karpenter/templates/_helpers.tpl
Fixes #7084
Dropping prefix `v` from tag from helpers.tpl
`manually tested`
=> chore: Remove prefix from chart.appversion in helpers.tpl

test/suites/ami/suite_test.go
Fixes #N/A 
Bumps version pins in the AMI suite_test to pin to available 1.31 AMIs
=> test: bump pinned AMIs for 1.31

pkg/providers/amifamily/al2023.go, pkg/providers/amifamily/bootstrap/bootstrap.go, pkg/providers/amifamily/bootstrap/bottlerocket.go, pkg/providers/amifamily/bootstrap/eksbootstrap.go, pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
We had the ENILimitedPodDensity option that's continuing to be used in the code. This value cannot be any value other than `false` so it no longer makes sense to have this as an option.
=> chore: Drop ENILimitedPodDensity option

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md
Fixes: disruption.md consolidationPolicy value cases 
`whenEmpty` or `whenEmptyOrUnderutilized` are unsupported values for `spec.disruption.consolidationPolicy`
=> fix: disruption.md consolidationPolicy value cases

pkg/providers/instancetype/instancetype.go
Fixes #N/A 
The resolver can return a nil instance type in some cases, although this is controlled by the cloud provider, we should just not panic in this case.
locally
=> chore: don't panic for a nil instance type

go.mod, go.sum
Fixes #N/A 
Pulls in https://github.com/kubernetes-sigs/karpenter/pull/1735
locally and presubmit
=> chore: update gomod to bring in ignore terminating nodes in budgets

test/suites/integration/scheduling_test.go
Fixes #N/A 
Wait for the Node's to be initialized in the zone-id scheduling tests before inspecting labels. This fix was already taken into main: https://github.com/aws/karpenter-provider-aws/pull/6493
=> test: wait for node intialization in zone-id tests

test/pkg/environment/common/expectations.go, test/suites/consolidation/suite_test.go, test/suites/drift/suite_test.go
Fixes #N/A 
Consolidation e2e budget tests were racing, because we asserted too tightly a certain number of nodes terminating, existing, and non-draining, where we don't consider nodes that are terminating against the budget. This modifies our assertions to be looser so that they're not racey, and assert how many disruptions we're currently seeing, and accounts for the change in terminating.
=> test: fix consolidation test races

.github/workflows/e2e.yaml, Makefile, charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
Fixes #N/A 
Enables smoke test for webhooks for E2E testing. This coerces the action from a string to bool
=> fix: smoke test for webhook e2e

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter/templates/deployment.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml
Fixes #N/A 
Updates the logic to disable the helm chart in the Karpenter deployment to reflect the new default upstream when the environment variable isn't set.
Applying Karpenter with the updated helm chart with webhooks disabled.
=> fix(0.37.x): disable webhooks appropriately in chart

pkg/providers/instancetype/instancetype.go
This reverts commit e07b37d277e733fecb827dd69fba1fe2bb23a3e0.
Fixes #N/A 
Reverting this since we should enforce an invariant that the cloud provider returns a real instance type. This prevents the CP from implementing a fix to return a nil instance type if an instance type shouldn't be used. We should opt to just mark all of the offerings as unavailable. But still allow it to be discovered. This allows us to not provision nodes that have this instance type, but still allow us to drift it if it no longer appears in describeinstancetypes
=> Revert "chore: don't panic for a nil instance type (#7144)"

test/suites/webhooks/suite_test.go
=> fix: simplify e2e for webhooks

charts/karpenter/templates/deployment.yaml
=> cherry-pick(0.35.x): disable webhooks appropriately in chart (#7177)

.github/actions/e2e/install-karpenter/action.yaml, .github/actions/e2e/setup-cluster/action.yaml, .github/workflows/e2e-matrix.yaml, .github/workflows/e2e.yaml, test/suites/webhooks/suite_test.go
Fixes #N/A 
Backports webhook smoke test.
=> fix: Backport webhook smoke test v0.35.x

pkg/providers/amifamily/ami.go
Fixes #N/A 
In the event of an AMI deprecation, we may not discover the new SSM parameter for up to 24 hours. Rather than failing to provision for those 24 hours, we'll continue to discover and use the deprecated AMI. This only impacts those using Karpetner's automatic AMI upgrade system which is not meant for production workloads.
=> fix(0.33.x): discover deprecated EKS optimized AMIs

pkg/providers/amifamily/ami.go
Fixes #N/A 
In the event of an AMI deprecation, we may not discover the new SSM parameter for up to 24 hours. Rather than failing to provision for those 24 hours, we'll continue to discover and use the deprecated AMI. This only impacts those using Karpetner's automatic AMI upgrade system which is not meant for production workloads.
=> fix(0.34.x): discover deprecated EKS optimized AMIs

pkg/providers/amifamily/ami.go
Fixes #N/A 
In the event of an AMI deprecation, we may not discover the new SSM parameter for up to 24 hours. Rather than failing to provision for those 24 hours, we'll continue to discover and use the deprecated AMI. This only impacts those using Karpenter's automatic AMI upgrade system which is not meant for production workloads.
=> fix(0.35.x): discover deprecated EKS optimized AMIs

pkg/providers/amifamily/ami.go
Fixes #N/A 
In the event of an AMI deprecation, we may not discover the new SSM parameter for up to 24 hours. Rather than failing to provision for those 24 hours, we'll continue to discover and use the deprecated AMI. This only impacts those using Karpetner's automatic AMI upgrade system which is not meant for production workloads.
=> fix(0.36.x): discover deprecated EKS optimized AMIs

pkg/providers/amifamily/ami.go
Fixes #N/A 
In the event of an AMI deprecation, we may not discover the new SSM parameter for up to 24 hours. Rather than failing to provision for those 24 hours, we'll continue to discover and use the deprecated AMI. This only impacts those using Karpetner's automatic AMI upgrade system which is not meant for production workloads.
=> fix(0.37.x): discover deprecated EKS optimized AMIs

test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
Testing CRD pin to use CRD where v1 has not been added.
=> fix: chart snapshot for webhook test v0.37.x

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/providers/amifamily/ami.go, pkg/providers/amifamily/types.go
Fixes #N/A 
In the event of an AMI deprecation, we may not discover the new SSM parameter for up to 24 hours. Rather than failing to provision for those 24 hours, we'll continue to discover and use the deprecated AMI. This only impacts those using Karpenter's automatic AMI upgrade system which is not meant for production workloads.
=> fix: discover deprecated EKS optimized AMIs

test/suites/integration/extended_resources_test.go
Fixes #N/A 
- Remove AL2 `AMISelectorTerms` pin from e2e tests now that AL2023 accelerated AMIs are available
=> chore: Remove AL2 `AMISelectorTerms` pin from e2e tests now that AL2023 accelerated AMIs are available

pkg/providers/instance/instance.go
Fixes #N/A 
Adding error logs for instance provider create call.
`manually tested`
=> Adding logs to instance provider create

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/providers/amifamily/ami.go
Fixes #N/A 
Corrects the check for latest alias when determining if we should discover deprecated AMI.
=> fix: correctly check for latest alias

go.mod
Fixes #N/A 
Pick up latest minor 1.23 release to address security vulnerabilities
https://go.dev/doc/devel/release#go1.23.
Specifically it addresses these:
```
% grype public.ecr.aws/karpenter/controller:1.0.6@sha256:25ec56d5bc718b213a648c0c64360a3be7fbe885b79905c73b77f68295352e9b
✔ Vulnerability DB                [no update available]
✔ Parsed image                                                                                     sha256:8a609f695a1dd5db4c85aab9e85fe97ac55b062f639643404c9cd67f04c6592a
✔ Cataloged contents                                                                                      ce005ceecbcc8627c0ecc91d767ea177b38db057a34fcbe2bc520e2881278308
├── ✔ Packages                        [99 packages]
├── ✔ File digests                    [1,128 files] …
```
=> chore: upgrade to go 1.23.2

pkg/providers/pricing/zz_generated.pricing_aws_cn.go
Fixes #7322
Generating new pricing data for aws-cn partition.
NA
=> generate pricing data for aws-cn

pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go, test/suites/ipv6/suite_test.go
Fixes #N/A 
By provisioning a v6 prefix during launching a node, we can save all complex IP management from IPAM. Since a static v6 prefix is sufficient and simpler, we want to add it to LT creation.
To set `PrimaryIPv6` to `true` will unblock users as https://github.com/aws/containers-roadmap/issues/1653
=> Feat: Provisioning IPv6 prefix to LT if cluster is IPv6

test/hack/e2e_scripts/install_karpenter.sh
Fixes #N/A 
When installing the CRD chart for the webhook test, we must include the v prefix in the version. Otherwise, we fail open during cluster creation and install the CRDs included in the main chart (which include the webhook stanza).
=> ci: include v prefix when install CRD chart

pkg/controllers/providers/instancetype/capacity/controller.go, pkg/providers/instancetype/instancetype.go
… from controller
Fixes #N/A 
Passing nodeclaim and nodeclass to UpdateInstanceTypeCapacityFromNode from controller
make presubmit
=> Passing nodeclaim and nodeclass to UpdateInstanceTypeCapacityFromNode

pkg/providers/instanceprofile/suite_test.go, pkg/test/nodeclass.go
Fixes #N/A 
This PR adds a test which ensures that no instance profile tags are added if InstanceProfileTags() returns empty map.
`make verify`
=> test: Add test for instance profile tags

test/suites/integration/tags_test.go
Fixes #N/A 
Dropping test for adding eks:eks-cluster-name tag key after restart in response to the change made here - https://github.com/aws/karpenter-provider-aws/commit/8ae2b8c79f11d292e9b5d3f36e8f04fe6a1c35d5
NA
=> test: drop test for adding eks:eks-cluster-name tag key after restart

pkg/apis/v1/labels.go, pkg/cloudprovider/cloudprovider.go, pkg/controllers/nodeclass/termination/suite_test.go, pkg/fake/utils.go, pkg/providers/instance/instance.go, pkg/providers/instance/suite_test.go, pkg/providers/launchtemplate/launchtemplate.go, website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Add `getTags` function to the CloudProvider Create call.
This change also drops the Managed Launch Template Key `karpenter.k8s.aws/cluster` since this key is no longer necessary with the use of `eks:eks-cluster-name`
=> chore: Drop `karpenter.k8s.aws/cluster` tag from launch templates

pkg/apis/v1/labels.go, pkg/controllers/nodeclaim/tagging/controller.go, pkg/controllers/nodeclaim/tagging/suite_test.go, pkg/providers/instance/instance.go, pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Update our `labels.go` to have defined tag variables in it. This cleans-up a weird cross-over that we had between labels and tags where it was difficult to delineate what a change in one would cause to the other
=> chore: Use defined tag variables in `labels.go`

pkg/providers/instance/instance.go
Fixes #N/A 
If `DescribeInstances` fails to return any response, we were checking the error in the wrong order. This also ensures that we are filtering by the correct tag key
=> fix: Fix error checking ordering for DescribeInstances

go.mod, go.sum, pkg/cloudprovider/cloudprovider.go, pkg/providers/instance/instance.go
Fixes #N/A 
Update error returned by `cloudprovider.Create()` to use upstream CreateError.
`make test`
=> chore: Update error returned by cloudprovider.Create()

pkg/cloudprovider/cloudprovider.go
Fixes #N/A 
This tosses out `kubernetes.io/` prefixed tags that are applied when bypassing CRD validation. Note that it does not filter out `eks:eks-cluster-name` because we overwrite that via static tags.
local CRD editing and launch instance tag validation:
```
map[eks:eks-cluster-name:<other-cluster-name> kubernetes.io/cluster/<other-cluster-name>:owned]
map[eks:eks-cluster-name:<other-cluster-name>]
```
=> feat: add nodeclass tag validation during instance create

charts/karpenter/templates/clusterrole-core.yaml, pkg/controllers/controllers.go
Fixes #N/A 
- Adding metrics based on node events
- Metric: `operator_node_event_total`
- N/A
=> feat: Add node events based metrics

pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go, test/suites/ipv6/suite_test.go
Fixes #N/A 
Since EC2 doesn't support primaryIPv6 and IPv6 prefix, we have to switch to IPv6 /128 address with primary IPv6 as true. Also we should remove the `AssociatePublicIPAddress` from the if check since the provisioned network interface by default with a instance won't be different from what we set in the if block.
=> replace ipv6 prefix with ipv6 address

pkg/cloudprovider/cloudprovider.go, test/suites/integration/repair_policy_test.go
Fixes #N/A 
- Dropping support for DiskPressure and MemoryPressure
- N/A
=> chore: Only support `Ready` Node Condition for Node Repair

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md
=> docs: Updated the hyperlink for nodepool disruption budgets to point to the right one

pkg/apis/v1/labels.go, pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Move the launch template name prefix to the apis group along with other portions of the API -- like the tag keys
`make presubmit
=> chore: Move the launch template name prefix into api labels

pkg/controllers/controllers.go, pkg/controllers/nodeclaim/tagging/controller.go, pkg/controllers/nodeclaim/tagging/suite_test.go
Fixes #N/A 
Adds a management check to the tagging controller.
integration testing
=> fix: only tag owned resources

website/content/en/docs/reference/metrics.md, website/content/en/preview/reference/metrics.md, website/content/en/preview/upgrading/upgrade-guide.md, website/content/en/v1.0/reference/metrics.md
Fixes #N/A 
Updated metrics in documentation
=> docs: updated metrics in documentation

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/ec2nodeclass_status.go
Fixes #N/A 
- fix a typo
- N/A
=> fix: fix typos on the apisv1

website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
Updates the weight of one of the headers to match its peers.
=> docs: fix header type in migration guide

website/content/en/docs/upgrading/upgrade-guide.md, website/content/en/preview/upgrading/upgrade-guide.md, website/content/en/v0.32/upgrading/upgrade-guide.md, website/content/en/v0.37/upgrading/upgrade-guide.md, website/content/en/v1.0/upgrading/upgrade-guide.md, website/content/en/v1.1/upgrading/upgrade-guide.md
Fixes #N/A 
Updates the CRD upgrade description to emphasize the link between CRD version and provider version, and codifies the recommendation to use the independent CRD chart.
=> docs: update CRD note in upgrade guide

website/content/en/docs/concepts/nodepools.md, website/content/en/preview/concepts/nodepools.md, website/content/en/v0.32/concepts/nodepools.md, website/content/en/v0.37/concepts/nodepools.md, website/content/en/v1.0/concepts/nodepools.md, website/content/en/v1.1/concepts/nodepools.md
Fixes #N/A 
Updates outdated ICE cache timeout references from 45s to 3m.
=> docs: update ICE cache timeout

website/content/en/docs/troubleshooting.md, website/content/en/preview/troubleshooting.md, website/content/en/v0.32/troubleshooting.md, website/content/en/v0.37/troubleshooting.md, website/content/en/v1.0/troubleshooting.md, website/content/en/v1.1/troubleshooting.md
Fixes #N/A 
Adds a note to the scheduling docs to clarify that eligible domains for TSC are based on the pod's requirements, not the requirements of compatible NodePools.
=> docs: add note on domain discovery for TSC

hack/docs/metrics_gen/main.go, website/content/en/docs/reference/metrics.md, website/content/en/preview/reference/metrics.md
=> docs: fix karpenter service namespace

website/content/en/docs/getting-started/getting-started-with-karpenter/scripts/step15-apply-flowschemas.sh, website/content/en/preview/getting-started/getting-started-with-karpenter/scripts/step15-apply-flowschemas.sh, website/content/en/v0.37/getting-started/getting-started-with-karpenter/scripts/step15-apply-flowschemas.sh, website/content/en/v1.0/getting-started/getting-started-with-karpenter/scripts/step15-apply-flowschemas.sh, website/content/en/v1.1/getting-started/getting-started-with-karpenter/scripts/step15-apply-flowschemas.sh
Fixes #N/A 
FlowControl API moved to v1 since v1.29, and will be removed till v1.32. [reference](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-32)
To remediate the issue comes from upgrade insights report
```
Migrate manifests and API clients to use the flowcontrol.apiserver.k8s.io/v1 API version, available since v1.29
```
=> chore: update the flowschema api version from v1beta3 to v1

pkg/controllers/nodeclass/status/ami.go, pkg/controllers/nodeclass/status/securitygroup.go, pkg/controllers/nodeclass/status/subnet.go, pkg/providers/amifamily/ami.go
Fixes #N/A 
if users omit the necessary tags and later add them, we need to reprocess the information
=> fix: re-reconcile the nodeclass status

pkg/apis/v1/ec2nodeclass_status.go, pkg/controllers/nodeclass/status/ami.go, pkg/controllers/nodeclass/status/ami_test.go, test/suites/ami/suite_test.go, test/suites/drift/suite_test.go, website/content/en/preview/concepts/nodeclasses.md
Fixes #N/A 
- Dropping the deprecated AMI status condition. We are in the process considering mechanisms to communicate nodeclass that are in a "Degraded" state, but are still able to provision capacity. The would like a general status condition that is able to describe multiple modes of degradation similar to deprecated AMIs 
=> chore: Drop deprecated AMI status condition 

.github/workflows/stale.yaml
Fixes #N/A 
Our triage process needs to get solidified. One thing that we want to do is ensure that we signal that issues should be staled out either because the issue has not been responded to and needed information (`triage/needs-information`) or because the issue has been marked as solved (`triage/solved`).
=> chore: Only stale triage/needs-information and triage/solved issues

go.mod, go.sum
Fixes #N/A 
Updates the gomod
points to the same underlying commit
=> chore: update go mod for v1.1.1

pkg/cloudprovider/cloudprovider.go, test/suites/integration/repair_policy_test.go
Fixes https://github.com/aws/karpenter-provider-aws/issues/7479
- Add Unknown status for the Kubelet Ready condition as a state to repair nodes. 
=> chore: Add Unknown Kubelet Ready condition into Repair Policies 

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md, website/content/en/v1.1/concepts/disruption.md
Fixes #N/A 
Update docs to indicate do-not-disrupt does not block expiration
NA
=> docs: Update docs to indicate do-not-disrupt does not block expiration

website/content/en/docs/troubleshooting.md, website/content/en/preview/troubleshooting.md, website/content/en/v1.0/troubleshooting.md, website/content/en/v1.1/troubleshooting.md
The Troubleshooting docs were out of date with v1.0+ (as per [this post](https://aws.amazon.com/blogs/containers/announcing-karpenter-1-0/) mentioning deprecation of the `do-not-evict` annotation.)  Figured I'd clean that up to reduce confusion!
NOTE: I'm not entirely sure how this works with already published docs versions, so any guidance there would be quite welcome.  Thanks!
Probably doesn't need testing?
=> docs: Convert mentions of `do-not-evict` to `do-not-disrupt`

website/content/en/docs/tasks/managing-amis.md, website/content/en/preview/tasks/managing-amis.md, website/content/en/v1.0/tasks/managing-amis.md, website/content/en/v1.1/tasks/managing-amis.md
Fixes #N/A 
This change updates the `Managing AMIs` task to reflect the v1 API including:
- Providing a high-level recommendation at the top of the doc to pin to a specific version of an AMI using the `alias` field or to pin to `name` or `id` if no such `alias` exists
- Updating statements throughout the doc that `amiFamily` automatically opts you into the latest AMI and that the field is required (this was true before v1, but post-v1, the field is no longer required and you specifically have to use an `alias` with `@latest` to opt-in to get auto-upgraded onto the latest AMI)
- Adding a section on Pod Disruption Budgets when describing AMI upgrade controls (this is another critical measure that needs to be employed to ensure that Karpenter is aware of what "application …
=> docs: Update the Managed AMIs task to reflect the v1 API

designs/interruption-handling.md, website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v0.32/concepts/disruption.md, website/content/en/v0.37/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md, website/content/en/v1.1/concepts/disruption.md
Fixes #N/A 
`graceful-node-shutdown` section does not longer exist on the "Nodes" page, but moved to separate "Node Shutdowns" page
=> docs: fix graceful-node-shutdown url reference

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml
=> Bump sigs.k8s.io/karpenter to latest for release-v0.37.x

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, hack/toolchain.sh, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml
=> Bump sigs.k8s.io/karpenter to latest for release-v0.36.x

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, hack/toolchain.sh, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml
=> Bump sigs.k8s.io/karpenter to latest for release-v0.35.x

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, hack/toolchain.sh, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml
=> Bump sigs.k8s.io/karpenter to latest for release-v0.34.x

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, hack/toolchain.sh, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml
=> Bump sigs.k8s.io/karpenter to latest for release-v0.33.x

pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/suite_test.go
Fixes #N/A 
This change reverts the change in handling for the NodeClass status condition that was introduced in #7625 
=> chore: Revert handling for NodeClaims when NodeClasses are Unknown

go.mod, go.sum, test/suites/integration/subnet_test.go, test/suites/storage/suite_test.go
Fixes #N/A 
This is to bump the go version and upstream version for 1.23.5
make presubmit
=> Chore: Bump go minor version to 1.23.5

pkg/controllers/controllers.go
Fixes #N/A 
When dealing with clusters that generate high volumes of events, the initial cache hydration in controller-runtime creates significant API Server load. This occurs because controller-runtime performs a LIST operation on all historical events during startup.
=> chore: Drop the events controller for v1.2.x 

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, go.mod, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/controllers/controllers.go
Fixes #N/A 
When dealing with clusters that generate high volumes of events, the initial cache hydration in controller-runtime creates significant API Server load. This occurs because controller-runtime performs a LIST operation on all historical events during startup.
=> chore: Drop the events controller for v1.1.x

pkg/controllers/controllers.go
Fixes #N/A 
When dealing with clusters that generate high volumes of events, the initial cache hydration in controller-runtime creates significant API Server load. This occurs because controller-runtime performs a LIST operation on all historical events during startup.
=> chore: Drop the events controller

.github/workflows/e2e-matrix.yaml
Fixes #N/A 
Bumps the pin for the upgrade test to 1.2.0 to ensure 1.32 compatibility.
=> ci: pin upgrade test to v1.2.0

go.mod, go.sum
Fixes #N/A 
- Bump sigs.k8s.io/karpenter to v0.33.12
- N/A
=> chore: Bump sigs.k8s.io/karpenter to v0.35.12

go.mod, go.sum
Fixes #N/A 
- Bump sigs.k8s.io/karpenter to v0.34.13
- N/A
=> chore: Bump sigs.k8s.io/karpenter to v0.34.13

pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/ami_test.go, pkg/controllers/providers/ssm/invalidation/suite_test.go, pkg/fake/ec2api.go, pkg/fake/utils.go, pkg/providers/amifamily/suite_test.go, pkg/providers/amifamily/types.go, pkg/providers/launchtemplate/suite_test.go
Fixes #7652 
Updates the AMI provider to only list AMIs in state `available`.
`make test` and `/karpenter snapshot`
=> fix: only select available AMIs

website/content/en/v1.0/upgrading/v1-migration.md
Fixes #N/A 
Use code format for env variables in upgrade guide
n/a
=> docs: Use code format for env variables in upgrade guide

website/content/en/docs/concepts/nodeclasses.md, website/content/en/docs/faq.md, website/content/en/docs/getting-started/getting-started-with-karpenter/_index.md, website/content/en/v1.2/concepts/nodeclasses.md, website/content/en/v1.2/faq.md, website/content/en/v1.2/getting-started/getting-started-with-karpenter/_index.md, website/hugo.yaml
Fixes #N/A 
Fixes the version ordering in the dropdown selector, and bumps the remaining 1.31 references to 1.32 in the 1.2 docs (including the eksctl version bump).
=> docs: fix version order and remaining 1.32 bumps

pkg/controllers/nodeclass/ami.go, pkg/controllers/nodeclass/controller.go, pkg/providers/amifamily/ami.go
Fixes #N/A 
The SSM invalidation controller uses the AMI provider to periodically check the AMIs provided by SSM parameters for deprecation. To do so, it creates dummy NodeClasses with the AMI IDs discovered from SSM parameters, and passes them to the provider. This causes spurious logging from the AMI providers change monitor, as it keeps discovering new AMIs for the EC2NodeClass with the name `""`:
https://github.com/aws/karpenter-provider-aws/blob/1b2fb34ece6b71b05cb5dc1a1850517d1627a61e/pkg/providers/amifamily/ami.go#L82-L85
Example Logs:
```
karpenter-7d45fc984d-x95n9 controller {"level":"DEBUG","time":"2025-02-05T16:11:25.875Z","logger":"controller","caller":"invalidation/controller.go:74","message":"discovered …
```
=> fix: spurious logging from the ssm invalidation controller

go.mod, go.sum, pkg/providers/instance/instance.go
Fixes #N/A 
We saw an issue where eventual consistency with EC2 can cause the underlying instance to be still around even when cloudProvider.Delete() call is made once against it. To tackle this in this PR, we have updated instance provider delete to check if the instance is terminated.
=> chore: Update instance provider delete to check if the instance is terminated

charts/karpenter/templates/_helpers.tpl, charts/karpenter/templates/deployment.yaml
Fixes #7650
the value `controller.containerName` is supported #7384, but not for relevant env set by downward api.
1. fix the env MEMORY_LIMIT to refer `controller.containerName` if set
2. pull up both container name and env to the helper function
```sh
❯ helm template charts/karpenter --set controller.containerName="custom-name" 2>/dev/null | yq '...comments="" | select(.kind=="Deployment").spec.template.spec.containers[0].env[] | select(.name=="MEMORY_LIMIT")' 
name: MEMORY_LIMIT
valueFrom:
resourceFieldRef:
containerName: custom-name
divisor: "0"
resource: limits.memory
❯ helm template charts/karpenter --set controller.containerName="custom-name" 2>/dev/null | yq '...comments="" | …
```
=> fix(helm):  MEMORY_LIMIT env for custom controller container name 

pkg/controllers/interruption/controller.go, pkg/controllers/interruption/suite_test.go, pkg/operator/operator.go, pkg/test/environment.go
Fixes #N/A 
This change removes the construction of the NodeClaim instanceID map and the Node instanceID map -- this was expensive to construct and was re-constructed on every requeue of the interruption controller. Rather than constructing the mapping this way, we can use a field indexer on instanceID and look-up the NodeClaim and Nodes add-hoc by performing a matchField list query against the internal read cache
=> perf: Remove calling List on NodeClaims and Nodes in interruption controller

go.mod, go.sum, pkg/providers/instance/instance.go
Fixes #N/A 
Add `CreateError` when launch template isn't found so that we ensure that all failures that occur from `launchInstance` return error reasons
=> chore: Add CreateError when launch template isn't found

charts/karpenter/templates/deployment.yaml, charts/karpenter/templates/serviceaccount.yaml
Fixes #N/A
Kubernetes automatically mounts ServiceAccount credentials in each ServiceAccount. The ServiceAccount may be assigned roles allowing Pods to access API resources. Blocking this ability is an extension of the least privilege best practice and should be followed if Pods do not need to speak to the API server to function.
Obviously Karpenter relies on this, so token is mounted to it's pods (set on deployment level).
Custom EKS cluster
=> Restrict auto-mount of service account token in service account

charts/karpenter/templates/serviceaccount.yaml
Fixes #N/A 
Fix a newline issue with the `automountServiceAccountToken` and ensure that we don't add this option when we don't create a serviceAccount
=> chore: Fix automount service account token

website/content/en/docs/concepts/disruption.md
typo fix
> Karpenter will ~~being~~ begin draining the node
=> docs: fix typo in concepts/disruption

pkg/controllers/interruption/controller.go, pkg/controllers/nodeclaim/garbagecollection/controller.go, pkg/controllers/nodeclaim/tagging/controller.go
Fixes #N/A 
We had a few controllers where the `Node` was not logged with `NodeClaim` or vice-versa, which makes it difficult to correlate logs across controllers
=> chore: Ensure that NodeClaim is always logged with Node

Makefile, test/pkg/environment/aws/default_ec2nodeclass.yaml, test/pkg/environment/aws/default_nodepool.yaml
Fixes #N/A 
- Adding support for running `kubernetes-sigs/karpenter` tests: https://github.com/kubernetes-sigs/karpenter/pull/1963
=> test: Add Support for Upstream E2E tests with default AWS Provider EC2NodeClass 

pkg/controllers/nodeclass/ami_test.go, pkg/providers/amifamily/bootstrap/bottlerocketsettings.go, pkg/providers/amifamily/bottlerocket.go, pkg/providers/amifamily/suite_test.go, website/content/en/preview/concepts/nodeclasses.md
Fixes #7596 
This changes allows karpenter to launch Neuron instances (`inf`, `trn` instance types) using the Bottlerocket AMI.
=> Add support for Bottlerocket on Neuron instance types

website/content/en/v1.0/upgrading/v1-migration.md
Adding a note to the upgrade docs for people not using `helm` to upgrade that some manual cleanup of the webhook configuraitons may be necessary.  There are a number of closed issues (e.g. #7134, #6982, #6879) where it seems like people are running into this so seems like maybe a helpful note to have.
Built the docs locally:
=> docs: webhook configurations for upgrade to v1

pkg/controllers/interruption/controller.go
Fixes #N/A 
fixed the logger with "e" instead of "err"
=> chore: Fixed error logger in interruption controller

go.mod, go.sum, website/content/en/preview/getting-started/getting-started-with-karpenter/cloudformation.yaml
Fixes #N/A 
Updates the resources scoping for RunInstances to include capacity reservations and unpins from my fork.
=> fix: update RunInstances permissions for capacity-reservations

cmd/controller/main.go, pkg/cloudprovider/suite_test.go, pkg/controllers/controllers.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/instanceprofile.go, pkg/controllers/nodeclass/readiness.go, pkg/controllers/nodeclass/securitygroup.go, pkg/controllers/nodeclass/subnet.go, pkg/controllers/nodeclass/suite_test.go, pkg/controllers/nodeclass/validation.go, pkg/controllers/nodeclass/validation_test.go, pkg/operator/operator.go, pkg/providers/launchtemplate/suite_test.go, pkg/test/environment.go, pkg/utils/utils.go
Fixes #N/A 
Implements caching for EC2NodeClass validation. Currently, Karpenter will perform the dry-run API calls for each reconciliation of the nodeclass controller. The issue is that this controller has a watch on NodeClaims in addition to NodeClasses, leading to an extremely high call volume. With this change we will cache the result for a minute, reducing call volume. The cache key is based on the nodeclass name and resource version, ensuring we invalidate the cache entry when there's an update to the nodeclass itself.
To reduce the risk of cache related errors (e.g. entering slightly different types into the cache, or the use of different cache key formats), I've split the main reconcile function by auth failure type. These are all called by the main reconcile …
=> fix: cache ec2nodeclass validation state

go.mod, go.sum
Fixes #N/A 
- Update Karpenter to using v1.0.6
- N/A
=> chore: Update Karpenter to v1.0.6

go.mod, go.sum
Fixes #N/A 
- Karpenter tags to v1.2.2
=> chore: Update Karpenter tag to v1.2.2

test/suites/termination/termination_grace_period_test.go
Fixes #N/A 
This change ensures that we don't try to be "so perfect" with our terminationGracePeriod testing where we try to get exactly up to our terminationGracePeriod on the pod. This gives us a 5s buffer so that we won't flake as frequently when it comes to timing
=> ci: Fix flaking in the terminationGracePeriod E2Es

hack/release/common.sh, website/hugo.yaml
Fixes #N/A 
Version dropdown ordering was reversed and was causing `latest` to be marked as `v0.32`
`prepareWebsite`
=> docs: Fix website version dropdown

website/content/en/docs/concepts/nodeclasses.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/v1.3/concepts/nodeclasses.md
Fixes #N/A 
Updates the `capacityReservationSelectorTerm` section of the docs to reference the feature state and link to the feature gates docs.
=> docs: note feature gate for capacity reservations

pkg/controllers/nodeclass/validation.go
Fixes #7834
Ensure that we model our RunInstances request to look like the launch template that we use for launch with CreateFleet. If we don't specify any details about subnet or security group, EC2 will attempt to validate with the user's default VPC -- if the user doesn't have a default VPC, the request will fail (even if the EKS cluster and subnets that they were attempting to launch into weren't associated with the default VPC)
We deleted the default VPCs from regions in our CI accounts -- this ensures that we are testing the bug that happened here. If tests succeed, that's an indication that this is no longer an issue
By submitting this pull request, I confirm …
=> fix: Pass security groups and subnets into RunInstances dry-run

pkg/controllers/nodeclaim/capacityreservation/controller.go
Fixes #7835 
Doesn't return true unless a nodeclaim was demoted from Reserved to OnDemand.
In test cluster
=> fix: spurious logging from capacity reservation controller

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md, website/content/en/v1.1/concepts/disruption.md, website/content/en/v1.2/concepts/disruption.md
Correcting spelling typo
Fixes #N/A 
correcting spelling typo under TerminationGracePeriod section. 
- [] No
=> docs: Update disruption.md - correcting spelling typo

hack/toolchain.sh
Also use sudo only when necessary to create the location
Fixes #N/A
This allows the installation of toolchain files to an arbitrary path by setting the KUBEBUILDER_ASSETS environment variable. This was done in order to avoid the use of sudo in order to create and use a system path. Backward compatibility with the original method is preserved.
I ran make toolchain both with and without setting the KUBEBUILDER_ASSETS environment variable. Without it set, the default location of /usr/local/kubebuilder/bin was used and I was prompted for my password by sudo. With it set to a path under my home directory, the indicated path was created without needing sudo, and all toolchain content was copied into place.
I then ran make test with …
=> chore: Install toolchain files to location provided in KUBEBUILDER_ASSETS if set

pkg/controllers/nodeclass/validation.go, pkg/errors/errors.go
Fixes #N/A 
Fix IAM instance profile eventual consistency error that we are hitting when we have just deployed an IAM instance profile
```
validating ec2:RunInstances authorization, operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: 80dcb2a2-8376-409e-a32c-378314b5799a, api error InvalidParameterValue: Value (consolidation-624112142_14082888993124779028) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
```
=> chore: Fix IAM instance profile eventual consistency error

pkg/cloudprovider/cloudprovider.go, pkg/controllers/nodeclaim/capacityreservation/suite_test.go, pkg/controllers/nodeclaim/garbagecollection/suite_test.go, pkg/controllers/nodeclaim/tagging/suite_test.go, pkg/providers/instance/instance.go, pkg/providers/instance/suite_test.go, pkg/providers/instance/types.go, test/suites/integration/tags_test.go
Fixes #7866 
On 1.3.0 and 1.3.1, Karpenter will initiate drift whenever an instance is launched into an open ODCR when the `ReservedCapacity` flag is set to false. This is due to insufficient gating when generating instances, resulting in a capacity reservation label being added to the node / nodeclaim. This then triggers dynamic drift since the reservation is not resolved by the nodeclass.
Note: this should only impact NodeClaims created after an upgrade to v1.3+. NodeClaims created previously won't have the `karpenter.k8s.aws/capacity-reservation-id` label which is responsible for initiating drift.
- manual testing
- `make test`
By submitting this pull request, I confirm that my contribution is made under …
=> fix: don't drift when launched into open ODCR

website/content/en/docs/contributing/development-guide.md, website/content/en/preview/contributing/development-guide.md, website/content/en/v0.32/contributing/development-guide.md, website/content/en/v1.0/contributing/development-guide.md, website/content/en/v1.1/contributing/development-guide.md, website/content/en/v1.2/contributing/development-guide.md, website/content/en/v1.3/contributing/development-guide.md
Fixes #N/A 
There didn't exist any documentation on how to build images with changes made in https://github.com/kubernetes-sigs/karpenter.
This adds explicit documentation on how to update the `go.mod` file and produce an image with changes made to the karpenter project.
By viewing the generated documenation.
=> docs(contributing): Add section for building custom image

website/hugo.yaml
Fixes #N/A 
The github link on karpenter.sh links to AWS' implementation provider. It should link to the main project. The main project currently contains links to the AWS provider, which is confusing for anyone using karpenter outside of AWS.
- [x ] Yes, PR includes docs updates 
- [] No
=> docs: Github should link to kubernetes sigs karpenter, instead of a provider (AWS)

pkg/cloudprovider/suite_test.go, pkg/controllers/providers/pricing/suite_test.go, pkg/fake/atomic.go, pkg/fake/ec2api.go, pkg/fake/pricingapi.go, pkg/fake/types.go, pkg/providers/instancetype/suite_test.go, pkg/providers/pricing/pricing.go
Fixes #N/A 
Spot pricing information was being incorrectly assigned to the [spotPrices map](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/pricing/pricing.go#L70). This bug was caused by https://github.com/aws/karpenter-provider-aws/pull/7198, specifically on [this line](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/pricing/pricing.go#L377) where we fully override the zonalData from a previous page. This meant that if a previous page had different zones, we wouldn't maintain that zone pricing information and would fully override it.
Practically, this would mean that we would report that certain AZs didn't have spot availability when the API actually did report that there was spot availability there
**How was this change …
=> fix: Fix spot pricing data being overridden when fetched

website/content/en/docs/upgrading/upgrade-guide.md, website/content/en/preview/upgrading/upgrade-guide.md, website/content/en/v0.32/upgrading/upgrade-guide.md, website/content/en/v1.0/upgrading/upgrade-guide.md, website/content/en/v1.1/upgrading/upgrade-guide.md, website/content/en/v1.2/upgrading/upgrade-guide.md, website/content/en/v1.3/upgrading/upgrade-guide.md
Fixes #N/A 
- Add a recommendation to customer to upgrade Karpenter using a pipeline based approach 
- N/A
=> chore: Add docs update to include a note on upgrading Karpenter using a CI/CD pipeline

pkg/cache/cache.go, pkg/controllers/nodeclass/validation.go, pkg/errors/errors.go, pkg/operator/operator.go
=> fix: Handle rate limiting in validation controller

website/content/en/docs/faq.md, website/content/en/preview/faq.md, website/content/en/v0.32/faq.md, website/content/en/v1.0/faq.md, website/content/en/v1.1/faq.md, website/content/en/v1.2/faq.md, website/content/en/v1.3/faq.md
Fixes #7876  
Updated the broken anchor link in faqs.md for cloud provider source.
=> docs: Fix cloud provider anchor link in faq.md

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md, website/content/en/v1.1/concepts/disruption.md, website/content/en/v1.3/concepts/disruption.md
Fixes #N/A 
The anchor link is broken in https://karpenter.sh/docs/concepts/disruption/#node-auto-repair
=> docs: Fix ref on disruption.md

.github/dependabot.yaml
This PR fixes an issue where Dependabot continues to create PRs to update `sigs.k8s.io/karpenter`, despite the `exclude-patterns` configuration in `dependabot.yaml`. 
The `exclude-patterns` directive only applies to dependencies within a defined Dependabot group. However, when Dependabot processes dependencies outside of groups, it treats them as standalone dependencies and continues creating PRs. This is why PRs for `sigs.k8s.io/karpenter` were still being generated.
You can distinguish between grouped and standalone dependency updates by checking the PR titles:
- **Standalone package update (without a group name):**  https://github.com/aws/karpenter-provider-aws/pull/7819/files
- **Grouped package update (with a group name):** …
=> Fix: Properly Ignore sigs.k8s.io/karpenter package in Dependabot

pkg/providers/instancetype/instancetype.go
By allowing the resolver to return nil instance types, we allow implementations to filter instance types by returning nil for instance types which shouldn't be included.
Fixes #N/A 
Enables the instance type resolver to filter instance types by returning a `nil` instance type. Currently, all returned values from the resolver must be non-nil, now a resolver may return nil if it doesn't want to include an instance type in the final set.
=> feat: enable resolver based instance type filtering

go.mod, go.sum, test/pkg/environment/common/expectations.go, test/suites/integration/metrics_test.go
Fixes #N/A 
Add e2etests for validating that a minimum number of metrics are returned back from Karpenter. This would have prevented the regression that was fixed in #7877.
The testing port-forwards the pods and directly hits their metrics endpoints, parsing the metrics, and ensuring the count of metrics is over a certain amount (which is estimated from the number of instance types/subnets that we support).
=> test: Add e2etests for checking metrics

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1/ec2nodeclass.go
Fixes #3643 
Update the CRD description for the KmsKeyID field to indicate all possible values.
Despite what the CRD says, Karpenter passes the value provided to the launch template [here](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/launchtemplate/launchtemplate.go#L370), which according to [`create-launch-template`](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-launch-template.html) is:
> Identifier (key ID, key alias, key ARN, or alias ARN) of the customer managed KMS key to use for EBS encryption.
Documentation only change.
=> doc: Updating CRD description for KmsKeyID to indicate that the field is not limited to ID or ARN

website/content/en/docs/concepts/_index.md, website/content/en/preview/concepts/_index.md, website/content/en/v0.32/concepts/_index.md, website/content/en/v1.0/concepts/_index.md, website/content/en/v1.1/concepts/_index.md, website/content/en/v1.2/concepts/_index.md, website/content/en/v1.3/concepts/_index.md
Fixes #N/A 
Improve clarity in NodePool constraint definition
=> docs: Improve clarity in NodePool constraint definition

pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/subnet_test.go, pkg/fake/ec2api.go, pkg/fake/types.go, pkg/providers/instancetype/suite_test.go, pkg/providers/securitygroup/securitygroup.go, pkg/providers/securitygroup/suite_test.go, pkg/providers/subnet/subnet.go, pkg/providers/subnet/suite_test.go
Fixes #N/A 
Adding pagination for subnets and security groups. I audited the other APIs and there are a couple follow up TODOs after this one:
addressed with `NewDescribeImagesPaginator`
TODO
addressed with `NewDescribeInstancesPaginator` in initial batch executor but not in the second call
addressed with `NewDescribeInstanceTypesPaginator`
Updated in this PR
Updated in this PR
addressed with `NewDescribeCapacityReservationsPaginator`
single describe call - pagination not needed
make presubmit
=> fix: add pagination for subnets and security groups

pkg/controllers/controllers.go, pkg/controllers/interruption/controller.go, pkg/controllers/interruption/suite_test.go, pkg/providers/sqs/sqs.go
Fixes #N/A 
This now allows Karpenter to function if the interruption queue is unavailable. This allows Karpenter to continue to consolidate or provision nodes even when there is an SQS outage.
=> fix: karpenter no longer panics if SQS queue is unavailable

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1/ec2nodeclass.go, pkg/errors/errors.go, pkg/providers/amifamily/ami.go, pkg/providers/amifamily/suite_test.go, pkg/providers/ssm/provider.go, pkg/providers/ssm/types.go, test/suites/ami/suite_test.go, website/content/en/preview/concepts/nodeclasses.md
Fixes #3657 
Adds `ssmParameter` to `amiSelectorTerms` to allow Karpenter to read a custom ssm parameter to get the AMI Image ID.
Karpenter already has ssm parameter IAM permissions and a ssm provider class as it's used to retrieve the public ssm params for alias based amiSelectorTerms.
- `make test`
- tested in an EKS cluster
=> feat: Add support for custom ssm parameters in amiSelectorTerms

charts/karpenter-crd/README.md, charts/karpenter/README.md, charts/karpenter/templates/deployment.yaml, charts/karpenter/values.yaml
Fixes #N/A 
This PR improves the default security context posture and adds support for setting container values which should be user defined.
The Helm chart was templated with the new values.
=> feat(chart): Improved default security context

pkg/cloudprovider/suite_test.go, pkg/controllers/controllers.go, pkg/controllers/nodeclass/controller.go, pkg/controllers/nodeclass/suite_test.go, pkg/controllers/nodeclass/validation.go, pkg/controllers/nodeclass/validation_test.go, pkg/fake/ec2api.go, pkg/providers/launchtemplate/suite_test.go
Fixes #7928 
Updates the validation provider to dynamically resolve compatible instance types for use with RunInstances validation. This ensures we don't perform validation against instance types which may not be allowlisted by the user (e.g. RunInstances permissions are conditional on the instance type). Additionally, when there are multiple compatible instance types we will prioritize launches with non-GPU instance types since the images may require a larger block device than provided.
`make test`(WIP)
=> feat: dynamically select instance types for validation

pkg/cache/unavailableofferings.go, pkg/errors/errors.go, pkg/operator/operator.go, pkg/providers/instance/events.go, pkg/providers/instance/instance.go, pkg/providers/instance/suite_test.go, pkg/test/environment.go
Fixes #N/A 
This change ensures that when we get a `AuthFailure.ServiceLinkedRoleCreationNotPermitted` error code response, we treat this as an ICE error. In general, users that are leveraging spot should enable the SLR before attempting to launch spot capacity, but (if they have not applied the Spot SLR for some reason), this ensures that we still allow on-demand capacity to be launched if the NodePool supports both.
```
"errorSet": {
"item": [
{
"lifecycle": "spot",
"launchTemplateAndOverrides": {
"overrides": {
"subnetId": "subnet-0dc970abd02c2e322",
"imageId": "ami-0e042be748dae7ca0",
"instanceType": "r7a.medium",
"availabilityZone": "us-west-2c"
},
"launchTemplateSpecification": {
"launchTemplateId": "lt-04a55ad0a639804fc",
"version": 1
}
},
"errorMessage": "The …
```
=> ICE spot capacity when there is no permission to create spot SLR

pkg/cloudprovider/cloudprovider.go, pkg/providers/instance/instance.go, pkg/providers/instance/suite_test.go
Fixes #N/A 
Update our debug logging to log when we are filtering out the instance types that we are removing when we are removing them due to being exotic or not having reserved offerings.
```
{"level":"INFO","time":"2025-04-09T01:11:42.759Z","logger":"controller","caller":"provisioning/provisioner.go:364","message":"computed new nodeclaim(s) to fit pod(s)","commit":"7473e53","controller":"provisioner","namespace":"","name":"","reconcileID":"282ce943-daac-48fb-b933-d92290108952","nodeclaims":5,"pods":10}
{"level":"INFO","time":"2025-04-09T01:11:42.777Z","logger":"controller","caller":"provisioning/provisioner.go:152","message":"created nodeclaim","commit":"7473e53","controller":"provisioner","namespace":"","name":"","reconcileID":"282ce943-daac-48fb-b933-d92290108952","Nod …
```
=> chore: Log rejected instance types in Create() path

.github/workflows/e2e.yaml
Fixes #N/A 
The jitter step in GitHub Actions adds unnecessary delay when testing workflows in forked repositories. Removing this step will speed up development and testing cycles while maintaining jitter in main repository workflows.
- N/A
=> ci: Remove jitter step for forked repositories

test/suites/integration/extended_resources_test.go
Fixes #N/A 
- Test: `should provision nodes for a deployment that requests vpc.amazonaws.com/efa`
- We are currently getting ICE for specific instances types that we need to launch (these are OD): https://github.com/aws/karpenter-provider-aws/actions/runs/14842018069/job/41667028013
- This is causing the test to run for 16 min and causing the whole test suite to timeout
- Reducing the resource request should allow Karpenter to send smaller instances type providing CreateFleet with more option when provisioning capacity for the test 
- https://github.com/aws/karpenter-provider-aws/actions/runs/14852340056
- https://github.com/aws/karpenter-provider-aws/actions/runs/14853916174
- …
=> test: Reduce EFA resource requests for a test

.github/workflows/e2e-matrix.yaml, .github/workflows/e2e-private-cluster-trigger.yaml, .github/workflows/e2e-scale-trigger.yaml, .github/workflows/e2e-soak-trigger.yaml, .github/workflows/e2e-upgrade.yaml, .github/workflows/e2e.yaml
Fixes #N/A 
- Now that we have verified that using pick a package with the source field works as expected. Switching all triggers to using a source package 
- Manually tested in a forked repo 
- https://github.com/engedaam/karpenter/actions/runs/14874479614/job/41769116618
- https://github.com/engedaam/karpenter/actions/runs/14874484906
=> chore: Switch All Github Action Triggers to Use a Source repository for E2E tests

pkg/controllers/nodeclass/instanceprofile_test.go, pkg/providers/instanceprofile/instanceprofile.go
Fixes #N/A 
If an ec2nodeclass is deleted and recreated again, the validation controller will requeue reconciliation because the dry run operation will fail to find the instanceProfile. This will cause the validation to remain stuck in unknown and that causes the ec2nodeclass ready stuck in unknown. The instance profile create call succeeds because we get it from the cache causing `InstanceProfileReady` to be in a `True` state. This PR fixes this by ensuring that we delete the instance profile entry from the cache when the nodeClass is deleted.
Added tests. Tested on dev cluster.
=> fix: should delete instanceProfile from cache when nodeclass is deleted

.github/workflows/e2e.yaml
Fixes #N/A 
- All support for running tests in all supported sourced package
- Manually tested in a forked account: https://github.com/engedaam/karpenter/actions/runs/15039143814/job/42266570475
=> ci: Allow all sources to be triggered for E2E tests

.github/workflows/e2e-matrix.yaml, .github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- All support for running tests in all supported sourced package for Upgrade suite
=> ci: Allow `all` sources to be triggered for upgrade E2E tests

charts/karpenter/values.yaml
Just updating the documentation link for the Service Monitor's endpoint configuration.
=> docs: update link for prometheus endpoint documentation

.github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Set integration as the test suite Upgrade E2E workflow 
- N/A
=> ci: Update test suite for upgrade E2E workflow

website/content/en/docs/getting-started/migrating-from-cas/_index.md, website/content/en/preview/getting-started/migrating-from-cas/_index.md, website/content/en/v0.32/getting-started/migrating-from-cas/_index.md, website/content/en/v1.0/getting-started/migrating-from-cas/_index.md, website/content/en/v1.2/getting-started/migrating-from-cas/_index.md, website/content/en/v1.3/getting-started/migrating-from-cas/_index.md, website/content/en/v1.4/getting-started/migrating-from-cas/_index.md
Fixes #8086 
- Update the Karpenter namespace on migrating from Cluster Autoscaler guide
- N/A
=> docs: Update namespace on migrating from Cluster Autoscaler guide

.github/workflows/e2e-upgrade.yaml
Fixes #N/A 
- Drop enabling metrics for upgrade suite causing a panic in the testing environment   
- N/A
=> chore: Fix E2E upgrade suite to avoid testing panic

website/content/en/docs/concepts/nodepools.md, website/content/en/preview/concepts/nodepools.md, website/content/en/v0.32/concepts/nodepools.md, website/content/en/v1.0/concepts/nodepools.md, website/content/en/v1.2/concepts/nodepools.md, website/content/en/v1.3/concepts/nodepools.md, website/content/en/v1.4/concepts/nodepools.md
=> docs: add description when the nodepool limit was not set

pkg/controllers/nodeclass/validation.go, pkg/providers/launchtemplate/launchtemplate.go, pkg/providers/launchtemplate/suite_test.go
Fixes #N/A 
Inject single-value requirements into the userData labels. These labels are already injected back into the NodeClaim when we [`PopulateNodeClaimDetails()`](https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/nodeclaim/lifecycle/launch.go#L122) but they are not passed through the userData today -- only the labels are passed through.
=> chore: Add single-value requirements as labels in userData

pkg/providers/launchtemplate/launchtemplate.go
Fixes #N/A 
Before this, this log would have memory addresses instead of launch template names:
```
karpenter-6dff595756-zzvv6 controller {"level":"DEBUG","time":"2025-05-21T23:23:17.634Z","logger":"controller","caller":"launchtemplate/launchtemplate.go:474","message":"deleted launch templates","commit":"91d8ecc-dirty","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"default-markglimmer-1-fuzbxqsnd0"},"namespace":"","name":"default-markglimmer-1-fuzbxqsnd0","reconcileID":"2fd1ccf4-7f08-4dd8-82b7-5dabad315097","launchTemplates":"karpenter.k8s.aws/12002143131405121058, karpenter.k8s.aws/15295270770572173640, karpenter.k8s.aws/12087419982868941428, karpenter.k8s.aws/10678046093716176425, …
```
=> chore: fix memory addresses in deleting log for launch templates

pkg/providers/version/version.go
Fixes #N/A 
Bumps the maximum supported k8s version to 1.33
Integration tests in a 1.33 cluster
=> chore: bump max k8s version to 1.33

pkg/providers/amifamily/bootstrap/bottlerocketsettings.go
Fixes #N/A 
Bottlerocket v1.39.0 and up adds a setting,
`settings.kubernetes.single-process-oom-kill`, configurable on k8s-1.32+ nodes.
See:
* https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/489
* https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.39.0
`make run` against a test cluster. Testing with valid and invalid values for the new setting. Valid nodeclass.yaml:
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
name: default
spec:
...
amiFamily: Bottlerocket
userData: |
[settings.kubernetes]
"single-process-oom-kill" = true
amiSelectorTerms:
- alias: bottlerocket@v1.39.0
...
```
Inspected the launched node and verified setting is set:
```
[ssm-user@control]$ apiclient get …
```
=> chore: add "single-process-oom-kill" Bottlerocket setting

pkg/operator/operator.go
Fixes #N/A 
Drops the kubelet compatibility annotation check from v1.1
=> chore: drop kubelet compatibility annotation check

website/content/en/docs/concepts/scheduling.md, website/content/en/preview/concepts/scheduling.md, website/content/en/v0.32/concepts/scheduling.md, website/content/en/v1.0/concepts/scheduling.md, website/content/en/v1.3/concepts/scheduling.md, website/content/en/v1.4/concepts/scheduling.md, website/content/en/v1.5/concepts/scheduling.md
Added correct habana device plugin link for kubernetes
Fixes #N/A 
=> Add updated habana plugin link in scheduling.md

kwok/cloudprovider/cloudprovider.go, kwok/ec2/ec2.go, kwok/main.go, kwok/operator/operator.go
Fixes #N/A 
Support 30s delayed registration for launching nodes with the AWS kwok cloudprovider to mock the instance startup time. Eventually, we may be able to extend this to have different launch times based on the instance types
=> feat: Support delayed registration for AWS KWOK

pkg/controllers/nodeclass/ami.go, pkg/providers/amifamily/ami.go, pkg/providers/amifamily/suite_test.go, pkg/providers/amifamily/types.go, pkg/test/environment.go
Fixes #N/A 
This PR insures Karpenter provides a useful error message to customers who are still using alias: al2@* on EKS 1.33+
=> chore: Add error for AL2 with K8s 1.33+ 

pkg/cache/unavailableofferings.go, pkg/errors/errors.go, pkg/providers/instance/instance.go, pkg/providers/instance/suite_test.go
Fixes #N/A 
When CreateFleet returns an `InsufficientFreeAddressesInSubnet` error, we temporarily ICE the AZ in which that subnet resides
=> feat: ICE AZs temporarily when subnets in that AZ run out of available ips

website/content/en/preview/troubleshooting.md, website/content/en/v0.32/troubleshooting.md, website/content/en/v1.0/troubleshooting.md, website/content/en/v1.3/troubleshooting.md, website/content/en/v1.4/troubleshooting.md, website/content/en/v1.5/troubleshooting.md
Adds some useful troubleshooting information to the troubleshooting guide on launching a node. The `offering` is in the error message refers to scheduling requirements such as the availability zone: https://github.com/kubernetes-sigs/karpenter/blob/1b5c30b3299f5ef16ab2a0bb0cd5b1147795f679/pkg/cloudprovider/types.go#L255
- [] No
=> docs: documentation update for instance type scheduling requirements

website/content/en/docs/concepts/nodeclasses.md, website/content/en/preview/concepts/nodeclasses.md, website/content/en/v1.5/concepts/nodeclasses.md
Fixes #8154
Add `volumeInitializationRate` property on https://karpenter.sh/docs/concepts/nodeclasses/#specblockdevicemappings. 
=> docs(website): adding volumeInitializationRate to spec.blockDeviceMappings

.github/actions/e2e/install-karpenter/action.yaml
test: ensure karpenter respects restricted PSS
Fixes #5442
Ensure Karpenter respects the "Restricted" Pod Security Standard when installing in E2E. This is done by checking the output of `install_karpenter.sh` for a pod security warning.
(1) locally by:
- modifying [deployment.yaml](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/templates/deployment.yaml#L67) to `allowPrivilegeEscalation: true`
- create karpenter image & deploying
- confirming grep logic
Example output:
```
if echo "$output" | grep -i "warning.*violate.*podsecurity"; then
echo "ERROR: Karpenter does not respect restricted Pod Security Standard"
fi
"Warning: would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (container …
```
=> test: ensure karpenter respects restricted PSS

kwok/operator/operator.go, pkg/operator/operator.go, pkg/test/environment.go
Fixes #8273 
This PR adds the hydration of instance type caches in `operator.go` before starting other controllers. This removes possible race conditions when other controllers attempt to find instance type info.
`make presubmit` && `/karpenter snapshot`
=> fix: hydrate instance type caches at startup

website/content/en/docs/reference/metrics.md, website/content/en/preview/reference/metrics.md, website/content/en/v1.6/reference/metrics.md
Fixes #N/A 
Metrics were accidentally dropped. Adding them back to the website.
=> fix: Add metrics back for v1.6

website/content/en/docs/concepts/disruption.md, website/content/en/preview/concepts/disruption.md, website/content/en/v1.0/concepts/disruption.md, website/content/en/v1.4/concepts/disruption.md, website/content/en/v1.5/concepts/disruption.md, website/content/en/v1.6/concepts/disruption.md
Fixes #N/A
Adds the default for `spec.disruption.consolidateAfter`. It's mentioned in the text above but not shown in the example.
=> docs: Fix missing disruption.consolidateAfter default

test/suites/integration/extended_resources_test.go
Fixes #N/A 
Removes `g6f` from the gpus selected in our tests to prevent unexpected performance degradation in the tests.
Local e2e
=> fix: remove g6f from gpu int tests

pkg/providers/instancetype/offering/offering.go, pkg/providers/instancetype/suite_test.go
Fixes #N/A 
Ensure that we mark expiring capacity blocks as unavailable. This prevents attempted relaunches into the capacity block during the drain period.
=> fix: mark expiring capacity blocks as unavailable

.github/workflows/codeql-analysis.yaml
This pull request updates the CodeQL workflow to use the newer Actions CodeQL pack instead of the legacy javascript packs that had minimal coverage for GitHub Actions workflows. As part of the pull request, I also updated the version of the CodeQL action to the latest one (https://github.com/github/codeql-action/releases/tag/v3.29.11).
=> ci: Update CodeQL to use actions packs.

.github/actions/install-deps/action.yaml, .github/workflows/codegen.yaml, .github/workflows/dryrun-gen.yaml, .github/workflows/release.yaml, .github/workflows/snapshot.yaml
Fixes #N/A 
Avoid using the install-deps cache on workflows on main that have access to the `id-token` permission
=> ci: Avoid using cache in GHA that have access to id-token on main

test/pkg/environment/common/expectations.go, test/suites/integration/nodeclass_test.go
Fixes #N/A 
Update the disable dry-run test to ensure that we properly wait for IAM to ensure that we have the proper permissions at the end of the test after we remove the role policy that blocks permissions for the dry-run validation to succeed.
Locally testing the "should succeed EC2NodeClass validation when dry run validation is disabled" test with the updated cleanup logic
=> test: Fix flaky disable dry-run test

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/controllers/nodeclass/validation.go
Fixes #N/A 
Add error logging messages when getting anauthorized errors from EC2 APIs for improved visibility
```
karpenter-667c975c47-qf427 controller {"level":"ERROR","time":"2025-08-29T20:55:48.007Z","logger":"controller","caller":"nodeclass/validation.go:257","message":"unauthorized to call ec2:CreateFleet","commit":"aceca23-dirty","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"toucannotch-4-2edbxszfct"},"namespace":"","name":"toucannotch-4-2edbxszfct","reconcileID":"c9db8135-bac1-4c08-a5f3-35786cc203d7","aws-error-code":"UnauthorizedOperation","aws-operation-name":"CreateFleet","aws-request-id":"b60e8bad-3d7d-4206-95e9-7af9f28b1d47","aws-service-name …
```
=> chore: Add error logging message when validation fails due to auth

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/controllers/nodeclass/instanceprofile.go, pkg/providers/instanceprofile/instanceprofile.go, pkg/providers/instanceprofile/suite_test.go
Fixes #N/A 
Allow the role path to be conditionally disabled.
`make test`
=> chore: allow paths to be conditionally disabled

.github/actions/e2e/setup-cluster/action.yaml
Fixes #N/A 
AL2 is no longer supported starting in 1.33 so this updates our ClusterConfig to use AL2023 for our EKS clusters
=> ci: Use AmazonLinux2023 for E2E test clusters

ADOPTERS.md
Cabify adopted Karpenter long time ago, this PR includes it in the ADOPTERS.md
N/A
=> docs: add Cabify to ADOPTERS.md

website/content/en/preview/upgrading/upgrade-guide.md
Fixes #N/A 
Updates the breaking changes in the upgrade guide to account for the following two PRs:
- https://github.com/kubernetes-sigs/karpenter/pull/2349
- https://github.com/kubernetes-sigs/karpenter/pull/2421
docs preview
=> docs: add additional breaking changes to the 1.7 upgrade guide

pkg/controllers/providers/instancetype/capacity/suite_test.go
UTs are failing after merging - https://github.com/kubernetes-sigs/karpenter/pull/2507
```
[FAILED] Expected capacity to match discovered node capacity
Expected
<int64>: 7945060352
to equal
<int64>: 4026531840
In [It] at: /Users/rsumukha/workspace/karpenter/karpenter-provider-aws/pkg/controllers/providers/instancetype/capacity/suite_test.go:192
```
This fixes the UT. 
=> fix: capacitycache UT failing

pkg/providers/instance/filter/filter.go, pkg/providers/instance/filter/filter_test.go
Fixes #8514 
Updates the capacity block filter to verify that offerings are both available and compatible. Although all instance types passed to this filter are guaranteed to be available and compatible, this does not mean that each offering is. This can result in all available offerings being filtered out.
=> fix: ensure filtered offering is available for capacity blocks

website/content/en/preview/concepts/nodeoverlays.md, website/content/en/v1.7/concepts/nodeoverlays.md
Fixes #N/A 
- There looks to be confusion over the semantic meaning of the `or` comment in the requirements for Node Overlay. 
- Removing them for now the show the illustrate the `and` semantic meaning for Node Overlay requirements  
- N/A
=> docs: Remove `OR` comment in the Node Overlay docs

charts/karpenter-crd/templates/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/crds/karpenter.k8s.aws_ec2nodeclasses.yaml, pkg/apis/v1/ec2nodeclass.go, pkg/apis/v1/ec2nodeclass_validation_cel_test.go, pkg/controllers/nodeclass/capacityreservation_test.go, pkg/fake/utils.go, pkg/providers/capacityreservation/types.go, website/content/en/preview/concepts/nodeclasses.md
Fixes #7978 
This change adds support for InstanceMatchCriteria in CapacityReservationSelectorTerms, allowing for the selection of Capacity Reservations by their [matching criteria](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/cr-concepts.html#cr-instance-eligibility)—"open" which accept all instances that have matching attributes, and "targeted" which only accept instances that have matching attributes and explicitly target the Capacity Reservation. 
Updated unit tests, along with manual tests by creating capacity reservations (two `open` and two `targeted`, with one of each having tags and the other having no tags) in my account and selecting them with the NodeClass. 
**Test examples:**
NodeClass configuration:
```yaml
... …
```
=> feat: add support for InstanceMatchCriteria in CapacityReservationSelectorTerms

.golangci.yaml, charts/karpenter-crd/templates/karpenter.sh_nodeclaims.yaml, charts/karpenter-crd/templates/karpenter.sh_nodepools.yaml, go.mod, go.sum, hack/toolchain.sh, pkg/apis/crds/karpenter.sh_nodeclaims.yaml, pkg/apis/crds/karpenter.sh_nodepools.yaml, pkg/cloudprovider/suite_test.go, pkg/controllers/nodeclass/validation.go, pkg/providers/amifamily/al2.go, pkg/providers/amifamily/al2023.go, pkg/providers/amifamily/bootstrap/custom.go, pkg/providers/amifamily/bottlerocket.go, pkg/providers/amifamily/windows.go, pkg/providers/launchtemplate/suite_test.go, test/pkg/debug/node.go, test/pkg/debug/nodeclaim.go, test/pkg/debug/pod.go, test/pkg/environment/aws/expectations.go, test/pkg/environment/aws/metrics.go, test/pkg/environment/aws/setup.go, test/pkg/environment/common/environment.go, test/suites/nodeclaim/garbage_collection_test.go, test/suites/scheduling/suite_test.go
Fixes #N/A 
Bumps the karpenter version to include [this fix](https://github.com/kubernetes-sigs/karpenter/pull/2539). Also upgrades golangci-lint (similar to #8453).
=> chore: Bump karpenter version and upgrade golangci-lint

Makefile, charts/karpenter/values.yaml, test/hack/e2e_scripts/install_karpenter.sh
Currently the CI fails - https://github.com/aws/karpenter-provider-aws/actions/runs/18264656746/job/52179554355
Fixes 
make presubmit and will run CI 
=> fix: failing install_karpenter.sh
